### ISSUE TITLE
Unable to initialize a new environment for amplify

### ISSUE THREAD

**Issue by harsh62** [aws-amplify/amplify-cli#10068]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v17.6.0

### Amplify CLI Version

7.6.26

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

Not applicable

### Amplify Commands

init

### Describe the bug

Unable to initialize a new environment for amplify. See relevant logs below.. I just installed the new version of amplify and did `amplify init`

```
Error: File at path: '/Volumes/workplace/workspaces/amplify/projects/amplify-ios-samples/amplify/backend/backend-config.json' does not exist
```

Also tried uninstalling and installing amplify again. 

### Expected behavior

`amplify init` should be able to initialize a new project. 

### Reproduction steps

1. Install amplify `npm install -g @aws-amplify/cli`
2. run `amplify init`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
2022-03-25T13:37:48.473Z|info : amplify help core  
2022-03-25T13:38:28.566Z|info : amplify init core  
2022-03-25T13:38:28.605Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2022-03-25T13:48:10.692Z|info : amplify init core  
2022-03-25T13:48:10.731Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2022-03-25T13:48:22.774Z|info : amplify init core  
2022-03-25T13:48:22.813Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}

```

</details>

### Additional information

```
➜  amplify-ios-samples git:(main) ✗ amplify init
Note: It is recommended to run this command from the root of your app directory
? Do you want to use an existing environment? No
? Enter a name for the environment dev
Using default provider  awscloudformation
✖ There was an error initializing your environment.
Error: File at path: '/Volumes/workplace/workspaces/amplify/projects/amplify-ios-samples/amplify/backend/backend-config.json' does not exist
    at Function.JSONUtilities.readJson (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/jsonUtilities.ts:25:15)
    at StateManager.getData (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/state-manager/stateManager.ts:399:32)
    at StateManager.getBackendConfig (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/state-manager/stateManager.ts:132:17)
    at populateAmplifyMeta (/opt/homebrew/lib/node_modules/@aws-amplify/cli/src/initialize-env.ts:113:38)
    at initializeEnv (/opt/homebrew/lib/node_modules/@aws-amplify/cli/src/initialize-env.ts:29:7)
    at onSuccess (/opt/homebrew/lib/node_modules/@aws-amplify/cli/src/init-steps/s9-onSuccess.ts:73:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.run (/opt/homebrew/lib/node_modules/@aws-amplify/cli/src/commands/init.ts:30:7)
    at Object.executeAmplifyCommand (/opt/homebrew/lib/node_modules/@aws-amplify/cli/src/index.ts:373:5)
    at executePluginModuleCommand (/opt/homebrew/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:178:3)
    at executeCommand (/opt/homebrew/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:30:5)
    at Object.run (/opt/homebrew/lib/node_modules/@aws-amplify/cli/src/index.ts:205:5)
➜  amplify-ios-samples git:(main) ✗ amplify init
Note: It is recommended to run this command from the root of your app directory
? Do you want to use an existing environment? Yes
? Choose the environment you would like to use: dev
Using default provider  awscloudformation
✖ There was an error initializing your environment.
Error: File at path: '/Volumes/workplace/workspaces/amplify/projects/amplify-ios-samples/amplify/backend/backend-config.json' does not exist
    at Function.JSONUtilities.readJson (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/jsonUtilities.ts:25:15)
    at StateManager.getData (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/state-manager/stateManager.ts:399:32)
    at StateManager.getBackendConfig (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/state-manager/stateManager.ts:132:17)
    at populateAmplifyMeta (/opt/homebrew/lib/node_modules/@aws-amplify/cli/src/initialize-env.ts:113:38)
    at initializeEnv (/opt/homebrew/lib/node_modules/@aws-amplify/cli/src/initialize-env.ts:29:7)
    at onSuccess (/opt/homebrew/lib/node_modules/@aws-amplify/cli/src/init-steps/s9-onSuccess.ts:73:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.run (/opt/homebrew/lib/node_modules/@aws-amplify/cli/src/commands/init.ts:30:7)
    at Object.executeAmplifyCommand (/opt/homebrew/lib/node_modules/@aws-amplify/cli/src/index.ts:373:5)
    at executePluginModuleCommand (/opt/homebrew/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:178:3)
    at executeCommand (/opt/homebrew/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:30:5)
    at Object.run (/opt/homebrew/lib/node_modules/@aws-amplify/cli/src/index.ts:205:5)

```

**Comment by marcvberg** [comment]
So you're not creating a new amplify project correct? You're trying to create a new environment in an existing project? Does the `backend-config.json` file exist or is this error being thrown even though the file is there (I know it may seem like a dumb question but we see it happen that the error gets thrown when the file is locally present)

Do you still see the error show up if you use `amplify env add`?

If you're not creating a new environment in an existing project, does the directory you're in have an `amplify` folder? It could be confusing the CLI if you have part of an amplify project in your directory
