### ISSUE TITLE
Unable to update NoSQL storage

### ISSUE THREAD

**Issue by iyz91** [aws-amplify/amplify-cli#10061]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.14.2

### Amplify CLI Version

7.6.26

### What operating system are you using?

Windows 11

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No.

### Amplify Categories

storage

### Amplify Commands

update

### Describe the bug

Running update on NoSQL dbs in amplify storage throws the error `TypeError: Cannot convert undefined or null to object`. The issue may be that the tables were created to back the API via the CLI, but do not seem to be present in the storage category via the CLI (but are present when referring to them to be able to set permissions on a lambda function through the CLI).

### Expected behavior

You should be able to update NoSQL storage.

### Reproduction steps

1. Run `amplify update auth`
2. Select `NoSQL`

### Log output

<details>

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at updateWalkthrough (C:\Users\*User*\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\@aws-amplify\amplify-category-storage\lib\provider-utils\awscloudformation\service-walkthroughs\dynamoDb-walkthrough.js:62:12)
    at Object.updateResource (C:\Users\*User*\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\@aws-amplify\amplify-category-storage\lib\provider-utils\awscloudformation\index.js:55:12)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.executeAmplifyCommand (C:\Users\*User*\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\@aws-amplify\amplify-category-storage\lib\index.js:172:5)
    at async executePluginModuleCommand (C:\Users\*User*\AppData\Roaming\npm\node_modules\@aws-amplify\cli\lib\execution-manager.js:164:5)
    at async executeCommand (C:\Users\*User*\AppData\Roaming\npm\node_modules\@aws-amplify\cli\lib\execution-manager.js:35:9)
    at async Object.run (C:\Users\*User*\AppData\Roaming\npm\node_modules\@aws-amplify\cli\lib\index.js:162:9)
```

</details>

**Comment by josefaidt** [comment]
Hey @iyz91 :wave: thanks for raising this! I was able to successfully reproduce this error message that's displayed when running `amplify update storage` after adding a GraphQL API. For that issue I will mark this as a bug 🙂 

1. `amplify init -y`
2. `amplify add api` > sample Todo schema
3. `amplify update storage` > NoSQL Database
4. observe unexpected stack trace

```
> amplify update storage
? Select from one of the below mentioned services: NoSQL Database
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at updateWalkthrough (/Users/josef/.fnm/node-versions/v16.13.2/installation/pnpm-global/5/node_modules/.pnpm/@aws-amplify+amplify-category-storage@3.1.21/node_modules/@aws-amplify/amplify-category-storage/lib/provider-utils/awscloudformation/service-walkthroughs/dynamoDb-walkthrough.js:62:12)
    at Object.updateResource (/Users/josef/.fnm/node-versions/v16.13.2/installation/pnpm-global/5/node_modules/.pnpm/@aws-amplify+amplify-category-storage@3.1.21/node_modules/@aws-amplify/amplify-category-storage/lib/provider-utils/awscloudformation/index.js:55:12)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.executeAmplifyCommand (/Users/josef/.fnm/node-versions/v16.13.2/installation/pnpm-global/5/node_modules/.pnpm/@aws-amplify+amplify-category-storage@3.1.21/node_modules/@aws-amplify/amplify-category-storage/lib/index.js:172:5)
    at async executePluginModuleCommand (/Users/josef/.fnm/node-versions/v16.13.2/installation/pnpm-global/5/node_modules/.pnpm/@aws-amplify+cli@7.6.26/node_modules/@aws-amplify/cli/lib/execution-manager.js:164:5)
    at async executeCommand (/Users/josef/.fnm/node-versions/v16.13.2/installation/pnpm-global/5/node_modules/.pnpm/@aws-amplify+cli@7.6.26/node_modules/@aws-amplify/cli/lib/execution-manager.js:35:9)
    at async Object.run (/Users/josef/.fnm/node-versions/v16.13.2/installation/pnpm-global/5/node_modules/.pnpm/@aws-amplify+cli@7.6.26/node_modules/@aws-amplify/cli/lib/index.js:162:9)
🛑 An error occurred when updating the storage resource
```

I'm interested in learning more about the use case for updating the underlying DynamoDB tables. While this action via the `amplify update storage` flow is not supported, perhaps [API overrides](https://docs.amplify.aws/cli/graphql/override/) would be a viable solution?

**Comment by iyz91** [comment]
@josefaidt So the use case was to add a DynamoDB stream trigger with an existing function, but I discovered that this is done via adding a *new* function with a trigger template. In my opinion, while that should be supported, the CLI should undoubtedly support being able to run `amplify update storage` and attach a trigger using an existing function (or create a new one in the same CLI flow). In my case it was not a big deal, I just created the new function, migrated the code and deleted the old one, but for me naturally I would think "I want to add a trigger to this table on item creation, I'm going to update the table via the CLI to attach a lambda trigger to it using a function I already have or create a new one just for this purpose." So overall I guess at this point it would be a feature request.

**Comment by josefaidt** [comment]
Hey @iyz91 that makes perfect sense, and reading your reasoning it seems like an appropriate flow to add a DynamoDB trigger from the `amplify update storage` flow based on the existing flow for adding triggers to s3 storage. For tracking purposes, would you mind filing a separate feature request with that explanation?

**Comment by iyz91** [comment]
@josefaidt Sounds good, will do.
