### ISSUE TITLE
Amplify mock fails to use SSL certificate for postgres connect

### ISSUE THREAD

**Issue by gouthasnm** [aws-amplify/amplify-cli#10099]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.18.3

### Amplify CLI Version

7.6.26

### What operating system are you using?

Amazon Linux

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

None

### Amplify Categories

function

### Amplify Commands

Not applicable

### Describe the bug

amplify mock function fails with 

{
  stack: 'Error: unable to get local issuer certificate\n' +
    '    at TLSSocket.onConnectSecure (_tls_wrap.js:1515:34)\n' +
    '    at TLSSocket.emit (events.js:400:28)\n' +
    '    at TLSSocket.emit (domain.js:475:12)\n' +
    '    at TLSSocket._finishInit (_tls_wrap.js:937:8)\n' +
    '    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:709:12)',
  message: 'unable to get local issuer certificate',
  code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY'
}

### Expected behavior

Should be able to use SSL.

### Reproduction steps

const signerOptions = {
		hostname: DB_HOST,
		region: "us-east-1",
		port: DB_PORT,
		username: DB_USER
	}

	const signer = new AWS.RDS.Signer(signerOptions)

	const token = await signer.getAuthToken();
	const client = await new Client({
		user: DB_USER,
		host: DB_HOST,
		database: 'postgres',
		password: token,
		port: DB_PORT,
		ssl: require
	}).connect();

### GraphQL schema(s)

NA

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

None

**Comment by ykethan** [comment]
Hello @gouthasnm, Thank you for reaching out. I was curious to know, are you currently using a EC2 instance that is configured with the same vpc as the RDS?

Additionally, for the SSL attribute are you currently passing in the pem from you local directory. For example:

`ssl: { ca: fs.readFileSync(__dirname + '/rds-ca-2019-root.pem') },`

I replicated the lambda function with the VPC configuration in my local Amplify application and observed the following.

code used: 

```js
const client = new Client({
     host: "<host>.rds.amazonaws.com",
     user: "<user>",
     database: "postgres",
     password: "<pass>",
     port: 5432,
     ssl: require
   });

await client.connect();
var a =await client.query('SELECT * from COMPANY');
  
console.log("output query", a)
client.end();
```

on performing a function mock I observed a timeout in my CLI output. But on deploying the Lambda function via `amplify push` and invoking the Lambda function on the Lambda console I observed an query output in my Cloudwatch logs.

Could you please provide me some information on your use case and RDS setup, I would be happy in diving deeper.

**Comment by gouthasnm** [comment]
@ykethan Thank you for your response. I am not using EC2. It's a server outside AWS. I eventually ended up passing the file from localhost (similar to what you'd suggested).

the lambda works fine from aws console after its pushed. But it's mock which has issue.

**Comment by ykethan** [comment]
@gouthasnm Thank you for your feedback. Currently, as function mock does not support mocking resources in a VPC, marking this as a feature request.
