### ISSUE TITLE
Host key verification failed

### ISSUE THREAD

**Issue by Sergej-Popov** [aws-amplify/amplify-cli#1010]
Cannot install `aws-amplify/cli`.
Other npm packages are intalling without any issues.

** Which Category is your question related to? **
installation

** Provide additional details e.g. code snippets **
When running ` npm install -g aws-amplify/cli`
I'm getting

```
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t ssh://git@github.com/aws-amplify/cli.git
npm ERR!
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128
```

full log

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\sergej.popov\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'aws-amplify/cli' ]
2 info using npm@6.7.0
3 info using node@v10.13.0
4 verbose npm-session 0e19d40dcf6ea8c8
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for github:aws-amplify/cli Error while executing:
7 silly fetchPackageMetaData C:\Program Files\Git\cmd\git.EXE ls-remote -h -t ssh://git@github.com/aws-amplify/cli.git
7 silly fetchPackageMetaData
7 silly fetchPackageMetaData Host key verification failed.
7 silly fetchPackageMetaData fatal: Could not read from remote repository.
7 silly fetchPackageMetaData
7 silly fetchPackageMetaData Please make sure you have the correct access rights
7 silly fetchPackageMetaData and the repository exists.
7 silly fetchPackageMetaData
7 silly fetchPackageMetaData exited with error code: 128
8 timing stage:rollbackFailedOptional Completed in 2ms
9 timing stage:runTopLevelLifecycles Completed in 4556ms
10 verbose stack Error: exited with error code: 128
10 verbose stack     at ChildProcess.<anonymous> (C:\Users\sergej.popov\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\util\finished.js:12:19)
10 verbose stack     at ChildProcess.emit (events.js:182:13)
10 verbose stack     at maybeClose (internal/child_process.js:962:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
11 verbose cwd C:\dev\private\roots\web
12 verbose Windows_NT 10.0.17134
13 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\sergej.popov\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "aws-amplify/cli"
14 verbose node v10.13.0
15 verbose npm  v6.7.0
16 error Error while executing:
16 error C:\Program Files\Git\cmd\git.EXE ls-remote -h -t ssh://git@github.com/aws-amplify/cli.git
16 error
16 error Host key verification failed.
16 error fatal: Could not read from remote repository.
16 error
16 error Please make sure you have the correct access rights
16 error and the repository exists.
16 error
16 error exited with error code: 128
17 verbose exit [ 1, true ]

```

**Comment by kaustavghosh06** [comment]
@Sergej-Popov Seems like an npm or network connectivity issue. Are you able to install any other packages through npm?

**Comment by UnleashedMind** [comment]
seems like you forgot to put the `@` in front of the aws-amplify/cli
the correct command is 'npm install -g @aws-amplify/cli`.

**Comment by UnleashedMind** [comment]
Closing this issue.
Please open a new issue to let us know if you encounter other problems during installation.

**Comment by Sergej-Popov** [comment]
oh, yes You are right, silly mistake, thank you!
