### ISSUE TITLE
Cannot add Lambda fn due to cyclic dependency with S3 storage

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#10278]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.17.6

### Amplify CLI Version

8.0.2

### What operating system are you using?

mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no

### Amplify Categories

storage, function

### Amplify Commands

update

### Describe the bug

I added an S3 Trigger from my storage category to a new lambda function. 

I then gave read access to the lambda to the same storage category, and I got a cyclic dependency error, but amplify still did some changes and everything seems to be working correctly. 

### Expected behavior

No error when giving lambda read access to storage category that has trigger to the same lambda. 

### Reproduction steps

1. Create lambda fn
2. Setup storage category with a trigger to that lambda fn
3. Then do the following: 

```
hisham@mb3 ess-app % amplify update function
? Select which capability you want to update: Lambda function (serverless function)
? Select the Lambda function you want to update EssS3TriggerFn
General information
- Name: EssS3TriggerFn
- Runtime: nodejs

Resource access permission
- Not configured

Scheduled recurring invocation
- Not configured

Lambda layers
- essappCliLambdaLayer

Environment variables:
- Not configured

Secrets configuration
- Not configured

? Which setting do you want to update? Resource access permissions
? Select the categories you want this function to have access to. storage
? Storage has 8 resources in this project. Select the one you would like your Lambda to access EssUsersS3
? Select the operations you want to permit on EssUsersS3 read

You can access the following resource attributes as environment variables from your Lambda function
	STORAGE_ESSUSERSS3_BUCKETNAME
Error: Cannot add EssS3TriggerFn due to a cyclic dependency
    at checkForCyclicDependencies (/snapshot/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/update-amplify-meta.js:246:15)
    at AmplifyToolkit.updateamplifyMetaAfterResourceUpdate [as _updateamplifyMetaAfterResourceUpdate] (/snapshot/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/update-amplify-meta.js:154:9)
    at updateFunctionResource (/snapshot/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/index.js:157:29)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Object.executeAmplifyCommand (/snapshot/node_modules/amplify-category-function/lib/index.js:262:5)
    at executePluginModuleCommand (/snapshot/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:142:5)
    at executeCommand (/snapshot/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:40:9)
    at Object.run (/snapshot/node_modules/@aws-amplify/cli-internal/lib/index.js:160:9)
```

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by hisham** [comment]
Actually the value for the environment variable added is incorrect: 

<img width="618" alt="EssS3TriggerFn-hishamdev - Lambda 2022-04-22 19-18-19" src="https://user-images.githubusercontent.com/81853/164851938-e056da7a-fe1c-406f-92c3-985941a24b56.png">

**Comment by hisham** [comment]
https://github.com/aws-amplify/amplify-cli/issues/8229 mentions a feature flag to break circular dependency (https://docs.amplify.aws/cli/reference/feature-flags/#configuration), but it seems to only apply for auth?

**Comment by hisham** [comment]
This is also relevant but does not cover adding the s3 bucket name as an env variable: https://github.com/aws-amplify/amplify-cli/issues/6526

**Comment by josefaidt** [comment]
Hey @hisham :wave: I was able to successfully reproduce this issue using the provided steps, thank you for those details! As you mentioned it does appear to add the appropriate permissions to the function CloudFormation template, however does not add the `dependsOn` nor does the resource access permissions carry to subsequent `amplify update function` executions:

```
> amplify update function
? Select the Lambda function you want to update S3Trigger7008eb43
General information
- Name: S3Trigger7008eb43
- Runtime: nodejs

Resource access permission
- Not configured

Scheduled recurring invocation
- Not configured

Lambda layers
- Not configured

Environment variables:
- Not configured

Secrets configuration
- Not configured

? Which setting do you want to update? (Use arrow keys)
❯ Resource access permissions 
  Scheduled recurring invocation 
  Lambda layers configuration 
  Environment variables configuration 
  Secret values configuration 
```

Finally as a note, here is the captured git diff of the failed `... update function` call: https://github.com/josefaidt/10278/commit/d9272b436ea9d06165f214597f9a7e92fe979ca4

Marking as a bug 🙂

**Comment by josefaidt** [comment]
Note, while this workflow is not supported out-of-the-box with cyclic dependencies, there are two pieces of this issue to address here:

1. the error stack trace, and add a useful error message
2. do not modify the function's CloudFormation template on failed update

**Comment by adam-nygate** [comment]
I'm also now suffering from this bug. Any news or a workaround?
