### ISSUE TITLE
appsync api schema.json does not update

### ISSUE THREAD

**Issue by ChhorvornBradley** [aws-amplify/amplify-cli#103]
**Do you want to request a feature or report a bug?**
this is a bug

**What is the current behavior?**

start a graphql appsync from the default
(use the blogs, comments, etc)
`ampfily push`
everything looks good
change the `schema.graphql`
to 

```type Story @model @searchable {
	id: ID!
	description: String!
	text: String!
	points: Int
	votes: [Vote] @connection(name: "StoryVotes")
}

type Vote @model {
	user: String!
	storyPoints: Int!
	story: Story @connection(name: "StoryVotes")
}
```

and save and `amplify push` and file remains the same

now create a graphql schema file in the app (I'm in angular so I have placed this in assets)
```
mutation Vote{
  createVote(input: { user:"bradley!", storyPoints:13, 
    voteStoryId:"3bc7a14e-ee44-4cd7-8b17-fc164081836c"})
  {
    storyPoints
    user
  
    story{
      description
      text
      id
    }
  }
}

query Stories{
  listStorys{
    items{
      id
      text
      description
      votes{
        items{
          user
          storyPoints
        }
      }
    }
  }
}```

run `amplify codegen generate`
and it fails looking for the blog stuff

```amplify codegen generate                       
⠋ Generating..././assets/schema.graphql: Cannot query field "createVote" on type "Mutation". Did you mean "createPost", "createBlog", or "createComment"?
..././assets/schema.graphql: Cannot query field "listStorys" on type "Query". Did you mean "listBlogs" or "listPosts"?
/home/ec2-user/.nvm/versions/node/v8.11.4/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/index.js:13```

**Steps to reproduce the issue:**

1. see above

**What is the expected behavior?**
I expect the backend and the 'current backend' to actually show what has been been posted by appsync and allow me to `amplify codegen generate`


**Additional environment details**
running this in AWS Cloud9

* **OS version (ie Windows 10 build X, macOS Sierra 10.12.6, etc.)**  AWS Cloud9* **Output of ``amplify --version``**: 0.1.16
* **Did this work in previous versions?**: ??

**Comment by yuth** [comment]
amplify codegen reuses the already downloaded introspection schema. If the schema is changed and if you want to force download it, use `amplify codegen generate --download`

**Comment by ChhorvornBradley** [comment]
okay, ran that, it did not change **schema.json** file and ended in error

```
 amplify codegen generate --download
✔ Downloaded the schema
⠋ Generating.../api/pinion/build/schema.graphql: Directive "aws_subscribe" may not be used on FIELD_DEFINITION.
.../api/***/build/schema.graphql: Directive "aws_subscribe" may not be used on FIELD_DEFINITION.
.../api/***/build/schema.graphql: Directive "aws_subscribe" may not be used on FIELD_DEFINITION.
.../api/***/build/schema.graphql: Directive "aws_subscribe" may not be used on FIELD_DEFINITION.
.../api/***/build/schema.graphql: Directive "aws_subscribe" may not be used on FIELD_DEFINITION.
.../api/**/build/schema.graphql: Directive "aws_subscribe" may not be used on FIELD_DEFINITION.
...
.../backend/api/***/schema.graphql: Unknown directive "model".
.../backend/api/***/schema.graphql: Unknown directive "searchable".
.../backend/api/***/schema.graphql: Unknown directive "connection".
.../backend/api/***/schema.graphql: Unknown directive "model".
.../backend/api/***/schema.graphql: Unknown directive "connection".

2018-09-05T19:13:32.053Z - error: uncaughtException: Validation of GraphQL query document failed date=Wed Sep 05 2018 19:13:32 GMT+0000 (UTC), pid=4042, uid=500, gid=500, cwd=/home/ec2-user/environment/src/pinion, execPath=/home/ec2-user/.nvm/versions/node/v8.11.4/bin/node, version=v8.11.4, argv=[/home/ec2-user/.nvm/versions/node/v8.11.4/bin/node, /home/ec2-user/.nvm/versions/node/v8.11.4/bin/amplify, codegen, generate, --download], rss=142778368, heapTotal=109301760, heapUsed=72053736, external=291751, loadavg=[0.19482421875, 0.08837890625, 0.029296875], uptime=115, trace=[column=11, file=/home/ec2-user/.nvm/versions/node/v8.11.4/lib/node_modules/@aws-amplify/cli/node_modules/aws-appsync-codegen/src/validation.ts, function=Object.validateQueryDocument, line=29, method=validateQueryDocument, native=false, column=3, file=/home/ec2-user/.nvm/versions/node/v8.11.4/lib/node_modules/@aws-amplify/cli/node_modules/aws-appsync-codegen/src/generate.ts, function=Object.generate, line=35, method=generate, native=false, column=22, file=/home/ec2-user/.nvm/versions/node/v8.11.4/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/index.js, function=projects.forEach, line=43, method=forEach, native=false, column=null, file=null, function=null, line=null, method=null, native=false, column=7, file=internal/process/next_tick.js, function=process._tickDomainCallback, line=228, method=_tickDomainCallback, native=false], stack=[ToolError: Validation of GraphQL query document failed,     at Object.validateQueryDocument (/home/ec2-user/.nvm/versions/node/v8.11.4/lib/node_modules/@aws-amplify/cli/node_modules/aws-appsync-codegen/src/validation.ts:29:11),     at Object.generate (/home/ec2-user/.nvm/versions/node/v8.11.4/lib/node_modules/@aws-amplify/cli/node_modules/aws-appsync-codegen/src/generate.ts:35:3),     at projects.forEach (/home/ec2-user/.nvm/versions/node/v8.11.4/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/index.js:43:22),     at <anonymous>,     at process._tickDomainCallback (internal/process/next_tick.js:228:7)]

```

**Comment by yuth** [comment]
Could  you share the contents of  `.graphqlconfig.yml` in the root of your project

**Comment by ChhorvornBradley** [comment]
Here you go:
```
pinion:
  schemaPath: amplify/backend/api/pinion/schema.json
  includes:
    - ./**/*.graphql
  excludes:
    - amplify/**
  extensions:
    amplify:
      graphQLApiId: *****hidden*****
      codeGenTarget: typescript
      generatedFileName: API.ts
```

**Comment by yuth** [comment]
#121 should fix this error. With this change, the exclude path is explicit and the schema.graphql won't be used by the codegen

**Comment by skc18** [comment]
@yuth I'm not able to find my .graphqlconfig.yml in the root. The project is in Desktop. Any idea? Thanks

**Comment by yuth** [comment]
@skc18 It should be in your project root if you have codegen configured. Since the file starts with `.` it might be hidden in your file manager, but you should be able to open in using the text editor
