### ISSUE TITLE
Support ES import when amplify mock function

### ISSUE THREAD

**Issue by bc4253** [aws-amplify/amplify-cli#10432]
### Is this feature request related to a new or existing Amplify category?

function

### Describe the feature you'd like to request

Similar to issue: https://github.com/aws-amplify/amplify-cli/issues/5691 support for import when mocking a function locally.

### Describe the solution you'd like

Either support ES import by default or support adding "type": "module" to package.json for amplify functions when testing with amplify mock function <myFunctionName>

### Describe alternatives you've considered

currently the only alternative is to require modules

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by josefaidt** [comment]
Hey @bc4253 :wave: thanks for taking the time to file this! I've marked this as a feature request for the team to evaluate further 🙂

**Comment by kriti-eco** [comment]
this feature request invalidate the steps mentioned in - https://docs.amplify.aws/cli/function/#graphql-from-lambda

 these steps won't work without this feature. so link needs to be updated.

**Comment by kriti-eco** [comment]
I'm trying to follow steps mentioned here - https://docs.amplify.aws/cli/function/#graphql-from-lambda to call GraphQL API from lambda.
As soon as I add "type": "module" to package.json , it starts throwing an error on amplify mock command. As per above link I need to import node-fetch but I'm not able to do it. Lambda code is just a hello-world code as of now, just changing package.json starts creating this problem.

stack: 'Error: Could not load lambda handler function due to Error [ERR_REQUIRE_ESM]: Must use import to load ES Module

**Comment by alexburciu** [comment]
The docs should also show how to run the function to try the GraphQL API (with and without amplify mock).

**Comment by ChrisColemanEH** [comment]
Using commonjs was causing headaches for me.

I have come up with a workaround using Typescript.  I am posting my retrospective notes here in hopes it helps others get around this issue if they are willing to use Typescript to solve it or are already using Typescript.

in amplify project root package.json I added to `"scripts"`
```
    "amplify:myFunctionName": "cd amplify/backend/function/myFunctionName/src && tsc"
```

i created this tsconfig.json inside of amplify/backend/function/myFunctionName/src
```
{
    "compilerOptions": {
      "target": "ES2017",
      "module": "commonjs",

      /* seems like what allows us to use ESM */
      "esModuleInterop": true,
      /* allow use of import AWS from 'aws-sdk' instead of import * as AWS from 'aws-sdk' */
      "allowSyntheticDefaultImports": true,
      
      /* other stuff I am not sure I even need */
      "moduleResolution": "node",
      "rootDir": "./",
      "baseUrl": "./",
      "lib": ["es2017", "dom"],
      "typeRoots": ["node_modules/@types"],
      "declaration": false,
      "strict": true,
      "noImplicitAny": true,
    },
    "include": ["."],
    "exclude": ["node_modules", "**/*.spec.ts"]
  }
```

In hindsight I am not sure what bits of this tsconfig I can leave out otherwise, however, the commented 2 lines allow me to use ES Module pattern in typescript while the output uses CommonJS that is supported by the errant node14 that Mock seems to use (see https://github.com/aws-amplify/amplify-cli/issues/10940)

now in index.tsx I can use normal import statements
```
import AWS from "aws-sdk";
import { v4 as uuid4 } from "uuid";
```

and in other ts files in that same directory I can use normal module pattern exports
```
export const foo = () => {}
```

I am sure my tsconfig file can be improved, but overall this has made a huge difference for me to be able to use ESM

**Comment by alex-griffiths** [comment]
I'm running into some similar issues trying to mock lambda functions using TypeScript. As a minimal example, I can create a function using `amplify function add` called testfunc. Then changing the `index.js` to an `index.mts` to get my TypeScript file.

I add `'type': 'module'` to my `package.json` and use the following `tsconfig.json`

```json
{
    "compilerOptions": {
        "target": "ES2020", /* Set the JavaScript language version for emitted JavaScript and include compatible library declarations. */
        "rootDir": "./", /* Specify the root folder within your source files. */
        "moduleResolution": "node", /* Specify how TypeScript looks up a file from a given module specifier. */
        "sourceMap": false, /* Create source map files for emitted JavaScript files. */
        "noEmit": false, /* Disable emitting files from a compilation. */
        "preserveConstEnums": true, /* Disable erasing 'const enum' declarations in generated code. */
        "isolatedModules": true, /* Ensure that each file can be safely transpiled without relying on other imports. */
        "allowSyntheticDefaultImports": true, /* Allow 'import x from y' when a module doesn't have a default export. */
        "esModuleInterop": true, /* Emit additional JavaScript to ease support for importing CommonJS modules. This enables 'allowSyntheticDefaultImports' for type compatibility. */
        "forceConsistentCasingInFileNames": true, /* Ensure that casing is correct in imports. */
        "strict": true, /* Enable all strict type-checking options. */
        "skipLibCheck": true /* Skip type checking all .d.ts files. */
    },
}
```

(I have used a `tsconfig.json` similar to the one @ChrisColemanEH suggested, however without `esModuleInterop` and `allowSyntheticDefaultImports` and had the same result)

Compiling this with `tsc` gives me my `index.mjs` file as expected, which looks like:

```js
/**
 * @type {import('@types/aws-lambda').APIGatewayProxyHandler}
 */
export const handler = async (event) => {
    console.log(`EVENT: ${JSON.stringify(event)}`);
    return {
        statusCode: 200,
        //  Uncomment below to enable CORS requests
        //  headers: {
        //      "Access-Control-Allow-Origin": "*",
        //      "Access-Control-Allow-Headers": "*"
        //  }, 
        body: JSON.stringify('Hello from Lambda!'),
    };
};
```

When I run `amplify mock function testfunc` I get the following output:

```
Starting execution...
testfunc failed with the following error:
{
  stack: "Error: Could not load lambda handler function due to Error: Cannot find module 'C:\\path\\to\\code\\amplify\\backend\\function\\testfunc\\src\\index'\n" +
    'Require stack:\n' +
    '- C:\\snapshot\\repo\\build\\node_modules\\amplify-nodejs-function-runtime-provider\\lib\\utils\\execute.js\n' +
    '    at loadHandler (C:\\snapshot\\repo\\build\\node_modules\\amplify-nodejs-function-runtime-provider\\lib\\utils\\execute.js:106:15)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n' +
    '    at async invokeFunction (C:\\snapshot\\repo\\build\\node_modules\\amplify-nodejs-function-runtime-provider\\lib\\utils\\execute.js:61:27)\n' +
    '    at async process.<anonymous> (C:\\snapshot\\repo\\build\\node_modules\\amplify-nodejs-function-runtime-provider\\lib\\utils\\execute.js:32:24)',
  message: "Could not load lambda handler function due to Error: Cannot find module 'C:\\path\\to\\code\\amplify\\backend\\function\\testfunc\\src\\index'\n" +
    'Require stack:\n' +
    '- C:\\snapshot\\repo\\build\\node_modules\\amplify-nodejs-function-runtime-provider\\lib\\utils\\execute.js'
}
Finished execution.
```

Amplify CLI version: `10.5.0`
Local NodeJS version: `16.15.0`
```json
// package.json
{
  "name": "testfunc",
  "version": "2.0.0",
  "description": "Lambda function generated by Amplify",
  "main": "index.mjs",
  "license": "Apache-2.0",
  "type": "module",
  "devDependencies": {
    "@types/aws-lambda": "^8.10.92"
  }
}
```

If I create this function and don't change anything about the generated files (i.e. not converting to TypeScript), mocking the function works fine and I see the response and console output as expected. I also know from experience with some other functions in another project, that running code similar to the example provided by @josefaidt by using ESM instead of CJS will run correctly on AWS, though I have not tried mocking those functions.

**Comment by AsemK** [comment]
+1
I hope this gets fixed soon.

**Comment by erikash** [comment]
Maybe it could help others facing the same issue:
Personally I just stopped using `amplify mock function` and just use `ts-node` to run my function directly and it just works :)

**Comment by joyacv2** [comment]
Hi, needs to be fixed, please

**Comment by unknown1337** [comment]
would be really helpfull...

**Comment by wheresthecode** [comment]
I think this is a bug and not a feature request. If you use the "amplify add function" along with the graphQL template it will generate a .js file that uses ES imports. That stock template does not work for amplify mock.

**Comment by scherrer** [comment]
Agreed, this should be classified as a bug. The template/boilerplate examples cannot be run using the mock functionality.

**Comment by johnemcbride** [comment]
plz fix

**Comment by raphipaffi** [comment]
Suffering from the same bug. Currently, I need to push any change to my lambda to test it on AWS. Here is the output from `amplify mock function`:

```
geocodeandaddclient failed with the following error:
{
  stack: 'Error: Could not load lambda handler function due to Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/raphael/Projects/route-planner/amplify/backend/function/geocodeandaddclient/src/index.js\n' +
    'require() of ES modules is not supported.\n' +
    'require() of /Users/raphael/Projects/route-planner/amplify/backend/function/geocodeandaddclient/src/index.js from /snapshot/repo/build/node_modules/amplify-nodejs-function-runtime-provider/lib/utils/execute.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.\n' +
    'Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/raphael/Projects/route-planner/amplify/backend/function/geocodeandaddclient/src/package.json.\n' +
    '\n' +
    '    at loadHandler (/snapshot/repo/build/node_modules/amplify-nodejs-function-runtime-provider/lib/utils/execute.js:106:15)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n' +
    '    at async invokeFunction (/snapshot/repo/build/node_modules/amplify-nodejs-function-runtime-provider/lib/utils/execute.js:61:27)\n' +
    '    at async process.<anonymous> (/snapshot/repo/build/node_modules/amplify-nodejs-function-runtime-provider/lib/utils/execute.js:32:24)',
  message: 'Could not load lambda handler function due to Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/raphael/Projects/route-planner/amplify/backend/function/geocodeandaddclient/src/index.js\n' +
    'require() of ES modules is not supported.\n' +
    'require() of /Users/raphael/Projects/route-planner/amplify/backend/function/geocodeandaddclient/src/index.js from /snapshot/repo/build/node_modules/amplify-nodejs-function-runtime-provider/lib/utils/execute.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.\n' +
    'Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/raphael/Projects/route-planner/amplify/backend/function/geocodeandaddclient/src/package.json.\n'
}
Finished execution.
```

**Comment by hackmajoris** [comment]
@josefaidt I think that the support of AWS JavaScript SDK v3 should be prioritised for Amplify CLI.

**Comment by scherrer** [comment]
please fix this bug. It slows development so much.

**Comment by johnemcbride** [comment]
wen fix?

**Comment by fvisticot** [comment]
any update ? would be really useful to speed up devs !

**Comment by skjortan23** [comment]
Yes just starting a new project and getting the exact same error. Having working local mock functionality for generated code should be a mimimum.

Might have to take the advice in the thread and do a .ts config etc. 

But this is a functionality bug as i see it as well.

**Comment by skjortan23** [comment]
For people having the same issue here. Mocking of typescript functions does not seem to work. However they seem to run with amplify push. 

So the workaround is as mentions above by @erikash is to just test locally with `ts-node`.

**Comment by mamoru77** [comment]
+1
I also hope the issue gets resolved.

**Comment by peter-iglaev** [comment]
any updates?

AWS Developers, you must to respect your users. say smth!

**Comment by vorant94** [comment]
> any updates?
> 
> AWS Developers, you must to respect your users. say smth!

nope, they would better rewrite the whole project structure and call it "Next gen dev experience" rather than fix things that developers face once they make one step out from the way the product works out of the box

**Comment by hackmajoris** [comment]
They always seems to put marketing over everything else.

**Comment by adrianpunkt** [comment]
Sadly, amplify is good only for todo tasks kind of projects, anything more serious than that is a waste of time and money. Been there, done that, I'd recommend staying away from it under any circumstance if your intention is to use it for business.

**Comment by cjsilva-umich** [comment]
Could anyone from the aws team comment on this? How can you all let issues like this go for so long?

**Comment by wac-eric** [comment]
Still waiting on this bug to be resolved as well. For now, I'm testing by pushing it to cloud and checking it on the lambda online...

**Comment by hackmajoris** [comment]
Just to note: using Lambda Layers for Amplify function will also break the mock functionality. It's clear that it's not really an Amplify problem. It's a generic one.

**Comment by vorant94** [comment]
> Just to note: using Lambda Layers for Amplify functions will also break the mock functionality.

If you use TypeScript you can workaround sharing code without Lambda Layers with the help of multiple root dirs inside your `tsconfig.json`

here is the post about it https://www.vorant94.io/posts/aws-amplify-functions-on-steroids#sharing-code-between-lambdas

and here is the repo with example https://github.com/vorant94/amplify-functions-on-steroids

**Comment by hackmajoris** [comment]
> > Just to note: using Lambda Layers for Amplify functions will also break the mock functionality.
> 
> If you use TypeScript you can workaround sharing code without Lambda Layers with the help of multiple root dirs inside your `tsconfig.json`
> 
> here is the post about it https://www.vorant94.io/posts/aws-amplify-functions-on-steroids#sharing-code-between-lambdas
> 
> and here is the repo with example https://github.com/vorant94/amplify-functions-on-steroids

I use Nx libs for this. It's not really the code sharing issue with the Mocking.

**Comment by vorant94** [comment]
> The problem that Lambda Layers solves is deploying all the dependencies once, so that it doesn't require a separate build or dependency installation for each Lambda.

yeah, that’s why u called it workaround)

> I also remember that Amplify has a size limit per Function, and deploying everything without Lambda dependencies was a problem.

Interesting… I remember this limit to be on Lambda side, not Amplify. And this limit is actually pretty high, I played with it and put the whole express service with set of basic libraries there without reaching even half of it…

**Comment by hackmajoris** [comment]
> > The problem that Lambda Layers solves is deploying all the dependencies once, so that it doesn't require a separate build or dependency installation for each Lambda.
> 
> yeah, that’s why u called it workaround)
> 
> > I also remember that Amplify has a size limit per Function, and deploying everything without Lambda dependencies was a problem.
> 
> Interesting… I remember this limit to be on Lambda side, not Amplify. And this limit is actually pretty high, I played with it and put the whole express service with set of basic libraries there without reaching even half of it…

The maximum size for a .zip deployment package for Lambda is 250 MB.

**Comment by vorant94** [comment]
> The maximum size for a .zip deployment package for Lambda is 250 MB.

yeah, and if during build process exclude dev dependencies it is more than enough to include fully-fledged express server all more so for some shared typescript code

**Comment by SilverLinings89** [comment]
It is important to note that the [aws-sdk version 2 deprecation has been announced](https://aws.amazon.com/de/blogs/developer/announcing-end-of-support-for-aws-sdk-for-javascript-v2/). The recommended fix is to migrate to v3. v3 uses import. import doesn't work with amplify function mock. Can somebody please clarify how one is supposed to use this now?

**Comment by SilverLinings89** [comment]
@josefaidt Thanks for the clarification, we have the code working that way in our codebase already. My point was more along the lines that the examples/code excerpts in the AWS SDK docs will no longer be compatible/useable in functions that need to use amplify mock (out of the box). There's afaik no clear indication in the docks that using an import will break mock. Considering this chapter, for example: https://docs.amplify.aws/javascript/tools/cli/usage/mock/#function-mock-limitations there are mentions of limitations but this pretty big limitation isn't referenced but might be relevant for newcomers.
