### ISSUE TITLE
Add existing environment from a second AWS account

### ISSUE THREAD

**Issue by chancyk** [aws-amplify/amplify-cli#10464]
**Which Category is your question related to?**
Environment

**Amplify CLI Version**
8.3.0

I am trying to replicate my Amplify environment onto a second machine. I'm running into a problem because my environments (dev and prod) exist in two different AWS accounts, and thus have two different Amplify AppIds. I was able to pull the first environment (dev). If I try `amplify env add` it will create a new environment in my production account, but I want to use an existing environment. If I try `amplify pull --appId <ID> --envName prod` it raises the error `You are currently working in the amplify project with Id <ID>`.

What's proper way to add the second (prod) environment that resides within a separate AWS account?

**Comment by josefaidt** [comment]
Hey @chancyk :wave: thanks for raising this! We should be able to import another environment from a different account using the `amplify env import` command, and for reference be sure to check out our docs for this command https://docs.amplify.aws/cli/teams/commands/#import-an-environment

**Comment by chancyk** [comment]
Thanks, @josefaidt !

I think this worked? The documentation is kind of minimal there about how to do it correctly. I populated the keys provided in the example but it seemed to be missing some things based on my old team-provider-info.json file. I assume you need everything under the `awscloudformation` key, but the other thing is it stubbed out my Lambda functions without their details. After running the `import` command, I just copied the full `team-provider-info.json` to the new machine... so I'll try at a later date to see if it blows up.

**Comment by OperationalFallacy** [comment]
@josefaidt, is there a way to see what properties it is complaining about? 

I copied AWSCLOUDFORMATIONCONFIG from the team-provider-info.json source env

AWS_CONFIG="{\
\"configLevel\":\"project\",\
\"useProfile\":true,\
\"profileName\":\"xxx-sso-dev-amplify\"\
}"

`profileName` should be the destination, or not? 

```
./import_prod.sh
🛑 The environment configuration provided is missing required properties.

Resolution: Add the required properties and try again.
Learn more at: https://docs.amplify.aws/cli/teams/commands/#import-an-environment

EnvironmentConfigurationError: The environment configuration provided is missing required properties.
    at Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/commands/env/import.js:36:19)
    at Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/commands/env.js:52:33)
    at Object.executeAmplifyCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:194:29)
    at process.runNextTicks [as _tickCallback] (node:internal/process/task_queues:60:5)
    at Function.runMain (pkg/prelude/bootstrap.js:1980:13)
    at node:internal/main/run_main_module:23:47
    at async executePluginModuleCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:139:5)
    at async executeCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:37:9)
    at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:121:5)

Session Identifier: 63f1cb7f-d9fe-442a-9661-2ce47e33d589
```
