### ISSUE TITLE
Show friendlier error message when required runtime CLI files are absent

### ISSUE THREAD

**Issue by attilah** [aws-amplify/amplify-cli#1056]
**Describe the bug**
After creating an AppSync project with environment support, git clean -fdx will remove .config/local-env-info.json and amplify/backend/amplify-meta.json as well which results in runtime errors for various amplify commands like amplify push, amplify status

**To Reproduce**
1. git init
2. amplify init (default settings are OK, env name: dev)
3. git add --all
4. amplify status
5. git clean -fdx
6. amplify status

**Expected behavior**
The required files should not be in gitignore, to keep the project functional

**Desktop (please complete the following information):**
 - OS: Irrelevant
 - Amplify CLI Version 1.1.7

Output for step 6:
```
Current Environment: undefined

~/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/index.js:13
    throw up;
    ^

Error: ENOENT: no such file or directory, open '/projects/foobar2/amplify/backend/amplify-meta.json'
    at Object.openSync (fs.js:439:3)
    at Object.readFileSync (fs.js:344:35)
    at getResourceStatus (~/.npm-global/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/resource-status.js:207:37)
    at Object.showResourceTable (~/.npm-global/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/resource-status.js:268:13)
    at Command.run (~/.npm-global/lib/node_modules/@aws-amplify/cli/src/commands/status.js:5:27)
    at Runtime.<anonymous> (~/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/runtime/run.js:90:58)
    at step (~/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/runtime/run.js:32:23)
    at Object.next (~/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/runtime/run.js:13:53)
    at ~/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/runtime/run.js:7:71
    at new Promise (<anonymous>)
```

Output for 'amplify push':

```
Current Environment: undefined
```

Output for 'amplify checkout dev':
```
~/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/index.js:13
    throw up;
    ^

Error: ENOENT: no such file or directory, open '/projects/foobar2/amplify/.config/local-env-info.json'
    at Object.openSync (fs.js:439:3)
    at Object.readFileSync (fs.js:344:35)
    at Command.run (~/.npm-global/lib/node_modules/@aws-amplify/cli/src/commands/env/checkout.js:22:40)
    at Runtime.<anonymous> (~/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/runtime/run.js:90:58)
    at step (~/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/runtime/run.js:32:23)
    at Object.next (~/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/runtime/run.js:13:53)
    at ~/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/runtime/run.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (~/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/runtime/run.js:3:12)
    at Runtime.run (~/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/runtime/run.js:51:12)
```

**Comment by kaustavghosh06** [comment]
After you `git clean -fdx` and get rid of the runtime files required by the CLI to function, you would need to run `amplify init` as the first step.

**Comment by attilah** [comment]
It does not sound really convenient, because if I've machine "A" and "B" or multiple devs with different local paths, then you need to call init after git clean, which is quite a regular thing you are doing during the course of the project.

I think that as environments are project level setting they should be persisted and init should be a one time thing per workspace and git clean should not mess up things, at least this is how everything else out there works.
