### ISSUE TITLE
amplify build failed with AlreadyExistsException (bucket exists)

### ISSUE THREAD

**Issue by kasukur** [aws-amplify/amplify-cli#10579]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:us-east-1:accountId:apps/d2j3vm4n1gru98

### Region

us-east-1

### Amplify Console feature

Backend builds

### Describe the bug

I am trying to deploy an amplify app as per https://webapp.serverlessworkshops.io/staticwebhosting/deploy/ but the build is failing because of an existing bucket. I don't have any buckets with that name. I understand that the buckets are global but not sure how to workaround this

```
2022-02-25T03:31:32.457Z [INFO]: An error occurred when creating the CloudFormation stack
2022-02-25T03:31:32.459Z [WARNING]: ✖ Root stack creation failed
2022-02-25T03:31:32.464Z [INFO]: AlreadyExistsException: Stack [amplify-wildrydes-prod-32220] already exists
                                 at Request.extractError (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/query.js:50:29)
                                 at Request.callListeners (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
                                 at Request.emit (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
                                 at Request.emit (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:686:14)
                                 at Request.transition (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
                                 at AcceptorStateMachine.runTo (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
                                 at /root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
                                 at Request.<anonymous> (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
                                 at Request.<anonymous> (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:688:12)
                                 at Request.callListeners (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
                                 at Request.emit (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
                                 at Request.emit (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:686:14)
                                 at Request.transition (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
                                 at AcceptorStateMachine.runTo (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
                                 at /root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
                                 at Request.<anonymous> (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
                                 at Request.<anonymous> (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:688:12)
                                 at Request.callListeners (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
                                 at callNextListener (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
                                 at IncomingMessage.onEnd (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/event_listeners.js:335:13)
                                 at IncomingMessage.emit (events.js:412:35)
                                 at IncomingMessage.emit (domain.js:475:12)
                                 at endReadableNT (internal/streams/readable.js:1334:12)
                                 at processTicksAndRejections (internal/process/task_queues.js:82:21) {
                                 code: 'AlreadyExistsException',
                                 time: 2022-02-25T03:31:32.456Z,
                                 requestId: '92bb3d71-1610-43c4-a385-54cb25e459cd',
                                 statusCode: 400,
                                 retryable: false,
                                 retryDelay: 81.16703459454344
                                 }
2022-02-25T03:31:32.487Z [ERROR]: !!! Build failed
2022-02-25T03:31:32.487Z [ERROR]: !!! Non-Zero Exit Code detected
2022-02-25T03:31:32.488Z [INFO]: # Starting environment caching...
2022-02-25T03:31:32.488Z [INFO]: # Environment caching completed
Terminating logging...
```

### Expected behavior

Build to complete successfully. 

### Reproduction steps

Deploy the app as per instructions at https://webapp.serverlessworkshops.io/staticwebhosting/deploy/

**Comment by josefaidt** [comment]
Hey @kasukur :wave: apologies for the delay here! Are you still experiencing this issue? @spina-a-d have you also continuously experienced this?

**Comment by josefaidt** [comment]
Hey @kasukur just wanted to follow-up on this one and see if you are still experiencing this issue?

**Comment by kasukur** [comment]
Hey @josefaidt, Sorry for the delay. it's working now. Thank you

**Comment by spina-a-d** [comment]
@josefaidt Yes I have continuously experienced this. I haven't been able to deploy since I originally had this issue and it's very frustrating.  Especially since I have bugs I can't patch.

**Comment by spina-a-d** [comment]
@josefaidt @hloriana I'm pretty sure this issue is not closed. I'm still experiencing this issue and I'm having no way to patch my active bugs in my website. I've patched all dependencies and the amplify cli  is latest locally and in the pipeline and I still can't deploy my project.

**Comment by josefaidt** [comment]
Hey @spina-a-d :wave: apologies for the delay; I missed these mentions. Are you still experiencing this issue? If so, would you mind creating a separate bug report for your occurrence? This way we'll ensure we have the up-to-date context and project information.

**Comment by josefaidt** [comment]
Hey @spina-a-d :wave: are you still experiencing this issue?

**Comment by josefaidt** [comment]
Closing due to inactivity. @spina-a-d if you are still experiencing this please reply back to this thread or open a new issue with a reference here.

**Comment by Themrpie** [comment]
This is still an issue. I just deleted the bucket and it worked, but I think this is a bug.

**Comment by kusiu** [comment]
@josefaidt I cant deploy before created and deleted branches main or master as I got message 
`the branch main already exists for the app`

`amplify env list` does not return main / master branches.
