### ISSUE TITLE
Amplify pull not working after amplify cli upgrade (cli.json does not exist)

### ISSUE THREAD

**Issue by chstrong** [aws-amplify/amplify-cli#10770]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v16.13.1

### Amplify CLI Version

9.1.0

### What operating system are you using?

macOs Monterey Version 12.4 (M1 Chip)

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

Not applicable

### Amplify Commands

pull

### Describe the bug

After running amplify upgrade when trying to pull the repository I get the following error:

```
99thcloud_blog $ amplify pull --appId d1mptt8hqo6wak --envName staging
✔ An unexpected error has occurred, opt in to send an error report to AWS Amplify with non-sensitive project configuration files. Confirm  (y/N) · yes


Learn more at https://docs.amplify.aws/cli/reference/diagnose/

This project has been opted in automatically to share non-sensitive project configuration files. you can opt out by running 'amplify diagnose --auto-send-off'
🛑 File at path: '/Users/chstrong/Development/99thcloud_blog/amplify/cli.json' does not exist
Error: File at path: '/Users/chstrong/Development/99thcloud_blog/amplify/cli.json' does not exist
    at Function.readJson (/snapshot/repo/build/node_modules/amplify-cli-core/lib/jsonUtilities.js:40:19)
    at StateManager.getData (/snapshot/repo/build/node_modules/amplify-cli-core/lib/state-manager/stateManager.js:309:56)
    at StateManager.getCLIJSON (/snapshot/repo/build/node_modules/amplify-cli-core/lib/state-manager/stateManager.js:254:25)
    at DebugConfig.getCLIJson (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/app-config/debug-config.js:31:48)
    at DebugConfig.writeShareProjectConfig (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/app-config/debug-config.js:44:30)
    at DebugConfig.setAndWriteShareProject (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/app-config/debug-config.js:66:14)
    at reportError (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/commands/diagnose.js:55:49)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:168:13)
```

### Expected behavior

No error message when trying to pull the amplify backend code.

### Reproduction steps

1. npx create-next-app 99thcloud_blog
2. cd 99thcloud_blog
3. Create table and authentication in Amplify Studio
4. amplify pull --appId d1mptt8hqo6wak --envName staging

### GraphQL schema(s)

Not pulled yet.

### Log output

This project has been opted in automatically to share non-sensitive project configuration files. you can opt out by running 'amplify diagnose --auto-send-off'
🛑 File at path: '/Users/chstrong/Development/99thcloud_blog/amplify/cli.json' does not exist
Error: File at path: '/Users/chstrong/Development/99thcloud_blog/amplify/cli.json' does not exist
    at Function.readJson (/snapshot/repo/build/node_modules/amplify-cli-core/lib/jsonUtilities.js:40:19)
    at StateManager.getData (/snapshot/repo/build/node_modules/amplify-cli-core/lib/state-manager/stateManager.js:309:56)
    at StateManager.getCLIJSON (/snapshot/repo/build/node_modules/amplify-cli-core/lib/state-manager/stateManager.js:254:25)
    at DebugConfig.getCLIJson (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/app-config/debug-config.js:31:48)
    at DebugConfig.writeShareProjectConfig (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/app-config/debug-config.js:44:30)
    at DebugConfig.setAndWriteShareProject (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/app-config/debug-config.js:66:14)
    at reportError (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/commands/diagnose.js:55:49)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:168:13)

**Comment by chstrong** [comment]
I've reinstalled the next app and then it worked.
