### ISSUE TITLE
"Inaccessible host" on amplify push

### ISSUE THREAD

**Issue by lewisdonovan** [aws-amplify/amplify-cli#10875]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.19.3

### Amplify CLI Version

9.2.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

Not applicable

### Amplify Commands

env, push

### Describe the bug

When I run `amplify push` I get the following error:

```
🛑 An error occurred during the push operation: /
Inaccessible host: `<MY-DEPLOYMENT-BUCKET-NAME>.s3.amazonaws.com' at port `undefined'. This service may not be available in the `us-east-1' region.
```

I created a new env and that produced a similar error:

```
UnknownEndpoint: Inaccessible host: `<NEW-ENV-DEPLOYMENT-BUCKET-NAME>.s3.amazonaws.com' at port `undefined'. This service may not be available in the `us-east-1' region.
    at Request.ENOTFOUND_ERROR (/snapshot/repo/build/node_modules/aws-sdk/lib/event_listeners.js:529:46)
    at Request.callListeners (/snapshot/repo/build/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/snapshot/repo/build/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/snapshot/repo/build/node_modules/aws-sdk/lib/request.js:686:14)
    at error (/snapshot/repo/build/node_modules/aws-sdk/lib/event_listeners.js:361:22)
    at ClientRequest.<anonymous> (/snapshot/repo/build/node_modules/aws-sdk/lib/http/node.js:99:9)
    at ClientRequest.emit (events.js:400:28)
    at ClientRequest.emit (domain.js:475:12)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28)
    at TLSSocket.emit (domain.js:475:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'UnknownEndpoint',
  region: 'us-east-1',
  hostname: '<NEW-ENV-DEPLOYMENT-BUCKET-NAME>.s3.amazonaws.com',
  retryable: true,
  originalError: Error: getaddrinfo ENOTFOUND <NEW-ENV-DEPLOYMENT-BUCKET-NAME>.s3.amazonaws.com
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26) {
    errno: -3008,
    code: 'NetworkingError',
    syscall: 'getaddrinfo',
    hostname: '<NEW-ENV-DEPLOYMENT-BUCKET-NAME>.s3.amazonaws.com',
    region: 'us-east-1',
    retryable: true,
    time: 2022-08-11T08:39:45.708Z
  },
  time: 2022-08-11T08:39:45.708Z
}
```

I've checked in the AWS Console and both buckets exist and look normal in terms of config and contents.

### Expected behavior

Pushing my deployment successfully

### Reproduction steps

This started immediately after an `amplify push` got stuck and was hanging for ages. I'm not sure if it timed out or my computer went to sleep, but it failed to complete anyway. 

When it was hanging, the CLI was saying `"Waiting for DynamoDB indices to be ready"`, that's where it seemed to get stuck. After the push failed, I tried again and looking in the logs I can see the subsequent push got a lot of line entries saying `Throttling: Rate exceeded` so I'm not sure if I've just been rate limited, although it's been well over an hour now and I'm still getting the `Inaccessible host` error.

It kinda seems like my whole project is borked 🤦🏻‍♂️

### GraphQL schema(s)

<details>

```graphql
type User @model(mutations: {create: "createUserGraphQL", update: "updateUserGraphQL"}, subscriptions: null) @auth(
  rules: [
    { allow: groups, groups: ["admins"] },
    { allow: groups, groups: ["fans", "artists"], operations: [create, read] },
    { allow: owner, operations: [update] },
    { allow: private, operations: [read] }
  ]
) {
  id: ID!
  username: String!
  firstName: String
  lastName: String
  bio: String
  picture: String
  isArtist: Boolean @default(value: false)
  darkmode: Boolean @default(value: true)
  isVisible: Boolean @default(value: true)
  isOnline: Boolean @default(value: false)
  lastOnline: AWSDate
}

type Meeting @model(mutations: {create: "createMeetingGraphQL", delete: "deleteMeetingGraphQL"}, subscriptions: null) @auth(
  rules: [
    { allow: groups, groups: ["admins"] },
    { allow: groups, groups: ["artists"], operations: [create] },
    { allow: owner, ownerField: "artistId", operations: [update, delete] },
    { allow: private, operations: [read] }
  ]
) {
  meetingId: String! @primaryKey
  title: String! 
  artistId: String!
  startDate: AWSDateTime!
  data: String!
  roster: [Attendee] @hasMany
}

type Attendee @model(mutations: {create: "createAttendeeGraphQL", delete: "deleteAttendeeGraphQL"}, subscriptions: null) @auth(
  rules: [
    { allow: groups, groups: ["admins", "artists"] },
    { allow: private, operations: [create, read] }
  ]
) {
  attendeeId: String! @primaryKey
  name: String!
  meeting: [Meeting] @belongsTo(fields: ["meetingId"])
}

type Query {
  createChimeMeeting(title: String, name: String, region: String, artistId: String, startDate: AWSDateTime): Response @function(name: "audioRoom-${env}")
  joinChimeMeeting(meetingId: String, name: String, username: String): Response @function(name: "audioRoom-${env}")
  endChimeMeeting(meetingId: String): Response  @function(name: "audioRoom-${env}")
}

type Response {
  statusCode: String!
  headers: String
  body: String
  isBase64Encoded: String
}
```

</details>

### Project Identifier

2b5b69e5fd0322ef942fa061df50b651

### Log output

<details>

```
UnknownEndpoint: Inaccessible host: `amplify-sonxbackend-lewisgql-192003-deployment.s3.amazonaws.com' at port `undefined'. This service may not be available in the `us-east-1' region.
2022-08-11T08:11:53.679Z|info : amplify push core  {"allow-destructive-graphql-schema-updates":true,"yes":false}
2022-08-11T08:11:53.724Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2022-08-11T08:11:54.836Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["default"])
2022-08-11T08:11:54.837Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2022-08-11T08:11:54.837Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["default"])
2022-08-11T08:11:55.293Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["default"])
2022-08-11T08:11:55.293Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2022-08-11T08:11:55.293Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["default"])
2022-08-11T08:11:55.298Z|info : amplify-provider-awscloudformation.aws-s3.deleteDirectory.s3.getAllObjectVersions([{"BucketName":"[***]ify-[***]ckend-[***]sgql-[***]003-[***]ment"}])
2022-08-11T08:11:55.298Z|info : amplify-provider-awscloudformation.aws-s3.getAllObjectKey.s3.listObjectVersions([{"Bucket":"[***]ify-[***]ckend-[***]sgql-[***]003-[***]ment","Prefix":"hooks/"}])
2022-08-11T08:12:38.869Z|info : amplify push core  {"force":true,"yes":false}
2022-08-11T08:12:38.910Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2022-08-11T08:12:39.770Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["default"])
2022-08-11T08:12:39.771Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2022-08-11T08:12:39.771Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["default"])
2022-08-11T08:12:40.076Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["default"])
2022-08-11T08:12:40.076Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2022-08-11T08:12:40.076Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["default"])
2022-08-11T08:12:40.080Z|info : amplify-provider-awscloudformation.aws-s3.deleteDirectory.s3.getAllObjectVersions([{"BucketName":"[***]ify-[***]ckend-[***]sgql-[***]003-[***]ment"}])
2022-08-11T08:12:40.080Z|info : amplify-provider-awscloudformation.aws-s3.getAllObjectKey.s3.listObjectVersions([{"Bucket":"[***]ify-[***]ckend-[***]sgql-[***]003-[***]ment","Prefix":"hooks/"}])
2022-08-11T08:13:16.490Z|info : amplify pull core  {"appId":"[***]j7co1z","envName":"[***]sgql","yes":false}
2022-08-11T08:13:16.530Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2022-08-11T08:13:37.871Z|info : amplify-provider-awscloudformation.amplify-service-permission-check.checkAmplifyServiceIAMPermission.amplifyClient.listApps([])
2022-08-11T08:13:38.319Z|info : amplify-provider-awscloudformation.attach-backend.getAmplifyApp.amplifyClient.getApp([{"appId":"[***]j7co1z"}])
2022-08-11T08:13:38.544Z|info : amplify-provider-awscloudformation.attach-backend.getBackendEnv.amplifyClient.getBackendEnvironment([{"appId":"[***]j7co1z","environmentName":"[***]sgql"}])
2022-08-11T08:13:38.705Z|info : amplify-provider-awscloudformation.attach-backend.downloadBackend.s3.getObject([{"Key":"[***]rent-[***]ud-[***]d.zip","Bucket":"[***]ify-[***]ckend-[***]sgql-[***]003-[***]ment"}])
2022-08-11T08:13:38.844Z|error : amplify-provider-awscloudformation.attach-backend.downloadBackend.s3.getObject([{"Key":"[***]rent-[***]ud-[***]d.zip","Bucket":"[***]ify-[***]ckend-[***]sgql-[***]003-[***]ment"}])
UnknownEndpoint: Inaccessible host: `amplify-sonxbackend-lewisgql-192003-deployment.s3.amazonaws.com' at port `undefined'. This service may not be available in the `us-east-1' region.

```

</details>

**Comment by lewisdonovan** [comment]
Also worth mentioning that I had my VPN on during this push, so may have appeared to be in a different time zone. Potentially a time drift issue, similar to #10103

**Comment by lewisdonovan** [comment]
Yes, this appears to have been a time drift issue. I reconnected my VPN to the same time zone it was in previously and the error no longer appeared. I did get another error message saying:

```
A deployment is in progress.
If the prior rollback was aborted, run:
`amplify push --iterative-rollback` to rollback the prior deployment
`amplify push --force` to re-deploy
```

I ran `amplify push --iterative-rollback` but then got another error about meta keys. In the end the solution was to go into the deployment bucket in the S3 console and delete `deployment-state.json` and then push again. That fix is described [in this reply](https://github.com/aws-amplify/amplify-adminui/issues/172#issuecomment-819784558) to another issue.

The issue I now have is that **I am unable to push unless I am in a specific timezone** and I don't live there, so I have to VPN into it, which seems kinda nuts. Is there any way to solve this? Thanks.

**Comment by ykethan** [comment]
Hey @lewisdonovan, Wanted to see if this behavior also occurs if a amplify application was created when not a VPN. Could you try disabling the VPN, then create a empty folder in a different directory and perform a `amplify init` with a sample resource or pull on a test application. Do let us know if you are seeing similar behavior. if yes, could you check to see if your ISP may be blocking the calls.

**Comment by lewisdonovan** [comment]
> Could you try disabling the VPN, then create a empty folder in a different directory and perform a `amplify init` with a sample resource or pull on a test application.

I tried this ☝️ and it worked fine. But my original issue was with an app I created while not connected to a VPN, it was just a subsequent pull/push while connected to a VPN that caused the issue.

**Comment by ykethan** [comment]
Hey @lewisdonovan, after testing the application in different scenarios and diving deep into the errors. I was able to find the following two issues.

1. when the time/timezone is set different for the amplify application. The amplify push fails with the following error: `The difference between the request time and the current time is too large.`
2. The error `Inaccessible host: <MY-DEPLOYMENT-BUCKET-NAME>.s3.amazonaws.com' at port undefined'` indicates the network is blocking the request. 

to mitigate the issue, could remove the amplify folder and then pull the backend using ` amplify pull --appId <appid> --envName <env name>` when not on a VPN. please do let us know if you are experiencing any issues on doing this.

**Comment by ykethan** [comment]
hey @ykethan, following up on this issue. Please do let us know if you need any assistance.

**Comment by Morrious** [comment]
I'm having this same issue after setting up a new MacBook. It seems like some operations work, but after I try to do an `amplify push`, that fails and then other operations start failing as well. The error is exactly the same: Inaccessible host: `<MY-DEPLOYMENT-BUCKET-NAME>.s3.amazonaws.com' at port `undefined'. This service may not be available in the `us-east-1' region.

I have previously been developing in a docker container on Ubuntu. This operations fails in the same exact docker container, running on MacOS 13.0.1. I think this must be a wifi issue..

**Comment by kolomiiets** [comment]
Had the same issue due to connected VPN. It works fine after I disconnected from the VPN
