### ISSUE TITLE
Amplify pull fails due to incorrect path (looks for file named undefined)

### ISSUE THREAD

**Issue by nsdhillon1** [aws-amplify/amplify-cli#10941]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.17.0

### Amplify CLI Version

9.2.1

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

auth, function, api

### Amplify Commands

pull

### Describe the bug

Created a simple amplify project for our app backend with auth + api.  Then added RDS data source.  This deploys successfully, push and pull work fine.

On a separate flutter project/repo for our app front-end, we are trying to integrate the backend amplify by running the following:
 $ amplify pull --appId <removed_for_privacy> --envName dev

It results in this error: File at path: 'C:\dev\workspaces\git\app1_app\amplify\#current-cloud-backend\awscloudformation\build/undefined' does not exist

✔ Successfully pulled backend environment dev from the cloud.
✖ There was an error initializing your environment.
Failed to pull the backend.
🛑 File at path: 'C:\dev\workspaces\git\app1_app\amplify\#current-cloud-backend\awscloudformation\build/undefined' does not exist
Error: File at path: 'C:\dev\workspaces\git\app1_app\amplify\#current-cloud-backend\awscloudformation\build/undefined' does not exist
    at Function.readJson (C:\snapshot\repo\build\node_modules\amplify-cli-core\lib\jsonUtilities.js:40:19)
    at serviceWalkthrough (C:\snapshot\repo\build\node_modules\@aws-amplify\amplify-category-api\lib\provider-utils\awscloudformation\service-walkthroughs\appSync-rds-walkthrough.js:40:54)
    at Object.addDatasource (C:\snapshot\repo\build\node_modules\@aws-amplify\amplify-category-api\lib\provider-utils\awscloudformation\index.js:285:92)
    at async initEnv (C:\snapshot\repo\build\node_modules\@aws-amplify\amplify-category-api\lib\index.js:157:5)

### Expected behavior

Amplify pull should finish

### Reproduction steps

1. Create amplify project with api and add an existing RDS datasource.  
2. Deploy it successfully
3. Run amplify pull with app id and env id on a second project to connect it to the deployment
4.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Project Identifier

Project id: 0b710c45bea4e664420f1520336f9b88 (this is from the backend project).  The frontend project that is trying to do the amplify pull does not yet have it as amplify pull does not succeed due to this issue

### Log output

<details>

```
# Put your logs below this line
Opening link: https://us-west-2.admin.amplifyapp.com/admin/d2cjx8alzgse62/dev/verify/?loginVersion=1
- Confirm login in the browser or manually paste in your CLI login key:
✔ Successfully received Amplify Studio tokens.
Amplify AppID found: <removed_for_privacy>. Amplify App name is: <removed>
Backend environment dev found in Amplify Console app: app1backend
? Choose your default editor: Visual Studio Code
? Choose the type of app that you're building (Use arrow keys)
? Choose the type of app that you're building flutter
Please tell us about your project
? Where do you want to store your configuration file? ./lib/
? Do you plan on modifying this backend? Yes
/ Fetching updates to backend environment: dev from the cloud.GraphQL schema compiled successfully.

Edit your schema at C:\dev\workspaces\git\app1_app\amplify\backend\api\app1backend\schema.graphql or place .graphql files in a directory at C:\dev\workspaces\git\app1_app\amplify\backend\api\app1backend\schema
✔ Successfully pulled backend environment dev from the cloud.
✖ There was an error initializing your environment.
Failed to pull the backend.
🛑 File at path: 'C:\dev\workspaces\git\app1_app\amplify\#current-cloud-backend\awscloudformation\build/undefined' does not exist
Error: File at path: 'C:\dev\workspaces\git\app1_app\amplify\#current-cloud-backend\awscloudformation\build/undefined' does not exist
    at Function.readJson (C:\snapshot\repo\build\node_modules\amplify-cli-core\lib\jsonUtilities.js:40:19)
    at serviceWalkthrough (C:\snapshot\repo\build\node_modules\@aws-amplify\amplify-category-api\lib\provider-utils\awscloudformation\service-walkthroughs\appSync-rds-walkthrough.js:40:54)
    at Object.addDatasource (C:\snapshot\repo\build\node_modules\@aws-amplify\amplify-category-api\lib\provider-utils\awscloudformation\index.js:285:92)
    at async initEnv (C:\snapshot\repo\build\node_modules\@aws-amplify\amplify-category-api\lib\index.js:157:5)

```

</details>

**Comment by nsdhillon1** [comment]
The cause of the issue is that the filename should be pulled from property rootStackFileName instead of cfnRootStackFileName in amplify-category-api\lib\provider-utils\awscloudformation\service-walkthroughs\appSync-rds-walkthrough.js

It seems unclear, to me at least, where this file lives in a different repo (amplify-category-api).  As such, I am not able to submit a pull request.  


Before Fix:
    const cfnJson = amplify_cli_core_1.JSONUtilities.readJson(`${amplify_cli_core_1.pathManager.getCurrentCloudRootStackDirPath(amplify_cli_core_1.pathManager.findProjectRoot())}/${amplify_provider_awscloudformation_1.cfnRootStackFileName}`);

After Fix:
    const cfnJson = amplify_cli_core_1.JSONUtilities.readJson(`${amplify_cli_core_1.pathManager.getCurrentCloudRootStackDirPath(amplify_cli_core_1.pathManager.findProjectRoot())}/${amplify_provider_awscloudformation_1.rootStackFileName}`);

**Comment by josefaidt** [comment]
Transferring to amplify-category-api as the affected code is there https://github.com/aws-amplify/amplify-category-api/blob/main/packages/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/appSync-rds-walkthrough.ts#L47
