### ISSUE TITLE
Backend ended up in bad state after push fail, preventing pull/clone/delete

### ISSUE THREAD

**Issue by CHURLZ** [aws-amplify/amplify-cli#11004]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

curl

### Amplify CLI Version

10.0.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

I manually removed a Function that failed to push properly. I was already in a bad state, prevented from deleting or cloning my env at this point.

### Amplify Categories

function, api

### Amplify Commands

pull

### Describe the bug

I added a (python) function, which failed to push. I nuked my local environment, but now I can't pull.
I tried to clone and delete the environment in Amplify console, but that fails with the same error:

 Deletion failed ENOENT: no such file or directory, stat '/tmp/amplify-39c6c37e-f948-4742-ab79-80a6db44f708/amplify/.temp/#current-cloud-backend/function/pycodegen/bin/python' at Object.statSync

### Expected behavior

I need to be able to pull the project to restore it, but some bad state prevents all actions.

### Reproduction steps

`amplify pull --appId dlbi7inq03mrd --envName staging`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Project Identifier

unable to run CLI for my project at this point.
App arn: dlbi7inq03mrd

### Log output

<details>

```
# Put your logs below this line
Failed to pull the backend.
🛑 ENOENT: no such file or directory, stat '/Users/churlz/amplify/.temp/#current-cloud-backend/function/pycodegen/bin/python'
Error: ENOENT: no such file or directory, stat '/Users/churlz/amplify/.temp/#current-cloud-backend/function/pycodegen/bin/python'
    at Object.statSync (fs.js:1131:3)
    at Object.statSync (pkg/prelude/bootstrap.js:1345:32)
    at Object.statSync (/snapshot/repo/build/node_modules/graceful-fs/polyfills.js:311:34)
    at getStatsSync (/snapshot/repo/build/node_modules/fs-extra/lib/util/stat.js:58:18)
    at Object.checkPathsSync (/snapshot/repo/build/node_modules/fs-extra/lib/util/stat.js:90:33)
    at copyDirItem (/snapshot/repo/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:119:29)
    at /snapshot/repo/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:39
    at Array.forEach (<anonymous>)
    at copyDir (/snapshot/repo/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:23)
    at mkDirAndCopy (/snapshot/repo/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:108:3)
    at onDir (/snapshot/repo/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:99:25)
    at getStats (/snapshot/repo/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:45:37)
    at startCopy (/snapshot/repo/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
    at copyDirItem (/snapshot/repo/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:120:10)
    at /snapshot/repo/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:39
    at Array.forEach (<anonymous>)
    at copyDir (/snapshot/repo/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:23)
    at mkDirAndCopy (/snapshot/repo/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:108:3)
    at onDir (/snapshot/repo/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:99:25)
    at getStats (/snapshot/repo/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:45:37)
    at startCopy (/snapshot/repo/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
    at copyDirItem (/snapshot/repo/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:120:10)
    at /snapshot/repo/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:39
    at Array.forEach (<anonymous>)
    at copyDir (/snapshot/repo/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:23)
    at mkDirAndCopy (/snapshot/repo/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:108:3)
    at onDir (/snapshot/repo/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:99:25)
    at getStats (/snapshot/repo/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:45:37)
    at startCopy (/snapshot/repo/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
    at copyDirItem (/snapshot/repo/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:120:10)
    at /snapshot/repo/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:39
    at Array.forEach (<anonymous>)
    at copyDir (/snapshot/repo/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:23)
    at onDir (/snapshot/repo/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:103:10)
    at getStats (/snapshot/repo/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:45:37)
    at startCopy (/snapshot/repo/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
    at handleFilterAndCopy (/snapshot/repo/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:33:10)
    at Object.copySync (/snapshot/repo/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:26:10)
    at downloadBackend (/snapshot/repo/build/node_modules/amplify-provider-awscloudformation/lib/attach-backend.js:389:8)
    at async Object.run (/snapshot/repo/build/node_modules/amplify-provider-awscloudformation/lib/attach-backend.js:116:3)
    at async Object.attachBackend (/snapshot/repo/build/node_modules/amplify-provider-awscloudformation/lib/index.js:208:3)
    at async queryProvider (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/attach-backend-steps/a10-queryProvider.js:31:5)
    at async attachBackend (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/attach-backend.js:38:9)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/commands/pull.js:70:9)
    at async Object.executeAmplifyCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:292:9)
    at async executePluginModuleCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:142:5)
    at async executeCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:40:9)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:165:13)

```

</details>

**Comment by josefaidt** [comment]
Hey @CHURLZ :wave: thanks for raising this! How was `.../bin/python` added to the function? This appears similar to a previous issue https://github.com/aws-amplify/amplify-cli/issues/10138#issuecomment-1090572243

Following the steps in this gist should get you back to a working state: https://gist.github.com/josefaidt/a117076b7bea81e1872e275176dbb23c

**Comment by CHURLZ** [comment]
@josefaidt I set up venv, and it started complaining about symlinks, I think that's what blew up.
I ended up creating a new amplify app, so no stress on my end.

**Comment by josefaidt** [comment]
Hey @CHURLZ apologies for the delay! We are actively tracking issues related to function's and symlinks. Closing in favor of tracking existing items
