### ISSUE TITLE
Appsync returns 401 when add Lambda as additional auth mode. Lambda never gets called.

### ISSUE THREAD

**Issue by davidallenmann** [aws-amplify/amplify-cli#11003]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.13.0

### Amplify CLI Version

10.0.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

cli.json changed from false to true (had no effect)
```
"appsync": {
      "generategraphqlpermissions": true
    },
```

### Amplify Categories

auth, function, api

### Amplify Commands

update

### Describe the bug

Appsync returns a 401 when running query from web app. The lambda auth function never gets called.

Cognito User Pools is the default auth provider.

From the AppSync console I can successfully query using Lambda auth and the appropriate authToken.

Web app query function:
```
        const getAuthToken = () => 'custom-authorized';
        const lambdaAuthToken = getAuthToken();
        const queryHits = await API.graphql({
          query: hitBySerialByDate,
          variables: {
            serial: serialClicked,
            dt: { gt: yesterdayDate },
            sortDirection: "DESC",
            nextToken: nextToken,
          },
          authMode: 'AWS_LAMBDA',
          authToken: lambdaAuthToken,
          filter: { wav: { gt: "" } },
        });
```

Lambda function (using generated example)
```

/* Amplify Params - DO NOT EDIT
	API_HAIKUBOXAMPLIFY_GRAPHQLAPIENDPOINTOUTPUT
	API_HAIKUBOXAMPLIFY_GRAPHQLAPIIDOUTPUT
	ENV
	REGION
Amplify Params - DO NOT EDIT */// This is sample code. Please update this to suite your schema

/**
 * @type {import('@types/aws-lambda').APIGatewayProxyHandler}
 */
exports.handler = async (event) => {
  console.log(`EVENT: ${JSON.stringify(event)}`);
  const {
    authorizationToken,
    requestContext: { apiId, accountId },
  } = event;
  const response = {
    isAuthorized: authorizationToken === 'custom-authorized',
    resolverContext: {
      userid: 'user-id',
      info: 'contextual information A',
      more_info: 'contextual information B',
    },
    deniedFields: [
      `arn:aws:appsync:${process.env.AWS_REGION}:${accountId}:apis/${apiId}/types/Event/fields/comments`,
      `Mutation.createEvent`,
    ],
    ttlOverride: 300,
  };
  console.log(`response >`, JSON.stringify(response, null, 2));
  return response;
};
```

### Expected behavior

I expect the query using the authMode: 'AWS_LAMBDA' will run the auth lambda function from my webapp.

### Reproduction steps

This is running on an amplify project created under an earlier version of the amplify cli. Everything works normally after upgrading to v 10.0.0. However, adding the lambda auth additional method causes this AppSync error.

### GraphQL schema(s)

I have tried with and without the:   @aws_lambda @aws_iam @aws_cognito_user_pools

```graphql
type hit
  @aws_lambda @aws_iam @aws_cognito_user_pools
  @model(subscriptions: null)
  @auth(
    rules: [
      { allow: private, provider: iam, operations: [create] }
      { allow: custom }
      { allow: groups, groups: ["Admin"], operations: [create, read, update] }
    ]
  ) {
  id: ID!


```

</details>

### Project Identifier

698d34206ca55439aff506887737f1f1

### Log output

<details>

```
GraphQLError
message
: 
"Request failed with status code 401"
extensions
: 
undefined
locations
: 
undefined
nodes
: 
undefined
originalError
: 
Error: Request failed with status code 401 at createError (webpack-internal:///./node_modules/axios/lib/core/createError.js:16:15) at settle (webpack-internal:///./node_modules/axios/lib/core/settle.js:17:12) at XMLHttpRequest.handleLoad (webpack-internal:///./node_modules/axios/lib/adapters/xhr.js:62:7)
path
: 
undefined
positions
: 
undefined
source
: 
undefined
stack
: 
"Error: Request failed with status code 401\n    at createError (webpack-internal:///./node_modules/axios/lib/core/createError.js:16:15)\n    at settle (webpack-internal:///./node_modules/axios/lib/core/settle.js:17:12)\n    at XMLHttpRequest.handleLoad (webpack-internal:///./node_modules/axios/lib/adapters/xhr.js:62:7)"
[[Prototype]]
: 
Error


```

</details>

**Comment by josefaidt** [comment]
Hey @davidallenmann :wave: thanks for raising this! Do you experience the same issue if you remove the redundant auth directives?

```
@aws_lambda @aws_iam @aws_cognito_user_pools
```
