### ISSUE TITLE
headless pull failing to pull OAuth credentials where regular pull is successful

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/amplify-cli#11010]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

pnpm

### If applicable, what version of Node.js are you using?

v18.7.0

### Amplify CLI Version

10.0.0

### What operating system are you using?

mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

n/a

### Amplify Categories

auth

### Amplify Commands

pull

### Describe the bug

When pulling a project with enabled social providers in the auth resource, headless pull fails ("headless" i.e. using `--yes`).

```
✖ There was an error initializing your environment.
Failed to pull the backend.
🛑 auth headless is missing the following inputParams facebookAppIdUserPool, facebookAppSecretUserPool
Error: auth headless is missing the following inputParams facebookAppIdUserPool, facebookAppSecretUserPool
    at updateConfigOnEnvInit (/snapshot/repo/build/node_modules/@aws-amplify/amplify-category-auth/lib/provider-utils/awscloudformation/index.js:93:23)
    at /snapshot/repo/build/node_modules/@aws-amplify/amplify-category-auth/lib/index.js:278:34
    at /snapshot/repo/build/node_modules/promise-sequential/index.js:16:18
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

### Expected behavior

headless pull with `--yes` should resolve previously inputted social provider credentials

### Reproduction steps

1. `amplify init -y`
2. `amplify add auth` > choose default with Social Providers
3. add some provider such as Facebook with dummy credentials: `fakeappid` and `fakeappsecret`
4. push with `amplify push -y`
5. in a separate, sibling directory, attempt to pull the project
	1. observe `amplify pull --appId d1ukap87uzfkby --envName dev --yes` will fail due to missing paramters
	2. observe `amplify pull --appId d1ukap87uzfkby --envName dev` will function as expected after reselecting project config settings such as AWS profile and frontend framework

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Project Identifier

5af6579a1a37406c0be3c40997d29532

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by lucasoares** [comment]
I updated the CLI and the error message just changed:

```
app › ✔ Successfully pulled backend environment *** from the cloud.
app › ✖ There was an error initializing your environment.
app › 🛑 Could not initialize categories for '***': auth headless is missing the following inputParams facebookAppIdUserPool, facebookAppSecretUserPool, googleAppIdUserPool, googleAppSecretUserPool
app › Resolution: Review the error message and stack trace for additional information.
app › Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/
app › Running command: flutter pub get
```

Any ideas?
