### ISSUE TITLE
Unable to deploy backend environment "storage headless is missing the following inputParams tables, region"

### ISSUE THREAD

**Issue by Syphini** [aws-amplify/amplify-cli#11085]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.17.0

### Amplify CLI Version

10.0.0

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes as far as I'm aware

### Amplify Categories

storage, api

### Amplify Commands

Not applicable

### Describe the bug

While attempting to deploy our AWS Amplify connected application, the backend environment fails to deploy with this error

> Command failed with exit code 1: amplify pull --amplify {"envName":"staging","defaultEditor":"code","appId":"d3nja2mywrxh1s"} --providers {"awscloudformation":{"configLevel":"project","useProfile":true,"profileName":"amplify-backend-processor"}} --frontend {"frontend":"javascript","framework":"react","config":{"SourceDir":"src","DistributionDir":"build","BuildCommand":"npm run-script build","StartCommand":"npm run-script start"}} --yes ✖ Failed to sync UI components - Fetching updates to backend environment: staging from the cloud. - Building resource api/sceniccheckout - Building resource auth/sceniccheckout110adb99 - Building resource storage/sceniccheckoutcontent - Building resource storage/accesscodes - Building resource storage/environmentvariables ✔ Successfully pulled backend environment staging from the cloud. ✖ There was an error initializing your environment. ⚠️ Amplify command hooks are disabled in the current execution environment. ⚠️ See https://docs.amplify.aws/cli/usage/command-hooks/ for more information. Amplify AppID found: d3nja2mywrxh1s. Amplify App name is: scenic_checkout Backend environment staging found in Amplify Console app: scenic_checkout ✅ GraphQL schema compiled successfully. Edit your schema at XXX or place .graphql files in a directory at XXX Successfully generated models. Generated models can be found in XXX ✅ GraphQL schema compiled successfully. Edit your schema at XXX or place .graphql files in a directory at XXX Failed to pull the backend. 🛑 storage headless is missing the following inputParams tables, region Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report' Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

After previously searching for solutions I attempted to add the following environment variables as others have said this helps

> AMPLIFY_STORAGE_BUCKET_NAME
 AMPLIFY_STORAGE_REGION

I similarly tried to add the CATEGORIES environment variable after the previous ones did not work, however this caused a separate issue and the 'Cloning Repository' build step now throws the following error

> Error: storage headless is missing the following inputParams tables, region
                                 at ensureHeadlessParameters (/snapshot/repo/build/node_modules/@aws-amplify/amplify-category-storage/lib/provider-utils/awscloudformation/import/import-dynamodb.js:400:11)
                                 at headlessImport (/snapshot/repo/build/node_modules/@aws-amplify/amplify-category-storage/lib/provider-utils/awscloudformation/import/import-dynamodb.js:360:40)
                                 at importedDynamoDBEnvInit (/snapshot/repo/build/node_modules/@aws-amplify/amplify-category-storage/lib/provider-utils/awscloudformation/import/import-dynamodb.js:260:12)
                                 at runMicrotasks (<anonymous>)
                                 at processTicksAndRejections (internal/process/task_queues.js:95:5)
                                 at async updateConfigOnEnvInit (/snapshot/repo/build/node_modules/@aws-amplify/amplify-category-storage/lib/provider-utils/awscloudformation/index.js:157:9)
                                 at async /snapshot/repo/build/node_modules/@aws-amplify/amplify-category-storage/lib/index.js:352:22
2022-09-30T00:52:15.094Z [ERROR]: !!! Build failed
2022-09-30T00:52:15.094Z [ERROR]: !!! Non-Zero Exit Code detected

I'd appreciate any advice I can get on solving this issue

### Expected behavior

Application should deploy with Frontend and Backend working correctly.

### Reproduction steps

After attempting to recreate on a new project I have come up with nothing, however it only seemed to have occurred in this project after importing an existing DynamoDB Table

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
input RequestHeader {
	tokenId: String!
	envId: String!
}

type ReservationBody {
  id: ID!
  totalPrice: Float!
  priceToPay: Float!
  discount: Float
  items: [ReservationItem]!
}

type ReservationItem {
  productId: ID!
  quantity: Int!
  bookingDate: AWSDate!
  startTime: AWSTime
}

input ReservationItemInput {
  productId: ID!
  quantity: Int!
  bookingDate: AWSDate!
  startTime: AWSTime
}

type Product {
	id: ID!
	name: String
	description: String
	imageUrl: String
	cost: Float
	tax: Float
	isTaxInclusive: Boolean
}

type Allocation {
	productId: ID!
	capacityRemaining: Int
	bookableCapacityRemaining: Int
	locations: [String]
}

type Availability {
	date: AWSDate!
	onlineSalesOpen: Boolean
	allocations: [Allocation]
}

type Session {
	date: AWSDate!
	name: String
	startTime: AWSTime
	endTime: AWSTime
	capacityRemaining: Int
	onlineSalesOpen: Boolean
	allocations: [Allocation]
}

type ProductAvailability {
	id: ID!
	name: String
	type: String
	description: String
	imageUrl: String
	products: [Product]
	availabilities: [Availability]
	sessions: [Session]
}

type ImageContent @model @auth(rules: [{ allow: public, operations: [read] }]) {
	id: ID!
	name: String!
	file: String!
	width: Int
	height: Int
	altText: String
}

type TextContent @model @auth(rules: [{ allow: public, operations: [read] }]) {
	id: ID!
	name: String!
	text: String!
}

type ProductContent @model @auth(rules: [{ allow: public, operations: [read] }]) {
	id: ID!
	name: String!
	image: ImageContent @hasOne
	description: String
}


type Query {
	getRollerToken(header: RequestHeader!): String @function(name: "getRollerToken-${env}")
	getProductAvailability(header: RequestHeader!, date: AWSDate!): [ProductAvailability] @function(name: "getProductAvailability-${env}")
}

type Mutation {
	rollerReserve(header: RequestHeader!, body: [ReservationItemInput]): ReservationBody @function(name: "rollerReserve-${env}")
	rollerReserveDelete(header: RequestHeader!, reservationId: String!): String @function(name: "rollerReserveDelete-${env}")
}

```

</details>

### Project Identifier

1faff6209c11433887b9b21140585980

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
Hey @Syphini :wave: thanks for raising this! From your note regarding the two environment variables, was `AMPLIFY_STORAGE_TABLES` environment variable also set? https://docs.amplify.aws/cli/storage/import/#configure-environment-variables-for-amplify-hosting-builds

**Comment by Syphini** [comment]
@josefaidt my bad, I meant to write in that I had used AMPLIFY_STORAGE_REGION and AMPLIFY_STORAGE_TABLES as per the documentation, but I must've typed the wrong one in here.
Adding in AMPLIFY_STORAGE_BUCKET_NAME didn't appear to do much for the build process either since I was only importing existing DynamoDB tables

**Comment by josefaidt** [comment]
Hey @Syphini no worries, thanks for clarifying! Is this failing at the backend build step of the automated build in Amplify Hosting? If so, would you mind sharing the App ID and region? Are you using a customized buildspec (`amplify.yml`) file?

**Comment by Syphini** [comment]
All I can see is that with those two environment variables added (AMPLIFY_STORAGE_REGION and AMPLIFY_STORAGE_TABLES) Amplify Hosting succeeds in the "Build" stage of the app, but then fails during the "Deploy" stage with the only error being "Deploy failed to complete successfully". Without those environment variables, it doesn't even get past the "Build" stage

AppID : d3nja2mywrxh1s
Region: ap-southeast-2

Not currently using any customized buildspec

**Comment by Syphini** [comment]
@josefaidt just going to bump this a little bit. I ended up switching from a GraphQL API to a Rest API thereby deleting and recreating all my API settings.
This seems to still be "failing" at the Deploy stage after Amplify Hosting is pulling changes from Git, but when I check the hosted website, the changes seem to be appearing just fine.
I'm very confused as to what the issue is now, but I'm seemingly able to make changes with the only error showing in AWS Console

**Comment by josefaidt** [comment]
Hey @Syphini :wave: apologies for the delay here. Does your project still import the DynamoDB table, and you're able to push without issue?

**Comment by Syphini** [comment]
Hi @josefaidt the project is importing all the tables correctly, is able to push via Amplify CLI and even seems to build on the Amplify console correctly.
Currently the only issue now is that during a git push the Amplify Console comes up with a "Deploy" error.
![image](https://user-images.githubusercontent.com/44600408/195733076-40b83e5a-e890-4311-abb2-1bcdef2b5ee2.png)

If I access the hosted website via Amplify Console it seems to have updated fine, it just visually shows the "Deploy" error in console

**Comment by josefaidt** [comment]
Hey @Syphini thanks for the clarification! I've reached out to some of our friends over at Amplify Hosting to get some additional assistance, and I will report back 🙂

**Comment by josefaidt** [comment]
Transferring to Amplify Hosting for better assistance regarding the failed deploment
