### ISSUE TITLE
Mocking lambda works but deployed, Error: Cannot find module 'aws-appsync'"

### ISSUE THREAD

**Issue by lallish** [aws-amplify/amplify-cli#11091]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.13.2

### Amplify CLI Version

10.0.0

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

function

### Amplify Commands

add

### Describe the bug

I have a function created through amplify which uses the aws-appsync client to call my AppSync API. When I run `amplify mock function <function>` the function works successfully. But after being deployed to AWS the function errors saying it is missing a module:

    {
        "errorType": "Runtime.ImportModuleError",
        "errorMessage": "Error: Cannot find module 'aws-appsync'\nRequire stack:\n- /var/task/index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/Runtime.js\n- /var/runtime/index.js",
        "stack": [
            "Runtime.ImportModuleError: Error: Cannot find module 'aws-appsync'",
            "Require stack:",
            "- /var/task/index.js",
            "- /var/runtime/UserFunction.js",
            "- /var/runtime/Runtime.js",
            "- /var/runtime/index.js",
            "    at _loadUserApp (/var/runtime/UserFunction.js:221:13)",
            "    at Object.module.exports.load (/var/runtime/UserFunction.js:279:17)",
            "    at Object.<anonymous> (/var/runtime/index.js:43:34)",
            "    at Module._compile (internal/modules/cjs/loader.js:1085:14)",
            "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)",
            "    at Module.load (internal/modules/cjs/loader.js:950:32)",
            "    at Function.Module._load (internal/modules/cjs/loader.js:790:12)",
            "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)",
            "    at internal/main/run_main_module.js:17:47"
        ]
    }

### Expected behavior

If mocking the function works locally it should work in AWS too.

### Reproduction steps

1. amplify add function (create a nodejs function with permissions to read from api)
2. add code to function
3. npm install
4. amplify mock function <function> # works!
5. run lambda in AWS console # fails!

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type Product
  @model
  @aws_iam
  @aws_cognito_user_pools
 {
  id: ID!
  name: String!
  price: Int
}

```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

package.json:

    {
      "name": "getproduct",
      "version": "2.0.0",
      "description": "Lambda function generated by Amplify",
      "main": "index.js",
      "license": "Apache-2.0",
      "dependencies": {
          "aws-appsync": "^4.1.7",
          "cross-fetch": "^3.1.5",
          "graphql-tag": "^2.12.6"
      }
    }

lambda.js

    /* Amplify Params - DO NOT EDIT
      API_MAPP_GRAPHQLAPIENDPOINTOUTPUT
      API_MAPP_GRAPHQLAPIIDOUTPUT
      ENV
      REGION
    Amplify Params - DO NOT EDIT */
    
    const appsync = require('aws-appsync');
    const gql = require('graphql-tag')
    require('cross-fetch/polyfill');
    
    const query = gql`
      query GetProduct(
        $id: ID!
      ) {
        getProduct(
          id: $id
        ) {
          items {
            id
            name
            price
           }
        }
      }`;
    const graphqlClient = new appsync.AWSAppSyncClient({
      url: process.env.API_MAPP_GRAPHQLAPIENDPOINTOUTPUT,
      region: process.env.AWS_REGION,
      auth: {
        type: 'AWS_IAM',
        credentials: {
          accessKeyId: process.env.AWS_ACCESS_KEY_ID,
          secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
          sessionToken: process.env.AWS_SESSION_TOKEN
        }
      },
      disableOffline: true
    });
    
    exports.handler = async (event, context, callback) => {
    
      let statusCode = 200;
      let item = {};
      try {
        const response = await graphqlClient.query({
          query,
          variables: {
            id: "abc"
          }
        });
        item = response.data?.getProduct?.items?.[0];
      } catch (e) {
        console.log(e);
        statusCode = 503;
      }
      console.log("Found item:");
      console.log(item);
      if (item === undefined) {
        statusCode = 404;
      }
      return callback(null, {
        statusCode: statusCode,
        headers: {
          'Content-Type': 'application/json'
        },
        body: item
      })
    }

**Comment by josefaidt** [comment]
Hey @lallish :wave: thanks for raising this! Unfortunately I was not able to reproduce this using the provided `package.json`. If you unzip the distribution zip archive in your function's `dist/` directory, do you see this npm package available in the `node_modules` folder?

**Comment by lallish** [comment]
> Hey @lallish 👋 thanks for raising this! Unfortunately I was not able to reproduce this using the provided `package.json`. If you unzip the distribution zip archive in your function's `dist/` directory, do you see this npm package available in the `node_modules` folder?

Thanks for quick reply @josefaidt !
Here is the contents of the zip archive:

![Capture](https://user-images.githubusercontent.com/3920385/193692729-6790b9a0-a984-4edb-9b30-fcf6fa691ac7.JPG)

**Comment by cdwheatley** [comment]
I am running in to this same error.

Amplify CLI version 10.2.3

Node.js version 14.x

Is there a known working older version that we could rollback to in order to work around this for now?

**Comment by josefaidt** [comment]
Hey @lallish sorry for the delay here!!! It appears while some of the dependencies are installed, I do not see the `aws-appsync` package. Can you try regenerating the lockfile by running `npm install` inside the function's `src/` directory?

Additionally, be sure to check out our docs for calling GraphQL from Nodejs! https://docs.amplify.aws/lib/graphqlapi/graphql-from-nodejs/q/platform/js/#commonjs

**Comment by josefaidt** [comment]
Hey @lallish I wanted to follow-up on this one and see if you are still experiencing this issue?

**Comment by josefaidt** [comment]
Closing due to inactivity. @lallish if you are still experiencing this please reply back to this thread and we can re-open to investigate further 🙂
