### ISSUE TITLE
Can't run amplify mock

### ISSUE THREAD

**Issue by chstrong** [aws-amplify/amplify-cli#11288]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

10.4.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

When I run "amplify mock" or "amplify mock api" I get the following error message:

`{
    "name": "UnknownFault",
    "classification": "FAULT",
    "options": {
        "message": "Cannot read property 'stop' of undefined",
        "resolution": "Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'",
        "stack": "TypeError: Cannot read property 'stop' of undefined\n    at APITest.stop (/snapshot/repo/build/node_modules/amplify-util-mock/lib/api/api.js:149:33)\n    at APITest.start (/snapshot/repo/build/node_modules/amplify-util-mock/lib/api/api.js:127:18)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
        "link": "https://docs.amplify.aws/cli/project/troubleshooting/"
    },
    "downstreamException": {},
    "resolution": "Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'",
    "link": "https://docs.amplify.aws/cli/project/troubleshooting/"
}`

### Expected behavior

Running amplify mock should not throw any errors.

### Reproduction steps

1. Create a new react project
2. Run amplify init
3. Run amplify mock

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type Restaurant @model @auth(rules: [{allow: private}]) {
  id: ID!
  name: String!
  foodCategory: [FoodCategory] @hasMany
}

type FoodCategory @model @auth(rules: [{allow: private}]) {
  id: ID!
  name: String!
  image: String
  restaurant: Restaurant @belongsTo
}

type MenuItems @model @auth(rules: [{allow: private}]) {
  id: ID!
  name: String!
}

```

</details>

### Project Identifier

fe991c4ae488b4f8c1065cb5a01664c7

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by chstrong** [comment]
This error appears if Java is not installed. After installing Java on my Mac it worked. Therefore closing this, even though I think, there should be a better error message that hints to the developer to install Java.
