### ISSUE TITLE
Adding notification permissions to Function throws error

### ISSUE THREAD

**Issue by ykethan** [aws-amplify/amplify-cli#11320]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify CLI Version

10.4.0, 10.4.1-rc.ac06cb27b.0

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

notifications

### Amplify Commands

add

### Describe the bug

When adding permissions for notification in Lambda function throws the following error

```
Policies cannot be added for notifications
PluginMethodNotFoundError: Method getPermissionPolicies does not exist or is not a function in category plugin: notifications.
at amplifyErrorWithTroubleshootingLink (/snapshot/repo/build/node_modules/amplify-cli-core/lib/errors/amplify-error.js:12:85)
at AmplifyToolkit.invokePluginMethod [as _invokePluginMethod] (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/invoke-plugin-method.js:35:74)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async getResourcesForCfn (/snapshot/repo/build/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.js:183:56)
at async askExecRolePermissionsQuestions (/snapshot/repo/build/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.js:113:66)
at async Object.createWalkthrough (/snapshot/repo/build/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/service-walkthroughs/lambda-walkthrough.js:53:83)
at async addFunctionResource (/snapshot/repo/build/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/index.js:78:9)
at async Object.executeAmplifyCommand (/snapshot/repo/build/node_modules/amplify-category-function/lib/index.js:267:5)
at async executePluginModuleCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:142:5)
at async executeCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:40:9)
at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:153:5)
```

created from comment https://github.com/aws-amplify/amplify-cli/issues/11260#issuecomment-1296513998 and reproduced.

### Expected behavior

able to access notifications in Lambda function

### Reproduction steps

amplify add function
? Do you want to access other resources in this project from your Lambda function? Yes
? Select the categories you want this function to have access to. notifications

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
related https://github.com/aws-amplify/amplify-cli/issues/5157

**Comment by evcodes** [comment]
Closing as the fix was released
