### ISSUE TITLE
Auto ID numbering does not work when adding `( timestamps: null )` to the model directive

### ISSUE THREAD

**Issue by unirt** [aws-amplify/amplify-cli#11359]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.14.0

### Amplify CLI Version

10.4.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

When I add `timestamps: null` to the model directive and test with the `amplify mock api`, the auto-numbering of IDs does not work.  
When there are two models as follows, the mutations `createTodo1` and `createTodo2` are created.
```graphql
type Todo1 @model {
  id: ID!
  name: String!
  description: String
}

type Todo2 @model( timestamps: null ) {
  id: ID!
  name: String!
  description: String
}
```
Both mutations do not require an id for input and the id should be auto-numbered, but when tested with the `amplify mock api`, the following error occurs when executing `createTodo2`.
```json
{
  "data": {
    "createTodo2": null
  },
  "errors": [
    {
      "message": "One of the required keys was not given a value",
      "errorType": "DynamoDB:ValidationException",
      "data": null,
      "errorInfo": null,
      "path": [
        "createTodo2"
      ],
      "locations": [
        {
          "line": 2,
          "column": 3,
          "sourceName": "GraphQL request"
        }
      ]
    }
  ]
}
```
And in my terminal I got the following error message.
```
Error while executing Local DynamoDB
{
    "version": "2018-05-29",
    "operation": "PutItem",
    "attributeValues": {
        "name": {
            "S": "test"
        },
        "__typename": {
            "S": "Todo2"
        }
    },
    "condition": {
        "expression": "attribute_not_exists(#id)",
        "expressionNames": {
            "#id": "id"
        }
    },
    "key": {}
}
ValidationException: One of the required keys was not given a value
    at Request.extractError (/snapshot/repo/build/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.callListeners (/snapshot/repo/build/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/snapshot/repo/build/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/snapshot/repo/build/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/snapshot/repo/build/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/snapshot/repo/build/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /snapshot/repo/build/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/snapshot/repo/build/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/snapshot/repo/build/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/snapshot/repo/build/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/snapshot/repo/build/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/snapshot/repo/build/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/snapshot/repo/build/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/snapshot/repo/build/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /snapshot/repo/build/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/snapshot/repo/build/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/snapshot/repo/build/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/snapshot/repo/build/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at callNextListener (/snapshot/repo/build/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at IncomingMessage.onEnd (/snapshot/repo/build/node_modules/aws-sdk/lib/event_listeners.js:380:13)
    at IncomingMessage.emit (events.js:412:35)
    at IncomingMessage.emit (domain.js:475:12)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'ValidationException',
  time: 2022-11-09T16:38:49.578Z,
  requestId: '2f11e892-9179-4132-ac1f-3880551f49c9',
  statusCode: 400,
  retryable: false,
  retryDelay: 0.3930575507768652
}
```
Of course, `createTodo1` was successfully executed.

Checking the VTL files of the generated resolver, I see that `Mutation.createTodo1.init.1.req.vtl` has `$util.qr($ctx.stash.defaultValues.put("id", $util.autoId()))` while `Mutation.createTodo2.init.1.req.vtl` does not.

`Mutation.createTodo1.init.1.req.vtl`
```
## [Start] Initialization default values. **
$util.qr($ctx.stash.put("defaultValues", $util.defaultIfNull($ctx.stash.defaultValues, {})))
#set( $createdAt = $util.time.nowISO8601() )
$util.qr($ctx.stash.defaultValues.put("id", $util.autoId()))
$util.qr($ctx.stash.defaultValues.put("createdAt", $createdAt))
$util.qr($ctx.stash.defaultValues.put("updatedAt", $createdAt))
$util.toJson({
  "version": "2018-05-29",
  "payload": {}
})
## [End] Initialization default values. **
```

`Mutation.createTodo2.init.1.req.vtl`
```
## [Start] Initialization default values. **
$util.qr($ctx.stash.put("defaultValues", $util.defaultIfNull($ctx.stash.defaultValues, {})))
$util.toJson({
  "version": "2018-05-29",
  "payload": {}
})
## [End] Initialization default values. **
```

### Expected behavior

The `createTodo2` mutation, like the `createTodo1` mutation, does not require an id for the input and expects the id to be auto-numbered.

### Reproduction steps

Here is my repo for reproduction: https://github.com/unirt/autoid-amplify-mock

Reproduction steps:
1. Run [the Amplify tutorial](https://docs.amplify.aws/start/getting-started/installation/q/integration/react/) up to [Connect API and database to the app](https://docs.amplify.aws/start/getting-started/data-model/q/integration/react/) (but not deploying the api)
2. Modify `schema.graphql` as follows:
```graphql
# This "input" configures a global authorization rule to enable public access to
# all models in this schema. Learn more about authorization rules here: https://docs.amplify.aws/cli/graphql/authorization-rules
input AMPLIFY { globalAuthRule: AuthRule = { allow: public } } # FOR TESTING ONLY!

type Todo1 @model {
  id: ID!
  name: String!
  description: String
}

type Todo2 @model( timestamps: null ) {
  id: ID!
  name: String!
  description: String
}
```
3. Run `amplify mock api`
4. In the GraphiQL Explorer, run the `createTodo2` mutation with only name in the input.
5. You'll get the following error message:
```json
{
  "data": {
    "createTodo2": null
  },
  "errors": [
    {
      "message": "One of the required keys was not given a value",
      "errorType": "DynamoDB:ValidationException",
      "data": null,
      "errorInfo": null,
      "path": [
        "createTodo2"
      ],
      "locations": [
        {
          "line": 2,
          "column": 3,
          "sourceName": "GraphQL request"
        }
      ]
    }
  ]
}
```

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
# This "input" configures a global authorization rule to enable public access to
# all models in this schema. Learn more about authorization rules here: https://docs.amplify.aws/cli/graphql/authorization-rules
input AMPLIFY { globalAuthRule: AuthRule = { allow: public } } # FOR TESTING ONLY!

type Todo1 @model {
  id: ID!
  name: String!
  description: String
}

type Todo2 @model( timestamps: null ) {
  id: ID!
  name: String!
  description: String
}

```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by unirt** [comment]
[Update] When a model is defined as follows, the create mutation with only name in the input.
```graphql
type Todo3 @model( timestamps: { createdAt: null, updatedAt: null } ) {
  id: ID!
  name: String!
  description: String
}
```
