### ISSUE TITLE
Creating an Additional Environment

### ISSUE THREAD

**Issue by Etep15** [aws-amplify/amplify-cli#11719]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.17.1

### Amplify CLI Version

10.5.1

### What operating system are you using?

MacOS

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

We had 3 environments, dev, test, and prod. Dev and test have been up and running and up to date for awhile and are running well. 

Prod was left dormant for a very long time. I tried to git merge changes over from test to prod but it failed when I tried to check out the prod env with `amplify env checkout prod`.  Complaining about the APNS push notifications with the error `🛑 Failed to enable the APNS channel.`

Thankfully the prod environment didn't have any important data so after some time I was able to remove the env (had issues getting over to another env but an `amplify pull` eventually worked when I was in the test env.)

However now when I try to create a new env I'm again plagued by the same issue and error. 

See log output for details. 

Also in the log you'll see the prompt at the end for the Google Web Client OD. I didn't get a chance to type anything in. The error showed up and that ended the process. 

### Expected behavior

Environment should be created with the provided APNS configuration.

### Reproduction steps

1. Have a working environment with APNS push notifications working.
2. Execute the `amplify env add` command and follow the prompts.

### Project Identifier

cf6680d5eea50e0f311acdd7f53684a0

### Log output

<details>

```
# Put your logs below this line

amplify env add
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the environment prod
Using default provider  awscloudformation
? Select the authentication method you want to use: AWS profile

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

? Please choose the profile you want to use default
Adding backend environment prod to AWS Amplify app: [REDACTED]

Deployment completed.
Deployed root stack [REDACTED] [ ======================================== ] 4/4
	amplify-[REDACTED]-prod-143424 AWS::CloudFormation::Stack     CREATE_COMPLETE                Thu Jan 05 2023 14:34:55…     
	DeploymentBucket               AWS::S3::Bucket                CREATE_COMPLETE                Thu Jan 05 2023 14:34:51…     
	UnauthRole                     AWS::IAM::Role                 CREATE_COMPLETE                Thu Jan 05 2023 14:34:52…     
	AuthRole                       AWS::IAM::Role                 CREATE_COMPLETE                Thu Jan 05 2023 14:34:51…     

Deployment bucket fetched.
⠋ Initializing your environment: prod⠋ Building resource auth/[REDACTED][WARNING] @aws-cdk/core.Lazy#anyValue is deprecated.
  Use `Lazy.any()` or `Lazy.uncachedAny()` instead.
  This API will be removed in the next major release.
✔ Initialized provider successfully.
⚠️ Pinpoint resource is only locally created
⚠️ Run "amplify push" to deploy the Pinpoint resource and then retry...
? Choose authentication method used for APNs Key
? The bundle id used for APNs Tokens:  [REDACTED]
? The team id used for APNs Tokens:  [REDACTED]
? The key id used for APNs Tokens:  [REDACTED]
? The key file path (.p8):  [REDACTED]
✖ There was an error initializing your environment.
  
 You've opted to allow users to authenticate via Google.  If you haven't already, you'll need to go to https://developers.google.com/identity and create an App ID. 
 
 Enter your Google Web Client ID for your identity pool:  🛑 Failed to enable the APNS channel.

Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by Etep15** [comment]
Some additional information (Progress?) :

I managed to get past the notification / APNS / auth issue by using the solution for a number of other tickets people have posted and that is to use `amplify update auth` command. Then selection Walkthrough all configs... This cleared things up and I was able to do an `amplify push` to a point. It appears to finish everything. Until it gets to `Creating API models...` and I get an error of `🛑 Cannot set property 'Id' of undefined`. I ran the amplify push command with --debug and have the following log output...

```
Creating API models...
🛑 Cannot set property 'Id' of undefined

Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

DeploymentFault: Cannot set property 'Id' of undefined
    at Object.run (/snapshot/repo/build/node_modules/amplify-provider-awscloudformation/lib/push-resources.js:450:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Promise.all (index 0)
    at async providersPush (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/push-resources.js:107:5)
    at async AmplifyToolkit.pushResources [as _pushResources] (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/push-resources.js:81:13)
    at async Object.executeAmplifyCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:212:9)
    at async executePluginModuleCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:142:5)
    at async executeCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:40:9)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:153:5)

Cannot set property 'Id' of undefined
TypeError: Cannot set property 'Id' of undefined
    at analyticsPluginAPIPostPush (/snapshot/repo/build/node_modules/amplify-category-analytics/lib/analytics-resource-api.js:147:43)
    at AmplifyToolkit.invokePluginMethod [as _invokePluginMethod] (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/invoke-plugin-method.js:39:12)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async invokePostPushAnalyticsUpdate (/snapshot/repo/build/node_modules/amplify-provider-awscloudformation/lib/plugin-client-api-analytics.js:10:56)
    at async Object.run (/snapshot/repo/build/node_modules/amplify-provider-awscloudformation/lib/push-resources.js:432:17)
    at async Promise.all (index 0)
    at async providersPush (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/push-resources.js:107:5)
    at async AmplifyToolkit.pushResources [as _pushResources] (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/push-resources.js:81:13)
    at async Object.executeAmplifyCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:212:9)
    at async executePluginModuleCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:142:5)
    at async executeCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:40:9)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:153:5)
```
This was the last step in the deployment as it shows 28/29 at the top of the output. 

I see reference to "analytics" at the top of the second stack trace. Wondering if that is the culprit and if so, what to do about it?

**Comment by Etep15** [comment]
This is also confirmed to be an issue with the current latest amplify cli, 10.6.1. Simpliest way to reproduce is to execute `amplify analytics update`.

**Comment by Etep15** [comment]
I dove into the amplify code and started looking for `pinpoint-helper.js`. I'm not familiar with the code base but I did managed to find a typescript version here :

https://github.com/aws-amplify/amplify-cli/blob/dev/packages/amplify-category-analytics/src/utils/pinpoint-helper.ts

Like 99 seems to be the same function where the stack trace is pointing to and lines 103 through 105 (105 specifically) seems to show where the error is occurring. On line 105 `categoryResources[resource].output.Id` suggests that the "output" variable is undefined. 

I searched around and found in my `amplify/backend/amplify-meta.json` file a section for the analytics as seen here : 

```
"analytics": {
    "[REDACTED]": {
      "service": "Pinpoint",
      "providerPlugin": "awscloudformation",
      "providerMetadata": {
        "s3TemplateURL": "https://s3.amazonaws.com/amplify-[REDACTED]-prod-[REDACTED]-deployment/amplify-cfn-templates/analytics/pinpoint-cloudformation-template.json",
        "logicalId": "analytics[REDACTED]"
      },
      "lastPushTimeStamp": "2023-01-06T00:16:30.735Z",
      "output": {
        "appName": "[REDACTED]-prod",
        "Region": "us-west-2",
        "Id": "[REDACTED]"
      },
      "lastPushDirHash": "kCsSCYQZGs79lElhqb6zTTennfw="
    }
  }
```

I redacted the ID as I wasn't sure how sensitive that information is from a security standpoint but there is definitely an ID in there. Not to mention there is definitely an output section for the analytics section. 

I'm not sure if any of this is helping but I'm hoping so. But I feel like this is showing that things should be working but there must be some other file that I'm not looking at the right location. 

Also, one final note. I cannot remove analytics nor notifications in order to recreate them. I get the same error. Therefore rebuilding this portion from scratch is not an option. This in turn does not allow me to create a new environment from scratch either.

**Comment by Etep15** [comment]
Actually, looking at the code again I realized that it is looking at the "notifications" section. Not the analytics.

Indeed our notifications section is missing the "output" section and therefore no Id. 
```
"notifications": {
    "[REDACTED]": {
      "service": "Pinpoint",
      "channels": [
        "APNS"
      ]
    }
```
So this is clearly the issue, but I've no idea how to resolve it? I've run the amplify update auth command many times but it does not seem to resolve this.

**Comment by Etep15** [comment]
Well, I think I've resolved the issue!!

Here's what I've done...

Because I seemed to have an incomplete notifications section in my configs (even after doing the "walkthrough" mentioned above) I loaded up my test environment and grabbed the notifications section from there. Then checked out my prod environment (with errors of course) and then replaced the notification section back into my prod env's `amplify/backend/amplify-meta.json` file. 

Next, as it seemed the pinpoint project my my prod env had indeed been created according to the Pinpoint web console, I  edited all the Id's to be what was shown the Pinpoint console (Project ID) and the Name to be my project name -prod. I also set the creationDate and lastModifiedDates to be the same as what is in the PinPoint web console as listed under All Projects, Creation date. For reference here is the json :
```
"notifications": {
    "[REDACTED]": {
      "Id": "[REDACTED]", ##  set to my prod pinpoint project ID
      "ResourceName": "[REDACTED]",
      "Name": "[REDACTED]-test", ## Changed -test to -prod
      "service": "Pinpoint",
      "output": {
        "Id": "[REDACTED]", ##  set to my prod pinpoint project ID
        "Name": "[REDACTED]-test", ## Changed -test to -prod
        "Region": "us-west-2",
        "APNS": {
          "ApplicationId": "[REDACTED]", ##  set to my prod pinpoint project ID
          "CreationDate": "2022-10-20T16:54:05.277Z", ## Changed to the Creation Date according to the Pinpoint console
          "DefaultAuthenticationMethod": "Key",
          "Enabled": true,
          "HasCredential": false,
          "HasTokenKey": true,
          "Id": "apns",
          "IsArchived": false,
          "LastModifiedDate": "2022-10-29T06:28:27.103Z", ## Changed to the Creation Date according to the Pinpoint console
          "Platform": "APNS",
          "Version": 9
        },
        "regulatedResourceName": "[REDACTED]"
      },
      "lastPushTimeStamp": "2023-01-05T23:49:50.400Z"
    }
  }
```

Note the fields that have ## comments. Those are the ones I changed.

Next I tried to do an `amplify notifications update` but that failed. Complained about a file missing from the `#current-cloud-backend` folder. `backend-config.json`. Which makes sense since this env has never been successfully pushed. 

I therefore did an `amplify push`... With **SUCCESS**!

Before I did this push my pinpoint application for prod had APNS disabled under _Settings/Push notifications_. Which is why I tried to do the `amplify notifications update` first. However the `amplify push` seemed to resolve this as after the push, and they are now enabled. I'm hoping that's all that is needed because normally the `amplify notifications` command configures things immediately in AWS without a push. 

Will update further if I find any issues with this build as I'm going to do some testing now. But hopefully this helps someone else in future should they come across it.

**Comment by biller-aivy** [comment]
Have the same problem at the moment. This is why the id is not set I guess 

<img width="917" alt="Bildschirm­foto 2023-01-11 um 13 47 48" src="https://user-images.githubusercontent.com/88539760/211810171-b1cffae7-3b8f-48fd-a716-7b9584795e1d.png">

**Comment by lukejbrennan** [comment]
I tried adding the following to my team-provider-info.json to match what i have for production (which is working as expected): 
```
"analytics": {
        "fringePinpoint": {},
        "Pinpoint": {
          "Name": "XXXXX-qa",
          "Id": "XXXXX",
          "Region": "us-east-1"
        }
      },
      "notifications": {
        "Pinpoint": {
          "Name": "XXXXX-qa",
          "Id": "XXXXX",
          "Region": "us-east-1"
        }
      }
```
Still getting  ```Cannot read property 'Id' of undefined``` on ```amplify push``` Also tried running ```amplify analytics update``` and ```amplify notifications update``` but no luck

**Comment by lazpavel** [comment]
This issue is fixed in latest Amplify CLI, please upgrade and try again
