### ISSUE TITLE
`Cannot convert undefined or null to Object` when attempting to push with an empty custom CDK resource

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/amplify-cli#11747]
### How did you install the Amplify CLI?

pnpm

### If applicable, what version of Node.js are you using?

18

### Amplify CLI Version

10.6.1

### What operating system are you using?

mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

n/a

### Describe the bug

Receiving `cannot convert undefined or null to object` when attempting to push my Amplify project. Upon further investigation it was noticed this is due to the fact that a custom CDK resource I added does not create any resources, therefore the CloudFormation template does not include a `Resources` key:

```
Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at getCategoryResources (/snapshot/repo/build/node_modules/amplify-provider-awscloudformation/lib/push-resources.js:806:36)
    at /snapshot/repo/build/node_modules/amplify-provider-awscloudformation/lib/push-resources.js:844:31
    at Array.forEach (<anonymous>)
    at handleCfnFiles (/snapshot/repo/build/node_modules/amplify-provider-awscloudformation/lib/push-resources.js:843:12)
    at /snapshot/repo/build/node_modules/amplify-provider-awscloudformation/lib/push-resources.js:831:9
    at Array.forEach (<anonymous>)
    at /snapshot/repo/build/node_modules/amplify-provider-awscloudformation/lib/push-resources.js:829:35
    at Array.forEach (<anonymous>)
    at createEventMap (/snapshot/repo/build/node_modules/amplify-provider-awscloudformation/lib/push-resources.js:827:21)
    at Object.run (/snapshot/repo/build/node_modules/amplify-provider-awscloudformation/lib/push-resources.js:164:22)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Promise.all (index 0)
    at async providersPush (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/push-resources.js:109:5)
    at async AmplifyToolkit.pushResources [as _pushResources] (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/push-resources.js:83:13)
    at async Object.executeAmplifyCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:179:9)
    at async executePluginModuleCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:142:5)
    at async executeCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:40:9)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:119:5)
```

https://github.com/aws-amplify/amplify-cli/blob/dev/packages/amplify-provider-awscloudformation/src/push-resources.ts#L875

### Expected behavior

CLI should ignore the resource that does not create any resources or print a warning informing the developer that the custom resource does not create any resources and will be skipped

```
Custom resource mycustomresource does not create any resources, skipping...
```

### Reproduction steps

1. `amplify init -y`
2. `amplify add custom` > cdk
3. `amplify push -y`
4. observe error

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Marking as a duplicate of https://github.com/aws-amplify/amplify-cli/issues/11341, closing
