### ISSUE TITLE
Unable to pull a prod env Amplify backend. It stopped working suddenly.

### ISSUE THREAD

**Issue by mithunkavullakandiyil** [aws-amplify/amplify-cli#11850]
### Description

Unable to pull a prod env Amplify backend. It stopped working suddenly. No clue what is the issue and how to resolve

```
amplify pull
? Select the authentication method you want to use: AWS profile

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

? Please choose the profile you want to use ***
? Which app are you working on? ***
Backend environment 'prod' found. Initializing...
🛑 Failed to pull the backend.

Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

Session Identifier: 9c0193de-c7e5-4eb8-9246-ad6cdb6a6577
```

**Comment by Jordan-Nelson** [comment]
@mithunkavullakandiyil - Thanks for taking the time to open the issue. I have transferred this issue to the CLI project since this doesn't appear to be specific to amplify flutter.

**Comment by josefaidt** [comment]
Hey @mithunkavullakandiyil :wave: thanks for raising this! As we begin to look at this in more depth I have a few follow-up questions:

- what version of the CLI are you using?
- if you re-run this command with `--debug`, does it print a stack trace?
- are there any additional logs in `~/.amplify/logs`?
- can you post the project ID output from `amplify diagnose --send-report`?

**Comment by mithunkavullakandiyil** [comment]
Finally figured out that the issue is related to bug #10032.

I am neither able to push, nor able to pull the project. (Tried with a fresh project).
I guess this issue occurs in Windows (mine is Windows 11) with the layer function with dependencies. And this occurs after certain successful pushes. Please refer the list of layer function dependencies mentioned below.

I am able to successfully pull and push the amplify backend in macOS.

This seems to be a real critical issue and please consider it for a quick resolution or a quick workaround fix until the real issue is fixed. I guess this is something to do with NodeJs, or some Nodejs dependencies or with the Windows Path limit.

### Push Command
```
amplify push --y      
× There was an error pulling the backend environment dev.
🛑 Failed to extract zip file:
ENOENT: no such file or directory, realpath 'C:\Users\***\Projects\***\projects\***\amplify\.temp\#current-cloud-backend\function\<LAYER_FUNCTION_NAME>\lib\nodejs\node_modules\@aws-sdk\client-secrets-manager\node_modules\@aws-crypto\sha256-js\node_modules\tslib\test\validateModuleExportsMatchCommonJS'

Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

ZipExtractFault: Failed to extract zip file:
    at extractZip (C:\snapshot\repo\build\node_modules\amplify-provider-awscloudformation\lib\zip-util.js:53:11)
    at async Object.run (C:\snapshot\repo\build\node_modules\amplify-provider-awscloudformation\lib\initialize-env.js:47:25)

ENOENT: no such file or directory, realpath 'C:\Users\***\Projects\***\projects\***\amplify\.temp\#current-cloud-backend\function\<LAYER_FUNCTION_NAME>\lib\nodejs\node_modules\@aws-sdk\client-secrets-manager\node_modules\@aws-crypto\sha256-js\node_modules\tslib\test\validateModuleExportsMatchCommonJS'
Error: ENOENT: no such file or directory, realpath 'C:\Users\***\Projects\***\projects\***\amplify\.temp\#current-cloud-backend\function\<LAYER_FUNCTION_NAME>\lib\nodejs\node_modules\@aws-sdk\client-secrets-manager\node_modules\@aws-crypto\sha256-js\node_modules\tslib\test\validateModuleExportsMatchCommonJS'

Session Identifier: c8611476-5d45-4c1f-9e06-7519dc6c072d

✅ Report saved: C:\Users\***\AppData\Local\Temp\***\report-1674686181016.zip

√ Done

Project Identifier: ca6a2f26a84952cd245c528e6fccb8f0
```
### Pull Command
```
amplify pull --y    

Pre-pull status:

    Current Environment: dev
    
┌───────────┬────────────────────────────┬───────────┬───────────────────┐
│ Category  │ Resource name              │ Operation │ Provider plugin   │
├───────────┼────────────────────────────┼───────────┼───────────────────┤
│ Api       │ ***│ Update    │ awscloudformation │
├───────────┼────────────────────────────┼───────────┼───────────────────┤
│ Function  │ ***│ Update    │ awscloudformation │
├───────────┼────────────────────────────┼───────────┼───────────────────┤
│ Function  │ ***│ Update    │ awscloudformation │ <--- This is a function layer with all dependencies
├───────────┼────────────────────────────┼───────────┼───────────────────┤
│ Analytics │ ***│ No Change │ awscloudformation │
├───────────┼────────────────────────────┼───────────┼───────────────────┤
│ Auth      │ ***│ No Change │ awscloudformation │
├───────────┼────────────────────────────┼───────────┼───────────────────┤
│ Auth      │ ***│ No Change │ awscloudformation │
├───────────┼────────────────────────────┼───────────┼───────────────────┤
│ Function  │ ***│ No Change │ awscloudformation │
├───────────┼────────────────────────────┼───────────┼───────────────────┤
│ Function  │ ***│ No Change │ awscloudformation │
├───────────┼────────────────────────────┼───────────┼───────────────────┤
│ Function  │ ***│ No Change │ awscloudformation │
├───────────┼────────────────────────────┼───────────┼───────────────────┤
│ Function  │ ***│ No Change │ awscloudformation │
├───────────┼────────────────────────────┼───────────┼───────────────────┤
│ Function  │ ***│ No Change │ awscloudformation │
└───────────┴────────────────────────────┴───────────┴───────────────────┘

⚠️ Local changes detected.
⚠️ Pulling changes from the cloud will override your local changes.
× There was an error initializing your environment.
🛑 Failed to extract zip file:
ENOENT: no such file or directory, realpath 'C:\Users\***\Projects\***\projects\***\amplify\.temp\#current-cloud-backend\function\<LAYER_FUNCTION_NAME>\lib\nodejs\node_modules\@aws-sdk\client-secrets-manager\node_modules\@aws-crypto\sha256-js\node_modules\tslib\test\validateModuleExportsMatchCommonJS'

Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

ZipExtractFault: Failed to extract zip file:
    at extractZip (C:\snapshot\repo\build\node_modules\amplify-provider-awscloudformation\lib\zip-util.js:53:11)
    at async Object.run (C:\snapshot\repo\build\node_modules\amplify-provider-awscloudformation\lib\initialize-env.js:47:25)

ENOENT: no such file or directory, realpath 'C:\Users\***\Projects\***\projects\***\amplify\.temp\#current-cloud-backend\function\<LAYER_FUNCTION_NAME>\lib\nodejs\node_modules\@aws-sdk\client-secrets-manager\node_modules\@aws-crypto\sha256-js\node_modules\tslib\test\validateModuleExportsMatchCommonJS'
Error: ENOENT: no such file or directory, realpath 'C:\Users\***\Projects\***\projects\***\amplify\.temp\#current-cloud-backend\function\<LAYER_FUNCTION_NAME>\lib\nodejs\node_modules\@aws-sdk\client-secrets-manager\node_modules\@aws-crypto\sha256-js\node_modules\tslib\test\validateModuleExportsMatchCommonJS'

Session Identifier: 10f3889e-68e9-4dca-bea6-5a92af431052

✅ Report saved: C:\Users\***\AppData\Local\Temp\***\report-1674685650641.zip

√ Done

Project Identifier: ca6a2f26a84952cd245c528e6fccb8f0
```

### Layer Function Dependencies
```
{
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "@aws-crypto/sha256-js": "^2.0.1",
    "@aws-sdk/credential-provider-node": "^3.76.0",
    "@aws-sdk/protocol-http": "^3.58.0",
    "@aws-sdk/signature-v4": "^3.58.0",
    "@aws-sdk/client-secrets-manager": "^3.258.0",
    "node-fetch": "2",
    "config": "^3.3.9",
    "uuid": "^9.0.0",
    "graphql": "^16.6.0",
    "graphql-tag": "^2.12.6",
    "@sentry/serverless": "^7.32.1",
    "lodash": "^4.17.21",
    "hash-object": "^0.1.7"
  },
  "devDependencies": {}
}
```

**Comment by mithunkavullakandiyil** [comment]
### amplify --version
```
10.6.2
```


### From "./amplify/logs"

```
2023-01-25T22:32:21.678Z|info : amplify pull core  {"debug":true,"yes":true}
2023-01-25T22:32:21.712Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2023-01-25T22:32:23.861Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["***amplify"])
2023-01-25T22:32:23.862Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"ap-south-1","output":"json","role_arn":"[***]***:role/[***]***","source_profile":"***"}])
2023-01-25T22:32:23.862Z|info : amplify-provider-awscloudformation.system-config-manager.getCacheFilePath(["C:\\Users\\***\\.amplify\\awscloudformation"])
2023-01-25T22:32:23.868Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["***amplify"])
2023-01-25T22:32:23.869Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"ap-south-1","output":"json","role_arn":"[***]***:role/[***]***","source_profile":"***"}])
2023-01-25T22:32:23.869Z|info : amplify-provider-awscloudformation.system-config-manager.getCacheFilePath(["C:\\Users\\***\\.amplify\\awscloudformation"])
2023-01-25T22:32:23.872Z|info : amplify-provider-awscloudformation.zip-util.downloadZip.s3.getFile([{"Key":"[***]rent-[***]ud-[***]d.zip"},null])
2023-01-25T22:32:23.873Z|info : amplify-provider-awscloudformation.aws-s3.s3.getFile([{"Key":"[***]rent-[***]ud-[***]d.zip","Bucket":"[***]ify-[***]ga-[***]ev-[***]952-[***]ment"}])
2023-01-25T22:32:31.775Z|error : Failed to extract zip file: 
ZipExtractFault: Failed to extract zip file: 
2023-01-25T22:35:54.008Z|info : amplify push core  {"yes":true}
2023-01-25T22:35:54.047Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2023-01-25T22:35:55.919Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["***amplify"])
2023-01-25T22:35:55.920Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"ap-south-1","output":"json","role_arn":"[***]***:role/[***]***","source_profile":"***"}])
2023-01-25T22:35:55.920Z|info : amplify-provider-awscloudformation.system-config-manager.getCacheFilePath(["C:\\Users\\***\\.amplify\\awscloudformation"])
2023-01-25T22:35:55.926Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["***amplify"])
2023-01-25T22:35:55.927Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"ap-south-1","output":"json","role_arn":"[***]***:role/[***]***","source_profile":"***"}])
2023-01-25T22:35:55.927Z|info : amplify-provider-awscloudformation.system-config-manager.getCacheFilePath(["C:\\Users\\***\\.amplify\\awscloudformation"])
2023-01-25T22:35:55.930Z|info : amplify-provider-awscloudformation.zip-util.downloadZip.s3.getFile([{"Key":"[***]rent-[***]ud-[***]d.zip"},null])
2023-01-25T22:35:55.931Z|info : amplify-provider-awscloudformation.aws-s3.s3.getFile([{"Key":"[***]rent-[***]ud-[***]d.zip","Bucket":"[***]ify-[***]ga-[***]ev-[***]952-[***]ment"}])
2023-01-25T22:36:06.931Z|error : Failed to extract zip file: 
ZipExtractFault: Failed to extract zip file: 
```
### Diagnose Report

````
amplify diagnose --send-report

Learn more at https://docs.amplify.aws/cli/reference/diagnose/

✅ Report saved: C:\Users\***\AppData\Local\Temp\***\report-1674687337957.zip

√ Done

Project Identifier: ca6a2f26a84952cd245c528e6fccb8f0

PS C:\Users\***\Projects\***\projects\***>

**Comment by josefaidt** [comment]
Hey @mithunkavullakandiyil :wave: thanks for the clarification and for providing those details! While we work to improve and resolve this issue, as a workaround, can you try moving the project higher in the directory tree?

**Comment by mithunkavullakandiyil** [comment]
> Hey @mithunkavullakandiyil 👋 thanks for the clarification and for providing those details! While we work to improve and resolve this issue, as a workaround, can you try moving the project higher in the directory tree?

@josefaidt Thanks for the quick workaround. I placed the project under C:\ drive (C:\<PROJECT_FOLDER>) and seems working without any error.

**Comment by josefaidt** [comment]
Hey @mithunkavullakandiyil glad to hear that worked for you! Apologies for any inconvenience this might have caused. Given this is now resolved I will close this issue in favor of tracking the existing item, #10032
