### ISSUE TITLE
Interactions manual setup throws "ReferenceError: log is not defined"

### ISSUE THREAD

**Issue by tannerabread** [aws-amplify/amplify-cli#11871]
### If applicable, what version of Node.js are you using?

16.18.1

### Amplify CLI Version

10.5.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

N/A

### Describe the bug

The "start from scratch" option for "Would you like to start with a sample chatbot or start from scratch" on the `amplify add interactions` wizard, the wizard fails at the "Would you like to choose an Amazon built-in slot type, a slot type you've already made, or create a new slot type?" when selecting "Amazon built-in slot type"

### Expected behavior

I would expect to be able to continue with the wizard and create Lex resources

### Reproduction steps

Input the following options into the wizard:
```bash
amplify add interactions
Using service: Lex, provided by: awscloudformation

Welcome to the Amazon Lex chatbot wizard
You will be asked a series of questions to help determine how to best construct your chatbot.

? Provide a friendly resource name that will be used to label this category in t
he project: lexa3daa010
? Would you like to start with a sample chatbot or start from scratch? Start fro
m scratch
? Enter a name for your bot: MyBot
? Choose an output voice: None. This is only a text based application.
? After how long should the session timeout (in minutes)? 5
? Please indicate if your use of this bot is subject to the Children\'s Online Pr
ivacy Protection Act (COPPA).
Learn more: https://www.ftc.gov/tips-advice/business-center/guidance/complying-c
oppa-frequently-asked-questions No

First create an intent for your new chatbot. An intent represents an action that the user wants to perform.

? Give a unique name for the new intent: find
? Enter a sample utterance (spoken or typed phrase that invokes your intent. e.g
. Book a hotel) find a hotel
? Would you like to add another utterance? No

Now, add a slot to your intent. A slot is data the user must provide to fulfill the intent.

? Enter a name for your slot (e.g. Location) location
? Would you like to choose an Amazon built-in slot type, a slot type you\'ve alre
ady made, or create a new slot type? Amazon built-in slot type
```

### Project Identifier

645ac3e16d19fd70102ef450db8fdc2b

### Log output

<details>

```
# Put your logs below this line

ReferenceError: log is not defined
    at /snapshot/repo/build/node_modules/amplify-provider-awscloudformation/lib/utility-functions.js:355:7
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async getSlotType (/snapshot/repo/build/node_modules/amplify-category-interactions/lib/provider-utils/awscloudformation/service-walkthroughs/lex-walkthrough.js:598:32)
    at async addSlot (/snapshot/repo/build/node_modules/amplify-category-interactions/lib/provider-utils/awscloudformation/service-walkthroughs/lex-walkthrough.js:540:17)
    at async addIntent (/snapshot/repo/build/node_modules/amplify-category-interactions/lib/provider-utils/awscloudformation/service-walkthroughs/lex-walkthrough.js:390:22)
    at async configure (/snapshot/repo/build/node_modules/amplify-category-interactions/lib/provider-utils/awscloudformation/service-walkthroughs/lex-walkthrough.js:304:20)
    at async Object.executeAmplifyCommand (/snapshot/repo/build/node_modules/amplify-category-interactions/lib/index.js:81:3)
    at async executePluginModuleCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:142:5)
    at async executeCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:40:9)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:153:5)
There was an error adding the interactions resource

```

</details>

### Additional information

Selecting the "Start with a sample" option was able to successfully create resources

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Was able to reproduce this issue, marking as bug.
