### ISSUE TITLE
unexpected stack trace for cyclic dependency error when attempting to grant auth access to lambda

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/amplify-cli#11881]
### How did you install the Amplify CLI?

pnpm

### If applicable, what version of Node.js are you using?

18

### Amplify CLI Version

10.6.2

### What operating system are you using?

mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

n/a

### Describe the bug

```
➜  ay update function
? Select the Lambda function you want to update 928762ef6d3PostConfirmation
General information
- Name: 928762ef6d3PostConfirmation
- Runtime: nodejs

Resource access permission
- Not configured

Scheduled recurring invocation
- Not configured

Lambda layers
- Not configured

Environment variables:
- Not configured

Secrets configuration
- Not configured

? Which setting do you want to update? Resource access permissions
? Select the categories you want this function to have access to. auth
? Auth has 2 resources in this project. Select the one you would like your Lambda 
to access 928762ef6d3
? Select the operations you want to permit on 928762ef6d3 read

You can access the following resource attributes as environment variables from your Lambda function
        AUTH_928762EF6D3_USERPOOLID
Error: Cannot add 928762ef6d3PostConfirmation due to a cyclic dependency
    at checkForCyclicDependencies (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/update-amplify-meta.js:248:15)
    at AmplifyToolkit.updateamplifyMetaAfterResourceUpdate [as _updateamplifyMetaAfterResourceUpdate] (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/update-amplify-meta.js:155:9)
    at updateFunctionResource (/snapshot/repo/build/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/index.js:157:29)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.executeAmplifyCommand (/snapshot/repo/build/node_modules/amplify-category-function/lib/index.js:270:5)
    at async executePluginModuleCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:142:5)
    at async executeCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:40:9)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:119:5)
There was an error adding the function resource
```

### Expected behavior

instead of

```
Error: Cannot add 928762ef6d3PostConfirmation due to a cyclic dependency
    at checkForCyclicDependencies (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/update-amplify-meta.js:248:15)
    at AmplifyToolkit.updateamplifyMetaAfterResourceUpdate [as _updateamplifyMetaAfterResourceUpdate] (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/update-amplify-meta.js:155:9)
    at updateFunctionResource (/snapshot/repo/build/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/index.js:157:29)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.executeAmplifyCommand (/snapshot/repo/build/node_modules/amplify-category-function/lib/index.js:270:5)
    at async executePluginModuleCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:142:5)
    at async executeCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:40:9)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:119:5)
There was an error adding the function resource
```

print

```
Error: Cannot add 928762ef6d3PostConfirmation due to a cyclic dependency
```

additionally, it would be nice if this error were printed when validating the options selected, blocking us from proceeding to select a CRUD permission:

```
? Select the categories you want this function to have access to. 
 ◯ api
❯◉ auth
 ◯ custom
 ◯ function
 ◯ storage
Unable to add auth due to a cyclic dependency
```

### Reproduction steps

1. `amplify init -y`
2. `amplify add auth` > manual configuration
3. accept most defaults, add a PostConfirmation trigger
4. update the PostConfirmation trigger with `amplify update function`
5. select Resource Access Permissions
6. attempt to grant auth read access
7. observe stack trace with error "There was an error adding the function resource"

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Marking this as bug as I was able to reproduce the issue. If a Lambda function trigger already has access to a auth user pool, the resource access option should not provide a selection again.
