### ISSUE TITLE
Build fails after adding Google OAuth to existing email based authentication

### ISSUE THREAD

**Issue by jcjollant** [aws-amplify/amplify-cli#11986]
### How did you install the Amplify CLI?

`amplify upgrade` from a previous `npm install -g @aws-amplify/cli`

### If applicable, what version of Node.js are you using?

v18.12.1

### Amplify CLI Version

10.7.1

### What operating system are you using?

Windows 11

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

When Google Auth is added to an existing App using email, build fails with the following error:
`InvalidParameterException: The provider Google does not exist for User Pool us-east-1_xyz`

When I added Google to Authentication, the following changes were made to `cli-input.json`
```
    "authProvidersUserPool": [
      "Google"
    ],
    "hostedUIProviderMeta": "[{\"ProviderName\":\"Google\",\"authorize_scopes\":\"openid email profile\",\"AttributeMapping\":{\"email\":\"email\",\"username\":\"sub\"}}]",
```
and
```
    "permissions": [],
    "oAuthMetadata": "{\"AllowedOAuthFlows\":[\"code\"],\"AllowedOAuthScopes\":[\"phone\",\"email\",\"openid\",\"profile\",\"aws.cognito.signin.user.admin\"],\"CallbackURLs\":[\"http://localhost:5173/\",\"https://dev.somedomain.net/\",\"https://prod.somedomain.net/\"],\"LogoutURLs\":[\"http://localhost:5173/\",\"https://dev.somedomain.net/\",\"https://prod.somedomain.net/\"]}"
```

### Expected behavior

Successful build

### Reproduction steps

1. Add authentication without social provider, requesting email field
2. deploy (build works)
3. Add Google Social provider to your backend
4. deploy (build fails)

### Project Identifier

Project Identifier: 0a9decdb9419720eb51b7021324415c7

### Log output

<details>
Here is the log from OAuthCustomResource Lambda execution
```
# Put your logs below this line
INIT_START Runtime Version: nodejs:14.v28	Runtime Version ARN: arn:aws:lambda:us-east-1::runtime:be4a32da6aeaa90583d476cb548ced79ae2c9aa7b14a45129198bbd13ea5822d
--
START RequestId: 3ed93258-72cf-4ea2-b9e3-d0396ec49284 Version: $LATEST
2023-02-10T22:51:13.219Z	3ed93258-72cf-4ea2-b9e3-d0396ec49284	INFO	{  UserPoolId: 'us-east-1_sFTwXDVzL',  AllowedOAuthFlows: [ 'code' ],  AllowedOAuthFlowsUserPoolClient: true,  AllowedOAuthScopes: [    'phone',    'email',    'openid',    'profile',    'aws.cognito.signin.user.admin'  ],  CallbackURLs: [    'http://localhost:5173/',    'https://dev.somedomain.net/',    'https://prod.somedomain.net/'  ],  LogoutURLs: [    'http://localhost:5173/',    'https://dev.somedomain.net/',    'https://digilogs.somedomain.net/'  ],  SupportedIdentityProviders: [ 'Google', 'COGNITO' ]}
2023-02-10T22:51:14.339Z	3ed93258-72cf-4ea2-b9e3-d0396ec49284	INFO	InvalidParameterException: The provider Google does not exist for User Pool us-east-1_sFTwXDVzL.    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12)    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
2023-02-10T22:51:14.340Z	3ed93258-72cf-4ea2-b9e3-d0396ec49284	INFO	Response body: {     "Status": "FAILED",     "Reason": "See the details in CloudWatch Log Stream: 2023/02/10/[$LATEST]a7ce103f144e453e90d495caecd934e7",     "PhysicalResourceId": "2023/02/10/[$LATEST]a7ce103f144e453e90d495caecd934e7",     "StackId": "arn:aws:cloudformation:us-east-1:263218251294:stack/amplify-digilogs-production-220413-authdigilogs42aaf660-1U036SDDDOZCT/0426db30-a995-11ed-87b2-0a91e4c1fd73",     "RequestId": "516bbf8c-2bc5-4dee-9621-19fc86feca8b",     "LogicalResourceId": "OAuthCustomResourceInputs",     "NoEcho": false,     "Data": {         "err": {             "message": "The provider Google does not exist for User Pool us-east-1_sFTwXDVzL.",             "code": "InvalidParameterException",             "time": "2023-02-10T22:51:14.281Z",             "requestId": "903387ee-428b-4cd4-8620-153797aef881",             "statusCode": 400,             "retryable": false,             "retryDelay": 58.37642406199948         }     } }
2023-02-10T22:51:14.486Z	3ed93258-72cf-4ea2-b9e3-d0396ec49284	INFO	Status code: 200
2023-02-10T22:51:14.487Z	3ed93258-72cf-4ea2-b9e3-d0396ec49284	INFO	Status message: OK
END RequestId: 3ed93258-72cf-4ea2-b9e3-d0396ec49284
REPORT RequestId: 3ed93258-72cf-4ea2-b9e3-d0396ec49284	Duration: 1297.71 ms	Billed Duration: 1298 ms	Memory Size: 128 MB	Max Memory Used: 80 MB	Init Duration: 455.29 ms

```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by jcjollant** [comment]
I have been able to fix this by manually editing the corresponding User Pool. I guess the learning is Amplify is not updating  Cognito upon `amplify auth update`.

**Comment by wvidana** [comment]
`amplify push` actually works, at least on version `10.8.1`. The problem is the CI/CD can't setup google oauth, I get the same problem. Seems an issue with the CLI on headless mode, some step or circular dependency is not handled well. I made this comment on a similar issue on a different repo, but my gut tells me this is a problem with headless mode rather than the amplify console itself https://github.com/aws-amplify/amplify-studio/issues/472#issuecomment-1611614050

**Comment by danielvouch** [comment]
@wvidana how did you get around this in CI/CD?

**Comment by wvidana** [comment]
> @wvidana how did you get around this in CI/CD?

I had to manually create the provider in cognito. If your are creating a new user pool I'd recommend doing it in 3 steps:

1. Create the pool with amplify with no oauth setup
2. Manually add the google provider
3. Push remaining changes related to google oauth
