### ISSUE TITLE
amplify init gives error when using for iOS

### ISSUE THREAD

**Issue by rohandubal** [aws-amplify/amplify-cli#1201]
**Describe the bug**
When I run amplify init on my iOS project, CLI errors out saying failed to initialize

**To Reproduce**

1. amplify init
2. select iOS as provider
3. follow prompts

**Expected behavior**
successful initialization

**Screenshots**
```
✔ Successfully created initial AWS cloud resources for deployments.
✔ Initialized provider successfully.
✖ There was an error initializing your environment.
init failed
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at getResourceOutputs (/usr/local/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/get-resource-outputs.js:18:10)
    at Object.onCategoryOutputsChange (/usr/local/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/on-category-outputs-change.js:24:29)
    at initializeEnv (/usr/local/lib/node_modules/@aws-amplify/cli/src/lib/initialize-env.js:79:27)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
```

**Desktop (please complete the following information):**
 - OS: High Sierra

**Additional context**
I was still able to push resources after failed init

**Comment by kaustavghosh06** [comment]
The fix for this has been rolled out and published to npm.
