### ISSUE TITLE
interactive prompts do not work in Git Bash for Windows

### ISSUE THREAD

**Issue by danmoran5** [aws-amplify/amplify-cli#12029]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

19.6.0

### Amplify CLI Version

10.7.3

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

When trying to add storage to the Amplify app, I receive the following error:

An error occurred when adding the storage resource
Error: Cannot prompt for [Provide a friendly name for your resource that will be used to label this category in the project:] in a non-interactive shell
    at AmplifyPrompter.prompterShim [as prompter] (C:\snapshot\repo\build\node_modules\amplify-prompts\lib\prompter.js:217:19)
    at AmplifyPrompter.input (C:\snapshot\repo\build\node_modules\amplify-prompts\lib\prompter.js:107:43)
    at askResourceNameQuestion (C:\snapshot\repo\build\node_modules\@aws-amplify\amplify-category-storage\lib\provider-utils\awscloudformation\service-walkthroughs\s3-questions.js:99:57)
    at addWalkthrough (C:\snapshot\repo\build\node_modules\@aws-amplify\amplify-category-storage\lib\provider-utils\awscloudformation\service-walkthroughs\s3-walkthrough.js:92:82)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.executeAmplifyCommand (C:\snapshot\repo\build\node_modules\@aws-amplify\amplify-category-storage\lib\index.js:305:3)
    at async executePluginModuleCommand (C:\snapshot\repo\build\node_modules\@aws-amplify\cli-internal\lib\execution-manager.js:142:5)
    at async executeCommand (C:\snapshot\repo\build\node_modules\@aws-amplify\cli-internal\lib\execution-manager.js:40:9)
    at async Object.run (C:\snapshot\repo\build\node_modules\@aws-amplify\cli-internal\lib\index.js:117:5)

### Expected behavior

I expected to be able to provide an answer to each question

### Reproduction steps

type 'amplify add storage' in CLI
Select 'Content (Images, audio video, etc.)
Then the error occurs

### Project Identifier

3631b60caad5e0f34bd616fe1a9f7600

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @danmoran5 :wave: thanks for raising this! Would you mind providing the full set of steps to receive this error? Typically you will see this in environments such as CI/CD pipelines if attempting to run interactive commands like `amplify add storage`. What terminal are you using?

**Comment by danmoran5** [comment]
@josefaidt Apologies for not being more thorough! 

1. Navigate to <drive>:/users/<username>/amplifyapp 
2. Right-click and choose "Git Bash here"
3. enter "amplify add storage" cmd and execute
4. It allows me to make the first selection(Select 'Content (Images, audio video, etc.)
5. Error hits when I should be able to choose the next value:[Provide a friendly name for your resource that will be used to label this category in the project:] 

Please let me know if any other info is needed

**Comment by josefaidt** [comment]
Hey @danmoran5 thanks for clarifying and no worries! It seems there is an issue with the CLI's prompter library and Git Bash for Windows. Can you try a different shell with [Windows Subsystem for Linux](https://learn.microsoft.com/en-us/windows/wsl/install), Git Bash with [Windows Terminal](https://apps.microsoft.com/store/detail/windows-terminal/9N0DX20HK701?hl=en-us&gl=us&rtc=1), or from running `amplify` directly in PowerShell?

**Comment by danmoran5** [comment]
@josefaidt That worked! I ran it directly from PowerShell and had no errors

**Comment by danmoran5** [comment]
@josefaidt Thanks!

**Comment by sblei** [comment]
I see the same issue (with self-built prompts using various rust crates). The program works fine in the powershell (and in terminals on my linux laptop), but prompts bug out in Git Bash for Windows.
