### ISSUE TITLE
amplify init fails with no obvious cause

### ISSUE THREAD

**Issue by mikemerritt** [aws-amplify/amplify-cli#1205]
**Describe the bug**
When running `amplify init` in a javascript project it fails out with `There was an error initializing your environment.` with the following stacktrace. The IAM user has the AdministratorAccess policy.

```
✔ Successfully created initial AWS cloud resources for deployments.
✔ Initialized provider successfully.
✖ There was an error initializing your environment.
init failed
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at getResourceOutputs (/usr/local/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/get-resource-outputs.js:18:10)
    at Object.onCategoryOutputsChange (/usr/local/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/on-category-outputs-change.js:24:29)
    at initializeEnv (/usr/local/lib/node_modules/@aws-amplify/cli/src/lib/initialize-env.js:79:27)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

**To Reproduce**
1. Run `amplify init` on an existing javascript project with the following responses.

```
? Enter a name for the project test-app
? Enter a name for the environment master
? Choose your default editor: Visual Studio Code
? Choose the type of app that you're building javascript
Please tell us about your project
? What javascript framework are you using react
? Source Directory Path:  src
? Distribution Directory Path: public
? Build Command:  yarn build
? Start Command: yarn start
```
2. Not using AWS profile, supplied accessKey and secretAccessKey and region via the prompt.

3. Wait and it will fail out with the above error and stacktrace.

**Expected behavior**
It should successfully initialize the amplify project.

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.4
 - Browser N/A
 - Version 1.5.0

**Additional context**
Here is the full terminal output

```
> amplify init
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the project test-app
? Enter a name for the environment master
? Choose your default editor: Visual Studio Code
? Choose the type of app that you're building javascript
Please tell us about your project
? What javascript framework are you using react
? Source Directory Path:  src
? Distribution Directory Path: public
? Build Command:  yarn build
? Start Command: yarn start
Using default provider  awscloudformation

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html

? Do you want to use an AWS profile? No
? accessKeyId:  [removed]
? secretAccessKey:  [removed]
? region:  us-west-2
⠦ Initializing project in the cloud...

CREATE_IN_PROGRESS UnauthRole                    AWS::IAM::Role             Wed Apr 03 2019 18:16:01 GMT-0500 (Central Daylight Time) Resource creation Initiated
CREATE_IN_PROGRESS AuthRole                      AWS::IAM::Role             Wed Apr 03 2019 18:16:01 GMT-0500 (Central Daylight Time)
CREATE_IN_PROGRESS DeploymentBucket              AWS::S3::Bucket            Wed Apr 03 2019 18:16:00 GMT-0500 (Central Daylight Time)
CREATE_IN_PROGRESS UnauthRole                    AWS::IAM::Role             Wed Apr 03 2019 18:16:00 GMT-0500 (Central Daylight Time)
CREATE_IN_PROGRESS test-app-20190403181555 AWS::CloudFormation::Stack Wed Apr 03 2019 18:15:56 GMT-0500 (Central Daylight Time) User Initiated
⠙ Initializing project in the cloud...

CREATE_IN_PROGRESS DeploymentBucket AWS::S3::Bucket Wed Apr 03 2019 18:16:02 GMT-0500 (Central Daylight Time) Resource creation Initiated
⠏ Initializing project in the cloud...

CREATE_IN_PROGRESS AuthRole AWS::IAM::Role Wed Apr 03 2019 18:16:02 GMT-0500 (Central Daylight Time) Resource creation Initiated
⠧ Initializing project in the cloud...

CREATE_COMPLETE AuthRole   AWS::IAM::Role Wed Apr 03 2019 18:16:19 GMT-0500 (Central Daylight Time)
CREATE_COMPLETE UnauthRole AWS::IAM::Role Wed Apr 03 2019 18:16:18 GMT-0500 (Central Daylight Time)
⠧ Initializing project in the cloud...

CREATE_COMPLETE test-app-20190403181555 AWS::CloudFormation::Stack Wed Apr 03 2019 18:16:25 GMT-0500 (Central Daylight Time)
CREATE_COMPLETE DeploymentBucket              AWS::S3::Bucket            Wed Apr 03 2019 18:16:22 GMT-0500 (Central Daylight Time)
✔ Successfully created initial AWS cloud resources for deployments.
✔ Initialized provider successfully.
✖ There was an error initializing your environment.
init failed
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at getResourceOutputs (/usr/local/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/get-resource-outputs.js:18:10)
    at Object.onCategoryOutputsChange (/usr/local/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/on-category-outputs-change.js:24:29)
    at initializeEnv (/usr/local/lib/node_modules/@aws-amplify/cli/src/lib/initialize-env.js:79:27)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

**Comment by kaustavghosh06** [comment]
Related: #1201 

We fixed this bug in v 1.5.1. Please re-install the CLI (with the latest version) and let me know if you're still seeing this.

**Comment by dkwl93** [comment]
Sorry to bump an old issue but I'm still getting this in version `1.10.0`. I'm using node `12.7.0` if that helps

**Comment by dkwl93** [comment]
```
✔ Successfully created initial AWS cloud resources for deployments.
✔ Initialized provider successfully.
✖ There was an error initializing your environment.
init failed
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at getCustomConfigs (/Users/daniellee/.nvm/versions/node/v10.4.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-javascript/lib/frontend-config-creator.js:49:10)
    at createAWSExports (/Users/daniellee/.nvm/versions/node/v10.4.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-javascript/lib/frontend-config-creator.js:40:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Similar but different issue
