### ISSUE TITLE
`add`, `remove` commands should exit gracefully outside an Amplify project directory

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/amplify-cli#12107]
### How did you install the Amplify CLI?

pnpm

### If applicable, what version of Node.js are you using?

18

### Amplify CLI Version

11.0.0-beta.8

### What operating system are you using?

mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

n/a

### Describe the bug

`amplify add <category>` and `amplify remove <category>` produce various errors while attempting to retrieve project files that do not exist.

```
aws-amplify/reproductions/a12089 
➜  amplify add function
🛑 File at path: '/Users/josef/Documents/projects/aws-amplify/reproductions/amplify/.config/local-env-info.json' does not exist

Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

Session Identifier: a39c7b06-e3e4-49d5-8077-e9d1b1f3ca9a
✖ An unexpected error has occurred, opt in to send an error report to AWS Amplify with non-sensitive project configuration files. Confirm  (y/N) · 

🛑 Failed to report error: 

aws-amplify/reproductions/a12089 
➜  amplify remove predictions
🛑 File at path: '/Users/josef/Documents/projects/aws-amplify/reproductions/amplify/backend/amplify-meta.json' does not exist

Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

Session Identifier: c96d097a-256a-4d5c-9f0f-cfd359f7f6b8
✖ An unexpected error has occurred, opt in to send an error report to AWS Amplify with non-sensitive project configuration files. Confirm  (y/N) · 

🛑 Failed to report error: 
```

```
➜  amplify add predictions
✔ Please select from one of the categories below · Identify
Error: File at path: '/Users/josef/Documents/projects/aws-amplify/reproductions/amplify/.config/project-config.json' does not exist
    at Function.readJson (/snapshot/repo/build/node_modules/amplify-cli-core/lib/jsonUtilities.js:44:19)
    at StateManager.getData (/snapshot/repo/build/node_modules/amplify-cli-core/lib/state-manager/stateManager.js:327:56)
    at StateManager.getProjectConfig (/snapshot/repo/build/node_modules/amplify-cli-core/lib/state-manager/stateManager.js:107:25)
    at AmplifyToolkit.getProjectDetails [as _getProjectDetails] (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/get-project-details.js:7:59)
    at checkIfAuthExists (/snapshot/repo/build/node_modules/@aws-amplify/amplify-category-predictions/lib/provider-utils/awscloudformation/prediction-category-walkthroughs/identify-walkthrough.js:481:15)
    at addWalkthrough (/snapshot/repo/build/node_modules/@aws-amplify/amplify-category-predictions/lib/provider-utils/awscloudformation/prediction-category-walkthroughs/identify-walkthrough.js:54:11)
    at Object.addResource (/snapshot/repo/build/node_modules/@aws-amplify/amplify-category-predictions/lib/provider-utils/awscloudformation/index.js:22:10)
    at /snapshot/repo/build/node_modules/@aws-amplify/amplify-category-predictions/lib/commands/predictions/add.js:26:31
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.executeAmplifyCommand (/snapshot/repo/build/node_modules/@aws-amplify/amplify-category-predictions/lib/index.js:77:3)
    at async executePluginModuleCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:136:5)
    at async executeCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:34:9)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:116:5)
An error occurred when adding the predictions resource
```

### Expected behavior

CLI should provide a helpful error:

```
➜  amplify add predictions
Unable to detect Amplify project. To get started, run `amplify init` to create a new Amplify project, or run `amplify pull` to pull an existing Amplify project.
```

### Reproduction steps

1. `amplify add predictions`
2. `amplify add function`
3. `amplify remove predictions`
4. `amplify remove function`

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
I have an amplify project in the parent directory which was causing this, closing
