### ISSUE TITLE
CLI is unable to load config if profile name contains a dot (`.`)

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/amplify-cli#12100]
### How did you install the Amplify CLI?

pnpm

### If applicable, what version of Node.js are you using?

18

### Amplify CLI Version

11.0.0-beta.7

### What operating system are you using?

mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

n/a

### Describe the bug

After updating a model's primary key and attempting to push we are presented with a vague error after the schema compiles but before the CloudFormation updates start to print:

```
➜  amplify push --allow-destructive-graphql-schema-updates --yes --debug
Not pulling components because this project is not configured with the "react" framework.
⠏ Fetching updates to backend environment: dev from the cloud.Overrides functionality is not implemented for this category
⠴ Fetching updates to backend environment: dev from the cloud.
⚠️  WARNING: Some types do not have authorization rules configured. That means all create, read, update, and delete operations are denied on these types:
	 - Todo
	 - Todo2
Learn more about "@auth" authorization rules here: https://docs.amplify.aws/cli/graphql/authorization-rules
⠦ Fetching updates to backend environment: dev from the cloud.✅ GraphQL schema compiled successfully.

Edit your schema at /Users/josef/Documents/projects/aws-amplify/reproductions/a1268/amplify/backend/api/a1268/schema.graphql or place .graphql files in a directory at /Users/josef/Documents/projects/aws-amplify/reproductions/a1268/amplify/backend/api/a1268/schema
Overrides functionality is not implemented for this category
✔ Successfully pulled backend environment dev from the cloud.
⠹ Building resource api/a1268
⚠️  WARNING: Some types do not have authorization rules configured. That means all create, read, update, and delete operations are denied on these types:
	 - Todo
	 - Todo2
Learn more about "@auth" authorization rules here: https://docs.amplify.aws/cli/graphql/authorization-rules
⠸ Building resource api/a1268✅ GraphQL schema compiled successfully.

Edit your schema at /Users/josef/Documents/projects/aws-amplify/reproductions/a1268/amplify/backend/api/a1268/schema.graphql or place .graphql files in a directory at /Users/josef/Documents/projects/aws-amplify/reproductions/a1268/amplify/backend/api/a1268/schema

    Current Environment: dev
    
┌──────────┬────────────────┬───────────┬───────────────────┐
│ Category │ Resource name  │ Operation │ Provider plugin   │
├──────────┼────────────────┼───────────┼───────────────────┤
│ Api      │ a1268          │ Update    │ awscloudformation │
├──────────┼────────────────┼───────────┼───────────────────┤
│ Hosting  │ amplifyhosting │ No Change │                   │
└──────────┴────────────────┴───────────┴───────────────────┘

⚠️  WARNING: Some types do not have authorization rules configured. That means all create, read, update, and delete operations are denied on these types:
	 - Todo
	 - Todo2
Learn more about "@auth" authorization rules here: https://docs.amplify.aws/cli/graphql/authorization-rules
✅ GraphQL schema compiled successfully.

Edit your schema at /Users/josef/Documents/projects/aws-amplify/reproductions/a1268/amplify/backend/api/a1268/schema.graphql or place .graphql files in a directory at /Users/josef/Documents/projects/aws-amplify/reproductions/a1268/amplify/backend/api/a1268/schema
⠼ Building resource api/a1268
⚠️  WARNING: Some types do not have authorization rules configured. That means all create, read, update, and delete operations are denied on these types:
	 - Todo
	 - Todo2
Learn more about "@auth" authorization rules here: https://docs.amplify.aws/cli/graphql/authorization-rules
⠴ Building resource api/a1268✅ GraphQL schema compiled successfully.

Edit your schema at /Users/josef/Documents/projects/aws-amplify/reproductions/a1268/amplify/backend/api/a1268/schema.graphql or place .graphql files in a directory at /Users/josef/Documents/projects/aws-amplify/reproductions/a1268/amplify/backend/api/a1268/schema
🛑 Could not load configuration

Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

DeploymentError: Could not load configuration
    at Function.createInstance (/snapshot/repo/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/iterative-deployment/deployment-manager.js:515:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/push-resources.js:288:35)
    at async Promise.all (index 0)
    at async providersPush (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/push-resources.js:160:5)
    at async AmplifyToolkit.pushResources [as _pushResources] (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/push-resources.js:135:13)
    at async Object.executeAmplifyCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:187:9)
    at async executePluginModuleCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:136:5)
    at async executeCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:34:9)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:116:5)

undefined == true
AssertionError [ERR_ASSERTION]: undefined == true
    at Function.createInstance (/snapshot/repo/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/iterative-deployment/deployment-manager.js:512:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/push-resources.js:288:35)
    at async Promise.all (index 0)
    at async providersPush (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/push-resources.js:160:5)
    at async AmplifyToolkit.pushResources [as _pushResources] (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/push-resources.js:135:13)
    at async Object.executeAmplifyCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:187:9)
    at async executePluginModuleCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:136:5)
    at async executeCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:34:9)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:116:5)

Session Identifier: 8e5bbc37-3973-4018-824d-1a871c837c9a
```

### Expected behavior

push succeeds

### Reproduction steps

I had a few other things hooked up here such as automated deployments with Amplify Hosting, but this is reproducible using a split schema definition

1. create a project `amplify init -y`
2. add a GraphQL API `amplify add api` > GraphQL
3. delete the single `schema.graphql` in favor of two separate schema files in the `schema/` directory: `Todo.graphql` and `Todo2.graphql`
	```graphql
	type Todo2 @model {
	  id: ID!
	  name: String!
	  description: String
	}
	```
4. push with `amplify push -y`
5. change the primary key of one of the models
	```diff
	type Todo2 @model {
	  id: ID!
	+ cpk: String! @primaryKey
	  name: String!
	  description: String
	}
 	```
6. push with `amplify push --allow-destructive-graphql-schema-updates --yes`
7. observe error

### Project Identifier

6eb2e5ca4610f067a938060bf5ef796a

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
closing as a duplicate of #10525 . @zirkelc would you mind filing a [separate bug report](https://github.com/aws-amplify/amplify-category-api/issues/new/choose) to track your occurrence? it appears this may be similar but different root causes. Do you have a `region` set for your chosen AWS profile in `~/.aws/config`?

```
[profile default]
region=us-east-1
```
