### ISSUE TITLE
amplify push fails with "Branch dev not found"

### ISSUE THREAD

**Issue by iwasinnam** [aws-amplify/amplify-cli#12143]
### How did you install the Amplify CLI?

curl

### If applicable, what version of Node.js are you using?

v16.13.2

### Amplify CLI Version

10.8.1

### What operating system are you using?

Ubuntu 22.04

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

I added a custom domain. Everything else I do with the cli

### Describe the bug

Amplify publish fails with "Branch dev not found"

### Expected behavior

Amplify publish should succeed

### Reproduction steps

cd to project root
run amplify publish

### Project Identifier

7f8ec3547b5ee21ce3e9d43a0ecd405c

### Log output

<details>

```
# Put your logs below this line
11:49 $ amplify publish
✔ Successfully pulled backend environment dev from the cloud.

    Current Environment: dev
    
┌──────────┬─────────────────┬───────────┬───────────────────┐
│ Category │ Resource name   │ Operation │ Provider plugin   │
├──────────┼─────────────────┼───────────┼───────────────────┤
│ Custom   │ customResources │ Update    │ awscloudformation │
├──────────┼─────────────────┼───────────┼───────────────────┤
│ Auth     │ userPoolGroups  │ No Change │ awscloudformation │
├──────────┼─────────────────┼───────────┼───────────────────┤
│ Auth     │ aruggaauth      │ No Change │ awscloudformation │
├──────────┼─────────────────┼───────────┼───────────────────┤
│ Api      │ arugga          │ No Change │ awscloudformation │
├──────────┼─────────────────┼───────────┼───────────────────┤
│ Function │ pullRobotData   │ No Change │ awscloudformation │
├──────────┼─────────────────┼───────────┼───────────────────┤
│ Function │ pushRobotData   │ No Change │ awscloudformation │
├──────────┼─────────────────┼───────────┼───────────────────┤
│ Function │ sunset          │ No Change │ awscloudformation │
├──────────┼─────────────────┼───────────┼───────────────────┤
│ Function │ hobo            │ No Change │ awscloudformation │
├──────────┼─────────────────┼───────────┼───────────────────┤
│ Function │ IotToSQS        │ No Change │ awscloudformation │
├──────────┼─────────────────┼───────────┼───────────────────┤
│ Function │ SQSToIoT        │ No Change │ awscloudformation │
├──────────┼─────────────────┼───────────┼───────────────────┤
│ Hosting  │ amplifyhosting  │ No Change │ awscloudformation │
└──────────┴─────────────────┴───────────┴───────────────────┘
✔ Are you sure you want to continue? (Y/n) · yes

Deployment completed.
Deploying root stack arugga [ =================================------- ] 10/12
	amplify-arugga-dev-145035      AWS::CloudFormation::Stack     UPDATE_COMPLETE_CLEANUP_IN_PR… Thu Mar 02 2023 11:50:50…     
	functionSQSToIoT               AWS::CloudFormation::Stack     UPDATE_COMPLETE                Thu Mar 02 2023 11:50:16…     
	autharuggaauth                 AWS::CloudFormation::Stack     UPDATE_COMPLETE                Thu Mar 02 2023 11:50:16…     
	functionhobo                   AWS::CloudFormation::Stack     UPDATE_COMPLETE                Thu Mar 02 2023 11:50:16…     
	functionsunset                 AWS::CloudFormation::Stack     UPDATE_COMPLETE                Thu Mar 02 2023 11:50:16…     
	functionIotToSQS               AWS::CloudFormation::Stack     UPDATE_COMPLETE                Thu Mar 02 2023 11:50:16…     
	apiarugga                      AWS::CloudFormation::Stack     UPDATE_COMPLETE                Thu Mar 02 2023 11:50:41…     
	authuserPoolGroups             AWS::CloudFormation::Stack     UPDATE_COMPLETE                Thu Mar 02 2023 11:50:19…     
	functionpushRobotData          AWS::CloudFormation::Stack     UPDATE_COMPLETE                Thu Mar 02 2023 11:50:43…     
	functionpullRobotData          AWS::CloudFormation::Stack     UPDATE_COMPLETE                Thu Mar 02 2023 11:50:44…     
	customcustomResources          AWS::CloudFormation::Stack     UPDATE_COMPLETE                Thu Mar 02 2023 11:50:47…     
Deployed custom customResources [ ======================================== ] 17/17

Deployment state saved successfully.

GraphQL transformer version: 1

Publish started for amplifyhosting

> front-end@0.1.0 build
> vue-cli-service build


⠋  Building for production...

 WARNING  Compiled with 2 warnings                                                                                                              11:51:52 AM

 warning  

asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  js/chunk-7d19c458.c44ac31a.js (3.26 MiB)
  js/chunk-vendors.da47f175.js (2.25 MiB)

 warning  

entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  app (2.31 MiB)
      js/chunk-vendors.da47f175.js
      css/app.4f8189af.css
      js/app.3a4612bf.js


  File                                      Size                                                  Gzipped

  dist/js/chunk-7d19c458.c44ac31a.js        3339.63 KiB                                           450.03 KiB
  dist/js/chunk-vendors.da47f175.js         2301.38 KiB                                           637.49 KiB
  dist/js/chunk-2283db18.6ffb5636.js        136.28 KiB                                            27.52 KiB
  dist/js/polyfills-core-js.f6039027.js     77.35 KiB                                             25.18 KiB
  dist/js/chunk-37038b9e.5b691c65.js        65.53 KiB                                             15.82 KiB
  dist/js/app.3a4612bf.js                   55.15 KiB                                             14.43 KiB
  dist/js/polyfills-dom.9cde2f64.js         36.74 KiB                                             5.86 KiB
  dist/js/chunk-2d208840.2a0646eb.js        34.94 KiB                                             12.88 KiB
  dist/js/chunk-2d226365.644e199d.js        34.36 KiB                                             5.80 KiB
  dist/js/chunk-3c14aece.ffc06cb1.js        24.37 KiB                                             6.29 KiB
  dist/js/chunk-ccf5388e.a57867c1.js        23.23 KiB                                             6.49 KiB
  dist/js/chunk-6ed2ef0c.6b2d6a25.js        19.45 KiB                                             6.14 KiB
  dist/js/chunk-f969a952.72fe4566.js        19.03 KiB                                             6.62 KiB
  dist/js/chunk-d45e23a8.8f3083cb.js        18.15 KiB                                             5.37 KiB
  dist/js/chunk-5eb09c95.73c5ed8b.js        17.26 KiB                                             5.21 KiB
  dist/js/home.ee014c43.js                  16.93 KiB                                             5.16 KiB
  dist/js/chunk-1c1f32f8.5bcf5274.js        16.90 KiB                                             5.39 KiB
  dist/js/chunk-e5bb031e.4838dd2c.js        16.28 KiB                                             6.12 KiB
  dist/js/chunk-c4d414ba.f9833530.js        15.98 KiB                                             5.17 KiB
  dist/js/chunk-73798ed0.d1aa1009.js        14.04 KiB                                             4.71 KiB
  dist/js/chunk-6242f2c2.137c1af2.js        13.28 KiB                                             4.98 KiB
  dist/js/chunk-65368c18.612e5c22.js        12.13 KiB                                             3.71 KiB
  dist/js/chunk-62175330.4ae9ab8a.js        10.54 KiB                                             3.89 KiB
  dist/js/chunk-621a6c74.57ff2751.js        9.81 KiB                                              3.60 KiB
  dist/js/chunk-62421cd4.70198f80.js        9.66 KiB                                              3.57 KiB
  dist/js/chunk-62199c8c.f2a98d64.js        9.60 KiB                                              3.31 KiB
  dist/js/polyfills-css-shim.78f54a4c.js    8.57 KiB                                              3.40 KiB
  dist/js/chunk-6218ddf4.b5878203.js        7.91 KiB                                              2.80 KiB
  dist/js/chunk-2d2105ef.bcc9741f.js        6.93 KiB                                              2.53 KiB
  dist/js/chunk-2d0dd0bc.f8389f3c.js        5.69 KiB                                              2.41 KiB
  dist/js/chunk-35d5ca8f.8c9a60d1.js        4.13 KiB                                              1.49 KiB
  dist/js/chunk-2d22dbc9.ddaa1fe7.js        3.66 KiB                                              1.15 KiB
  dist/js/chunk-2d0d7838.e968d875.js        3.13 KiB                                              1.43 KiB
  dist/js/chunk-2d0a4629.86d1609c.js        2.07 KiB                                              0.84 KiB
  dist/js/chunk-2d0b722b.0fce066d.js        1.99 KiB                                              0.70 KiB
  dist/js/chunk-2d0abfcf.677bcef1.js        1.48 KiB                                              0.66 KiB
  dist/js/chunk-2d22c8fe.5fd00250.js        0.91 KiB                                              0.46 KiB
  dist/js/chunk-2d228cf2.1eb3282c.js        0.90 KiB                                              0.49 KiB
  dist/js/chunk-2d208de0.1408bea0.js        0.54 KiB                                              0.35 KiB
  dist/css/app.4f8189af.css                 12.07 KiB                                             2.64 KiB
  dist/css/home.7a97bfef.css                7.83 KiB                                              1.97 KiB
  dist/css/chunk-65368c18.f2de9d0c.css      4.06 KiB                                              1.12 KiB
  dist/css/chunk-7d19c458.3722d636.css      0.70 KiB                                              0.36 KiB

  Images and other types of assets omitted.

 DONE  Build complete. The dist directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html
      
✔ Zipping artifacts completed.
✖ Deployment failed! Please report an issue on the Amplify Console GitHub issue tracker at https://github.com/aws-amplify/amplify-console/issues.
🛑 Branch dev not found.

Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

Session Identifier: d91b8d5d-9843-4c23-889a-1dab5f9c332f


```

</details>

### Additional information
Earlier I downgraded nodejs from 18.12.1 to 16.13.2 (using 'sudo n') because I kept getting `ERR_OSSL_EVP_UNSUPPORTED` when running `npm run serve` locally to test the front-end.
```
10% building 2/5 modules 3 active /home/iwasinnam/code/front-end/node_modules/webpack/hot/dev-server.jsnode:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/iwasinnam/code/front-end/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/iwasinnam/code/front-end/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/iwasinnam/code/front-end/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/iwasinnam/code/front-end/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/iwasinnam/code/front-end/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/iwasinnam/code/front-end/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/iwasinnam/code/front-end/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/home/iwasinnam/code/front-end/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/iwasinnam/code/front-end/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/iwasinnam/code/front-end/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /home/iwasinnam/code/front-end/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

```
After I downgraded this crash stopped
_No response_

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @iwasinnam :wave: thanks for raising this! I'm not able to reproduce this without a custom domain set up. How was the custom domain added?

**Comment by iwasinnam** [comment]
We have a domain registered in GoDaddy. The root domain points to our website (outside of AWS). I created a subdomain that refers to the Amplify hosted frontend as instructed [here](https://docs.aws.amazon.com/amplify/latest/userguide/to-add-a-custom-domain-managed-by-godaddy.html).

**Comment by iwasinnam** [comment]
We overcame the problem. It seems this happened after we migrated our 'dev' env from one region to the other. However, team-provider-info.json in several git branches was still pointing to the old env, and during merge conflict we picked the old env.
