### ISSUE TITLE
Amplify function build throw "Command failed with exit code 1: yarn --no-bin-links --production"

### ISSUE THREAD

**Issue by edisonthk** [aws-amplify/amplify-cli#12156]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v18.14.2

### Amplify CLI Version

10.8.1

### What operating system are you using?

Ubuntu

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Enable access to unauthenticated identities in Federated Identities page.

### Describe the bug

The following error occurred when I attempted to build the added function by `amplify function build`.
```
Error: Packaging lambda function failed with the error 
Command failed with exit code 1: yarn --no-bin-links --production
```

### Expected behavior

`amplify function build` command called successfully.

### Reproduction steps

1. Move to repository root directory.
2. amplify function add                                                                            
? Select which capability you want to add: Lambda function (serverless function)
? Provide an AWS Lambda function name: s3trigger
? Choose the runtime that you want to use: NodeJS
? Choose the function template that you want to use: Hello World

Available advanced settings:
- Resource access permissions
- Scheduled recurring invocation
- Lambda layers configuration
- Environment variables configuration
- Secret values configuration

? Do you want to configure advanced settings? No
? Do you want to edit the local lambda function now? No
Successfully added resource s3trigger locally.

3. amplify function build

### Project Identifier

2bc8eecf179b5a1f301a49637a1f8529

### Log output

<details>

```
ubuntu@dev $> amplify function add                                                                            
? Select which capability you want to add: Lambda function (serverless function)
? Provide an AWS Lambda function name: s3trigger
? Choose the runtime that you want to use: NodeJS
? Choose the function template that you want to use: Hello World

Available advanced settings:
- Resource access permissions
- Scheduled recurring invocation
- Lambda layers configuration
- Environment variables configuration
- Secret values configuration

? Do you want to configure advanced settings? No
? Do you want to edit the local lambda function now? No
Successfully added resource s3trigger locally.

Next steps:
Check out sample function code generated in <project-dir>/amplify/backend/function/s3trigger/src
"amplify function build" builds all of your functions currently in the project
"amplify mock function <functionName>" runs your function locally
To access AWS resources outside of this Amplify app, edit the /home/ubuntu/myrepository/amplify/backend/function/s3trigger/custom-policies.json
"amplify push" builds all of your local backend resources and provisions them in the cloud
"amplify publish" builds all of your local backend and front-end resources (if you added hosting category) and provisions them in the cloud

ubuntu@dev $> amplify function build                                                                          
✔ Are you sure you want to continue building the resources? (y/N) · yes

Error: Packaging lambda function failed with the error 
Command failed with exit code 1: yarn --no-bin-links --production
    at runPackageManager (/snapshot/repo/build/node_modules/amplify-nodejs-function-runtime-provider/lib/utils/legacyBuild.js:86:19)
    at installDependencies (/snapshot/repo/build/node_modules/amplify-nodejs-function-runtime-provider/lib/utils/legacyBuild.js:61:5)
    at Object.buildResource [as build] (/snapshot/repo/build/node_modules/amplify-nodejs-function-runtime-provider/lib/utils/legacyBuild.js:39:9)
    at buildFunction (/snapshot/repo/build/node_modules/@aws-amplify/amplify-category-function/lib/provider-utils/awscloudformation/utils/buildFunction.js:32:40)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/amplify-category-function/lib/commands/function/build.js:23:43)
    at async Object.executeAmplifyCommand (/snapshot/repo/build/node_modules/@aws-amplify/amplify-category-function/lib/index.js:277:5)
    at async executePluginModuleCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:144:5)
    at async executeCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:42:9)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:120:5)
There was an error building the function resources
```

</details>

### Additional information

Repository is `next.js@13.1.6` and `npm install` on project root.

There are no errors on following command, I wonder why above errors occur when using `amplify function build`

```
cd <project-root>/amplify/backend/function/s3trigger/src
yarn --no-bin-links --production
```

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @edisonthk :wave: thanks for raising this! Are you only experiencing this issue on the newly created S3 trigger function? If you run the same command with `--debug` does it print a stack trace with a resolution?

Additionally, can you confirm your Function's lockfile is up to date by `cd`-ing into your Function's `src/` directory and running `yarn install`?

**Comment by josefaidt** [comment]
Closing due to inactivity

**Comment by curb47** [comment]
@josefaidt I am getting this same issue. Here is the stack trace:

DeploymentFault: Packaging lambda function failed with the error 
Command was killed with SIGSEGV (Segmentation fault): yarn --no-bin-links --production
    at Object.run (/snapshot/repo/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/push-resources.js:458:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Promise.all (index 0)
    at async providersPush (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/push-resources.js:160:5)
    at async AmplifyToolkit.pushResources (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/push-resources.js:134:13)
    at async Object.executeAmplifyCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:189:9)
    at async executePluginModuleCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:135:5)
    at async executeCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:33:9)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:117:5)

Packaging lambda function failed with the error 
Command was killed with SIGSEGV (Segmentation fault): yarn --no-bin-links --production
Error: Packaging lambda function failed with the error 
Command was killed with SIGSEGV (Segmentation fault): yarn --no-bin-links --production
    at runPackageManager (/snapshot/repo/build/node_modules/amplify-nodejs-function-runtime-provider/lib/utils/legacyBuild.js:86:19)
    at installDependencies (/snapshot/repo/build/node_modules/amplify-nodejs-function-runtime-provider/lib/utils/legacyBuild.js:61:5)
    at Object.buildResource [as build] (/snapshot/repo/build/node_modules/amplify-nodejs-function-runtime-provider/lib/utils/legacyBuild.js:39:9)
    at buildFunction (/snapshot/repo/build/node_modules/@aws-amplify/amplify-category-function/lib/provider-utils/awscloudformation/utils/buildFunction.js:32:40)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async prepareResource (/snapshot/repo/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/push-resources.js:522:33)
    at async Promise.all (index 0)
    at async prepareBuildableResources (/snapshot/repo/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/push-resources.js:518:3)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/push-resources.js:237:5)
    at async Promise.all (index 0)
    at async providersPush (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/push-resources.js:160:5)
    at async AmplifyToolkit.pushResources (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/push-resources.js:134:13)
    at async Object.executeAmplifyCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:189:9)
    at async executePluginModuleCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:135:5)
    at async executeCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:33:9)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:117:5)
