### ISSUE TITLE
upgrade to 10.8.1 returning failed to get profile credentials

### ISSUE THREAD

**Issue by adcanis** [aws-amplify/amplify-cli#12174]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

19.6.0

### Amplify CLI Version

10.8.2

### What operating system are you using?

mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no

### Describe the bug

upgrade to 10.8.2 fails to get profile credentials when performing amplify task. Sends Authorization request multiple times despite currently being logged in before failing with error:

"Failed to get profile credentials. Unexpected token A in JSON at position 0"

### Expected behavior

should allow amplify commands the same as v10.8.0

### Reproduction steps

1. aws-vault exec <account name>
2. authenticate
3. update schema
4. amplify push -y

### Project Identifier

9004eca0-6404-4a91-9fae-e5a8474cb213

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by adcanis** [comment]
Anything? This was working on v10.8.1

**Comment by josefaidt** [comment]
Hey @adcanis :wave: thanks for raising this! Can you confirm your Amplify CLI version? The issue description mentions 10.8.2 though the `latest` is 10.8.1

**Comment by adcanis** [comment]
sorry yes your right. 10.8.1 and was working on 10.8.0

**Comment by josefaidt** [comment]
Ah no worries just wanted to clarify 🙂 do you only experience this issue in this one project or are you able to execute commands outside the project?

**Comment by adcanis** [comment]
This is the only project using SSO credentials.

**Comment by josefaidt** [comment]
Thanks for clarifying @adcanis , I'm going to take a further look at this one 🙂

**Comment by josefaidt** [comment]
Hey @adcanis while we investigate this further can you run the same command with `--debug` to print the stack trace?

**Comment by adcanis** [comment]
```
Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1

Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

BackendPullFault: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1
    at syncCurrentCloudBackend (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/commands/push.js:59:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/commands/push.js:73:5)
    at async Object.executeAmplifyCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:181:9)
    at async executePluginModuleCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:144:5)
    at async executeCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:42:9)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:120:5)

Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1
Error: connect EHOSTDOWN 169.254.169.254:80 - Local (192.168.1.141:50654)
    at internalConnect (net.js:934:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:452:18)
    at net.js:1022:9
    at processTicksAndRejections (internal/process/task_queues.js:77:11)

Session Identifier: b7bf36f2-a7eb-45fa-bda9-c18dc8f0eeb2
```

**Comment by josefaidt** [comment]
Hey @adcanis thanks for pasting that output. I have not been able to reproduce this issue with just credentials on environment variables. Does aws-vault create a `config` or `credentials` file at `~/.aws/`?

as a note, this may be fixed with https://github.com/aws-amplify/amplify-cli/pull/12139

**Comment by adcanis** [comment]
@josefaidt `aws-vault` doesn't create a new config file or credentials file. Instead, it stores the temporary session credentials in memory. This has worked in multiple projects. I've also cleared `aws-vault` and used `aws sso login --profile <profile name>` and received the same multiple authentication pages throughout the push process before returning the same error

**Comment by adcanis** [comment]
```
{
  "dev": {
    "configLevel": "project",
    "useProfile": true,
    "profileName": "account-sso-dev"
  }
}
```

**Comment by adcanis** [comment]
@josefaidt if it helps. The issue seems to be related to my API. I've re-pulled the backend, making a small change to my Lambda and `amplify push` was successful. The API fails with error 
> Failed to get profile credentials. Unexpected token A in JSON at position 0

**Comment by josefaidt** [comment]
Hey @adcanis thanks for posting that! Can you try running the command with the `AWS_SDK_LOAD_CONFIG` env var set to `1`?

```
AWS_SDK_LOAD_CONFIG=1 amplify push -y
```

**Comment by adcanis** [comment]
@josefaidt same thing

**Comment by adcanis** [comment]
@josefaidt so some more findings. I added s3 just to see the behaviour on another resource, and it added it just fine.  I then pushed each resource independently. s3  and lambda fine. Cognito errors with the 
> Failed to get profile credentials
Unexpected token A in JSON at position 0

but shows no change when `amplify status` is ran after and appears updated in console.
The API still errors with the above and does NOT update. It also shows s3 create, cognito update in console, despite those resources being created and without change. 

Hope this helps a bit more.

**Comment by adcanis** [comment]
any further information as this is still an issue?

**Comment by josefaidt** [comment]
Hey @adcanis apologies for the delay here. This should be fixed as of the latest version of Amplify CLI (11.0.2), can you try upgrading and see if this alleviates the issue with resolving credentials?

**Comment by adcanis** [comment]
@josefaidt upgraded and received:

> Failed to get profile credentials
Unexpected token A in JSON at position 0

This was after successfully logging in with both `aws sso login --profile account-sso-dev` and `aws-vault exec accont-sso-dev`

session identifier: c2016373-da23-4404-a552-46f6f3af9f05
my credentials file:
```
[account-sso-dev]
aws_access_key_id=*****
aws_secret_access_key=*****
aws_session_token=******
```

my config:
```
[profile account-sso-dev]
sso_start_url=https://*******.awsapps.com/start
sso_region=ca-central-1
sso_account_id=**********
sso_role_name= *********
credential_process=aws sso login --profile account-sso-dev
region=ca-central-1
output=json
```

**Comment by josefaidt** [comment]
Captured stack trace output for debugging

```
ProfileConfigurationError: Failed to get profile credentials
    at loadConfigurationForEnv (/snapshot/repo/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/configuration-manager.js:777:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.loadConfiguration (/snapshot/repo/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/configuration-manager.js:718:18)
    at async Object.configureWithCreds (/snapshot/repo/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/aws-utils/aws.js:34:18)
    at async Object.getConfiguredAWSClient (/snapshot/repo/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/index.js:281:3)
    at async getAWSClient (/snapshot/repo/build/node_modules/@aws-amplify/amplify-console-hosting/lib/utils/client-factory.js:18:10)
    at async Object.getAmplifyClient (/snapshot/repo/build/node_modules/@aws-amplify/amplify-console-hosting/lib/utils/client-factory.js:4:15)
    at async Object.generateTableContentForApp (/snapshot/repo/build/node_modules/@aws-amplify/amplify-console-hosting/lib/utils/table-utils.js:10:25)
    at async Object.status (/snapshot/repo/build/node_modules/@aws-amplify/amplify-console-hosting/lib/hosting/index.js:164:3)
    at async status (/snapshot/repo/build/node_modules/@aws-amplify/amplify-console-hosting/lib/index.js:29:5)
    at async showAmplifyConsoleHostingStatus (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/commands/status.js:62:13)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/commands/status.js:53:9)
    at async Object.executeAmplifyCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:189:9)
    at async executePluginModuleCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:135:5)
    at async executeCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:33:9)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:117:5)

Unexpected token A in JSON at position 0
ProcessCredentialsProviderFailure: Unexpected token A in JSON at position 0
    at /snapshot/repo/build/node_modules/aws-sdk/lib/credentials/process_credentials.js:142:13
    at ChildProcess.exithandler (child_process.js:374:7)
    at ChildProcess.emit (events.js:400:28)
    at ChildProcess.emit (domain.js:475:12)
    at maybeClose (internal/child_process.js:1088:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
⠧ Fetching AWS Amplify Console domains
Session Identifier: 3e45598e-b810-4408-9fd0-bf623bde9788
```

**Comment by josefaidt** [comment]
Hey @adcanis the team is actively investigating this issue for a fix

**Comment by josefaidt** [comment]
Hey @adcanis this was closed from automation but has not quite been released. I've added `pending-release` and will circle back shortly!

**Comment by adcanis** [comment]
@josefaidt thanks, I've added a new issue if you'd like to remove it [#7789](https://github.com/aws/aws-cli/issues/7789) it may outline the issue a little better

**Comment by adcanis** [comment]
@josefaidt have we had any updates yet as this is still effecting 9 of my 12 accounts.

**Comment by adcanis** [comment]
Just a follow up. The issue seems to be with aws sso. When `aws sso login --profile <>` is ran to login, it does not update the `/.aws/credentials` with the new AWS Access Key ID, AWS Secret Access Key, AWS Session Token. This throws the error experienced above. 

What i've been doing now is logging in, then pasting the new credentials found in `Command line or programmatic access` and performing the amplify commands after.

**Comment by OperationalFallacy** [comment]
```
npx amplify --version
11.0.5
```

I've tried to use amplify first time and immediately ended up on this issue. Dear maintainers, this is the first thing customer sees when interacting with the library. I'm sorry to say this, but it's pretty terrible experience.

Every other web library I've used had flawless initial auth flow (usually oauth2 with GitHub).

**Comment by lazpavel** [comment]
Hi @OperationalFallacy, sorry for late response. I am not able to reproduce the issue using latest Amplify CLI, can you provide more details about the issue you're having?

1. which command is failing for you? can you provide the stack trace printed when you execute the command with `--debug` flag?
2. can you provide a set of steps to reproduce the issue in a newly created project?
3. can you share with us at amplify-cli@amazon.com your `~/.aws/config` file, please remove any sensitive information
4. is your issue with selecting an AWS profile on `amplify init` or you're experiencing issues with the Social Sign-in Auth flow as described here: https://docs.amplify.aws/lib/auth/social/q/platform/js/

Thank you

**Comment by lazpavel** [comment]
Closing, as we cannot reproduce any longer using latest CLI, if you're still experiencing the issue please create a new issue.

**Comment by OperationalFallacy** [comment]
> Hi @OperationalFallacy, sorry for late response. I am not able to reproduce the issue using latest Amplify CLI, can you provide more details about the issue you're having?
> 
> 1. which command is failing for you? can you provide the stack trace printed when you execute the command with `--debug` flag?
> 2. can you provide a set of steps to reproduce the issue in a newly created project?
> 3. can you share with us at [amplify-cli@amazon.com](mailto:amplify-cli@amazon.com) your `~/.aws/config` file, please remove any sensitive information
> 4. is your issue with selecting an AWS profile on `amplify init` or you're experiencing issues with the Social Sign-in Auth flow as described here: https://docs.amplify.aws/lib/auth/social/q/platform/js/
> 
> Thank you

Here's a full output on a freshly installed amplify package, new project.

```
amplify init
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the project testapi
The following configuration will be applied:

Project information
| Name: testapi
| Environment: dev
| Default editor: Visual Studio Code
| App type: javascript
| Javascript framework: none
| Source Directory Path: src
| Distribution Directory Path: dist
| Build Command: npm run-script build
| Start Command: npm run-script start

? Initialize the project with the above configuration? No
? Enter a name for the environment dev
? Choose your default editor: Visual Studio Code
✔ Choose the type of app that you're building · javascript
Please tell us about your project
? What javascript framework are you using react
? Source Directory Path:  src
? Distribution Directory Path: build
? Build Command:  npm run-script build
? Start Command: npm run-script start
Using default provider  awscloudformation
? Select the authentication method you want to use: AWS profile

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

? Please choose the profile you want to use testprofile-sso-dev
🛑 Failed to get profile credentials
Cannot read properties of undefined (reading 'accessKeyId')

Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

Session Identifier: 83461e3a-9008-4ee5-92ae-8c376a5e103f
```

There is nothing special about profile, standard SSO 

```
[profile testprofile-sso-dev]
sso_start_url = https://test.awsapps.com/start#/
sso_region = us-east-1
sso_account_id = xxx
sso_role_name = Developer
region = us-east-1
output = json
```

and its logged in and working properly, I've tried some simple operations like aws s3 ls

**Comment by thantos** [comment]
Same issue as @OperationalFallacy. SSO profile is working for the SDK and CDK.

**Comment by OperationalFallacy** [comment]
![image](https://github.com/aws-amplify/amplify-cli/assets/62673610/58640cc8-a1cb-44ed-a2d8-08500e018f79)

Amplify team, can you at least fix this error message?

Explain users what config it is, what credentials, and how to fix it.
Also you should explain why do they need to to use AWS_CONFIG_FILE or set AWS_SDK_LOAD_CONFIG=1

It's even more annoying to see this "helpful" message then the broken auth itself.

The auth workflow for local development remains an absolutely terrible experience on the platform.
