### ISSUE TITLE
New install now has dependency on external libraries?

### ISSUE THREAD

**Issue by bwobbones** [aws-amplify/amplify-cli#1223]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Describe the bug**
When I do a brand new installation of the latest release (1.5.3) running the `amplify` command gives an error saying that it is missing dependencies

**To Reproduce**
1. Install version with `npm i -g @aws-amplify/cli@1.5.3`
2. Execute with`amplify function`

Shows this error:
```
/Users/xxx/.nvm/versions/node/v11.12.0/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/index.js:13
    throw up;
    ^

Error: Cannot find module 'amplify-graphql-docs-generator'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:649:15)
    at Function.Module._load (internal/modules/cjs/loader.js:575:25)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/xxx/.nvm/versions/node/v11.12.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/commands/statements.js:4:23)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
```

**Expected behavior**
Commands to execute correcly

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS and Alpine Linux through Docker
 - Browser 
 - Version 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kaustavghosh06** [comment]
@bwobbones 1.5.3 is experimental has an unstable tag associated tag.
 Please use `npm install -g @aws-amplify/cli` to install the latest stable version of the CLI (v 1.5.1).

**Comment by bwobbones** [comment]
Ahh sorry I missed that!

**Comment by yuth** [comment]
closing the issue. Feel free to comment if this didn't help
