### ISSUE TITLE
environment name not available in hook event data on `amplify env checkout` (`event.amplify.environment.envName`)

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/amplify-cli#12291]
### How did you install the Amplify CLI?

pnpm

### If applicable, what version of Node.js are you using?

18

### Amplify CLI Version

11.0.2

### What operating system are you using?

mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

n/a

### Describe the bug

I'm using a [collection of hooks](https://gist.github.com/josefaidt/cd031d1f4b1eb375b937de0dc958fe9a) to track progress of reproductions with git, and I noticed after executing `amplify env checkout main` to checkout the `main` env, the hook failed with

```console
➜  amplify env checkout main

----- 🪝 pre-checkout execution start -----
🛑 file:///Users/josef/Documents/projects/aws-amplify/reproductions/a12289/amplify/hooks/auto-git.js:49
  const message = `${stage} ${command} ${environment.envName}`
                                                     ^

TypeError: Cannot read properties of undefined (reading 'envName')
    at handler (file:///Users/josef/Documents/projects/aws-amplify/reproductions/a12289/amplify/hooks/auto-git.js:49:54)
    at autogit (file:///Users/josef/Documents/projects/aws-amplify/reproductions/a12289/amplify/hooks/auto-git.js:64:3)
    at file:///Users/josef/Documents/projects/aws-amplify/reproductions/a12289/amplify/hooks/pre-checkout.js:2:1
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v18.15.0


🛑 pre-checkout hook script exited with exit code 1

🛑 exiting Amplify process...
```

### Expected behavior

`envName` is available

### Reproduction steps

1. `amplify init -y`
2. `amplify env add --envName next --yes`
3. clone the linked gist to the `amplify/hooks` directory
4. run `amplify env checkout <some-environment>`
5. observe error

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @ykethan thanks for trying it out. I don't remember running into this since creating these hooks, but it came up yesterday for the first time. We can close this as `not-reproducible` since you're not able to reproduce

**Comment by ykethan** [comment]
@josefaidt did you do anything else in the steps, just to be sure before I can close the issue.

**Comment by josefaidt** [comment]
@ykethan no but I just realized my `amplify-meta.json` file was missing (I messed up my gitignore at one point and accidentally committed a few things, and I removed them all but must have deleted that locally)
