### ISSUE TITLE
🛑 EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by pensievelabs** [aws-amplify/amplify-cli#12357]
### How did you install the Amplify CLI?

sudo npm install

### If applicable, what version of Node.js are you using?

v16.17.0

### Amplify CLI Version

11.0.3

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

I did not make any changes to the cloud resources managed by Amplify. But I started hitting this error when I added custom resolvers successfully **using** Amplify and updated to this version. 

### Describe the bug

I added custom resolver (worked), upgraded amplify and started seeing this error.

```
sudo amplify push --debug
Not pulling components because this project is not configured with the "react" framework.
✖ There was an error pulling the backend environment dev.
🛑 EISDIR: illegal operation on a directory, read

Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

BackendPullFault: EISDIR: illegal operation on a directory, read
    at syncCurrentCloudBackend (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/commands/push.js:54:15)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/commands/push.js:69:5)
    at async Object.executeAmplifyCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:189:9)
    at async executePluginModuleCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:135:5)
    at async executeCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:33:9)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:117:5)

EISDIR: illegal operation on a directory, read
Error: EISDIR: illegal operation on a directory, read

Session Identifier: ba5a54dc-de3e-4453-9e79-7c0db17dc9ec
```

### Expected behavior

No error and push is successful.

### Reproduction steps

I do not think I have deterministic steps to reproduce on any machine. But here's what I did:

1. I added a custom resolver
2. Updated amplify to the latest version

I have tried:
1. Uninstalling and reinstalling amplify
2. Deleting the existing resolver using amplify
3. Pulling the backend (works with no error), but subsequent push still fails with the same error.

### Project Identifier

Project Identifier: 39e7b3c691dcd8118082b45b0b2f34fd

### Log output

<details>

```
# Put your logs below this line
2023-03-31T17:35:19.491Z|info : amplify push core  {"debug":true,"yes":false}
2023-03-31T17:35:19.534Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2023-03-31T17:35:20.344Z|error : EISDIR: illegal operation on a directory, read
BackendPullFault: EISDIR: illegal operation on a directory, read
2023-03-31T17:35:51.512Z|info : amplify pull core  {"debug":true,"yes":false}
2023-03-31T17:35:51.547Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2023-03-31T17:35:52.555Z|info : amplify-provider-awscloudformation.zip-util.downloadZip.s3.getFile([{"Key":"[***]rent-[***]ud-[***]d.zip"},null])
2023-03-31T17:35:52.555Z|info : amplify-provider-awscloudformation.aws-s3.s3.getFile([{"Key":"[***]rent-[***]ud-[***]d.zip","Bucket":"[***]ify-[***]alok-[***]ev-[***]720-[***]ment"}])
2023-03-31T17:35:53.259Z|info : amplify-provider-awscloudformation.initialize-env.run.cfn.updateamplifyMetaFileWithStackOutputs([{"StackName":"[***]ify-[***]alok-[***]ev-[***]720"}])
2023-03-31T17:35:53.261Z|info : amplify-provider-awscloudformation.aws-cfn.updateamplifyMetaFileWithStackOutputs.cfn.listStackResources([{"StackName":"[***]ify-[***]alok-[***]ev-[***]720"}])
2023-03-31T17:35:53.498Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]ify-[***]alok-[***]ev-[***]720"}])
2023-03-31T17:35:53.629Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]49:stack/[***]ify-[***]alok-[***]ev-[***]720-[***]ialok-[***]A3TRAZ/[***]ee30-[***]fd-[***]ec-[***]45-[***]e784f"}])
2023-03-31T17:35:53.631Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]49:stack/[***]ify-[***]alok-[***]ev-[***]720-[***]viaLok-[***]AW4S1K/[***]23f0-[***]1e-[***]ed-[***]37-[***]9b5ef"}])
2023-03-31T17:35:53.632Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]49:stack/[***]ify-[***]alok-[***]ev-[***]720-[***]alokimgs-[***]WOJWSU/[***]89c0-[***]ff-[***]ed-[***]ad-[***]96a8b"}])
2023-03-31T17:35:53.753Z|info : amplify-provider-awscloudformation.aws-s3.s3.getFile([{"Key":"[***]ify-[***]json","Bucket":"[***]ify-[***]alok-[***]ev-[***]720-[***]ment"}])
2023-03-31T17:36:02.538Z|info : amplify push core  {"debug":true,"yes":false}
2023-03-31T17:36:02.585Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2023-03-31T17:36:03.198Z|error : EISDIR: illegal operation on a directory, read
BackendPullFault: EISDIR: illegal operation on a directory, read
2023-03-31T17:37:30.759Z|info : amplify version core
2023-03-31T17:40:01.024Z|info : amplify diagnose core  {"send-report":true,"yes":false}
2023-03-31T17:40:01.070Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
~                                                                                                                                                                     

```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @pensievelabs :wave: thanks for raising this! We typically recommend installing without `sudo` to mitigate permissions issues, and if you are experiencing `EACCES` issues installing via npm without sudo please follow [this doc from npm](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally)

Are you able to push successfully without `sudo`?

**Comment by pensievelabs** [comment]
Thank you for responding.

Amplify does not work well without sudo for me. However, this is not EACCESS it is EISDIR instead. It is expecting something to be a file but it is a directory.

**Comment by josefaidt** [comment]
Hey @pensievelabs what issues do you have using the Amplify CLI without sudo? `EACCES` is typically the error you'll encounter when attempting to install dependencies globally when Node/npm was installed with sudo

**Comment by pensievelabs** [comment]
Generally, for most commands there's no error but no action:

<user>@<MachineName> <Dir> % `amplify push`
<user>@<MachineName> <Dir> % 

However, yes, in other case it is EACCES.

To clarify: are you saying that my original error: EISDIR will also get fixed if I run the command without `sudo` by following the steps mentioned above?

**Comment by pensievelabs** [comment]
Tried this without sudo by installing node version manager and reinstalling with amplify cli. I am seeing the same error:

```
amplify push --debug

Not pulling components because this project is not configured with the "react" framework.
✖ There was an error pulling the backend environment dev.
🛑 EISDIR: illegal operation on a directory, read

Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

BackendPullFault: EISDIR: illegal operation on a directory, read
    at syncCurrentCloudBackend (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/commands/push.js:54:15)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/commands/push.js:69:5)
    at async Object.executeAmplifyCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:189:9)
    at async executePluginModuleCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:135:5)
    at async executeCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:33:9)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:117:5)

EISDIR: illegal operation on a directory, read
Error: EISDIR: illegal operation on a directory, read


```

**Comment by josefaidt** [comment]
Hey @pensievelabs thanks for clarifying and for checking on that! How was the custom resolver added to the project? Was this created in the API directory's `resolvers/` directory?

**Comment by pensievelabs** [comment]
Yes, it was added here: <pathToDir>/amplify/backend/api/<app>/resolvers/

**Comment by josefaidt** [comment]
Hey @pensievelabs thanks for clarifying! Is there any nested structure within the `resolvers/` directory? I was able to reproduce this if I added a nested directory 
![image](https://user-images.githubusercontent.com/5033303/229876187-24b51bdc-c515-475a-90d1-676b6cc96e11.png)
![image](https://user-images.githubusercontent.com/5033303/229876232-417515a5-9caf-4407-859e-41ae2e66c2de.png)

**Comment by josefaidt** [comment]
>  ran the command to build the resolver using amplify push while I was in that folder on terminal.

This makes sense as I was not able to push with this nested directory to cause the issue you are seeing where `pull` no longer works. How are these resolvers written and built?

> But now anytime I pull amplify, I get the src folder in resolvers folder with some code for resolver.

Can you try downloading your `#current-cloud-backend.zip`, unzip, remove the offending directory, then re-zip and re-upload? (more steps are outlined here https://gist.github.com/josefaidt/be56f2a8a821b084b66e40ce51e20b44)

**Comment by matthewberryman** [comment]
@josefaidt I was able to use your gist to successfully undo a wonky backend that had the same error that @pensievelabs encountered. 
Like @pensievelabs, I am using the guide from https://stackoverflow.com/questions/57084650/how-do-i-add-items-to-a-list/57088993#57088993 , which I have used successfully before, but this time encountered an issue (I must have missed a step)

**Comment by 99electronic** [comment]
I had same problem, created folder in api/resolvers and actually it let me push it to the cloud, since then I could never push, because it would first pull and tried to use the folder as file (hence this error) I had to manually download #current-cloud-backend.zip folder from cloud (s3) edit the api/resolvers to remove the folder, zip it back upload and that fixed it.
