### ISSUE TITLE
Cannot read property 'name' of undefined when amplify publish

### ISSUE THREAD

**Issue by xalepo4** [aws-amplify/amplify-cli#12495]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.15.0

### Amplify CLI Version

11.0.5

### What operating system are you using?

Ubuntu 22.04

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

When run amplify publish after a long time appears the error Cannot read property 'name' of undefined.

### Expected behavior

Publish the application to development/production site.

### Reproduction steps

1. Run amplify publish
2. Wait for frontend compilation (Angular).
3. After a long time appears the error: Cannot read property 'name' of undefined.

### Project Identifier

94fea9fa9c2ef410fc180035881a9e8d

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @xalepo4 :wave: thanks for raising this! As we begin to look at this in more depth would you mind re-running this command with `--debug` and post the stack trace output?

**Comment by xalepo4** [comment]
Hello @josefaidt , I attach here the debug logs.
[debug.txt](https://github.com/aws-amplify/amplify-cli/files/11266096/debug.txt)

**Comment by josefaidt** [comment]
Hey @xalepo4 thanks for posting that! Copying here for reference

```
✔ Zipping artifacts completed.
⠋ Deploying build artifacts to the Amplify Console..Job Timeout before succeeded
✖ Deployment failed! Please report an issue on the Amplify Console GitHub issue tracker at https://github.com/aws-amplify/amplify-console/issues.
🛑 Cannot read property 'name' of undefined

Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

UnknownFault: Cannot read property 'name' of undefined
    at genericErrorToAmplifyException (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/amplify-exception-handler.js:125:49)
    at handleException (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/amplify-exception-handler.js:26:28)
    at process.<anonymous> (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:48:93)
    at process.emit (events.js:400:28)
    at processEmit [as emit] (/snapshot/repo/build/node_modules/signal-exit/index.js:199:34)
    at process._fatalException (internal/process/execution.js:167:25)

Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at Object.publish (/snapshot/repo/build/node_modules/@aws-amplify/amplify-console-hosting/lib/index.js:46:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/amplify-frontend-javascript/lib/publisher.js:41:5)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/commands/publish.js:39:9)
    at async Object.executeAmplifyCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:189:9)
    at async executePluginModuleCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:135:5)
    at async executeCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:33:9)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:117:5)

Session Identifier: 7b4f486e-66dd-4d93-ab9b-280f7835a242
```

This appears to be erroring here https://github.com/aws-amplify/amplify-cli/blob/dev/packages/amplify-console-hosting/src/index.js#L39

Taking a further look at this one

**Comment by xalepo4** [comment]
Hello @josefaidt, I try to upload manually the zip to the Amplify web interface and it stucks at 70% always so it's possible that the problem are not on the cli.

**Comment by josefaidt** [comment]
Hey @xalepo4 apologies for the delay here. How large is the build artifact for your site?

**Comment by josefaidt** [comment]
Hey @xalepo4 are you still experiencing this?

**Comment by xalepo4** [comment]
Hello, after receive support AWS team the problem with my account was solved. Thanks.

**Comment by josefaidt** [comment]
Glad to hear you're back up and running! I'll close this issue for now but in the event this resurfaces please do not hesitate to reach out!
