### ISSUE TITLE
Initializing env fails

### ISSUE THREAD

**Issue by cocacrave** [aws-amplify/amplify-cli#1249]
I was working on an env `invite` but needed to remove it. I'm using envs and git branches: `master`, `dev`, and `invite` The steps I took to remove `invite` was following:

`git checkout dev`
tried to `amplify env remove invite` but couldn't find the env in list so I just deleted the stack from cloudformation console and zip from z3.
`git branch -D invite`

Now whenever I try to: `amplify env add` I get the options:
```
? Do you want to use an existing environment? No
? Enter a name for the environment invite
Using default provider  awscloudformation
```
Noticed I don't get the option to select the provider which should not be default. Then I get the following error:
```
init failed
TypeError: Cannot read property 'config' of undefined
    at getConfiguredAwsCfnClient (/Users/me/.nvm/versions/node/v8.10.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/initializer.js:63:21)
    at Object.run (/Users/me/.nvm/versions/node/v8.10.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/initializer.js:15:26)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

I was using `cli@1.1.8` and tried updating it to `cli@1.6.1` but same errors...

Please help.

**Comment by cocacrave** [comment]
Fixed it by merging env and removing `dev` and then tried adding it back and it works now.
