### ISSUE TITLE
Unable to login through the Amplify CLI

### ISSUE THREAD

**Issue by Thiamath** [aws-amplify/amplify-cli#12513]
### How did you install the Amplify CLI?

curl

### Amplify CLI Version

11.0.5

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

When I run
```
amplify pull --appId dg7jtgfxh9v63 --envName dev
```
The CLI opens the Amplify login page in the browser, but after login, an empty screen with the Amplify header appears and nothing happens.
![image](https://user-images.githubusercontent.com/6080704/233624789-26a0a2ec-4d90-443c-9b11-4a00e0126ad2.png)
If I hit `enter` in the terminal then I get the following:
![image](https://user-images.githubusercontent.com/6080704/233624956-b779348c-7ca5-4e5a-bc22-96d30da5921c.png)

### Expected behavior

After I log in Amplify Studio through the web, the CLI should be logged in and continue doing the pull.

### Reproduction steps

1. Install the Amplify CLI with `curl -sL https://aws-amplify.github.io/amplify-cli/install-win -o install.cmd && install.cmd`
2. Try to pull the Amplify environment
3. Try to log into the platform

### Project Identifier

Since I could not pull the project, diagnose just throws:
`No Amplify backend project files detected within this folder.`

### Log output

<details>

```
# Put your logs below this line
2023-04-20T23:37:28.303Z|error : Current environment cannot be determined.
EnvironmentNotInitializedError: Current environment cannot be determined.
2023-04-21T07:57:53.949Z|info : amplify version core
2023-04-21T11:31:04.740Z|info : amplify diagnose core  {"send-report~":true,"yes":false}
2023-04-21T11:31:04.772Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}

```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @Thiamath, 👋 thank you for reaching out. 
Does the project have Amplify studio enabled? 
is yes, Could you try the following steps.

1. Open AWS Amplify console and select a app.
2. Launch studio for app. 
3. then in you local machine, remove an files created by the previous amplify pull. example: `amplify-backup` and `amplify` folder 
4. rerun Amplify headless pull 
5. the cli should open a new tab in the browser. select yes if prompted for access
6. the cli should continue with the prompts.

additionally, could try adding the `--debug` to the pull command?

**Comment by Thiamath** [comment]
Hi @ykethan !
Thank you for reaching out so fast.

I made it and the same thing happened. On point 5 there's no prompt, just an empty screen as shown above. Point 6 never occurs.

After using the flag `--debug` I got the following output:
```
viajero@PC:~/test$ amplify pull --appId dg7jtgfxh9v63 --envName dev --debug
Opening link: https://eu-west-1.admin.amplifyapp.com/admin/dg7jtgfxh9v63/dev/verify/?loginVersion=1
⠹ Confirm login in the browser or manually paste in your CLI login key:

🛑 Failed to authenticate with Amplify Studio: Provided token was invalid.
? Select the authentication method you want to use: Amplify Studio
🛑 Current environment cannot be determined.

Resolution: Use 'amplify init' in the root of your app directory to create a new environment.
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

EnvironmentNotInitializedError: Current environment cannot be determined.
    at AmplifyToolkit.getEnvInfo (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/get-env-info.js:9:11)
    at adminLoginFlow (/snapshot/repo/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/admin-login.js:31:40)
    at getTempCredsWithAdminTokens (/snapshot/repo/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/utils/admin-helpers.js:72:44)
    at Object.loadConfigurationForEnv (/snapshot/repo/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/configuration-manager.js:769:73)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/attach-backend.js:129:21)
    at async Object.attachBackend (/snapshot/repo/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/index.js:253:3)
    at async queryProvider (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/attach-backend-steps/a10-queryProvider.js:31:5)
    at async attachBackend (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/attach-backend.js:39:9)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/commands/pull.js:64:9)
    at async Object.executeAmplifyCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:189:9)
    at async executePluginModuleCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:135:5)
    at async executeCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:33:9)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:117:5)

Session Identifier: abbc7cdd-793d-4566-91bc-422b7614a657
```

I'm trying to allow some developers to use the CLI to run the application locally and connect to Amplify authentication and database.

**Comment by ykethan** [comment]
hey @Thiamath, interesting, do you observe any errors in the browser console?

**Comment by Thiamath** [comment]
Hi @ykethan 
Not many:
![image](https://user-images.githubusercontent.com/6080704/233673252-42c709f3-263d-4fb6-b00d-3be1c75956c3.png)

**Comment by ykethan** [comment]
Additionally, were the users configured as ManageOnly User?

**Comment by Thiamath** [comment]
Yeah, the user is configured as ManageOnly, and I'm logging in with email and password.
I closed all the tabs and spawned a clean Chrome page (I tried with Edge too, same thing) and the answer was the same. An empty page with the header and footer from Amplify shows me as logged in but without any content. And the CLI waiting for a response.

**Comment by ykethan** [comment]
Hey @Thiamath, thank you for the information. Wanted to clarify some information.
Currently:
Full access: allows the team member to create and manage AWS resources. for example, being able to pull and modify resources
Manage only: allows access to team member to edit app content and users. for example, edit a data/records in a table but does not allow access to pull resources.

To allow access to developers, you will need to assign Full Access to the users. The Amplify Studio team is currently aware on this behaviour are working on providing better error messaging in the future releases.

**Comment by ykethan** [comment]
@Thiamath no worries, glad i was able to assist you. This is currently being documented here https://docs.amplify.aws/console/adminui/access-management/. 
Thank you for the feedback, i believe the information can be expanded for a better understanding. I will pass this on to the Amplify Studio team. 

For now, I will be closing the issue. Please feel free in reaching out to us again and we would be happy in assisting you.
