### ISSUE TITLE
Unexpected argument *folder directory* when `amplify pull` is called in CLI

### ISSUE THREAD

**Issue by dan-codes1** [aws-amplify/amplify-cli#12593]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

18.16.0

### Amplify CLI Version

11.1.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

Hello there,

After leaving it for about 2 weeks, I just returned to my amplify project and decided to make and deploy some changes to my data models in amplify console. After that, I called amplify pull and it gave an error message saying: 

Command failed with exit code 64: /Users/*user name*/.amplify/lib/aws-amplify-a mplify-frontend-ios/resources/amplify-xcode import-config --path=/Users: *my project dir*
Error: Unexpected argument 'PROJECTS/eemo2'
Usage: amplify-xcode import-config [--path <path>]
See 'amplify-xcode import-config --help' for more information.

I did try running the `amplify-xcode import-config --help` as suggested by it could not recognize the command.

I also noticed that after running `amplify pull` the `amplify codegen`, that the only models that get generated are the ones that I created today. The ones created two weeks and later do not get generated.

I use amplify-swift, and Xcode is my IDE.

Thanks.

### Expected behavior

I expected it to pull without an error. This is the first time I am getting such error.

### Reproduction steps

1. Make some changes via amplify console
2. Call amplify pull

** I don't know if this is important to note but I left the project idle for about two weeks. I just revisited it today **

### Log output

<details>

```
# Put your logs below this line
Command failed with exit code 64: /Users/*user name*/.amplify/lib/aws-amplify-a mplify-frontend-ios/resources/amplify-xcode import-config --path=/Users: *my project dir*
Error: Unexpected argument 'PROJECTS/eemo2'
Usage: amplify-xcode import-config [--path <path>]
See 'amplify-xcode import-config --help' for more information.

```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @dan-codes1 :wave: thanks for raising this! As we begin to look at this in more depth would you mind re-running `amplify pull` with `--debug` and poste the full error output here?

**Comment by dan-codes1** [comment]
Hey @josefaidt ,
This is the full output. Btw, I re-tried `amplify pull` a couple times and it ended up generating all the models. It still shows the same error though.

🛑 Command failed with exit code 64: /Users/*userName*/.amplify/lib/aws-amplify-amplify-frontend-ios/resources/amplify-xcode import-config --path=/Users/danieleze/Documents/SWIFT PROJECTS/*projectName*
Error: Unexpected argument 'PROJECTS/*projectName*'
Usage: amplify-xcode import-config [--path <path>]
  See 'amplify-xcode import-config --help' for more information.

Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

UnknownFault: Command failed with exit code 64: /Users/*userName*/.amplify/lib/aws-amplify-amplify-frontend-ios/resources/amplify-xcode import-config --path=/Users/*userName*/Documents/SWIFT PROJECTS/*projectName*
Error: Unexpected argument 'PROJECTS/*projectName*'
Usage: amplify-xcode import-config [--path <path>]
  See 'amplify-xcode import-config --help' for more information.
    at genericErrorToAmplifyException (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/amplify-exception-handler.js:126:49)
    at handleException (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/amplify-exception-handler.js:27:28)
    at process.<anonymous> (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:48:93)
    at process.emit (events.js:400:28)
    at processEmit [as emit] (/snapshot/repo/build/node_modules/signal-exit/index.js:199:34)
    at process._fatalException (internal/process/execution.js:167:25)

Command failed with exit code 64: /Users/*username*/.amplify/lib/aws-amplify-amplify-frontend-ios/resources/amplify-xcode import-config --path=/Users/*username*/Documents/SWIFT PROJECTS/*projectName*
Error: Unexpected argument 'PROJECTS/*projectName*'
Usage: amplify-xcode import-config [--path <path>]
  See 'amplify-xcode import-config --help' for more information.
Error: Command failed with exit code 64: /Users/*username*/.amplify/lib/aws-amplify-amplify-frontend-ios/resources/amplify-xcode import-config --path=/Users/*username*/Documents/SWIFT PROJECTS/*projectName*
Error: Unexpected argument 'PROJECTS/*ProjectName*'
Usage: amplify-xcode import-config [--path <path>]
  See 'amplify-xcode import-config --help' for more information.
    at makeError (/snapshot/repo/build/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/snapshot/repo/build/node_modules/execa/index.js:118:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async importConfig (/snapshot/repo/build/node_modules/@aws-amplify/amplify-frontend-ios/lib/amplify-xcode.js:38:3)
    at async Object.handleAmplifyEvent (/snapshot/repo/build/node_modules/@aws-amplify/amplify-frontend-ios/index.js:128:7)
    at async eventHandler (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:281:17)
    at async raiseEvent (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:286:13)
    at async raisePostPullEvent (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:256:5)
    at async raisePostEvent (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:240:13)
    at async executePluginModuleCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:138:5)
    at async executeCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:33:9)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:117:5)

Thanks.

**Comment by josefaidt** [comment]
Hey @dan-codes1 thanks for posting that! It appears this is due to the fact the path is not surrounded in quotes when passed into the `--path` option, which in turn is causing this command to try to pass "PROJECTS/projectName" as another argument. Marking as a bug

As a workaround, can you try to move your project to a parent directory that does not contain spaces? (e.g. `/Users/username/Documents/SWIFT-PROJECTS/projectName`)

Note for fix, here is where we should wrap the path in quotes https://github.com/aws-amplify/amplify-cli/blob/dev/packages/amplify-frontend-ios/lib/amplify-xcode.js#L49

**Comment by dan-codes1** [comment]
Hi @josefaidt, 

can you give a slightly better example? I tried it with your example and the `amplify pull` command works but still shows the same error message.

Thanks

**Comment by dan-codes1** [comment]
Hey @josefaidt , any updates?

**Comment by josefaidt** [comment]
Hey @dan-codes1 to clarify, after you modified the project path to contain no spaces you're still encountering this issue?

**Comment by dan-codes1** [comment]
@josefaidt sorry it just worked. Thanks
