### ISSUE TITLE
amplify update notifications error: pushTransform already has a running timer

### ISSUE THREAD

**Issue by snozoka** [aws-amplify/amplify-cli#12734]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.15.1

### Amplify CLI Version

12.0.3

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

I ran 'amplify update notifications' and get the follow error/resolution message:

"
Edit your schema at /.../schema.graphql or place .graphql files in a directory at /...schema
Deployment state saved successfully.

GraphQL transformer version: 2

🛑 pushTransform already has a running timer

Resolution: **Please report this issue at https://github.com/aws-amplify/amplify-cli/issues** and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

"

### Expected behavior

I expect 'notifications' category to be updated (even though I have not made any manual change). I also expect to be able to run 'amplify pull --appId XXX --envName staging' and 'amplify push' successfully. Currently I'm getting "Could not initialize categories for 'staging': Cannot read properties of undefined (reading 'Soar4JrbB')" when I run 'amplify pull'

### Reproduction steps

1. Run 'amplify update notifications' in Android Studio terminal window

### Project Identifier

adf24a36f9a97bc1518d1dfa8861c7ae

### Log output

<details>

```
# Put your logs below this line


```

</details>
"
⠧ Building resource api/Soar✅ GraphQL schema compiled successfully.

Edit your schema at /.../schema.graphql or place .graphql files in a directory at /...schema
Deployment state saved successfully.

GraphQL transformer version: 2

🛑 pushTransform already has a running timer

Resolution: **Please report this issue at https://github.com/aws-amplify/amplify-cli/issues** and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

Session Identifier: c774bd85-f540-4c40-b2db-a822f7201ecf

✅ Report saved: /...zip

✔ Done

"

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @snozoka, thank you for reaching out. Could you try adding the `--debug` and provide the output being displayed.
The issue appears to be similar to https://github.com/aws-amplify/amplify-cli/issues/12747 where i observed the update command threw a different error.
Additionally, for could you try pulling the Amplify backend with the `--debug` in a new directory and re-run `amplify update notification`. Do let us know if you observe the same error message.

**Comment by snozoka** [comment]
Hi @ykethan thanks for your response. Here's what I get when I run 'amplify update notification --debug' :


"

🛑 pushTransform already has a running timer

Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

UnknownFault: pushTransform already has a running timer
    at genericErrorToAmplifyException (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/amplify-exception-handler.js:126:49)
    at handleException (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/amplify-exception-handler.js:27:28)
    at process.<anonymous> (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:48:93)
    at process.emit (node:events:513:28)
    at process.processEmit [as emit] (/snapshot/repo/build/node_modules/signal-exit/index.js:199:34)
    at process._fatalException (node:internal/process/execution:149:25)

pushTransform already has a running timer
Error: pushTransform already has a running timer
    at UsageData.startCodePathTimer (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/domain/amplify-usageData/UsageData.js:74:19)
    at AmplifyToolkit.pushResources (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/push-resources.js:38:23)
    at run (/snapshot/repo/build/node_modules/@aws-amplify/amplify-category-analytics/lib/commands/analytics/push.js:17:18)
    at inAppMessagingMigrationCheck (/snapshot/repo/build/node_modules/@aws-amplify/amplify-category-analytics/lib/migrations/in-app-messaging-migration.js:125:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async analyticsMigrations (/snapshot/repo/build/node_modules/@aws-amplify/amplify-category-analytics/lib/migrations/index.js:11:3)
    at async migrationCheck (/snapshot/repo/build/node_modules/@aws-amplify/amplify-category-notifications/lib/migrations/index.js:7:9)
    at async Object.executeAmplifyCommand (/snapshot/repo/build/node_modules/@aws-amplify/amplify-category-notifications/lib/index.js:57:5)
    at async executePluginModuleCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:135:5)
    at async executeCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:33:9)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:117:5)

Session Identifier: 34e25dc3-ff52-463f-bf84-f94a1145959e

✅ Report saved: /tmp/Soar/report-1687094368886.zip

✔ Done

Project Identifier: adf24a36f9a97bc1518d1dfa8861c7ae


"

**Comment by snozoka** [comment]
Additionally, below is the error I get when I try pulling the Amplify backend with the '--debug'

"

⚠️ Local changes detected.
⚠️ Pulling changes from the cloud will override your local changes.
? Are you sure you would like to continue? Yes
⠸ Fetching updates to backend environment: staging from the cloud.Overrides functionality is not implemented for this category
⠴ Building resource api/Soar[WARNING] aws-cdk-lib.CfnResource#addDependsOn is deprecated.
  use addDependency
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.CfnResource#addDependsOn is deprecated.
  use addDependency
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.CfnResource#addDependsOn is deprecated.
  use addDependency
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.CfnResource#addDependsOn is deprecated.
  use addDependency
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.CfnResource#addDependsOn is deprecated.
  use addDependency
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.CfnResource#addDependsOn is deprecated.
  use addDependency
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.CfnResource#addDependsOn is deprecated.
  use addDependency
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.CfnResource#addDependsOn is deprecated.
  use addDependency
  This API will be removed in the next major release.
⠧ Building resource api/Soar✅ GraphQL schema compiled successfully.

Edit your schema at /Users/Scott/Documents/GitHub/Soar/amplify/backend/api/Soar/schema.graphql or place .graphql files in a directory at /Users/Scott/Documents/GitHub/Soar/amplify/backend/api/Soar/schema
Overrides functionality is not implemented for this category
Overrides functionality is not implemented for this category
✔ Successfully pulled backend environment staging from the cloud.
✔ Successfully retrieved channel information for FCM.
✔ Channel information retrieved for Email
✖ There was an error initializing your environment.
🛑 Could not initialize categories for 'staging': Cannot read properties of undefined (reading 'Soar4JrbB')

Resolution: Review the error message and stack trace for additional information.
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

ProjectInitFault: Could not initialize categories for 'staging': Cannot read properties of undefined (reading 'Soar4JrbB')
    at initializeEnv (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/initialize-env.js:114:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async pullBackend (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/pull-backend.js:31:5)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/commands/pull.js:46:17)
    at async Object.executeAmplifyCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:189:9)
    at async executePluginModuleCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:135:5)
    at async executeCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:33:9)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:117:5)

Cannot read properties of undefined (reading 'Soar4JrbB')
TypeError: Cannot read properties of undefined (reading 'Soar4JrbB')
    at writeData (/snapshot/repo/build/node_modules/@aws-amplify/amplify-category-notifications/lib/multi-env-manager-utils.js:60:89)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.initEnv (/snapshot/repo/build/node_modules/@aws-amplify/amplify-category-notifications/lib/multi-env-manager.js:76:13)
    at async initEnv (/snapshot/repo/build/node_modules/@aws-amplify/amplify-category-notifications/lib/index.js:47:5)

Session Identifier: e4911749-7286-403f-83b5-139e56e41269

✅ Report saved: /tmp/Soar/report-1687094787166.zip

✔ Done

Project Identifier: adf24a36f9a97bc1518d1dfa8861c7ae

**Comment by snozoka** [comment]
And here's what I get when I run amplify push --debug:

"

Not pulling components because this project is not configured as a javascript frontend.
⠋ Fetching updates to backend environment: staging from the cloud.Overrides functionality is not implemented for this category
⠙ Fetching updates to backend environment: staging from the cloud.[WARNING] aws-cdk-lib.CfnResource#addDependsOn is deprecated.
  use addDependency
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.CfnResource#addDependsOn is deprecated.
  use addDependency
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.CfnResource#addDependsOn is deprecated.
  use addDependency
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.CfnResource#addDependsOn is deprecated.
  use addDependency
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.CfnResource#addDependsOn is deprecated.
  use addDependency
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.CfnResource#addDependsOn is deprecated.
  use addDependency
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.CfnResource#addDependsOn is deprecated.
  use addDependency
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.CfnResource#addDependsOn is deprecated.
  use addDependency
  This API will be removed in the next major release.
⠸ Fetching updates to backend environment: staging from the cloud.✅ GraphQL schema compiled successfully.

Edit your schema at /Users/Scott/Documents/GitHub/Soar/amplify/backend/api/Soar/schema.graphql or place .graphql files in a directory at /Users/Scott/Documents/GitHub/Soar/amplify/backend/api/Soar/schema
Overrides functionality is not implemented for this category
Overrides functionality is not implemented for this category
✔ Successfully pulled backend environment staging from the cloud.

    Current Environment: staging
    
┌───────────────┬───────────────────────┬───────────┬───────────────────┐
│ Category      │ Resource name         │ Operation │ Provider plugin   │
├───────────────┼───────────────────────┼───────────┼───────────────────┤
│ Auth          │ soar                  │ No Change │ awscloudformation │
├───────────────┼───────────────────────┼───────────┼───────────────────┤
│ Api           │ Soar                  │ No Change │ awscloudformation │
├───────────────┼───────────────────────┼───────────┼───────────────────┤
│ Function      │ soarlambdafunction    │ No Change │ awscloudformation │
├───────────────┼───────────────────────┼───────────┼───────────────────┤
│ Notifications │ Soar4JrbB             │ No Change │                   │
├───────────────┼───────────────────────┼───────────┼───────────────────┤
│ Storage       │ s3soarstoragecb023aae │ No Change │ awscloudformation │
└───────────────┴───────────────────────┴───────────┴───────────────────┘
✔ Are you sure you want to continue? (Y/n) · yes
Overrides functionality is not implemented for this category
⠼ Building resource api/Soar[WARNING] aws-cdk-lib.CfnResource#addDependsOn is deprecated.
  use addDependency
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.CfnResource#addDependsOn is deprecated.
  use addDependency
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.CfnResource#addDependsOn is deprecated.
  use addDependency
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.CfnResource#addDependsOn is deprecated.
  use addDependency
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.CfnResource#addDependsOn is deprecated.
  use addDependency
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.CfnResource#addDependsOn is deprecated.
  use addDependency
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.CfnResource#addDependsOn is deprecated.
  use addDependency
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.CfnResource#addDependsOn is deprecated.
  use addDependency
  This API will be removed in the next major release.
⠦ Building resource api/Soar✅ GraphQL schema compiled successfully.

Edit your schema at /Users/Scott/Documents/GitHub/Soar/amplify/backend/api/Soar/schema.graphql or place .graphql files in a directory at /Users/Scott/Documents/GitHub/Soar/amplify/backend/api/Soar/schema
Overrides functionality is not implemented for this category
Overrides functionality is not implemented for this category
Deployment state saved successfully.

GraphQL transformer version: 2

Not pulling components because this project is not configured as a javascript frontend.


"

**Comment by ykethan** [comment]
Hey @snozoka, thank you for the information. Could you let us know the Amplify CLI version the project and the notifications category created on as this would enable us in reproducing the issue?
Additionally, if possible could you try removing the notifications channel and then re-add the channels back in?

Marking this as bug for further investigation.

**Comment by snozoka** [comment]
Hi @ykethan below are the responses to your question. I attempted to remove the notifications category but it still appears when I run 'amplify status'

- Amplify CLI version: 12.0.3


**... % sudo amplify status**

    Current Environment: staging
    
┌───────────────┬───────────────────────┬───────────┬───────────────────┐
│ Category      │ Resource name         │ Operation │ Provider plugin   │
├───────────────┼───────────────────────┼───────────┼───────────────────┤
│ Auth          │ soar                  │ No Change │ awscloudformation │
├───────────────┼───────────────────────┼───────────┼───────────────────┤
│ Api           │ Soar                  │ No Change │ awscloudformation │
├───────────────┼───────────────────────┼───────────┼───────────────────┤
│ Function      │ soarlambdafunction    │ No Change │ awscloudformation │
├───────────────┼───────────────────────┼───────────┼───────────────────┤
│ Notifications │ Soar4JrbB             │ No Change │                   │
├───────────────┼───────────────────────┼───────────┼───────────────────┤
│ Storage       │ s3soarstoragecb023aae │ No Change │ awscloudformation │
└───────────────┴───────────────────────┴───────────┴───────────────────┘

Pinpoint URL to track events 
GraphQL endpoint: 
GraphQL API KEY: 

GraphQL transformer version: 2

**... % sudo amplify remove notifications**
Password:
? Choose the notification channel to remove …  
  FCM  | » Firebase Push Notifications 
❯ All channels on Pinpoint resource : Soar4JrbB

✔ Choose the notification channel to remove · All channels on Pinpoint resource : Soar4JrbB
✔ Confirm that you want to delete the associated Amazon Pinpoint application (y/N) · yes
Deployment state saved successfully.
The Pinpoint application has been successfully deleted.
**...Soar % sudo amplify remove notifications**
Password:
? Choose the notification channel to remove …  (Use arrow keys or type to filter)
❯ FCM  | » Firebase Push Notifications 
  Email
  All channels on Pinpoint resource : Soar4JrbB
  Cancel

**Comment by ykethan** [comment]
Hey @snozoka, thank you for the information. I observed that the project currently does not have a analytics resource present in the project as when adding a notifications resource a analytics pinpoint resource automatically gets added to the project.
unfortunately it appears we may have to manually remove the resource from the project. To remove the notifications and analytics from the project we can utilize the following steps.

1. remove the analytics and notifications directory if present under `amplify/backend/`
2. carefully remove the analytics and pinpoint references in `amplify/team-provider-info.json`
3. carefully remove the analytics and pinpoint references references in `amplify/backend/backend-config.json`. this includes the parameters as well.
4. run `amplify env checkout <current-env-name>`
5. this should now show your analytics and notifications in the `DELETE` state
6. push with `amplify push -y`

**Comment by snozoka** [comment]
Hi @ykethan it appears the analytics and notifications resources are removed, but for some reason I'm still not able to pull the project from Amplify Studio; I'm getting an error saying "Cannot read properties of undefined" (se images below) which was the error I was previously getting, and which was related to Notifications.

 I'm now thinking it may be best to start all over, clean AWS from the Android project and pull the project from Amplify Studio; how can I do this?

<img width="1666" alt="image" src="https://github.com/aws-amplify/amplify-cli/assets/46583219/a5ec5420-ad56-4397-b18e-6af9900e6235">


<img width="1659" alt="image" src="https://github.com/aws-amplify/amplify-cli/assets/46583219/fb1db7bb-80b4-471f-aae3-72f9ef4ae374">

**Comment by snozoka** [comment]
Hello,

Any help with the above?

I'm still not able to pull the project from the cloud or save and deploy my data model.

Thanks

**Comment by snozoka** [comment]
Please ignore; I've deleted the Amplify project and started over.
