### ISSUE TITLE
Cannot pull backend “🛑 Failed to pull the backend.” - amplify-meta.json does not exist

### ISSUE THREAD

**Issue by mrcoles** [aws-amplify/amplify-cli#12766]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.18.3

### Amplify CLI Version

12.0.3, 11.0.5, 10.6.2

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made. HOWEVER, I am seeing in the AWS Amplify Console that “Enable Amplify Studio.” is “On”. I don’t remember enabling this, could Studio being enabled break things?

### Describe the bug

I’m unable to push or pull my backend right now. It keeps leading to cryptic errors about `amplify-meta.json` either not existing in `amplify/backend/` or `amplify/#current-cloud-backend/`.

As a test, I tried cloning my repo fresh and checking out the last branch to successfully deploy. From there I ran `amplify pull` and that failed too.

See the full amplify-cli command and `--debug` error in the “log output” section below. FWIW, I tried with amplify v 12.0.3, 11.0.5, and 10.6.2 (which is the last version I remember this working on).

### Expected behavior

I would expect being able to clone my repo and run amplify pull and for it to pull the backend.

### Reproduction steps

1. `git clone [path_to_repo] fullpage-ALTTEST4`
2. `git co dev`
3. `amplify pull`
4. Fill out the options for my profile, the app id, and `dev` envName

### Project Identifier

I have never been able to send a report. It always errors out with no explanation. I communicated this in January in this issue: https://github.com/aws-amplify/amplify-cli/issues/11723

### Log output

<details>

**The CLI output:**

```
(dev) ~/p/fullpage-ALTTEST4 > amplify pull --debug                                                                     22:21:41
? Select the authentication method you want to use: AWS profile

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

? Please choose the profile you want to use fpsc
? Which app are you working on? d32cgdvim65k7p
? Pick a backend environment: dev
🛑 Failed to pull the backend.

Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

PullBackendFault: Failed to pull the backend.
    at attachBackend (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/attach-backend.js:51:15)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/commands/pull.js:64:9)
    at async Object.executeAmplifyCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:179:9)
    at async executePluginModuleCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:142:5)
    at async executeCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:40:9)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:119:5)

File at path: '/Users/peter/projects/fullpage-ALTTEST4/amplify/#current-cloud-backend/amplify-meta.json' does not exist
Error: File at path: '/Users/peter/projects/fullpage-ALTTEST4/amplify/#current-cloud-backend/amplify-meta.json' does not exist
    at Function.readJson (/snapshot/repo/build/node_modules/amplify-cli-core/lib/jsonUtilities.js:40:19)
    at AmplifyToolkit.readJsonFile [as _readJsonFile] (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/read-json-file.js:6:45)
    at ensureAmplifyMeta (/snapshot/repo/build/node_modules/amplify-provider-awscloudformation/lib/attach-backend.js:160:46)
    at Object.run (/snapshot/repo/build/node_modules/amplify-provider-awscloudformation/lib/attach-backend.js:149:36)
    at async Object.attachBackend (/snapshot/repo/build/node_modules/amplify-provider-awscloudformation/lib/index.js:208:3)
    at async queryProvider (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/attach-backend-steps/a10-queryProvider.js:31:5)
    at async attachBackend (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/attach-backend.js:39:9)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/commands/pull.js:64:9)
    at async Object.executeAmplifyCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:179:9)
    at async executePluginModuleCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:142:5)
    at async executeCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:40:9)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:119:5)

Session Identifier:

✅ Report saved: /var/folders/s8/2cc1_sx93dgdm20y08gnc2900000gn/T/fullpage/report-1686190927979.zip

⠋ Sending zip
File at path: '/Users/peter/projects/fullpage-ALTTEST4/amplify/backend/amplify-meta.json' does not exist
✖ Sending zip
```

**The ~/.amplify/logs/amplify-cli-2023-06-07.log data:**

```
# Put your logs below this line
2023-06-08T02:22:06.034Z|info : amplify-provider-awscloudformation.attach-backend.getBackendEnv.amplifyClient.listBackendEnvironments([{"appId":"[***]m65k7p"}])
2023-06-08T02:22:07.131Z|info : amplify-provider-awscloudformation.attach-backend.downloadBackend.s3.getObject([{"Key":"[***]rent-[***]ud-[***]d.zip","Bucket":"[***]page-[***]131120-[***]ment"}])
2023-06-08T02:22:08.024Z|error : Failed to pull the backend.
PullBackendFault: Failed to pull the backend.
2023-06-08T02:26:03.319Z|info : amplify version core  {"version":true,"yes":false}
```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @mrcoles :wave: thanks for raising this! You will need to pass the associated `appId` and `envName` to pull the Amplify project that is not yet initialized in the freshly cloned project directory. Once the project and environment are initialized you will be able to run `amplify pull` without passing additional options

**Comment by mrcoles** [comment]
@josefaidt it feels like a bug that if I enter the appId and envName via the wizard interface it breaks and if I pass them in directly in the command line argument it does something different?

When I pass in directly, e.g., `amplify pull --appId d32cgdvim65k7p --envName dev`, I get the following results (see video):

https://github.com/aws-amplify/amplify-cli/assets/136651/d7c091b0-f8f8-46a5-9284-af5376383884

I don’t think I ever actually used Amplify Studio—but maybe I turned it on by mistake so I just disabled it from the AWS console (from this interface—a pretty scary message!):

<img width="650" alt="Screen Shot 2023-06-12 at 10 50 29 PM" src="https://github.com/aws-amplify/amplify-cli/assets/136651/3ca99d24-ccab-422c-821b-4a281ad423f1">

Now when I try to do a pull, I get this result instead:

```bash
(dev) ~/p/fullpage-ALTTEST8 > echo $AMPLIFY_ENABLE_DEBUG_OUTPUT                                          23:00:13
true
(dev) ~/p/fullpage-ALTTEST8 > amplify pull --debug --appId d32cgdvim65k7p --envName dev                  23:00:14
? Select the authentication method you want to use: AWS profile

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

? Please choose the profile you want to use fpsc
Amplify AppID found: d32cgdvim65k7p. Amplify App name is: fullpage
Backend environment dev found in Amplify Console app: fullpage
🛑 Failed to pull the backend.

Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

PullBackendFault: Failed to pull the backend.
    at attachBackend (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/attach-backend.js:51:15)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/commands/pull.js:64:9)
    at async Object.executeAmplifyCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:179:9)
    at async executePluginModuleCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:142:5)
    at async executeCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:40:9)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:119:5)

File at path: '/Users/petercoles/projects/fullpage-ALTTEST8/amplify/#current-cloud-backend/amplify-meta.json' does not exist
Error: File at path: '/Users/petercoles/projects/fullpage-ALTTEST8/amplify/#current-cloud-backend/amplify-meta.json' does not exist
    at Function.readJson (/snapshot/repo/build/node_modules/amplify-cli-core/lib/jsonUtilities.js:40:19)
    at AmplifyToolkit.readJsonFile [as _readJsonFile] (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/read-json-file.js:6:45)
    at ensureAmplifyMeta (/snapshot/repo/build/node_modules/amplify-provider-awscloudformation/lib/attach-backend.js:160:46)
    at Object.run (/snapshot/repo/build/node_modules/amplify-provider-awscloudformation/lib/attach-backend.js:149:36)
    at async Object.attachBackend (/snapshot/repo/build/node_modules/amplify-provider-awscloudformation/lib/index.js:208:3)
    at async queryProvider (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/attach-backend-steps/a10-queryProvider.js:31:5)
    at async attachBackend (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/attach-backend.js:39:9)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/commands/pull.js:64:9)
    at async Object.executeAmplifyCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:179:9)
    at async executePluginModuleCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:142:5)
    at async executeCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:40:9)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:119:5)

Session Identifier:

✅ Report saved: /var/folders/s8/2cc1_sx93dgdm20y08gnc2900000gn/T/fullpage/report-1686625225977.zip

⠋ Sending zip
File at path: '/Users/petercoles/projects/fullpage-ALTTEST8/amplify/backend/amplify-meta.json' does not exist
✖ Sending zip
```

I’m really confused, because this commit and branch deployed fine from the AWS Amplify Console CI before… did something else change with Amplify?

**Comment by josefaidt** [comment]
Hey @mrcoles it appears Studio is enabled on your project, which is why it is forcing you through that auth flow. Despite the issue the error you are seeing is caused by `amplify diagnose` attempting to read this file after the failed pull attempt, which is effectively erroring twice.

Can you try running the same command with `--yes`?

```
amplify pull --debug --appId d32cgdvim65k7p --envName dev --yes
```

For example, here is how I've cloned an existing project and pulled the backend:

```console
projects/aws-amplify/reproductions 
➜  mkdir 12640two

projects/aws-amplify/reproductions 
➜  cd 12640two

aws-amplify/reproductions/12640two 
➜  gh repo clone 12640 .
Cloning into '.'...
remote: Enumerating objects: 72, done.
remote: Counting objects: 100% (72/72), done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 72 (delta 25), reused 66 (delta 20), pack-reused 0
Receiving objects: 100% (72/72), 11.12 KiB | 3.71 MiB/s, done.
Resolving deltas: 100% (25/25), done.

12640two on  main 
➜  amplify pull --appId d33s566qkjqjly --envName dev --yes
Amplify AppID found: d33s566qkjqjly. Amplify App name is: 12640
Backend environment dev found in Amplify Console app: 12640
✔ Successfully pulled backend environment dev from the cloud.
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
✅ 
```

After the failed pull attempt were there any files leftover such as the `amplify-backup/` directory? If the above commands still do not work, can you download, unzip, and inspect the contents of `#current-cloud-backend.zip` for the `amplify-meta.json` file?

**Comment by josefaidt** [comment]
You can also try `amplify init --envName dev --yes` to initialize the project after cloning from git. It may print a warning about being unable to resolve the AppId but that can be ignored for now

**Comment by mrcoles** [comment]
Thx for the notes! Here’s what I got:

RE: Studio - yes in my prior comment I show the output of a pull after having disabled it. Did trying to take a look at this at some point in the past potentially cause everything to break?

RE: `--yes` - by auto-approving the prompts it ends up selecting the wrong AWS profile and fails for that reason.

RE: files - There is no `amplify-backup/` or `#current-cloud-backend.zip` after the failed pull. I already emailed the resulting folder & the report separate from this issue (I’m still really confused as to why the sending of reports always fails). I also tried copying in amplify-meta.json from another repo, but that just causes another error for `File at path: '…/amplify/#current-cloud-backend/amplify-meta.json' does not exist`

RE: amplify init - wouldn’t this lead to something pointing to the wrong appId?

**Comment by josefaidt** [comment]
Hey @mrcoles thanks for checking that! In your project's deployment bucket, can you download the `#current-cloud-backend.zip` and inspect its contents for an `amplify-meta.json` file? For some reason it appears this is missing, but it is typically uploaded on `push`. There have been reports in the past where the project's backend is hooked into multiple frontends, and when those frontend builds the state upload corrupts the zip archive. Do you have a similar setup?

**Comment by mrcoles** [comment]
Hi @josefaidt 

> can you download the #current-cloud-backend.zip and inspect its contents for an amplify-meta.json

Is there a resource that shares how someone does this?

> There have been reports in the past where the project's backend is hooked into multiple frontends, and when those frontend builds the state upload corrupts the zip archive. Do you have a similar setup?

My project has been running using the AWS Amplify Web Console CI tool and I’ve also done manual pull/push commands using the CLI. As mentioned above, I believe I—out of curiosity—tried to look at Studio sometime ago and that maybe unintentionally caused some problems. (If that’s the problem, then that’s pretty scary that it’s so easy to shoot myself in the foot with that)

Here are additional steps I took with a copy of an `amplify-meta.json` file that I was able to find in another repo:

1. From a fresh checkout of my repo, I copied the `amplify-meta.json` into `./amplify/backend/` and did the `amplify pull` command
2. This errored out saying it couldn’t find `amplify/#current-cloud-backend/amplify-meta.json`, interestingly enough when I searched for `amplify-meta.json` it came up with:

    ```
    ./amplify/#current-cloud-backend/#current-cloud-backend/amplify-meta.json
    ./amplify/backend/#current-cloud-backend/amplify-meta.json
    ```

3. So I went ahead and copied the file into `./amplify/#current-cloud-backend/` and did the pull again
4. This lead to the same error and also to the file being deleted, such that when I searched for it I got the same output as in step 2 above

See the entire output in the details below.

<details>

```
(dev) ~/p/fullpage-ALTTEST13 > amplify pull --debug --appId d32cgdvim65k7p --envName dev     21:59:34
? Select the authentication method you want to use: AWS profile

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

? Please choose the profile you want to use fpsc
Amplify AppID found: d32cgdvim65k7p. Amplify App name is: fullpage
Backend environment dev found in Amplify Console app: fullpage
🛑 Failed to pull the backend.

Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

PullBackendFault: Failed to pull the backend.
    at attachBackend (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/attach-backend.js:55:15)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/commands/pull.js:64:9)
    at async Object.executeAmplifyCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:194:9)
    at async executePluginModuleCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:139:5)
    at async executeCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:37:9)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:121:5)

File at path: '/Users/petercoles/projects/fullpage-ALTTEST13/amplify/#current-cloud-backend/amplify-meta.json' does not exist
Error: File at path: '/Users/petercoles/projects/fullpage-ALTTEST13/amplify/#current-cloud-backend/amplify-meta.json' does not exist
    at JSONUtilities.readJson (/snapshot/repo/build/node_modules/@aws-amplify/amplify-cli-core/lib/jsonUtilities.js:44:19)
    at AmplifyToolkit.readJsonFile (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/read-json-file.js:6:45)
    at ensureAmplifyMeta (/snapshot/repo/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/attach-backend.js:127:46)
    at Object.run (/snapshot/repo/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/attach-backend.js:118:36)
    at async Object.attachBackend (/snapshot/repo/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/index.js:195:3)
    at async queryProvider (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/attach-backend-steps/a10-queryProvider.js:36:5)
    at async attachBackend (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/attach-backend.js:43:9)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/commands/pull.js:64:9)
    at async Object.executeAmplifyCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:194:9)
    at async executePluginModuleCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:139:5)
    at async executeCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:37:9)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:121:5)

Session Identifier:

✅ Report saved: /var/folders/s8/2cc1_sx93dgdm20y08gnc2900000gn/T/fullpage/report-1686880783628.zip

⠧ Sending zip
DiagnoseReportUploadError
✖ Sending zip
(dev) ~/p/fullpage-ALTTEST13 > find . -name amplify-meta.json                                22:00:00
./amplify/#current-cloud-backend/#current-cloud-backend/amplify-meta.json
./amplify/backend/amplify-meta.json
(dev) ~/p/fullpage-ALTTEST13 >                                                               22:00:00
(dev) ~/p/fullpage-ALTTEST13 > cp ./amplify/backend/amplify-meta.json ./amplify/\#current-cloud-backend/
(dev) ~/p/fullpage-ALTTEST13 >                                                               22:00:31
(dev) ~/p/fullpage-ALTTEST13 > amplify pull --debug --appId d32cgdvim65k7p --envName dev     22:00:33

Pre-pull status:

    Current Environment: dev

┌──────────┬────────────────────┬───────────┬───────────────────┐
│ Category │ Resource name      │ Operation │ Provider plugin   │
├──────────┼────────────────────┼───────────┼───────────────────┤
│ Api      │ fpapi              │ Update    │ awscloudformation │
├──────────┼────────────────────┼───────────┼───────────────────┤
│ Auth     │ fpcognito          │ Update    │ awscloudformation │
├──────────┼────────────────────┼───────────┼───────────────────┤
│ Function │ fpaccount          │ Update    │ awscloudformation │
├──────────┼────────────────────┼───────────┼───────────────────┤
│ Function │ fpcognitoPreSignup │ Update    │ awscloudformation │
├──────────┼────────────────────┼───────────┼───────────────────┤
│ Function │ fpimages           │ Update    │ awscloudformation │
├──────────┼────────────────────┼───────────┼───────────────────┤
│ Function │ fppreauth          │ Update    │ awscloudformation │
├──────────┼────────────────────┼───────────┼───────────────────┤
│ Function │ fpwebhooks         │ Update    │ awscloudformation │
├──────────┼────────────────────┼───────────┼───────────────────┤
│ Storage  │ fpabtest           │ Update    │ awscloudformation │
├──────────┼────────────────────┼───────────┼───────────────────┤
│ Storage  │ fpimagesdynamo     │ Update    │ awscloudformation │
├──────────┼────────────────────┼───────────┼───────────────────┤
│ Storage  │ fpimagestorage     │ Update    │ awscloudformation │
├──────────┼────────────────────┼───────────┼───────────────────┤
│ Storage  │ fporgs             │ Update    │ awscloudformation │
├──────────┼────────────────────┼───────────┼───────────────────┤
│ Storage  │ fpusers            │ Update    │ awscloudformation │
└──────────┴────────────────────┴───────────┴───────────────────┘

⚠️ Local changes detected.
⚠️ Pulling changes from the cloud will override your local changes.
? Are you sure you would like to continue? Yes
✖ Fetching updates to backend environment: dev from the cloud.
✖ There was an error initializing your environment.
🛑 Could not initialize platform for 'dev': File at path: '/Users/petercoles/projects/fullpage-ALTTEST13/amplify/#current-cloud-backend/amplify-meta.json' does not exist

Resolution: Review the error message and stack trace for additional information.
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

ProjectInitFault: Could not initialize platform for 'dev': File at path: '/Users/petercoles/projects/fullpage-ALTTEST13/amplify/#current-cloud-backend/amplify-meta.json' does not exist
    at initializeEnv (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/initialize-env.js:103:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async pullBackend (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/pull-backend.js:31:5)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/commands/pull.js:46:17)
    at async Object.executeAmplifyCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:194:9)
    at async executePluginModuleCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:139:5)
    at async executeCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:37:9)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:121:5)

File at path: '/Users/petercoles/projects/fullpage-ALTTEST13/amplify/#current-cloud-backend/amplify-meta.json' does not exist
Error: File at path: '/Users/petercoles/projects/fullpage-ALTTEST13/amplify/#current-cloud-backend/amplify-meta.json' does not exist
    at JSONUtilities.readJson (/snapshot/repo/build/node_modules/@aws-amplify/amplify-cli-core/lib/jsonUtilities.js:44:19)
    at StateManager.getData (/snapshot/repo/build/node_modules/@aws-amplify/amplify-cli-core/lib/state-manager/stateManager.js:327:56)
    at StateManager.getCurrentMeta (/snapshot/repo/build/node_modules/@aws-amplify/amplify-cli-core/lib/state-manager/stateManager.js:59:31)
    at Object.run (/snapshot/repo/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/initialize-env.js:73:64)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Session Identifier:
⠋ Creating Zip
File at path: '/Users/petercoles/projects/fullpage-ALTTEST13/amplify/backend/backend-config.json' does not exist
✖ Creating Zip
(dev ✨%) ~/p/fullpage-ALTTEST13 >                                                           22:00:48
(dev ✨%) ~/p/fullpage-ALTTEST13 >                                                           22:00:59
(dev ✨%) ~/p/fullpage-ALTTEST13 > find . -name amplify-meta.json                            22:00:59
./amplify/#current-cloud-backend/#current-cloud-backend/amplify-meta.json
./amplify/backend/#current-cloud-backend/amplify-meta.json
```

</details>

**Comment by josefaidt** [comment]
Hey @mrcoles this line leads me to believe there was an issue re-zipping the directory. 
```
./amplify/#current-cloud-backend/#current-cloud-backend/amplify-meta.json
```
I wrote up a few instructions for zipping as I have encountered the same issue in the past

1. be sure to not accidentally zip as a nested folder
2. `unzip "#current-cloud-backend.zip" -d "#current-cloud-backend"`
3. `mv "#current-cloud-backend.zip" backup.zip`
4. correct the files
5. `cd "#current-cloud-backend"; zip -r "../#current-cloud-backend.zip" *`

**Comment by mrcoles** [comment]
Thanks for the response.

The nested folder is being created by the Amplify CLI not by me! I still don’t even know how to download this zip file—that was my first question in my last response:

> > can you download the #current-cloud-backend.zip and inspect its contents for an amplify-meta.json
>
> Is there a resource that shares how someone does this?

Can you please share instructions on how I would download the `#current-cloud-backend.zip` file? And then it sounds like you’re asking me to try: (1) unzipping it and adding it to the `./amplify/` directory in my project and (2) maybe also copying the `amplify-meta.json` into `./amplify/backend/` as well?

**Comment by josefaidt** [comment]
Hey @mrcoles first, if you do not have any changes locally can you try `amplify push --force`? This should forcefully save the backend state and upload to your S3 deployment bucket.

Below is an example project's deployment bucket in S3:
![image](https://github.com/aws-amplify/amplify-cli/assets/5033303/8aeae8ea-1a0e-4c3b-a4f7-e2e8806aef5e)

> And then it sounds like you’re asking me to try: (1) unzipping it and adding it to the ./amplify/ directory in my project and (2) maybe also copying the amplify-meta.json into ./amplify/backend/ as well?

Yes, if force pushing does not alleviate the issue can you try copying the `amplify-meta.json` file you have locally into the downloaded current-cloud-backend archive, re-zip, and re-upload?

**Comment by mrcoles** [comment]
@josefaidt thx for sharing the download info! However, what do you mean by doing the push force? Also you said “if you do not have any changes locally…” I am using a completely fresh git checkout of my code that has none of the #current-cloud-backend or amplify-meta.json content populated in it, so I assume an `amplify push --force` would do nothing in that case? Or am I missing something?

That being said are you assuming that I’ve downloaded and copied these files into place? I’ve tried populating the "#current--cloud-backend” from those files in S3 as well as “backend/amplify-meta.json” (both are required for me to a do an amplify pull). However, when I run `amplify pull --debug --appId d32cgdvim65k7p --envName dev` the Amplify CLI moves the "./#current-cloud-backend" into "./#current-cloud-backend/#current-cloud-backend" and then complains about there being no "./#current-cloud-backend/amplify-meta.json".

Is there something else you’re assuming about how I’m setting this up that I’m missing on my side?

For extra context, here’s my .gitignore (within “Details”):

<details>

```
node_modules/
.cache/
.parcel-cache/
.vscode/
dist/
examples/
.DS_Store
out/

# ## Client Env
#
# env variables exist in the Amplify Console build, but add
# your own in ./.env for settings `process.env` for running
# the client on localhost.
#
# TODO - maybe have .env.dev (or .env as default) and
# .env.master in source control, but .env.local not and in
# the amplify build settings pass through env via
# `NODE_ENV=$AWS_BRANCH npm build`
#
.env
.env.master

# ## Scripts and Backend Env
#
# Special environment variables for the scripts and backends.
# See README.md for more info.
#
.env.scripts.dev
.env.scripts.master
.idea

#amplify-do-not-edit-begin
amplify/\#current-cloud-backend
amplify/.config/local-*
amplify/logs
amplify/mock-data
amplify/backend/amplify-meta.json
amplify/backend/.temp
build/
aws-exports.js
awsconfiguration.json
amplifyconfiguration.json
amplifyconfiguration.dart
amplify-build-config.json
amplify-gradle-config.json
amplifytools.xcconfig
.secret-*
**.sample
#amplify-do-not-edit-end
```
</details>

And here’s the files that exist in source code within…

./amplify:

<img src="https://github.com/aws-amplify/amplify-cli/assets/136651/854a9716-024c-4bd1-8e42-393859b4c75f" width="343" alt="./ampify" />

./amplify/backend:

<img src="https://github.com/aws-amplify/amplify-cli/assets/136651/c644310b-60e9-40bb-b876-a538a31a2b97" width="404" alt="./amplify/backend" />

**Comment by josefaidt** [comment]
Hey @mrcoles :wave: 

> However, what do you mean by doing the push force? Also you said “if you do not have any changes locally…” I am using a completely fresh git checkout of my code that has none of the #current-cloud-backend or amplify-meta.json content populated in it, so I assume an amplify push --force would do nothing in that case? Or am I missing something?

Force pushing with `amplify push --force` will forcefully upload backend state. Since `amplify-meta.json` does not live within a category's directory (like `amplify/backend/auth/<auth-name>`) it will not trigger an `UPDATE` to a resource, and therefore the CLI will say there are no changes on `amplify status`. Force pushing will ensure files like `amplify-meta.json` are re-uploaded to the deployment bucket, and will be available on `amplify pull`

> the Amplify CLI moves the "./#current-cloud-backend" into "./#current-cloud-backend/#current-cloud-backend" and then complains about there being no "./#current-cloud-backend/amplify-meta.json".

This sounds like there's a nested `#current-cloud-backend` in the zip archive in s3

**Comment by mrcoles** [comment]
Ok I believe I finally got it working…

1. Find the project in s3, look for a bucket named something like `{project_name}-{id}-deployment`—if there are multiple, you can look in the amplify-meta.json file in each to see which env name is set as a suffix on the files
2. Download the `#current-cloud-backend.zip` file
3. View the file: `unzip -l \#current-cloud-backend.zip`
4. If it has a `#current-cloud-backend` directory in it, then unzip the file and create a new one within that directory, e.g., `unzip \#current-cloud-backend.zip && cd \#current-cloud-backend && zip -r \#current-cloud-backend.zip *`
5. Upload that new directory into the s3 bucket, replacing the old one
6. Now try a pull again, but you’ll need to do some extra work...
    1. I encountered `error constructs@10.2.55: The engine "node" is incompatible with this module. Expected version ">= 16.14.0". Got "14.18.3"`, so make sure you’re on a new enough node version, I did `echo 'v18.16.0' > .nvmrc && nvm use`
        * btw, is there any guidance on nvm for amplify?
        * also my lambdas are all running node v14.x—can I upgrade these? This is the best doc I could find: https://docs.amplify.aws/cli/function/configure-options/
    2. I also encountered an issue where it still expected ./amplify/backend/amplify-meta.json to exist, even though it’s set to be ignored from my .gitignore—is this a problem, should I remove that line from my gitignore? I ended up downloading that file and copying it in
    3. Now I was able to finally do `amplify pull --debug --appId d32cgdvim65k7p --envName dev`
    4. It felt weird that I had to specify everything again, specifically these ones which are intrinsic to the project, not different per person using it:
        * ? What javascript framework are you using react
        * ? Source Directory Path:  src
        * ? Distribution Directory Path: dist
        * ? Build Command:  npm run build
        * ? Start Command: npm start
      5. And this question was confusing, does it exist because some people want to literally only edit the front-end code and you make that an option? That’s weird though since my git repo has all the backend code in it already?
        * ? Do you plan on modifying this backend? Yes

Steps 1–5 are what you shared in [this comment](https://github.com/aws-amplify/amplify-cli/issues/12766#issuecomment-1597449526), but I needed the extra context on where specifically to find and then upload them.

In step 6, can you address the subquestions on node version and the ./amplify/backend/amplify-meta.json file?

**Comment by mrcoles** [comment]
Ok, thanks for the help!

> Although tedious, you can skip those prompts by specifying --yes.

This would be better if it could identify the defaults from my repo instead of suggesting platform-wide defaults, like I have to always tell it to use `dist` instead of `build`.

RE: node runtimes—here’s the list of supported runtimes that I was looking for: https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

Things are up and running again, so I’m closing the issue!
