### ISSUE TITLE
amplify init fails when using AWS IAM Identity Center: Failed to get profile credentials, Unexpected token A in JSON at position 0

### ISSUE THREAD

**Issue by restfulhead** [aws-amplify/amplify-cli#12777]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v18.16.0

### Amplify CLI Version

12.0.3

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No, I'm not even able to init.

### Describe the bug

Tryin to use Amplify with AWS IAM Identity Center. `amplify init --debug` fails with the following error:

```
 Failed to get profile credentials
Unexpected token A in JSON at position 0

Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

ProfileConfigurationError: Failed to get profile credentials
    at Object.getAwsConfig (/snapshot/repo/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/configuration-manager.js:939:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/initializer.js:119:27)

Unexpected token A in JSON at position 0
ProcessCredentialsProviderFailure: Unexpected token A in JSON at position 0
    at /snapshot/repo/build/node_modules/aws-sdk/lib/credentials/process_credentials.js:142:13
    at ChildProcess.exithandler (node:child_process:411:7)
    at ChildProcess.emit (node:events:513:28)
```

### Expected behavior

Amplify init should work.

### Reproduction steps

The same behavior was reported by @josefaidt in https://github.com/aws-amplify/amplify-cli/issues/12174#issuecomment-1476927553

The issue says it's fixed, but I'm using the latest version and it's apparently not fixed.

Steps to reproduce:
1. `aws configure sso`
2. `amplify init` 

This will fail with `Cannot read properties of undefined (reading 'accessKeyId')`.

3. Manually add `credential_process = aws sso login --profile ...` to `~/.aws/config`.
4. `amplify init` now redirects to SSO. After a successful login, the error above appears.

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @restfulhead :wave: thanks for raising this! How do you have your `~/.aws/config` file structured? When setting up SSO profiles you will also specify an `sso-session` entry:

```ini
[profile sso-josef]
sso_session=josef
sso_account_id=8147xxxxxx
sso_role_name=AdministratorAccess
region=us-east-1
credential_process=aws sso login --profile sso-josef

[sso-session josef] 
sso_start_url=https://d-xxxxx.awsapps.com/start
sso_region=us-east-1
sso_registration_scopes=sso:account:access
```

the `sso-session` entry should not show up in the list of available AWS profiles displayed during the `amplify init` flow. Can you confirm you have a setup similar to the example shown above? Are you able to use the associated AWS profile?

**Comment by restfulhead** [comment]
> Are you able to use the associated AWS profile?

Yes, CLI and also SAM work just fine.

> Can you confirm you have a setup similar to the example shown above?

Yes, mine looks similar:

```
[profile default]
sso_session = default
sso_account_id = ***
sso_role_name = AdministratorAccess
region = us-east-1
output = json
cli_pager=

[sso-session default]
sso_start_url = https://d-***.awsapps.com/start
sso_region = us-east-1
sso_registration_scopes = sso:account:access
```

> the `sso-session` entry should not show up in the list of available AWS profiles displayed during the `amplify init` flow. 

Oh, but it does show up:

![sso](https://github.com/aws-amplify/amplify-cli/assets/558375/bc0a591b-156f-4c28-b679-f281298b6525)

Btw, today I get another error:

```
🛑 Internal server error

Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

ProjectInitFault: Internal server error
    at init (/snapshot/repo/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/amplify-service-manager.js:200:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/initializer.js:132:9)
```

**Comment by josefaidt** [comment]
Hey @restfulhead thanks for checking on that! It's interesting the `sso-session` is showing up in this profile list. It showed up for me on the first `init`, but after I selected the associated profile the `sso-session` entry disappeared from the list. Using the `default` profile in your case should work, however there is an active issue in `us-east-1` that is causing the 500 "internal server error" you're seeing https://health.aws.amazon.com/health/status

I will mark this as a bug to remove the `sso-session` entries from the AWS profile list
