### ISSUE TITLE
Amplify cant find IdentityPool after change Message of SMS verification.

### ISSUE THREAD

**Issue by sprisao** [aws-amplify/amplify-cli#12781]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d6scr4mjs9vzt

### AWS Region

ap-southeast-1

### Amplify Hosting feature

Access control, Backend builds, Deployments

### Describe the bug

I have Amplify Authentication with Phonenumber mechanism.
After already deployed Amplify Auth with the setting, I wanted to change the message of verification SMS.
But then at the amplify configure it can't find IdentityPool with the Exception:

[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: ResourceNotFoundException {
  "message": "IdentityPool 'ap-southeast-1:c1918108-4200-4a1e-a01b-********' not found.",
  "underlyingException": "ResourceNotFoundException {\n  message=IdentityPool 'ap-southeast-1:c1918108-4200-4a1e-a01b-8d2292f7efd2' not found.,\n}"
}
#0      AWSErrorResult.value (package:aws_common/src/result/aws_result.dart:117:5)
aws-amplify/amplify-hosting#1      CognitoIamAuthProvider.retrieve (package:amplify_auth_cognito_dart/src/util/cognito_iam_auth_provider.dart:26:42)
<asynchronous suspension>
aws-amplify/amplify-hosting#2      WithSigV4.intercept (package:smithy_aws/src/http/interceptors/with_sig_v4.dart:37:7)
<asynchronous suspension>
aws-amplify/amplify-hosting#3      SmithyHttpRequest.transformRequest (package:smithy/src/http/http_request.dart:137:19)
<asynchronous suspension>

I've tried to change the verification message on Amplify Studio and also using amplify cli.
But both caused the error.

### Expected behavior

Changing message of verification SMS

### Reproduction steps

1. set Amplify Auth with phonenumber login mechanism
2. deploy
3. change message of verifcation SMS
4. deploy
5. Sometimes in the first a few minute it looks like it has been changed without problem.
6. After more minutes. It starts create the error.

### Log output

<details>

[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: ResourceNotFoundException {
  "message": "IdentityPool 'ap-southeast-1:c1918108-4200-4a1e-a01b-**********' not found.",
  "underlyingException": "ResourceNotFoundException {\n  message=IdentityPool 'ap-southeast-1:c1918108-4200-4a1e-a01b-8d2292f7efd2' not found.,\n}"
}
#0      AWSErrorResult.value (package:aws_common/src/result/aws_result.dart:117:5)
aws-amplify/amplify-hosting#1      CognitoIamAuthProvider.retrieve (package:amplify_auth_cognito_dart/src/util/cognito_iam_auth_provider.dart:26:42)
<asynchronous suspension>
aws-amplify/amplify-hosting#2      WithSigV4.intercept (package:smithy_aws/src/http/interceptors/with_sig_v4.dart:37:7)
<asynchronous suspension>
aws-amplify/amplify-hosting#3      SmithyHttpRequest.transformRequest (package:smithy/src/http/http_request.dart:137:19)
<asynchronous suspension>
aws-amplify/amplify-hosting#4      SmithyHttpRequest.send.<anonymous closure> (package:smithy/src/http/http_request.dart:185:23)
<asynchronous suspension>

</details>

**Comment by josefaidt** [comment]
Hey @sprisao :wave: how was the SMS message changed? Was this by modifying your auth's `cli-inputs.json` file? The error message is concerning as it is claiming the Identity Pool does not exist. If this is not the case and the identity pool does exist, can you try running `amplify env checkout <current-env-name>` to regenerate the configuration JSON file?

**Comment by josefaidt** [comment]
Closing due to inactivity
