### ISSUE TITLE
Amplify Storage Issue

### ISSUE THREAD

**Issue by vgthoppae** [aws-amplify/amplify-cli#12782]
### Amplify CLI Version

11.1.1

### Question

This may be something simple, but the `Storage.put` command works fine from localhost, but breaks when the app is accessed from the custom domain set up on hosting, with the below error. Simply puzzling. Appreciate any pointers.

```
TypeError: (0 , sx.resolveHostHeaderConfig) is not a function
    at new t (_app-355c5eb0eb8aef58.js:13:240132)
    at sL (_app-355c5eb0eb8aef58.js:13:242758)
    at e._createNewS3Client (_app-355c5eb0eb8aef58.js:13:256028)
    at new e (_app-355c5eb0eb8aef58.js:13:251009)
    at e.put (_app-355c5eb0eb8aef58.js:13:272345)
    at e.put (_app-355c5eb0eb8aef58.js:13:280266)
    at O (_app-355c5eb0eb8aef58.js:35:387332)
```

**Comment by ykethan** [comment]
👋 thanks for raising this! I'm going to transfer this over to our JavaScript repository for better assistance 🙂
