### ISSUE TITLE
Amplify init errors out for appsync event starter app

### ISSUE THREAD

**Issue by kvasukib** [aws-amplify/amplify-cli#1280]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Describe the bug**

Create the AppSync API using the Events Starter through the AppSync console.
Clone appsync events starter for Android
Run amplify init

```
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the project awsmobileappsynceven
? Enter a name for the environment beta
? Choose your default editor: Sublime Text
? Choose the type of app that you're building android
Please tell us about your project
? Where is your Res directory:  app/src/main/res
Using default provider  awscloudformation

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html

? Do you want to use an AWS profile? Yes
? Please choose the profile you want to use default
⠦ Initializing project in the cloud...

CREATE_IN_PROGRESS awsmobileappsynceven-20190415094023 AWS::CloudFormation::Stack Mon Apr 15 2019 09:40:23 GMT-0700 (PDT) User Initiated
CREATE_IN_PROGRESS UnauthRole                          AWS::IAM::Role             Mon Apr 15 2019 09:40:27 GMT-0700 (PDT)
CREATE_IN_PROGRESS AuthRole                            AWS::IAM::Role             Mon Apr 15 2019 09:40:27 GMT-0700 (PDT)
CREATE_IN_PROGRESS DeploymentBucket                    AWS::S3::Bucket            Mon Apr 15 2019 09:40:28 GMT-0700 (PDT)
CREATE_IN_PROGRESS UnauthRole                          AWS::IAM::Role             Mon Apr 15 2019 09:40:28 GMT-0700 (PDT) Resource creation Initiated
⠇ Initializing project in the cloud...

CREATE_IN_PROGRESS AuthRole AWS::IAM::Role Mon Apr 15 2019 09:40:29 GMT-0700 (PDT) Resource creation Initiated
⠦ Initializing project in the cloud...

CREATE_IN_PROGRESS DeploymentBucket AWS::S3::Bucket Mon Apr 15 2019 09:40:29 GMT-0700 (PDT) Resource creation Initiated
⠴ Initializing project in the cloud...

CREATE_COMPLETE UnauthRole AWS::IAM::Role Mon Apr 15 2019 09:40:46 GMT-0700 (PDT)
CREATE_COMPLETE AuthRole   AWS::IAM::Role Mon Apr 15 2019 09:40:46 GMT-0700 (PDT)
⠴ Initializing project in the cloud...

CREATE_COMPLETE DeploymentBucket AWS::S3::Bucket Mon Apr 15 2019 09:40:50 GMT-0700 (PDT)
⠦ Initializing project in the cloud...

CREATE_COMPLETE awsmobileappsynceven-20190415094023 AWS::CloudFormation::Stack Mon Apr 15 2019 09:40:54 GMT-0700 (PDT)
✔ Successfully created initial AWS cloud resources for deployments.
✔ Initialized provider successfully.
✖ There was an error initializing your environment.
init failed
SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at getCurrentAWSConfig (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-android/lib/frontend-config-creator.js:84:22)
    at createAWSConfig (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-android/lib/frontend-config-creator.js:26:28)
    at Object.createFrontendConfigs (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-android/index.js:23:10)
    at Object.onCategoryOutputsChange (/usr/local/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/on-category-outputs-change.js:22:33)
    at initializeEnv (/usr/local/lib/node_modules/@aws-amplify/cli/src/lib/initialize-env.js:79:27)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

**To Reproduce**
1. Create the AppSync API using the Events Starter through the AppSync console.
2. Clone appsync events starter for Android
3. Run amplify init

**Expected behavior**
Amplify init to succeed.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by UnleashedMind** [comment]
It turned out the starter repo
https://github.com/aws-samples/aws-mobile-appsync-events-starter-android.git
saved this file app/src/main/res/raw/awsconfiguration.json as a UTF-8 BOM file, probably because it was edited in Windows, causing the json parser to fail. 
see this node issue for more information: https://github.com/nodejs/node/issues/20649
I will talk to the team tomorrow to figure out the best solution for this.
