### ISSUE TITLE
amplify diagnose --send-report

### ISSUE THREAD

**Issue by Babymo1900** [aws-amplify/amplify-cli#12863]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v18.16.0

### Amplify CLI Version

12.1.1

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Created a new dataset and relations, delete it to check if was the cause of the issue but still can push or pull any information

### Describe the bug

Can't pull or push anything from amplify, it will have the same error.

### Expected behavior

Pull information from aplify

### Reproduction steps

amplify pull or amplify push

    "name": "UnknownNodeJSFault",
    "classification": "FAULT",
    "options": {
        "message": "UNKNOWN: unknown error, readlink 'C:\\Users\\fturr\\OneDrive\\Documents\\NewAppEnv\\andanza\\amplify\\backend\\api\\Andanza\\cli-inputs.json'",
        "resolution": "Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'",
        "code": "UNKNOWN"
    },
    "downstreamException": {
        "errno": -4094,
        "code": "UNKNOWN",
        "syscall": "readlink",
        "path": "C:\\Users\\fturr\\OneDrive\\Documents\\NewAppEnv\\andanza\\amplify\\backend\\api\\Andanza\\cli-inputs.json"
    },
    "resolution": "Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'",
    "code": "UNKNOWN",
    "link": "https://docs.amplify.aws/cli/project/troubleshooting/"
}

### Project Identifier

 33bc131caf4800a69d620e3cea14bb68

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @Babymo1900 :wave: thanks for raising this! Between the error's path and the project files captured by `diagnose` it appears this file does in fact exist, but out of curiosity was this project moved on the local filesystem? Is the project path captured in `amplify/.config/local-env-info.json` accurate?

**Comment by Babymo1900** [comment]
Hi @josefaidt it hasnt been moved at all, the project path is correct in the local-env-info.json file

**Comment by Babymo1900** [comment]
Sure:

{
    "name": "UnknownNodeJSFault",
    "classification": "FAULT",
    "options": {
        "message": "UNKNOWN: unknown error, readlink 'C:\\Users\\fturr\\OneDrive\\Documents\\NewAppEnv\\andanza\\amplify\\backend\\api\\Andanza\\cli-inputs.json'",
        "resolution": "Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'",
        "code": "UNKNOWN"
    },
    "downstreamException": {
        "errno": -4094,
        "code": "UNKNOWN",
        "syscall": "readlink",
        "path": "C:\\Users\\fturr\\OneDrive\\Documents\\NewAppEnv\\andanza\\amplify\\backend\\api\\Andanza\\cli-inputs.json"
    },
    "resolution": "Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'",
    "code": "UNKNOWN",
    "link": "https://docs.amplify.aws/cli/project/troubleshooting/"
}

**Comment by Babymo1900** [comment]
Heres the terminal view:
PS C:\Users\fturr\OneDrive\Documents\NewAppEnv\andanza> amplify pull --debug

Pre-pull status:
🛑 UNKNOWN: unknown error, readlink 'C:\Users\fturr\OneDrive\Documents\NewAppEnv\andanza\amplify\backend\api\Andanza\cli-inputs.json'

Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'  
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

UnknownNodeJSFault: UNKNOWN: unknown error, readlink 'C:\Users\fturr\OneDrive\Documents\NewAppEnv\andanza\amplify\backend\api\Andanza\cli-inputs.json'
    at nodeErrorToAmplifyException (C:\snapshot\repo\build\node_modules\@aws-amplify\cli-internal\lib\amplify-exception-handler.js:144:12)
    at handleException (C:\snapshot\repo\build\node_modules\@aws-amplify\cli-internal\lib\amplify-exception-handler.js:24:28)
    at process.<anonymous> (C:\snapshot\repo\build\node_modules\@aws-amplify\cli-internal\lib\index.js:52:93)
    at process.emit (node:events:513:28)
    at process._fatalException (node:internal/process/execution:149:25)

UNKNOWN: unknown error, readlink 'C:\Users\fturr\OneDrive\Documents\NewAppEnv\andanza\amplify\backend\api\Andanza\cli-inputs.json'
Error: UNKNOWN: unknown error, readlink 'C:\Users\fturr\OneDrive\Documents\NewAppEnv\andanza\amplify\backend\api\Andanza\cli-inputs.json'

Session Identifier: 14258b62-524e-4d4b-a7bd-e1a2221ddbd8

✅ Report saved: C:\Users\fturr\AppData\Local\Temp\Andanza\report-1689979491943.zip

√ Done

Project Identifier: 33c76be1cb6b929df95af8211c6985e8

**Comment by josefaidt** [comment]
Hey @Babymo1900 thanks for clarifying! Taking a further look at this one do you experience this when `amplify pull`-ing the project into a directory outside of the OneDrive directory?

**Comment by Babymo1900** [comment]
Not sure I havent deployed it outside of the OneDrive Directory, are you thinking thats the root cause?

**Comment by josefaidt** [comment]
@Babymo1900 it stood out to me when reviewing the `UnknownNodeJSFault: UNKNOWN: unknown error, readlink` error.

**Comment by Babymo1900** [comment]
Should I move the directory?

**Comment by josefaidt** [comment]
Hey @Babymo1900 can you try pulling it into a separate directory first? there's a `projectPath` property in `amplify/.config/local-env-info.json` that will need to be updated if you move the directory

**Comment by Babymo1900** [comment]
For sure, what would be the process to try pulling it from a separate directory?

**Comment by Babymo1900** [comment]
I pulled it from a different directory not in OneDrive and it worked, should I move the entire project off OneDrive?

**Comment by josefaidt** [comment]
Hey @Babymo1900 glad to hear that worked! Yes, I would suggest moving the project out of the OneDrive directory.

**Comment by josefaidt** [comment]
Hey @Babymo1900 just wanted to follow-up here, are you still experiencing this? Were you able to resolve the issue by moving it off of the OndDrive fodler?

**Comment by josefaidt** [comment]
Closing due to inactivity

**Comment by IanMurnane** [comment]
> I pulled it from a different directory not in OneDrive and it worked, should I move the entire project off OneDrive?

I had the same issue with OneDrive and this worked. Also once it was fixed in the new cloned folder, I was able to "amplify pull" in my original folder and everything was fixed.
