### ISSUE TITLE
Push Python lambda function fails

### ISSUE THREAD

**Issue by mh35** [aws-amplify/amplify-cli#12923]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v18.16.0

### Amplify CLI Version

12.1.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

1. Install Python 3.8, 3.9, 3.10, 3.11, pipenv and virtualenv via homebrew
2. Create function via Amplify CLI
3. Install required modules to function source directory via Docker container

### Describe the bug

When pushing to environment, packaging fails.

```
An error occurred while installing -e ./src! Will try again.
Installing initially failed dependencies...
Traceback (most recent call last):
  File "/usr/local/Cellar/pipenv/2023.7.9/libexec/bin/pipenv", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/Cellar/pipenv/2023.7.9/libexec/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/pipenv/2023.7.9/libexec/lib/python3.11/site-packages/pipenv/cli/options.py", line 58, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/pipenv/2023.7.9/libexec/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/pipenv/2023.7.9/libexec/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/pipenv/2023.7.9/libexec/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/pipenv/2023.7.9/libexec/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/pipenv/2023.7.9/libexec/lib/python3.11/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/pipenv/2023.7.9/libexec/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/pipenv/2023.7.9/libexec/lib/python3.11/site-packages/pipenv/cli/command.py", line 233, in install
    do_install(
  File "/usr/local/Cellar/pipenv/2023.7.9/libexec/lib/python3.11/site-packages/pipenv/routines/install.py", line 170, in do_install
    do_init(
  File "/usr/local/Cellar/pipenv/2023.7.9/libexec/lib/python3.11/site-packages/pipenv/routines/install.py", line 777, in do_init
    do_install_dependencies(
  File "/usr/local/Cellar/pipenv/2023.7.9/libexec/lib/python3.11/site-packages/pipenv/routines/install.py", line 455, in do_install_dependencies
    batch_install(
  File "/usr/local/Cellar/pipenv/2023.7.9/libexec/lib/python3.11/site-packages/pipenv/routines/install.py", line 596, in batch_install
    batch_install_iteration(
  File "/usr/local/Cellar/pipenv/2023.7.9/libexec/lib/python3.11/site-packages/pipenv/routines/install.py", line 538, in batch_install_iteration
    _cleanup_procs(project, procs, failed_deps_queue, retry=retry)
  File "/usr/local/Cellar/pipenv/2023.7.9/libexec/lib/python3.11/site-packages/pipenv/routines/install.py", line 651, in _cleanup_procs
    dep.use_pep517 = True
    ^^^^^^^^^^^^^^
  File "/usr/local/Cellar/pipenv/2023.7.9/libexec/lib/python3.11/site-packages/pipenv/vendor/requirementslib/models/common.py", line 18, in __setattr__
    raise ValueError(f'"{self.__class__.__name__}" object has no field "{name}"')
ValueError: "Requirement" object has no field "use_pep517"
```

### Expected behavior

Packaging will succeed.

### Reproduction steps

amplify push

### Project Identifier

25bc49dd8da25f103d04177367c06b9a

### Log output

<details>

```
2023-07-10T08:14:08.422Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["*********"])
2023-07-10T08:14:08.423Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"ap-northeast-1","source_profile":"*********","role_arn":"[***]:role/[***]nRole","mfa_serial":"*******"}])
2023-07-10T08:14:08.423Z|info : amplify-provider-awscloudformation.system-config-manager.getCacheFilePath(["/Users/********/.amplify/awscloudformation"])
2023-07-10T08:14:52.741Z|info : amplify-provider-awscloudformation.push-resources.uploadTemplateToS3.s3.uploadFile([{"Key":"[***]ify-[***]fn-[***]ates/[***]th/[***]th-[***]ger-[***]mation-[***]e.json"}])
2023-07-10T08:14:52.745Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Body":{"fd":null,"path":"/Users/****/Documents/*****/amplify/backend/auth/********/build/auth-trigger-cloudformation-template.json","flags":"r","mode":438,"end":null,"bytesRead":0,"_readableState":{"objectMode":false,"highWaterMark":65536,"buffer":{"head":null,"tail":null,"length":0},"length":0,"pipes":[],"flowing":null,"ended":false,"endEmitted":false,"reading":false,"constructed":false,"sync":true,"needReadable":false,"emittedReadable":false,"readableListening":false,"resumeScheduled":false,"errorEmitted":false,"emitClose":true,"autoDestroy":true,"destroyed":false,"errored":null,"closed":false,"closeEmitted":false,"defaultEncoding":"utf8","awaitDrainWriters":null,"multiAwaitDrain":false,"readingMore":false,"dataEmitted":false,"decoder":null,"encoding":null},"_events":{},"_eventsCount":1},"Key":"[***]ify-[***]fn-[***]ates/[***]th/[***]th-[***]ger-[***]mation-[***]e.json","Bucket":"[***]ify-[***]bcms-[***]ev-[***]709-[***]ment"}])
2023-07-10T08:16:24.856Z|error : Failed to install dependencies in /Users/*****/Documents/*********/amplify/backend/function/******: Error: Command failed with exit code 1: pipenv install```

</details>


### Additional information

_No response_

### Before submitting, please confirm:


- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @mh35 :wave: thanks for raising this! How was this Function configured? Is the runtime also manually set to v3.11?

**Comment by mh35** [comment]
No. The runtime is Python 3.8 (the default setting).

**Comment by mh35** [comment]
I found the solution.

It can be fixed with creating venv and install pipenv into that venv.
Do not use homebrew pipenv, it requires Python 3.11 and breaks building dependencies.

**Comment by freedomtowin** [comment]
> I found the solution.
> 
> It can be fixed with creating venv and install pipenv into that venv. Do not use homebrew pipenv, it requires Python 3.11 and breaks building dependencies.

I am guessing using an Anaconda (base 3.11) with 3.8 env + local venv also would have the same issue?

**Comment by freedomtowin** [comment]
I can confirm that creating a local env (with pipenv and wheel) using anaconda (3.8 VENV) works (compiles).

**Comment by josefaidt** [comment]
Hey @mh35 and @freedomtowin glad to hear y'all have found a suitable solution! I'll make a note of this for future reference, but will close this issue for now.

**Comment by johnemcbride** [comment]
> I found the solution.
> 
> It can be fixed with creating venv and install pipenv into that venv. Do not use homebrew pipenv, it requires Python 3.11 and breaks building dependencies.

Do you mind elaborating on this solution?
For example I used peen to install python 3.8 and added its bin to my path to get a python3.8 pipenv going, but now the .venv in my lambs function contains symlinks back to that and then the currentcloudbuild gets corrupted as those symlinks  effectively disappear.  Breaking my whole amplify app...
