### ISSUE TITLE
Can re-initialize deleted env

### ISSUE THREAD

**Issue by OperationalFallacy** [aws-amplify/amplify-cli#12938]
### How did you install the Amplify CLI?

not sure

### If applicable, what version of Node.js are you using?

18.3

### Amplify CLI Version

12.1.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes

### Describe the bug

I'm trying to restore env that got deleted accidentally.

I've found this blog post
https://aws.amazon.com/blogs/mobile/restoring-aws-amplify-project-after-deleting-it-from-the-cloud/

They said to delete `amplify/team-provider-info.json` which I did, and now running init from the root of project repo.

```
$ amplify init --envName dev --debug         
                        
Note: It is recommended to run this command from the root of your app directory
Using default provider  awscloudformation
⚠️ Failed to resolve AppId. Skipping parameter download.
✖ Initializing your environment: dev
✖ There was an error initializing your environment.
🛑 Could not initialize platform for 'dev': Missing required key 'Bucket' in params

Resolution: Review the error message and stack trace for additional information.
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

ProjectInitFault: Could not initialize platform for 'dev': Missing required key 'Bucket' in params
    at initializeEnv (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/initialize-env.js:103:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async onSuccess (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/init-steps/s9-onSuccess.js:94:5)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/commands/init.js:34:9)
    at async Object.executeAmplifyCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:194:9)
    at async executePluginModuleCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:139:5)
    at async executeCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:37:9)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:121:5)

Missing required key 'Bucket' in params
MissingRequiredParameter: Missing required key 'Bucket' in params
    at ParamValidator.fail (/snapshot/repo/build/node_modules/aws-sdk/lib/param_validator.js:50:37)
    at ParamValidator.validateStructure (/snapshot/repo/build/node_modules/aws-sdk/lib/param_validator.js:62:14)
    at ParamValidator.validateMember (/snapshot/repo/build/node_modules/aws-sdk/lib/param_validator.js:89:21)
    at ParamValidator.validate (/snapshot/repo/build/node_modules/aws-sdk/lib/param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (/snapshot/repo/build/node_modules/aws-sdk/lib/event_listeners.js:166:42)
    at Request.callListeners (/snapshot/repo/build/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at callNextListener (/snapshot/repo/build/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at /snapshot/repo/build/node_modules/aws-sdk/lib/event_listeners.js:120:11
    at finish (/snapshot/repo/build/node_modules/aws-sdk/lib/config.js:396:7)
    at /snapshot/repo/build/node_modules/aws-sdk/lib/config.js:414:9
    at Credentials.get (/snapshot/repo/build/node_modules/aws-sdk/lib/credentials.js:127:7)
    at getAsyncCredentials (/snapshot/repo/build/node_modules/aws-sdk/lib/config.js:408:24)
    at Config.getCredentials (/snapshot/repo/build/node_modules/aws-sdk/lib/config.js:428:9)
    at Request.VALIDATE_CREDENTIALS (/snapshot/repo/build/node_modules/aws-sdk/lib/event_listeners.js:111:28)
    at Request.callListeners (/snapshot/repo/build/node_modules/aws-sdk/lib/sequential_executor.js:102:18)
    at Request.emit (/snapshot/repo/build/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/snapshot/repo/build/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/snapshot/repo/build/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/snapshot/repo/build/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at Request.runTo (/snapshot/repo/build/node_modules/aws-sdk/lib/request.js:406:15)
    at /snapshot/repo/build/node_modules/aws-sdk/lib/request.js:795:12
    at new Promise (<anonymous>)
    at Request.promise (/snapshot/repo/build/node_modules/aws-sdk/lib/request.js:781:12)
    at S3.getFile (/snapshot/repo/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/aws-utils/aws-s3.js:118:54)
    at downloadZip (/snapshot/repo/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/zip-util.js:23:33)
    at Object.run (/snapshot/repo/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/initialize-env.js:34:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Expected behavior

env initialized

### Reproduction steps

1. delete environment in ui
2. try to restore with amplify init

### Project Identifier

f4c5586d188f83914c6ef1de654b22fa

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @OperationalFallacy :wave: thanks for raising this! To clarify, was the entire project deleted or just the environment?

**Comment by josefaidt** [comment]
@OperationalFallacy do you have other environments in the project?

**Comment by OperationalFallacy** [comment]
No, that was only one.

**Comment by josefaidt** [comment]
Hey @OperationalFallacy thanks for clarifying. To avoid manual cleanup of backend state files I would suggest creating a new project and deleting the project without any environments. Unfortunately once an environment has been deleted it cannot be restored, however it should be possible to recreate the same infrastructure in another environment with `amplify env add`

**Comment by OperationalFallacy** [comment]
Thank you for clarifying! It wasn't exactly clear from the blog post if the project+env act as a whole part.
