### ISSUE TITLE
Error when executing the “amplify init” command in windows environment (for an android studio project)

### ISSUE THREAD

**Issue by ELDHOSE-P-A** [aws-amplify/amplify-cli#1294]
**Describe the bug**

I was following the official documentation ( [This Page](https://aws-amplify.github.io/docs/android/start?ref=amplify-android-btn)) to setup my back-end of a new android studio project with the AWS Amplify, in my windows 10 Machine. 
in the step where I write the command:
`$amplify init`

I get the following error:

`
init failed
{Error: D:\EDUCATION\Developer\Final_Year_Project\MusicAppAWS\D:\EDUCATION\Developer\Final_Year_Project\MusicAppAWS\app\src\main\res\raw contains invalid WIN32 path characters 
at Object.mkdirsSync (C:\Users\eldho\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-frontend-android\node_modules\fs-extra\lib\mkdirs\mkdirs-sync.js:18:22)
    at generateAWSConfigFile (C:\Users\eldho\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-frontend-android\lib\frontend-config-creator.js:110:6)
    at createAWSConfig (C:\Users\eldho\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-frontend-android\lib\frontend-config-creator.js:32:3)
    at Object.createFrontendConfigs (C:\Users\eldho\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-frontend-android\index.js:23:10)
    at Object.onCategoryOutputsChange (C:\Users\eldho\AppData\Roaming\npm\node_modules\@aws-amplify\cli\src\extensions\amplify-helpers\on-category-outputs-change.js:22:33)
    at initializeEnv (C:\Users\eldho\AppData\Roaming\npm\node_modules\@aws-amplify\cli\src\lib\initialize-env.js:79:27)
    at process._tickCallback (internal/process/next_tick.js:68:7) code: 'EINVAL'}
`
### All the previous steps in the documentation worked fine for me

I'am running this in windows command prompt. I'm guessing that this error might be due to the path having characters like ":" as in "amplify-frontend-android\index.js:23:10" that are not supported in windows. I'am a beginner at coding and I'm clueless how to fix this problem.

**Screenshots**
![Screenshot of the error](https://user-images.githubusercontent.com/17046794/56259927-8585c780-60f2-11e9-8d9d-eec3aeaee83a.jpg)

**Desktop :**
 - OS: Windows 10
 - Android Studio Version 3.2.1

**Comment by UnleashedMind** [comment]
@ELDHOSE-P-A 
when prompt "Where is your Res directory:" 
only enter the relative path "app\src\main\res" instead of the full path. 
I will also mark this as an enhancement because the CLI should have the smarts to detect his.

**Comment by ELDHOSE-P-A** [comment]
@UnleashedMind 
Awesome, it worked just fine. Thanks for the help.

**Comment by inaki332** [comment]
> @ELDHOSE-P-A
> when prompt "Where is your Res directory:"
> only enter the relative path "app\src\main\res" instead of the full path.
> I will also mark this as an enhancement because the CLI should have the smarts to detect his.

How do I access the prompt again once I've messed up the configuration? I have the same error as above when I try to "amplify pull" and i'm not sure where to change that path?
