### ISSUE TITLE
amplify init - You have reached the Amplify App limit for this account and region

### ISSUE THREAD

**Issue by Sky-Soo-Ap** [aws-amplify/amplify-cli#13126]
### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v18.17.1

### Amplify CLI Version

12.2.5

### What operating system are you using?

Windows 10

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

"No manual changes made"

### Describe the bug

I have 1 amplify app and following is the "amplify init --debug" log.

D:\SkySoo\Projects\AWS\Modified_Code\gw-rainbow>amplify init --debug
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the project gwrainbow
The following configuration will be applied:

Project information
| Name: gwrainbow
| Environment: dev
| Default editor: Visual Studio Code
| App type: javascript
| Javascript framework: react
| Source Directory Path: src
| Distribution Directory Path: build
| Build Command: npm.cmd run-script build
| Start Command: npm.cmd run-script start

? Initialize the project with the above configuration? Yes
Using default provider  awscloudformation
? Select the authentication method you want to use: AWS profile

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

? Please choose the profile you want to use default
🛑 You have reached the Amplify App limit for this account and region

Resolution: Use a different account or region with fewer apps, or request a service limit increase: https://docs.aws.amazon.com/general/latest/gr/amplify.html#service-quotas-amplify
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

ProjectInitError: You have reached the Amplify App limit for this account and region
    at init (C:\snapshot\repo\build\node_modules\@aws-amplify\amplify-provider-awscloudformation\lib\amplify-service-manager.js:151:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.run (C:\snapshot\repo\build\node_modules\@aws-amplify\amplify-provider-awscloudformation\lib\initializer.js:96:9)

Failed to create app. You have reached the maximum number of apps in this account.
LimitExceededException: Failed to create app. You have reached the maximum number of apps in this account.
    at Object.extractError (C:\snapshot\repo\build\node_modules\aws-sdk\lib\protocol\json.js:80:27)
    at Request.extractError (C:\snapshot\repo\build\node_modules\aws-sdk\lib\protocol\rest_json.js:61:8)
    at Request.callListeners (C:\snapshot\repo\build\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
    at Request.emit (C:\snapshot\repo\build\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (C:\snapshot\repo\build\node_modules\aws-sdk\lib\request.js:686:14)
    at Request.transition (C:\snapshot\repo\build\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\snapshot\repo\build\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\snapshot\repo\build\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\snapshot\repo\build\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\snapshot\repo\build\node_modules\aws-sdk\lib\request.js:688:12)
    at Request.callListeners (C:\snapshot\repo\build\node_modules\aws-sdk\lib\sequential_executor.js:116:18)
    at Request.emit (C:\snapshot\repo\build\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (C:\snapshot\repo\build\node_modules\aws-sdk\lib\request.js:686:14)
    at Request.transition (C:\snapshot\repo\build\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\snapshot\repo\build\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\snapshot\repo\build\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\snapshot\repo\build\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\snapshot\repo\build\node_modules\aws-sdk\lib\request.js:688:12)
    at Request.callListeners (C:\snapshot\repo\build\node_modules\aws-sdk\lib\sequential_executor.js:116:18)
    at callNextListener (C:\snapshot\repo\build\node_modules\aws-sdk\lib\sequential_executor.js:96:12)
    at IncomingMessage.onEnd (C:\snapshot\repo\build\node_modules\aws-sdk\lib\event_listeners.js:417:13)
    at IncomingMessage.emit (node:events:525:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Session Identifier: 709794e9-1285-4145-b7b9-90ec4047291c

D:\SkySoo\Projects\AWS\Modified_Code\gw-rainbow>

### Expected behavior

amplify init work normally as before.

### Reproduction steps

1. npm install -g @aws-amplify/cli
2. amplify configure
3. create a new React app;
npx create-react-app react-amplified
cd react-amplified
4. amplify init

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @Sky-Soo-Ap, thank you for reaching out. 

> You have reached the Amplify App limit for this account and region

It appears you have reach the application limit in the account and region, to mitigate the issue could you open a quota increase request? Please refer to the document providing this information. https://docs.aws.amazon.com/servicequotas/latest/userguide/request-quota-increase.html

**Comment by Sky-Soo-Ap** [comment]
Hi [ykethan](https://github.com/ykethan),
After increasing AWS-Amplify quotas, then ‘amplify init’ succeeded, so closed it.
