### ISSUE TITLE
Unable to add Apple Auth to cognito both time when attempting to add through Amplify Studio and CLI it fails: Log shows InternalErrorException

### ISSUE THREAD

**Issue by aryan1107** [aws-amplify/amplify-cli#13200]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
  System:
    OS: macOS 13.5.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 214.83 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm
    pnpm: 8.6.11 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 116.0.5845.179
    Safari: 16.6
  npmGlobalPackages:
    @aws-amplify/cli: 12.4.0
    corepack: 0.17.0
    firebase-tools: 12.4.6
    npm: 9.5.1
    pnpm: 8.6.11
    yarn: 1.22.19

```

</details>

### Describe the bug

Basically When Adding Apple Oauth the deployment fails have tried adding through Amplify Studio first and then CLI both time it gives same error to check the log. Then test it by adding Google Oauth it was successful problem lies when adding Apple auth.

Example error:
```
Received response status [FAILED] from custom resource. Message returned: See the details in CloudWatch Log Stream: 2023/09/08/[$LATEST]d7d81d4f1c5f4dc7a0263cab93205e7e
```

Here is the log:
```
2023-09-08T16:14:35.260Z	2bd35fc1-34ce-4fb9-9e1a-a45ddf8690a4	INFO	InternalErrorException: Internal server error.
    at deserializeAws_json1_1InternalErrorExceptionResponse (/var/runtime/node_modules/@aws-sdk/client-cognito-identity-provider/dist-cjs/protocols/Aws_json1_1.js:6611:23)
    at deserializeAws_json1_1CreateIdentityProviderCommandError (/var/runtime/node_modules/@aws-sdk/client-cognito-identity-provider/dist-cjs/protocols/Aws_json1_1.js:2933:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /var/runtime/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /var/runtime/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:13:20
    at async StandardRetryStrategy.retry (/var/runtime/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
    at async /var/runtime/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
    at async createIdentityProvider (/var/task/index.js:96:3)
    at async handleEvent (/var/task/index.js:45:9)
    at async tryHandleEvent (/var/task/index.js:18:5)

```

### Expected behavior

Deployment Failure for Auth.

### Reproduction steps

When Adding apple OAuth trough amplify studio and then clicking on deploy.

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Additional information and screenshots
<img width="694" alt="Screenshot 2023-09-08 at 12 42 25 PM" src="https://github.com/aws-amplify/amplify-js/assets/31214277/d86388b0-6ae1-42fd-a19f-49e0ee388313">

Below Image from the log:
<img width="1394" alt="Screenshot 2023-09-08 at 12 39 00 PM" src="https://github.com/aws-amplify/amplify-js/assets/31214277/cda86ad9-5d1d-4d76-947c-b5e69f4081be">

**Comment by josefaidt** [comment]
Hey @aryan1107 :wave: did this occur after adding Sign in with Apple to an existing, OAuth-enabled Cognito resource? Sometimes we will see this custom Lambda callout fail due to an invalid/malformed private key. Can you try re-inputting the key without spaces and newlines?

**Comment by aryan1107** [comment]
Hi key was not the problem as I was uploading key file. I tried both method
it failed lastly I created a new project and this time used cli entirely
and was able to add Apple auth.

**Comment by josefaidt** [comment]
Hey @aryan1107 glad to hear you were able to workaround the issue by using the CLI. I was chatting with a few friends over at Amplify Studio and found this active bug that describes the issue you were experiencing uploading the SIWA key there https://github.com/aws-amplify/amplify-studio/issues/792.

I'll close this issue for now, but please feel free to add your thoughts or a 👍 to the linked issue
