### ISSUE TITLE
Using interface as a field causes codegen error.

### ISSUE THREAD

**Issue by mnikolic10** [aws-amplify/amplify-cli#13225]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.15.1

### Amplify CLI Version

12.0.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

I initially had a failure when running amplify push, the cloudformation stack was stuck in update rollback state, so i resolved by manually continuing the rollback.

### Describe the bug

When running `amplify codegen models` i receive an error 

_"Unknown type Cuisine for field items. Did you forget to add the @model directive"_

In the time i've spent debugging I can see the issue is coming from using Cuisine as a field within another type, see example snippet below:

```
interface Cuisine {
  id: ID!
  name: String!
  type: ItemType
  cuisineColor: String
  locations: [Float]
  allRatings: [Int]
  rating: Float
}

type GlobalCuisine implements Cuisine
  @model
  @auth(rules: [{allow: public}])
  @searchable {
...
}

type ContinentCuisine implements Cuisine
  @model
  @auth(rules: [{allow: public}])
  @searchable {
...
}

type CountryCuisine implements Cuisine
  @model
  @auth(rules: [{allow: public}])
  @searchable {
...
}

type Query {
  searchCuisines(input: CuisineSearchInput): CuisinesConnection
}

type CuisinesConnection {
  items: [Cuisine]
  total: Int
  nextToken: String
}
```

### Expected behavior

Would have expected this to compile correctly as it was previously working.

### Reproduction steps

**How can this bug be reproduced?**

1. Run amplify codegen models
2. See error logged and no models file generated.

**Will running the exact steps below in an empty directory create an Amplify project that demonstrates the bug behavior?**

I believe this likely to be an individual issue within my environment but may be helpful if others encounter a similar issue

`Screenshots can be provided in the issue body below.`
<img width="562" alt="Screenshot 2023-09-15 at 12 07 40 pm" src="https://github.com/aws-amplify/amplify-cli/assets/12807915/af0c1726-20d8-43f7-8603-fa3795419574">

### Project Identifier

33607ffacefa5dabac82046c3bfc9645

### Log output

<details>

```
# Put your logs below this line

Unknown type Cuisine for field items. Did you forget to add the @model directive
Error: Unknown type Cuisine for field items. Did you forget to add the @model directive
    at AppSyncModelJavascriptVisitor.getNativeType (/snapshot/repo/build/node_modules/@aws-amplify/appsync-modelgen-plugin/lib/visitors/appsync-visitor.js:218:19)
    at AppSyncModelJavascriptVisitor.getNativeType (/snapshot/repo/build/node_modules/@aws-amplify/appsync-modelgen-plugin/lib/visitors/appsync-typescript-visitor.js:227:32)
    at /snapshot/repo/build/node_modules/@aws-amplify/appsync-modelgen-plugin/lib/visitors/appsync-typescript-visitor.js:132:63
    at Array.forEach (<anonymous>)
    at AppSyncModelJavascriptVisitor.generateModelDeclaration (/snapshot/repo/build/node_modules/@aws-amplify/appsync-modelgen-plugin/lib/visitors/appsync-typescript-visitor.js:130:25)
    at /snapshot/repo/build/node_modules/@aws-amplify/appsync-modelgen-plugin/lib/visitors/appsync-javascript-visitor.js:24:38
    at Array.map (<anonymous>)
    at AppSyncModelJavascriptVisitor.generate (/snapshot/repo/build/node_modules/@aws-amplify/appsync-modelgen-plugin/lib/visitors/appsync-javascript-visitor.js:24:18)
    at Object.plugin (/snapshot/repo/build/node_modules/@aws-amplify/appsync-modelgen-plugin/lib/plugin.js:55:24)
    at /snapshot/repo/build/node_modules/@graphql-codegen/core/cjs/execute-plugin.js:36:54
    at /snapshot/repo/build/node_modules/@graphql-codegen/core/node_modules/@graphql-codegen/plugin-helpers/cjs/profiler.js:7:49


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @mnikolic10 :wave: thanks for raising this! I'm going to transfer this over to our API repo for better support 🙂
