### ISSUE TITLE
After creating lambda function: Haste module naming collision

### ISSUE THREAD

**Issue by juri-diener** [aws-amplify/amplify-cli#13244]
### If applicable, what version of Node.js are you using?

20.6.1

### Amplify CLI Version

12.4.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Not that I know.

### Describe the bug

After creating a lambda function with amplify add function and going through all the steps and then following this article:
https://dev.to/codebeast/how-to-create-a-record-in-dynamodb-when-a-user-signs-up-34e2

I get following Error when I start my app with expo start.
```
metro-file-map: Haste module naming collision: insertuserintablefromcognitouser
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/amplify/#current-cloud-backend/function/InsertUserInTableFromCognitoUser/src/package.json
    * <rootDir>/amplify/backend/function/InsertUserInTableFromCognitoUser/src/package.json

Failed to construct transformer:  DuplicateError: Duplicated files or mocks. Please check the console for more info
    at setModule (/Users/juridiener/Projects/react-native/my-app/node_modules/metro-file-map/src/index.js:450:17)
    at workerReply (/Users/juridiener/Projects/react-native/my-app/node_modules/metro-file-map/src/index.js:507:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 98)
    at async HasteMap._applyFileDelta (/Users/juridiener/Projects/react-native/my-app/node_modules/metro-file-map/src/index.js:672:7)
    at async /Users/juridiener/Projects/react-native/my-app/node_modules/metro-file-map/src/index.js:327:9
    at async DependencyGraph.ready (/Users/juridiener/Projects/react-native/my-app/node_modules/metro/src/node-haste/DependencyGraph.js:95:5)
    at async Bundler.ready (/Users/juridiener/Projects/react-native/my-app/node_modules/metro/src/Bundler.js:69:5)
    at async IncrementalBundler.ready (/Users/juridiener/Projects/react-native/my-app/node_modules/metro/src/IncrementalBundler.js:289:5)
    at async Server.ready (/Users/juridiener/Projects/react-native/my-app/node_modules/metro/src/Server.js:1085:5) {
  mockPath1: 'amplify/#current-cloud-backend/function/InsertUserInTableFromCognitoUser/src/package.json',
  mockPath2: 'amplify/backend/function/InsertUserInTableFromCognitoUser/src/package.json'
}
```

### Expected behavior

No naming collision

### Reproduction steps

https://dev.to/codebeast/how-to-create-a-record-in-dynamodb-when-a-user-signs-up-34e2

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @juri-diener :wave: thanks for raising this! Is your app importing any files from the `amplify/` directory? Are you able to ignore this directory entirely from your expo build/start?

**Comment by josefaidt** [comment]
Closing due to inactivity
