### ISSUE TITLE
Error adding lambda trigger to cognito user pool using cli

### ISSUE THREAD

**Issue by destradar93** [aws-amplify/amplify-cli#13286]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v18.17.1

### Amplify CLI Version

12.5.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

I added a custom attribute

### Describe the bug

When attempting to configure a Lambda trigger for a Cognito User Pool using the Amplify CLI, the process encounters an error, preventing successful configuration. The issue occurs during the configuration of a "Post Confirmation" trigger when selecting the option to "Create your own module."

### Expected behavior

The Amplify CLI should successfully add a Lambda trigger for the Post Confirmation event in the Cognito User Pool without any errors.

### Reproduction steps

1.  Run the amplify auth update command.
2. Follow the on-screen prompts to configure authentication settings.
3. When asked, "Do you want to configure Lambda Triggers for Cognito?" choose "Yes."
4. Select "Post Confirmation" as the trigger type.
5. Choose "Create your own module" as the method to create the Lambda trigger.

### Log output

<details>

```
Error: InvalidOverrideError: Executing overrides failed.
    at generateUserPoolGroupStackTemplate (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-category-auth/lib/provider-utils/awscloudformation/utils/generate-user-pool-group-stack-template.js:11:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async updateUserPoolGroups (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-category-auth/lib/provider-utils/awscloudformation/utils/synthesize-resources.js:224:9)
    at async /snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-category-auth/lib/provider-utils/awscloudformation/handlers/resource-handlers.js:66:9
    at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-category-auth/lib/commands/auth/update.js:94:40)
    at async Object.executeAmplifyCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-category-auth/lib/index.js:347:5)
    at async executePluginModuleCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:139:5)
    at async executeCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:37:9)
    at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:121:5)
🛑 There was an error adding the auth resource
```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @destradar93 :wave: thanks for raising this! From the error it appears there is an error in of the project's overrides, would you mind sharing the auth override file? The resource is likely being built at the end of the `amplify add|update auth` flow and failing to complete the operation due to the override error.

**Comment by destradar93** [comment]
Hey @josefaidt thanks for the response! Do you mean this file?

override.ts
````
import { AmplifyUserPoolGroupStackTemplate } from '@aws-amplify/cli-extensibility-helper';

export function override(resources: AmplifyUserPoolGroupStackTemplate) {
    resources.roleMapLambdaFunction.runtime = "nodejs18.x"
}
````

**Comment by josefaidt** [comment]
Despite the underlying issue here, invalid overrides should fail on `amplify build` and `amplify push` rather than at the end of an update to the resource, and the stack trace should not print if `--debug` was not provided.

Marking as a bug

**Comment by destradar93** [comment]
Hey @josefaidt thanks for the reply. I did exactly what you described and it worked by adding the postConfirmation lambda trigger, but I had some problems deploying the project:

1. "amplify push": 
```
✖ There was an error pulling the backend environment dev.
🛑 Executing overrides failed.
Cannot set properties of undefined (setting 'runtime')
```

2. After encountering this error and with the Lambda function already created, I rolled back the changes in the override file. I was able to deploy the project with the new Lambda function, but the function was created in the cloud without an EventBridge trigger. When I searched for the Lambda function within the user pool, it did not appear in the Lambda triggers section.

**Comment by josefaidt** [comment]
Hey @destradar93 how are you configuring this Lambda trigger with the auth resource? If this is a trigger you are attempting to modify it unfortunately cannot be modified via auth overrides
