### ISSUE TITLE
Pulling environment fails in latest (12.6) CLI version

### ISSUE THREAD

**Issue by szymondobrzanski** [aws-amplify/amplify-cli#13313]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v18.15.0

### Amplify CLI Version

12.6

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

After upgrading CLI to version 12.6 pulling environments stopped working.
![Zrzut ekranu 2023-10-6 o 11 01 08](https://github.com/aws-amplify/amplify-cli/assets/119587310/a948781d-1d7c-4783-97b7-85783f101f5c)

### Expected behavior

amplify pull works

### Reproduction steps

1. Upgrade CLI to latest version
2. Run 'amplify pull' command for any environment

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by mkaya95** [comment]
Hi,

I just had the same problem. It seems that there is a problem with the amplify-cli version 12.6.0. Therefore I downgraded version  to 12.5.2. 

**App settings**: **Environment variables** -> 
Overwrite **_LIVE_UPDATES** variable like this;
`
[{"pkg":"@aws-amplify/cli","type":"npm","version":"12.5.2"}]
`

**Comment by ykethan** [comment]
Hey @szymondobrzanski @mkaya95 , thank you for reaching. In an empty directory could try using the pull command with the `--debug` and provide us the output?
Additionally, in the `~/.amplify/logs` directory should contain log files with `amplify-cli-<Timestamp>.log`. Could you rerun the pull command and provide us with any notable error messages observed in the log file or the log outputs?

**Comment by mkaya95** [comment]
@ykethan 
When I was pulling/pushing locally I was not receiving any error.  However, had a problem with the CI/CD pulling/pushing

```
2023-10-06T12:21:02.582Z [WARNING]: WARNING: You are using pip version 19.2.3, however version 23.2.1 is available.
                                    You should consider upgrading via the 'pip install --upgrade pip' command.
2023-10-06T12:21:05.156Z [INFO]: [0mAmplify AppID found: d2***b*pr****. Amplify App name is: CloudFinances-CMS/Backend[0m
2023-10-06T12:21:05.198Z [INFO]: [0mBackend environment dev found in Amplify Console app: MYAPPNAME-CMS/Backend[0m
2023-10-06T12:21:10.962Z [INFO]: 🛑 Failed to pull the backend.
2023-10-06T12:21:10.965Z [INFO]: Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/
2023-10-06T12:21:10.974Z [INFO]: 
2023-10-06T12:21:10.974Z [INFO]: Session Identifier: 7824654a-862a-4b96-9014-6ba56eba6ce5
2023-10-06T12:21:10.995Z [ERROR]: !!! Build failed
2023-10-06T12:21:10.995Z [ERROR]: !!! Non-Zero Exit Code detected
2023-10-06T12:21:10.995Z [INFO]: # Starting environment caching...
2023-10-06T12:21:10.996Z [INFO]: # Uploading environment cache artifact...
2023-10-06T12:21:11.047Z [INFO]: # Uploaded environment cache artifact
2023-10-06T12:21:11.047Z [INFO]: # Environment caching completed
```

**Comment by ykethan** [comment]
Hey @mkaya95, thank you for the information. Tried reproducing the issue but did not observe a similar behaviour. 
Could you run `amplify diagnose --send-report ` in your local env and provide us the Project Identifier printed in the output.
Additionally, Could you provide some information on the project, for example is this a mono repo or the `amplify.yml` file utilized.
This would assist in reproducing the issue.

**Comment by szymondobrzanski** [comment]
Hello @ykethan. Issue is happening to me only in project that uses mono repo. For the other 'normal' one, pulling works correctly.
I run `amplify pull --debug` as you requested. This is console output:
```
🛑 Failed to pull the backend.

Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

PullBackendFault: Failed to pull the backend.
    at attachBackend (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/attach-backend.js:55:15)
    at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/commands/pull.js:55:17)
    at async Object.executeAmplifyCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:194:9)
    at async executePluginModuleCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:139:5)
    at async executeCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:37:9)
    at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:121:5)

Cannot copy '../uuid/dist/bin/uuid' to a subdirectory of itself, '../uuid/dist/bin/uuid'.
Error: Cannot copy '../uuid/dist/bin/uuid' to a subdirectory of itself, '../uuid/dist/bin/uuid'.
    at onLink (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:146:13)
    at getStats (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:49:45)
    at startCopy (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
    at copyDirItem (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:120:10)
    at /snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:39
    at Array.forEach (<anonymous>)
    at copyDir (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:23)
    at onDir (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:103:10)
    at getStats (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:45:37)
    at startCopy (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
    at copyDirItem (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:120:10)
    at /snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:39
    at Array.forEach (<anonymous>)
    at copyDir (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:23)
    at onDir (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:103:10)
    at getStats (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:45:37)
    at startCopy (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
    at copyDirItem (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:120:10)
    at /snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:39
    at Array.forEach (<anonymous>)
    at copyDir (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:23)
    at onDir (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:103:10)
    at getStats (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:45:37)
    at startCopy (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
    at copyDirItem (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:120:10)
    at /snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:39
    at Array.forEach (<anonymous>)
    at copyDir (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:23)
    at onDir (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:103:10)
    at getStats (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:45:37)
    at startCopy (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
    at copyDirItem (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:120:10)
    at /snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:39
    at Array.forEach (<anonymous>)
    at copyDir (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:23)
    at onDir (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:103:10)
    at getStats (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:45:37)
    at startCopy (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
    at copyDirItem (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:120:10)
    at /snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:39
    at Array.forEach (<anonymous>)
    at copyDir (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:23)
    at onDir (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:103:10)
    at getStats (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:45:37)
    at startCopy (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
    at handleFilterAndCopy (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:33:10)
    at Object.copySync (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:26:10)
    at downloadBackend (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/attach-backend.js:346:24)
    at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/attach-backend.js:117:3)
    at async Object.attachBackend (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/index.js:196:3)
    at async queryProvider (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/attach-backend-steps/a10-queryProvider.js:36:5)
    at async attachBackend (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/attach-backend.js:43:9)
    at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/commands/pull.js:55:17)
    at async Object.executeAmplifyCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:194:9)
    at async executePluginModuleCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:139:5)
    at async executeCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:37:9)
    at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:121:5)

Session Identifier: 954c7bc0-db70-4360-a118-61ece5bb9b8f
```

**Comment by ykethan** [comment]
@szymondobrzanski thank you for the information. From the error message it appears to be occurring on a uuid package. Is this package part of you lambda function or lambda layer?
Tried to reproduce the issue by creating a mono-repo with lambda layer and function with uuid package, then committed to git, on the hosting build i did not observe any errors on a push or pull.

Could you provide us some additional information `amplify.yml` script being utilized on Amplify hosting and function/layers configuration(if any)? As this would assist in reproducing the behavior.
Could you run amplify `diagnose --send-report`  in your local env and provide us the Project Identifier printed in the output.

**Comment by szymondobrzanski** [comment]
Yes, uuid package is used in couple of lambdas, it's used to set id for models object's created by GraphQLClient. 
This is amplify.yml we are currently using:
```
version: 1
backend:
  phases:
    preBuild:
      commands:
        - ln -fs /usr/local/bin/pip3.8 /usr/bin/pip3
        - ln -fs /usr/local/bin/python3.8 /usr/bin/python3
        - pip3 install --user pipenv
        - cd packages/aws_repository/amplify/backend/function/cannabebackendlambdaGQLLayer/lib/
        - npm install
        - cd ../../../../..
        - pwd
        - amplify uninstall -y
        - npm install -g @aws-amplify/cli@12.5.2 
    build:
      commands:
        - amplify version
        - amplifyPush --simple
        - amplify push
        - pwd
        - |
          JSON_FILE="amplify/.config/local-env-info.json"
    
          if [ -f "$JSON_FILE" ]; then
            curr_env=$(grep -oP '"envName": "\K[^"]+' "$JSON_FILE")
            echo "Current environment: $curr_env"
          else
            echo "err: file $JSON_FILE does not exist."
          fi
        - echo ${curr_env}
        - aws s3 cp ./lib/amplifyconfiguration.dart s3://amplify-configuration-files/${curr_env}/amplifyconfiguration.dart
  artifacts:
    baseDirectory: /
    files:
      - '**/*'
  cache:
    paths: []
frontend:
  phases:
    build:
      commands: []
  artifacts:
    baseDirectory: /
    files:
      - '**/*'
  cache:
    paths: []
```
 
Project identifier: 14b516f1a9f9856b80b4fbd680c2de74

**Comment by ykethan** [comment]
Hey @szymondobrzanski, thank you for your patience. On multiple tries creating a monorepo with functions and layers with uuid packages i have been unable to reprodue the issue. Additionally, tried utilizing the provided `amplify.yml` in the hosting build to replicate the issue but i was unable to replicate the behaviour. 
To dive deeper into the issue, would you be open to sharing your amplify folder at `amplify-cli@amazon.com`?

**Comment by szymondobrzanski** [comment]
Hey @ykethan, email sent, let me know if you need anything else.

**Comment by ykethan** [comment]
Hey @szymondobrzanski, apologies but we did not receive an email, could you check if the email may have failed due to size constraints.

**Comment by szymondobrzanski** [comment]
It looks like it was sent properly, anyway I sent it from another mailbox.

**Comment by ykethan** [comment]
Hey @szymondobrzanski, thank you for the folder. I was able to reproduce the behaviour, the issue appears to be occurring on the `cannabebackendlambdaGQLLayer `. 
For a quick test on removing the following lines in the yml script, the push succeeds. 
```
- cd packages/aws_repository/amplify/backend/function/cannabebackendlambdaGQLLayer/lib/
- npm install
- cd ../../../../..
```
on diving into the layer, noticed the packages were installed at the root of the `lib` folder instead of the `lib/nodejs` folder which comes with the `package.json`. Could provide us some additional information for installing the packages at lib, is this expected. Could you try installing the packages in the `/lib/nodejs` and retry the build?

Furthermore, creating a new Amplify backend with the layer and build script then connecting the hosting. Noticed the first build was successful but re-running the same build causes the build fail with the following error creating a symlink

```
  Cannot copy '../uuid/dist/bin/uuid' to a subdirectory of itself, '../uuid/dist/bin/uuid'.
Error: Cannot copy '../uuid/dist/bin/uuid' to a subdirectory of itself, '../uuid/dist/bin/uuid'.
```

**Comment by szymondobrzanski** [comment]
Thank you @ykethan, after I moved `package.json` to `/lib/nodejs` pulling started to work fine in latest CLI version.
