### ISSUE TITLE
Can't add lambda function to my vue2 app using aws amplify cli

### ISSUE THREAD

**Issue by Johankoekoepan** [aws-amplify/amplify-cli#13374]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [x] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Vue

### Amplify APIs

REST API

### Amplify Categories

function

### Environment information

<details>

```
# Put output below this line
$ npx envinfo --system --binaries --browsers --npmPackages --duplicates --npmGlobalPackages

  System:
    OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Memory: 8.57 GB / 15.55 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Browsers:
    Chrome: 117.0.5938.149
  npmPackages:
    @aws-amplify/ui-components: ^1.9.6 => 1.9.40 (1.9.6)
    @aws-amplify/ui-vue: ^1.0.11 => 1.1.20 
    @babel/core: ^7.12.16 => 7.20.12 
    @babel/eslint-parser: ^7.12.16 => 7.19.1 
    @vue/cli-plugin-babel: ~5.0.0 => 5.0.8 
    @vue/cli-plugin-eslint: ~5.0.0 => 5.0.8 
    @vue/cli-plugin-pwa: ~5.0.0 => 5.0.8 
    @vue/cli-service: ~5.0.0 => 5.0.8 
    @vue/compiler-sfc:  2.7.14 
    amplify-ui-components-loader:  undefined ()
    aws-amplify: ^4.3.21 => 4.3.46 
    aws-sdk: ^2.1185.0 => 2.1481.0 
    core-js: ^3.8.3 => 3.27.2 
    deepmerge: ^4.2.2 => 4.3.0 (1.5.2)
    dev:  1.0.0 
    eslint: ^7.32.0 => 7.32.0 
    eslint-plugin-vue: ^8.0.3 => 8.7.1 
    register-service-worker: ^1.7.2 => 1.7.2 
    sass: ~1.32.0 => 1.32.13 
    sass-loader: ^10.2.1 => 10.4.1 
    vue: ^2.6.14 => 2.7.14 
    vue-cli-plugin-vuetify: ~2.4.8 => 2.4.8 
    vue-cookie-law: ^1.13.3 => 1.13.3 
    vue-router: ^3.5.3 => 3.6.5 
    vue-template-compiler: ^2.6.14 => 2.7.14 
    vuetify: ^2.6.5 => 2.6.14 
    vuetify-loader: ^1.7.0 => 1.9.2 
    vuex: ^3.6.2 => 3.6.2 

```

</details>

### Describe the bug

I tried adding a lambda function through the aws amplify cli but couldn't successfully push it to the cloud nor build it locally. I've tried looking at stackoverflow questions and github questions but I haven't found a solution that works for me. I tried doing 'npm i' in the src of my lambda function but that doesn't work either.

### Expected behavior

It should push the lambda function to the cloud

### Reproduction steps

![Screenshot from 2023-10-27 16-29-39](https://github.com/aws-amplify/amplify-js/assets/98417762/0eed409d-8686-4073-ad86-2fb1dcee078b)
![Screenshot from 2023-10-27 16-33-38](https://github.com/aws-amplify/amplify-js/assets/98417762/0d15e9a0-43c0-4d62-bbaa-16ff0e0d97e3)

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
Hey @Johankoekoepan :wave: thanks for raising this! As we begin to look at this in more depth I have a couple follow-up questions:

- what version of the Amplify CLI are you currently using?
- what version of yarn are you currently using? (we have another issue with yarn berry and building functions due to the lack of a `--production` flag in yarn berry - https://github.com/aws-amplify/amplify-cli/issues/13001)

additionally, if you'd like to switch from yarn to npm you can delete the `yarn.lock` file in the function's `src` directory, install with npm to generate the `package-lock.json`, and push. Once the CLI detects the package-lock it will default to npm.

**Comment by Johankoekoepan** [comment]
Hey man hope it's going well,

amplify --version shows 12.7.1
yarn --version shows 1.22.19

But I use npm, and after i run npm install in the /src directory of my function and try to run amplify push again, it throws this error:

✔ Are you sure you want to continue? (Y/n) · yes
🛑 Packaging lambda function failed with the error 
Command failed with exit code 243: npm install --no-bin-links --production

![Screenshot from 2023-10-28 14-01-28](https://github.com/aws-amplify/amplify-cli/assets/98417762/dfd10dcb-e8fd-4f01-aeed-3d67da073fd6)
![Screenshot from 2023-10-28 14-01-59](https://github.com/aws-amplify/amplify-cli/assets/98417762/2b09c8f5-27f9-4b6a-945e-e8d0b117bf0c)

**Comment by josefaidt** [comment]
Hey @Johankoekoepan thanks for clarifying! If you `cd` into this directory again and run the command printed in error `npm install --no-bin-links --production` does that also error? You should see a similar stack trace when running amplify commands with a `--debug` if so. Is there a postinstall step in your function's package.json that relies on a devDependency?

**Comment by Johankoekoepan** [comment]
Hi @josefaidt, In the end I need a function with other dependencies in it yes, but that didn't work and so now I'm ONLY creating the function in the cli and trying to push it without any code modified in the function like app.js or package.json and it still wont let me push it. Running `npm install --no-bin-links --production` in the src of my lambda function it gives the exact same error again when I try to amplify push (I tried pushing twice, once after using the `--production` and the second push after using `--omit=dev` when running `npm i` in the src of the function):

![Screenshot from 2023-10-31 10-17-54](https://github.com/aws-amplify/amplify-cli/assets/98417762/cdc159f0-4d33-4b71-9a8a-b9485018ac12)
![Screenshot from 2023-10-31 10-18-29](https://github.com/aws-amplify/amplify-cli/assets/98417762/ec0e733d-5a78-4f9f-acaa-672b87cb9968)

Running amplify push with `--debug` I got the same error but more details about it:

![Screenshot from 2023-10-31 10-32-35](https://github.com/aws-amplify/amplify-cli/assets/98417762/16c8c316-4dec-416a-8a16-dbc258b082bd)

✔ Are you sure you want to continue? (Y/n) · yes
🛑 Packaging lambda function failed with the error 
Command failed with exit code 243: npm install --no-bin-links --production

Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

PackagingLambdaFunctionError: Packaging lambda function failed with the error 
Command failed with exit code 243: npm install --no-bin-links --production
    at runPackageManager (/snapshot/amplify-cli/build/node_modules/amplify-nodejs-function-runtime-provider/lib/utils/legacyBuild.js:100:19)
    at runPackageManagerInstall (/snapshot/amplify-cli/build/node_modules/amplify-nodejs-function-runtime-provider/lib/utils/legacyBuild.js:75:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async installDependencies (/snapshot/amplify-cli/build/node_modules/amplify-nodejs-function-runtime-provider/lib/utils/legacyBuild.js:67:5)
    at async Object.buildResource [as build] (/snapshot/amplify-cli/build/node_modules/amplify-nodejs-function-runtime-provider/lib/utils/legacyBuild.js:44:13)
    at async buildFunction (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-category-function/lib/provider-utils/awscloudformation/utils/buildFunction.js:29:22)
    at async prepareResource (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/push-resources.js:420:33)
    at async prepareBuildableResources (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/push-resources.js:416:5)
    at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/push-resources.js:177:5)
    at async /snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/push-resources.js:137:16
    at async Promise.all (index 0)
    at async providersPush (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/push-resources.js:133:5)
    at async AmplifyToolkit.pushResources (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/push-resources.js:107:13)
    at async Object.executeAmplifyCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:194:9)
    at async executePluginModuleCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:139:5)
    at async executeCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:37:9)
    at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:121:5)

Command failed with exit code 243: npm install --no-bin-links --production
Error: Command failed with exit code 243: npm install --no-bin-links --production
    at makeError (/snapshot/amplify-cli/build/node_modules/execa/lib/error.js:60:11)
    at Function.sync (/snapshot/amplify-cli/build/node_modules/execa/index.js:194:17)
    at runPackageManager (/snapshot/amplify-cli/build/node_modules/amplify-nodejs-function-runtime-provider/lib/utils/legacyBuild.js:87:25)
    at runPackageManagerInstall (/snapshot/amplify-cli/build/node_modules/amplify-nodejs-function-runtime-provider/lib/utils/legacyBuild.js:75:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async installDependencies (/snapshot/amplify-cli/build/node_modules/amplify-nodejs-function-runtime-provider/lib/utils/legacyBuild.js:67:5)
    at async Object.buildResource [as build] (/snapshot/amplify-cli/build/node_modules/amplify-nodejs-function-runtime-provider/lib/utils/legacyBuild.js:44:13)
    at async buildFunction (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-category-function/lib/provider-utils/awscloudformation/utils/buildFunction.js:29:22)
    at async prepareResource (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/push-resources.js:420:33)
    at async prepareBuildableResources (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/push-resources.js:416:5)
    at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/push-resources.js:177:5)
    at async /snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/push-resources.js:137:16
    at async Promise.all (index 0)
    at async providersPush (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/push-resources.js:133:5)
    at async AmplifyToolkit.pushResources (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/push-resources.js:107:13)
    at async Object.executeAmplifyCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:194:9)
    at async executePluginModuleCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:139:5)
    at async executeCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:37:9)
    at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:121:5)

**Comment by josefaidt** [comment]
Hey @Johankoekoepan thanks for clarifying! The exit code being 243 is interesting. What version of Node.js are you using? Can you try deleting the associated node_modules directory and let the CLI attempt to install to a clean directory?

**Comment by Johankoekoepan** [comment]
Hey @josefaidt , I've done an npm install with the node modules and package.lock deleted it still has the exact same behaviour when trying to push.

My node version is v18.18.0.

**Comment by ykethan** [comment]
Following up on this issue, were you able to add the lambda function?

**Comment by josefaidt** [comment]
Closing due to inactivity
