### ISSUE TITLE
No CloudFormation template found at /codebuild/output/

### ISSUE THREAD

**Issue by leandrorp** [aws-amplify/amplify-cli#13380]
### How did you install the Amplify CLI?

npm

### Amplify CLI Version

12.7.1

### What operating system are you using?

Window

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

After adding a new lambda with REST API, it works locally, but the pipeline does not build

```
No CloudFormation template found at /codebuild/output/src3518215431/src/xxx-next/amplify/backend/function/stripewebhook/stripewebhook-cloudformation-template.json
2023-10-30T22:02:44.707Z [INFO]: Resolution: Ensure the file exists and is a valid CloudFormation template.
```

The stripewebhook-cloudformation-template.json exists

### Expected behavior

Pipeline Build successfully; I tried to amplify pull or push a lot of times.

### Reproduction steps

ADD new API rest in an existing project with graphql 
Add new lambda with cognito ( auth permissions)  

### Project Identifier

Project Identifier: 1cfb423cd45ea0cbbb19bb7d0629aa77

### Log output

<details>

```
#2023-10-30T22:02:44.706Z [WARNING]: ✖ There was an error initializing your environment.
2023-10-30T22:02:44.706Z [INFO]: 🛑 No CloudFormation template found at /codebuild/output/src3518215431/src/axxxnext/amplify/backend/function/stripewebhook/stripewebhook-cloudformation-template.json
2023-10-30T22:02:44.707Z [INFO]: Resolution: Ensure the file exists and is a valid CloudFormation template.
                                 File path should match the following pattern: '<projectRoot>/amplify/backend/<category>/<resourceName>/<resourceName>-cloudformation-template.json' where <resourceName> should match the value from <projectRoot>/amplify/team-provider-info.json.
                                 If the resource directory was manually removed, run 'amplify remove <category>' to remove the resource from the project.
                                 Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @leandrorp, thank you for reaching out. When running `amplify status` do you observe the stripewebhook function being displayed. Additionally, does the `team-provider-info.json` also show an reference to the function?
Do you also observe this behaviour when running a `amplify push` in your terminal?

**Comment by leandrorp** [comment]
Hello @ykethan! Thanks for the response.
 Yes, the `stripewebhook `is displayed when running `amplify status`
 About  `team-provider-info.json`
![team](https://github.com/aws-amplify/amplify-cli/assets/5436170/9764c29d-84c6-460b-91d3-902fe1416691)

 When I run `amplify push` locally, it runs successfully. Only in the backend build display this error
 
```
 Deployment state saved successfully.

GraphQL transformer version: 2
```

**Comment by ykethan** [comment]
@leandrorp interesting. are you running an custom build scripts? Could you provide the `amplify.yml` script present in the AWS Amplify console under `Build settings` on the left panel.

Additionally, could you add the environment variable `AMPLIFY_ENABLE_DEBUG_OUTPUT` in the  AWS Amplify console under `Environment variables` on the left panel and set this to true. Could you then re-run the build and provide us the output/stack trace printed.

**Comment by leandrorp** [comment]
Sure, buddy!

Here they are: 

![buildSettings](https://github.com/aws-amplify/amplify-cli/assets/5436170/ba168c2a-3868-437a-ab2c-351454a11719)

Log With debug mode on :

`2023-10-31T18:30:09.490Z [INFO]: 🛑 No CloudFormation template found at /codebuild/output/src3838413546/src/acervo-front-next/amplify/backend/function/stripewebhook/stripewebhook-cloudformation-template.json
2023-10-31T18:30:09.490Z [INFO]: Resolution: Ensure the file exists and is a valid CloudFormation template.
                                 File path should match the following pattern: '<projectRoot>/amplify/backend/<category>/<resourceName>/<resourceName>-cloudformation-template.json' where <resourceName> should match the value from <projectRoot>/amplify/team-provider-info.json.
                                 If the resource directory was manually removed, run 'amplify remove <category>' to remove the resource from the project.
                                 Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/
                                 CloudFormationTemplateFault: No CloudFormation template found at /codebuild/output/src3838413546/src/acervo-front-next/amplify/backend/function/stripewebhook/stripewebhook-cloudformation-template.json
                                 at readCFNTemplate (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-cli-core/lib/cfnUtilities.js:39:15)
                                 at ensureLambdaExecutionRoleOutputs (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-category-function/lib/provider-utils/awscloudformation/utils/ensure-lambda-arn-outputs.js:42:72)
                                 at prePushHandler (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-category-function/lib/events/prePushHandler.js:22:76)
                                 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                                 at async Object.handleAmplifyEvent (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-category-function/lib/index.js:284:13)
                                 at async eventHandler (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:304:17)
                                 at async raiseEvent (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:309:13)
                                 at async raisePrePushEvent (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:220:5)
                                 at async initializeEnv (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/initialize-env.js:135:13)
                                 at async onSuccess (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/init-steps/s9-onSuccess.js:98:5)
                                 at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/commands/init.js:29:9)
                                 at async Object.executeAmplifyCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:194:9)
                                 at async executePluginModuleCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:139:5)
                                 at async executeCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:37:9)
                                 at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:121:5)`

**Comment by ykethan** [comment]
Hey @leandrorp, thank you for the information. On diving into logs noticed the remove function command was run and the `backend-config.json` does not have a reference to the function.
Could try removing the reference in `team-provider-info.json` and push as follows

1. run `amplify pull`
2. remove the `stripewebhook` in the function block of `team-provider-info.json` 
3. remove the `stripewebhook` function folder.
4. run `amplify push`
5. commit to git and let Amplify hosting build the commit.

**Comment by leandrorp** [comment]
> 5\. to git and let Amplify hosting build the commit.

Hey @ykethan, after doing all the steps and running `amplify push,` I received the same error in my terminal :

`🛑 No CloudFormation template found at D:\workspace\seuacervo\seuacervo-frontend-next\amplify\backend\function\stripewebhook\stripewebhook-cloudformation-template.json`

**Comment by ykethan** [comment]
@leandrorp interesting, on the AWS S3 console, could you open the S3 bucket `amplify-<appName>-<envName>-<randomHash>-deployment`, download the `#current-cloud-backend.zip` and extract it. 
In the `#current-cloud-backend`, under the function folder `stripewebhook` do you observe a  `stripewebhook -cloudformation-template.json` file?

**Comment by leandrorp** [comment]
> @leandrorp interesting. on the AWS S3 console, could you open the S3 bucket `amplify-<appName>-<envName>-<randomHash>-deployment`, download the `#current-cloud-backend.zip` and extract it. In the `#current-cloud-backend`, under the function folder `stripewebhook`, do you observe a `stripewebhook -cloudformation-template.json` file?

Yes, 
![file](https://github.com/aws-amplify/amplify-cli/assets/5436170/bb26f149-9d3c-4b79-8177-792979fa4763)
What do you think about removing the lambda ( it will ask for removing the rest API also)
And create all the stuff again?

Or we can try other solutions?
Thanks

**Comment by ykethan** [comment]
@leandrorp would you be open for a quick call? I am available on discord at handle `ykethan`.

**Comment by ykethan** [comment]
Hey @leandrorp, thank you for taking the time in hopping on a call, it was great chatting with you. 
We were able to mitigate the issue by removing the REST API and Lambda function. Please do let us know if you run into the issue again.

Closing the issue.

**Comment by leandrorp** [comment]
> Hey @leandrorp, thank you for taking the time in hopping on a call, it was great chatting with you. We were able to mitigate the issue by removing the REST API and Lambda function. Please do let us know if you run into the issue again.
> 
> Closing the issue.

It was great for me too! Thanks for the support
