### ISSUE TITLE
Unable to init amplify app

### ISSUE THREAD

**Issue by eddeyonline** [aws-amplify/amplify-cli#13384]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.13.0

### Amplify CLI Version

12.7.1

### What operating system are you using?

Windows 10

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

"amplify init" in project root directory gives persistent error "ProjectInitFault: We are unable to process your request. Please reach out to your support representative."

### Expected behavior

The application to be initialised and able to proceed with tutorial. 

### Reproduction steps

Followed instructions in tutuorial found at following URL:
https://docs.amplify.aws/start/getting-started/setup/q/integration/react/
After ensuring all the prerequisites on the previous tutorial page were met. 

### Log output

<details>

```
# Put your logs below this line
E:\AWS\react-amplify>amplify init --debug
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the project reactamplify
The following configuration will be applied:

Project information
| Name: reactamplify
| Environment: dev
| Default editor: Visual Studio Code
| App type: javascript
| Javascript framework: react
| Source Directory Path: src
| Distribution Directory Path: build
| Build Command: npm.cmd run-script build
| Start Command: npm.cmd run-script start

? Initialize the project with the above configuration? No
? Enter a name for the environment dev
? Choose your default editor: Sublime Text
√ Choose the type of app that you're building · javascript
Please tell us about your project
? What javascript framework are you using react
? Source Directory Path:  src
? Distribution Directory Path: build
? Build Command:  npm.cmd run-script build
? Start Command: npm.cmd run-script start
Using default provider  awscloudformation
? Select the authentication method you want to use: AWS profile

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

? Please choose the profile you want to use default
🛑 We are unable to process your request. Please reach out to your support representative.

Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

ProjectInitFault: We are unable to process your request. Please reach out to your support representative.
    at init (C:\snapshot\amplify-cli\build\node_modules\@aws-amplify\amplify-provider-awscloudformation\lib\amplify-service-manager.js:163:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.run (C:\snapshot\amplify-cli\build\node_modules\@aws-amplify\amplify-provider-awscloudformation\lib\initializer.js:96:9)

We are unable to process your request. Please reach out to your support representative.
UnauthorizedException: We are unable to process your request. Please reach out to your support representative.
    at Object.extractError (C:\snapshot\amplify-cli\build\node_modules\aws-sdk\lib\protocol\json.js:80:27)
    at Request.extractError (C:\snapshot\amplify-cli\build\node_modules\aws-sdk\lib\protocol\rest_json.js:61:8)
    at Request.callListeners (C:\snapshot\amplify-cli\build\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
    at Request.emit (C:\snapshot\amplify-cli\build\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (C:\snapshot\amplify-cli\build\node_modules\aws-sdk\lib\request.js:686:14)
    at Request.transition (C:\snapshot\amplify-cli\build\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\snapshot\amplify-cli\build\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\snapshot\amplify-cli\build\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\snapshot\amplify-cli\build\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\snapshot\amplify-cli\build\node_modules\aws-sdk\lib\request.js:688:12)
    at Request.callListeners (C:\snapshot\amplify-cli\build\node_modules\aws-sdk\lib\sequential_executor.js:116:18)
    at Request.emit (C:\snapshot\amplify-cli\build\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (C:\snapshot\amplify-cli\build\node_modules\aws-sdk\lib\request.js:686:14)
    at Request.transition (C:\snapshot\amplify-cli\build\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\snapshot\amplify-cli\build\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\snapshot\amplify-cli\build\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\snapshot\amplify-cli\build\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\snapshot\amplify-cli\build\node_modules\aws-sdk\lib\request.js:688:12)
    at Request.callListeners (C:\snapshot\amplify-cli\build\node_modules\aws-sdk\lib\sequential_executor.js:116:18)
    at callNextListener (C:\snapshot\amplify-cli\build\node_modules\aws-sdk\lib\sequential_executor.js:96:12)
    at IncomingMessage.onEnd (C:\snapshot\amplify-cli\build\node_modules\aws-sdk\lib\event_listeners.js:417:13)
    at IncomingMessage.emit (node:events:525:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Session Identifier: 095ed2b4-4ea8-440c-a8b6-5c1edbe3eeeb

```

</details>

### Additional information

I have tried with AWS CLI version 1 and version 2 in case of breaking change. 
I have installed additional profiles to ensure this is not the issue. 
I have tried different names for development environment. 
I have tried with and without "npm start" already run. 
I have tried adding an app in the console and after clicking on "save and deploy" I get the following message:
"Houston, there's a problem
We are unable to process your request. Please reach out to your support representative."
Thanks for any help or guidance you can give!

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @eddeyonline, thank you for reaching out. From the error messages provided it appears the issue is occurring on a account level. 
Is this a new account?
We can utilize the following options to mitigate the issue
option 1:

If you have a premium support plan, open a case under the `technical` option and selecting the service as `Amplify`
Describe the issue you are experiencing. Do provide a link to the GitHub issue in the request.

option 2:

If you do not have a premium support plan, select the `Account and billing` option with the following options.
![image](https://github.com/aws-amplify/amplify-cli/assets/87995712/07259061-3b6c-49bc-a734-318f05fddfd9)
Add a subject line "Check Account Status - Amplify Console" and describe the issue you are experiencing. Do provide a link to the GitHub issue in the request.

**Comment by josefaidt** [comment]
Closing due to inactivity
