### ISSUE TITLE
Amplify status: providers is not iterable

### ISSUE THREAD

**Issue by harrynguyen2510** [aws-amplify/amplify-cli#13400]
### Description

Suddenly I have this issue below when running command locally Amplify status
I did upgrade latest version of Amplify 

Current Environment: prod
    
│ Category  │ Resource name │ Operation │ Provider plugin   │
│ Analytics │ *************** │ No Change │ awscloudformation │
│ Api       │ *************  │ No Change │ awscloudformation │
│ Auth      │ *************       │ No Change │ awscloudformation │
│ Storage   │*************    │ No Change │ awscloudformation │
 
🛑 providers is not iterable

Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

Session Identifier: f3ef178a-b41d-4494-8a9d-e440029aa27b
⠋ Creating Zip
The "path" argument must be of type string. Received undefined
✖ Creating Zip

### Categories

- [X] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Notifications (Push)
- [X] Storage

### Steps to Reproduce

Running command: "Amplify status"

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.13.9

### Amplify Flutter Version

1.6.

### Deployment Method

Amplify CLI

**Comment by ykethan** [comment]
Hey @harrynguyen2510, in the `amplify/.config` folder could you open the `project-config` file, as this should contain the providers for the project. could you provide us the contents of the file. note: the `.config` folder may be hidden in vscode, at the top the project could you open the `.vscode/settings.json` and set `amplify/.config` as false.
Could you try running `amplify configure project`, select `Project information` and go through the cli flow and then try running the command?
Additionally, could you try running `amplify status --debug` and provide us the output?

**Comment by harrynguyen2510** [comment]
After setting it false like this 
`{
  "files.exclude": {
    "amplify/.config": false,
    "amplify/**/*-parameters.json": true,
    "amplify/**/amplify.state": true,
    "amplify/**/transform.conf.json": true,
    "amplify/#current-cloud-backend": true,
    "amplify/backend/amplify-meta.json": true,
    "amplify/backend/awscloudformation": true
  }
}`

And running command: `amplify configure project`
This is output:
`Project information
| Name: undefined
| Environment: prod
| Default editor: vscode
| App type: javascript
| Javascript framework: none
| Source Directory Path: src
| Distribution Directory Path: dist
| Build Command: npm run-script build
| Start Command: npm run-script start

Advanced: Container-based deployments
| Leverage container-based deployments: No

? Which setting do you want to configure? Project information
? Enter a name for the project Projectname
? Choose your default editor: Visual Studio Code
✔ Choose the type of app that you're building · flutter
Please tell us about your project
? Where do you want to store your configuration file? ./lib/
Using default provider  awscloudformation
Error occurred during configuration.
TypeError: Cannot read properties of undefined (reading 'includes')
    at configProviders (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/config-steps/c2-configProviders.js:44:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/commands/configure.js:81:13)
    at async Object.executeAmplifyCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:194:9)
    at async executePluginModuleCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:139:5)
    at async executeCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:37:9)
    at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:121:5)`

Running `amplify status --debug`
`Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

UnknownFault: providers is not iterable
    at genericErrorToAmplifyException (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/amplify-exception-handler.js:126:49)
    at handleException (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/amplify-exception-handler.js:27:28)
    at process.<anonymous> (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:52:93)
    at process.emit (node:events:513:28)
    at process._fatalException (node:internal/process/execution:149:25)

providers is not iterable
TypeError: providers is not iterable
    at AmplifyToolkit.showHelpfulProviderLinks (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/show-helpful-provider-links.js:36:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/commands/status.js:55:9)
    at async Object.executeAmplifyCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:194:9)
    at async executePluginModuleCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:139:5)
    at async executeCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:37:9)
    at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:121:5)

Session Identifier: f19a0421-dc25-46d1-b4ab-1558a48df56b
⠋ Creating Zip
The "path" argument must be of type string. Received undefined
✖ Creating Zip`


in `.config` folder, I have three file
* **local-aws-info.json** 
`{
  "prod": {
    "configLevel": "amplifyAdmin"
  },
  "dev": {
    "configLevel": "amplifyAdmin"
  }
}`

**local-env-info.json**
`{
  "prod": {
    "configLevel": "amplifyAdmin"
  },
  "dev": {
    "configLevel": "amplifyAdmin"
  }
}`
**project-config.json**
`{
  "frontend": "javascript",
  "javascript": {
    "framework": "none",
    "config": {
      "SourceDir": "amplify-codegen-temp"
    }
  }
}`

**Comment by ykethan** [comment]
Hey @harrynguyen2510, thank you for the information. The `project-config.json` seems to missing the providers.

could you modify the file to have a similar structure as follows, modified the from javascript to flutter as it does appears you are trying to use this in a flutter app.
```
{
  "providers": [
    "awscloudformation"
  ],
  "projectName": "<Projectname>",
  "version": "3.1",
  "frontend": "flutter",
  "flutter": {
    "config": {
      "ResDir": "./lib/"
    }
  }
}
```
then try running `amplify status`

**Comment by harrynguyen2510** [comment]
@ykethan it works, so I just **remove** old json?

 `{
  "frontend": "javascript",
  "javascript": {
    "framework": "none",
    "config": {
      "SourceDir": "amplify-codegen-temp"
    }
  }
}`

**Comment by ykethan** [comment]
Hey @harrynguyen2510, glad to hear you were able to mitigate the issue. you should be able to remove the old file.

**Comment by josefaidt** [comment]
Closing due to inactivity
