### ISSUE TITLE
Unable to build backend when using Amazon Linux:2023 and default Amplify CLI

### ISSUE THREAD

**Issue by kachkaev** [aws-amplify/amplify-cli#13423]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d3bq67l0547585

### AWS Region

eu-west-2

### Amplify Hosting feature

Build settings

### Frontend framework

Next.js

### Next.js version

13.5.6

### Next.js router

Pages Router

### Describe the bug

I am trying to upgrade to Next.js 14. The original issue (https://github.com/aws-amplify/amplify-hosting/issues/3773) got resolved by a new image _Amazon Linux 2023_. I tried this image and saw `v18.18.2` when running `node --version`. That’s good.

<img src="https://github.com/aws-amplify/amplify-hosting/assets/608862/ad58b9d3-c186-46fe-af5b-74c1d7603645" width=400 >

However, the build failed:

![Screenshot 2023-11-18 at 13 50 55](https://github.com/aws-amplify/amplify-hosting/assets/608862/72297a48-60de-48c2-b8e0-b64ed641e7ac)

Last few lines of the logs:

```
2023-11-18T01:52:59.157Z [INFO]: # Completed phase: preBuild
                                 # Starting phase: build
2023-11-18T01:52:59.157Z [INFO]: # Executing command: export PATH="$PWD/amplify/bin:$PATH"
                                 # Executing command: export COREPACK_ENABLE_STRICT=0
                                 ## Running amplify pull to generate aws-exports.js file for frontend
2023-11-18T01:53:02.761Z [INFO]: [0mAmplify AppID found: d3bq67l0547585. Amplify App name is: myapp[0m
2023-11-18T01:53:02.815Z [INFO]: [0mBackend environment dev found in Amplify Console app: myapp[0m
2023-11-18T01:53:06.970Z [INFO]: 🛑 Failed to pull the backend.
2023-11-18T01:53:06.973Z [INFO]: Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/
2023-11-18T01:53:06.988Z [INFO]: 
2023-11-18T01:53:06.988Z [INFO]: Session Identifier: 4f025418-c3cc-4045-bd4a-a1a240e35809
2023-11-18T01:53:07.009Z [ERROR]: !!! Build failed
2023-11-18T01:53:07.009Z [INFO]: Please check the supported SSR features to find if your build failure is related to an unsupported feature: https://docs.aws.amazon.com/amplify/latest/userguide/ssr-Amplify-support.html#supported-unsupported-features. You may also find this troubleshooting guide useful: https://docs.aws.amazon.com/amplify/latest/userguide/troubleshooting-ssr-deployment.html
2023-11-18T01:53:07.009Z [ERROR]: !!! Non-Zero Exit Code detected
2023-11-18T01:53:07.009Z [INFO]: # Starting environment caching...
2023-11-18T01:53:07.009Z [INFO]: # Uploading environment cache artifact...
2023-11-18T01:53:07.095Z [INFO]: # Uploaded environment cache artifact
2023-11-18T01:53:07.095Z [INFO]: # Environment caching completed
Terminating logging...
```

### Expected behavior

Backend builds without errors.

### Reproduction steps

1. Switch to `Amazon Linux:2023`
2. Don't configure Amplify CLI version or set it to [latest](https://github.com/aws-amplify/amplify-cli/releases) (12.8.2 at the time of writing)
3. Run the build
4. Observe backend build failing

### Additional information

I managed to find a workaround:
<img src="https://github.com/aws-amplify/amplify-hosting/assets/608862/546b1fdb-8ba3-4e24-b2b1-7cb2009c92d2" width=400 >

Setting Amplify CLI version to anything higher than 12.5.2 causes the failure.

Backend build logs when Amplify CLI version is set to 12.5.2:

```
2023-11-18T11:22:16.609Z [INFO]: # Completed phase: preBuild
                                 # Starting phase: build
2023-11-18T11:22:16.610Z [INFO]: # Executing command: export PATH="$PWD/amplify/bin:$PATH"
                                 # Executing command: export COREPACK_ENABLE_STRICT=0
                                 ## Running amplify pull to generate aws-exports.js file for frontend
2023-11-18T11:22:18.728Z [INFO]: [0mAmplify AppID found: d3bq67l0547585. Amplify App name is: myapp[0m
2023-11-18T11:22:18.776Z [INFO]: [0mBackend environment dev found in Amplify Console app: myapp[0m
2023-11-18T11:22:24.874Z [WARNING]: - Fetching updates to backend environment: dev from the cloud.
2023-11-18T11:22:29.289Z [WARNING]: - Building resource api/NeptuneApi
2023-11-18T11:22:30.376Z [INFO]: [32mGraphQL schema compiled successfully.[39m
                                 [32mEdit your schema at /codebuild/output/src3127556268/src/myapp/amplify/backend/api/NeptuneApi/schema.graphql or place .graphql files in a directory at /codebuild/output/src3127556268/src/myapp/amplify/backend/api/NeptuneApi/schema[39m
2023-11-18T11:22:30.378Z [WARNING]: - Building resource auth/myapp356a8770
2023-11-18T11:22:30.496Z [WARNING]: ✔ Successfully pulled backend environment dev from the cloud.
2023-11-18T11:22:30.767Z [INFO]: ✅
2023-11-18T11:22:32.878Z [INFO]: # Completed phase: build
```

Frontend build is successful too.

**Comment by kachkaev** [comment]
A bit more info: our project uses pnpm instead of npm/yarn. We call `corepack enable; pnpm config set node-linker hoisted; pnpm install` in the `breBuild` step of `amplify.yaml`. If there were any changes to package management between Amplify CLI 12.5.2 and 12.6.0, that could explain it. 

As you can see in my original post, our failing build logs are not very helpful. All we see is `🛑 Failed to pull the backend` but there are no other warnings or errors to inspect. It is possible that pnpm is not relevant here, I’m sharing this detail just in case.

**Comment by ykethan** [comment]
Hey @kachkaev, could you try adding `AMPLIFY_ENABLE_DEBUG_OUTPUT` to `true` as a environment variable in the AWS Amplify console this should verbose logging and then run the build. 
Could you provide us the output and any identifiers printed here?

**Comment by kachkaev** [comment]
Just tried `AMPLIFY_ENABLE_DEBUG_OUTPUT=true amplify pull --envName dev` locally (Amplify CLI 12.8.2). Here is the output:

<details><summary>Details</summary>
<pre>

🛑 Failed to pull the backend.

Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

PullBackendFault: Failed to pull the backend.
    at attachBackend (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/attach-backend.js:55:15)
    at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/commands/pull.js:64:9)
    at async Object.executeAmplifyCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:194:9)
    at async executePluginModuleCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:139:5)
    at async executeCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:37:9)
    at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:121:5)

EEXIST: file already exists, symlink '../uuid/dist/bin/uuid' -> '/path/to/project/amplify/backend/function/arahitoolspocAWSSDK/lib/nodejs/node_modules/.bin/uuid'
Error: EEXIST: file already exists, symlink '../uuid/dist/bin/uuid' -> '/path/to/project/amplify/backend/function/arahitoolspocAWSSDK/lib/nodejs/node_modules/.bin/uuid'
    at Object.symlinkSync (node:fs:1741:3)
    at onLink (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:139:70)
    at getStats (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:49:45)
    at startCopy (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
    at copyDirItem (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:120:10)
    at /snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:39
    at Array.forEach (<anonymous>)
    at copyDir (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:23)
    at onDir (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:103:10)
    at getStats (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:45:37)
    at startCopy (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
    at copyDirItem (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:120:10)
    at /snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:39
    at Array.forEach (<anonymous>)
    at copyDir (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:23)
    at onDir (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:103:10)
    at getStats (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:45:37)
    at startCopy (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
    at copyDirItem (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:120:10)
    at /snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:39
    at Array.forEach (<anonymous>)
    at copyDir (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:23)
    at onDir (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:103:10)
    at getStats (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:45:37)
    at startCopy (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
    at copyDirItem (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:120:10)
    at /snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:39
    at Array.forEach (<anonymous>)
    at copyDir (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:23)
    at onDir (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:103:10)
    at getStats (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:45:37)
    at startCopy (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
    at copyDirItem (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:120:10)
    at /snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:39
    at Array.forEach (<anonymous>)
    at copyDir (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:23)
    at onDir (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:103:10)
    at getStats (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:45:37)
    at startCopy (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
    at copyDirItem (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:120:10)
    at /snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:39
    at Array.forEach (<anonymous>)
    at copyDir (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:23)
    at onDir (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:103:10)
    at getStats (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:45:37)
    at startCopy (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
    at copyDirItem (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:120:10)
    at /snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:39
    at Array.forEach (<anonymous>)
    at copyDir (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:23)
    at onDir (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:103:10)
    at getStats (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:45:37)
    at startCopy (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
    at handleFilterAndCopy (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:33:10)
    at Object.copySync (/snapshot/amplify-cli/build/node_modules/fs-extra/lib/copy-sync/copy-sync.js:26:10)
    at downloadBackend (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/attach-backend.js:347:24)
    at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/attach-backend.js:117:3)
    at async Object.attachBackend (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/index.js:196:3)
    at async queryProvider (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/attach-backend-steps/a10-queryProvider.js:36:5)
    at async attachBackend (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/attach-backend.js:43:9)
    at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/commands/pull.js:64:9)
    at async Object.executeAmplifyCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:194:9)
    at async executePluginModuleCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:139:5)
    at async executeCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:37:9)
    at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:121:5)

Session Identifier: 927e3a42-23ea-4332-87f0-fbbf7fc4b3ef

</pre>
</details>

**Comment by ykethan** [comment]
Hey @kachkaev, thank you for the information. 
The error message: `EEXIST: file already exists, symlink '../uuid/dist/bin/uuid' -> '/path/to/project/amplify/backend/function/arahitoolspocAWSSDK/lib/nodejs/node_modules/.bin/uuid'` indicates the build failed due to a symlink link error in `arahitoolspocAWSSDK` resource. 

The issue appears to be similar to https://github.com/aws-amplify/amplify-cli/issues/2948.
To mitigate the issue the workaround would be to remove the `node_modules` and `.temp ` then running push/re-build the application, the detailed steps are documented [here](https://gist.github.com/josefaidt/a117076b7bea81e1872e275176dbb23c).

**Comment by kachkaev** [comment]
I’m afraid I won’t be able to try this hack with removing `node_modules` in early January only. In the meantime, if anyone has the same issue or has successfully applied a workaround, please share your experience.

**Comment by ykethan** [comment]
@kachkaev I understand, i am not aware on other workarounds at this moment. But the `amplify push` should recreate the node modules in the `current-cloud-backed.zip`. Do reach out if you experience any issues or get a chance to test the workaround.

**Comment by josefaidt** [comment]
Closing due to inactivity
