### ISSUE TITLE
An error occurred when creating the CloudFormation stack 🛑 

### ISSUE THREAD

**Issue by NoellaMarie501** [aws-amplify/amplify-cli#13469]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v21.4.0

### Amplify CLI Version

12.8.2

### What operating system are you using?

Ubuntu

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

"No manual changes made"

### Describe the bug

1. First I tried initializing a project with amplify 3 times but got this error: "
An error occurred when creating the CloudFormation stack
🛑 The following resources failed to deploy:
🛑 Initialization of project failed
"
2. I tried again and now had this error: "🛑 You have reached the Amplify App limit for this account and region" whereas on my amplify console there are no apps.
3. I changed the region in the configurations and went back to the error: "An error occurred when creating the CloudFormation stack
🛑 The following resources failed to deploy:
🛑 Initialization of project failed"
4. I have searched about the problem it all I find is that it is related to having a new account, but I do not find a solution

### Expected behavior

-To be able to initialize an amplify project and push afterwards.

### Reproduction steps

- Have an existing React js project
- Run `amplify init` 

### Log output

<details>

```
# Put your logs below this line


An error occurred when creating the CloudFormation stack
🛑 The following resources failed to deploy:
🛑 Initialization of project failed

Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

Resource is not in the state stackCreateComplete
AccessDenied: Resource is not in the state stackCreateComplete
    at Request.extractError (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /snapshot/amplify-cli/build/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /snapshot/amplify-cli/build/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at callNextListener (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at IncomingMessage.onEnd (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/event_listeners.js:417:13)
    at IncomingMessage.emit (node:events:525:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @NoellaMarie501, thank you for reaching out. Could you try running `amplify init --debug`?
Additionally, in the AWS CloudFormation console could you check the stacks of the application for any failure messages.

**Comment by NoellaMarie501** [comment]
Hello @ykethan as for the stacks of the application i do not have any yet as i am still trying to initiate the project and create stacks. here is the output i get from using the debug. "
An error occurred when creating the CloudFormation stack
🛑 The following resources failed to deploy:
🛑 Initialization of project failed

Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

Resource is not in the state stackCreateComplete
AccessDenied: Resource is not in the state stackCreateComplete
    at Request.extractError (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /snapshot/amplify-cli/build/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /snapshot/amplify-cli/build/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at callNextListener (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at IncomingMessage.onEnd (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/event_listeners.js:417:13)
    at IncomingMessage.emit (node:events:525:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"

**Comment by ykethan** [comment]
Hey @NoellaMarie501, are you running init on a project that contains a Amplify folder?
from the error message `Resource is not in the state stackCreateComplete` it does look like the CloudFormation deployment  did start to create the application and a stack creation was initiated. Do check the deleted section as well as the stack may have been deleted.
The issue appears to be similar to https://github.com/aws-amplify/amplify-cli/issues/353. Checking the stack would help us in understanding if the issue is due to limits on the underlying resources created or if any resource failed to create.

**Comment by NoellaMarie501** [comment]
Hello @ykethan No the project does not contain an Amplify folder. It is a React project that I am trying to use amplify for hosting and lamda as the backend but get this error when trying to initialize the project with amplify init command

**Comment by NoellaMarie501** [comment]
@ykethan I honestly have no idea what the issue is. And i will love to know why i receive the "🛑 You have reached the Amplify App limit for this account and region" error when i try the init command again to the point i get to change the region.  whereas i have no application that was actually created

**Comment by ykethan** [comment]
Hey @NoellaMarie501, thank you for the information. The error message appears to be similar to https://github.com/aws-amplify/amplify-hosting/issues/2797.

But from the information provided I believe the issue may be occurring on a account level, 
As a quick confirmation to check if this is occurring on a account level, could you try creating a backend application on AWS Amplify console using the `build an app`. 
![image](https://github.com/aws-amplify/amplify-cli/assets/87995712/dfb20622-57d3-456f-9a7b-c460c27e81ad)

Additionally, is this a new account?

**Comment by NoellaMarie501** [comment]
yes @ykethan 
it is a new account

**Comment by ykethan** [comment]
@NoellaMarie501 when creating the new app on the Amplify console, if you run experience a error message similar to `We are unable to process your request. Please reach out to your support representative`, we can confirm that the issue is occurring on a account level.

to mitigate the issue, we will need to reach out to the AWS support team 
If you have a premium support plan, open a support case under the `Amplify Console Support` with a brief explanation with the error message and being unable to create resources. Do link the Github issue to the support case.

If you do not have a support plan and see a Basic Support Plan in the AWS support console,
create a new support case under `Account and Billing` using the following headings:

Service: Account
Category: Other Account Issues
General Question
add a subject line say `Check Account Status - Amplify Console` and describe the issue you are experiencing such as the error message and unable to create a app. Do link the GitHub issue to the support ticket to help track the issue.
