### ISSUE TITLE
object Object at handleError graphql using amplify

### ISSUE THREAD

**Issue by Arya-Bastani23** [aws-amplify/amplify-cli#13533]
### Amplify CLI Version

12.10.1

### Question

I created a graphQL API for my amplify project following [this Amplify documentation](https://docs.amplify.aws/javascript/build-a-backend/graphqlapi/connect-to-api/). 

I've followed all the steps layed out here but whenever I try to call the `createItem` function I show below I get the following error:

```
ERROR
[object Object]
    at handleError (http://localhost:3000/static/js/bundle.js:69505:58)
    at http://localhost:3000/static/js/bundle.js:69528:7

```

At first I thought it's because I'm passing in the wrong object type and it should be of type `CreateApplicationInput!`,  so I created a class with that name and created a new instance of it named `new_input`, but that didn't work. I'm not sure if amplify already created a class of that type I need to import into this file (I couldn't find anything like that).

**Any input for why this error is popping up or how to debug would be really appreciated**

I have the following function that's called when a button is clicked to use graphQL to create a new item in my backend DB: 
```
const client = generateClient();

class CreateApplicationInput {
  constructor(name, description) {
    this.name = name;
    this.description = description;
  }
}

async function createItem() {
  const old_input = {name: "test", description: "first one"}

  const new_input = new CreateApplicationInput('test', 'idk')

  console.log(test)

  await client.graphql({
    query: createApplication,
    variables: {
      input: new_input
    }
  });
```

The `createApplication` function that's used is here and was automatically generated by amplify:
```
export const createApplication = /* GraphQL */ `
  mutation CreateApplication(
    $input: CreateApplicationInput!
    $condition: ModelApplicationConditionInput
  ) {
    createApplication(input: $input, condition: $condition) {
      id
      name
      description
      createdAt
      updatedAt
      __typename
    }
  }
`;
```

And this is what my graphQL schema looks like:
```
type Application @model @auth(rules: [{allow: public}]) {
  id: ID!
  name: String!
  description: String
}
```

**Comment by ykethan** [comment]
Hey @Arya-Bastani23,👋 thanks for raising this! I'm going to transfer this over to our JS repository for better assistance 🙂.

Tried to quickly reproduce the issue using the data model, but did not run into the same error. Wanted to confirm a detail, does the application currently have the following?
```
import { Amplify } from 'aws-amplify';
import config from './amplifyconfiguration.json';
Amplify.configure(config);
```

Note, reproduction steps utilized:

1. amplify init
2. amplify add api, added the model and push
3. 
```
import { generateClient } from "aws-amplify/api";
import { createApplication } from "@/src/graphql/mutations";

const client = generateClient();

export default function Home() {
  const createApp = async () => {
    const app = await client.graphql({
      query: createApplication,
      variables: {
        input: {
          name: "test",
          description: "test",
        },
      },
    });
    console.log(app);
  };
  return (
    <>
      <button onClick={createApp}>test</button>
    </>
  );
}
```
