### ISSUE TITLE
InvalidParameterException: The provider SignInWithApple does not exist for User Pool...

### ISSUE THREAD

**Issue by jonathanburris** [aws-amplify/amplify-cli#13549]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-adminui/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-adminui/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1uhgb0aro2pe4

### Region

es-east-1

### Environment name

staging

### Amplify CLI Version

7.6.13

### If applicable, what version of Node.js are you using?

v14.17.3

### What operating system are you using?

Mac and Windows

### Browser type?

Chrome

### Describe the bug

While trying to add SignInWithApple, I get the error below. It actually created the sign in provider in Cognito, but it doesn't show in Amplify. The deploy failed and rolled-back.

2022-01-29T19:40:56.161Z	2c012f4a-1614-4509-ba87-18616eaac71c	INFO	InvalidParameterException: The provider SignInWithApple does not exist for User Pool us-east-1_vJLmlGxlZ.
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)

### Expected behavior

I should be able to add this additional sign-in provider and deploy successfully.

### Reproduction steps

Using Amplify Studio:

Add Apple Sign-in Provider

Add:
ServicesID
TeamID
KeyID
Upload private key cert

Deploy

**Comment by ykethan** [comment]
Closing this as duplicate https://github.com/aws-amplify/amplify-cli/issues/11526, do subscribe to the issue linked for further updates.
