### ISSUE TITLE
"Unexpected token  in JSON at position 0" during amplify init

### ISSUE THREAD

**Issue by palpatim** [aws-amplify/amplify-cli#1355]
**Describe the bug**
During the execution of `amplify init` the console returns an error message: 

```
% amplify init
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the project <MY PROJECT NAME>
? Enter a name for the environment dev
? Choose your default editor: None
? Choose the type of app that you're building ios
Using default provider  awscloudformation

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html

? Do you want to use an AWS profile? Yes
? Please choose the profile you want to use <MY PROFILE NAME>
⠸ Initializing project in the cloud...
...
✔ Successfully created initial AWS cloud resources for deployments.
✔ Initialized provider successfully.
✖ There was an error initializing your environment.
init failed
SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at getCurrentAWSConfig (/Users/schmelte/.nvm/versions/node/v8.15.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-ios/lib/frontend-config-creator.js:77:22)
    at createAWSConfig (/Users/schmelte/.nvm/versions/node/v8.15.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-ios/lib/frontend-config-creator.js:22:28)
    at Object.createFrontendConfigs (/Users/schmelte/.nvm/versions/node/v8.15.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-ios/index.js:23:10)
    at Object.onCategoryOutputsChange (/Users/schmelte/.nvm/versions/node/v8.15.0/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/on-category-outputs-change.js:22:33)
    at initializeEnv (/Users/schmelte/.nvm/versions/node/v8.15.0/lib/node_modules/@aws-amplify/cli/src/lib/initialize-env.js:79:27)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

**To Reproduce**
1. Clone [iOS EventsApp starter](https://github.com/aws-samples/aws-mobile-appsync-events-starter-ios)
1. In project directory, issue `amplify init`

**Expected behavior**
Project initializes successfully

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.4
 - Browser: N/A
 - Amplify Version: 1.6.5

**Contents of awsconfiguration.json:**

```json
{
    "UserAgent": "aws-amplify-cli/0.1.0",
    "Version": "1.0",
    "IdentityManager": {
        "Default": {}
    },
    "AppSync": {
        "Default": {
        "ApiUrl": "https://<MY API URL>.appsync-api.us-east-2.amazonaws.com/graphql",
        "Region": "us-east-2",
        "AuthMode": "API_KEY",
        "ApiKey": "<MY API KEY>"
        }
    }
}
```

**Comment by yuth** [comment]
Released in Amplify CLI 1.6.6
