### ISSUE TITLE
Amplify references deleted Pinpoint project 

### ISSUE THREAD

**Issue by osehmathias** [aws-amplify/amplify-cli#13560]
### How did you install the Amplify CLI?

npm 

### If applicable, what version of Node.js are you using?

n/a

### Amplify CLI Version

12.10.1

### What operating system are you using?

macOS 14.3

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Yes, but will explain in bug report 

### Describe the bug

I have 3 amplify environments - `dev`, `staging` and `production`

At some point, I had to delete and recreate the `dev` environment because I made too many changes to the schema at once and it got stuck in a stack error that couldn't be rolled back. 

Now, I tried to update the notifications to APNS. It fails with:
```
MAC verified OK
🛑 Failed to enable the APNS channel.
```

the `--debug` flag shows the cause of the error is: 

```
Resource not found
NotFoundException: Resource not found
```

So I try to delete the Pinpoint resource so that I could add it again. 

`amplify remove notifications`

It responds with: 

```
osehmathias@Osehs-MacBook-Air mobile % amplify remove notifications --debug
✔ Choose the notification channel to remove · All channels on Pinpoint resource : *********
✔ Confirm that you want to delete the associated Amazon Pinpoint application (y/N) · yes

✔ Project with ID 'd2beb632edfb40f38d7a62526b8c2c8b' was already deleted from the cloud.
Deployment state saved successfully.
The Pinpoint application has been successfully deleted.
```

This is the old project ID. 

I check the status however, and it still shows notifications and analytics are active. 

It won't get rid of this ID, so I can't add a new Pinpoint project.

I have tried editing all of the AWS files to replace the old Pinpoint project ID with the new one, then pushing it up. This causes a failed deployment and I need to rollback. 

It's causing major development delays as it shows an error on every page load. 

### Expected behavior

1. I should be able to update or delete my Pinpoint resource 
2. After deleting an environment, then creating it again, the old Pinpoint ID should not persist the in the Amplify config
3. I should have a way to get rid of this ID

### Reproduction steps

Noted above. 

### Log output

<details>

```
# Put your logs below this line
osehmathias@Osehs-MacBook-Air mobile % amplify add notifications --debug
✔ Choose the notification channel to enable · APNS |  Apple Push Notifications
✔ Select the authentication method for the APNS channel · Certificate
✔ The certificate file path (.p12):  · ./certificates/amplify.p12
✔ The certificate password (if any):  · ***********
MAC verified OK
🛑 Failed to enable the APNS channel.

Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

NotificationsChannelAPNSFault: Failed to enable the APNS channel.
    at Object.enable (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-category-notifications/lib/channel-apns.js:121:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-category-notifications/lib/commands/notifications/add.js:46:40)
    at async Object.executeAmplifyCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-category-notifications/lib/index.js:62:5)
    at async executePluginModuleCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:139:5)
    at async executeCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:37:9)
    at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:121:5)

Resource not found
NotFoundException: Resource not found
    at Object.extractError (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/protocol/json.js:80:27)
    at Request.extractError (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/protocol/rest_json.js:61:8)
    at Request.callListeners (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /snapshot/amplify-cli/build/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /snapshot/amplify-cli/build/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at callNextListener (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at IncomingMessage.onEnd (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/event_listeners.js:417:13)
    at IncomingMessage.emit (node:events:525:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Session Identifier: e8df8299-d98b-4337-9758-38982c91841d
osehmathias@Osehs-MacBook-Air mobile % amplify remove notifications
✔ Choose the notification channel to remove · All channels on Pinpoint resource : speechfit
✔ Confirm that you want to delete the associated Amazon Pinpoint application (y/N) · yes

✔ Project with ID 'd2beb632edfb40f38d7a62526b8c2c8b' was already deleted from the cloud.
Deployment state saved successfully.
The Pinpoint application has been successfully deleted.

osehmathias@Osehs-MacBook-Air mobile % amplify push --y
✔ Successfully pulled backend environment dev from the cloud.

    Current Environment: dev

┌───────────────┬───────────────────────────────┬───────────┬───────────────────┐
│ Category      │ Resource name                 │ Operation │ Provider plugin   │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Analytics     │ speechfit                     │ No Change │ awscloudformation │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Api           │ speechfit                     │ No Change │ awscloudformation │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Auth          │ speechfitf3055fe3             │ No Change │ awscloudformation │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Auth          │ userPoolGroups                │ No Change │ awscloudformation │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Function      │ PostConfirmationTrigger       │ No Change │ awscloudformation │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Function      │ PreSignUpTrigger              │ No Change │ awscloudformation │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Function      │ actionInvitationLink          │ No Change │ awscloudformation │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Function      │ cleanUpRecordsUserInputs      │ No Change │ awscloudformation │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Function      │ clientConnectionUtils         │ No Change │ awscloudformation │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Function      │ clientsClinicConnection       │ No Change │ awscloudformation │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Function      │ cliniciansClinicConnection    │ No Change │ awscloudformation │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Function      │ compressAudio                 │ No Change │ awscloudformation │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Function      │ createClient                  │ No Change │ awscloudformation │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Function      │ createClinician               │ No Change │ awscloudformation │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Function      │ createDefaultEntry            │ No Change │ awscloudformation │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Function      │ createDefaultInsight          │ No Change │ awscloudformation │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Function      │ createFromTemplate            │ No Change │ awscloudformation │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Function      │ createUserAfterSignUp         │ No Change │ awscloudformation │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Function      │ deviceInterface               │ No Change │ awscloudformation │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Function      │ enrollInBeta                  │ No Change │ awscloudformation │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Function      │ exportClientData              │ No Change │ awscloudformation │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Function      │ getCardPreview                │ No Change │ awscloudformation │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Function      │ getEmailVerificationStatus    │ No Change │ awscloudformation │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Function      │ getNotesByRecord              │ No Change │ awscloudformation │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Function      │ importClient                  │ No Change │ awscloudformation │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Function      │ insightsBubble                │ No Change │ awscloudformation │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Function      │ insightsBubbleSummary         │ No Change │ awscloudformation │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Function      │ insightsLine                  │ No Change │ awscloudformation │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Function      │ insightsPie                   │ No Change │ awscloudformation │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Function      │ inviteParticipants            │ No Change │ awscloudformation │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Function      │ linkExistingClientOrClinician │ No Change │ awscloudformation │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Function      │ resendInvitation              │ No Change │ awscloudformation │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Function      │ sendpulseSubscribe            │ No Change │ awscloudformation │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Function      │ setEntryCount                 │ No Change │ awscloudformation │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Function      │ updateEntryCount              │ No Change │ awscloudformation │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Function      │ updatePicture                 │ No Change │ awscloudformation │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Function      │ updateRecordDate              │ No Change │ awscloudformation │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Function      │ updateUserAttributes          │ No Change │ awscloudformation │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Function      │ updateUserGroups              │ No Change │ awscloudformation │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Function      │ upgradeProgram                │ No Change │ awscloudformation │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Function      │ verifyEmail                   │ No Change │ awscloudformation │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Function      │ createGoalEntries             │ No Change │ awscloudformation │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Function      │ updateClientStreak            │ No Change │ awscloudformation │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Function      │ deleteEmptyRecords            │ No Change │ awscloudformation │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Notifications │ speechfit                     │ No Change │                   │
├───────────────┼───────────────────────────────┼───────────┼───────────────────┤
│ Storage       │ audio                         │ No Change │ awscloudformation │
└───────────────┴───────────────────────────────┴───────────┴───────────────────┘

No changes detected
osehmathias@Osehs-MacBook-Air mobile %

```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by osehmathias** [comment]
Further, when I pull down

`amplify pull --appId d1p8jrlphkviwn --envName dev`

Then check my amplify config file, I can see it's referencing the deleted pinpoint project. 

```
    "analytics": {
        "plugins": {
            "awsPinpointAnalyticsPlugin": {
                "pinpointAnalytics": {
                    "appId": "d2beb632edfb40f38d7a62526b8c2c8b",
                    "region": "ap-southeast-2"
                },
                "pinpointTargeting": {
                    "region": "ap-southeast-2"
                }
            }
        }
    },
```

There is no Pinpoint project with this ID in my account.

If I try to delete it with `amplify remove notifications`, it just gives me: 

```
osehmathias@Osehs-MacBook-Air mobile % amplify remove notifications 
✔ Choose the notification channel to remove · All channels on Pinpoint resource : *********
✔ Confirm that you want to delete the associated Amazon Pinpoint application (y/N) · yes

✔ Project with ID 'd2beb632edfb40f38d7a62526b8c2c8b' was already deleted from the cloud.
Deployment state saved successfully.
The Pinpoint application has been successfully deleted.
osehmathias@Osehs-MacBook-Air mobile %
```

**Comment by osehmathias** [comment]
I resolved this issue by editing the Amplify files to not have any Pinpoint resources, force pushing it, then adding a Pinpoint resource back into the project.
