### ISSUE TITLE
Unable to pull backend

### ISSUE THREAD

**Issue by muratcali** [aws-amplify/amplify-cli#13570]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v20.10.0

### Amplify CLI Version

12.10.1

### What operating system are you using?

MacOS 14.2.1

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

We are not able to pull the amplify backend. When we run the pull command with or without app ID it failes with error: `Failed to pull the backend` without any further information. This happens on all of the laptops of our developers. Even when we try to build the project in amplify it failes with the same error. So we are also not able to build and publish something on Amplify. Ive added the error log when we run the `amplify pull --appId *** --envName *** --debug` command. 

Deleting the Amplify folder doesnt solve the problem and when we run amplify init (with or without AppID) it doesnt recognise the backend. Also running `amplify pull --appId *** --envName *** --debug` in an empty folder doesnt work. Pulling new created environments works but pulling the existing one is not possible.

Looks like there is somewhere a bug which prevents us and AWS Amplify systems for pulling the backend from this environment.

Here a picture from the failed build:
<img width="2165" alt="AWS Build failed" src="https://github.com/aws-amplify/amplify-cli/assets/38989039/40c09b0b-6e6a-4ebd-afec-7b130dd033d6">

### Expected behavior

I expect the backend to be pulled from AWS Amplify. 

### Reproduction steps

1. Running `amplify pull --appId *** --envName *** --debug`
2. Returns with `Failed to pull the backend` on all devices + AWS Amplify build
3. Tried the same within an empty folder and amplify init resulted with same error.

### Log output

<details>

```
muratcaliskan@MacBook-Pro-van-Murat dashboard % amplify pull --appId *** --envName staging --debug
Opening link: https://eu-central-1.admin.amplifyapp.com/admin/***/staging/verify/?loginVersion=1
⠏ Confirm login in the browser or manually paste in your CLI login key:
Successfully received Amplify Studio tokens.
Amplify AppID found: ddon70oqkysfm. Amplify App name is: ***
Backend environment staging found in Amplify Console app: ***
? Choose your default editor: Visual Studio Code
✔ Choose the type of app that you're building · javascript
Please tell us about your project
? What javascript framework are you using react
? Source Directory Path:  src
? Distribution Directory Path: build
? Build Command:  npm run-script build
? Start Command: npm run-script start
🛑 Failed to pull the backend.

Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

PullBackendFault: Failed to pull the backend.
    at attachBackend (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/attach-backend.js:55:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/commands/pull.js:64:9)
    at async Object.executeAmplifyCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:194:9)
    at async executePluginModuleCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:139:5)
    at async executeCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:37:9)
    at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:121:5)

File at path: '/Users/muratcaliskan/Projects/dashboard/amplify/backend/auth/TenderTracer/parameters.json' does not exist
Error: File at path: '/Users/muratcaliskan/Projects/dashboard/amplify/backend/auth/TenderTracer/parameters.json' does not exist
    at JSONUtilities.readJson (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-cli-core/lib/jsonUtilities.js:44:19)
    at StateManager.getData (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-cli-core/lib/state-manager/stateManager.js:327:56)
    at StateManager.getResourceParametersJson (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-cli-core/lib/state-manager/stateManager.js:149:25)
    at ensureAmplifyMetaFrontendConfig (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/on-category-outputs-change.js:105:60)
    at AmplifyToolkit.onCategoryOutputsChange (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/on-category-outputs-change.js:46:53)
    at generateFiles (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/attach-backend-steps/a40-generateFiles.js:63:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async attachBackend (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/attach-backend.js:49:9)
    at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/commands/pull.js:64:9)
    at async Object.executeAmplifyCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:194:9)
    at async executePluginModuleCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:139:5)
    at async executeCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:37:9)
    at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:121:5)

Session Identifier: 10e95ec8-c591-44f7-80cc-ffa852f5b60f


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @muratcali, thank you for reaching out. From the logs provided the error message stands out: `'/Projects/dashboard/amplify/backend/auth/TenderTracer/parameters.json' does not exist`. 
Do you observe the error message on a local `amplify push`?
locally, under the `amplify/auth/build` folder do you observe a `parameters.json` file? if you do not see one, could try adding a empty `parameters.json`, run `amplify build` to verify if the file gets populated and then push.
additionally, on the AWS S3 console, could you open the S3 bucket `amplify-<appName>-<envName>-<randomHash>-deployment`, download the `#current-cloud-backend.zip` and extract it.
In the `#current-cloud-backend`, under the auth folder do you observe a `parameters.json` file?

**Comment by muratcali** [comment]
Hi @ykethan, Thanks for your message.

Ive deleted the whole amplify folder to do a clean pull so there is right now no amplify folder available in my project. So its not possible for me to da a push right now.

If download and open the `#current-cloud-backend.zip` file it doesn't have an auth map. It only has an auth map inside the map awscloudformation, which doesnt have the parameters.json file. Ive added pictures from this map structure down below.

Ive noticed that there are a lot of duplicate files.


<img width="365" alt="Screenshot at Feb 06 00-08-38" src="https://github.com/aws-amplify/amplify-cli/assets/38989039/c670249d-338e-495a-b1bb-e6351054f8b6">
<img width="365" alt="Screenshot at Feb 06 00-08-54" src="https://github.com/aws-amplify/amplify-cli/assets/38989039/dd64fd2e-9894-435c-bbea-d7c0469904fb">
<img width="344" alt="Screenshot at Feb 06 00-09-06" src="https://github.com/aws-amplify/amplify-cli/assets/38989039/c847150f-ca2d-4908-b70d-6fbe57068796">

**Comment by ykethan** [comment]
Hey @muratcali, is the project in a google/icloud drive folder? as the issue appears to be similar to https://github.com/aws-amplify/amplify-cli/issues/13335, to mitigate this you can download the `#current-cloud-backend.zip` archive, unzip, remove duplicate files, re-zip, and re-upload.

**Comment by muratcali** [comment]
Hi @ykethan , Thanks for your message. Ive tried the option you mentioned and now im getting the following error:

```
muratcaliskan@MacBook-Pro-van-Murat dashboard % amplify pull --appId*** --envName *** --debug
Opening link: https://eu-central-1.admin.amplifyapp.com/admin/***/***/verify/?loginVersion=1
⠇ Confirm login in the browser or manually paste in your CLI login key:
Successfully received Amplify Studio tokens.
Amplify AppID found: ***. Amplify App name is: ***
Backend environment staging found in Amplify Console app: ***
🛑 Failed to pull the backend.

Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

PullBackendFault: Failed to pull the backend.
    at attachBackend (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/attach-backend.js:55:15)
    at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/commands/pull.js:64:9)
    at async Object.executeAmplifyCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:194:9)
    at async executePluginModuleCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:139:5)
    at async executeCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:37:9)
    at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:121:5)

File at path: '/Users/muratcaliskan/Projects/dashboard/amplify/#current-cloud-backend/amplify-meta.json' does not exist
Error: File at path: '/Users/muratcaliskan/Projects/dashboard/amplify/#current-cloud-backend/amplify-meta.json' does not exist
    at JSONUtilities.readJson (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-cli-core/lib/jsonUtilities.js:44:19)
    at AmplifyToolkit.readJsonFile (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/read-json-file.js:6:45)
    at ensureAmplifyMeta (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/attach-backend.js:127:46)
    at Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/attach-backend.js:118:36)
    at async Object.attachBackend (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/index.js:196:3)
    at async queryProvider (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/attach-backend-steps/a10-queryProvider.js:36:5)
    at async attachBackend (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/attach-backend.js:43:9)
    at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/commands/pull.js:64:9)
    at async Object.executeAmplifyCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:194:9)
    at async executePluginModuleCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:139:5)
    at async executeCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:37:9)
    at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:121:5)

Session Identifier: 0aee2b19-d393-4064-a728-c8dddb3b8da3
```

As mentioned in the error before it returns:
`Error: File at path: '/Users/muratcaliskan/Projects/dashboard/amplify/#current-cloud-backend/amplify-meta.json' does not exist`

But this file exists inside the S3 bucket see image:
<img width="644" alt="image" src="https://github.com/aws-amplify/amplify-cli/assets/38989039/4eb01eda-f945-4e3c-b174-cf512e81225f">

Also ive mentioned alot of other directories inside this S3 bucket which i never saw before. Here is a picture from the bucket. Are these required files? Or is something wrong here?
<img width="1039" alt="image" src="https://github.com/aws-amplify/amplify-cli/assets/38989039/45cf7316-df30-4b3b-9dc9-fc05729e98d4">

**Comment by ykethan** [comment]
Hey @muratcali, just to ensure this isnt the case. Could you download the `#current-cloud-backend.zip` from the S3 bucket as when re-zipping this tends to create a nested folder that may cause this error message. similar issue: https://github.com/aws-amplify/amplify-cli/issues/13386
The steps in the [gist](https://gist.github.com/josefaidt/be56f2a8a821b084b66e40ce51e20b44) provides an example. 

The files at the root of the S3 bucket are expected as they get utilized by services such as Amplify Studio.

**Comment by ykethan** [comment]
Hey @muratcali, interesting. could you try zipping the `#current-cloud-backend` with a local copy of the project resources?
For example:
![image](https://github.com/aws-amplify/amplify-cli/assets/87995712/64255398-afb9-4f1b-9ae2-b1dab5ab55c3)

**Comment by josefaidt** [comment]
Hey @muratcali :wave: if you check the CloudFormation console for this stack, do you see the previous deployment failure and reason (under the "Events" tab)? Does it show a reason for the rollback failure?

**Comment by muratcali** [comment]
@josefaidt Thanks for your message. I see the following errors:

<img width="719" alt="image" src="https://github.com/aws-amplify/amplify-cli/assets/38989039/cb5571d5-9566-4296-8d53-68193206275c">

**Comment by ykethan** [comment]
Hey @muratcali , apologies on the delay in a response. Transferring the issue to our API repository for additional assistance as the error appears to be an error on the GraphQL API resource.
