### ISSUE TITLE
Unable to pull project using SSO

### ISSUE THREAD

**Issue by ellsssss** [aws-amplify/amplify-cli#13730]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

21.5.0

### Amplify CLI Version

12.11.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

Im trying to pull an existing project from amplify using the following command and choosing AWS profile for authentication method.
`amplify pull --appId 123466foobar --envName dev`

This is how I have setup my profiles according to https://docs.amplify.aws/javascript/start/getting-started/installation/#manually-configure-the-amplify-cli

```
[profile my-sso-profile]
sso_session = my-sso
sso_account_id = 123456789
sso_role_name = AdministratorAccess
region = us-east-2
output = json
credential_process = aws configure export-credentials --profile my-sso-profile

[sso-session my-sso]
sso_region = us-east-2
sso_start_url = https://mycompany.awsapps.com/start
sso_registration_scopes = sso:account:access
```

I get this error
```
 Select the authentication method you want to use: AWS profile

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

? Please choose the profile you want to use my-sso-profile
🛑 App 123466foobar not found.

Resolution: Check that the region of the Amplify App is matching the configured region.
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

ProjectNotFoundError: App 123466foobar not found.
    at getAmplifyApp (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/attach-backend.js:182:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/attach-backend.js:115:22)
    at async Object.attachBackend (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/index.js:196:3)
    at async queryProvider (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/attach-backend-steps/a10-queryProvider.js:36:5)
    at async attachBackend (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/attach-backend.js:43:9)
    at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/commands/pull.js:64:9)
    at async Object.executeAmplifyCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:194:9)
    at async executePluginModuleCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:139:5)
    at async executeCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:37:9)
    at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:121:5)

App 123466foobar not found.
NotFoundException: App 123466foobar not found.
    at Object.extractError (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/protocol/json.js:80:27)
    at Request.extractError (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/protocol/rest_json.js:61:8)
    at Request.callListeners (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /snapshot/amplify-cli/build/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /snapshot/amplify-cli/build/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at callNextListener (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at IncomingMessage.onEnd (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/event_listeners.js:417:13)
    at IncomingMessage.emit (node:events:525:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

When I do `aws amplify list-apps --region us-east-2 --profile my-sso-profile` I can see the App/Project in there, so not really sure what is going on. Also using long-lived access/secret key works just fine.

### Expected behavior

Be able to pull an Amplify project using AWS profile as authentication method

### Reproduction steps

1. Setup aws profile according to https://docs.amplify.aws/javascript/start/getting-started/installation/#manually-configure-the-amplify-cli
2. Run `amplify pull --appId 123466foobar --envName dev`

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ellsssss** [comment]
@ykethan Hello! Thanks for the response! 

When i try just `amplify-pull`, I see projects from a different AWS account under our org (the error does makes sense because the appID i was pulling does not exist there), which is strange since I have set the correct account id on the profile settings for `sso_account_id`. Any idea why its looking up from a different account instead of whats set on the profile?

**Comment by ykethan** [comment]
@ellsssss could  run `cat ~/.aws/config` and re-verify if the account id. are you pulling the environment into a empty folder? Could you check for any environment variables that may be causing this behavior?
could you try removing the old sso local config and recreate using `aws configure sso` and rerun the pull?

**Comment by ellsssss** [comment]
> @ellsssss could run `cat ~/.aws/config` and re-verify if the account id. are you pulling the environment into a empty folder? Could you check for any environment variables that may be causing this behavior? could you try removing the old sso local config and recreate using `aws configure sso` and rerun the pull?

Thanks, this works now. This is what I had to do:
- Clear out my `~/.aws/credentials` file (not sure if this affected anything)
- Comment out all stuff within `~/.aws/config` and redo the `aws configure sso` process.
- Added a line `credential_process = aws configure export-credentials --profile my-dev-sso` for the profile `my-dev-sso`

Thanks for the help, I was able to pull the project.
