### ISSUE TITLE
Migration to new account

### ISSUE THREAD

**Issue by fistofzen** [aws-amplify/amplify-cli#13744]
### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

v20.11.1

### Amplify CLI Version

12.10.3

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

Hello
I followed the https://docs.amplify.aws/javascript/tools/cli/migration/cli-migrate-aws-account/
to migrate my app to the new aws account but I am getting error because apmlify tries to signin with the appid d22h1kgc6xq1y7 but it is not available in the new account. 

### Expected behavior

pushing the app to the new account

### Reproduction steps

[1. ampl](https://docs.amplify.aws/javascript/tools/cli/migration/cli-migrate-aws-account/)

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @fistofzen, could you provide us the full error message printed on the terminal?
Does the project have a `team-provider-info.json`? 
Tried reproducing the error message with and without a `team-provider-info.json` wile selecting a new profile created a new app.

**Comment by fistofzen** [comment]
I tried every way,
First I deleted the team-provider-info.json but still the same error. app id not found. 
The system trying to find old app id in the new account but it not exists. And as a result login is not successful.

**Comment by ykethan** [comment]
@fistofzen tried reproing this issue with a new account and removing the `team-provider-info.json` then run `amplify init` selecting the new profile but did not observe any init failure.
Are you referring to the warning `⚠️ Failed to resolve AppId. Skipping parameter download.`?
the warning should not effect the project creation but warns the user it unable to find an appID associated and created a new application on the console.

**Comment by fistofzen** [comment]
after apmlify init,
I am going like that.

 Note: It is recommended to run this command from the root of your app directory
? Do you want to use an existing environment? No
? Enter a name for the environment dev
Using default provider  awscloudformation
⚠️ Failed to resolve AppId. Skipping parameter download.
? Select the authentication method you want to use: AWS access keys
⠴ Initializing your environment: dev
✖ Initializing your environment: dev
✖ There was an error initializing your environment.
🛑 Could not initialize platform for 'dev': Missing required key 'Bucket' in params

**Comment by fistofzen** [comment]
ShellCommandExecutionError: Received error [Error: Command was killed with SIGSEGV (Segmentation fault): yarn --version] running command [yarn --version]
    at execWithOutputAsString (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-cli-core/lib/utils/shell-utils.js:38:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getYarnPackageManager (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-cli-core/lib/utils/packageManager.js:131:36)
    at async runPackageManagerInstall (/snapshot/amplify-cli/build/node_modules/amplify-nodejs-function-runtime-provider/lib/utils/legacyBuild.js:70:28)
    at async installDependencies (/snapshot/amplify-cli/build/node_modules/amplify-nodejs-function-runtime-provider/lib/utils/legacyBuild.js:67:5)
    at async Object.buildResource [as build] (/snapshot/amplify-cli/build/node_modules/amplify-nodejs-function-runtime-provider/lib/utils/legacyBuild.js:44:13)
    at async buildFunction (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-category-function/lib/provider-utils/awscloudformation/utils/buildFunction.js:29:22)
    at async prepareResource (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/push-resources.js:420:33)
    at async prepareBuildableResources (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/push-resources.js:416:5)
    at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/push-resources.js:177:5)
    at async /snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/push-resources.js:137:16
    at async Promise.all (index 0)
    at async providersPush (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/push-resources.js:133:5)
    at async AmplifyToolkit.pushResources (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/push-resources.js:107:13)
    at async Object.executeAmplifyCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:194:9)
    at async executePluginModuleCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:139:5)
    at async executeCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:37:9)
    at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:121:5)

Session Identifier: 335820ba-9e85-4be9-8e54-c08a8b701d7d

**Comment by ykethan** [comment]
@fistofzen could you provide us the local yarn version being used. Could you trying using the yarn version `1.22.19` and retry the command.

**Comment by ykethan** [comment]
Closing the issue due to inactivity. Do reach out to us if you are still experiencing this issue
