### ISSUE TITLE
Error when run "amplify init"

### ISSUE THREAD

**Issue by hoangnguyencong-agilityio** [aws-amplify/amplify-cli#13770]
### How did you install the Amplify CLI?

From AWS Image

### If applicable, what version of Node.js are you using?

v16.19.0

### Amplify CLI Version

4.46.1

### What operating system are you using?

Ubuntu

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No, I didn't

### Describe the bug

My project was running for a long time, I have configured triggering build from Amplify CI/CD.
It still worked well yesterday but there is an error being thrown today at the build step.

The error is below:
```
# Initializing new Amplify environment: dev (amplify init)

2024-05-08T10:51:36.716Z [INFO]: Initializing new Amplify CLI version...

2024-05-08T10:51:36.975Z [INFO]: Cannot find module 'node:os'

Require stack:

- /root/.nvm/versions/node/v16.19.0/lib/node_modules/@aws-amplify/cli/node_modules/address/dist/commonjs/address.js

- /root/.nvm/versions/node/v16.19.0/lib/node_modules/@aws-amplify/cli/node_modules/address/dist/commonjs/index.js

- /root/.nvm/versions/node/v16.19.0/lib/node_modules/@aws-amplify/cli/node_modules/detect-port/lib/detect-port.js

- /root/.nvm/versions/node/v16.19.0/lib/node_modules/@aws-amplify/cli/node_modules/detect-port/index.js

- /root/.nvm/versions/node/v16.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-dynamodb-simulator/index.js

- /root/.nvm/versions/node/v16.19.0/lib/node_modules/@aws-amplify/cli/lib/utils/post-install-initialization.js

- /root/.nvm/versions/node/v16.19.0/lib/node_modules/@aws-amplify/cli/lib/plugin-manager.js

- /root/.nvm/versions/node/v16.19.0/lib/node_modules/@aws-amplify/cli/lib/index.js

- /root/.nvm/versions/node/v16.19.0/lib/node_modules/@aws-amplify/cli/bin/amplify
2024-05-08T10:51:36.976Z [INFO]: /root/.nvm/versions/node/v16.19.0/lib/node_modules/@aws-amplify/cli/node_modules/address/dist/commonjs/address.js:1
```

### Expected behavior

amplify init command can back to work

### Reproduction steps

Configure build settings:
Image: Amazon Linux 2
Live package updates: 4.46.1

Build settings:
version: 1
applications:
  - backend:
      phases:
        build:
          commands:
            - amplify init
            - amplify push --simple

### Log output

<details>

```
# Put your logs below this line
2024-05-08T10:50:10.406Z [INFO]: Git SSH Key acquired


2024-05-08T10:50:14.501Z [INFO]: Agent pid 166

2024-05-08T10:50:14.596Z [INFO]: Identity added: /root/.ssh/git_rsa (/root/.ssh/git_rsa)

Cloning into ...

Warning: Permanently added the ECDSA host key for IP address '140.82.113.4' to the list of known hosts.

2024-05-08T10:50:14.597Z [INFO]: # Checking for Git submodules at: /codebuild/output/src2340588738/src/.../.gitmodules

2024-05-08T10:50:14.602Z [INFO]: # Retrieving environment cache...

2024-05-08T10:50:14.657Z [INFO]: # Retrieved environment cache

2024-05-08T10:50:14.658Z [INFO]: ---- Setting Up SSM Secrets ----

2024-05-08T10:50:14.658Z [INFO]: SSM params {"Path":"/amplify/d35xmengb0w263/dev/","WithDecryption":true}

2024-05-08T10:50:15.962Z [INFO]: # Patching NPM package '@aws-amplify/cli' from 10.5.2 to 4.46.1...

2024-05-08T10:50:22.063Z [INFO]: npm WARN ERESOLVE overriding peer dependency

2024-05-08T10:50:22.068Z [INFO]: npm WARN While resolving: amplify-codegen@2.28.1

npm WARN Found: amplify-cli-core@1.18.1

npm WARN node_modules/@aws-amplify/cli/node_modules/amplify-cli-core

npm WARN amplify-cli-core@"1.18.1" from @aws-amplify/cli@4.46.1

npm WARN node_modules/@aws-amplify/cli

npm WARN @aws-amplify/cli@"4.46.1" from the root project

npm WARN 19 more (amplify-category-analytics, amplify-category-api, ...)

20

npm WARN

21

npm WARN Could not resolve dependency:

22

npm WARN peer amplify-cli-core@"^2.3.0" from amplify-codegen@2.28.1

23

npm WARN node_modules/@aws-amplify/cli/node_modules/amplify-codegen

24

npm WARN amplify-codegen@"^2.23.1" from @aws-amplify/cli@4.46.1

25

npm WARN node_modules/@aws-amplify/cli

26

npm WARN 2 more (amplify-provider-awscloudformation, amplify-util-mock)

27

npm WARN

28

npm WARN Conflicting peer dependency: amplify-cli-core@2.12.0

29

npm WARN node_modules/amplify-cli-core0

npm WARN peer amplify-cli-core@"^2.3.0" from amplify-codegen@2.28.11

npm WARN node_modules/@aws-amplify/cli/node_modules/amplify-codegen2

npm WARN amplify-codegen@"^2.23.1" from @aws-amplify/cli@4.46.13

npm WARN node_modules/@aws-amplify/cli4

npm WARN 2 more (amplify-provider-awscloudformation, amplify-util-mock)5

2024-05-08T10:50:22.077Z [INFO]: npm WARN ERESOLVE overriding peer dependency6

npm WARN While resolving: amplify-codegen@2.28.17

npm WARN Found: graphql-transformer-core@6.27.08

npm WARN node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core9

npm WARN graphql-transformer-core@"6.27.0" from @aws-amplify/cli@4.46.1
0

npm WARN node_modules/@aws-amplify/cli
1

npm WARN @aws-amplify/cli@"4.46.1" from the root project
2

npm WARN 5 more (amplify-category-api, amplify-category-function, ...)
3

npm WARN
4

npm WARN Could not resolve dependency

npm WARN peer graphql-transformer-core@"^7.2.1" from amplify-codegen@2.28.

npm WARN node_modules/@aws-amplify/cli/node_modules/amplify-codege

npm WARN amplify-codegen@"^2.23.1" from @aws-amplify/cli@4.46.

npm WARN node_modules/@aws-amplify/cl

npm WARN 2 more (amplify-provider-awscloudformation, amplify-util-mock)0

npm WARN1

npm WARN Conflicting peer dependency: graphql-transformer-core@7.6.112

npm WARN node_modules/graphql-transformer-core3

npm WARN peer graphql-transformer-core@"^7.2.1" from amplify-codegen@2.28.14

npm WARN node_modules/@aws-amplify/cli/node_modules/amplify-codegen5

npm WARN amplify-codegen@"^2.23.1" from @aws-amplify/cli@4.46.16

npm WARN node_modules/@aws-amplify/cli7

npm WARN 2 more (amplify-provider-awscloudformation, amplify-util-mock)8

2024-05-08T10:50:40.412Z [INFO]: npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated9

2024-05-08T10:50:40.435Z [INFO]: npm

2024-05-08T10:50:40.436Z [INFO]: WARN deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.

2024-05-08T10:50:40.528Z [INFO]: npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated

2024-05-08T10:50:40.641Z [INFO]: npm WARN

2024-05-08T10:50:40.642Z [INFO]: deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated

2024-05-08T10:50:40.797Z [INFO]: npm

2024-05-08T10:50:40.798Z [INFO]: WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated

2024-05-08T10:50:40.799Z [INFO]: npm

2024-05-08T10:50:40.800Z [INFO]: WARN deprecated @babel/plugin-proposal-object-rest-spread@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.

2024-05-08T10:50:41.026Z [INFO]: npm WARN

2024-05-08T10:50:41.026Z [INFO]: deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

2024-05-08T10:50:41.252Z [INFO]: npm WARN deprecated

2024-05-08T10:50:41.252Z [INFO]: uuid@3.4.0: Please upgrade to version 7 or higher. Older versions may use Math.random() in certain circumstances, which is known to be problematic. See https://v8.dev/blog/math-random for details.

2024-05-08T10:50:42.365Z [INFO]: npm

2024-05-08T10:50:42.366Z [INFO]:

2024-05-08T10:50:42.366Z [INFO]: WARN

2024-05-08T10:50:42.366Z [INFO]:

2024-05-08T10:50:42.366Z [INFO]: deprecated

2024-05-08T10:50:42.366Z [INFO]: graphql-import@0.7.1: GraphQL Import has been deprecated and merged into GraphQL Tools, so it will no longer get updates. Use GraphQL Tools instead to stay up-to-date! Check out https://www.graphql-tools.com/docs/migration-from-import for migration and https://the-guild.dev/blog/graphql-tools-v6 for new changes.

2024-05-08T10:50:42.601Z [INFO]: npm WARN

2024-05-08T10:50:42.602Z [INFO]: deprecated event-to-promise@0.8.0: Use promise-toolbox/fromEvent instead

2024-05-08T10:50:44.645Z [INFO]: npm WARN deprecated

2024-05-08T10:50:44.651Z [INFO]: @graphql-toolkit/common@0.6.6: GraphQL Toolkit is deprecated and merged into GraphQL Tools, so it will no longer get updates. Use GraphQL Tools instead to stay up-to-date! Check out https://www.graphql-tools.com/docs/migration-from-toolkit for migration and https://the-guild.dev/blog/graphql-tools-v6 for new changes.

2024-05-08T10:50:45.693Z [INFO]: npm WARN deprecated @graphql-toolkit/common@0.9.7: GraphQL Toolkit is deprecated and merged into GraphQL Tools, so it will no longer get updates. Use GraphQL Tools instead to stay up-to-date! Check out https://www.graphql-tools.com/docs/migration-from-toolkit for migration and https://the-guild.dev/blog/graphql-tools-v6 for new changes.

2024-05-08T10:50:45.740Z [INFO]: npm WARN

2024-05-08T10:50:45.740Z [INFO]: deprecated @graphql-toolkit/common@0.9.7: GraphQL Toolkit is deprecated and merged into GraphQL Tools, so it will no longer get updates. Use GraphQL Tools instead to stay up-to-date! Check out https://www.graphql-tools.com/docs/migration-from-toolkit for migration and https://the-guild.dev/blog/graphql-tools-v6 for new changes.

2024-05-08T10:50:46.857Z [INFO]: npm WARN deprecated graphql-tools@4.0.8: This package has been deprecated and now it only exports makeExecutableSchema.

npm WARN deprecated And it will no longer receive updates.

npm WARN

2024-05-08T10:50:46.857Z [INFO]: deprecated We recommend you to migrate to scoped packages such as @graphql-tools/schema, @graphql-tools/utils and etc.

npm WARN deprecated Check out https://www.graphql-tools.com to learn what package you should use instead

2024-05-08T10:51:25.568Z [INFO]: npm WARN

2024-05-08T10:51:25.573Z [INFO]: deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

2024-05-08T10:51:25.574Z [INFO]: npm

2024-05-08T10:51:25.574Z [INFO]: WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

2024-05-08T10:51:25.585Z [INFO]: npm

2024-05-08T10:51:25.586Z [INFO]: WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

2024-05-08T10:51:28.631Z [INFO]: # Done patching NPM package '@aws-amplify/cli' to version 4.46.1

2024-05-08T10:51:28.639Z [INFO]: # Retrieving cache...

2024-05-08T10:51:28.678Z [INFO]: # Retrieved cache

2024-05-08T10:51:32.609Z [INFO]: ## Starting Backend Build

# Starting phase: build

2024-05-08T10:51:32.615Z [INFO]: # Executing command: EXPORT_STANDARD_GL_TYPES_TEMPLATE_FILE=$PWD/amplify/backend/excel/exportStandardGLTypes/exportStandardGLTypes-cloudformation-template.json

# Executing command: COMBINE_TEMPLATE_FILE=$PWD/amplify/backend/excel/combine/combine-cloudformation-template.json

# Executing command: EXPORT_TEMPLATE_FILE=$PWD/amplify/backend/excel/export/export-cloudformation-template.json

# Executing command: IMPORT_TEMPLATE_FILE=$PWD/amplify/backend/excel/import/import-cloudformation-template.json

# Executing command: FOLDER="amplify-build"

# Executing command: aws cloudformation package --use-json --template-file $EXPORT_TEMPLATE_FILE --s3-bucket $AMPLIFY_S3_BUCKET --s3-prefix $FOLDER --output-template-file $EXPORT_TEMPLATE_FILE

2024-05-08T10:51:33.515Z [WARNING]: Uploading to amplify-build/9d38dbc951a0b242e8703cf3754ee7e2 24340 / 24340.0 (100.00%)

2024-05-08T10:51:33.631Z [INFO]: Successfully packaged artifacts and wrote output template to file /codebuild/output/src2340588738/src/.../customer-api/amplify/backend/excel/export/export-cloudformation-template.json.

Execute the following command to deploy the packaged template

aws cloudformation deploy --template-file /codebuild/output/src2340588738/src/.../customer-api/amplify/backend/excel/export/export-cloudformation-template.json --stack-name <YOUR STACK NAME>

2024-05-08T10:51:33.705Z [INFO]: # Executing command: aws cloudformation package --use-json --template-file $IMPORT_TEMPLATE_FILE --s3-bucket $AMPLIFY_S3_BUCKET --s3-prefix $FOLDER --output-template-file $IMPORT_TEMPLATE_FILE

2024-05-08T10:51:34.159Z [WARNING]: Uploading to amplify-build/2d80fb939d5204b7fd90d1367dec9b0a 5400 / 5400.0 (100.00%)

2024-05-08T10:51:34.160Z [INFO]: Successfully packaged artifacts and wrote output template to file /codebuild/output/src2340588738/src/.../customer-api/amplify/backend/excel/import/import-cloudformation-template.json.

Execute the following command to deploy the packaged template

aws cloudformation deploy --template-file /codebuild/output/src2340588738/src/.../customer-api/amplify/backend/excel/import/import-cloudformation-template.json --stack-name <YOUR STACK NAME>

2024-05-08T10:51:34.233Z [INFO]: # Executing command: aws cloudformation package --use-json --template-file $COMBINE_TEMPLATE_FILE --s3-bucket $AMPLIFY_S3_BUCKET --s3-prefix $FOLDER --output-template-file $COMBINE_TEMPLATE_FILE

2024-05-08T10:51:34.732Z [WARNING]: Uploading to amplify-build/96af72d0993e6ec620409f508412cde6 27994 / 27994.0 (100.00%)

2024-05-08T10:51:34.733Z [INFO]: Successfully packaged artifacts and wrote output template to file /codebuild/output/src2340588738/src/.../customer-api/amplify/backend/excel/combine/combine-cloudformation-template.json.

Execute the following command to deploy the packaged template

aws cloudformation deploy --template-file /codebuild/output/src2340588738/src/.../customer-api/amplify/backend/excel/combine/combine-cloudformation-template.json --stack-name <YOUR STACK NAME>

2024-05-08T10:51:34.806Z [INFO]: # Executing command: aws cloudformation package --use-json --template-file $EXPORT_STANDARD_GL_TYPES_TEMPLATE_FILE --s3-bucket $AMPLIFY_S3_BUCKET --s3-prefix $FOLDER --output-template-file $EXPORT_STANDARD_GL_TYPES_TEMPLATE_FILE

2024-05-08T10:51:35.284Z [WARNING]: Uploading to amplify-build/845150d8e5563efa5876ed06373d533b 9589 / 9589.0 (100.00%)

2024-05-08T10:51:35.285Z [INFO]: Successfully packaged artifacts and wrote output template to file /codebuild/output/src2340588738/src/.../customer-api/amplify/backend/excel/exportStandardGLTypes/exportStandardGLTypes-cloudformation-template.json.

Execute the following command to deploy the packaged template

aws cloudformation deploy --template-file /codebuild/output/src2340588738/src/.../customer-api/amplify/backend/excel/exportStandardGLTypes/exportStandardGLTypes-cloudformation-template.json --stack-name <YOUR STACK NAME>

2024-05-08T10:51:35.362Z [INFO]: # Executing command: chmod u+x bin/amplifyPush.sh

2024-05-08T10:51:35.363Z [INFO]: # Executing command: ./bin/amplifyPush.sh -e $USER_BRANCH --simple

2024-05-08T10:51:35.374Z [INFO]: # Getting Amplify CLI Cloud-Formation stack info from environment cache

2024-05-08T10:51:35.382Z [INFO]: # Start initializing Amplify environment: dev

# Initializing new Amplify environment: dev (amplify init)

2024-05-08T10:51:36.716Z [INFO]: Initializing new Amplify CLI version...

2024-05-08T10:51:36.975Z [INFO]: Cannot find module 'node:os'

Require stack:

- /root/.nvm/versions/node/v16.19.0/lib/node_modules/@aws-amplify/cli/node_modules/address/dist/commonjs/address.js

- /root/.nvm/versions/node/v16.19.0/lib/node_modules/@aws-amplify/cli/node_modules/address/dist/commonjs/index.js

- /root/.nvm/versions/node/v16.19.0/lib/node_modules/@aws-amplify/cli/node_modules/detect-port/lib/detect-port.js

- /root/.nvm/versions/node/v16.19.0/lib/node_modules/@aws-amplify/cli/node_modules/detect-port/index.js

- /root/.nvm/versions/node/v16.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-dynamodb-simulator/index.js

- /root/.nvm/versions/node/v16.19.0/lib/node_modules/@aws-amplify/cli/lib/utils/post-install-initialization.js

- /root/.nvm/versions/node/v16.19.0/lib/node_modules/@aws-amplify/cli/lib/plugin-manager.js

- /root/.nvm/versions/node/v16.19.0/lib/node_modules/@aws-amplify/cli/lib/index.js

- /root/.nvm/versions/node/v16.19.0/lib/node_modules/@aws-amplify/cli/bin/amplify

2024-05-08T10:51:36.976Z [INFO]: /root/.nvm/versions/node/v16.19.0/lib/node_modules/@aws-amplify/cli/node_modules/address/dist/commonjs/address.js:1

Error: Cannot find module 'node:os'

Require stack:

- /root/.nvm/versions/node/v16.19.0/lib/node_modules/@aws-amplify/cli/node_modules/address/dist/commonjs/address.js

- /root/.nvm/versions/node/v16.19.0/lib/node_modules/@aws-amplify/cli/node_modules/address/dist/commonjs/index.js

- /root/.nvm/versions/node/v16.19.0/lib/node_modules/@aws-amplify/cli/node_modules/detect-port/lib/detect-port.js

- /root/.nvm/versions/node/v16.19.0/lib/node_modules/@aws-amplify/cli/node_modules/detect-port/index.js

- /root/.nvm/versions/node/v16.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-dynamodb-simulator/index.js

- /root/.nvm/versions/node/v16.19.0/lib/node_modules/@aws-amplify/cli/lib/utils/post-install-initialization.js

- /root/.nvm/versions/node/v16.19.0/lib/node_modules/@aws-amplify/cli/lib/plugin-manager.js

- /root/.nvm/versions/node/v16.19.0/lib/node_modules/@aws-amplify/cli/lib/index.js

- /root/.nvm/versions/node/v16.19.0/lib/node_modules/@aws-amplify/cli/bin/amplify

at Object.<anonymous> (/root/.nvm/versions/node/v16.19.0/lib/node_modules/@aws-amplify/cli/node_modules/address/dist/commonjs/address.js:7:35)

at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)

at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)

at Object.<anonymous> (/root/.nvm/versions/node/v16.19.0/lib/node_modules/@aws-amplify/cli/node_modules/address/dist/commonjs/index.js:17:22)

at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)

at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)

at Object.<anonymous> (/root/.nvm/versions/node/v16.19.0/lib/node_modules/@aws-amplify/cli/node_modules/detect-port/lib/detect-port.js:3:17)

at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)

at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)

at Object.<anonymous> (/root/.nvm/versions/node/v16.19.0/lib/node_modules/@aws-amplify/cli/node_modules/detect-port/index.js:3:18)

at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)

at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)

at Object.<anonymous> (/root/.nvm/versions/node/v16.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-dynamodb-simulator/index.js:5:20)

at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)

at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)

at /root/.nvm/versions/node/v16.19.0/lib/node_modules/@aws-amplify/cli/lib/utils/post-install-initialization.js:33:91

at async /root/.nvm/versions/node/v16.19.0/lib/node_modules/@aws-amplify/cli/lib/utils/post-install-initialization.js:33:43

at async Promise.all (index 0)

at async Object.postInstallInitialization (/root/.nvm/versions/node/v16.19.0/lib/node_modules/@aws-amplify/cli/lib/utils/post-install-initialization.js:32:5)

at async Object.getPluginPlatform (/root/.nvm/versions/node/v16.19.0/lib/node_modules/@aws-amplify/cli/lib/plugin-manager.js:56:9)

at async Object.run (/root/.nvm/versions/node/v16.19.0/lib/node_modules/@aws-amplify/cli/lib/index.js:65:30)

2024-05-08T10:51:36.988Z [ERROR]: !!! Build failed

2024-05-08T10:51:36.988Z [ERROR]: !!! Error: Command failed with exit code 1
2024-05-08T10:51:36.989Z [INFO]: # Starting environment caching...
2024-05-08T10:51:36.989Z [INFO]: # Uploading environment cache artifact...
2024-05-08T10:51:37.070Z [INFO]: # Uploaded environment cache artifact
2024-05-08T10:51:37.071Z [INFO]: # Environment caching completed
2024-05-08T10:51:37.071Z [INFO]: # A new default build image based on Amazon Linux 2023 is now generally available. The image includes newer versions of Node.js, Python, and Ruby that you can use to build your app. To use the new image, select "Amazon Linux:2023" in the "Build settings" section for your app in the Amplify console.

```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @hoangnguyencong-agilityio, thank you for reaching. noticed the Amplify CLI version is set to 4.46.1 which is an older version: https://www.npmjs.com/package/@aws-amplify/cli?activeTab=versions . with the current version being 12.12.0.
Additionally, you may have to upgrade your node version to 18.

**Comment by ykethan** [comment]
Closing the issue due to inactivity. Do reach out to us if you are still experiencing this issue
