### ISSUE TITLE
Running any amplify cmd results in "End of input while parsing an object (missing '}') at line 100,2 >>>} ..."

### ISSUE THREAD

**Issue by JncHrmn** [aws-amplify/amplify-cli#13868]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v20.0.0

### Amplify CLI Version

Cannot run the cmd

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

Whenever I run any `amplify` related command, it always results in this output: 
End of input while parsing an object (missing '}') at line 100,2 >>>} ...

Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

Session Identifier: 1626b8ef-3ccb-4387-bbe8-1cd361097c77
⠋ Creating Zip
End of input while parsing an object (missing '}') at line 100,2 >>>} ...
✖ Creating Zip

### Expected behavior

Commands should work as expected

### Reproduction steps

Just run any Amplify cmd from the terminal

### Project Identifier

Not able to run this command, because of the issue.

### Log output

<details>
Running `amplify --debug` returns this:                                                                                                                          
End of input while parsing an object (missing '}') at line 100,2 >>>} ...

Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

UnknownFault: End of input while parsing an object (missing '}') at line 100,2 >>>} ...
    at genericErrorToAmplifyException (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/amplify-exception-handler.js:129:49)
    at handleException (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/amplify-exception-handler.js:28:28)
    at process.<anonymous> (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:52:93)
    at process.emit (node:events:513:28)
    at process._fatalException (node:internal/process/execution:149:25)

End of input while parsing an object (missing '}') at line 100,2 >>>} ...
Error: End of input while parsing an object (missing '}') at line 100,2 >>>} ...
    at error (/snapshot/amplify-cli/build/node_modules/hjson/lib/hjson-parse.js:41:11)
    at object (/snapshot/amplify-cli/build/node_modules/hjson/lib/hjson-parse.js:379:12)
    at value (/snapshot/amplify-cli/build/node_modules/hjson/lib/hjson-parse.js:391:24)
    at object (/snapshot/amplify-cli/build/node_modules/hjson/lib/hjson-parse.js:358:23)
    at value (/snapshot/amplify-cli/build/node_modules/hjson/lib/hjson-parse.js:391:24)
    at object (/snapshot/amplify-cli/build/node_modules/hjson/lib/hjson-parse.js:358:23)
    at legacyRootValue (/snapshot/amplify-cli/build/node_modules/hjson/lib/hjson-parse.js:428:38)
    at Object.<anonymous> (/snapshot/amplify-cli/build/node_modules/hjson/lib/hjson-parse.js:454:23)
    at JSONUtilities.parse (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-cli-core/lib/jsonUtilities.js:94:27)
    at JSONUtilities.readJson (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-cli-core/lib/jsonUtilities.js:51:32)
    at StateManager.getData (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-cli-core/lib/state-manager/stateManager.js:327:56)
    at StateManager.getBackendConfig (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-cli-core/lib/state-manager/stateManager.js:116:31)
    at backendConfigParameterMapSupplier (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-environment-parameters/lib/backend-config-parameters-controller.js:61:70)
    at getParametersControllerInstance (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-environment-parameters/lib/backend-config-parameters-controller.js:13:81)
    at ensureEnvParamManager (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-environment-parameters/lib/environment-parameter-manager.js:14:144)
    at migrateTeamProviderInfo (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/utils/team-provider-migrate.js:21:74)
    at Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:109:69)
    at process.runNextTicks [as _tickCallback] (node:internal/process/task_queues:60:5)
    at Function.runMain (pkg/prelude/bootstrap.js:1980:13)
    at node:internal/main/run_main_module:23:47
</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @JannicMeetYu, thank you for reaching from the error message this stands out
`End of input while parsing an object (missing '}') at line 100,2 >>>}`
was there a recent merge done on your git branch? As the `>>>` appears to be added to the files.
Could you check the `amplify-meta.json` and `backend-config.json` to ensure if the file does contain the appropriate structure.
