### ISSUE TITLE
Blocked error! Syntax Error: Expected ":", found "@" when executing amplify push and amplify pull, also admin.amplifyapp.com/admin/.. data-manager doesnt work

### ISSUE THREAD

**Issue by chirpavel** [aws-amplify/amplify-cli#13862]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v20.12.2

### Amplify CLI Version

12.12.4

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

I added this model:
type SubscriptionPlan @model 
  @auth(
    rules: [
      {allow: private, provider: iam, operations: [read, create, update]},
      {allow: groups, groups: ["eu-central-admins"], operations: [read, create, update, delete]}
    ]
  ) {
  id: ID!
  branchId: ID!
  prevSubscriptionPlan: String
  subscriptionPlan: String
  price: Float
  paidAmount: Float
  isFake: Boolean
  duration: Int
  convertedDays: Int
  extraDays: Int
  expiryDate: AWSDateTime
  detailsSnapshot: String
  autoRenewal: Boolean
  owner: String
  type: String!
    String @default(value: "SP")
    @index(
      name: "subscriptionPlansByDate"
      queryField: "subscriptionPlansByDate"
      sortKeyFields: ["createdAt"]
    )
  createdAt: String!
}

This part to sort by createdAt:
type: String!
    String @default(value: "SP")
    @index(
      name: "subscriptionPlansByDate"
      queryField: "subscriptionPlansByDate"
      sortKeyFields: ["createdAt"]
    )
  createdAt: String!

### Describe the bug

When I added this part:
type: String!
    String @default(value: "SP")
    @index(
      name: "subscriptionPlansByDate"
      queryField: "subscriptionPlansByDate"
      sortKeyFields: ["createdAt"]
    )
  createdAt: String!

to the end of SubscriptionPlan model and execute amplify push - nothing work:
amplify push and amplify pull return error: Syntax Error: Expected ":", found "@"

The same error in the browser: https://eu-central-1.admin.amplifyapp.com/admin/d2bvp8o95pga13/staging/data-manager
GraphQLError: Syntax Error: Expected ":", found "@".
The error may be correlated with this previous error:
GraphQLError: Syntax Error: Expected ":", found "@".
    at Sa (https://eu-central-1.admin.amplifyapp.com/static/js/37.76c182c0.chunk.js:4:161300)
    at t.expectToken (https://eu-central-1.admin.amplifyapp.com/static/js/37.76c182c0.chunk.js:4:189570)
    at t.parseFieldDefinition (https://eu-central-1.admin.amplifyapp.com/static/js/37.76c182c0.chunk.js:4:183142)
    at t.optionalMany (https://eu-central-1.admin.amplifyapp.com/static/js/37.76c182c0.chunk.js:4:190428)
    at t.parseFieldsDefinition (https://eu-central-1.admin.amplifyapp.com/static/js/37.76c182c0.chunk.js:4:182944)
    at t.parseObjectTypeDefinition (https://eu-central-1.admin.amplifyapp.com/static/js/37.76c182c0.chunk.js:4:182172)
    at t.parseTypeSystemDefinition (https://eu-central-1.admin.amplifyapp.com/static/js/37.76c182c0.chunk.js:4:180669)
    at t.parseDefinition (https://eu-central-1.admin.amplifyapp.com/static/js/37.76c182c0.chunk.js:4:174398)
    at t.many (https://eu-central-1.admin.amplifyapp.com/static/js/37.76c182c0.chunk.js:4:190559)
    at t.parseDocument (https://eu-central-1.admin.amplifyapp.com/static/js/37.76c182c0.chunk.js:4:174002)
    at https://eu-central-1.admin.amplifyapp.com/static/js/37.76c182c0.chunk.js:4:195496
    at https://eu-central-1.admin.amplifyapp.com/static/js/37.76c182c0.chunk.js:4:1185836
    at f (https://eu-central-1.admin.amplifyapp.com/static/js/37.76c182c0.chunk.js:4:1184785)
    at https://eu-central-1.admin.amplifyapp.com/static/js/37.76c182c0.chunk.js:4:1185969
    at f (https://eu-central-1.admin.amplifyapp.com/static/js/37.76c182c0.chunk.js:4:1184785)
    at Object.current (https://eu-central-1.admin.amplifyapp.com/static/js/37.76c182c0.chunk.js:4:309635)
    at Object.e [as onStateChange] (https://eu-central-1.admin.amplifyapp.com/static/js/38.948fc0bf.chunk.js:4:1188845)
    at Object.i [as callback] (https://eu-central-1.admin.amplifyapp.com/static/js/38.948fc0bf.chunk.js:4:1180074)
    at https://eu-central-1.admin.amplifyapp.com/static/js/38.948fc0bf.chunk.js:4:1179674
    at ll (https://eu-central-1.admin.amplifyapp.com/static/js/38.948fc0bf.chunk.js:4:206125)
    at Object.notify (https://eu-central-1.admin.amplifyapp.com/static/js/38.948fc0bf.chunk.js:4:1179643)
    at Object.notifyNestedSubs (https://eu-central-1.admin.amplifyapp.com/static/js/38.948fc0bf.chunk.js:4:1180240)
    at Object._ [as onStateChange] (https://eu-central-1.admin.amplifyapp.com/static/js/38.948fc0bf.chunk.js:4:1181633)
    at Object.i [as callback] (https://eu-central-1.admin.amplifyapp.com/static/js/38.948fc0bf.chunk.js:4:1180074)
    at https://eu-central-1.admin.amplifyapp.com/static/js/38.948fc0bf.chunk.js:4:1179674
    at ll (https://eu-central-1.admin.amplifyapp.com/static/js/38.948fc0bf.chunk.js:4:206125)
    at Object.notify (https://eu-central-1.admin.amplifyapp.com/static/js/38.948fc0bf.chunk.js:4:1179643)
    at Object.notifyNestedSubs (https://eu-central-1.admin.amplifyapp.com/static/js/38.948fc0bf.chunk.js:4:1180240)
    at i (https://eu-central-1.admin.amplifyapp.com/static/js/38.948fc0bf.chunk.js:4:1180074)
    at E (https://eu-central-1.admin.amplifyapp.com/static/js/38.948fc0bf.chunk.js:4:276448)
    at https://eu-central-1.admin.amplifyapp.com/static/js/44.824f95d4.chunk.js:3:460334
    at https://eu-central-1.admin.amplifyapp.com/static/js/38.948fc0bf.chunk.js:4:102575
    at dispatch (https://eu-central-1.admin.amplifyapp.com/static/js/38.948fc0bf.chunk.js:4:278216)
    at https://eu-central-1.admin.amplifyapp.com/static/js/37.76c182c0.chunk.js:4:1307011
    at https://eu-central-1.admin.amplifyapp.com/static/js/37.76c182c0.chunk.js:4:1299533
    at Object.next (https://eu-central-1.admin.amplifyapp.com/static/js/37.76c182c0.chunk.js:4:1299638)
    at a (https://eu-central-1.admin.amplifyapp.com/static/js/37.76c182c0.chunk.js:4:1300278)

    at Sa (https://eu-central-1.admin.amplifyapp.com/static/js/37.76c182c0.chunk.js:4:161300)
    at t.expectToken (https://eu-central-1.admin.amplifyapp.com/static/js/37.76c182c0.chunk.js:4:189570)
    at t.parseFieldDefinition (https://eu-central-1.admin.amplifyapp.com/static/js/37.76c182c0.chunk.js:4:183142)
    at t.optionalMany (https://eu-central-1.admin.amplifyapp.com/static/js/37.76c182c0.chunk.js:4:190428)
    at t.parseFieldsDefinition (https://eu-central-1.admin.amplifyapp.com/static/js/37.76c182c0.chunk.js:4:182944)
    at t.parseObjectTypeDefinition (https://eu-central-1.admin.amplifyapp.com/static/js/37.76c182c0.chunk.js:4:182172)
    at t.parseTypeSystemDefinition (https://eu-central-1.admin.amplifyapp.com/static/js/37.76c182c0.chunk.js:4:180669)
    at t.parseDefinition (https://eu-central-1.admin.amplifyapp.com/static/js/37.76c182c0.chunk.js:4:174398)
    at t.many (https://eu-central-1.admin.amplifyapp.com/static/js/37.76c182c0.chunk.js:4:190559)
    at t.parseDocument (https://eu-central-1.admin.amplifyapp.com/static/js/37.76c182c0.chunk.js:4:174002)
    at https://eu-central-1.admin.amplifyapp.com/static/js/37.76c182c0.chunk.js:4:195496
    at https://eu-central-1.admin.amplifyapp.com/static/js/37.76c182c0.chunk.js:4:1185836
    at f (https://eu-central-1.admin.amplifyapp.com/static/js/37.76c182c0.chunk.js:4:1184785)
    at https://eu-central-1.admin.amplifyapp.com/static/js/37.76c182c0.chunk.js:4:1185969
    at f (https://eu-central-1.admin.amplifyapp.com/static/js/37.76c182c0.chunk.js:4:1184785)
    at https://eu-central-1.admin.amplifyapp.com/static/js/37.76c182c0.chunk.js:4:309635
    at https://eu-central-1.admin.amplifyapp.com/static/js/38.948fc0bf.chunk.js:4:1188491
    at https://eu-central-1.admin.amplifyapp.com/static/js/38.948fc0bf.chunk.js:4:1189025
    at Eg (https://eu-central-1.admin.amplifyapp.com/static/js/37.76c182c0.chunk.js:4:308847)
    at Xa (https://eu-central-1.admin.amplifyapp.com/static/js/38.948fc0bf.chunk.js:4:170059)
    at Go (https://eu-central-1.admin.amplifyapp.com/static/js/38.948fc0bf.chunk.js:4:178951)
    at vs (https://eu-central-1.admin.amplifyapp.com/static/js/38.948fc0bf.chunk.js:4:217401)
    at El (https://eu-central-1.admin.amplifyapp.com/static/js/38.948fc0bf.chunk.js:4:208925)
    at fl (https://eu-central-1.admin.amplifyapp.com/static/js/38.948fc0bf.chunk.js:4:208850)
    at sl (https://eu-central-1.admin.amplifyapp.com/static/js/38.948fc0bf.chunk.js:4:205859)
    at https://eu-central-1.admin.amplifyapp.com/static/js/38.948fc0bf.chunk.js:4:157337
    at t.unstable_runWithPriority (https://eu-central-1.admin.amplifyapp.com/static/js/38.948fc0bf.chunk.js:4:232575)
    at ji (https://eu-central-1.admin.amplifyapp.com/static/js/38.948fc0bf.chunk.js:4:157046)
    at $i (https://eu-central-1.admin.amplifyapp.com/static/js/38.948fc0bf.chunk.js:4:157282)
    at Qi (https://eu-central-1.admin.amplifyapp.com/static/js/38.948fc0bf.chunk.js:4:157217)
    at ll (https://eu-central-1.admin.amplifyapp.com/static/js/38.948fc0bf.chunk.js:4:206150)
    at Object.notify (https://eu-central-1.admin.amplifyapp.com/static/js/38.948fc0bf.chunk.js:4:1179643)
    at Object.notifyNestedSubs (https://eu-central-1.admin.amplifyapp.com/static/js/38.948fc0bf.chunk.js:4:1180240)
    at i (https://eu-central-1.admin.amplifyapp.com/static/js/38.948fc0bf.chunk.js:4:1180074)
    at E (https://eu-central-1.admin.amplifyapp.com/static/js/38.948fc0bf.chunk.js:4:276448)
    at https://eu-central-1.admin.amplifyapp.com/static/js/44.824f95d4.chunk.js:3:460334
    at https://eu-central-1.admin.amplifyapp.com/static/js/38.948fc0bf.chunk.js:4:102575
    at dispatch (https://eu-central-1.admin.amplifyapp.com/static/js/38.948fc0bf.chunk.js:4:278216)
    at https://eu-central-1.admin.amplifyapp.com/static/js/37.76c182c0.chunk.js:4:1307011
    at https://eu-central-1.admin.amplifyapp.com/static/js/37.76c182c0.chunk.js:4:1299533
    at Object.next (https://eu-central-1.admin.amplifyapp.com/static/js/37.76c182c0.chunk.js:4:1299638)
    at a (https://eu-central-1.admin.amplifyapp.com/static/js/37.76c182c0.chunk.js:4:1300278)
    
44.824f95d4.chunk.js:3 
 GET https://eu-central-1.admin.amplifyapp.com/static/js/44.824f95d4.chunk.js.map 404 (Not Found)
44.824f95d4.chunk.js:3 
 GET https://eu-central-1.admin.amplifyapp.com/static/js/38.948fc0bf.chunk.js.map 404 (Not Found)
44.824f95d4.chunk.js:3 
 GET https://eu-central-1.admin.amplifyapp.com/static/js/37.76c182c0.chunk.js.map 404 (Not Found)
44.824f95d4.chunk.js:3 
 POST https://o4505399133929472.ingest.sentry.io/api/4505399136092160/envelope/?s…bae4b0ae2f&sentry_version=7&sentry_client=sentry.javascript.react%2F7.57.0 429 (Too Many Requests)
 
 
 Session Identifier: 961eee15-0da6-458b-a4f2-2fb37d52f7ac
 Session Identifier: 9c55993b-53d7-49d7-89ca-c1cd94796a01
 Session Identifier: fb8e6830-83a8-4dec-808b-057654562da7
 Session Identifier: f17812a0-b421-4cec-be01-be2850c0a6a3
 
amplify diagnose --send-report
✅ Report saved: C:\Users\chirp\AppData\Local\Temp\SplitPay\report-1721509444518.zip
√ Done

Project Identifier: 70952c35bc147986b145b568d0636b2e

After error i tried amplify push --force and --no-gql-override flag
Nothing helps

### Expected behavior

Sorting by date like in the doc:
https://docs.amplify.aws/gen1/javascript/build-a-backend/graphqlapi/best-practice/query-with-sorting/

### Reproduction steps

1. Add this model:
type SubscriptionPlan @model 
  @auth(
    rules: [
      {allow: private, provider: iam, operations: [read, create, update]},
      {allow: groups, groups: ["eu-central-admins"], operations: [read, create, update, delete]}
    ]
  ) {
  id: ID!
  branchId: ID!
  prevSubscriptionPlan: String
  subscriptionPlan: String
  price: Float
  paidAmount: Float
  isFake: Boolean
  duration: Int
  convertedDays: Int
  extraDays: Int
  expiryDate: AWSDateTime
  detailsSnapshot: String
  autoRenewal: Boolean
  owner: String
  type: String!
    String @default(value: "SP")
    @index(
      name: "subscriptionPlansByDate"
      queryField: "subscriptionPlansByDate"
      sortKeyFields: ["createdAt"]
    )
  createdAt: String!
}

2. amplify push

3. Change the model

4. amplify push

### Project Identifier

 Project Identifier: 70952c35bc147986b145b568d0636b2e

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

![data-manager-screenshot 2024-07-21 050628](https://github.com/user-attachments/assets/dd28afac-7b2f-4132-b5f0-8b6170333518)

Data manager doesnt work at all!

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by chirpavel** [comment]
Now I tried to:
1. Clear the SubscriptionPlan model from AppSync Schema. No effect
2. Delete ui-components folder from src (maybe there some errors). No effect
3. Delete all data models in local schema and amplify push. No effect
4. Of cause I tried to restore from git. No effect

I cant use Amplify Data Manager, white blank page with errors in console

Help me please ASAP

**Comment by chirpavel** [comment]
После многих попыток попасть в Data manager - я смог. Он откылся без таблиц, я создал единственноу для пробы и нажал Deploy. Отобразилась ошибка при деплое

Step 1: Deployment failed
Close
GraphQL API SplitPay already exists in the project","resolution":"Use amplify update api to make modifications","link":"https://docs.amplify.aws/cli/project/troubleshooting/"}


I tried update api in cli, but the same error:
**amplify update api**

? Select from one of the below mentioned services: GraphQL

General information
- Name: SplitPay
- API endpoint: https://qoju2h4htrh3xitgusj476izcy.appsync-api.eu-central-1.amazonaws.com/graphql

Authorization modes
- Default: Amazon Cognito User Pool
- IAM

Conflict detection (required for DataStore)
- Conflict resolution strategy: Auto Merge

? Select a setting to edit Authorization modes
? Choose the default authorization type for the API Amazon Cognito User Pool
Use a Cognito user pool configured as a part of this project.
? Configure additional auth types? Yes
? Choose the additional authorization types you want to configure for the API API key, IAM
API key configuration
√ Enter a description for the API key: · No desc
√ After how many days from now the API key should expire (1-365): · 5
🛑 Syntax Error: Expected ":", found "@".

**Comment by chirpavel** [comment]
**amplify pull shows this error several times:**

amplify pull --appId d2bXXXX --envName staging

Pre-pull status:

    Current Environment: staging

┌──────────┬──────────────────────────────┬───────────┬───────────────────┐
│ Category │ Resource name                │ Operation │ Provider plugin   │
├──────────┼──────────────────────────────┼───────────┼───────────────────┤
│ Api      │ SplitPay                     │ Update    │ awscloudformation │
├──────────┼──────────────────────────────┼───────────┼───────────────────┤
│ Function │ ChangeSubscriptionPlanLambda │ Update    │ awscloudformation │
├──────────┼──────────────────────────────┼───────────┼───────────────────┤
│ Auth     │ SplitPay                     │ No Change │ awscloudformation │
├──────────┼──────────────────────────────┼───────────┼───────────────────┤
│ Function │ CognitoSignupTriggerLambda   │ No Change │ awscloudformation │
├──────────┼──────────────────────────────┼───────────┼───────────────────┤
│ Function │ RMSIikoGetMenuLambda         │ No Change │ awscloudformation │
├──────────┼──────────────────────────────┼───────────┼───────────────────┤
│ Storage  │ s3splitpaystoragestaging     │ No Change │ awscloudformation │
└──────────┴──────────────────────────────┴───────────┴───────────────────┘

⚠️ Local changes detected.
⚠️ Pulling changes from the cloud will override your local changes.
? Are you sure you would like to continue? Yes
√ Successfully pulled backend environment staging from the cloud.
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
✅ 
GraphQLError: Syntax Error: Expected ":", found "@".
× Failed to sync the following components: MenuItemCreateForm, UserProfileUpdateForm, MenuItemSizeUpdateForm, MenuItemSizeCreateForm, BranchPublicInfoUpdateForm, MenuGroupUpdateForm, MenuGroupCreateForm, BranchOperatingHoursUpdateForm, MenuItemUpdateForm
GraphQLError: Syntax Error: Expected ":", found "@".
🛑 Syntax Error: Expected ":", found "@".

Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

Session Identifier: 6e0a7efe-dd6c-4c5a-92c2-2a7ab3433804

✅ Report saved: C:\Users\chirp\AppData\Local\Temp\SplitPay\report-1721513470733.zip

√ Done

Project Identifier: 70952c35bc147986b145b568d0636b2e

**Comment by chirpavel** [comment]
![image](https://github.com/user-attachments/assets/ccae347a-f0e3-4126-ab7c-9bd8b38cf8c3)

**Comment by chirpavel** [comment]
![data-manager-screenshot 2024-07-21 144238](https://github.com/user-attachments/assets/67f8e5f4-f15c-42de-a9c3-c9d36867956d)
At this step AWS sends model with mistake (after decoding):
```
type SubscriptionPlan @model 
  @auth(
    rules: [
      {allow: private, provider: iam, operations: [read, create, update]},
      {allow: groups, groups: ["eu-central-admins"], operations: [read, create, update, delete]}
    ]
  ) {
  id: ID!
  branchId: ID!
  prevSubscriptionPlan: String
  subscriptionPlan: String
  price: Float
  paidAmount: Float
  isFake: Boolean
  duration: Int
  convertedDays: Int
  extraDays: Int
  expiryDate: AWSDateTime
  detailsSnapshot: String
  autoRenewal: Boolean
  owner: String
  type: String!
  String @default(value: "SP")
  @index(
    name: "subscriptionPlansByDate"
    queryField: "subscriptionPlansByDate"
    sortKeyFields: ["createdAt"]
  )
  createdAt: String!
}
```

Mistake is here:
**String @default(value: "SP")**

**Comment by ykethan** [comment]
Hey,👋 thanks for raising this! I'm going to transfer this over to our API repository for better assistance.

But to mitigate the issue you will need to download the `current-cloud-backend.zip` from the Amplify S3 deployment bucket, update the schema and carefully re-upload zip. 
Then running the pull locally should build the schema.
