### ISSUE TITLE
An error occurred during the push operation: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by Paulo-Ferreira-SJ** [aws-amplify/amplify-cli#13981]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

18.17.1

### Amplify CLI Version

@aws-amplify/cli@12.13.0

### What operating system are you using?

Ubuntu

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

I received the message: Cannot read properties of undefined (reading 'length')

### Expected behavior

Deploy the amplify app

### Reproduction steps

amplify push

### Log output

<details>

```
# Put your logs below this line
On branch staging
Your branch is up to date with 'origin/staging'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   amplify/README.md
	modified:   amplify/backend/backend-config.json
	modified:   amplify/backend/types/amplify-dependent-resources-ref.d.ts
	modified:   amplify/cli.json
	modified:   amplify/team-provider-info.json

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	amplify/hooks/

no changes added to commit (use "git add" and/or "git commit -a")
Please note that certain attributes may not be overwritten if you choose to use defaults settings.

You have configured resources that might depend on this Cognito resource.  Updating this Cognito resource could have unintended side effects.

Using service: Cognito, provided by: awscloudformation
 What do you want to do? (Use arrow keys)
❯ Apply default configuration without Social Provider (Federation) 
  Apply default configuration with Social Provider (Federation) 
  Walkthrough all the auth configurations 
  Create or update Cognito user pool groups 
  Create or update Admin queries API 
- Fetching updates to backend environment: staging from the cloud.
- Building resource api/ApiSalesJourney
- Building resource auth/salesjourneybackendbc6d5592
- Building resource storage/salesjourney
✔ Successfully pulled backend environment staging from the cloud.
- Building resource api/ApiSalesJourney
- Building resource auth/salesjourneybackendbc6d5592
- Building resource storage/salesjourney

    Current Environment: staging
    
┌──────────┬──────────────────────────────────────────┬───────────┬───────────────────┐
│ Category │ Resource name                            │ Operation │ Provider plugin   │
├──────────┼──────────────────────────────────────────┼───────────┼───────────────────┤
│ Api      │ ApiSalesJourney                          │ Update    │ awscloudformation │
├──────────┼──────────────────────────────────────────┼───────────┼───────────────────┤
│ Auth     │ salesjourneybackendbc6d5592              │ Update    │ awscloudformation │
├──────────┼──────────────────────────────────────────┼───────────┼───────────────────┤
│ Function │ accessHierarchies                        │ Update    │ awscloudformation │
├──────────┼──────────────────────────────────────────┼───────────┼───────────────────┤
│ Function │ accounts                                 │ Update    │ awscloudformation │
├──────────┼──────────────────────────────────────────┼───────────┼───────────────────┤
│ Function │ blockingObjects                          │ Update    │ awscloudformation │
├──────────┼──────────────────────────────────────────┼───────────┼───────────────────┤
│ Function │ customFields                             │ Update    │ awscloudformation │
├──────────┼──────────────────────────────────────────┼───────────┼───────────────────┤
│ Function │ customers                                │ Update    │ awscloudformation │
├──────────┼──────────────────────────────────────────┼───────────┼───────────────────┤
│ Function │ domains                                  │ Update    │ awscloudformation │
├──────────┼──────────────────────────────────────────┼───────────┼───────────────────┤
│ Function │ dynamicMargins                           │ Update    │ awscloudformation │
├──────────┼──────────────────────────────────────────┼───────────┼───────────────────┤
│ Function │ forkData                                 │ Update    │ awscloudformation │
├──────────┼──────────────────────────────────────────┼───────────┼───────────────────┤
│ Function │ generatePdf                              │ Update    │ awscloudformation │
├──────────┼──────────────────────────────────────────┼───────────┼───────────────────┤
│ Function │ governance                               │ Update    │ awscloudformation │
├──────────┼──────────────────────────────────────────┼───────────┼───────────────────┤
│ Function │ health                                   │ Update    │ awscloudformation │
├──────────┼──────────────────────────────────────────┼───────────┼───────────────────┤
│ Function │ integrations                             │ Update    │ awscloudformation │
├──────────┼──────────────────────────────────────────┼───────────┼───────────────────┤
│ Function │ leads                                    │ Update    │ awscloudformation │
├──────────┼──────────────────────────────────────────┼───────────┼───────────────────┤
│ Function │ notifications                            │ Update    │ awscloudformation │
├──────────┼──────────────────────────────────────────┼───────────┼───────────────────┤
│ Function │ paymentConditions                        │ Update    │ awscloudformation │
├──────────┼──────────────────────────────────────────┼───────────┼───────────────────┤
│ Function │ paymentMethods                           │ Update    │ awscloudformation │
├──────────┼──────────────────────────────────────────┼───────────┼───────────────────┤
│ Function │ plants                                   │ Update    │ awscloudformation │
├──────────┼──────────────────────────────────────────┼───────────┼───────────────────┤
│ Function │ pricing                                  │ Update    │ awscloudformation │
├──────────┼──────────────────────────────────────────┼───────────┼───────────────────┤
│ Function │ products                                 │ Update    │ awscloudformation │
├──────────┼──────────────────────────────────────────┼───────────┼───────────────────┤
│ Function │ public                                   │ Update    │ awscloudformation │
├──────────┼──────────────────────────────────────────┼───────────┼───────────────────┤
│ Function │ pushNotificationsTrigger                 │ Update    │ awscloudformation │
├──────────┼──────────────────────────────────────────┼───────────┼───────────────────┤
│ Function │ reports                                  │ Update    │ awscloudformation │
├──────────┼──────────────────────────────────────────┼───────────┼───────────────────┤
│ Function │ saleOrders                               │ Update    │ awscloudformation │
├──────────┼──────────────────────────────────────────┼───────────┼───────────────────┤
│ Function │ salesjourneybackendbc6d5592CustomMessage │ Update    │ awscloudformation │
├──────────┼──────────────────────────────────────────┼───────────┼───────────────────┤
│ Function │ scheduledEmails                          │ Update    │ awscloudformation │
├──────────┼──────────────────────────────────────────┼───────────┼───────────────────┤
│ Function │ squads                                   │ Update    │ awscloudformation │
├──────────┼──────────────────────────────────────────┼───────────┼───────────────────┤
│ Function │ stocks                                   │ Update    │ awscloudformation │
├──────────┼──────────────────────────────────────────┼───────────┼───────────────────┤
│ Function │ support                                  │ Update    │ awscloudformation │
├──────────┼──────────────────────────────────────────┼───────────┼───────────────────┤
│ Function │ users                                    │ Update    │ awscloudformation │
├──────────┼──────────────────────────────────────────┼───────────┼───────────────────┤
│ Function │ webhooks                                 │ Update    │ awscloudformation │
├──────────┼──────────────────────────────────────────┼───────────┼───────────────────┤
│ Storage  │ salesjourney                             │ Update    │ awscloudformation │
└──────────┴──────────────────────────────────────────┴───────────┴───────────────────┘
🛑 Cannot read properties of undefined (reading 'length')

Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

Session Identifier: 290b8a44-fd38-4bc0-b5ee-cdbeb1eb4c4b

```

</details>

### Additional information

Session Identifier: 290b8a44-fd38-4bc0-b5ee-cdbeb1eb4c4b

After consulting other issues, in a similar unresolved problem, there was a suggestion to use version 14.x of Node. I tested it, and the same error occurred.

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @Paulo-Ferreira-SJ, could you try adding `--debug` to the amplify command and provide us the output on CLI?

**Comment by Paulo-Ferreira-SJ** [comment]
Hi @ykethan! 
Sorry for the delay in responding; I just managed to execute it a little while ago. Here is the log running the command with --debug :

Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/
DeploymentFault: Cannot read properties of undefined (reading 'length')
    at Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/push-resources.js:362:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/push-resources.js:137:16
    at async Promise.all (index 0)
    at async providersPush (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/push-resources.js:133:5)
    at async AmplifyToolkit.pushResources (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/push-resources.js:107:13)
    at async Object.executeAmplifyCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:194:9)
    at async executePluginModuleCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:139:5)
    at async executeCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:37:9)
    at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:121:5)
Cannot read properties of undefined (reading 'length')
TypeError: Cannot read properties of undefined (reading 'length')
    at /snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/utils/consolidate-apigw-policies.js:139:83
    at Array.forEach (<anonymous>)
    at ApiGatewayAuthStack.createPoliciesFromResources (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/utils/consolidate-apigw-policies.js:138:13)
    at /snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/utils/consolidate-apigw-policies.js:100:16
    at Array.forEach (<anonymous>)
    at /snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/utils/consolidate-apigw-policies.js:89:44
    at Array.forEach (<anonymous>)
    at new ApiGatewayAuthStack (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/utils/consolidate-apigw-policies.js:72:23)
    at createApiGatewayAuthResources (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/utils/consolidate-apigw-policies.js:217:17)
    at consolidateApiGatewayPolicies (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/utils/consolidate-apigw-policies.js:193:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async createEnvLevelConstructs (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/utils/env-level-constructs.js:61:95)
    at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/push-resources.js:133:5)
    at async /snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/push-resources.js:137:16
    at async Promise.all (index 0)
    at async providersPush (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/push-resources.js:133:5)
    at async AmplifyToolkit.pushResources (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/push-resources.js:107:13)
    at async Object.executeAmplifyCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:194:9)
    at async executePluginModuleCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:139:5)
    at async executeCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:37:9)
    at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:121:5)

**Comment by ykethan** [comment]
Hey @Paulo-Ferreira-SJ, thank you for the information. From the stack trace, it appears the error occurred on a API gateway resource.
https://github.com/aws-amplify/amplify-cli/blob/265726ddb0f4d99dcbde60d315df85bf34c791a4/packages/amplify-provider-awscloudformation/src/utils/consolidate-apigw-policies.ts#L157

From the stack trace it appears there are several updates on resources including a API resource. Could you let us know the changes made on the resource or any reproduction steps to reproduce the issue.

**Comment by Paulo-Ferreira-SJ** [comment]
Hey @ykethan. I'm updating my AWS amplify functions Lambda from using aws-sdk v2 to v3. There are really many changes. But from the stack trace, I couldn't identify what is wrong. Could you tell me which file it is trying to read and extract these parameters from?

**Comment by ykethan** [comment]
Hey @Paulo-Ferreira-SJ,  I would suggest running `amplify update api` and selecting the existing options to check if the error is mitigated. 
additionally, you could try verifying the changes made in the files under `amplify/api/<rest-api-name>` folder.
