### ISSUE TITLE
amplify api add-graphql-datasource ⠸ Fetching Aurora Serverless cluster...BadRequestException: This API is deprecated and not available. Use ExecuteStatement API instead

### ISSUE THREAD

**Issue by oste** [aws-amplify/amplify-cli#1403]
**Describe the bug**
Running `amplify api add-graphql-datasource` gives this fatal error

Full stack trace:
```
at Object.extractError (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.extractError (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12)
There was an error adding the datasource
⠧ Fetching Aurora Serverless cluster...
```

It continues to fetch aurora serverless cluster indefinitely.

**To Reproduce**
Follow steps here https://aws-amplify.github.io/docs/cli/graphql#automatically-import-existing-datasources

```
❯ amplify api add-graphql-datasource
Using datasource: Aurora Serverless, provided by: awscloudformation
? Provide the region in which your cluster is located: us-east-1
? Select the Aurora Serverless cluster that will be used as the data source for your API: amplify-serverless-cluster
```

Pressing enter gives the result and stacktrace shown above

**Expected behavior**
Aurora database added successfully.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: n/a
 - Version: n/a

**Comment by UnleashedMind** [comment]
@oste 
We've identified the cause of this bug, and we are working with the internal teams to resolve it.

**Comment by ashwindevendran** [comment]
Hi, we have worked with the internal teams to resolve this. You should no longer be running into this issue. Feel free to re-open if it persists.

**Comment by tylernevell** [comment]
I am running into the same EXACT issue. Only issue is... 
`BadRequestException: Access denied for user 'admin'@'10.1.3.186' (using password: YES)`
At the top of the stacktrace. I've googled this issue and cannot seem to find what the issue is. I've checked permissions for all IAM users that I've tried using this for. Data API is enabled for my Aurora Serverless DB as well.
