### ISSUE TITLE
Crash caused by `amplify push` of API

### ISSUE THREAD

**Issue by plaa** [aws-amplify/amplify-cli#1408]
**Describe the bug**
I added the following to schema.graphql (I was trying to investigate how bidirectional one-to-one connections worked):

```
type ModelA @model {
  b: ModelB @connection(name:"NameAB", keyField: "ab")
}
type ModelB @model {
  a: ModelA @connection(name:"NameAB", keyField: "ab")
}
```

In this case `amplify api gql-compile` is successful, but `amplify push` crashes:

```
⠴ Updating resources in the cloud. This may take a few minutes...⠋ Generating GraphQL operations2019-05-07T10:56:46.954Z - error: uncaughtException: Syntax Error: Expected Name, found ( (6:7)
  4 |   )
  5 | {
> 6 |       (
    |       ^
  7 |       id:$id
  8 |   )
  9 |   date=Tue May 07 2019 13:56:46 GMT+0300 (Eastern European Summer Time), pid=29392, uid=501, gid=20, cwd=/Users/vincit/workspace/xyzzy, execPath=/usr/local/Cellar/node/11.13.0/bin/node, version=v11.13.0, argv=[/usr/local/Cellar/node/11.13.0/bin/node, /usr/local/bin/amplify, push, -y], rss=115417088, heapTotal=83701760, heapUsed=70310848, external=1650796, loadavg=[1.86865234375, 2.158203125, 2.5087890625], uptime=2477095, trace=[column=431, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/prettier/parser-graphql.js, function=n, line=1, method=null, native=false, column=35727, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/prettier/parser-graphql.js, function=Object.parse, line=1, method=parse, native=false, column=19, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/prettier/index.js, function=Object.parse$2 [as parse], line=10639, method=parse$2 [as parse], native=false, column=23, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/prettier/index.js, function=coreFormat, line=13856, method=null, native=false, column=73, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/prettier/index.js, function=format, line=14115, method=null, native=false, column=12, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/prettier/index.js, function=formatWithCursor, line=14131, method=null, native=false, column=15, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/prettier/index.js, function=null, line=42399, method=null, native=false, column=12, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/prettier/index.js, function=Object.format, line=42418, method=format, native=false, column=19, file=/home/circleci/repo/packages/amplify-graphql-docs-generator/src/index.ts, function=format, line=131, method=null, native=false, column=12, file=/home/circleci/repo/packages/amplify-graphql-docs-generator/src/index.ts, function=null, line=117, method=null, native=false], stack=[SyntaxError: Syntax Error: Expected Name, found ( (6:7),   4 |   ),   5 | {, > 6 |       (,     |       ^,   7 |       id:$id,   8 |   ),   9 |  ,     at n (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/prettier/parser-graphql.js:1:431),     at Object.parse (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/prettier/parser-graphql.js:1:35727),     at Object.parse$2 [as parse] (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/prettier/index.js:10639:19),     at coreFormat (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/prettier/index.js:13856:23),     at format (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/prettier/index.js:14115:73),     at formatWithCursor (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/prettier/index.js:14131:12),     at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/prettier/index.js:42399:15,     at Object.format (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/prettier/index.js:42418:12),     at format (/home/circleci/repo/packages/amplify-graphql-docs-generator/src/index.ts:131:19),     at Object.<anonymous> (/home/circleci/repo/packages/amplify-graphql-docs-generator/src/index.ts:117:12)]
```

I can't find any file containing `id:$id` so I assume it's an in-memory document. I'm not sure whether the rest of the schema.graphql has impact on this occurring.

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - amplify-cli 1.6.7

**Comment by vparpoil** [comment]
Try to add an Id field to your models, I think it is mandatory, specially when you have `@connection`, because the ID will be use to link data : 
```
type ModelA @model {
  id: ID!
  b: ModelB @connection(name:"NameAB", keyField: "ab")
}
type ModelB @model {
  id: ID!
  a: ModelA @connection(name:"NameAB", keyField: "ab")
}
```
I'm also unsure of your use of the keyField parameter. If you have other errors, you can try to remove it.

**Comment by kaustavghosh06** [comment]
Thanks @vparpoil. I think that should solve the issue @plaa. Please re-open the issue if you're still seeing this issue.

**Comment by plaa** [comment]
Even if that's the issue Amplify shouldn't crash and become out-of-sync with the cloud version.
