### ISSUE TITLE
Error "Cannot read property 'accessKeyId' of undefined" with configLevel general

### ISSUE THREAD

**Issue by chris-merapar** [aws-amplify/amplify-cli#1424]
**Describe the bug**
When amplify publish is run in a headless CodeBuild environment with configLevel=general, it fails with the error:

`frontend build command exited with code 0 
2019-05-07T14:42:41.575Z - error: uncaughtException: Cannot read property 'accessKeyId' of undefined date=Tue May 07 2019 14:42:41 GMT+0000 (Coordinated Universal Time), pid=132, uid=0, gid=0, cwd=/codebuild/output/src781019302/src, execPath=/usr/local/bin/node, version=v10.14.1, argv=[/usr/local/bin/node, /usr/local/bin/amplify, publish, --yes, --codegen, {"generateCode":true,"codeLanguage":"javascript","fileNamePattern":"src/graphql/**/*.js","generatedFileName":"API","generateDocs":true}, -c], rss=98869248, heapTotal=70103040, heapUsed=54395864, external=1861408, loadavg=[2.6982421875, 1.9453125, 1.49267578125], uptime=2416, trace=[column=17, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js, function=Config.extractCredentials, line=537, method=extractCredentials, native=false, column=20, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js, function=Config.update, line=416, method=update, native=false, column=14, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/aws-utils/aws.js, function=Object.aws.configureWithCreds, line=7, method=configureWithCreds, native=false, column=7, file=internal/process/next_tick.js, function=process._tickCallback, line=68, method=_tickCallback, native=false], stack=[TypeError: Cannot read property 'accessKeyId' of undefined,     at Config.extractCredentials (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js:537:17),     at Config.update (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js:416:20),     at Object.aws.configureWithCreds (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/aws-utils/aws.js:7:14),     at process._tickCallback (internal/process/next_tick.js:68:7)] 
Tue May  7 14:42:41 UTC 2019 ERROR Could not publish amplify project (status 1) `

**To Reproduce**
Steps to reproduce the behaviour:
1. Use CodeBuild image aws/codebuild/nodejs:10.14.1
2. Install amplify CLI 1.6.7
3. Run amplify init (without --yes option)
4. Run amplify publish
5. Backend changes are pushed but the publish fails after the frontend build

I have tried this with the following variations:
1. Using configLevel = general, so the ECS instance role is used
2. Using configLevel = project and providing a named profile as follows

AMPLIFY="{\
\"envName\":\"${envName}\",\
\"defaultEditor\":\"code\"\
}"
`AWSCLOUDFORMATIONCONFIG="{\
\"configLevel\":\"project\",\
\"useProfile\":true,\
\"profileName\":\"amplify\"\
}"
PROVIDERS="{\
\"awscloudformation\":$AWSCLOUDFORMATIONCONFIG\
}"
CODEGEN="{\
\"generateCode\":true,\
\"codeLanguage\":\"javascript\",\
\"fileNamePattern\":\"src/graphql/**/*.js\",\
\"generatedFileName\":\"API\",\
\"generateDocs\":true\
}"

amplify init --amplify $AMPLIFY --providers $PROVIDERS
amplify publish --yes --codegen $CODEGEN -c
`

Where the profile is created as follows:
`
echo "[profile amplify]" >> ~/.aws/config
echo "region=eu-west-1" >> ~/.aws/config
echo "credential_source = EcsContainer" >> ~/.aws/config
`
The publish works ok when using the named profile.

**Expected behaviour**
The publish command should complete without errors when using configLevel=general.

**Comment by johnford2002** [comment]
Encountered this same error yesterday with our init scripts setting the configLevel to general. 

I believe one part of the problem lies at this line in that no config is returned if level isn't set to project:
https://github.com/aws-amplify/amplify-cli/blame/master/packages/amplify-provider-awscloudformation/lib/configuration-manager.js#L508

**Comment by kaustavghosh06** [comment]
We’ve identified the issue and working on the fix. I believe there’s a PR out for this.

**Comment by kaustavghosh06** [comment]
@chris-merapar Can you test this with v 1.6.8? I wasn't able to reproduce this issue with the latest version of the CLI. Also, are you getting the same error when you use project level onfig isntead of default?
