### ISSUE TITLE
Accidently removed amplify's s3 deployment bucket :-( What can I do?

### ISSUE THREAD

**Issue by sakhmedbayev** [aws-amplify/amplify-cli#1441]
** Which Category is your question related to? **
deployment

** What AWS Services are you utilizing? **
S3

** Provide additional details e.g. code snippets **
While searching for a solution for another issue I accidentally removed S3 deployment bucket which amplify uses to deploy resources. 

Is there any way I can initialize it again? If not, what are my options?

I have both `dev` and `prod` env's. I deleted deployment buckets for both of them. I really do not care about `dev` env but `prod` env has live databases. 

Thanks in advance for any help!

**Comment by kstro21** [comment]
Hi, @sakhmedbayev, I've been there too. What I did was to create a bucket with the same name.

1. Open `amplify\backend\amplify-meta.json` and look for the value of `"DeploymentBucketName"`
2. Create a bucket in S3 with the value of `"DeploymentBucketName"`
3. Deploy

It works for me, hope for you too.

**Comment by sakhmedbayev** [comment]
Thank you @kstro21!

**Comment by MontoyaAndres** [comment]
I did the same, but I got this error :(

````
 Fetching updates to backend environment: dev from the cloud.(node:11025) UnhandledPromiseRejectionWarning: NoSuchKey: The specified key does not exist.
    at Request.extractError (/home/andres/.nvm/versions/node/v13.11.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/services/s3.js:835:35)
    at Request.callListeners (/home/andres/.nvm/versions/node/v13.11.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/andres/.nvm/versions/node/v13.11.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/andres/.nvm/versions/node/v13.11.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/andres/.nvm/versions/node/v13.11.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/andres/.nvm/versions/node/v13.11.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/andres/.nvm/versions/node/v13.11.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/andres/.nvm/versions/node/v13.11.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/andres/.nvm/versions/node/v13.11.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/andres/.nvm/versions/node/v13.11.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
(node:11025) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11025) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠏ Fetching updates to backend environment: dev from the cloud.
```

**Comment by Serachebhor** [comment]
#- **s4******$@************@

**Comment by mburgjr** [comment]
I had this same issue and followed the above instructions. However, now when I try to run "amplify push/pull", I'm getting the error:

"✖ There was an error pulling the backend environment dev.
An error occurred during the push operation: The specified key does not exist."

Do I need to place something into the deployment bucket after I make it?

I just made an empty S3 bucket with the name that matched the "DeploymentBucketName" and then tried to push and pull directly after that. Not sure if I missed a step. Please help I am very stuck
