### ISSUE TITLE
amplify publish fails with configLevel general

### ISSUE THREAD

**Issue by johnford2002** [aws-amplify/amplify-cli#1455]
**Describe the bug**
When using the CLI for headless publish on an AWS CodeBuild container, publish fails with the following error:

```
2019-05-15T13:21:43.747Z - error: uncaughtException: Cannot read property 'accessKeyId' of undefined date=Wed May 15 2019 13:21:43 GMT+0000 (Coordinated Universal Time), pid=381, uid=0, gid=0, cwd=/codebuild/output/src404694579/src, execPath=/usr/local/bin/node, version=v10.14.1, argv=[/usr/local/bin/node, /usr/local/bin/amplify, publish, --codegen, {"generateCode":true,"codeLanguage":"javascript","fileNamePattern":"src/**/*.js","generatedFileName":"API","generateDocs":true}, --invalidateCloudFront, --yes], rss=99631104, heapTotal=72052736, heapUsed=56939880, external=702214, loadavg=[1.05712890625, 0.4697265625, 0.19482421875], uptime=3105, trace=[column=17, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js, function=Config.extractCredentials, line=537, method=extractCredentials, native=false, column=20, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js, function=Config.update, line=416, method=update, native=false, column=14, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/aws-utils/aws.js, function=Object.aws.configureWithCreds, line=7, method=configureWithCreds, native=false, column=7, file=internal/process/next_tick.js, function=process._tickCallback, line=68, method=_tickCallback, native=false], stack=[TypeError: Cannot read property 'accessKeyId' of undefined,     at Config.extractCredentials (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js:537:17),     at Config.update (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js:416:20),     at Object.aws.configureWithCreds (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/aws-utils/aws.js:7:14),     at process._tickCallback (internal/process/next_tick.js:68:7)] 
```

CodeBuild is using an IAM role that has the required permissions, and this process was working until recently.

**To Reproduce**
Init script run first in CodeBuild:
```
AWSCLOUDFORMATIONCONFIG="{\
\"configLevel\":\"general\"\
}"

AMPLIFY="{\
\"envName\":\"$ENVIRONMENT\"\
}"
PROVIDERS="{\
\"awscloudformation\":$AWSCLOUDFORMATIONCONFIG\
}"

amplify init \
--amplify $AMPLIFY \
--providers $PROVIDERS \
--categories $CATEGORIES \
--yes
```

Publish script run after:
```
CODEGEN="{\
\"generateCode\":true,\
\"codeLanguage\":\"javascript\",\
\"fileNamePattern\":\"src/**/*.js\",\
\"generatedFileName\":\"API\",\
\"generateDocs\":true\
}"

amplify publish \
--codegen $CODEGEN \
--invalidateCloudFront \
--yes
```

**Expected behavior**
Publish should complete successfully.

**Version Info:**
 - amplify-cli @ 1.6.8
 - node @ 10.14
 - aws-sdk @ 1.16.69

**Additional context**
Previously commented on another issue that was similar, but that fix didn't seem to fix this problem:
https://github.com/aws-amplify/amplify-cli/issues/1424

**Comment by johnford2002** [comment]
I still believe the issue lies with this code not having a return if configLevel isn't set to 'project':
https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-provider-awscloudformation/lib/configuration-manager.js#L506

**Comment by YatesSpearman** [comment]
Following: I'm having the same issue with my project

**Comment by kaustavghosh06** [comment]
@johnford2002 We submitted a fix for it but  the version is not published to NPM. Did you fork the repo and try it out?

**Comment by johnford2002** [comment]
@kaustavghosh06 - can you point me to the fix? It doesn't appear to be in master. I was able to get past our issue for the moment by patching the area I linked above and returning just an empty object. I'll admit though that I'm not sure if that would fully solve the problem for use cases outside my own.

**Comment by johnford2002** [comment]
Found it here:
https://github.com/aws-amplify/amplify-cli/commit/0c2e2d18748b31ccb3e98a1b6cbbde41d653314d

You took the approach of handling it by not calling the underlying AWS method if there wasn't a config returned. I'm reasonably confident that would have also addressed the issue, but I still dislike having an async method return undefined. Personal preference though, so no real complaint from me.

Is there a timeline for release of that fix? Further, is there anything in the works to lock the dependencies of the CLI?

**Comment by kaustavghosh06** [comment]
@johnford2002 Can you please install the latest version of the CLI? This should fix this issue. @bokuweb  confirmed that this change fixed his problem.
