### ISSUE TITLE
ZlibError: zlib: unexpected end of file

### ISSUE THREAD

**Issue by kashifmehmood9** [aws-amplify/amplify-cli#147]
i am running this command npm install -g @aws-amplify/cli to install amplify but its giving me the following error
please guide MACOS High Sierra
node version 10.10.0 npm version 6.4.1

ZlibError: zlib: unexpected end of file
npm verb stack     at Zlib.(anonymous function).onerror (/usr/local/lib/node_modules/npm/node_modules/minizlib/index.js:131:21)
npm verb stack     at Unzip.write (/usr/local/lib/node_modules/npm/node_modules/minizlib/index.js:255:31)
npm verb stack     at Unzip.flush (/usr/local/lib/node_modules/npm/node_modules/minizlib/index.js:222:10)
npm verb stack     at Unzip.end (/usr/local/lib/node_modules/npm/node_modules/minizlib/index.js:229:10)
npm verb stack     at Object.end (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:415:21)
npm verb stack     at PassThrough.onend (_stream_readable.js:628:10)
npm verb stack     at Object.onceWrapper (events.js:273:13)
npm verb stack     at PassThrough.emit (events.js:187:15)
npm verb stack     at endReadableNT (_stream_readable.js:1092:12)
npm verb stack     at process._tickCallback (internal/process/next_tick.js:63:19)
npm verb cwd /
npm verb Darwin 17.7.0
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "@aws-amplify/cli" "-verbose"
npm verb node v10.10.0
npm verb npm  v6.4.1
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5
npm ERR! zlib: unexpected end of file
npm verb exit [ -5, true ]
npm timing npm Completed in 161828ms

**Comment by kashifmehmood9** [comment]
solved it by clearing cache of npm
