### ISSUE TITLE
amplify add api requires "Provide a custom type name"

### ISSUE THREAD

**Issue by oste** [aws-amplify/amplify-cli#1527]
**Describe the bug**
When using the `amplify add api` command it asks for `Provide a custom type name`. This is not always necessary. I immediately followed up with `amplify api add-graphql-datasource` to add a aurora serverless data source. This results in unnecessary Dynamo db tables being created and extra schema added.

**Expected behavior**
Option to skip Dynamo table creation.

**Comment by kaustavghosh06** [comment]
@oste You can get rid of the type generated when editing the schema before pushing. That would make sure that a table is not generated.

**Comment by oste** [comment]
@kaustavghosh06 I actually tried this before running `amplify api add-graphql-datasource` and was given this error

```GraphQLError: Syntax Error: Unexpected <EOF>
    at syntaxError (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/error/syntaxError.js:24:10)
    at unexpected (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/language/parser.js:1322:33)
    at parseDefinition (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/language/parser.js:152:9)
    at parseDocument (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/language/parser.js:110:22)
    at Object.parse (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/language/parser.js:38:10)
    at datasourceSelectionPrompt.then.then.then (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/commands/api/add-datasource.js:111:46)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
There was an error adding the datasource```

Will try to do that after adding the aurora data source. Thanks!

**Comment by Collin-St** [comment]
I am also running into this bug. I am attempting to add an existing aurora-serverless datasource with the `amplify api add-graphql-datasource` command. I am given this error, similar to above:

`GraphQLError: Syntax Error: Unexpected <EOF>
    at syntaxError (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/error/syntaxError.js:24:10)
    at unexpected (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/language/parser.js:1322:33)
    at parseDefinition (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/language/parser.js:152:9)
    at parseDocument (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/language/parser.js:110:22)
    at Object.parse (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/language/parser.js:38:10)
    at datasourceSelectionPrompt.then.then.then (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/commands/api/add-datasource.js:108:46)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
`
