### ISSUE TITLE
amplify status TypeError: Cannot read property 'lastPushTimeStamp' of undefined

### ISSUE THREAD

**Issue by kl5331** [aws-amplify/amplify-cli#1606]
**Describe the bug**
Receives "TypeError: Cannot read property 'lastPushTimeStamp' of undefined" when trying to call "amplify status" or "amplify push".

**To Reproduce**
1. Uninstalled entire node and npm environment first, hoping that would resolve the issue.
2. npm install -g @aws-amplify/cli
3. Checked Version to confirm @aws-amplify/cli@1.7.1
4. amplify configure
5. amplify init
6. amplify status or amplify push 
7. 
TypeError: Cannot read property 'lastPushTimeStamp' of undefined
    at getResourcesToBeCreated (C:\Users\****\AppData\Roaming\npm\node_modules\@aws-amplify\cli\src\extensions\amplify-helpers\resource-status.js:120:69)
    at getResourceStatus (C:\Users\****\AppData\Roaming\npm\node_modules\@aws-amplify\cli\src\extensions\amplify-helpers\resource-status.js:213:30)
    at Object.showResourceTable (C:\Users\****\AppData\Roaming\npm\node_modules\@aws-amplify\cli\src\extensions\amplify-helpers\resource-status.js:269:13)
    at Command.run (C:\Users\****\AppData\Roaming\npm\node_modules\@aws-amplify\cli\src\commands\status.js:5:27)
    at Runtime.<anonymous> (C:\Users\****\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\gluegun\build\runtime\run.js:90:58)
    at step (C:\Users\****\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\gluegun\build\runtime\run.js:32:23)
    at Object.next (C:\Users\****\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\gluegun\build\runtime\run.js:13:53)
    at C:\Users\****\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\gluegun\build\runtime\run.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\****\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\gluegun\build\runtime\run.js:3:12)

**Expected behavior**
Amplify status would allow me to see changes and push allows me to push. From both machines flawlessly. Currently am unable to test on my desktop. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit
 - Browser: Chrome

**Additional context**
I  use a desktop and laptop for this project. They have two different access account and I utilize CodeCommit between them.

**Comment by kl5331** [comment]
Update: I think... I fixed it. I managed to find my way to the amplify-meta.json file and noticed that some functions and a table were missing the timestamp. I also didn't need them anymore so I deleted from the file correctly. Everything is working so far!
