### ISSUE TITLE
Unable to add interactions to a sample aws sdk android app (LexSample)

### ISSUE THREAD

**Issue by satishlokkoju** [aws-amplify/amplify-cli#1621]
**Describe the bug**
I was trying to run sample LexSample.

- amplify init   *works*
- amplify add interactions *throws up the below error*

Using service: Lex, provided by: awscloudformation
Adding interactions would also add the Auth category to the project if not already added.
Successfully updated auth resource locally.

Welcome to the Amazon Lex chatbot wizard
You will be asked a series of questions to help determine how to best construct your chatbot.

? Provide a friendly resource name that will be used to label this category in the project: lex0a2d8e3e
? Would you like to start with a sample chatbot, import a chatbot, or start from scratch? Start with a sample
? Choose a sample chatbot: BookTrip
? Please indicate if your use of this bot is subject to the Children's Online Privacy Protection Act (COPPA).
Learn more: https://www.ftc.gov/tips-advice/business-center/guidance/complying-coppa-frequently-asked-questions No
TypeError: Cannot read property 'dependsOn' of undefined
    at Object.updateamplifyMetaAfterResourceAdd (/usr/local/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/update-amplify-meta.js:76:15)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-interactions/provider-utils/awscloudformation/index.js:85:23
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
There was an error adding the interactions resource

**To Reproduce**
1. root directory of LexSample
2. run 'amplify add interactions'

Using a MacBook Pro

**Comment by Kitemaker** [comment]
I am getting following error while trying to add interactions 
TypeError: Cannot read property 'dependsOn' of undefined
    at Object.updateamplifyMetaAfterResourceAdd (C:\<path>\AppData\Roaming\npm\node_modules\@aws-amplify\cli\src\extensions\amplify-helpers\update-amplify-meta.js:76:15)
    at addWalkthrough.then (C:\Users\Saleem\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-category-interactions\provider-utils\awscloudformation\index.js:85:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
There was an error adding the interactions resource

**Comment by yuth** [comment]
Fix has been released in @aws-amplify/cli@1.7.3
