### ISSUE TITLE
I encounterd 'SyntaxError: Upexpected token export' when I executed 'amplify env add'

### ISSUE THREAD

**Issue by yukitaka13-1110** [aws-amplify/amplify-cli#1623]
I encounterd this error suddenly.

It occurred after adding api( `amplify api add `).
Is this my fault ?
How shuld I do ?

```
✔ Successfully created initial AWS cloud resources for deployments.
✔ Initialized provider successfully.
✖ There was an error initializing your environment.
init failed
/Users/*path to project*/src/aws-exports.js:15
export default awsmobile
^^^^^^
SyntaxError: Unexpected token export
    at new Script (vm.js:83:7)
    at createScript (vm.js:267:10)
    at Object.runInThisContext (vm.js:319:10)
    at Module._compile (internal/modules/cjs/loader.js:685:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

#### Information
Amplify CLI    =>    1.7.0
API(GraphQL)    =>    Select Option -> TypeScript

**Comment by edlefebvre** [comment]
Same error here during a `amplify env add`

`
✔ Successfully created initial AWS cloud resources for deployments.
✔ Initialized provider successfully.
✖ There was an error initializing your environment.
init failed
/home/*path to project*/src/aws-exports.js:14
export default awsmobile
^^^^^^
SyntaxError: Unexpected token export
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at getCurrentAWSExports (.nvm/versions/node/v8.11.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-javascript/lib/frontend-config-creator.js:105:18)
`
Amplify CLI => 1.7.1

**Comment by yuth** [comment]
@yukitaka13-1110 @edlefebvre could you paste the content from your `aws-exports.js`. Please obfuscate any sensitive info in the file before pasting them.
