### ISSUE TITLE
Amplify publish to S3 Cloudfront

### ISSUE THREAD

**Issue by miffycs** [aws-amplify/amplify-cli#1697]
Trying to set up a new react project with amplify and cognito.

I followed this tutorial: (used npm instead of yarn to create the react app)
https://aws-amplify.github.io/docs/js/react

Up to the Add Auth section. When I do `$amplify publish`

This is my error message:

Error has occured during file upload.
2019-06-20T21:10:57.592Z - error: uncaughtException: Access Denied date=Thu Jun 20 2019 17:10:57 GMT-0400 (Eastern Daylight Time), pid=47901, uid=462280680, gid=1896053708, cwd=/Users/miffyche/Desktop/ProServe Portfolio/myapp, execPath=/usr/local/Cellar/node/12.4.0/bin/node, version=v12.4.0, argv=[/usr/local/Cellar/node/12.4.0/bin/node, /usr/local/bin/amplify, publish], rss=204881920, heapTotal=156999680, heapUsed=100461624, external=19364351, loadavg=[2.4072265625, 2.32958984375, 2.3095703125], uptime=114010, trace=[column=35, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/services/s3.js, function=Request.extractError, line=585, method=extractError, native=false, column=20, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js, function=Request.callListeners, line=106, method=callListeners, native=false, column=10, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js, function=Request.emit, line=78, method=emit, native=false, column=14, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js, function=Request.emit, line=683, method=emit, native=false, column=10, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js, function=Request.transition, line=22, method=transition, native=false, column=12, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js, function=AcceptorStateMachine.runTo, line=14, method=runTo, native=false, column=10, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js, function=null, line=26, method=null, native=false, column=9, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js, function=null, line=38, method=null, native=false, column=12, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js, function=null, line=685, method=null, native=false, column=18, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js, function=Request.callListeners, line=116, method=callListeners, native=false], stack=[AccessDenied: Access Denied,     at Request.extractError (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/services/s3.js:585:35),     at Request.callListeners (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20),     at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10),     at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14),     at Request.transition (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10),     at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12),     at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10,     at Request.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9),     at Request.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12),     at Request.callListeners (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)]

Been trying to solve this error for hours.

Sometimes it also asks me to `$npm install aws-amplify-react` even though I have done so already.

I tried EVERYTHING up to reinstalling node, pip, awscli.

Please help.

**Comment by UnleashedMind** [comment]
@miffycs 

This might be due to a setting in your account. we are investigate this issue.

**Comment by kaustavghosh06** [comment]
Are you using an internal Amazon/AWS account?

**Comment by UnleashedMind** [comment]
This is due to an account restriction, closing the issue.

**Comment by Bulletninja** [comment]
@UnleashedMind What kind of restriction? A dev in my team has the same issue.

**Comment by abdsahin** [comment]
I also have exactly the same issue. The user I am using has the "Administrator" user permissions and after doing `amplify publish`, the following is the error.

```
✖ Error has occured during file upload.
2019-07-30T16:14:08.976Z - error: uncaughtException: Access Denied date=Tue Jul 30 2019 18:14:08 GMT+0200 (Central European Summer Time), 
```

I don't think there is a problem with the access rights since I can do `aws s3 sync build/ s3://my-bucket` (and only then make the site up and running)

Can you give us more information @UnleashedMind  ?

Thanks!

**Comment by satueveliina** [comment]
I also have this issue.

**Comment by abdsahin** [comment]
I found the problem, "Block public access to buckets and objects granted through new access control lists (ACLs)" option was turned on on the account level and that is why the publish is failing.

**Comment by jakemraz** [comment]
I also got the same issue on Isengard account
