### ISSUE TITLE
error: uncaughtException: when doing push

### ISSUE THREAD

**Issue by helloniklas** [aws-amplify/amplify-cli#1701]
Using v 1.7.4 what used to work now gives me an error when doing a push.

```
✔ Generated GraphQL operations successfully and saved at graphql
2019-06-21T16:43:05.635Z - error: uncaughtException: Syntax Error: Unexpected <EOF> date=Fri Jun 21 2019 17:43:05 GMT+0100 (BST), pid=90230, uid=501, gid=20, cwd=/Users/niklas/development/yaynay, execPath=/Users/niklas/.nvm/versions/node/v9.2.0/bin/node, version=v9.2.0, argv=[/Users/niklas/.nvm/versions/node/v9.2.0/bin/node, /Users/niklas/.nvm/versions/node/v9.2.0/bin/amplify, push], rss=220684288, heapTotal=194605056, heapUsed=152820512, external=11771932, loadavg=[1.67236328125, 1.82666015625, 2.2626953125], uptime=3295, trace=[column=10, file=/Users/niklas/.nvm/versions/node/v9.2.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-graphql-types-generator/node_modules/graphql/error/syntaxError.js, function=syntaxError, line=24, method=null, native=false, column=33, file=/Users/niklas/.nvm/versions/node/v9.2.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-graphql-types-generator/node_modules/graphql/language/parser.js, function=unexpected, line=1491, method=null, native=false, column=9, file=/Users/niklas/.nvm/versions/node/v9.2.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-graphql-types-generator/node_modules/graphql/language/parser.js, function=parseDefinition, line=155, method=null, native=false, column=16, file=/Users/niklas/.nvm/versions/node/v9.2.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-graphql-types-generator/node_modules/graphql/language/parser.js, function=many, line=1521, method=null, native=false, column=18, file=/Users/niklas/.nvm/versions/node/v9.2.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-graphql-types-generator/node_modules/graphql/language/parser.js, function=parseDocument, line=115, method=null, native=false, column=10, file=/Users/niklas/.nvm/versions/node/v9.2.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-graphql-types-generator/node_modules/graphql/language/parser.js, function=Object.parse, line=50, method=parse, native=false, column=56, file=/Users/niklas/.nvm/versions/node/v9.2.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-graphql-types-generator/src/loading.ts, function=graphql_1.concatAST.sources.map.source, line=60, method=source, native=false, column=null, file=null, function=Array.map, line=null, method=map, native=false, column=42, file=/Users/niklas/.nvm/versions/node/v9.2.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-graphql-types-generator/src/loading.ts, function=Object.loadAndMergeQueryDocuments, line=60, method=loadAndMergeQueryDocuments, native=false, column=20, file=/Users/niklas/.nvm/versions/node/v9.2.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-graphql-types-generator/src/generate.ts, function=generate, line=32, method=null, native=false], stack=[GraphQLError: Syntax Error: Unexpected <EOF>,     at syntaxError (/Users/niklas/.nvm/versions/node/v9.2.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-graphql-types-generator/node_modules/graphql/error/syntaxError.js:24:10),     at unexpected (/Users/niklas/.nvm/versions/node/v9.2.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-graphql-types-generator/node_modules/graphql/language/parser.js:1491:33),     at parseDefinition (/Users/niklas/.nvm/versions/node/v9.2.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-graphql-types-generator/node_modules/graphql/language/parser.js:155:9),     at many (/Users/niklas/.nvm/versions/node/v9.2.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-graphql-types-generator/node_modules/graphql/language/parser.js:1521:16),     at parseDocument (/Users/niklas/.nvm/versions/node/v9.2.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-graphql-types-generator/node_modules/graphql/language/parser.js:115:18),     at Object.parse (/Users/niklas/.nvm/versions/node/v9.2.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-graphql-types-generator/node_modules/graphql/language/parser.js:50:10),     at graphql_1.concatAST.sources.map.source (/Users/niklas/.nvm/versions/node/v9.2.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-graphql-types-generator/src/loading.ts:60:56),     at Array.map (<anonymous>),     at Object.loadAndMergeQueryDocuments (/Users/niklas/.nvm/versions/node/v9.2.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-graphql-types-generator/src/loading.ts:60:42),     at generate (/Users/niklas/.nvm/versions/node/v9.2.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-graphql-types-generator/src/generate.ts:32:20)]
```

**Comment by UnleashedMind** [comment]
Hi @helloniklas 

Could you share your schema with us so we can investigate further?

**Comment by helloniklas** [comment]
So I’ve updated to 1.7.5 and deleted all local files and folders then re did everything and it now works.

**Comment by helloniklas** [comment]
So I’ve updated to 1.7.5 and deleted all local files and folders then re did everything and it now works.
