### ISSUE TITLE
How do you use same backend with multi-env?

### ISSUE THREAD

**Issue by d3vhound** [aws-amplify/amplify-cli#1734]
**Describe the bug**
Confused on the best way to do this step that's currently in the multienv docs.
<img width="832" alt="Screen Shot 2019-06-26 at 6 58 30 PM" src="https://user-images.githubusercontent.com/17565159/60222863-923a4080-9844-11e9-9127-2abfdae6c72e.png">

When following these steps it'll show that I need to update the api part of the stack and when I do my other team member has to then create a whole new stack again and it goes back and forth like this. 

What is the best way to share the same backend if the steps in the docs don't work?

**Comment by attilah** [comment]
@d3vhound sorry about the confusion, we update the documentation regularly based on customer feedback, feel free to open an issue in the https://github.com/aws-amplify/docs repository next time.

After you've created the initial amplify cli workspace for a new team member and since ```team-provider-info.json``` contains the required deployment information, team members during the development cycle just have to repeat these steps, just like for git:
```
$ amplify env pull
$ git pull origin dev
```

No need to repeat the same steps for adding APIs, etc. That needs to be done only by the team member who is responsible for that part.

Would this clear up the process for you?

If you think that this is functionally not working, please send the exact steps you're executing between team members to help us to track down the issue.

**Comment by kaustavghosh06** [comment]
@d3vhound Which version of the CLI are you using? We recently released a fix for avoiding the "Update" status to REST API's/Lambda functions (When there is no update to the src code) when working between teams.

**Comment by d3vhound** [comment]
@attilah when I run `amplify env pull` right after cloning the project for the first time I either get an Unauthorized error or this:
```bash
2019-06-27T17:14:04.208Z - error: uncaughtException: Cannot read property 'awscloudformation' of undefined date=Thu Jun 27 2019 12:14:04 GMT-0500 (Central Daylight Time), pid=44232, uid=501, gid=20, cwd=/Users/devionvillegas/Developer/WELLHAUX/AMPLIFY/wellhaux-pumper, execPath=/usr/local/bin/node, version=v11.14.0, argv=[/usr/local/bin/node, /usr/local/bin/amplify, env, pull], rss=207908864, heapTotal=155426816, heapUsed=119862544, external=20600458, loadavg=[1.9375, 3.14013671875, 2.62744140625], uptime=223385, trace=[column=30, file=/usr/local/lib/node_modules/@aws-amplify/cli/src/lib/initialize-env.js, function=initializationTasks.push, line=56, method=push, native=false, column=18, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/promise-sequential/index.js, function=null, line=16, method=null, native=false, column=5, file=internal/process/task_queues.js, function=process.runNextTicks [as _tickCallback], line=52, method=runNextTicks [as _tickCallback], native=false, column=11, file=internal/modules/cjs/loader.js, function=Module.runMain, line=880, method=runMain, native=false, column=11, file=internal/main/run_main_module.js, function=null, line=21, method=null, native=false], stack=[TypeError: Cannot read property 'awscloudformation' of undefined,     at initializationTasks.push (/usr/local/lib/node_modules/@aws-amplify/cli/src/lib/initialize-env.js:56:30),     at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/promise-sequential/index.js:16:18,     at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:52:5),     at Function.Module.runMain (internal/modules/cjs/loader.js:880:11),     at internal/main/run_main_module.js:21:11]
```

The exact steps are:
1. 1st team member sets up graphql api with amplify
2. pushes to github
3. 2nd member clones repository
4. 2nd member wants to change schema or see output of `amplify status`

The 4. step is where I've always encountered difficulty. The docs make it seem like you have to run `amplify init` after cloning and switching to a branch. Is that not the case?

**Comment by d3vhound** [comment]
@kaustavghosh06 
```bash
❯ amplify -v
1.7.6
```

**Comment by kaustavghosh06** [comment]
@d3vhound Are the team members using different versions of the CLI? Also, would it be possible to see your amplify directory structure? I'm suspicious that the project is using pre v1 version project structure.

**Comment by d3vhound** [comment]
No, we're all on 1.7.6. The project structure is the same as running `amplify init` right now with a react native project.

**Comment by SwaySway** [comment]
@d3vhound Are you still experiencing issues?
