### ISSUE TITLE
CloudFormation cannot update a stack when a custom-named resource requires replacing

### ISSUE THREAD

**Issue by yukitaka13-1110** [aws-amplify/amplify-cli#1866]
I have three branches ( master develop feature/* ).
And have two amplify environment ( dev feat ).
I implemented in feature branch and feat env.
I could build and create cloud resource in feat environment.
Push remote and merge to develop and tried to deploy it.
But, an error has occurred.
I realize that was occurred by the changes of GraphQL schema.
I change DynamoDB SORT key, so update was failed.
In this case, what can I do ?
As far as I can think of ...

- Delete & create api at feat env and merge and deploy

Is there any other way ?

```log
                                 Resource Name: <MyTable>Info-ghvuofo6ijfhvdyxg6fg47urku (AWS::DynamoDB::Table)
                                 Event Type: update
                                 Reason: CloudFormation cannot update a stack when a custom-named resource requires replacing. Rename <MyTable>Info-ghvuofo6ijfhvdyxg6fg47urku-dev and update the stack again.
                                 URL: https://console.aws.amazon.com/cloudformation/home?region=us-west-2#/stacks/arn%3Aaws%3Acloudformation%3Aus-west-2%3A367986456615%3Astack%2Fmyproject-dev-20190617194927-apimyproject-1FLOM7FHM41XP-<MyTable>Info-Q3WUWDTWHHVY%2F5e1d5e70-90ee-11e9-8ebf-02cb67b6aa16/events
                                 init failed
2019-07-19T01:34:53.910Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
                                    ✖ There was an error initializing your environment.
2019-07-19T01:34:53.913Z [INFO]: { ResourceNotReady: Resource is not in the state stackUpdateComplete
                                 at constructor.setError (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/resource_waiter.js:182:47)
                                 at Request.CHECK_ACCEPTORS (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/resource_waiter.js:44:12)
                                 at Request.callListeners (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
                                 at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
                                 at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
                                 at Request.transition (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
                                 at AcceptorStateMachine.runTo (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
                                 at Request.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
                                 at Request.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12)
                                 message: 'Resource is not in the state stackUpdateComplete',
                                 code: 'ResourceNotReady',
                                 retryable: false,
                                 time: 2019-07-19T01:34:48.897Z,
                                 statusCode: 200,
                                 retryDelay: 30000 }
2019-07-19T01:34:53.966Z [ERROR]: !!! Build failed
2019-07-19T01:34:54.088Z [ERROR]: !!! Non-Zero Exit Code detected
2019-07-19T01:34:54.088Z [INFO]: # Starting environment caching...
2019-07-19T01:34:54.089Z [INFO]: # Uploading environment cache artifact...
2019-07-19T01:34:54.179Z [INFO]: # Environment caching completed
Terminating logging...
```

**Comment by yukitaka13-1110** [comment]
The solution I presented is likely to end up with the same result.
It seems that there is no way but to change the dev environment directly.

**Comment by UnleashedMind** [comment]
@yukitaka13-1110 
When you `git checkout` to another branch, you should also `amplify env checkout` to the corresponding env. 
https://aws-amplify.github.io/docs/cli-toolchain/quickstart#environments--teams

**Comment by yukitaka13-1110** [comment]
@UnleashedMind Is it mean I should not merge on remote ?
I implement local feat branch and  and push remote feat branch.
Next, merge to develop on remote develop branch and amplify console run build.
Is it wrong way ?

I think this error has occurred by changing of GraphQL(DynamoDB) schema.

**Comment by mart2967** [comment]
Perhaps the same issue as https://github.com/aws-amplify/amplify-cli/issues/1651 which is still a problem for me and others.

cc @yuth

**Comment by kaustavghosh06** [comment]
@yukitaka13-1110 You would have to iteratively change your schema if you're dealing with changing @connections. I'm curious to know what changed in the GraphQL schema so that we can root-cause this. A before and after snapshot of the schema would help.

**Comment by tgjorgoski** [comment]
Happened to me too: 
I'm attaching: the schema change, the general error, and more detailed error from CFN:

<img width="1303" alt="Screenshot 2019-09-01 at 14 12 42" src="https://user-images.githubusercontent.com/1822105/64076260-e2a9a080-ccc2-11e9-866b-d4a718692f24.png">
<img width="1340" alt="Screenshot 2019-09-01 at 14 13 41" src="https://user-images.githubusercontent.com/1822105/64076261-e2a9a080-ccc2-11e9-9c60-53a77d896e0b.png">
<img width="1334" alt="Screenshot 2019-09-01 at 14 14 26" src="https://user-images.githubusercontent.com/1822105/64076262-e3423700-ccc2-11e9-9205-9a1a0cd33c92.png">
