### ISSUE TITLE
Amplify CLI throws up "Error: EISDIR: illegal operation on a directory, read"

### ISSUE THREAD

**Issue by babus** [aws-amplify/amplify-cli#1876]
**Describe the bug**
Amplify CLI on Mac OS doesn't work and throws up error while invoking. I have installed node and npm using brew.

**Expected behavior**
CLI should work without any system patching.

**Console Error**
```
babusomasundaram@Babus-MacBook-Pro Boop $ node -v
v12.6.0
babusomasundaram@Babus-MacBook-Pro Boop $ npm -v
6.10.1
babusomasundaram@Babus-MacBook-Pro Boop $ npm install -g @aws-amplify/cli
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
npm WARN deprecated set-value@1.0.0: Critical bug fixed in v3.0.1, please upgrade to the latest version.
/usr/local/bin/amplify -> /usr/local/lib/node_modules/@aws-amplify/cli/bin/amplify

> fsevents@1.2.9 install /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download
[fsevents] Success: "/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" is installed via remote

> core-js@2.6.9 postinstall /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

npm WARN graphql-toolkit@0.4.1 requires a peer of graphql-tag-pluck@^0.8.3 but none is installed. You must install peer dependencies yourself.

+ @aws-amplify/cli@1.8.2
added 2021 packages from 1375 contributors and updated 2 packages in 111.755s
babusomasundaram@Babus-MacBook-Pro Boop $ amplify
/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/index.js:13
    throw up;
    ^

Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:513:3)
    at tryReadSync (fs.js:338:20)
    at Proxy.readFileSync (fs.js:375:19)
    at Function.readFileSync [as sync] (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/cosmiconfig/dist/readFile.js:33:15)
    at Explorer.loadSearchPlaceSync (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/cosmiconfig/dist/createExplorer.js:157:30)
    at Explorer.searchDirectorySync (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/cosmiconfig/dist/createExplorer.js:136:21)
    at run (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/cosmiconfig/dist/createExplorer.js:108:27)
    at cacheWrapper (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/cosmiconfig/dist/cacheWrapper.js:14:18)
    at Explorer.searchFromDirectorySync (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/cosmiconfig/dist/createExplorer.js:117:14)
    at run (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/cosmiconfig/dist/createExplorer.js:111:21) {
  errno: -21,
  syscall: 'read',
  code: 'EISDIR'
}
```

**Desktop (please complete the following information):**
 - OS: Mac
 - Version: 10.14.1 Mojave

**Comment by babus** [comment]
Installed `graphql-tag-pluck` manually but still error throws up.

```
babusomasundaram@Babus-MacBook-Pro Boop $ npm list -g --depth=0
/usr/local/lib
├── @aws-amplify/cli@1.8.2
├── artillery@1.6.0-28
├── npm@6.10.1
├── package.json@2.0.1
├── serverless@1.48.2
├── serverless-domain-manager@3.2.6
├── serverless-offline-python@3.22.1
└── serverless-stage-manager@1.0.5

npm ERR! peer dep missing: graphql-tag-pluck@^0.8.3, required by graphql-toolkit@0.4.1
babusomasundaram@Babus-MacBook-Pro Boop $ npm install -g graphql-tag-pluck
+ graphql-tag-pluck@0.8.3
added 31 packages from 47 contributors in 1.815s
babusomasundaram@Babus-MacBook-Pro Boop $ amplify
/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/index.js:13
    throw up;
    ^

Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:513:3)
    at tryReadSync (fs.js:338:20)
    at Proxy.readFileSync (fs.js:375:19)
    at Function.readFileSync [as sync] (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/cosmiconfig/dist/readFile.js:33:15)
    at Explorer.loadSearchPlaceSync (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/cosmiconfig/dist/createExplorer.js:157:30)
    at Explorer.searchDirectorySync (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/cosmiconfig/dist/createExplorer.js:136:21)
    at run (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/cosmiconfig/dist/createExplorer.js:108:27)
    at cacheWrapper (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/cosmiconfig/dist/cacheWrapper.js:14:18)
    at Explorer.searchFromDirectorySync (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/cosmiconfig/dist/createExplorer.js:117:14)
    at run (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/cosmiconfig/dist/createExplorer.js:111:21) {
  errno: -21,
  syscall: 'read',
  code: 'EISDIR'
}
babusomasundaram@Babus-MacBook-Pro Boop $ npm list -g --depth=0
/usr/local/lib
├── @aws-amplify/cli@1.8.2
├── artillery@1.6.0-28
├── graphql-tag-pluck@0.8.3
├── npm@6.10.1
├── package.json@2.0.1
├── serverless@1.48.2
├── serverless-domain-manager@3.2.6
├── serverless-offline-python@3.22.1
└── serverless-stage-manager@1.0.5
```

**Comment by babus** [comment]
Used this gist to reinstall node with nvm after `brew uninstall node`,
https://gist.github.com/brock/5b1b70590e1171c4ab54. Updated the node to the latest and able to install and use CLI with success.

**Comment by vparfaniuc** [comment]
Running into the same issue was able to solve it by removing the .aws folder and it's contents from the home folder (Eg: ~/.aws). I hope it helps anyone.
