### ISSUE TITLE
Cannot publish new checkout of code

### ISSUE THREAD

**Issue by revmischa** [aws-amplify/amplify-cli#1925]
I added amplify hosting and pushed the amplify project config. All the files in the amplify/ directory minus the ones amplify added to .gitignore are present, including the hosting/ dir.

When someone else pulls the code and runs `amplify publish` - they get:
```
test|master⚡ ⇒ amplify publish

Please add hosting to your project before publishing your project
Command: amplify hosting add

```

It's already added but ok...

```
test|master⚡ ⇒ amplify hosting add
Hosting is already fully enabled.
/Users/cyber/.config/yarn/global/node_modules/gluegun/build/index.js:13
    throw up;
    ^

Error: Hosting is already fully enabled.
    at Object.add (/Users/cyber/.config/yarn/global/node_modules/amplify-category-hosting/index.js:32:11)
    at Command.run (/Users/cyber/.config/yarn/global/node_modules/amplify-category-hosting/commands/hosting/add.js:8:18)
    at Runtime.<anonymous> (/Users/cyber/.config/yarn/global/node_modules/gluegun/build/runtime/run.js:90:58)
    at step (/Users/cyber/.config/yarn/global/node_modules/gluegun/build/runtime/run.js:32:23)
    at Object.next (/Users/cyber/.config/yarn/global/node_modules/gluegun/build/runtime/run.js:13:53)
    at /Users/cyber/.config/yarn/global/node_modules/gluegun/build/runtime/run.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/cyber/.config/yarn/global/node_modules/gluegun/build/runtime/run.js:3:12)
    at Runtime.run (/Users/cyber/.config/yarn/global/node_modules/gluegun/build/runtime/run.js:51:12)
    at Object.run (/Users/cyber/.config/yarn/global/node_modules/@aws-amplify/cli/src/cli.js:29:29)
test|master⚡ ⇒ amplify configure project
Error occured during configuration.
Error: ENOENT: no such file or directory, open '/Users/cyber/dev/jb/eres/test/amplify/.config/local-env-info.json'
    at Object.openSync (fs.js:447:3)
    at Object.readFileSync (fs.js:349:35)
    at readJsonFile (/Users/cyber/.config/yarn/global/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/read-json-file.js:11:33)
    at Object.run (/Users/cyber/.config/yarn/global/node_modules/@aws-amplify/cli/src/lib/config-steps/c0-analyzeProject.js:15:34)
    at Command.run (/Users/cyber/.config/yarn/global/node_modules/@aws-amplify/cli/src/commands/configure.js:18:29)
    at Runtime.<anonymous> (/Users/cyber/.config/yarn/global/node_modules/gluegun/build/runtime/run.js:90:58)
    at step (/Users/cyber/.config/yarn/global/node_modules/gluegun/build/runtime/run.js:32:23)
    at Object.next (/Users/cyber/.config/yarn/global/node_modules/gluegun/build/runtime/run.js:13:53)
    at /Users/cyber/.config/yarn/global/node_modules/gluegun/build/runtime/run.js:7:71
    at new Promise (<anonymous>) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/cyber/dev/jb/eres/test/amplify/.config/local-env-info.json'
}
```

**Comment by kaustavghosh06** [comment]
@revmischa After pulling the code from GitHub, did you run ‘amplify init’? That would setup all the runtime files that the CLI needs which you’d gitignored.

**Comment by revmischa** [comment]
that seems to have helped. is that documented somewhere?
can't it detect that amplify config already exists and prompt me?

**Comment by kaustavghosh06** [comment]
We've mentioned the flow in our docs out here - https://aws-amplify.github.io/docs/cli-toolchain/quickstart#team-workflow

**Comment by kaustavghosh06** [comment]
We already have an enhancement request in our backlog to auto-detect these configs and prompt the user when running any amplify command.
