### ISSUE TITLE
'amplify api add-graphql-datasource' throwing 'Unable to merge GraphQL type'

### ISSUE THREAD

**Issue by MaximumCrash** [aws-amplify/amplify-cli#1941]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **
* AWS Amplify CLI Usage / Bug(?)

** What AWS Services are you utilizing? **
* RDS (Serverless Aurora)
* App Sync

** Provide additional details e.g. code snippets **

I've been trying to add an aurora RDS data source to my app sync API, but whenever I do I get:

    'Error: Unable to merge GraphQL type "UserIdentifiable": asNext is not iterable'

My terminal looked like this when I run amplify api add-graphql-datasource

```console
$ amplify api add-graphql-datasource
Using datasource: Aurora Serverless, provided by: awscloudformation
? Provide the region in which your cluster is located: us-east-1
? Select the Aurora Serverless cluster that will be used as the data source for your API: amplify-serverless-cluster
✔ Fetched Aurora Serverless cluster.
? Select the database to use as the datasource: Users
Error: Unable to merge GraphQL type "UserIdentifiable": asNext is not iterable
    at Object.mergeType (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-toolkit/src/epoxy/typedefs-mergers/type.ts:20:13)
    at nodes.reduce (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-toolkit/src/epoxy/typedefs-mergers/merge-nodes.ts:42:22)
    at Array.reduce (<anonymous>)
    at Object.mergeGraphQLNodes (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-toolkit/src/epoxy/typedefs-mergers/merge-nodes.ts:29:16)
    at mergeGraphQLTypes (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-toolkit/src/epoxy/typedefs-mergers/merge-typedefs.ts:228:40)
    at Object.mergeTypeDefs (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-toolkit/src/epoxy/typedefs-mergers/merge-typedefs.ts:93:18)
    at mergeTypes (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/merge-graphql-schemas/src/merge_types.ts:9:10)
    at datasourceSelectionPrompt.then.then.then (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/commands/api/add-datasource.js:116:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
There was an error adding the datasource

```

I've created a table in RDS using this Query 

```sql
CREATE DATABASE Users;
USE Users;
CREATE TABLE UserIdentifiable (
  id char(11) NOT NULL PRIMARY KEY,
  user_auth_id varchar(50) NOT NULL, 
  user_name varchar(50) NOT NULL, 
  user_nickname varchar(50) NOT NULL, 
  contact_name_first varchar(50),
  contact_name_middle varchar(50),
  contact_name_last varchar(50), 
  contact_name_title varchar(50),
  contact_email_primary varchar(50) NOT NULL, 
  contact_email_secondary varchar(50),
  contact_number int(20),
  date_created datetime DEFAULT CURRENT_TIMESTAMP
  ); 
```

** Steps to Reproduce ** 

Follow this tutorial: [https://aws-amplify.github.io/docs/cli-toolchain/graphql#relational-databases](https://aws-amplify.github.io/docs/cli-toolchain/graphql#relational-databases)

See the error once you run **amplify api add-graphql-datasource**

**Comment by MaximumCrash** [comment]
After running some more tests, I've found that the field giving me grief was that my id definition: 
```sql
id char(11) NOT NULL PRIMARY KEY,
```
should have been 

```sql 
id int(11) NOT NULL PRIMARY KEY,
```

With the change to int the amplify api add-graphql-datasource command now successfully adds my Aurora serverless datasource locally. 

I'm no expert, but I believe there may be a conflict with id's being defined as Char since GraphQL's ID scalar is serialized in the same way a string is.

**Comment by manchicken** [comment]
This still seems like an issue. If the GraphQL spec calls for IDs to be serialized as strings, why is it being a `CHAR(11)` a problem?
