### ISSUE TITLE
amplify push failed with token expired in the middle of the push

### ISSUE THREAD

**Issue by monaye** [aws-amplify/amplify-cli#1980]
**Describe the bug**
amplify push failed with token expired in middle of the push

**To Reproduce**
1. push with `amplify push` 

**Terminal Output**
```
mowin:handbook mowin$ amplify push

Current Environment: monaye

| Category | Resource name | Operation | Provider plugin   |
| -------- | ------------- | --------- | ----------------- |
| Auth     | nhbcognito    | Create    | awscloudformation |
| Api      | nhb           | Create    | awscloudformation |
| Api      | nhbusersapi   | Create    | awscloudformation |
| Function | nhbusersfunc  | Create    | awscloudformation |
? Are you sure you want to continue? Yes

GraphQL schema compiled successfully.

Edit your schema at /Users/mowin/Documents/000_APPS/handbook/amplify/backend/api/nhb/schema.graphql or place .graphql files in a directory at /Users/mowin/Documents/000_APPS/handbook/amplify/backend/api/nhb/schema
? Do you want to generate code for your newly created GraphQL API No
⠹ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS nhb-monaye-20190806140846 AWS::CloudFormation::Stack Tue Aug 06 2019 14:16:53 GMT-0700 (Pacific Daylight Time) User Initiated
⠴ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS authnhbcognito AWS::CloudFormation::Stack Tue Aug 06 2019 14:16:58 GMT-0700 (Pacific Daylight Time)
⠹ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS authnhbcognito AWS::CloudFormation::Stack Tue Aug 06 2019 14:17:00 GMT-0700 (Pacific Daylight Time) Resource creation Initiated
⠴ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS nhb-monaye-20190806140846-authnhbcognito-NNOS8MK4UFIY AWS::CloudFormation::Stack Tue Aug 06 2019 14:16:59 GMT-0700 (Pacific Daylight Time) User Initiated
⠦ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS SNSRole AWS::IAM::Role Tue Aug 06 2019 14:17:13 GMT-0700 (Pacific Daylight Time)
⠋ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS SNSRole AWS::IAM::Role Tue Aug 06 2019 14:17:14 GMT-0700 (Pacific Daylight Time) Resource creation Initiated
⠋ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE SNSRole AWS::IAM::Role Tue Aug 06 2019 14:18:26 GMT-0700 (Pacific Daylight Time)
⠋ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS UserPool AWS::Cognito::UserPool Tue Aug 06 2019 14:18:32 GMT-0700 (Pacific Daylight Time)
⠋ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE    UserPool AWS::Cognito::UserPool Tue Aug 06 2019 14:18:35 GMT-0700 (Pacific Daylight Time)
CREATE_IN_PROGRESS UserPool AWS::Cognito::UserPool Tue Aug 06 2019 14:18:35 GMT-0700 (Pacific Daylight Time) Resource creation Initiated
⠙ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE    UserPoolGroupLAC         AWS::Cognito::UserPoolGroup  Tue Aug 06 2019 14:18:43 GMT-0700 (Pacific Daylight Time)
CREATE_IN_PROGRESS UserPoolGroupLAC         AWS::Cognito::UserPoolGroup  Tue Aug 06 2019 14:18:43 GMT-0700 (Pacific Daylight Time) Resource creation Initiated
CREATE_COMPLETE    UserPoolGroupSysAdmin    AWS::Cognito::UserPoolGroup  Tue Aug 06 2019 14:18:43 GMT-0700 (Pacific Daylight Time)
CREATE_COMPLETE    UserPoolClientWeb        AWS::Cognito::UserPoolClient Tue Aug 06 2019 14:18:43 GMT-0700 (Pacific Daylight Time)
CREATE_IN_PROGRESS UserPoolGroupSysAdmin    AWS::Cognito::UserPoolGroup  Tue Aug 06 2019 14:18:43 GMT-0700 (Pacific Daylight Time) Resource creation Initiated
CREATE_COMPLETE    UserPoolClient           AWS::Cognito::UserPoolClient Tue Aug 06 2019 14:18:43 GMT-0700 (Pacific Daylight Time)
CREATE_IN_PROGRESS UserPoolClientWeb        AWS::Cognito::UserPoolClient Tue Aug 06 2019 14:18:42 GMT-0700 (Pacific Daylight Time) Resource creation Initiated
CREATE_IN_PROGRESS UserPoolClient           AWS::Cognito::UserPoolClient Tue Aug 06 2019 14:18:42 GMT-0700 (Pacific Daylight Time) Resource creation Initiated
CREATE_COMPLETE    UserPoolGroupCampusAdmin AWS::Cognito::UserPoolGroup  Tue Aug 06 2019 14:18:42 GMT-0700 (Pacific Daylight Time)
CREATE_IN_PROGRESS UserPoolGroupCampusAdmin AWS::Cognito::UserPoolGroup  Tue Aug 06 2019 14:18:42 GMT-0700 (Pacific Daylight Time) Resource creation Initiated
CREATE_IN_PROGRESS UserPoolGroupLAC         AWS::Cognito::UserPoolGroup  Tue Aug 06 2019 14:18:41 GMT-0700 (Pacific Daylight Time)
CREATE_COMPLETE    UserPoolGroupViewer      AWS::Cognito::UserPoolGroup  Tue Aug 06 2019 14:18:41 GMT-0700 (Pacific Daylight Time)
CREATE_IN_PROGRESS UserPoolGroupViewer      AWS::Cognito::UserPoolGroup  Tue Aug 06 2019 14:18:41 GMT-0700 (Pacific Daylight Time) Resource creation Initiated
CREATE_IN_PROGRESS UserPoolGroupCampusAdmin AWS::Cognito::UserPoolGroup  Tue Aug 06 2019 14:18:41 GMT-0700 (Pacific Daylight Time)
CREATE_IN_PROGRESS UserPoolGroupSysAdmin    AWS::Cognito::UserPoolGroup  Tue Aug 06 2019 14:18:41 GMT-0700 (Pacific Daylight Time)
CREATE_IN_PROGRESS UserPoolClientWeb        AWS::Cognito::UserPoolClient Tue Aug 06 2019 14:18:40 GMT-0700 (Pacific Daylight Time)
CREATE_IN_PROGRESS UserPoolClient           AWS::Cognito::UserPoolClient Tue Aug 06 2019 14:18:40 GMT-0700 (Pacific Daylight Time)
CREATE_IN_PROGRESS UserPoolGroupViewer      AWS::Cognito::UserPoolGroup  Tue Aug 06 2019 14:18:39 GMT-0700 (Pacific Daylight Time)
⠙ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS UserPoolClientRole AWS::IAM::Role Tue Aug 06 2019 14:18:48 GMT-0700 (Pacific Daylight Time)
⠴ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS UserPoolClientRole AWS::IAM::Role Tue Aug 06 2019 14:18:49 GMT-0700 (Pacific Daylight Time) Resource creation Initiated
⠏ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE UserPoolClientRole AWS::IAM::Role Tue Aug 06 2019 14:20:00 GMT-0700 (Pacific Daylight Time)
⠧ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE    UserPoolClientLambda AWS::Lambda::Function Tue Aug 06 2019 14:20:07 GMT-0700 (Pacific Daylight Time)
CREATE_IN_PROGRESS UserPoolClientLambda AWS::Lambda::Function Tue Aug 06 2019 14:20:07 GMT-0700 (Pacific Daylight Time) Resource creation Initiated
CREATE_IN_PROGRESS UserPoolClientLambda AWS::Lambda::Function Tue Aug 06 2019 14:20:06 GMT-0700 (Pacific Daylight Time)
⠴ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS UserPoolClientLambdaPolicy AWS::IAM::Policy Tue Aug 06 2019 14:20:14 GMT-0700 (Pacific Daylight Time) Resource creation Initiated
CREATE_IN_PROGRESS UserPoolClientLambdaPolicy AWS::IAM::Policy Tue Aug 06 2019 14:20:13 GMT-0700 (Pacific Daylight Time)
⠹ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE UserPoolClientLambdaPolicy AWS::IAM::Policy Tue Aug 06 2019 14:21:24 GMT-0700 (Pacific Daylight Time)
⠹ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS UserPoolClientLogPolicy AWS::IAM::Policy Tue Aug 06 2019 14:21:31 GMT-0700 (Pacific Daylight Time) Resource creation Initiated
CREATE_IN_PROGRESS UserPoolClientLogPolicy AWS::IAM::Policy Tue Aug 06 2019 14:21:29 GMT-0700 (Pacific Daylight Time)
⠙ Updating resources in the cloud. This may take a few minutes...TypeError: events is not iterable
    at getUniqueStacksEvents (/Users/mowin/.nvm/versions/node/v11.4.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js:453:28)
    at getStackEvents.then (/Users/mowin/.nvm/versions/node/v11.4.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js:140:30)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
2019-08-06T21:22:41.564Z - error: uncaughtException: The security token included in the request is expired date=Tue Aug 06 2019 14:22:41 GMT-0700 (Pacific Daylight Time), pid=30314, uid=1247762399, gid=1042715009, cwd=/Users/mowin/Documents/000_APPS/handbook, execPath=/Users/mowin/.nvm/versions/node/v11.4.0/bin/node, version=v11.4.0, argv=[/Users/mowin/.nvm/versions/node/v11.4.0/bin/node, /Users/mowin/.nvm/versions/node/v11.4.0/bin/amplify, push], rss=195440640, heapTotal=139821056, heapUsed=110576904, external=22759168, loadavg=[3.92431640625, 5.0703125, 6.21923828125], uptime=71147, trace=[column=29, file=/Users/mowin/.nvm/versions/node/v11.4.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/query.js, function=Request.extractError, line=50, method=extractError, native=false, column=20, file=/Users/mowin/.nvm/versions/node/v11.4.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js, function=Request.callListeners, line=106, method=callListeners, native=false, column=10, file=/Users/mowin/.nvm/versions/node/v11.4.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js, function=Request.emit, line=78, method=emit, native=false, column=14, file=/Users/mowin/.nvm/versions/node/v11.4.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js, function=Request.emit, line=683, method=emit, native=false, column=10, file=/Users/mowin/.nvm/versions/node/v11.4.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js, function=Request.transition, line=22, method=transition, native=false, column=12, file=/Users/mowin/.nvm/versions/node/v11.4.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js, function=AcceptorStateMachine.runTo, line=14, method=runTo, native=false, column=10, file=/Users/mowin/.nvm/versions/node/v11.4.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js, function=null, line=26, method=null, native=false, column=9, file=/Users/mowin/.nvm/versions/node/v11.4.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js, function=null, line=38, method=null, native=false, column=12, file=/Users/mowin/.nvm/versions/node/v11.4.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js, function=null, line=685, method=null, native=false, column=18, file=/Users/mowin/.nvm/versions/node/v11.4.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js, function=Request.callListeners, line=116, method=callListeners, native=false], stack=[ExpiredToken: The security token included in the request is expired,     at Request.extractError (/Users/mowin/.nvm/versions/node/v11.4.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/query.js:50:29),     at Request.callListeners (/Users/mowin/.nvm/versions/node/v11.4.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20),     at Request.emit (/Users/mowin/.nvm/versions/node/v11.4.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10),     at Request.emit (/Users/mowin/.nvm/versions/node/v11.4.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14),     at Request.transition (/Users/mowin/.nvm/versions/node/v11.4.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10),     at AcceptorStateMachine.runTo (/Users/mowin/.nvm/versions/node/v11.4.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12),     at /Users/mowin/.nvm/versions/node/v11.4.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10,     at Request.<anonymous> (/Users/mowin/.nvm/versions/node/v11.4.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9),     at Request.<anonymous> (/Users/mowin/.nvm/versions/node/v11.4.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12),     at Request.callListeners (/Users/mowin/.nvm/versions/node/v11.4.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)]
```

**Comment by kaustavghosh06** [comment]
@monaye The Cloudformation push still must've succeeded, just that the CLI wasn't able to fetch the event due to the token expiration. If you run `amplify push` the second time with your new token, your local files would be updated with whateever was created in the cloud.

**Comment by monaye** [comment]
@kaustavghosh06 
yes. it successfully pushed on the second time.
