### ISSUE TITLE
Error occured during configuration. Error: Corrupt file contents 

### ISSUE THREAD

**Issue by oliverandersencox** [aws-amplify/amplify-cli#2010]
I am trying to use 2 front ends with my amplify. One in Ionic, which works fine and one in angular. 

As per the docs I copied the Amplify folder across to the angular project and then ran:

amplify configure project

I went through the steps and was then presented with this:

```
> Please tell us about your project
? What javascript framework are you using angular
? Source Directory Path:  src
? Distribution Directory Path: dist
? Build Command:  ng build --prod
? Start Command: ng serve
Using default provider  awscloudformation
Error occured during configuration.
Error: Corrupt file contents in /Users/Ollie/Desktop/Doin/Dashboard/Doin-Dashboard/amplify/.config/local-aws-info.json
    at getConfigForEnv (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/configuration-manager.js:455:17)
    at getCurrentConfig (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/configuration-manager.js:428:10)
    at Object.configure (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/configuration-manager.js:34:35)
    at Object.configure (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/index.js:40:24)
    at configTasks.push (/usr/local/lib/node_modules/@aws-amplify/cli/src/lib/config-steps/c2-configProviders.js:19:45)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/promise-sequential/index.js:16:18
    at process._tickCallback (internal/process/next_tick.js:68:7)
Olivers-MacBook-Pro:Doin-Dashboard Ollie$ 
```

Nothing seems to make this work. Any ideas?

**Comment by kaustavghosh06** [comment]
What contents does this file-> `/Users/Ollie/Desktop/Doin/Dashboard/Doin-Dashboard/amplify/.config/local-aws-info.json` have?

**Comment by kaustavghosh06** [comment]
@oliverandersencox Please let us know if you're still stuck on this. CLosing this issue due to lack of requestor response.

**Comment by solisarg** [comment]
Having the same issue, contents on local-aws-info.json is

{
    "dev": {
        "configLevel": "project",
        "useProfile": false,
        "awsConfigFilePath": "/Users/jorgesolis/.amplify/awscloudformation/R7GZ3mZY7B"
    }
}

**Comment by solisarg** [comment]
Ok, looking into it, the path was wrong. Corrupt file is probably not the best message, but basically the check on the script check for this

if (configInfo.awsConfigFilePath && fs.existsSync(configInfo.awsConfigFilePath))
