### ISSUE TITLE
If Analytics was provisioned for a project and then removed, apps fail to connect to Amplify console

### ISSUE THREAD

**Issue by jkeys-ecg-nmsu** [aws-amplify/amplify-cli#2154]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
When Analytics category is removed from an Amplify project, backend-config.json and amplify-meta.json contain the analytics category. That causes this error in the Amplify Console Backend step.

```
2019-08-27T16:30:11.865Z [WARNING]: - Initializing your environment: prod
2019-08-27T16:30:12.281Z [WARNING]: ✔ Initialized provider successfully.
2019-08-27T16:30:12.303Z [WARNING]: ✖ There was an error initializing your environment.
2019-08-27T16:30:12.303Z [INFO]: init failed
2019-08-27T16:30:12.305Z [INFO]: { Error: ENOENT: no such file or directory, scandir '/codebuild/output/src051470590/src/**************/amplify/backend/analytics/**************'
                                 at Object.readdirSync (fs.js:790:3)
                                 at validateCfnTemplates (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/push-resources.js:194:22)
                                 at Object.run (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/push-resources.js:33:3)
                                 at Object.pushResources (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/index.js:32:25)
                                 at providerPushTasks.push (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/src/lib/initialize-env.js:81:53)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/promise-sequential/index.js:16:18
                                 at process._tickCallback (internal/process/next_tick.js:68:7)
                                 errno: -2,
                                 syscall: 'scandir',
                                 code: 'ENOENT',
                                 path:
                                 '/codebuild/output/src051470590/src/**************/amplify/backend/analytics/**************' }
```

When removing these keys by hand, Amplify Console build succeeds.

**Comment by kaustavghosh06** [comment]
@jkeys-ecg-nmsu I tried reproducing it in a project and couldn't see this behavior. I'll re-open this issue if anyone else has the same issue.
