### ISSUE TITLE
amplify-cli Install fails

### ISSUE THREAD

**Issue by JonRave3** [aws-amplify/amplify-cli#2204]
**Describe the bug**
Unable to install aws-amplify/cli successfully. Keep getting the following output:
```
C:\Users\212714715>npm install -g @aws-amplify/cli --unsafe-perm=true
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
C:\Users\212714715\AppData\Roaming\npm\amplify -> C:\Users\212714715\AppData\Roaming\npm\node_modules\@aws-amplify\cli\bin\amplify

**> kerberos@0.0.24 install C:\Users\212714715\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\kerberos
> (node-gyp rebuild) || (exit 0)**


**C:\Users\212714715\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\kerberos>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )**
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Program Files\Python36\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\212714715\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\kerberos
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

> fs-ext@0.5.0 install C:\Users\212714715\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\fs-ext
> node-gyp configure build


**C:\Users\212714715\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\fs-ext>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure build )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" configure build )**
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Program Files\Python36\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build"
gyp ERR! cwd C:\Users\212714715\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\fs-ext
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

> snappy@5.0.5 install C:\Users\212714715\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\snappy
> node-gyp rebuild


**C:\Users\212714715\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\snappy>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )**
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Program Files\Python36\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\212714715\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\snappy
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

> amplify-dynamodb-simulator@0.5.0 install C:\Users\212714715\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-dynamodb-simulator
> download --extract -o emulator https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.zip

**RequestError: unable to get local issuer certificate
    at ClientRequest.req.once.err (C:\Users\212714715\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\got\index.js:111:21)**
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm WARN @conduitvc/mosca@2.8.3 requires a peer of leveldown@~1.4.3 but none is installed. You must install peer dependencies yourself.
npm WARN @conduitvc/mosca@2.8.3 requires a peer of ioredis@^1.15.1 but none is installed. You must install peer dependencies yourself.
npm WARN @conduitvc/mosca@2.8.3 requires a peer of mongodb@~2.1.4 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\@aws-amplify\cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.7 (node_modules\@aws-amplify\cli\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fs-ext@0.5.0 (node_modules\@aws-amplify\cli\node_modules\fs-ext):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fs-ext@0.5.0 install: `node-gyp configure build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: snappy@5.0.5 (node_modules\@aws-amplify\cli\node_modules\snappy):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: snappy@5.0.5 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! amplify-dynamodb-simulator@0.5.0 install: `download --extract -o emulator https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.zip`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the amplify-dynamodb-simulator@0.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**To Reproduce**
1. npm install -g @aws-amplify/cli --unsafe-perm=true 

**Expected behavior**
amplify-cli successfully installs with no errors (warnings are acceptable)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node: v10.15.0
 - npm: v6.4.1

i have also tried installing in an elevated cmd prompt and get the same results

**Comment by yuth** [comment]
@JonRave3 are you behind an proxy server?

**Comment by JonRave3** [comment]
i have tried both (behind and not behind one) and get the exact same error messages

**Comment by JonRave3** [comment]
It appears that some of the errors are related to version compatibility with newer versions of python (3.x.x). I've set node to run with python.2.7.4 and no longer receive these specific errors. However issues still persist. closing this issue as resolved. Recommend documentation specify dependency on Python2.7.

**Comment by phsstory** [comment]
@JonRave3 python2.7 is end of life is just over 3 months away (2020-01-01) so that solution is proably not a good workaround
