### ISSUE TITLE
amplify env checkout prod > amplify status > throw up;

### ISSUE THREAD

**Issue by christodupreez** [aws-amplify/amplify-cli#2208]
Hi,

Not sure what's causing this. When I checkout an environment, amplify status produces an error, see below:

```
amplify status

Current Environment: prod

/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/index.js:13
    throw up;
    ^

TypeError: Cannot read property 'charAt' of undefined
    at capitalize (/usr/local/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/resource-status.js:56:14)
    at Object.showResourceTable (/usr/local/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/resource-status.js:285:7)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

I have tried: amplify env pull --restore, but no luck.

What am I doing wrong?

amplify -v
1.7.8

**Comment by nikhname** [comment]
Are you using any custom resources in your project?

**Comment by christodupreez** [comment]
Hi Nikhil,

No custom resources used for this project.

Kind regards,
Christo

**Comment by nikhname** [comment]
@christodupreez What categories are you using in your project? Could you please also check if you can reproduce this with v3.0.0? I am currently unable to reproduce this error.

**Comment by christodupreez** [comment]
@nikhname , I'm using Auth, Api, Hosting & Storage.

I can give v3.0.0 a go.

I have a suspicion that my git is causing the issue. I think I added stuff that should not have been according to .gitignore. Can you perhaps advise me on how to start a new project and importing the categories from the cloud? Or how to get my git sorted to support multi environments?

**Comment by christodupreez** [comment]
Current > amplify -v
1.7.8

Trying to update I get the error below:

npm update -g @aws-amplify/cli

`npm ERR! path /usr/local/bin/amplify
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall unlink
npm ERR! Error: EACCES: permission denied, unlink '/usr/local/bin/amplify'
npm ERR!  { Error: EACCES: permission denied, unlink '/usr/local/bin/amplify'
npm ERR!   cause: 
npm ERR!    { Error: EACCES: permission denied, unlink '/usr/local/bin/amplify'
npm ERR!      errno: -13,
npm ERR!      code: 'EACCES',
npm ERR!      syscall: 'unlink',
npm ERR!      path: '/usr/local/bin/amplify' },
npm ERR!   stack: 'Error: EACCES: permission denied, unlink \'/usr/local/bin/amplify\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'unlink',
npm ERR!   path: '/usr/local/bin/amplify' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).`

**Comment by UnleashedMind** [comment]
@christodupreez 
Try the following to update the amplify cli to the latest version first. 
- `npm remove -g @aws-amplify/cli`
- `npm install -g @aws-amplify/cli`
Maybe add `sudo` in front of the command if there's a permission issue. 

The Amplify CLI currently does NOT support importing an existing category into a new project. 
But you can run `amplify env pull` to pull down the current environment from the cloud.

**Comment by christodupreez** [comment]
I have updated @aws-amplify/cli and now I get another error trying to run amplify status

`amplify status
Scanning for plugins...
Plugin scan successful

Current Environment: dev

Cannot create property 'resourceName' on boolean 'true'
TypeError: Cannot create property 'resourceName' on boolean 'true'
    at /usr/local/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js:137:66
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js:132:37
    at Array.forEach (<anonymous>)
    at getResourcesToBeCreated (/usr/local/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js:130:32)
    at /usr/local/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js:282:44
    at step (/usr/local/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js:33:23)
    at Object.next (/usr/local/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js:14:53)
    at /usr/local/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js:4:12)
    at getResourceStatus (/usr/local/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js:273:12)
    at AmplifyToolkit.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js:320:42)
    at step (/usr/local/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js:33:23)
    at Object.next (/usr/local/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js:14:53)
    at /usr/local/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js:8:71`

**Comment by kaustavghosh06** [comment]
@christodupreez Could you send your `amplify/` directory in the project to `amplify-cli@amazon.com`? We would like to take a look at it and diagnose the issue.

**Comment by christodupreez** [comment]
@kaustavghosh06 I have sent amplify/ to amplify-cli@amazon.com as requested. Thank you.

**Comment by SwaySway** [comment]
```json
	"analytics": {
		"disabled": true
	},
```

This doesn't look like an artifact that is generated by the CLI. Was this added in manually? Could you try to do a push with this removed from your project?

**Comment by christodupreez** [comment]
It is generated automatically for some reason.

I removed the "analytics": {"disabled": true} from all the files and then tried to amplify push but I still get the same error, so then I ran amplify init and followed the steps, then the  "analytics": {"disabled": true} reappeared, followed by the error, see below:

```
amplify init
Note: It is recommended to run this command from the root of your app directory
? Do you want to use an existing environment? Yes
? Choose the environment you would like to use: prod
? Choose your default editor: Visual Studio Code
Using default provider  awscloudformation

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html

? Do you want to use an AWS profile? Yes
? Please choose the profile you want to use amplify-user
✔ Initialized provider successfully.
✖ There was an error initializing your environment.
init failed
TypeError: Cannot create property 'resourceName' on boolean 'true'
    at /usr/local/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js:175:73
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js:173:37
    at Array.forEach (<anonymous>)
    at getResourcesToBeDeleted (/usr/local/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js:171:39)
    at AmplifyToolkit.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js:286:44)
    at step (/usr/local/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js:33:23)
    at Object.next (/usr/local/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js:14:53)
    at fulfilled (/usr/local/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js:5:58)
    at <anonymous>
```

**Comment by nikhname** [comment]
@christodupreez Could you try replacing 
"analytics": {
		"disabled": true
	},
with 
"analytics": {}
and trying a push?
