### ISSUE TITLE
Add User to Group failure

### ISSUE THREAD

**Issue by danhumphrey** [aws-amplify/amplify-cli#2214]
**Describe the bug**
I added the Auth service and chose the 'Add User To Group' trigger. After adding a user I got some failures in CloudWatch for the first confirmed user. 

The second time I added and confirmed a user, there were no failures.

**To Reproduce**
1. Add auth and choose the trigger 'Add User to Group'
2. Use the default function
3. push to AWS
4. Sign up and confirm a user
5. Check the CloudWatch logs

**Logs**

`2019-09-06T05:41:15.573Z	9ef8078d-ff5e-42b1-8837-2f3cb229f479	(node:1) UnhandledPromiseRejectionWarning: ResourceNotFoundException: Group not found.
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:51:27)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)`

`2019-09-06T05:41:15.611Z	9ef8078d-ff5e-42b1-8837-2f3cb229f479	(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)`

`2019-09-06T05:41:15.611Z	9ef8078d-ff5e-42b1-8837-2f3cb229f479	(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

`2019-09-06T05:41:15.825Z	9ef8078d-ff5e-42b1-8837-2f3cb229f479	(node:1) UnhandledPromiseRejectionWarning: GroupExistsException: A group with the name already exists.
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:51:27)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)`

`2019-09-06T05:41:15.825Z	9ef8078d-ff5e-42b1-8837-2f3cb229f479	(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)`

**Expected behavior**
The user should be added to the group without errors

**Additional context**
cli version 3.0.0

**Comment by haverchuck** [comment]
@danhumphrey Did the first user still get added to the group?

**Comment by danhumphrey** [comment]
Looks good, thanks for the quick turnaround!

**Comment by kaustavghosh06** [comment]
We released a new version of the CLI - v3.8.0 with a fix for this.
