### ISSUE TITLE
CLI Lambda Function as trigger for non-CLI DynamoDB table?

### ISSUE THREAD

**Issue by sopranolinist** [aws-amplify/amplify-cli#2256]
** Which Category is your question related to? **
Lambda Functions, Storage

** What AWS Services are you utilizing? **
API, Storage

** Provide additional details e.g. code snippets **
Is it possible to add a lambda function created with the Amplify CLI as a trigger for a DynamoDB table that was NOT created with `amplify add storage`? 

I have a DynamoDB table that was created when I added a GraphQL API with the `@model` directive using `amplify add api`. The guide [here](https://aws-amplify.github.io/docs/cli-toolchain/quickstart#dynamodb-lambda-triggers) says if I want to associate a CLI-created lambda function with a DynamoDB table, I should run `amplify update storage` but running that command and selecting `NoSQL Database` does not list my DynamoDB table, instead it generates an error: 
```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at updateWalkthrough (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-storage/provider-utils/awscloudformation/service-walkthroughs/dynamoDb-walkthrough.js:23:10)
    at Object.updateResource (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-storage/provider-utils/awscloudformation/index.js:29:10)
    at amplify.serviceSelectionPrompt.then (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-storage/commands/storage/update.js:21:35)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
An error occurred when updating the storage resource.
```

**Comment by ambientlight** [comment]
It's actually a valid question. Can you reopen it?

`@model` backed dynamoDB tables actually come with stream(New and old images) enabled. 
It would make sense if there is out of the box support for adding triggers to them.

**Comment by sopranolinist** [comment]
@ambientlight I closed it because there are other open tickets that already raised this issue: https://github.com/aws-amplify/amplify-cli/issues/997
