### ISSUE TITLE
CLI version 3.2: Cannot read property 'defaultAuthentication' of undefined

### ISSUE THREAD

**Issue by andreialecu** [aws-amplify/amplify-cli#2275]
I'm using a pre-build script on a CI server to push resources to the cloud. Since updating the cli to version 3.2, it started throwing this error:

GraphQL schema compiled successfully.

```
Edit your schema at /Users/vsts/agent/2.155.1/work/1/s/amplify/backend/api/projectsport/schema.graphql or place .graphql files in a directory at /Users/vsts/agent/2.155.1/work/1/s/amplify/backend/api/projectsport/schema
✖ An error occurred when pushing the resources to the cloud
✖ There was an error initializing your environment.
init failed
TypeError: Cannot read property 'defaultAuthentication' of undefined
    at getApiKeyConfigured (/Users/vsts/.nvm/versions/node/v10.16.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/upload-appsync-files.js:68:24)
    at writeUpdatedParametersJson (/Users/vsts/.nvm/versions/node/v10.16.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/upload-appsync-files.js:85:30)
    at uploadAppSyncFiles (/Users/vsts/.nvm/versions/node/v10.16.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/upload-appsync-files.js:166:5)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

The contents of the pre-build script is as follows:

```bash
#!/usr/bin/env bash

npm install -g @aws-amplify/cli

AWSCONFIG="{\
\"configLevel\":\"general\"\
}"

AMPLIFY="{\
\"envName\":\"${AMPLIFY_ENV}\"\
}"

PROVIDERS="{\
\"awscloudformation\":${AWSCONFIG}\
}"

CODEGEN="{\
\"generateCode\":false,\
\"generateDocs\":false\
}"

amplify init --amplify ${AMPLIFY} --providers ${PROVIDERS} --codegen ${CODEGEN} --yes
amplify push --codegen $CODEGEN --yes
```

Reverting the CLI to version 2.0.0 makes everything work again.

AWS authentication is provided through regular ENV variables (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION). 

The CI server is Microsoft AppCenter.

**Comment by attilah** [comment]
@andreialecu thanks for reporting this issue, it is already fixed by #2261
