### ISSUE TITLE
Creating backend on Amplify Console fails.

### ISSUE THREAD

**Issue by hi120ki** [aws-amplify/amplify-cli#2362]
I set amplify latest version on Amplify Console.

Yesterday 2019/9/19, released amplify-cli 3.8.0, fails to creating backend on Amplify Console.
and today 2019/9/20, released amplify-cli 3.9.0, fails same situation.
(2019/9/18 amplify-cli 3.7.0, succeed to deploy)

Running "amplify push" in local has no problem. (every amplify-cli version)

My Amplify Console log is here

```
# Starting phase: build
                                 # Executing command: amplifyPush --simple
2019-09-19T04:06:33.181Z [INFO]: # Getting Amplify CLI Cloud-Formation stack info from environment cache
2019-09-19T04:06:33.189Z [INFO]: # Start initializing Amplify environment: env
2019-09-19T04:06:33.194Z [INFO]: STACKINFO=context.print.fancy is not a function
                                 TypeError: context.print.fancy is not a function
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env/get.js:53:35
                                 at step (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env/get.js:33:23)
                                 at Object.next (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env/get.js:14:53)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env/get.js:8:71
                                 at new Promise (<anonymous>)
                                 at __awaiter (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env/get.js:4:12)
                                 at Object.run (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env/get.js:41:38)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env.js:64:56
                                 at step (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env.js:33:23)
                                 at Object.next (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env.js:14:53)
                                 # Importing Amplify environment: env (amplify env import)
2019-09-19T04:06:34.137Z [INFO]: Scanning for plugins...
2019-09-19T04:06:41.925Z [INFO]: Plugin scan successful
2019-09-19T04:06:41.939Z [INFO]: You must pass in the configs of the environment in an object format using the --config flag
2019-09-19T04:06:41.984Z [ERROR]: !!! Build failed
2019-09-19T04:06:42.076Z [ERROR]: !!! Non-Zero Exit Code detected
2019-09-19T04:06:42.076Z [INFO]: # Starting environment caching...
2019-09-19T04:06:42.077Z [INFO]: # Uploading environment cache artifact...
2019-09-19T04:06:42.178Z [INFO]: # Environment caching completed
Terminating logging...
```

and my amplify.yml is

```yml
version: 0.1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn
    build:
      commands:
        - yarn build
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
  customHeaders:
    - pattern: '**/*'
      headers:
      - key: 'X-Frame-Options'
        value: 'deny'
      - key: 'X-XSS-Protection'
        value: '1; mode=block'
      - key: 'X-Content-Type-Options'
        value: 'nosniff'
```

Maybe I did't commit critical change on my project.

I'm waiting for your great support. Thank you.

**Comment by attilah** [comment]
@hi120ki The root cause seems to be the missing function as it is in #2351. We already did a fix and it is in the latest release, please try it out and re-open if the issue still exists for you

**Comment by hi120ki** [comment]
I try to deploy again.

Checking log, amplify 3.9.0 is installed.

```
2019-09-20T10:32:35.452Z [INFO]: # Ensuring NPM package '@aws-amplify/cli' is version: 'latest'
2019-09-20T10:32:42.573Z [INFO]: # Patching NPM package '@aws-amplify/cli' from 1.12.0 to 3.9.0...
```

But still deploy has error.

```
                                 # Starting phase: build
                                 # Executing command: amplifyPush --simple
2019-09-20T10:33:46.817Z [INFO]: # Getting Amplify CLI Cloud-Formation stack info from environment cache
2019-09-20T10:33:46.824Z [INFO]: # Start initializing Amplify environment: env
2019-09-20T10:33:46.828Z [INFO]: STACKINFO=context.print.fancy is not a function
                                 TypeError: context.print.fancy is not a function
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env/get.js:53:35
                                 at step (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env/get.js:33:23)
                                 at Object.next (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env/get.js:14:53)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env/get.js:8:71
                                 at new Promise (<anonymous>)
                                 at __awaiter (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env/get.js:4:12)
                                 at Object.run (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env/get.js:41:38)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env.js:64:56
                                 at step (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env.js:33:23)
                                 at Object.next (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env.js:14:53)
                                 # Importing Amplify environment: env (amplify env import)
2019-09-20T10:33:47.776Z [INFO]: Scanning for plugins...
2019-09-20T10:33:54.791Z [INFO]: Plugin scan successful
2019-09-20T10:33:54.873Z [INFO]: You must pass in the configs of the environment in an object format using the --config flag
2019-09-20T10:33:54.924Z [ERROR]: !!! Build failed
2019-09-20T10:33:54.924Z [ERROR]: !!! Non-Zero Exit Code detected
2019-09-20T10:33:54.924Z [INFO]: # Starting environment caching...
2019-09-20T10:33:54.924Z [INFO]: # Uploading environment cache artifact...
2019-09-20T10:33:55.021Z [INFO]: # Environment caching completed
Terminating logging...
```
```

**Comment by mrducky4** [comment]
I think this should be reopened. I have the same problem. I had CLI version 3.8.0. I had the problem #2351 on my local machine. I upgraded my local machine to CLI version 3.9.0, which fixed that problem. However, on AWS Console when I specified to use Amplify CLI 3.9.0 it still fails with "context.print.fancy is not a function". My log looks just like the one posted by hi120ki.

**Comment by hi120ki** [comment]
Maybe you know, it is not able to re-open issue from me.
There are no "Reopen issue" button on my display.
(On GitHub, if you are not a collaborator of a repo, you can re-open your own issues if you closed them yourself)

@attilah Could you re-open this issue? I can't re-open this issue myself.
