### ISSUE TITLE
Creating backend on Amplify Console fails v3.9.0

### ISSUE THREAD

**Issue by hi120ki** [aws-amplify/amplify-cli#2364]
This issue is related with #2362 

I try to deploy my project on Amplify Console, but an error still happened.
(I have already tried amplify-cli v3.9.0 at #2362)

My log is here.

```
2019-09-20T10:32:35.452Z [INFO]: # Ensuring NPM package '@aws-amplify/cli' is version: 'latest'
2019-09-20T10:32:42.573Z [INFO]: # Patching NPM package '@aws-amplify/cli' from 1.12.0 to 3.9.0...
```

```
                                 # Starting phase: build
                                 # Executing command: amplifyPush --simple
2019-09-20T10:33:46.817Z [INFO]: # Getting Amplify CLI Cloud-Formation stack info from environment cache
2019-09-20T10:33:46.824Z [INFO]: # Start initializing Amplify environment: env
2019-09-20T10:33:46.828Z [INFO]: STACKINFO=context.print.fancy is not a function
                                 TypeError: context.print.fancy is not a function
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env/get.js:53:35
                                 at step (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env/get.js:33:23)
                                 at Object.next (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env/get.js:14:53)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env/get.js:8:71
                                 at new Promise (<anonymous>)
                                 at __awaiter (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env/get.js:4:12)
                                 at Object.run (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env/get.js:41:38)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env.js:64:56
                                 at step (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env.js:33:23)
                                 at Object.next (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env.js:14:53)
                                 # Importing Amplify environment: env (amplify env import)
2019-09-20T10:33:47.776Z [INFO]: Scanning for plugins...
2019-09-20T10:33:54.791Z [INFO]: Plugin scan successful
2019-09-20T10:33:54.873Z [INFO]: You must pass in the configs of the environment in an object format using the --config flag
2019-09-20T10:33:54.924Z [ERROR]: !!! Build failed
2019-09-20T10:33:54.924Z [ERROR]: !!! Non-Zero Exit Code detected
2019-09-20T10:33:54.924Z [INFO]: # Starting environment caching...
2019-09-20T10:33:54.924Z [INFO]: # Uploading environment cache artifact...
2019-09-20T10:33:55.021Z [INFO]: # Environment caching completed
Terminating logging...
```

This is same error message at v3.8.0 and v3.9.0.

And this error message is little different from #2351 at line 14

```
at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env.js:64:56
```

I'm waiting for your great support. Thank you.

**Comment by attilah** [comment]
@hi120ki it is the same error, please don't open multiple issues about the same problem. The line number can differ between releases.

Perhaps that fix did not make into 3.9.0, so it will be in the next one.

A workaround would be for you If you would not use the ```json``` argument, which references the ```fancy``` function.
