### ISSUE TITLE
Cant Install CLI Correctly

### ISSUE THREAD

**Issue by Spaceman1861** [aws-amplify/amplify-cli#2371]
**Describe the bug**
Im trying to install the cli via the following
`npm install -g @aws-amplify/cli`

I get a bunch of errors during the install however it says it installed correctly.

But then when I run.
`amplify configure`

I get a prompt saying.
> ? Select the backend providers. (Press <space> to select, <a> to toggle all, <i> to invert selection)

Any key I press just exits amplify.

Im using node 10.16.3
Im using npm 6.9.0

Here is the npm output

```npm install -g @aws-amplify/cli
npm WARN deprecated @types/ora@3.2.0: This is a stub types definition. ora provides its own type definitions, so you do not need this installed.
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
C:\Users\REDACTED\AppData\Roaming\npm\amplify -> C:\Users\REDACTED\AppData\Roaming\npm\node_modules\@aws-amplify\cli\bin\amplify

> fs-ext@0.5.0 install C:\Users\REDACTED\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\fs-ext
> node-gyp configure build


C:\Users\REDACTED\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\fs-ext>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure build )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" configure build )
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
VCBUILD : error : project file 'C:\Users\REDACTED\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\fs-ext\build\fs-ext.vcproj' was not found or not a valid project file. [C:\Users\REDACTED\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\fs-ext\build
\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build"
gyp ERR! cwd C:\Users\REDACTED\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\fs-ext
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

> snappy@5.0.5 install C:\Users\REDACTED\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\snappy
> node-gyp rebuild


C:\Users\REDACTED\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\snappy>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
VCBUILD : error : project file 'C:\Users\REDACTED\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\snappy\build\deps\snappy\snappy.vcproj' was not found or not a valid project file. [C:\Users\REDACTED\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\
snappy\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\REDACTED\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\snappy
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

> zmq@2.15.3 install C:\Users\REDACTED\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\zmq
> node-gyp rebuild


C:\Users\REDACTED\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\zmq>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
VCBUILD : error : project file 'C:\Users\REDACTED\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\zmq\build\zmq.vcproj' was not found or not a valid project file. [C:\Users\REDACTED\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\zmq\build\binding.
sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\REDACTED\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\zmq
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

> @aws-amplify/cli@3.9.0 postinstall C:\Users\REDACTED\AppData\Roaming\npm\node_modules\@aws-amplify\cli
> node scripts/post-install.js

Ignore installation errors for optional dependencies: gyp, fs-ext


----------------------------------------
Successfully installed the Amplify CLI
----------------------------------------


Javascript Getting Started - https://aws-amplify.github.io/docs/js/start


Android Getting Started - https://aws-amplify.github.io/docs/android/start


iOS Getting Started - https://aws-amplify.github.io/docs/ios/start


npm WARN @conduitvc/mosca@2.8.3 requires a peer of leveldown@~1.4.3 but none is installed. You must install peer dependencies yourself.
npm WARN @conduitvc/mosca@2.8.3 requires a peer of ioredis@^1.15.1 but none is installed. You must install peer dependencies yourself.
npm WARN @conduitvc/mosca@2.8.3 requires a peer of mongodb@~2.1.4 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.7 (node_modules\@aws-amplify\cli\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\@aws-amplify\cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fs-ext@0.5.0 (node_modules\@aws-amplify\cli\node_modules\fs-ext):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fs-ext@0.5.0 install: `node-gyp configure build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: snappy@5.0.5 (node_modules\@aws-amplify\cli\node_modules\snappy):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: snappy@5.0.5 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: zmq@2.15.3 (node_modules\@aws-amplify\cli\node_modules\zmq):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: zmq@2.15.3 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ @aws-amplify/cli@3.9.0
updated 1 package in 53.855s```

**Expected behavior**
Amplify configure to run.

If anyone can point me in the right direction that would be mad :D

**Comment by UnleashedMind** [comment]
@Spaceman1861 

On what Operating System did you run the amplify command?
Could you try to run `amplify plugin scan` then try again?
If it still fails, please try to run `amplify plugin list`, select `active plugins` and see if there is a plugin named 'awscloudformation` in the list.

**Comment by Spaceman1861** [comment]
@UnleashedMind running amplify plugin can fixed it.

Thanks

As a side note i'm running latest windows 10.
