### ISSUE TITLE
Error when deploying through aws amplify console CI

### ISSUE THREAD

**Issue by incr3m** [aws-amplify/amplify-cli#2377]
We're currently getting the error below when deploying changes on amplify console ci:
![image](https://user-images.githubusercontent.com/3125784/65403889-9dcbe200-de08-11e9-9fa1-916fdf242371.png)
Current version we use is 3.8.0. We did not change any config on amplify ci console. It was working before,

**Comment by im-dnsosso** [comment]
same problem after upgrade to 3.9.0

**Comment by thedgbrt** [comment]
I've had issues with the amplify console since updating too. For me it was because the version of amplify-cli in the console was an old one (by default it was 1.7.0). You can see which version of the cli the console in using in the provision step:

<img width="1095" alt="Capture d’écran 2019-09-23 à 11 52 25" src="https://user-images.githubusercontent.com/1362558/65416700-be8c3b80-ddf8-11e9-9748-581a0bbf321e.png">

The solution is to override it in Build settings > Build image settings > Live package updates 

<img width="630" alt="Capture d’écran 2019-09-23 à 11 51 33" src="https://user-images.githubusercontent.com/1362558/65416588-81c04480-ddf8-11e9-89f7-0dd015f76654.png">

On the next generation, the right amplify-cli version will be installed at the end of the "cloning repository" step. 
<img width="1096" alt="Capture d’écran 2019-09-23 à 11 54 24" src="https://user-images.githubusercontent.com/1362558/65416877-15921080-ddf9-11e9-8b16-5468224fce16.png">

**Comment by im-dnsosso** [comment]
Yes I adjusted those settings but the problem remain the same... The interesting part is I can deploy it from local cli with amplify push but it does not work from the cloud.

**Comment by thedgbrt** [comment]
@im-dnsosso i've had issues like that too. Right now when that happens I just re-push from local and re-run the cloud deployment right after. It has worked so far but it's not reassuring...

**Comment by thedgbrt** [comment]
@im-dnsosso did you try this ? https://github.com/aws-amplify/amplify-cli/issues/1415#issuecomment-490297162

**Comment by im-dnsosso** [comment]
Thank you! Let me try that...

**Comment by im-dnsosso** [comment]
`                                 # Starting phase: build
                                 # Executing command: amplifyPush --simple
2019-09-23T10:16:58.646Z [INFO]: # Getting Amplify CLI Cloud-Formation stack info from environment cache
2019-09-23T10:16:58.652Z [INFO]: # Start initializing Amplify environment: develop
2019-09-23T10:16:58.653Z [INFO]: STACKINFO=context.print.fancy is not a function
                                 TypeError: context.print.fancy is not a function
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env/get.js:53:35
                                 at step (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env/get.js:33:23)
                                 at Object.next (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env/get.js:14:53)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env/get.js:8:71
                                 at new Promise (<anonymous>)
                                 at __awaiter (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env/get.js:4:12)
                                 at Object.run (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env/get.js:41:38)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env.js:67:56
                                 at step (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env.js:33:23)
                                 at Object.next (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env.js:14:53)
                                 # Importing Amplify environment: develop (amplify env import)
2019-09-23T10:16:59.467Z [INFO]: Scanning for plugins...
2019-09-23T10:17:06.445Z [INFO]: Plugin scan successful
2019-09-23T10:17:06.462Z [INFO]: You must pass in the configs of the environment in an object format using the --config flag
2019-09-23T10:17:06.509Z [ERROR]: !!! Build failed
2019-09-23T10:17:06.561Z [ERROR]: !!! Non-Zero Exit Code detected
2019-09-23T10:17:06.561Z [INFO]: # Starting environment caching...
2019-09-23T10:17:06.561Z [INFO]: # Uploading environment cache artifact...
2019-09-23T10:17:06.598Z [INFO]: # Environment caching completed
`

Same problem... I deleted the cache option from the buildspec but still no luck...

**Comment by RossWilliams** [comment]
I am also seeing this issue on my latest deploy.

**Comment by kaustavghosh06** [comment]
This is an issue tied to the Amplify console not able to switch CLI versions - they've been informed and looking into it. Moving it to the console team repo to further investigate and provide a workaround for the same.
