### ISSUE TITLE
amplify api update results in error: Cannot redefine property: flatMap

### ISSUE THREAD

**Issue by jeanpaulcozzatti** [aws-amplify/amplify-cli#239]
amplify api update results in error: Cannot redefine property: flatMap

When running 

` amplify api update
`
I get 

```
TypeError: Cannot redefine property: flatMap
    at Function.defineProperty (<anonymous>)
    at Object.<anonymous> (/usr/local/Cellar/node/9.11.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-appsync-codegen/src/utilities/array.ts:9:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/Cellar/node/9.11.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-appsync-codegen/src/compiler/legacyIR.ts:10:1)
```

**Comment by elorzafe** [comment]
@jeanpaulcozzatti Did you change update node after creating the project?

**Comment by elorzafe** [comment]
That happened to me and after running `amplify configure project` and confirmed default values the problem was solved.

**Comment by kaustavghosh06** [comment]
@jeanpaulcozzatti Please feel to re-open this issue if the problem still persists.
