### ISSUE TITLE
Amplify API codegen fails -  UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, mkdir 'D:\'

### ISSUE THREAD

**Issue by pnadkar** [aws-amplify/amplify-cli#2418]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
After the latest install of ampliy 3.10.0, did a codegen with api id

**To Reproduce**
1. Go to 'command prompt root'
2. Paste this for the code gen amplify add codegen --apiId <API_ID_HERE>
3. See error
```
amplify add codegen --apiId <API_ID_HERE>
√ Getting API details
Successfully added API <API_NAME> to your Amplify project
? Choose the code generation language target (Use arrow keys)
> angular
  typescript (node:34968) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, mkdir 'D:\'
    at Object.mkdirSync (fs.js:775:3)
    at mkdirsSync (C:\Users\Praneet\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\fs-extra\lib\mkdirs\mkdirs-sync.js:31:9)
    at mkdirsSync (C:\Users\Praneet\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\fs-extra\lib\mkdirs\mkdirs-sync.js:36:14)
    at mkdirsSync (C:\Users\Praneet\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\fs-extra\lib\mkdirs\mkdirs-sync.js:36:14)
    at Object.mkdirsSync (C:\Users\Praneet\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\fs-extra\lib\mkdirs\mkdirs-sync.js:36:14)
    at generateAWSExportsFile (C:\Users\Praneet\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-frontend-javascript\lib\frontend-config-creator.js:162:6)
    at createAWSExports (C:\Users\Praneet\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-frontend-javascript\lib\frontend-config-creator.js:47:3)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:34968) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:34968) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
**Expected behavior**
It should add the API.ts and update the meta json files. It is updating the meta json files, but it still throws an error

**Comment by nikhname** [comment]
Hi @pnadkar, what OS are you running this on?

**Comment by nikhname** [comment]
@pnadkar Can you please update to the latest version of the cli (3.14.0) and see if you still have this issue? I was not able to reproduce this on 3.14.0 with an angular project.

**Comment by pnadkar** [comment]
Updating the cli worked

**Comment by tgjorgoski** [comment]
I'm getting this on 3.16.0 , and after updating also on 3.17.0
when I try:
amplify codegen types
(with or without --nodownload)

The error is:
 ✖ ENOENT: no such file or directory, open '/webapp/amplify/backend/api/hubhighup/build/schema.graphql'

**Comment by tgjorgoski** [comment]
Succeeded to solve it by getting clean code from git, and doing amplify init, and amplify codegen add again.
