### ISSUE TITLE
amplify init TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by ozten** [aws-amplify/amplify-cli#250]
**Describe the bug**
After a new install of aws-amplify in an empty project, running `amplify init` correctly lists editor options, but then the list of "types of apps" to create is empty. Pressing enter results in a JS error.

**To Reproduce**
1. `npm install @aws-amplify/cli`
2. Go to CLI and enter `./node_modules/.bin/amplify init`
3. Press enter to pick the first editor
4. Note: **Choose the type of app that you're building** has no options.
5. Press enter
6. See error `TypeError: Cannot read property 'value' of undefined`

**Expected behavior**
amplify init should have listed types of apps such as `javascript`.

**Screenshots**

    amplify init
    Note: It is recommended to run this command from the root of your app directory
    ? Choose your default editor: None
    ? Choose the type of app that you're building (Use arrow keys)

    readline.js:1020
                throw err;
                ^

    TypeError: Cannot read property 'value' of undefined
        at Prompt.getCurrentValue (/Users/ozten/projects/CMSv0/node_modules/inquirer/lib/prompts/list.js:126:51)
        at tryCatcher (/Users/ozten/projects/CMSv0/node_modules/rx-lite/rx.lite.js:67:31)
        at InnerObserver.next (/Users/ozten/projects/CMSv0/node_modules/rx-lite/rx.lite.js:4495:43)
        at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/ozten/projects/CMSv0/node_modules/rx-lite/rx.lite.js:1602:31)
        at InnerObserver.tryCatcher (/Users/ozten/projects/CMSv0/node_modules/rx-lite/rx.lite.js:67:31)
        at AutoDetachObserverPrototype.next (/Users/ozten/projects/CMSv0/node_modules/rx-lite/rx.lite.js:6495:51)
        at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/ozten/projects/CMSv0/node_modules/rx-lite/rx.lite.js:1602:31)
        at TakeObserver.next (/Users/ozten/projects/CMSv0/node_modules/rx-lite/rx.lite.js:4681:17)
        at TakeObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/ozten/projects/CMSv0/node_modules/rx-lite/rx.lite.js:1602:31)
        at TakeObserver.tryCatcher (/Users/ozten/projects/CMSv0/node_modules/rx-lite/rx.lite.js:67:31)

**Desktop (please complete the following information):**
 - OS: Mac OS X 10.13.6 (17G65)
 - NodeJS: v8.12.0

**Additional context**
I'm new to amplify and have never installed or run it before.

**Comment by yuth** [comment]
@ozten Could you install amplify-cli globally by running `npm install -g  @aws-amplify/cli` for time being. 

We will have a fix for this in a bit

**Comment by kaustavghosh06** [comment]
The fix for this is merged in the latest version of the CLI -> 0.1.28. You can now locally install the install.
