### ISSUE TITLE
add-graphql-datasource - aurora serverless - update fails

### ISSUE THREAD

**Issue by raelmiu** [aws-amplify/amplify-cli#2510]
When running `amplify add-graphql-datasource` to update the schema, old schema changes seem to conflict with the script:

```
$ amplify api add-graphql-datasource
Using datasource: Aurora Serverless, provided by: awscloudformation
? Provide the region in which your cluster is located: us-east-1
? Select the Aurora Serverless cluster that will be used as the data source for your API: champagne-glory-us-east-1
✔ Fetched Aurora Serverless cluster.
? Select the database to use as the datasource: ChampagneGlory
Error: Unable to merge GraphQL type "Users": asNext is not iterable
    at Object.mergeType (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-toolkit/src/epoxy/typedefs-mergers/type.ts:20:13)
    at nodes.reduce (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-toolkit/src/epoxy/typedefs-mergers/merge-nodes.ts:42:22)
    at Array.reduce (<anonymous>)
    at Object.mergeGraphQLNodes (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-toolkit/src/epoxy/typedefs-mergers/merge-nodes.ts:29:16)
    at mergeGraphQLTypes (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-toolkit/src/epoxy/typedefs-mergers/merge-typedefs.ts:228:40)
    at Object.mergeTypeDefs (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-toolkit/src/epoxy/typedefs-mergers/merge-typedefs.ts:93:18)
    at mergeTypes (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/merge-graphql-schemas/src/merge_types.ts:9:10)
    at datasourceSelectionPrompt.then.then.then (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/commands/api/add-graphql-datasource.js:116:12)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
There was an error adding the datasource
```

**To Reproduce**
1. Setup an aws amplify project with an aurora api backend
2. Run amplify add-graphql-datasource
3. Make schema changes manually (not sure if optional)
4. Update database tables
5. run amplify add-graphql-datasource again
6. See error

**Expected behavior**
Either an updated schema, or an error message that can be solved.

**Desktop (please complete the following information):**
 - MacOS 10.14.6 (18G87)
 - Amplify 3.10.0

**Comment by yuth** [comment]
@raelmiu Do you have type `User` already in your existing schema? Are there any other type collisions in existing schema, and have a table with the same name in  RDS?

**Comment by raelmiu** [comment]
Yes, the User is already in the schema. Actually there are two "User" from DynamoDB and "Users" from RDS.
Not in conflict, but that should be updated, yes?

**Comment by yuth** [comment]
> Not in conflict, but that should be updated, yes?

Merging `User` would cause problems as the data is stored in 2 data stores and resolvers used for them are different. The resolver is not equipped to fetch data from 2 different data sources and merge them together. 

Could you try renaming one of the types and see if you are still having the same issue.

**Comment by raelmiu** [comment]
I don't think it's an issue of Model names. But I removed all the references to `User`and got this error:

```
Error: Unable to merge GraphQL input type "CreateUsersInput": asNext is not iterable
    at Object.mergeInputType (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-toolkit/src/epoxy/typedefs-mergers/input-type.ts:23:13)
    at nodes.reduce (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-toolkit/src/epoxy/typedefs-mergers/merge-nodes.ts:50:22)
    at Array.reduce (<anonymous>)
    at Object.mergeGraphQLNodes (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-toolkit/src/epoxy/typedefs-mergers/merge-nodes.ts:29:16)
    at mergeGraphQLTypes (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-toolkit/src/epoxy/typedefs-mergers/merge-typedefs.ts:228:40)
    at Object.mergeTypeDefs (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-toolkit/src/epoxy/typedefs-mergers/merge-typedefs.ts:93:18)
    at mergeTypes (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/merge-graphql-schemas/src/merge_types.ts:9:10)
    at datasourceSelectionPrompt.then.then.then (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/commands/api/add-graphql-datasource.js:116:12)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
There was an error adding the datasource
```

Which is the same as the last one.

**Comment by nikhname** [comment]
@raelmiu could you provide the query you used to create this table? In particular, what is your primary key and its type?

**Comment by nikhname** [comment]
@raelmiu The way the transformer is currently set up, you can only run add-graphql-datasource once per api. Updating the RDS table is a valid use case however so I'm marking this as an enhancement. As a workaround you can remove the api and add it again, then run add-graphql-datasource with the updated tables.

**Comment by raelmiu** [comment]
The primary keys are char(36) on all my entities.

That explains it @nikhname , but I got the impression I should be able to update it from this article: 
https://aws-amplify.github.io/docs/cli-toolchain/graphql?sdk=js#how-does-this-work
```
You may run add-graphql-datasource again to update your project with changes in the database but be careful as these will overwrite any existing templates in the stacks/ or resolvers/ directories.
```

**Comment by nikhname** [comment]
Because updating in that way is mentioned in the docs I have marked this as a bug. In the mean time you can try deleting the api and adding it back with the updated datasource as a work around.

**Comment by raelmiu** [comment]
For posterity: Tried the workaround with deleting the API and adding a new one, worked fine.

**Comment by stephanrb3** [comment]
I'm also experiencing this issue? I'm attempting to delete and retry.

**Comment by emersonhsieh** [comment]
I ran into the same issue when adding a new table to the same Aurora database and running `amplify api add-graphql-datasource`. After I deleted all the existing types and inputs from `schema.graphql` and all the resolvers in the resolvers directory, the command succeeded. The schemas and resolvers was then automatically regenerated.

**Comment by raelmiu** [comment]
I've just run into this problem again. With many-to-many relationships the middle model cannot be saved. Debugging as we speak. But I'm surprised these similar issues keep appearing.
