### ISSUE TITLE
Unable to add Lambda function with CLI "Resource is not in the state stackUpdateComplete"

### ISSUE THREAD

**Issue by magjack** [aws-amplify/amplify-cli#2621]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **
Amplify add Function

** What AWS Services are you utilizing? **
Amplify, Cognito, Graphql, Lambda

** Provide additional details e.g. code snippets **
I am trying to connect to a graphql endpoint from a Lambda function. I am following this [documentation ](https://aws-amplify.github.io/docs/cli-toolchain/quickstart#graphql-from-lambda). I have tried several times to create the function via add api and add function and giving the lambda the correct permissions. However, even when attempting to create the basic hello world example with no additional permissions I am faced with the same error. See CLI Usage 

```console
c:\Users\Jack\Documents\Roundin\roundin-customer-app>amplify status

Current Environment: dev

| Category | Resource name              | Operation | Provider plugin   |
| -------- | -------------------------- | --------- | ----------------- |
| Auth     | roundinbusinessappf7f2ffdg | No Change | awscloudformation |
| Api      | roundin                    | No Change | awscloudformation |

GraphQL endpoint: https://dfghjjdjxrdshjjfrwxc5ydfhe.appsync-api.eu-west-1.amazonaws.com/graphql


c:\Users\Jack\Documents\Roundin\roundin-customer-app>amplify add function
Using service: Lambda, provided by: awscloudformation
? Provide a friendly name for your resource to be used as a label for this category in the project: exampleLambda
? Provide the AWS Lambda function name: exampleLambda
? Choose the function template that you want to use: Hello world function
? Do you want to access other resources created in this project from your Lambda function? No
? Do you want to edit the local lambda function now? Yes
Please edit the file in your editor: c:\Users\Jack\Documents\Roundin\roundin-customer-app\amplify\backend/function/exampleLambda/src/index.js? Press enter to continue Selected  editor code was not found in your machine. Please manually edit the file created at c:\Users\Jack\Documents\Roundin\roundin-customer-app\amplify\backend/function/exampleLambda/src/index.js
? Press enter to continue
Successfully added resource exampleLambda locally.

Next steps:
Check out sample function code generated in <project-dir>/amplify/backend/function/exampleLambda/src
"amplify function build" builds all of your functions currently in the project
"amplify function invoke exampleLambda" enables you to test a function locally
"amplify push" builds all of your local backend resources and provisions them in the cloud
"amplify publish" builds all of your local backend and front-end resources (if you added hosting category) and provisions them in the cloud


c:\Users\Jack\Documents\Roundin\roundin-customer-app>amplify build function
? Are you sure you want to continue building the resources? Yes
√ All resources are built.

c:\Users\Jack\Documents\Roundin\roundin-customer-app>amplify function invoke exampleLambda
Using service: Lambda, provided by: awscloudformation
? Provide the name of the script file that contains your handler function: index.js
? Provide the name of the handler function to invoke: handler
? Provide the relative path to the event: event.json
Testing function locally
value1 = value1
value2 = value2
value3 = value3

Success!  Message:
------------------
Hello World

c:\Users\Jack\Documents\Roundin\roundin-customer-app>amplify push

Current Environment: dev

| Category | Resource name              | Operation | Provider plugin   |
| -------- | -------------------------- | --------- | ----------------- |
| Function | exampleLambda              | Create    | awscloudformation |
| Auth     | roundinbusinessapp | No Change | awscloudformation |
| Api      | roundin                    | No Change | awscloudformation |
? Are you sure you want to continue? Yes


GraphQL schema compiled successfully.

Edit your schema at c:\Users\Jack\Documents\Roundin\roundin-customer-app\amplify\backend\api\roundin\schema.graphql or place .graphql files in a directory at c:\Users\Jack\Documents\Roundin\roundin-customer-app\amplify\backend\api\roundin\schema
/ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS roundin-business-app-dev-20190914143056 AWS::CloudFormation::Stack Tue Oct 22 2019 23:18:39 GMT+0100 (British Summer Time) User Initiated
CREATE_IN_PROGRESS functionexampleLambda                   AWS::CloudFormation::Stack Tue Oct 22 2019 23:18:42 GMT+0100 (British Summer Time)
CREATE_IN_PROGRESS functionexampleLambda                   AWS::CloudFormation::Stack Tue Oct 22 2019 23:18:42 GMT+0100 (British Summer Time) Resource creation Initiated
UPDATE_IN_PROGRESS authroundinbusinessappf7f2ggdc         AWS::CloudFormation::Stack Tue Oct 22 2019 23:18:42 GMT+0100 (British Summer Time)
UPDATE_COMPLETE    authroundinbusinessappf7f2ggdc         AWS::CloudFormation::Stack Tue Oct 22 2019 23:18:43 GMT+0100 (British Summer Time)
\ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS roundin-business-app-dev-20190914143056-functionexampleLambda-1BWOG6PQHP3AP AWS::CloudFormation::Stack Tue Oct 22 2019 23:18:42 GMT+0100 (British Summer Time) User Initiated
| Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS LambdaExecutionRole AWS::IAM::Role Tue Oct 22 2019 23:18:45 GMT+0100 (British Summer Time)
| Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS          apiroundin                              AWS::CloudFormation::Stack Tue Oct 22 2019 23:18:45 GMT+0100 (British Summer Time)
UPDATE_IN_PROGRESS          UpdateRolesWithIDPFunction              AWS::Lambda::Function      Tue Oct 22 2019 23:18:45 GMT+0100 (British Summer Time)
UPDATE_FAILED               apiroundin                              AWS::CloudFormation::Stack Tue Oct 22 2019 23:18:45 GMT+0100 (British Summer Time) Parameters: [CreateAPIKey] do not exist in the template
UPDATE_COMPLETE             UpdateRolesWithIDPFunction              AWS::Lambda::Function      Tue Oct 22 2019 23:18:46 GMT+0100 (British Summer Time)
CREATE_FAILED               functionexampleLambda                   AWS::CloudFormation::Stack Tue Oct 22 2019 23:18:46 GMT+0100 (British Summer Time) Resource creation cancelled
UPDATE_ROLLBACK_IN_PROGRESS roundin-business-app-dev-20190914143056AWS::CloudFormation::Stack Tue Oct 22 2019 23:18:46 GMT+0100 (British Summer Time) The following resource(s) failed to create: [functionexampleLambda]. The following resource(s) failed to update: [apiroundin].
\ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS LambdaExecutionRole AWS::IAM::Role Tue Oct 22 2019 23:18:45 GMT+0100 (British Summer Time) Resource creation Initiated
\ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE LambdaExecutionRole AWS::IAM::Role Tue Oct 22 2019 23:19:03 GMT+0100 (British Summer Time)
- Updating resources in the cloud. This may take a few minutes...

UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS roundin-business-app-dev-20190914143056 AWS::CloudFormation::Stack Tue Oct 22 2019 23:19:07 GMT+0100 (British Summer Time)
UPDATE_IN_PROGRESS                           authroundinbusinessappf7f2ggdc         AWS::CloudFormation::Stack Tue Oct 22 2019 23:19:04 GMT+0100 (British Summer Time)
UPDATE_COMPLETE                              authroundinbusinessappf7f2ggdc         AWS::CloudFormation::Stack Tue Oct 22 2019 23:19:05 GMT+0100 (British Summer Time)
UPDATE_IN_PROGRESS                           UpdateRolesWithIDPFunction              AWS::Lambda::Function      Tue Oct 22 2019 23:19:05 GMT+0100 (British Summer Time)
UPDATE_COMPLETE                              apiroundin                              AWS::CloudFormation::Stack Tue Oct 22 2019 23:19:05 GMT+0100 (British Summer Time)
UPDATE_COMPLETE                              UpdateRolesWithIDPFunction              AWS::Lambda::Function      Tue Oct 22 2019 23:19:06 GMT+0100 (British Summer Time)
UPDATE_IN_PROGRESS                           apiroundin                              AWS::CloudFormation::Stack Tue Oct 22 2019 23:19:07 GMT+0100 (British Summer Time)
DELETE_IN_PROGRESS                           functionexampleLambda                   AWS::CloudFormation::Stack Tue Oct 22 2019 23:19:07 GMT+0100 (British Summer Time)
UPDATE_COMPLETE                              apiroundin                              AWS::CloudFormation::Stack Tue Oct 22 2019 23:19:08 GMT+0100 (British Summer Time)
UPDATE_IN_PROGRESS                           authroundinbusinessappf7f2ggdc       AWS::CloudFormation::Stack Tue Oct 22 2019 23:19:08 GMT+0100 (British Summer Time)
UPDATE_COMPLETE                              authroundinbusinessappf7f2ggdc          AWS::CloudFormation::Stack Tue Oct 22 2019 23:19:08 GMT+0100 (British Summer Time)
| Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS LambdaFunction                                                              AWS::Lambda::Function      Tue Oct 22 2019 23:19:06 GMT+0100 (British Summer Time)
CREATE_IN_PROGRESS LambdaFunction                                                              AWS::Lambda::Function      Tue Oct 22 2019 23:19:06 GMT+0100 (British Summer Time) Resource creation Initiated
CREATE_COMPLETE    LambdaFunction                                                              AWS::Lambda::Function      Tue Oct 22 2019 23:19:07 GMT+0100 (British Summer Time)
DELETE_IN_PROGRESS roundin-business-app-dev-20190914143056-functionexampleLambda-1BWOG6PQHP3AP AWS::CloudFormation::Stack Tue Oct 22 2019 23:19:08 GMT+0100 (British Summer Time) User Initiated
| Updating resources in the cloud. This may take a few minutes...

DELETE_IN_PROGRESS LambdaFunction      AWS::Lambda::Function Tue Oct 22 2019 23:19:33 GMT+0100 (British Summer Time)
DELETE_COMPLETE    LambdaFunction      AWS::Lambda::Function Tue Oct 22 2019 23:19:34 GMT+0100 (British Summer Time)
DELETE_IN_PROGRESS LambdaExecutionRole AWS::IAM::Role        Tue Oct 22 2019 23:19:35 GMT+0100 (British Summer Time)
\ Updating resources in the cloud. This may take a few minutes...TypeError: events is not iterable
    at getUniqueStacksEvents (C:\Users\Jack\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-provider-awscloudformation\src\aws-utils\aws-cfn.js:436:28)
    at getStackEvents.then.stackEvents (C:\Users\Jack\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-provider-awscloudformation\src\aws-utils\aws-cfn.js:128:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:16424) UnhandledPromiseRejectionWarning: Error: getaddrinfo EAI_AGAIN cloudformation.eu-west-1.amazonaws.com cloudformation.eu-west-1.amazonaws.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:16424) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16424) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
- Updating resources in the cloud. This may take a few minutes...Error updating cloudformation stack
/ Updating resources in the cloud. This may take a few minutes...

DELETE_COMPLETE          functionexampleLambda                   AWS::CloudFormation::Stack Tue Oct 22 2019 23:19:42 GMT+0100 (British Summer Time)
UPDATE_ROLLBACK_COMPLETE roundin-business-app-dev-20190914143056
AWS::CloudFormation::Stack Tue Oct 22 2019 23:19:42 GMT+0100 (British Summer Time)
- Updating resources in the cloud. This may take a few minutes...

Following resources failed

× An error occurred when pushing the resources to the cloud

Resource is not in the state stackUpdateComplete
An error occured during the push operation: Resource is not in the state stackUpdateComplete

c:\Users\Jack\Documents\Roundin\roundin-customer-app>amplify status

Current Environment: dev

| Category | Resource name              | Operation | Provider plugin   |
| -------- | -------------------------- | --------- | ----------------- |
| Function | exampleLambda              | Create    | awscloudformation |
| Auth     | roundinbusinessapp| No Change | awscloudformation |
| Api      | roundin                    | No Change | awscloudformation |
``` 
I did do a amplify env pull --restore so I am sure it isn't and missed changes made via the console. I do have other Lambda function that are created on my AWS account separately from this project could they be a problem. Any help on this would be good thank you.

**Comment by kaustavghosh06** [comment]
@magjack From your stack-trace it looks like, this is the issue -`UPDATE_FAILED               apiroundin                              AWS::CloudFormation::Stack Tue Oct 22 2019 23:18:45 GMT+0100 (British Summer Time) Parameters: [CreateAPIKey] do not exist in the template`

Can you run `amplify update api` follow the steps and then push again and check if you see the same error?

**Comment by kaustavghosh06** [comment]
@magjack Please take a look at #2626 
Just unblocked @vdiaza on a very similar issue.

**Comment by magjack** [comment]
Hi, the advice in #2626 works. I added an empty space character in graphql.schema and did `amplify push` and it resolved everything. I then added another api function and it worked. Looks like it was a one-off fix. Has there been a recent update that would require this?
