### ISSUE TITLE
Amplify CLI error on trying to pull existing environment

### ISSUE THREAD

**Issue by amey91** [aws-amplify/amplify-cli#2632]
**Describe the bug**
`amplify env checkout gamma` fails on machine B after I initialize amplify on another machine A.

**To Reproduce**
1. Initialize amplify on some machine and create environment gamma and do `amplify push`
2. On another machine B or a different workspace, I do `amplify env list` and I can see the environment as expected
3. I tried `amplify status` and it shows the environment on the new machine, but it is in CREATE operation instead of no action. 
4. When I try to do any of the following `amplify env pull --restore`, `amplify env checkout`, `amplify push` I get this error:

```
➜  DataModeler git:(amey91-amplifySetup) ✗ amplify init     
Note: It is recommended to run this command from the root of your app directory
? Do you want to use an existing environment? Yes
? Choose the environment you would like to use: gamma
Using default provider  awscloudformation
✖ There was an error initializing your environment.
init failed
AccessDenied: Access Denied
    at Request.extractError (/Users/aghadiga/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/services/s3.js:585:35)
    at Request.callListeners (/Users/aghadiga/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/aghadiga/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/aghadiga/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/aghadiga/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/aghadiga/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/aghadiga/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/aghadiga/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/aghadiga/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/aghadiga/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  message: 'Access Denied',
  code: 'AccessDenied',
  region: null,
  time: 2019-10-26T00:55:09.853Z,
  requestId: '3E1391E4E97C4C5F',
  extendedRequestId: 'TIrWS5B/eIgBaKyQdtH5H3PI6713H+7s129Bxb4z7haIoLwLR/+cRX11/CirFRVshD3tW2JcviY=',
  cfId: undefined,
  statusCode: 403,
  retryable: false,
  retryDelay: 0.32978387131537
}
➜  DataModeler git:(amey91-amplifySetup) ✗ amplify -v
3.14.0
```

**Expected behavior**
I would expect the other machine to also be able to pull and push the existing cloud environment

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser N/A
 - Version 
➜  DataModeler git:(amey91-amplifySetup) ✗ amplify -v
3.14.0

**Comment by kaustavghosh06** [comment]
@amey91 Can you check the profile set for the gamma environment in `amplify/.config/local-aws-info.json` file and see if the accesskey and secretkey corresponding to that profile has access to the AWS account in which the environment is provisioned in?

**Comment by kaustavghosh06** [comment]
Closing this issue due to lack of response. Please let us know if you're still stuck on this.
