### ISSUE TITLE
Codegen Error: Syntax Error

### ISSUE THREAD

**Issue by arvinkx** [aws-amplify/amplify-cli#264]
I have an existing api I'm trying to integrate into a new application and I'm running into an issue when trying to run codegen. Specifically the error is: `Syntax Error: Expected Name, found }`. I don't think my schema has any errors as it doesn't complain in the appsync console and I can access it outside this. Is this an issue with the code generation itself or something in my schema? 

Full Error:
```$ amplify codegen
✔ Downloaded the schema
⠋ Generating GraphQL operations⠋ Generating.../graphql/queries.graphql: Field "posts" argument "limit" of type "Int!" is required but not provided.
.../graphql/queries.graphql: Field "videos" argument "limit" of type "Int!" is required but not provided.
.../graphql/queries.graphql: Field "stories" argument "limit" of type "Int!" is required but not provided.
.../graphql/queries.graphql: Field "podcasts" argument "limit" of type "Int!" is required but not provided.
.../graphql/queries.graphql: Field "posts" argument "limit" of type "Int!" is required but not provided.
.../graphql/queries.graphql: Field "videos" argument "limit" of type "Int!" is required but not provided.
.../graphql/queries.graphql: Field "stories" argument "limit" of type "Int!" is required but not provided.
.../graphql/queries.graphql: Field "podcasts" argument "limit" of type "Int!" is required but not provided.
.../graphql/queries.graphql: Field "posts" argument "limit" of type "Int!" is required but not provided.
.../graphql/queries.graphql: Field "videos" argument "limit" of type "Int!" is required but not provided.
.../graphql/queries.graphql: Field "stories" argument "limit" of type "Int!" is required but not provided.
.../graphql/queries.graphql: Field "podcasts" argument "limit" of type "Int!" is required but not provided.
.../graphql/queries.graphql: Variable "$users" of type "String!" used in position expecting type "[String!]!".
.../graphql/queries.graphql: Variable "$users" of type "String!" used in position expecting type "[String!]!".
.../graphql/queries.graphql: Field "posts" argument "limit" of type "Int!" is required but not provided.
.../graphql/queries.graphql: Field "videos" argument "limit" of type "Int!" is required but not provided.
.../graphql/queries.graphql: Field "stories" argument "limit" of type "Int!" is required but not provided.
.../graphql/queries.graphql: Field "podcasts" argument "limit" of type "Int!" is required but not provided.
2018-10-05T04:41:59.242Z - error: uncaughtException: Syntax Error: Expected Name, found } (146:17)
  144 |   )
  145 |  {
> 146 |                 }      
      |                 ^
  147 | }
  148 |   mutation UnlikePost   (
  149 |       $input:PostLikeInput! date=Thu Oct 04 2018 21:41:59 GMT-0700 (PDT), pid=68157, uid=501, gid=20, cwd=/LOCAL_DIRECTORY, execPath=/Users/username/.nvm/versions/node/v8.12.0/bin/node, version=v8.12.0, argv=[/Users/username/.nvm/versions/node/v8.12.0/bin/node, /Users/username/.nvm/versions/node/v8.12.0/bin/amplify, codegen], rss=151486464, heapTotal=116416512, heapUsed=80099272, external=1466198, loadavg=[2.62255859375, 2.31982421875, 2.15966796875], uptime=695325, trace=[column=493, file=/Users/username/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/prettier/parser-graphql.js, function=n, line=1, method=null, native=false, column=35789, file=/Users/username/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/prettier/parser-graphql.js, function=Object.parse, line=1, method=parse, native=false, column=19, file=/Users/username/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/prettier/index.js, function=Object.parse$2 [as parse], line=7138, method=parse$2 [as parse], native=false, column=23, file=/Users/username/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/prettier/index.js, function=coreFormat, line=10398, method=null, native=false, column=16, file=/Users/username/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/prettier/index.js, function=format, line=10570, method=null, native=false, column=12, file=/Users/username/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/prettier/index.js, function=formatWithCursor, line=10582, method=null, native=false, column=15, file=/Users/username/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/prettier/index.js, function=null, line=34924, method=null, native=false, column=12, file=/Users/username/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/prettier/index.js, function=Object.format, line=34943, method=format, native=false, column=19, file=/Users/kaustavg/amplify-launch/amplify-cli/packages/amplify-graphql-docs-generator/src/index.ts, function=format, line=117, method=null, native=false, column=10, file=/Users/kaustavg/amplify-launch/amplify-cli/packages/amplify-graphql-docs-generator/src/index.ts, function=renderOps, line=85, method=null, native=false], stack=[SyntaxError: Syntax Error: Expected Name, found } (146:17),   144 |   ),   145 |  {, > 146 |                 }      ,       |                 ^,   147 | },   148 |   mutation UnlikePost   (,   149 |       $input:PostLikeInput!,     at n (/Users/username/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/prettier/parser-graphql.js:1:493),     at Object.parse (/Users/username/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/prettier/parser-graphql.js:1:35789),     at Object.parse$2 [as parse] (/Users/username/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/prettier/index.js:7138:19),     at coreFormat (/Users/username/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/prettier/index.js:10398:23),     at format (/Users/username/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/prettier/index.js:10570:16),     at formatWithCursor (/Users/username/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/prettier/index.js:10582:12),     at /Users/username/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/prettier/index.js:34924:15,     at Object.format (/Users/username/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/prettier/index.js:34943:12),     at format (/Users/kaustavg/amplify-launch/amplify-cli/packages/amplify-graphql-docs-generator/src/index.ts:117:19),     at renderOps (/Users/kaustavg/amplify-launch/amplify-cli/packages/amplify-graphql-docs-generator/src/index.ts:85:10)]
```
Schema downloaded from appsync console:
[GraphQL](https://gist.github.com/arvinkx/3d3f7f79d640adcdea692a09397648c1)

Introspection that's downloaded during codegen:
[JSON](https://gist.github.com/arvinkx/dad8faf1e6cb8481a92cfca0fb20c3b8)

graphqlconfig.yml:
```
projects:
  apiName:
    schemaPath: graphql/schema.json
    includes:
      - graphql/**/*.graphql
    excludes:
      - amplify/**
    extensions:
      amplify:
        graphQLApiId: **API_ID**
        codeGenTarget: swift
        generatedFileName: API.swift
        docsFilePath: graphql
        region: us-east-1
```

**Comment by yuth** [comment]
@arvinkx What version of amplify-cli do you have installed? You get it by running `amplify -v`.

Some thing odd that I see in your schema is that the return type for some of the mutations are `String`, is that intentional? For instance
```graphql
  clearVideoVote(authorId: String!, id: ID!): String
  deletePodcast(input: DeletePodcastInput!): String
  deletePost(input: DeletePostInput!): String
  deleteStory(input: DeleteStoryInput!): String
  deleteVideo(authorId: String!, id: ID!): String
  downvoteVideo(authorId: String!, id: ID!): String
  followUser(user: String!): String!
  likePodcast(input: PodcastLikeInput!): String
  likePost(input: PostLikeInput!): String!
  removeComment(commentId: ID!, parentId: ID!): String
  reportContent(authorId: String!, id: ID!, type: String!): String
  reportPostAdImpression(id: ID!): String
  reportVideoView(authorId: String!, id: ID!): String
  unfollowUser(user: String!): String!
  unlikePodcast(input: PodcastLikeInput!): String
  unlikePost(input: PostLikeInput!): String!
  upvoteVideo(authorId: String!, id: ID!): String
```

When the mutation returns a `Scalar` type you can't use the return value from it
for `  clearVideoVote(authorId: String!, id: ID!): String` your statement will have to be
```graphql
 mutation ClearVideoVote   (
      $authorId:String!,
      $id:ID!
  )
{
    clearVideoVote  (
      authorId:$authorId,
      id:$id
    )
}
```

**Comment by arvinkx** [comment]
I'm running v0.1.27 - is the reason codegen is having issues because of the use of String return values? It was intentional but if that's the issue it can be changed.

**Comment by yuth** [comment]
>  is the reason codegen is having issues because of the use of String return values

Yes, but I am going update codegen to support this use case. Thanks for reporting it

**Comment by arvinkx** [comment]
@yuth Thanks for the fix, I'm running into a possibly related issue. The generation of the graphql files seem to complete now but the validation fails with the error `Validation of GraphQL query document failed`. I believe the issue is related to the warnings in the original error message above about "limit" not being provided. I've included a snippet of the schema below, it looks like the generation isn't adding the extra arguments (limit and nextToken) for the posts, video, stories, etc. Are arguments in response fields not supported?

Actual Schema
```
type User {
    username: String!
    preferred_username: String!
    picture: String!
    email: String!
    name: String!
    family_name: String!
    posts(limit: Int!, nextToken: String): PostConnection
    videos(limit: Int!, nextToken: String): VideoConnection
    stories(limit: Int!, nextToken: String): StoryConnection
    podcasts(limit: Int!, nextToken: String): PodcastConnection
    notifications: NotificationConnection
    followerCount: Int!
    followingCount: Int!
    followerIds: [String!]!
    followingIds: [String!]!
    followingTags: [String!]
}

```

What's being generated (this mutation returns a User):
```
mutation UpdateFollowingTags($tags: String!) {
  updateFollowingTags(tags: $tags) {
    username
    preferred_username
    picture
    email
    name
    family_name
    posts {
      items {
        id
        date
        updatedAt
        title
        authorId
        content
        likesCount
        video
        isLiked
      }
      nextToken
    }
    videos {
      items {
        id
        authorId
        date
        viewCount
        category
        upvotesCount
        upvotes
        downvotesCount
        downvotes
        title
        alternativeTitle
        thumbnailUrl
        alternativeThumbnailUrl
        description
        videoUrl
        videoLength
        tags
      }
      nextToken
    }
    stories {
      items {
        id
        date
        authorId
        image
        video
      }
      nextToken
    }
    podcasts {
      items {
        id
        date
        updatedAt
        url
        authorId
        description
        likesCount
        isLiked
      }
      nextToken
    }
    notifications {
      items {
        userId
        notificationId
        date
        likes
        newLikesCount
        followers
        newFollowersCount
      }
    }
    followerCount
    followingCount
    followerIds
    followingIds
    followingTags
  }
}
```
