### ISSUE TITLE
UnhandledPromiseRejectionWarning when running Amplify Codegen 

### ISSUE THREAD

**Issue by drooJohnson** [aws-amplify/amplify-cli#2708]
**Describe the bug**
When running `amplify codegen` I get an UnhandledPromiseRejectionWarning 

**Amplify CLI Version**
3.17

**To Reproduce**
Initialize project and add the codegen via the command provided by the AppSync page, `amplify add codegen --apiId <API_ID_HERE>`. 

The console output is this
`✔ Downloaded the schema
⠋ Generating GraphQL operations(node:2451) UnhandledPromiseRejectionWarning: Error: GraphQL schema file should contain a valid GraphQL introspection query result
	at Object.generate [as default] (/Users/andrewjohnson/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-graphql-docs-generator/lib/generator/src/generator/generate.ts:16:11)
    at generate (/Users/andrewjohnson/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-graphql-docs-generator/lib/src/index.ts:32:57)
    at projects.forEach (/Users/andrewjohnson/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/commands/statements.js:55:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)

(node:2451) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). 
(rejection id: 1)

(node:2451) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Expected behavior**
My project is populated with all possible GraphQL operations in the src/graphql directory.

**Desktop (please complete the following information):**
 - OS: Mac 10.15
 - Node Version: 10.16.0

**Comment by drooJohnson** [comment]
Changing a schema definition from `interface` to `type` fixed this issue.
