### ISSUE TITLE
error when attempting to add auth access to cognito function

### ISSUE THREAD

**Issue by mwarger** [aws-amplify/amplify-cli#2767]
**Describe the bug**
I was trying to add auth access to a generated cognito function and got an error:

```
amplify update function
Using service: Lambda, provided by: awscloudformation
? Please select the Lambda Function you would want to update cognito51fac114PostConfirmation
? Do you want to update permissions granted to this Lambda function to perform on other resources in your project? Yes
? Select the category auth
? Auth has 2 resources in this project. Select the one you would like your Lambda to access userPoolGroups
? Select the operations you want to permit for userPoolGroups read
Could not get policies for auth: userPoolGroups
Policies cannot be added for auth
TypeError: Cannot destructure property `serviceWalkthroughFilename` of 'undefined' or 'null'.
    at Object.getPermissionPolicies (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/provider-utils/awscloudformation/index.js:585:42)
    at Object.keys.forEach.resourceName (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/index.js:256:59)
    at Array.forEach (<anonymous>)
    at getPermissionPolicies (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/index.js:252:35)
    at askExecRolePermissionsQuestions (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/provider-utils/awscloudformation/service-walkthroughs/lambda-walkthrough.js:422:68)
    at process._tickCallback (internal/process/next_tick.js:68:7)

You can access the following resource attributes as environment variables from your Lambda function
var environment = process.env.ENV
var region = process.env.REGION
```
**Amplify CLI Version**
amplify -v
3.17.0

**Comment by kaustavghosh06** [comment]
@mwarger When prompted for the auth resource, you seemed to have selected the userpoolGroups resource  (which doesn't have permissions support from lambda yet) instead of the auth (Cognito) resource. If you select the cognito - auth resource - the flow should work.
