### ISSUE TITLE
amplify codegen types fails in unrelated file 

### ISSUE THREAD

**Issue by mwarger** [aws-amplify/amplify-cli#278]
**Describe the bug**
Running `amplify codegen types` does not run correctly.  Fails in unrelated file (e.g. a file with no graphql type declarations in it)

**To Reproduce**
1. run `amplify codgen types` (or, since I'm on windows `wsl amplify codegen types`)
2. See error below

**Expected behavior**
Codegen works by generating types

**Screenshots**
```

project-web develop * = $ wsl amplify codegen types
✔ Downloaded the schema
⠋ Generating2018-10-07T16:29:12.191Z - error: uncaughtException: Syntax Error src/components/auth/SignUpForm.tsx (1:1) Unexpected (

1: ()
   ^
2: () -
 date=Sun Oct 07 2018 10:29:10 GMT-0600 (GMT-06:00), pid=4, uid=1000, gid=1000, cwd=/mnt/c/dev/slx/project-web, execPath=/usr/bin/node, version=v10.9.0, argv=[/usr/bin/node, /usr/bin/amplify, codegen, types], rss=115699712, heapTotal=94654464, heapUsed=55606320,
external=1671191, loadavg=[0.5185546875, 0.57763671875, 0.5859375], uptime=16, trace=[column=15, file=/usr/lib/node_modules/@aws-amplify/cli/node_modules/aws-appsync-codegen/node_modules/graphql/error/syntaxError.js, function=syntaxError, line=30, method=null, native=false, column=33, file=/usr/lib/node_modules/@aws-amplify/cli/node_modules/aws-appsync-codegen/node_modules/graphql/language/parser.js, function=unexpected, line=995, method=null, native=false, column=9, file=/usr/lib/node_modules/@aws-amplify/cli/node_modules/aws-appsync-codegen/node_modules/graphql/language/parser.js, function=parseDefinition, line=154, method=null, native=false, column=22, file=/usr/lib/node_modules/@aws-amplify/cli/node_modules/aws-appsync-codegen/node_modules/graphql/language/parser.js, function=parseDocument, line=108, method=null, native=false, column=10, file=/usr/lib/node_modules/@aws-amplify/cli/node_modules/aws-appsync-codegen/node_modules/graphql/language/parser.js, function=Object.parse, line=45, method=parse, native=false, column=56, file=/usr/lib/node_modules/@aws-amplify/cli/node_modules/aws-appsync-codegen/src/loading.ts, function=graphql_1.concatAST.sources.map.source, line=84, method=source, native=false, column=null, file=null, function=Array.map, line=null, method=map, native=false, column=42, file=/usr/lib/node_modules/@aws-amplify/cli/node_modules/aws-appsync-codegen/src/loading.ts, function=Object.loadAndMergeQueryDocuments, line=84, method=loadAndMergeQueryDocuments, native=false, column=20, file=/usr/lib/node_modules/@aws-amplify/cli/node_modules/aws-appsync-codegen/src/generate.ts, function=generate, line=33, method=null, native=false, column=7, file=/usr/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/commands/types.js, function=projects.forEach, line=39, method=forEach, native=false], **stack=[GraphQLError: Syntax Error src/components/auth/SignUpForm.tsx (1:1) Unexpected (, , 1: () ,    ^, 2: () -, ,     at syntaxError (/usr/lib/node_modules/@aws-amplify/cli/node_modules/aws-appsync-codegen/node_modules/graphql/error/syntaxError.js:30:15),**     at unexpected (/usr/lib/node_modules/@aws-amplify/cli/node_modules/aws-appsync-codegen/node_modules/graphql/language/parser.js:995:33),     at parseDefinition (/usr/lib/node_modules/@aws-amplify/cli/node_modules/aws-appsync-codegen/node_modules/graphql/language/parser.js:154:9),     at parseDocument (/usr/lib/node_modules/@aws-amplify/cli/node_modules/aws-appsync-codegen/node_modules/graphql/language/parser.js:108:22),     at Object.parse (/usr/lib/node_modules/@aws-amplify/cli/node_modules/aws-appsync-codegen/node_modules/graphql/language/parser.js:45:10),
   at graphql_1.concatAST.sources.map.source (/usr/lib/node_modules/@aws-amplify/cli/node_modules/aws-appsync-codegen/src/loading.ts:84:56),     at Array.map (<anonymous>),     at Object.loadAndMergeQueryDocuments (/usr/lib/node_modules/@aws-amplify/cli/node_modules/aws-appsync-codegen/src/loading.ts:84:42),     at generate (/usr/lib/node_modules/@aws-amplify/cli/node_modules/aws-appsync-codegen/src/generate.ts:33:20),     at projects.forEach (/usr/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/commands/types.js:39:7)]
```

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
Version of amplify:
wsl amplify -v
0.1.27

Here is the codegen config (as noted, this has previously worked without issue):
wsl amplify codegen configure
? Choose the code generation language target typescript
? Enter the file name pattern of graphql queries, mutations and subscriptions src/**/*.tsx
? Enter the file name for the generated code src/API.ts

Project is running with typescript - this has worked consistently - something in the latest version seems to have broken this.  

Thanks for all the hard work on this project!

**Comment by mwarger** [comment]
I was able to get this working without issue in another project, so I'm going to close this for now and will re-open if I see it happen again.

**Comment by mwarger** [comment]
I'm re-opening this for visibility, wondering if anyone has seen this.  Has only popped up in the latest version of the CLI.

**Comment by kaustavghosh06** [comment]
@mwarger Could you please check out v 0.1.28 and see if you can reproduce it?

**Comment by yuth** [comment]
@mwarger could you share the content of your `<project-root>/.graphqlconfig.yml`. I am interested at looking at `includes:` section on that file.

**Comment by mwarger** [comment]
> @mwarger Could you please check out v 0.1.28 and see if you can reproduce it?

@kaustavghosh06 I get the same error after I updated.

**Comment by yuth** [comment]
This is caused because your include pattern `src/**/*.tsx` includes unrelated files as GraphQL statements. Can you move the GraphqQL statements to its own foloder (e.g., `src/graphql/`) and update your `.graphqlconfig.yml` to point it the newly created `graphql` folder. The updated file should look something as follows:
```yaml
projects:
  name_redacted:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphq/**/*.tsx
    excludes:
      - amplify/**
    extensions:
      amplify:
        graphQLApiId: asdfasdf
        codeGenTarget: typescript
        generatedFileName: src/API.ts
      endpoints:
        prod: >-
          endpoint redacted
```

__PS__: If you are using the amplify codegen to generate the statements, the files generated by it will end with `.ts` extension and not `.tsx`

**Comment by kaustavghosh06** [comment]
@mwarger Do you still have this issue with the latest versions of the CLI?

**Comment by mwarger** [comment]
@kaustavghosh06 I will give this a look and report back.

**Comment by mwarger** [comment]
@kaustavghosh06 After this point, I moved my GQL to the query files as this approach didn't work.  I had left Apollo as well so I'm not sure if this works or not, but I don't need it at the moment.
