### ISSUE TITLE
Amplify mock + lambda function + other resources permissions

### ISSUE THREAD

**Issue by aprat84** [aws-amplify/amplify-cli#2799]
**Describe the bug**
Amplify mock not able to simulate lambda execution role to manage other services for which it's been granted permissions using this same cli.

**Amplify CLI Version**
3.17.0

**To Reproduce**
- Create test project
```bash
$ amplify init
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the project test
? Enter a name for the environment dev
? Choose your default editor: None
? Choose the type of app that you're building javascript
Please tell us about your project
? What javascript framework are you using none
? Source Directory Path:  src
? Distribution Directory Path: dist
? Build Command:  npm run-script build
? Start Command: npm run-script start
Using default provider  awscloudformation

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html

? Do you want to use an AWS profile? Yes
? Please choose the profile you want to use XXX
⠙ Initializing project in the cloud...
✔ Successfully created initial AWS cloud resources for deployments.
✔ Initialized provider successfully.
```

- Add GraphQL API to the project
```bash
$ amplify add api
? Please select from one of the below mentioned services: GraphQL
? Provide API name: test
? Choose the default authorization type for the API Amazon Cognito User Pool
Using service: Cognito, provided by: awscloudformation
 
 The current configured provider is Amazon Cognito. 
 
 Do you want to use the default authentication and security configuration? Default configuration
 Warning: you will not be able to edit these selections. 
 How do you want users to be able to sign in? Email
 Do you want to configure advanced settings? No, I am done.
Successfully added auth resource
? Do you want to configure advanced settings for the GraphQL API No, I am done.
? Do you have an annotated GraphQL schema? No
? Do you want a guided schema creation? No
? Provide a custom type name MyType
Creating a base schema for you...
GraphQL schema compiled successfully.
Successfully added resource test locally
```

- Add a function with full access to auth (cognito)
```bash
$ amplify add function
Using service: Lambda, provided by: awscloudformation
? Provide a friendly name for your resource to be used as a label for this category in the project: examplefn
? Provide the AWS Lambda function name: examplefn
? Choose the function template that you want to use: Hello world function
? Do you want to access other resources created in this project from your Lambda function? Yes
? Select the category auth
Auth category has a resource called test344ffb68
? Select the operations you want to permit for test344ffb68 (Press <space> to select, <a> to toggle all, <i> to invert selection) create, read, update, delete

You can access the following resource attributes as environment variables from your Lambda function
var environment = process.env.ENV
var region = process.env.REGION
var authTest344ffb68UserPoolId = process.env.AUTH_TEST344FFB68_USERPOOLID

? Do you want to edit the local lambda function now? No
Successfully added resource examplefn locally.
```

- Add `aws-sdk` to function dependencies with `npm i -D aws-sdk`

- Edit function code to instantiate `CognitoIdentityServiceProvider` and call some cognito function:
```js
const { CognitoIdentityServiceProvider } = require('aws-sdk');
const cognitoServiceProvider = new CognitoIdentityServiceProvider();

exports.handler = function (event, context) { //eslint-disable-line
        cognitoServiceProvider.adminCreateUser({
            UserPoolId: process.env.AUTH_TEST344FFB68_USERPOOLID,
            MessageAction: 'SUPPRESS',
            Username: 'test2@domain.com',
            TemporaryPassword: '123456789'
        }).promise().then(function() {
                context.done(null, 'Hello World'); // SUCCESS with message
        }, function(error) {
                console.log(error);
                context.done('ERROR');
        });
};

```

- Modify API graphql schema with a simple test query that calls the function
```graphql
type Query {
    test(msg: String!): String @function(name: "examplefn-${env}")
}
```

- Push evnerything to cloud (just in case) with `amplify push`
```bash
$ amplify push

Current Environment: dev

| Category | Resource name | Operation | Provider plugin   |
| -------- | ------------- | --------- | ----------------- |
| Auth     | test344ffb68  | Create    | awscloudformation |
| Api      | test          | Create    | awscloudformation |
| Function | examplefn     | Create    | awscloudformation |
? Are you sure you want to continue? Yes

The following types do not have '@auth' enabled. Consider using @auth with @model
	 - MyType
Learn more about @auth here: https://aws-amplify.github.io/docs/cli-toolchain/graphql#auth 

GraphQL schema compiled successfully.

Edit your schema at /home/albert/Downloads/test/amplify/backend/api/test/schema.graphql or place .graphql files in a directory at /home/albert/Downloads/test/amplify/backend/api/test/schema
? Do you want to generate code for your newly created GraphQL API Yes
? Choose the code generation language target javascript
? Enter the file name pattern of graphql queries, mutations and subscriptions src/graphql/**/*.js
? Do you want to generate/update all possible GraphQL operations - queries, mutations and subscriptions Yes
? Enter maximum statement depth [increase from default if your schema is deeply nested] 2
⠧ Updating resources in the cloud. This may take a few minutes...
✔ Generated GraphQL operations successfully and saved at src/graphql
✔ All resources are updated in the cloud
```

- Test the function in the AWS console:
Create a test user first using AWS cli
```bash
aws cognito-idp admin-create-user --profile XXX --region eu-west-1 --user-pool-id eu-west-1_XXXXXXX --username test@domain.com --message-action SUPPRESS
aws cognito-idp admin-set-user-password --profile XXX --region eu-west-1 --user-pool-id eu-west-1_XXXXXXX --username test@domain.com --password 123456789 --permanent
```
Query
```graphql
query test {
  test(msg: "Hello?")
}
```
Response
```json
{
  "data": {
    "test": "Hello World"
  }
}
```

- Add `authtest344ffb68UserPoolId` parameter into `function-parameters.json` file, otherwise `amplify mock` will fail with "function not exists" error (https://github.com/aws-amplify/amplify-cli/issues/2280 ?)
```json
{
    "permissions": {
        "auth": {
            "test344ffb68": ["create", "read", "update", "delete"]
        }
    },
    "authtest344ffb68UserPoolId": "authtest344ffb68UserPoolId"
}
```

- Start local testing with `amplify mock` and execute same query in the GraphiQL interface. Gives the following error
```js
{ ConfigError: Missing region in config
    at Request.VALIDATE_REGION (test/amplify/backend/function/examplefn/src/node_modules/aws-sdk/lib/event_listeners.js:92:45)
    at Request.callListeners (test/amplify/backend/function/examplefn/src/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at callNextListener (test/amplify/backend/function/examplefn/src/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at test/amplify/backend/function/examplefn/src/node_modules/aws-sdk/lib/event_listeners.js:86:9
    at finish (test/amplify/backend/function/examplefn/src/node_modules/aws-sdk/lib/config.js:362:7)
    at test/amplify/backend/function/examplefn/src/node_modules/aws-sdk/lib/config.js:404:9
    at Object.<anonymous> (test/amplify/backend/function/examplefn/src/node_modules/aws-sdk/lib/credentials/credential_provider_chain.js:111:13)
    at Object.arrayEach (test/amplify/backend/function/examplefn/src/node_modules/aws-sdk/lib/util.js:516:32)
    at resolveNext (test/amplify/backend/function/examplefn/src/node_modules/aws-sdk/lib/credentials/credential_provider_chain.js:110:20)
    at test/amplify/backend/function/examplefn/src/node_modules/aws-sdk/lib/credentials/credential_provider_chain.js:126:13
  message: 'Missing region in config',
  code: 'ConfigError',
  time: 2019-11-21T14:55:22.873Z }
```

**Expected behavior**
Expected behavior would be the function to execute as it does from the AWS console.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.3 LTS
 - Node Version: v10.16.3

**Comment by kaustavghosh06** [comment]
@aprat84 The aws_sdk used in your Lambda function is trying to use the aws creds configured locally in your machine. It first tries to look for your env variables and then it tries to look for the "default" profile in your system. 

You can read more about this out here - https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/setup-credentials.html

**Comment by kaustavghosh06** [comment]
Closing this issue. Please feel free to comment on this thread if you have more questions around this.

**Comment by TakagiHiroto** [comment]
thx you saved me
