### ISSUE TITLE
Console error reading inputParams googleClientId, facebookAppId

### ISSUE THREAD

**Issue by dahersoftware** [aws-amplify/amplify-cli#2833]
I encounter this problem quite frequently(Until now I used to delete my app), I am using prod environment.
It is working fine from my local machine and I don't understand why I get "getting stack from env cache" line even though I am reseting my environment cache.

2019-11-25T16:28:56.016Z [INFO]: # Executing command: amplifyPush --environment prod
2019-11-25T16:28:56.020Z [INFO]: # Getting Amplify CLI Cloud-Formation stack info from environment cache
2019-11-25T16:28:56.026Z [INFO]: # Start initializing Amplify environment: prod
2019-11-25T16:28:56.028Z [INFO]: # Initializing new Amplify environment: prod (amplify init)
2019-11-25T16:29:16.860Z [INFO]: Note: It is recommended to run this command from the root of your app directory
2019-11-25T16:29:21.331Z [WARNING]: - Initializing your environment: prod
2019-11-25T16:29:21.786Z [WARNING]: ✔ Initialized provider successfully.
2019-11-25T16:29:21.832Z [WARNING]: ✖ There was an error initializing your environment.
2019-11-25T16:29:21.833Z [INFO]: init failed
2019-11-25T16:29:21.834Z [INFO]: Error: auth headless init is missing the following inputParams facebookAppIdUserPool, facebookAppSecretUserPool, googleAppIdUserPool, googleAppSecretUserPool
at updateConfigOnEnvInit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/provider-utils/awscloudformation/index.js:315:15)
at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/index.js:241:28
at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/promise-sequential/index.js:16:18
at process._tickCallback (internal/process/next_tick.js:68:7)
2019-11-25T16:29:21.908Z [ERROR]: !!! Build failed
2019-11-25T16:29:21.909Z [ERROR]: !!! Non-Zero Exit Code detected
2019-11-25T16:29:21.909Z [INFO]: # Starting environment caching...
2019-11-25T16:29:21.909Z [INFO]: # Environment caching completed

My backend build file
version: 0.1
backend:
  phases:
    preBuild:
      commands:
        - 'cd packages/backend/'
        - echo "printing dir"
        - pwd
    build:
      commands:
        - echo "printing dir"
        - pwd
        - '# Execute Amplify CLI with the helper script'
        - envCache --set stackInfo ""
        - amplifyPush --environment prod --simple 
      commands:
        - 'cd ../../'

**Comment by Jkap7788** [comment]
@dahersoftware I had the same issue, the console team are working on a fix, for a temporary workaround, see this comment https://github.com/aws-amplify/amplify-console/issues/206#issuecomment-552548466

**Comment by dahersoftware** [comment]
My issue went away once the build restarted after a push (Earlier it was not , I am not sure what exactly fixed the issue.). I didn't try workaround @Jkap7788  mentioned.

**Comment by kevin-mitchell** [comment]
FWIW, I'm having this same issue.

I'm seeing:

```
Error: auth headless init is missing the following inputParams googleClientId, googleAppIdUserPool, googleAppSecretUserPool
                                 at updateConfigOnEnvInit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/provider-utils/awscloudformation/index.js:367:15)
...
...
```

This started happening after I added a second `test` environment to my project.

For what it's worth, pushing manually (e.g. `amplify push`) does not cause any issues, and as far as I know I am correctly supplying all of the required information (but maybe not?).

FWIW, my `team-provider-info.json` looks something like this:

```
   ...
   ...
   "master: { 
       ...
   }
   ...
   "test": {
        "awscloudformation": {
            "AuthRoleName": "amplify-myproject-test-842928-authRole",
            "UnauthRoleArn": "arn:aws:iam::98482482723:role/amplify-myproject-test-842928-unauthRole",
            "AuthRoleArn": "arn:aws:iam::98482482723:role/amplify-myproject-test-842928-authRole",
            "Region": "us-west-2",
            "DeploymentBucketName": "amplify-myproject-test-842928-deployment",
            "UnauthRoleName": "amplify-myproject-test-842928-unauthRole",
            "StackName": "amplify-myproject-test-842928",
            "StackId": "arn:aws:cloudformation:us-west-2:98482482723:stack/amplify-myproject-test-842928/asdfasdf124-as-123-sdfasdfas-23423dsf4"
        },
        "categories": {
            "auth": {
                "myproject2939da8": {
                    "hostedUIProviderCreds": "[{\"ProviderName\":\"Google\",\"client_id\":\"asldkjasfo9u3as-asdfjsafasdf.apps.googleusercontent.com\",\"client_secret\":\"lsfdkj309asfljas31\"}]",
                    "googleClientId": "asldkjasfo9u3as-asdfjsafasdf.apps.googleusercontent.com"
                }
            },
            "function": {
                "configurations": {},
                "myproject2939da8PreSignup": {
                    "DOMAINWHITELIST": "testdomain.com",
                    "VALIDEMAILS": "testemail@gmail.com"
                },
                "myproject2939da8PostAuthentication": {},
                "myproject2939da8PreAuthentication": {}
            }
        }
    }
    ...
    ...
```

**Comment by kevin-mitchell** [comment]
@dahersoftware did you manage to figure out what hte issue was by chance?

In my case, I have three environments: `master`, `test`, and `local` - all three are configured with different Google credentials I generated w/ the google developer console (basically this bit looks different for each environment in my `team-provider-info.json` file:

```
...
"hostedUIProviderCreds": "[{\"ProviderName\":\"Google\",\"client_id\":\"asldkjasfo9u3as-asdfjsafasdf.apps.googleusercontent.com\",\"client_secret\":\"lsfdkj309asfljas31\"}]",
                    "googleClientId": "asldkjasfo9u3as-asdfjsafasdf.apps.googleusercontent.com"
...
```
I used amplify-cli to generate all of these configurations.

I'm able to "amplify push" and "amplify publish" with all three environments (after `amplify env checkout _____`), and they all seem to "work".

That said, when I use the Amplify console to automatically build to these environments on commit, they are now failing with the messages (missing configuration values). I'm curious if you think it was a timing issue of some sort (?) or if you have any clue about how it resolved itself?

My initial `master` environment WAS working, but now that I've added multiple environments it seems to be failing. 

@Jkap7788 when you say that the team is aware and is working on a fix, do you have any more info on that? I went to the issue you called out but didn't see anything specific (maybe I just missed it). I saw the workaround, but I'd prefer not to go down that route as I've got enough things I'm juggling in my head at the moment ;). 

Thank you!!
