### ISSUE TITLE
ERROR DURING Amplify Configure 

### ISSUE THREAD

**Issue by awesome2live** [aws-amplify/amplify-cli#2937]
```
2019-12-06T11:20:48.273Z - error: uncaughtException: spawn cmd ENOENT date=Fri Dec 06 2019 16:50:48 GMT+0530 (India Standard Time), pid=10156, uid=null, gid=null, cwd=C:\Users\ROUNAK, execPath=C:\Program Files\nodejs\node.exe, version=v12.13.1, argv=[C:\Program Files\nodejs\node.exe, C:\Users\ROUNAK\AppData\Roaming\npm\node_modules\@aws-amplify\cli\bin\amplify, configure], rss=226959360, heapTotal=189296640, heapUsed=164254376, external=10011718, loadavg=[0, 0, 0], uptime=165423, trace=[column=19, file=internal/child_process.js, function=Process.ChildProcess._handle.onexit, line=264, method=onexit, native=false, column=16, file=internal/child_process.js, function=onErrorNT, line=456, method=null, native=false, column=21, file=internal/process/task_queues.js, function=processTicksAndRejections, line=80, method=null, native=false], stack=[Error: spawn cmd ENOENT,     at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19),     at onErrorNT (internal/child_process.js:456:16),     at processTicksAndRejections (internal/process/task_queues.js:80:21)]
```

**Comment by ammarkarachi** [comment]
@awesome2live Can you update the CLI version you are using and node version?

```amplify-cli -v```

```node -v```

**Comment by jkeys-ecg-nmsu** [comment]
@awesome2live doesn't solve your this issue but I'd recommend you use PowerShell or WSL Ubuntu for developing your Amplify projects.

**Comment by kaustavghosh06** [comment]
@awesome2live Are you still stuck on this issue? As a workaround you can use `amplify configure` to setup your AWS access creds and then run the build steps again.

**Comment by TS98TGK** [comment]
I am Still getting the error with the same config above, How do we Fix it?

**Comment by awesome2live** [comment]
If u r network have proxy then u have to apply proxy adding some code and
add environment variable with Name HTTP_PROXY and HTTPS_PROXY
