### ISSUE TITLE
Incompatible schema is suggested for IAM auth type

### ISSUE THREAD

**Issue by TrekSoft** [aws-amplify/amplify-cli#2967]
**Describe the bug**
When running `amplify add api` and selecting `IAM` authorization type, it gives `Objects with fine-grained access control` as one of the guided schemas but then fails because that type of schema requires Cognito User Pools.

**Amplify CLI Version**
4.5.0

**To Reproduce**
```terminal
a483e75e14fe:iamapi ddaudeli$ amplify add api
? Please select from one of the below mentioned services: GraphQL
? Provide API name: iamapi
? Choose the default authorization type for the API IAM
? Do you want to configure advanced settings for the GraphQL API No, I am done.
? Do you have an annotated GraphQL schema? No
? Do you want a guided schema creation? Yes
? What best describes your project: Objects with fine-grained access control (e.g., a project management app with owner-based authorization)
? Do you want to edit the schema now? No
InvalidDirectiveError: @auth directive with 'userPools' provider found, but the project has no Cognito User Pools authentication provider configured.
    at ModelAuthTransformer.validateRuleAuthStrategy (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-auth-transformer/src/ModelAuthTransformer.ts:2031:13)
    at ModelAuthTransformer.validateRules (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-auth-transformer/src/ModelAuthTransformer.ts:887:12)
    at ModelAuthTransformer.object (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-auth-transformer/src/ModelAuthTransformer.ts:348:10)
    at GraphQLTransform.transformObject (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/GraphQLTransform.ts:340:25)
    at GraphQLTransform.transform (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/GraphQLTransform.ts:266:18)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/util/amplifyUtils.ts:53:35
    at step (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/amplifyUtils.js:44:23)
    at Object.next (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/amplifyUtils.js:25:53)
    at fulfilled (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/amplifyUtils.js:16:58)
There was an error adding the API resource
```

**Expected behavior**
It shouldn't offer the `Objects with fine-grained access control` option for authorization types which don't support it.

**Desktop (please complete the following information):**
 - Mac
 - v12.13.0

**Comment by SwaySway** [comment]
Closing this issue as the pr for this has been merged.
