### ISSUE TITLE
"amplify api add-graphql-datasource" does not work in aurora is inactive 

### ISSUE THREAD

**Issue by Ricardo1980** [aws-amplify/amplify-cli#2971]
**Describe the bug**
If aurora is inactive, the command "amplify api add-graphql-datasource" does not activate again your database.

```
amplify api add-graphql-datasource                    
Using datasource: Aurora Serverless, provided by: awscloudformation
? Provide the region in which your cluster is located: eu-west-1
? Select the Aurora Serverless cluster that will be used as the data source for your API: database-3
⠙ Fetching Aurora Serverless cluster...BadRequestException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
    at Object.extractError (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.extractError (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12)
There was an error adding the datasource
⠦ Fetching Aurora Serverless cluster...
⠧ Fetching Aurora Serverless cluster...
⠏ Fetching Aurora Serverless cluster...
⠼ Fetching Aurora Serverless cluster...^C
```

**Amplify CLI Version**
4.2.0

**To Reproduce**
Activate "Pause compute capacity after consecutive minutes of inactivity" in your aurora serverless database and setup 5 minutes.
Wait more than 5 minutes and don't use your database.
Run: "amplify api add-graphql-datasource"
After "Select the Aurora Serverless cluster that will be used as the data source for your API"
You will see "Fetching Aurora Serverless cluster.." forever.

**Expected behavior**
A connection should be establish properly.

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. v13.2.0

**Additional context**
To fix the problem, go to the Query Editor and run any command to force the activation of your aurora db. For example, run "use mydb; show tables;"

**Comment by josefaidt** [comment]
**NOTE**: CLI should send command to activate RDS cluster
