### ISSUE TITLE
Throttling Exception during push

### ISSUE THREAD

**Issue by darnmark64** [aws-amplify/amplify-cli#3027]
At 11:15'ish (EST) today, I was able to perform a successful "amplify push." Since then I've been unable to perform a push. I keep getting the following:

? Are you sure you want to continue? Yes
Updating resources in the cloud. This may take a few minutes...Throttling: Rate exceeded
    at Request.extractError (C:\Users\MarkDarnell\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\protocol\query.js:50:29)
    at Request.callListeners (C:\Users\MarkDarnell\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
    at Request.emit (C:\Users\MarkDarnell\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (C:\Users\MarkDarnell\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\request.js:683:14)
    at Request.transition (C:\Users\MarkDarnell\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\Users\MarkDarnell\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\Users\MarkDarnell\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\Users\MarkDarnell\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\Users\MarkDarnell\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\request.js:685:12)
    at Request.callListeners (C:\Users\MarkDarnell\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\sequential_executor.js:116:18)
× An error occurred when pushing the resources to the cloud

Project stack doesn't exist
An error occured during the push operation: Project stack doesn't exist

I don't know how to fix this issue and **I CAN NO LONGER UPDATE** my baseline. A co-worker is not having any issues at this time but he did have problems yesterday. We are using multiple environments and teams as described in the Amplify Quickstart documentation. I even tried doing "amplify env pull" with NO success.

**Comment by yuth** [comment]
We have a similar issue reported in #3019 and have PR #3020 where we have added re-try logic
