### ISSUE TITLE
amplify api add-graphql-datasource fails when using schema subdirectory

### ISSUE THREAD

**Issue by berenddeboer** [aws-amplify/amplify-cli#3082]
**Describe the bug**

`amplify api add-graphql-datasource` fails when you have put your schema(s) in the `schema` subdirectory, so there is no `schema.graphql` in the API directory.

```
? Select the database to use as the datasource: TESTDB
GraphQLError: Syntax Error: Unexpected <EOF>
    at syntaxError (/usr/lib/node_modules/@aws-amplify/cli/node_modules/graphql/error/syntaxError.js:24:10)
    at unexpected (/usr/lib/node_modules/@aws-amplify/cli/node_modules/graphql/language/parser.js:1322:33)
    at parseDefinition (/usr/lib/node_modules/@aws-amplify/cli/node_modules/graphql/language/parser.js:152:9)
    at parseDocument (/usr/lib/node_modules/@aws-amplify/cli/node_modules/graphql/language/parser.js:110:22)
    at Object.parse (/usr/lib/node_modules/@aws-amplify/cli/node_modules/graphql/language/parser.js:38:10)
    at datasourceSelectionPrompt.then.then.then.graphqlSchemaContext (/usr/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/commands/api/add-graphql-datasource.js:111:46)
    at process._tickCallback (internal/process/next_tick.js:68:7)
There was an error adding the datasource
```

**Amplify CLI Version**
4.7.0

**To Reproduce**
Create a `schema` subdirectory, move `schema.graphql` in there and rename it to `demo.graphql` for example.

**Expected behavior**
If there is no `schema.graphql` directory, create new schema in the subdirectory.

**Desktop**
 - OS: Ubuntu 19.10
 - Node Version: 10.18.0

**Comment by dtelaroli** [comment]
+1

but for me does not working with even the schema.graphql in the default folder.
any workaround?

**Comment by yahavb** [comment]
+1
per https://github.com/aws-amplify/amplify-cli/issues/3536 

Any ETA?
