### ISSUE TITLE
colon in S3 path is invalid for Windows file path

### ISSUE THREAD

**Issue by gaochenyue** [aws-amplify/amplify-cli#3215]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
For the S3 mock on Windows, the S3 file path of a private put has a colon, e.g `us-west-2:e2b2fdb8-38b8-4e47-8594-316a20dea577`,  which is an invalid character for Windows file path. When put a file with private level, it failed with the error below
```
(node:9360) UnhandledPromiseRejectionWarning: Error: E:\webWokrspace\programs\app\amplify\mock-data\S3\app\private\us-west-2:e2b2fdb8-38b8-4e47-8594-316a20dea577\labelx\2019 contains invalid WIN32 path characters.
    at Object.mkdirsSync (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\fs-extra\lib\mkdirs\mkdirs-sync.js:18:22)
    at Object.createFileSync (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\fs-extra\lib\ensure\file.js:40:11)
    at StorageServer.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-storage-simulator\src\server\S3server.ts:212:5)
    at Generator.next (<anonymous>)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-storage-simulator\lib\server\S3server.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-storage-simulator\lib\server\S3server.js:4:12)
    at StorageServer.handleRequestPut (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-storage-simulator\lib\server\S3server.js:195:16)
    at StorageServer.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-storage-simulator\src\server\S3server.ts:90:12)
    at Generator.next (<anonymous>)
(node:9360) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9360) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
**Amplify CLI Version**
4.12.0
**To Reproduce**
Run the following code in mock mode
```
Storage.put(s3Key, xlsxFile, {
        level: "private",
        contentType: "application/octet-stream"
    });
```
**Expected behavior**
The file can be save succefully

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version. 10

**Additional context**

**Comment by SimonLegg** [comment]
Just as a note: any contentType will cause this. I commented on a [related issue in a different repo](https://github.com/jamhall/s3rver/issues/390) 

## Angular Workaround (use environment.production)
```
await Storage.put(fileName, file, {
    level: environment.production ? 'private': 'public',
});
await Storage.get('myFileKey', { 
    level: environment.production ? 'private' : 'public' 
});
```
