### ISSUE TITLE
Amplify init profile selection fails - UnhandledPromiseRejectionWarning: AccessDenied: Access Denied

### ISSUE THREAD

**Issue by joakweb** [aws-amplify/amplify-cli#3263]
**Describe the bug**
Using `amplify init` in my project, when I get to the profile selection part, I get the error `UnhandledPromiseRejectionWarning: AccessDenied: Access Denied` and the routine stops indefinitely at `\ Initializing your environment: dev`

**Amplify CLI Version**
4.12.0

**To Reproduce**

```
PS D:\dev\hpd-mobile-app> amplify init
Note: It is recommended to run this command from the root of your app directory
? Do you want to use an existing environment? Yes
? Choose the environment you would like to use: dev
? Choose your default editor: Atom Editor
Using default provider  awscloudformation

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html

? Do you want to use an AWS profile? Yes
? Please choose the profile you want to use default
/ Initializing your environment: dev(node:6704) UnhandledPromiseRejectionWarning: AccessDenied: Access Denied
    at Request.extractError (C:\Users\jcarvalho\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\services\s3.js:816:35)
    at Request.callListeners (C:\Users\jcarvalho\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
    at Request.emit (C:\Users\jcarvalho\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (C:\Users\jcarvalho\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\request.js:683:14)
    at Request.transition (C:\Users\jcarvalho\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\Users\jcarvalho\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\Users\jcarvalho\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\Users\jcarvalho\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\Users\jcarvalho\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\request.js:685:12)
    at Request.callListeners (C:\Users\jcarvalho\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\sequential_executor.js:116:18)
(node:6704) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6704) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
\ Initializing your environment: dev
```

**Expected behavior**
The routine doesn't stop indefinitely at "\ Initializing your environment: dev    ", profile is chosen then my environment is ready for development

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version: 12.9.1

**Comment by SwaySway** [comment]
Hello @joakweb 
Do you specific iam permissions on the default aws profile?

**Comment by kaustavghosh06** [comment]
Looks like it's you're getting an "AccessDenied" error - tied to your accessKey and secretKey which doesn't seem to be correct. How did you configure your profile?

**Comment by joakweb** [comment]
@SwaySway 
Yes. My profile is currently associated with an admin access user.

@kaustavghosh06 
Sure, amplify configure runs without trouble. See below:

```
PS D:\dev\hpd-mobile-app> amplify configure                                                                                                                                                                                                  Follow these steps to set up access to your AWS account:

Sign in to your AWS administrator account:
https://console.aws.amazon.com/
Press Enter to continue

Specify the AWS Region
? region:  us-east-2
Specify the username of the new IAM user:
? user name:  amplify-5RzfD
Complete the user creation using the AWS console
https://console.aws.amazon.com/iam/home?region=undefined#/users$new?step=final&accessKey&userNames=amplify-5RzfD&permissionType=policies&policies=arn:aws:iam::aws:policy%2FAdministratorAccess
Press Enter to continue

Enter the access key of the newly created user:
? accessKeyId:  ******************
? secretAccessKey:  ***********************
This would update/create the AWS Profile in your local machine
? Profile Name:  default

Successfully set up the new user.
```

I checked the credentials file inside the folder .aws. Everything seemed fine there.

**Comment by joakweb** [comment]
There was something wrong with the initialization of amplify on the branch I was working. Everything's in order now. Thanks.

**Comment by parthshah111** [comment]
hy

**Comment by sotomaque** [comment]
how did you resolve this? i am facing the same issue
