### ISSUE TITLE
Switch between two environments should be clarified in docs

### ISSUE THREAD

**Issue by sorokinvj** [aws-amplify/amplify-cli#3271]
**Is your feature request related to a problem? Please describe.**
Last week I switched from my working machine to a temporary one and today I switched back. In both "switchings" I stumbled upon many errors during amplify pull, which you would normally want to do to continue your work. 

In both cases what I was needed was the command:

```
amplify configure project
```
which now in the docs is explained as "is an advanced command and not commonly used for getting started or individual development projects."

However, I think its the important thing and the case (imagine your machine suddenly breaks and you have a replacement laptop). So maybe this case of switching between environments has to be stated more concisely in the docs.

**Comment by SwaySway** [comment]
Hello @sorokinvj 
Are you able to provide the error log either here or email, amplify-cli@amazon.com?

**Comment by sorokinvj** [comment]
@SwaySway When I first tried to transfer the project from laptop A to B it was an error "Can't find a file (don't remember which one) in amplify/#current-cloud-backend", then when I transfered the project back from B to A it was:

```
✖ There was an error pulling the backend environment maingitrep.
Stack with id speechmedia-maingitrep-20191125174542 does not exist
ValidationError: Stack with id speechmedia-maingitrep-20191125174542 does not exist
    at Request.extractError (/Users/vladislavsorokin/.nvm/versions/node/v12.6.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/Users/vladislavsorokin/.nvm/versions/node/v12.6.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/vladislavsorokin/.nvm/versions/node/v12.6.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/vladislavsorokin/.nvm/versions/node/v12.6.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/vladislavsorokin/.nvm/versions/node/v12.6.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/vladislavsorokin/.nvm/versions/node/v12.6.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/vladislavsorokin/.nvm/versions/node/v12.6.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/vladislavsorokin/.nvm/versions/node/v12.6.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/vladislavsorokin/.nvm/versions/node/v12.6.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/vladislavsorokin/.nvm/versions/node/v12.6.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
```
I think the problem appeared in both cases because in amplify/.config/local-aws-info.json there was a different profile: 

```
{
    "maingitrep": {
        "configLevel": "project",
        "useProfile": true,
        "profileName": "AWS Amplify" // this profile is different on different computers, maybe I should name it identical, but it was too late when I figured this out
    }
}
```

**Comment by sorokinvj** [comment]
in both cases problem was solved immediately after 
```
amplify configure project
```

**Comment by UnleashedMind** [comment]
@sorokinvj 
The local config files in the `amplify/.config` folder are not checked into code repo, when you run `amplify pull` for the first time on another computer, you will be prompted to select profile along with other questions to setup those local config files. 
`amplify configure project` is only needed to correct the settings if you have selected the wrong one during the first `amplify pull` run.

**Comment by sorokinvj** [comment]
amplify pull in my both cases produced some error, but I am really sorry that I didn't collect one.

**Comment by UnleashedMind** [comment]
It's very likely the same error, it's because the credential profile you selected does not have the permissions to access the aws resources associated with your backend environment. And you can run amplify configure project to correct it.
