### ISSUE TITLE
Cannot create new env: AlreadyExistsException: Stack [amplify-myproj-samdev-152827] already exists

### ISSUE THREAD

**Issue by elimence** [aws-amplify/amplify-cli#3287]
**Describe the bug**
I cloned an existing project and initialized an env called `prod`.
I tried creating a new env `samdev` (I removed it with `amplify env remove` earlier when `amplify push` kept failing on that env) but I keep getting the following error:
```
⠴ Initializing project in the cloud...An error occurred when creating the CloudFormation stack
✖ Root stack creation failed
init failed
AlreadyExistsException: Stack [amplify-myproj-samdev-152827] already exists
    at Request.extractError (/Users/elimence/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/Users/elimence/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/elimence/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/elimence/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/elimence/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/elimence/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/elimence/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/elimence/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/elimence/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/elimence/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  message: 'Stack [amplify-myproj-samdev-152827] already exists',
  code: 'AlreadyExistsException',
  time: 2020-01-28T00:00:36.146Z,
  requestId: '0779f95e-af14-4890-9e51-d05f1812733e',
  statusCode: 400,
  retryable: false,
  retryDelay: 27.05650614071111
}```

Running `amplify env remove samdev` says the env doesn't exist

I also check https://console.aws.amazon.com/appsync/home?region=us-east-1#/apis and there's no trace of samdev

**Amplify CLI Version**
4.13.1

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. 13.2.0

**Comment by yuth** [comment]
@elimence `amplify env remove` looks at the `<project-root>/amplify/team-provider-info.json` to determine if an environment exists or not. Could you check logging into AWS Cloudformation console and see if there indeed is a stack with name `amplify-myproj-samdev-152827`. 

Technically whenever a new environment is added, it should follow the following pattern to name the CloudFormation stack `amplify-<projName>-<envName>-<randomNumber>`. Could you try to run `amplify env add` command again and see if the same name is generated for the environment

**Comment by elimence** [comment]
@yuth Checked and there's indeed a stack with that name, it's status is set to `UPDATE_ROLLBACK_COMPLETE`.
I'm not very familiar with cloudformation, should I attempt to delete it from here?

Trying to add `samdev` still fails. I tried adding another env and it did create a stack in cloudformation with that naming convention.

**Comment by yuth** [comment]
you could select the root stack of that Environment in CloudFormation console and click on delete stack as documented [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-console-delete-stack.html)

Just before deleting the stack could you share your `team-provider-info.json`. Please make sure you have redacted sensitive info from the file

**Comment by UnleashedMind** [comment]
@elimence 
I could not reproduce the issue. 
Root stack name clash is very unlikely, especially when you try it multiple times during one day because there's a timestamp string appended to the name. 
You can just go ahead and remove that stack on the Cloudformation Console if its resources are no longer needed. 
In what AWS region did you create the env?

**Comment by elimence** [comment]
@yuth @UnleashedMind 

The env was created in `us-east-1`
```
{
    "prod": {
        "awscloudformation": {
            "AuthRoleName": "amplify-myproj-prod-210654-authRole",
            "UnauthRoleArn": "arn:aws:iam::675309137591:role/amplify-myproj-prod-210654-unauthRole",
            "AuthRoleArn": "arn:aws:iam::675309137591:role/amplify-myproj-prod-210654-authRole",
            "Region": "us-east-1",
            "DeploymentBucketName": "amplify-myproj-prod-210654-deployment",
            "UnauthRoleName": "amplify-myproj-prod-210654-unauthRole",
            "StackName": "amplify-myproj-prod-210654",
            "StackId": "arn:aws:cloudformation:us-east-1:675309137591:stack/amplify-myproj-prod-210654/54278150-2691-11ea-9379-0a99e59b1983",
            "AmplifyAppId": "d11w7z8nivpu0n"
        },
        "categories": {
            "auth": {
                "myAuthc63cb94d": {}
            }
        }
    },
    "ericdev": {
        "awscloudformation": {
            "AuthRoleName": "amplify-myproj-ericdev-122252-authRole",
            "UnauthRoleArn": "arn:aws:iam::482634744216:role/amplify-myproj-ericdev-122252-unauthRole",
            "AuthRoleArn": "arn:aws:iam::482634744216:role/amplify-myproj-ericdev-122252-authRole",
            "Region": "us-east-1",
            "DeploymentBucketName": "amplify-myproj-ericdev-122252-deployment",
            "UnauthRoleName": "amplify-myproj-ericdev-122252-unauthRole",
            "StackName": "amplify-myproj-ericdev-122252",
            "StackId": "arn:aws:cloudformation:us-east-1:482634744216:stack/amplify-myproj-ericdev-122252/9cf24ac0-23ec-11ea-8fc7-0e43f2110cc5"
        },
        "categories": {
            "auth": {
                "myAuthc63cb94d": {}
            }
        }
    },
    "stage": {
        "awscloudformation": {
            "AuthRoleName": "amplify-myproj-stage-233930-authRole",
            "UnauthRoleArn": "arn:aws:iam::675309137591:role/amplify-myproj-stage-233930-unauthRole",
            "AuthRoleArn": "arn:aws:iam::675309137591:role/amplify-myproj-stage-233930-authRole",
            "Region": "us-east-1",
            "DeploymentBucketName": "amplify-myproj-stage-233930-deployment",
            "UnauthRoleName": "amplify-myproj-stage-233930-unauthRole",
            "StackName": "amplify-myproj-stage-233930",
            "StackId": "arn:aws:cloudformation:us-east-1:675309137591:stack/amplify-myproj-stage-233930/a5ab8750-26a6-11ea-8a07-12a48490849f",
            "AmplifyAppId": "d11w7z8nivpu0n"
        },
        "categories": {
            "auth": {
                "myAuthc63cb94d": {}
            }
        }
    }
}
```

I successfully deleted the stack and tried adding the env, I got this error:

```
CREATE_FAILED      AuthRole                          AWS::IAM::Role             Thu Jan 30 2020 09:01:07 GMT+0000 (Greenwich Mean Time) Resource creation cancelled
CREATE_FAILED      UnauthRole                        AWS::IAM::Role             Thu Jan 30 2020 09:01:06 GMT+0000 (Greenwich Mean Time) Resource creation cancelled
CREATE_IN_PROGRESS AuthRole                          AWS::IAM::Role             Thu Jan 30 2020 09:01:06 GMT+0000 (Greenwich Mean Time) Resource creation Initiated
CREATE_FAILED      DeploymentBucket                  AWS::S3::Bucket            Thu Jan 30 2020 09:01:06 GMT+0000 (Greenwich Mean Time) amplify-myproj-samdev-152827-deployment already exists
```

```
ROLLBACK_COMPLETE amplify-myproj-samdev-152827 AWS::CloudFormation::Stack Thu Jan 30 2020 09:01:30 GMT+0000 (Greenwich Mean Time)
⠙ Initializing project in the cloud...An error occurred when  creating the CloudFormation stack
✖ Root stack creation failed
init failed
TypeError: Cannot read property 'Stacks' of null
    at processStackCreationData (/Users/elimence/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/initializer.js:88:44)
    at /Users/elimence/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/initializer.js:62:9
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

After deleting the S3 deployment bucket, I was able to create the env successfully.
Never run into this issue before this incident, there's a chance I may have inadvertently messed something up.

**Comment by olivoil** [comment]
This happened to me in a PR preview in the amplify console. 

When I created the PR, the first build failed for another reason. When I fixed the issue and pushed a commit to the PR, it tried to deploy again, but then showed this error `AlreadyExistsException: Stack [amplify-<project-name>-prbe-35825] already exists`

**Comment by UnleashedMind** [comment]
@elimence 
Did you also get the error from Amplify Console?

**Comment by elimence** [comment]
@UnleashedMind No, mine is from the amplify-cli

**Comment by monaye** [comment]
@UnleashedMind 
I got the same error from Amplify Console.

**Comment by UnleashedMind** [comment]
@elimence 
but you are un-blocked after you removed the S3 bucket right? 
"After deleting the S3 deployment bucket, I was able to create the env successfully."

**Comment by elimence** [comment]
@UnleashedMind Yes that's correct.
