### ISSUE TITLE
`amplify codegen model` fails on `AWS*`scalar types

### ISSUE THREAD

**Issue by cpiro** [aws-amplify/amplify-cli#3296]
In the latest version 4.13.1, if `schema.graphql` contains an AWS-defined scalar type — e.g. `AWSEmail` —`amplify codegen model` exits with the error `Type "AWSEmail" not found in document."`. This schema fails:

```graphql
type Post {
  id: ID
  email: AWSEmail
}
```

Specifically, the scalar definitions are passed to `gqlCodeGen.codegen`, but inside that function, `schemaMerging.mergeSchemas` is called in such a way that the scalar definitions are inaccessible, so those types are unknown. The relevant Promise(s) `await`ed at [amplify-codegen/src/commands/models.js:67](https://github.com/aws-amplify/amplify-cli/blob/12eacbee29be477c197f3d4324f638ad951a5aae/packages/amplify-codegen/src/commands/models.js#L67) is rejected, and the error `Type "AWSEmail" not found in document."` is thrown.

Redefining the scalar at the top of `schema.graphql` is (correctly) an error: `There can be only one type named "AWSEmail".`

```graphql
scalar AWSEmail
type Post {
  id: ID
  email: AWSEmail
}
```

The error happens as the schema is input and before actual code generation starts, so it seems unrelated to choice of output language.

**Expected behavior**
`amplify codegen model` should succeed. Removing the affected field(s) or changing them to a non-AWS-defined type works as expected.

**Versions**
```
$ uname
Darwin
$ amplify -v
4.13.1
$ node -v
v13.6.0
```

**To Reproduce**
Install the CLI, then run `amplify init`, `amplify add api`, and `amplify codegen model`. In the following transcript I choose `ios` as the "type of app that you're building", but choosing `javascript` and `react` gives identical results.

```
$ npm install -g @aws-amplify/cli@latest
[...]
+ @aws-amplify/cli@4.13.1

$ amplify init
[...]
? Choose the type of app that you're building ios
[...]

$ cat > minimal.graphql
type Post {
  id: ID
  email: AWSEmail
}

$ amplify add api
[...]
? Provide your schema file path: minimal.graphql
[...]

$ amplify codegen model

GraphQL schema compiled successfully.

Edit your schema at [...] or place .graphql files in a directory at [...]
Type "AWSEmail" not found in document.
Error: Type "AWSEmail" not found in document.
    at ASTDefinitionBuilder._resolveType (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/utilities/buildASTSchema.js:94:13)
    at ASTDefinitionBuilder.getNamedType (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/utilities/buildASTSchema.js:171:37)
    at ASTDefinitionBuilder.getWrappedType (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/utilities/buildASTSchema.js:183:17)
    at ASTDefinitionBuilder.buildField (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/utilities/buildASTSchema.js:212:18)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/utilities/buildASTSchema.js:303:23
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/jsutils/keyValMap.js:27:24
    at Array.reduce (<anonymous>)
    at keyValMap (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/jsutils/keyValMap.js:26:15)
    at keyByNameNode (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/utilities/buildASTSchema.js:396:33)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/utilities/buildASTSchema.js:302:14

$ cat > amplify/backend/api/aws/schema.graphql
type Post {
  id: ID
  email: String
}

$ amplify codegen model

GraphQL schema compiled successfully.

Edit your schema at [...] or place .graphql files in a directory at [...]
Successfully generated models. Generated models can be found [...]

$ cat > amplify/backend/api/aws/schema.graphql
scalar AWSEmail
type Post {
  id: ID
  email: AWSEmail
}

$ amplify codegen model
There can be only one type named "AWSEmail".
Error: There can be only one type named "AWSEmail".
    at assertValidSDL (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/validation/validate.js:108:11)
    at Object.buildASTSchema (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/utilities/buildASTSchema.js:71:34)
    at Object.exports.validateModelSchema (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/validation.ts:141:18)
    at GraphQLTransform.transform (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/GraphQLTransform.ts:240:20)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/util/amplifyUtils.ts:53:35
    at step (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/amplifyUtils.js:44:23)
    at Object.next (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/amplifyUtils.js:25:53)
    at fulfilled (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/amplifyUtils.js:16:58)
```

**Comment by CarlitosBeto** [comment]
Hello @cpiro is only in this version of amplify cli?, i need generate a model and i couldn`t or is in all versions?

**Comment by cpiro** [comment]
The other `amplify codegen` subcommands (not `model`) seem to use a different code generator and are unaffected by this — and several other — issues. I haven't tried different versions of this npm package, but I suspect that `amplify codegen model` just doesn't yet support these scalars.

**Comment by Rjgoolsby** [comment]
Watching this because I'm experiencing the same issue

**Comment by CarlitosBeto** [comment]
I have the same issue

**Comment by liamor** [comment]
Just hit the same
