### ISSUE TITLE
amplify api add-graphql-datasource fails with error: Cannot find module 'cloudform'

### ISSUE THREAD

**Issue by cendenta** [aws-amplify/amplify-cli#3344]
**Describe the bug**

`amplify api add-graphql-datasource` fails for a new Amplify API. 

```
Cannot find module 'cloudform'
Require stack:
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-relational-schema-transformer/lib/RelationalDBTemplateGenerator.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-relational-schema-transformer/lib/index.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/commands/api/add-graphql-datasource.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/index.js
- /usr/local/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js
- /usr/local/lib/node_modules/@aws-amplify/cli/lib/index.js
- /usr/local/lib/node_modules/@aws-amplify/cli/bin/amplify
/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-relational-schema-transformer/lib/RelationalDBTemplateGenerator.js:1
Error: Cannot find module 'cloudform'
Require stack:
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-relational-schema-transformer/lib/RelationalDBTemplateGenerator.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-relational-schema-transformer/lib/index.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/commands/api/add-graphql-datasource.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/index.js
- /usr/local/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js
- /usr/local/lib/node_modules/@aws-amplify/cli/lib/index.js
- /usr/local/lib/node_modules/@aws-amplify/cli/bin/amplify
    at Object.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-relational-schema-transformer/lib/RelationalDBTemplateGenerator.js:6:21)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
```

**Amplify CLI Version**
4.13.1

**To Reproduce**
1. `amplify add api` to set up a new API
2. `amplify push` to provision the API in the cloud
3. `amplify api add-graphql-datasource` generates error

**Expected behavior**
To continue setting up a GraphQL datasource for a new Amplify API.

**Desktop**
OS: Ubuntu 18.04
Node Version: 12.14.1

**Comment by UnleashedMind** [comment]
@cendenta I've reproduced the bug, Thanks for notifying us.
