### ISSUE TITLE
Cannot destructure property `AmplifyAppId` of 'undefined' or 'null' on amplify pull

### ISSUE THREAD

**Issue by amirhajimirsadeghi** [aws-amplify/amplify-cli#3360]
Here is the error I get
```
> amplify pull --appId XXXX --envName staging
Cannot destructure property `AmplifyAppId` of 'undefined' or 'null'.
TypeError: Cannot destructure property `AmplifyAppId` of 'undefined' or 'null'.
    at /usr/local/lib/node_modules/@aws-amplify/cli/lib/commands/pull.js:27:64
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/@aws-amplify/cli/lib/commands/pull.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/@aws-amplify/cli/lib/commands/pull.js:4:12)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/lib/commands/pull.js:18:23)
    at Object.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/lib/index.js:114:29)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/@aws-amplify/cli/lib/index.js:8:71
    at new Promise (<anonymous>)
```
**Version:** 4.11.0

I can't figure out what's going on from the error message

**Comment by amirhajimirsadeghi** [comment]
Figured it out. Make sure to have `AmplifyAppId` defined in `amplify/team-provider-info.json` under  `<env>.awscloudformation`
