### ISSUE TITLE
npx amplify-app init --quickstart fails on Windows 10

### ISSUE THREAD

**Issue by attilah** [aws-amplify/amplify-cli#3396]
amplify-app fails on Windows 10 when spawning Amplify CLI.

```
🎸 Creating base Amplify project
events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: spawn amplify ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn amplify',
  path: 'amplify',
  spawnargs: [ 'init', '--quickstart' ]
}
```
Desktop:

* OS: Windows 10
* Node Version. 12.15.0
* AWS Amplify-cli 4.13.2

https://github.com/aws-amplify/amplify-cli/issues/3379#issuecomment-584474190

**Comment by apoorvmote** [comment]
Today's release fixed it. Yesterday it was not working. But today its working.
