### ISSUE TITLE
Amplify Pull with a profile specified in --awsInfo fails to find app

### ISSUE THREAD

**Issue by dbhagen** [aws-amplify/amplify-cli#3413]
**Describe the bug**
When I perform the following command, I'm able to pull my environment correctly:
```
amplify pull --appId XXXXXXXX --envName dev

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html

? Do you want to use an AWS profile? Yes
? Please choose the profile you want to use personaleast1
Amplify AppID found: XXXXXXXX. Amplify App name is: MyAppName
```

When I specify the `--awsInfo` argument with the following:
```
amplify pull --appId XXXXXXXX --envName dev --yes --awsInfo {"configLevel":"project","useProfile":true,"profileName":"amplifyrole"}
```
or if I just specifying the `--yes` argument, anticipating it will pull the AWS CLI profile from my shell session, the following error results:
```
amplify pull --appId XXXXXXXX --envName dev --yes

Amplify AppID: XXXXXXXX not found. Please ensure your local profile matches the AWS account or region in which the Amplify app exists.
NotFoundException: App XXXXXXXX not found.
    at Object.extractError (/Users/dhagen/.nvm/versions/node/v13.6.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.extractError (/Users/dhagen/.nvm/versions/node/v13.6.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/Users/dhagen/.nvm/versions/node/v13.6.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/dhagen/.nvm/versions/node/v13.6.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/dhagen/.nvm/versions/node/v13.6.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/dhagen/.nvm/versions/node/v13.6.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/dhagen/.nvm/versions/node/v13.6.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/dhagen/.nvm/versions/node/v13.6.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/dhagen/.nvm/versions/node/v13.6.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/dhagen/.nvm/versions/node/v13.6.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12) {
  message: 'App XXXXXXXX not found.',
  code: 'NotFoundException',
  time: 2020-02-12T19:16:41.355Z,
  requestId: '940de103-82ba-42ab-addd-d2400ab49083',
  statusCode: 404,
  retryable: false,
  retryDelay: 45.92666615486441
}
Failed to pull the backend.
NotFoundException: App XXXXXXXX not found.
    at Object.extractError (/Users/dhagen/.nvm/versions/node/v13.6.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.extractError (/Users/dhagen/.nvm/versions/node/v13.6.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/Users/dhagen/.nvm/versions/node/v13.6.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/dhagen/.nvm/versions/node/v13.6.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/dhagen/.nvm/versions/node/v13.6.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/dhagen/.nvm/versions/node/v13.6.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/dhagen/.nvm/versions/node/v13.6.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/dhagen/.nvm/versions/node/v13.6.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/dhagen/.nvm/versions/node/v13.6.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/dhagen/.nvm/versions/node/v13.6.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12) {
  message: 'App XXXXXXXX not found.',
  code: 'NotFoundException',
  time: 2020-02-12T19:16:41.355Z,
  requestId: '940de103-82ba-42ab-addd-d2400ab49083',
  statusCode: 404,
  retryable: false,
  retryDelay: 45.92666615486441
}
```

**Amplify CLI Version**
```
$ amplify -v
4.13.1
```

**To Reproduce**
Specified above in the description.

**Expected behavior**
Also basically described in the first section.

**Screenshots**
The terminal output provided above.

**Desktop (please complete the following information):**
 - OS: `MacOS`
 - Node Version: `v13.6.0`

**Additional context**
Trying to set up a command for `amplify.yaml` to perform to pull the Amplify environment into the cloned codebase during the build.

**Comment by UnleashedMind** [comment]
`amplify pull` does not  take the `--awsInfo` input parameter, so the profile specification is not taken in by the CLI. The `--yes` flag will suppress command line prompt, The CLI will just rely on the aws-sdk to resolve the credentials, very likely using the `default` profile, which is different than the original account when the Amplify Console Project is created. that's why you got the error. 
It's very difficult to pass in stringified JSON object on command line, you can instead run a headless script, like the following: 

``` bash
#!/bin/bash
set -e
IFS='|'

AWSCLOUDFORMATIONCONFIG="{\
\"configLevel\":\"project\",\
\"useProfile\":true,\
\"profileName\":\"default\"\
}"
AMPLIFY="{\
\"appId\":\"yourAppid\",\
\"envName\":\"yourEnvName\"\
}"
PROVIDERS="{\
\"awscloudformation\":$AWSCLOUDFORMATIONCONFIG\
}"

amplify pull \
--amplify $AMPLIFY \
--providers $PROVIDERS \
--yes

```

**Comment by dbhagen** [comment]
Hello @UnleashedMind,

I've been trying the headless script like you sent. I probably just mixed up the push vs. pull scripts with the `--awsInfo` flag.

So using the script you gave, the following command is formed and included is it's result.
```
amplify pull --amplify {"appId":"XXXXXXXX","envName":"localdev"} --providers {"awscloudformation":{"configLevel":"project","useProfile":true,"profileName":"default"}}
Scanning for plugins...
Plugin scan successful
Cannot create property 'providers' on string 'appId:XXXXXXXX'
TypeError: Cannot create property 'providers' on string 'appId:XXXXXXXX'
    at transform (/Users/dhagen/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/src/input-params-manager.js:43:32)
    at normalizeInputParams (/Users/dhagen/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/src/input-params-manager.js:8:3)
    at constructInputParams (/Users/dhagen/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/src/amplify-service-helper.js:4:23)
    at Object.run (/Users/dhagen/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/src/commands/pull.js:11:25)
    at Object.executeAmplifyCommand (/Users/dhagen/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/src/index.ts:96:23)
    at executePluginModuleCommand (/Users/dhagen/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:56:26)
    at Object.executeCommand (/Users/dhagen/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:21:5)
    at Object.run (/Users/dhagen/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/src/index.ts:40:5)
```

```
➜ amplify -v
4.13.3
```

**Comment by dbhagen** [comment]
Ok, just a quick follow up. I'm running in a ZSH shell, and it's behaving the same as I mentioned in the BASH based build container in the build pipeline. By adding single quotes around the JSON, the error above goes away. Copying the code here:

```bash
#!/bin/bash
set -e
IFS='|'

AWSCLOUDFORMATIONCONFIG="{\
\"configLevel\":\"project\",\
\"useProfile\":true,\
\"profileName\":\"default\"\
}"
AMPLIFY="'{\
\"appId\":\"yourAppid\",\
\"envName\":\"yourEnvName\"\
}'"
PROVIDERS="'{\
\"awscloudformation\":$AWSCLOUDFORMATIONCONFIG\
}'"

amplify pull \
--amplify $AMPLIFY \
--providers $PROVIDERS \
--yes
```

Actually, if anyone wants my script code, this is what I'm doing to produce the same idea, just with passable flags:
```bash
#!/bin/bash
set -e
IFS='|'
args=("$@")

appId=""
envName=""
useProfile="false"
profileName="default"
for ((argPos=0; argPos <= ${#args}; argPos++))
do
  if [ "${args[$argPos]}" == "--appid" ]; then
    appId="${args[(($argPos+1))]}"
    argPos=$((argPos+1))
  elif [ "${args[$argPos]}" == "--envName" ]; then
    envName="${args[(($argPos+1))]}"
    argPos=$((argPos+1))
  elif [ "${args[$argPos]}" == "--useProfile" ]; then
    useProfile="true"
  elif [ "${args[$argPos]}" == "--profileName" ]; then
    profileName="${args[(($argPos+1))]}"
    argPos=$((argPos+1))
  fi
done

AWSCLOUDFORMATIONCONFIG="{\
\"configLevel\":\"project\",\
\"useProfile\":${useProfile},\
\"profileName\":\"${profileName}\"\
}"
AMPLIFY="'{\
\"appId\":\"${appId}\",\
\"envName\":\"${envName}\"\
}'"
PROVIDERS="'{\
\"awscloudformation\":$AWSCLOUDFORMATIONCONFIG\
}'"

cmd="amplify pull --providers ${PROVIDERS} --amplify ${AMPLIFY} --yes"
echo $cmd
eval $cmd
```

**Comment by dbhagen** [comment]
That was it! Amplify Build pipeline was able to pull in the project without any `aws-exports.js` being committed, just the way I wanted it!

Any objection to me submitting a PR for the script above? I need to put some error checking in to make me happy, though.
