### ISSUE TITLE
amplify env remove someEnv failed

### ISSUE THREAD

**Issue by ambriglia** [aws-amplify/amplify-cli#3451]
**Describe the bug**
I ran `amplify env remove someEnv` and the cmd threw an error.

**Amplify CLI Version**
4.11.0

**To Reproduce**
1. `amplify env add`
2. `amplify push`
3. `amplify env checkout prod`
4. `amplify env remove someEnv`

**Expected behavior**
I was not expecting the `remove` cmd to error out.

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. 12.14

**Additional context**
The remove cmd threw a few errors, I will paste the output below. Also, it didn't stop executing, my cli was just hung. I had to kill the cmd manually. Cloudformation did actually delete everything successfully. Here is the output...

```
amplify env remove staging
? Are you sure you want to continue? (This would delete all the environments of the project from the cloud and wipe out all the local amplify resource files) Yes
⠋ Deleting resources from the cloud. This may take a few minutes...
Deleting env:staging
⠇ Deleting resources from the cloud. This may take a few minutes...(node:12416) UnhandledPromiseRejectionWarning: MissingRequiredParameter: Missing required key 'Bucket' in params
    at ParamValidator.fail (/Users/anthonybriglia/.nvm/versions/node/v12.14.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/param_validator.js:50:37)
    at ParamValidator.validateStructure (/Users/anthonybriglia/.nvm/versions/node/v12.14.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/param_validator.js:61:14)
    at ParamValidator.validateMember (/Users/anthonybriglia/.nvm/versions/node/v12.14.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/param_validator.js:88:21)
    at ParamValidator.validate (/Users/anthonybriglia/.nvm/versions/node/v12.14.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (/Users/anthonybriglia/.nvm/versions/node/v12.14.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/event_listeners.js:126:42)
    at Request.callListeners (/Users/anthonybriglia/.nvm/versions/node/v12.14.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at callNextListener (/Users/anthonybriglia/.nvm/versions/node/v12.14.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at /Users/anthonybriglia/.nvm/versions/node/v12.14.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/event_listeners.js:86:9
    at finish (/Users/anthonybriglia/.nvm/versions/node/v12.14.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js:379:7)
    at /Users/anthonybriglia/.nvm/versions/node/v12.14.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js:397:9
(node:12416) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:12416) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:12416) UnhandledPromiseRejectionWarning: MissingRequiredParameter: Missing required key 'Bucket' in params
    at ParamValidator.fail (/Users/anthonybriglia/.nvm/versions/node/v12.14.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/param_validator.js:50:37)
    at ParamValidator.validateStructure (/Users/anthonybriglia/.nvm/versions/node/v12.14.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/param_validator.js:61:14)
    at ParamValidator.validateMember (/Users/anthonybriglia/.nvm/versions/node/v12.14.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/param_validator.js:88:21)
    at ParamValidator.validate (/Users/anthonybriglia/.nvm/versions/node/v12.14.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (/Users/anthonybriglia/.nvm/versions/node/v12.14.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/event_listeners.js:126:42)
    at Request.callListeners (/Users/anthonybriglia/.nvm/versions/node/v12.14.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at callNextListener (/Users/anthonybriglia/.nvm/versions/node/v12.14.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at /Users/anthonybriglia/.nvm/versions/node/v12.14.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/event_listeners.js:86:9
    at finish (/Users/anthonybriglia/.nvm/versions/node/v12.14.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js:379:7)
    at /Users/anthonybriglia/.nvm/versions/node/v12.14.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js:397:9
(node:12416) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:12416) UnhandledPromiseRejectionWarning: MissingRequiredParameter: Missing required key 'Bucket' in params
    at ParamValidator.fail (/Users/anthonybriglia/.nvm/versions/node/v12.14.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/param_validator.js:50:37)
    at ParamValidator.validateStructure (/Users/anthonybriglia/.nvm/versions/node/v12.14.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/param_validator.js:61:14)
    at ParamValidator.validateMember (/Users/anthonybriglia/.nvm/versions/node/v12.14.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/param_validator.js:88:21)
    at ParamValidator.validate (/Users/anthonybriglia/.nvm/versions/node/v12.14.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (/Users/anthonybriglia/.nvm/versions/node/v12.14.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/event_listeners.js:126:42)
    at Request.callListeners (/Users/anthonybriglia/.nvm/versions/node/v12.14.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at callNextListener (/Users/anthonybriglia/.nvm/versions/node/v12.14.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at /Users/anthonybriglia/.nvm/versions/node/v12.14.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/event_listeners.js:86:9
    at finish (/Users/anthonybriglia/.nvm/versions/node/v12.14.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js:379:7)
    at /Users/anthonybriglia/.nvm/versions/node/v12.14.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js:397:9
(node:12416) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
⠴ Deleting resources from the cloud. This may take a few minutes...
```

**Comment by ammarkarachi** [comment]
@ambriglia What resources did the environment have that you attempted to delete?

**Comment by ambriglia** [comment]
A lot of different ones... S3 buckets, Lambdas, API Gateways, AppSync API, Cognito User Pool, and DynamoDB tables.

**Comment by ambriglia** [comment]
I have been removing a few environments over the past couple days and I am now seeing this consistently.

**Comment by ngnathan** [comment]
I'm having this issue too.


```
amplify env remove devorg
? Are you sure you want to continue? (This would delete all the environments of the project from the cloud and wipe out all the local amplify resource files) Yes
⠋ Deleting resources from the cloud. This may take a few minutes...
Deleting env:devorg
⠏ Deleting resources from the cloud. This may take a few minutes...(node:72697) UnhandledPromiseRejectionWarning: BucketNotEmpty: The bucket you tried to delete is not empty
    at Request.extractError (/Users/nathan/.nvm/versions/node/v13.1.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/services/s3.js:816:35)
    at Request.callListeners (/Users/nathan/.nvm/versions/node/v13.1.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/nathan/.nvm/versions/node/v13.1.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/nathan/.nvm/versions/node/v13.1.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/nathan/.nvm/versions/node/v13.1.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/nathan/.nvm/versions/node/v13.1.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/nathan/.nvm/versions/node/v13.1.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/nathan/.nvm/versions/node/v13.1.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/nathan/.nvm/versions/node/v13.1.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/nathan/.nvm/versions/node/v13.1.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
(node:72697) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:72697) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠦ Deleting resources from the cloud. This may take a few minutes...^C
```

I have the following resources:

- Auth (Cognito User Pool and User Pool Groups)
- API (GraphQL)
- Function x 3 (Pre Token Trigger, S3 Trigger, and a separate Lambda Function)
- Storage x 2 (Content, and DynamoDB)
- Hosting (S3AndCloudFront)

I tried emptying the S3 bucket associated with the environment (since the error was that the bucket isn't empty) and now I have another error.

```
❯ amplify env remove devorg
? Are you sure you want to continue? (This would delete all the environments of the project from the cloud and wipe out all the local amplify resource files) Yes
⠋ Deleting resources from the cloud. This may take a few minutes...
Deleting env:devorg
⠸ Deleting resources from the cloud. This may take a few minutes...
Error in deleting env:devorg
Stack with id amplify-project-devorg-140525 does not exist
Stack with id amplify-project-devorg-140525 does not exist
ValidationError: Stack with id amplify-project-devorg-140525 does not exist
    at Request.extractError (/Users/nathan/.nvm/versions/node/v13.1.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/Users/nathan/.nvm/versions/node/v13.1.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/nathan/.nvm/versions/node/v13.1.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/nathan/.nvm/versions/node/v13.1.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/nathan/.nvm/versions/node/v13.1.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/nathan/.nvm/versions/node/v13.1.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/nathan/.nvm/versions/node/v13.1.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/nathan/.nvm/versions/node/v13.1.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/nathan/.nvm/versions/node/v13.1.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/nathan/.nvm/versions/node/v13.1.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
⠹ Deleting resources from the cloud. This may take a few minutes...^C
```

**Comment by ammarkarachi** [comment]
@ambriglia and @ngnathan Are you using different accounts for separate environments?

**Comment by ambriglia** [comment]
@ammarkarachi No. Same account for both environments.

**Comment by ngnathan** [comment]
@ammarkarachi Same account for both environments for me as well.
