### ISSUE TITLE
 UnhandledPromiseRejectionWarning: NoSuchKey: The specified key does not exist

### ISSUE THREAD

**Issue by skysf** [aws-amplify/amplify-cli#3595]
**Which Category is your question related to?**
Vue setup

**Amplify CLI Version** 
4.13.4

**What AWS Services are you utilizing?**
Amplify API

**Provide additional details e.g. code snippets**
I've done below command successfully
```
amplify add api
```
Now I am trying to do below command
```
amplify push
```
then below ERROR shows:
```
SKY-MacBook-Pro:my-project sky$ amplify push
⠼ Fetching updates to backend environment: mpvue from the cloud.(node:61964) UnhandledPromiseRejectionWarning: NoSuchKey: The specified key does not exist.
    at Request.extractError (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/services/s3.js:816:35)
    at Request.callListeners (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
(node:61964) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:61964) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by nikhname** [comment]
Hi @skysf, which version of node are you using?

**Comment by skysf** [comment]
Hi @nikhname , I am using 10.16.0

**Comment by UnleashedMind** [comment]
@skysf 
Did you recently remove any of your S3 buckets? 
Could you do this quick check? 
1. go to the `amplify/backend/amplify-meta.json`, find the value `providers.awscloudformation.DeploymentBucketName`
2. log into your aws account on the aws web console, go to the S3 console, and see if you can find the S3 bucket with the name you got from step 1.

**Comment by kaustavghosh06** [comment]
@skysf Closing this issue due to lack of requested information. If you're still stuck please comment on this thread and we'll re-open the issue.
