### ISSUE TITLE
Amplify pull misses hostedUIProviderCreds in the team-provider.info file - An error occured during the push operation: Resource is not in the state stackUpdateComplete

### ISSUE THREAD

**Issue by jcbdev** [aws-amplify/amplify-cli#3642]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
`Amplify pull` misses `hostedUIProviderCreds` in the team-provider.info file.  This causes a push to fail with the following cloudformation error:
```
UPDATE_FAILED      authxxxxxxx630360af         AWS::CloudFormation::Stack Tue Mar 10 2020 23:26:52 GMT+0000 (Greenwich Mean Time) Template format error: Unresolved resource dependencies [hostedUIProviderCreds] in the Resources block of the template

Following resources failed

✖ An error occurred when pushing the resources to the cloud

Resource is not in the state stackUpdateComplete
An error occured during the push operation: Resource is not in the state stackUpdateComplete
```

**Amplify CLI Version**
4.13.4

**To Reproduce**

- Add federated login to project with add auth and add fb/google oauth details.
- Then push with `amplify push`
- create another project in a different folder and `amplify pull` (yes this project will update backend)
- make a change to auth (I changed the redirect urls)
- `amplify push`

**Expected behavior**
push should work/update as with the original project

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. v13.5.0

**Additional context**
Missing following section from team-provider.info file:
```
"categories": {
            "auth": {
                "roarapp630360af": {
                    "hostedUIProviderCreds": "[{\"ProviderName\":\"Facebook\",\"client_id\":\"xxxxxxxxxxxxxxx\",\"client_secret\":\"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\"},{\"ProviderName\":\"Google\",\"client_id\":\"xxxxxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com\",\"client_secret\":\"xxxxxxxxxxxxxxxxxxxxxxxx\"}]"
                }
            }
        }
```

Adding the section fixes the issue

**Comment by kaustavghosh06** [comment]
@jcbdev Yes, this is a bug. The ideal experience would be to prompt you for a question regarding it or populate it if stored in the service.

**Comment by pechisworks** [comment]
I got the same error when building a new backend version on amplify console.

```
2020-05-23T12:30:57.856Z [INFO]: # Switching to commit: d143098119aa8887ae64a2819e8a1727cc9f0206
2020-05-23T12:30:57.881Z [INFO]: Note: checking out 'd143098119aa8887ae64a2819e8a1727cc9f0206'.
                                 You are in 'detached HEAD' state. You can look around, make experimental
                                 changes and commit them, and you can discard any commits you make in this
                                 state without impacting any branches by performing another checkout.
                                 If you want to create a new branch to retain commits you create, you may
                                 do so (now or later) by using -b with the checkout command again. Example:
                                 git checkout -b <new-branch-name>
                                 HEAD is now at d143098 ..
2020-05-23T12:30:57.882Z [INFO]: # Checking for Git submodules at: /codebuild/output/src869087581/src/Stamps_Frontend/.gitmodules
2020-05-23T12:30:57.912Z [INFO]: # Retrieving cache...
2020-05-23T12:31:27.645Z [INFO]: # Extracting cache...
2020-05-23T12:31:38.472Z [INFO]: # Extraction completed
2020-05-23T12:31:38.641Z [INFO]: # Retrieving environment cache...
2020-05-23T12:31:38.722Z [INFO]: # Retrieved environment cache
2020-05-23T12:32:07.210Z [INFO]: ## Starting Backend Build
                                 # Starting phase: build
                                 # Executing command: amplifyPush --simple
2020-05-23T12:32:07.216Z [INFO]: # Getting Amplify CLI Cloud-Formation stack info from environment cache
2020-05-23T12:32:07.282Z [INFO]: # Start initializing Amplify environment: dev
2020-05-23T12:32:07.283Z [INFO]: STACKINFO={
                                 "awscloudformation": {
                                 "AuthRoleName": "stamps-project-20190414212003-authRole",
                                 "UnauthRoleArn": "arn:aws:iam::526170664677:role/stamps-project-20190414212003-unauthRole",
                                 "AuthRoleArn": "arn:aws:iam::526170664677:role/stamps-project-20190414212003-authRole",
                                 "Region": "eu-central-1",
                                 "DeploymentBucketName": "stamps-project-20190414212003-deployment",
                                 "UnauthRoleName": "stamps-project-20190414212003-unauthRole",
                                 "StackName": "stamps-project-20190414212003",
                                 "StackId": "arn:aws:cloudformation:eu-central-1:526170664677:stack/stamps-project-20190414212003/4f19a630-5eea-11e9-af5d-0a4de0a8f3d8"
                                 },
                                 "categories": {
                                 "auth": {
                                 "stampsprojectcognito": {}
                                 },
                                 "function": {
                                 "receiveStamp": {},
                                 "GraphQlResolver": {},
                                 "stampsprojectcognitoPostAuthentication": {},
                                 "stampsprojectcognitoPreSignup": {},
                                 "AdminQueries5e5c1c74": {}
                                 }
                                 }
                                 }
                                 # Importing Amplify environment: dev (amplify env import)
2020-05-23T12:32:10.639Z [INFO]: Successfully added environment from your project
2020-05-23T12:32:10.767Z [INFO]: # Initializing existing Amplify environment: dev (amplify init)
2020-05-23T12:32:14.030Z [INFO]: Note: It is recommended to run this command from the root of your app directory
2020-05-23T12:32:18.089Z [WARNING]: - Initializing your environment: dev
2020-05-23T12:32:18.618Z [WARNING]: ✔ Initialized provider successfully.
2020-05-23T12:33:30.515Z [INFO]: Could not read cloudformation template at path: /codebuild/output/src869087581/src/Stamps_Frontend/amplify/backend/api/stampsproject/build/cloudformation-template.json
2020-05-23T12:33:30.567Z [WARNING]: - Updating resources in the cloud. This may take a few minutes...
2020-05-23T12:33:36.182Z [INFO]: 
2020-05-23T12:33:36.187Z [INFO]: UPDATE_IN_PROGRESS stamps-project-20190414212003                  AWS::CloudFormation::Stack Sat May 23 2020 12:33:30 GMT+0000 (Coordinated Universal Time) User Initiated
                                 UPDATE_IN_PROGRESS functionstampsprojectcognitoPreSignup          AWS::CloudFormation::Stack Sat May 23 2020 12:33:35 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_IN_PROGRESS storagestampss3                                AWS::CloudFormation::Stack Sat May 23 2020 12:33:35 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_IN_PROGRESS functionstampsprojectcognitoPostAuthentication AWS::CloudFormation::Stack Sat May 23 2020 12:33:35 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_COMPLETE    functionstampsprojectcognitoPreSignup          AWS::CloudFormation::Stack Sat May 23 2020 12:33:35 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_COMPLETE    storagestampss3                                AWS::CloudFormation::Stack Sat May 23 2020 12:33:35 GMT+0000 (Coordinated Universal Time)
2020-05-23T12:33:36.400Z [INFO]: 
2020-05-23T12:33:36.400Z [INFO]: UPDATE_COMPLETE functionstampsprojectcognitoPostAuthentication AWS::CloudFormation::Stack Sat May 23 2020 12:33:35 GMT+0000 (Coordinated Universal Time)
2020-05-23T12:33:41.111Z [INFO]: 
2020-05-23T12:33:41.114Z [INFO]: UPDATE_IN_PROGRESS          authstampsprojectcognito      AWS::CloudFormation::Stack Sat May 23 2020 12:33:38 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_FAILED               authstampsprojectcognito      AWS::CloudFormation::Stack Sat May 23 2020 12:33:38 GMT+0000 (Coordinated Universal Time) Parameters: [hostedUIProviderCreds] must have values
                                 UPDATE_ROLLBACK_IN_PROGRESS stamps-project-20190414212003 AWS::CloudFormation::Stack Sat May 23 2020 12:33:39 GMT+0000 (Coordinated Universal Time) The following resource(s) failed to update: [authstampsprojectcognito].
2020-05-23T12:34:06.170Z [INFO]: 
2020-05-23T12:34:06.173Z [INFO]: UPDATE_IN_PROGRESS                           functionstampsprojectcognitoPreSignup          AWS::CloudFormation::Stack Sat May 23 2020 12:34:03 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_IN_PROGRESS                           functionstampsprojectcognitoPostAuthentication AWS::CloudFormation::Stack Sat May 23 2020 12:34:03 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_IN_PROGRESS                           storagestampss3                                AWS::CloudFormation::Stack Sat May 23 2020 12:34:03 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_COMPLETE                              functionstampsprojectcognitoPreSignup          AWS::CloudFormation::Stack Sat May 23 2020 12:34:03 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_COMPLETE                              functionstampsprojectcognitoPostAuthentication AWS::CloudFormation::Stack Sat May 23 2020 12:34:03 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_COMPLETE                              storagestampss3                                AWS::CloudFormation::Stack Sat May 23 2020 12:34:03 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_COMPLETE                              authstampsprojectcognito                       AWS::CloudFormation::Stack Sat May 23 2020 12:34:04 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS stamps-project-20190414212003                  AWS::CloudFormation::Stack Sat May 23 2020 12:34:05 GMT+0000 (Coordinated Universal Time)
2020-05-23T12:34:11.138Z [INFO]: 
2020-05-23T12:34:11.139Z [INFO]: UPDATE_COMPLETE          authstampsprojectcognito                       AWS::CloudFormation::Stack Sat May 23 2020 12:34:06 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_COMPLETE          storagestampss3                                AWS::CloudFormation::Stack Sat May 23 2020 12:34:06 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_COMPLETE          functionstampsprojectcognitoPostAuthentication AWS::CloudFormation::Stack Sat May 23 2020 12:34:07 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_COMPLETE          functionstampsprojectcognitoPreSignup          AWS::CloudFormation::Stack Sat May 23 2020 12:34:07 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_ROLLBACK_COMPLETE stamps-project-20190414212003                  AWS::CloudFormation::Stack Sat May 23 2020 12:34:07 GMT+0000 (Coordinated Universal Time)
2020-05-23T12:34:31.164Z [WARNING]: Error updating cloudformation stack
2020-05-23T12:34:36.172Z [INFO]: Following resources failed
2020-05-23T12:34:36.174Z [INFO]: init failed
2020-05-23T12:34:36.175Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
                                    ✖ There was an error initializing your environment.
2020-05-23T12:34:36.177Z [INFO]: { ResourceNotReady: Resource is not in the state stackUpdateComplete
                                 at constructor.setError (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/resource_waiter.js:182:47)
                                 at Request.CHECK_ACCEPTORS (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/resource_waiter.js:44:12)
                                 at Request.callListeners (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
                                 at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
                                 at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
                                 at Request.transition (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
                                 at AcceptorStateMachine.runTo (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
                                 at Request.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
                                 at Request.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12)
                                 at Request.callListeners (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
                                 at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
                                 at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
                                 at Request.transition (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
                                 at AcceptorStateMachine.runTo (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
                                 message: 'Resource is not in the state stackUpdateComplete',
                                 code: 'ResourceNotReady',
                                 retryable: false,
                                 time: 2020-05-23T12:34:31.163Z,
                                 statusCode: 200,
                                 retryDelay: 30000 }
2020-05-23T12:34:39.499Z [INFO]: Note: It is recommended to run this command from the root of your app directory
2020-05-23T12:34:40.716Z [WARNING]: - Initializing your environment: dev
2020-05-23T12:34:41.312Z [WARNING]: ✔ Initialized provider successfully.
2020-05-23T12:35:45.493Z [INFO]: Could not read cloudformation template at path: /codebuild/output/src869087581/src/Stamps_Frontend/amplify/backend/api/stampsproject/build/cloudformation-template.json
2020-05-23T12:35:45.543Z [WARNING]: - Updating resources in the cloud. This may take a few minutes...
2020-05-23T12:35:51.136Z [INFO]: 
2020-05-23T12:35:51.140Z [INFO]: UPDATE_IN_PROGRESS stamps-project-20190414212003                  AWS::CloudFormation::Stack Sat May 23 2020 12:35:45 GMT+0000 (Coordinated Universal Time) User Initiated
                                 UPDATE_IN_PROGRESS functionstampsprojectcognitoPostAuthentication AWS::CloudFormation::Stack Sat May 23 2020 12:35:49 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_IN_PROGRESS storagestampss3                                AWS::CloudFormation::Stack Sat May 23 2020 12:35:50 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_IN_PROGRESS functionstampsprojectcognitoPreSignup          AWS::CloudFormation::Stack Sat May 23 2020 12:35:50 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_COMPLETE    functionstampsprojectcognitoPostAuthentication AWS::CloudFormation::Stack Sat May 23 2020 12:35:50 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_COMPLETE    storagestampss3                                AWS::CloudFormation::Stack Sat May 23 2020 12:35:50 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_COMPLETE    functionstampsprojectcognitoPreSignup          AWS::CloudFormation::Stack Sat May 23 2020 12:35:50 GMT+0000 (Coordinated Universal Time)
2020-05-23T12:35:56.087Z [INFO]: 
2020-05-23T12:35:56.089Z [INFO]: UPDATE_IN_PROGRESS          authstampsprojectcognito      AWS::CloudFormation::Stack Sat May 23 2020 12:35:52 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_FAILED               authstampsprojectcognito      AWS::CloudFormation::Stack Sat May 23 2020 12:35:53 GMT+0000 (Coordinated Universal Time) Parameters: [hostedUIProviderCreds] must have values
                                 UPDATE_ROLLBACK_IN_PROGRESS stamps-project-20190414212003 AWS::CloudFormation::Stack Sat May 23 2020 12:35:53 GMT+0000 (Coordinated Universal Time) The following resource(s) failed to update: [authstampsprojectcognito].
2020-05-23T12:36:06.070Z [INFO]: 
2020-05-23T12:36:06.071Z [INFO]: UPDATE_IN_PROGRESS                           functionstampsprojectcognitoPreSignup          AWS::CloudFormation::Stack Sat May 23 2020 12:36:03 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_IN_PROGRESS                           functionstampsprojectcognitoPostAuthentication AWS::CloudFormation::Stack Sat May 23 2020 12:36:03 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_IN_PROGRESS                           storagestampss3                                AWS::CloudFormation::Stack Sat May 23 2020 12:36:03 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_COMPLETE                              functionstampsprojectcognitoPreSignup          AWS::CloudFormation::Stack Sat May 23 2020 12:36:03 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_COMPLETE                              functionstampsprojectcognitoPostAuthentication AWS::CloudFormation::Stack Sat May 23 2020 12:36:03 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_COMPLETE                              storagestampss3                                AWS::CloudFormation::Stack Sat May 23 2020 12:36:03 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_COMPLETE                              authstampsprojectcognito                       AWS::CloudFormation::Stack Sat May 23 2020 12:36:04 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS stamps-project-20190414212003                  AWS::CloudFormation::Stack Sat May 23 2020 12:36:05 GMT+0000 (Coordinated Universal Time)
2020-05-23T12:36:11.079Z [INFO]: 
2020-05-23T12:36:11.081Z [INFO]: UPDATE_COMPLETE          storagestampss3                                AWS::CloudFormation::Stack Sat May 23 2020 12:36:07 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_COMPLETE          authstampsprojectcognito                       AWS::CloudFormation::Stack Sat May 23 2020 12:36:07 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_COMPLETE          functionstampsprojectcognitoPreSignup          AWS::CloudFormation::Stack Sat May 23 2020 12:36:07 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_COMPLETE          functionstampsprojectcognitoPostAuthentication AWS::CloudFormation::Stack Sat May 23 2020 12:36:08 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_ROLLBACK_COMPLETE stamps-project-20190414212003                  AWS::CloudFormation::Stack Sat May 23 2020 12:36:08 GMT+0000 (Coordinated Universal Time)
2020-05-23T12:36:16.066Z [WARNING]: Error updating cloudformation stack
2020-05-23T12:36:16.171Z [INFO]: Following resources failed
2020-05-23T12:36:16.171Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
                                    ✖ There was an error initializing your environment.
2020-05-23T12:36:16.171Z [INFO]: init failed
2020-05-23T12:36:16.174Z [INFO]: { ResourceNotReady: Resource is not in the state stackUpdateComplete
                                 at constructor.setError (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/resource_waiter.js:182:47)
                                 at Request.CHECK_ACCEPTORS (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/resource_waiter.js:44:12)
                                 at Request.callListeners (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
                                 at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
                                 at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
                                 at Request.transition (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
                                 at AcceptorStateMachine.runTo (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
                                 at Request.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
                                 at Request.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12)
                                 at Request.callListeners (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
                                 at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
                                 at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
                                 at Request.transition (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
                                 at AcceptorStateMachine.runTo (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
                                 message: 'Resource is not in the state stackUpdateComplete',
                                 code: 'ResourceNotReady',
                                 retryable: false,
                                 time: 2020-05-23T12:36:16.066Z,
                                 statusCode: 200,
                                 retryDelay: 30000 }
2020-05-23T12:36:16.193Z [ERROR]: !!! Build failed
2020-05-23T12:36:16.193Z [ERROR]: !!! Non-Zero Exit Code detected
2020-05-23T12:36:16.194Z [INFO]: # Starting environment caching...
2020-05-23T12:36:16.194Z [INFO]: # Uploading environment cache artifact...
2020-05-23T12:36:16.257Z [INFO]: # Environment caching completed

```

**Comment by isyaniv** [comment]
hey, I recently had that exact issue with my project.
it seemed to be fixed after I added the following to my ./amplify/backend/auth/[ResourceName]/parameter.json:
{ ...
      "hostedUIProviderCreds": "[{\"ProviderName\":\"Facebook\",\"client_id\":\"xxxxxxxxxxxxxxx\",\"client_secret\":\"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\"},{\"ProviderName\":\"Google\",\"client_id\":\"xxxxxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com\",\"client_secret\":\"xxxxxxxxxxxxxxxxxxxxxxxx\"}]",
...
}

hope it will be helpful for someone

**Comment by SwaySway** [comment]
Closing this issue as this has been addressed in version 4.23.0.
When running amplify pull the CLI will prompt for these credentials. If you are running amplify headless pull and have social providers enabled the authConfig can be passed in like so.

```
amplify pul --appId ${AppID} --envName ${ENVNAME} --categories ${CATEGORIES}
```
authConfig is defined with categories
```bash
AUTHCONFIG="{\
    \"facebookAppIdUserPool\":\"${AMPLIFY_FACEBOOK_CLIENT_ID}\",\
    \"facebookAppSecretUserPool\":\"${AMPLIFY_FACEBOOK_CLIENT_SECRET}\",\
    \"googleAppIdUserPool\":\"${AMPLIFY_GOOGLE_CLIENT_ID}\",\
    \"googleAppSecretUserPool\":\"${AMPLIFY_GOOGLE_CLIENT_SECRET}\",\
    \"loginwithamazonAppIdUserPool\":\"${AMPLIFY_AMAZON_CLIENT_ID}\",\
    \"loginwithamazonAppSecretUserPool\":\"${AMPLIFY_AMAZON_CLIENT_SECRET}\"\
    }"

CATEGORIES="{\
\"auth\":$AUTHCONFIG\
}"
```

**Comment by juliandm** [comment]
I still had this problem in v4.30. apparently because i added facebook as identity provider and then removed it. Somehow amplify didn't update the cloudformation files as it seems. 
So i solved it by readding the facebook credentials:
`amplify update auth` > `Walkthrough all the auth configurations` > `Do you want to use an OAuth flow? Yes` 
There i readded facebook with app ID and Secret. After that i was able to push.

**Comment by ignaciolarranaga** [comment]
also happening in 4.36

**Comment by amuresia** [comment]
+1, it's happening in 4.36.2

**Comment by toddmcbrearty** [comment]
+1 with version 4.35.0

**Comment by isbkch** [comment]
Same issue still happening in 4.37.1

**Comment by vidhyasagarj** [comment]
+ . Same issue happening in 4.37.1

**Comment by jcbdev** [comment]
@SwaySway this is happening again in the more recent client again.

It seems to copy the values into deployment-secrets.json when you do the first push but then will remove this section from deployment-secrets.json after you do two or three more deployments, I'm not sure 100% what the scenario is for the push to remove it (maybe auth changes?)

I have managed to repro it by doing the following

- Add the hostedUIProviderCreds to team-provider.json
- Do a change and push, it will ask about backing up the credentials etc and select Y
- once the push succeeds do another push but with the `--force` flag
-- Sometimes the credentials will disappear from deployment-secrets.json at the end of the push here (they disappear right at the end of the push)
- If not, force push again.  They will definitely disappear this time

As I said, this recreates it but it is not just force pushing, it's a particular type of change I think.  I suspect an auth change?

**Comment by jcbdev** [comment]
If I was to take a guess at the offending it would be the following line in `push-resources.ts` in `amplify-provider-awscloudformation` package. It seems to call this if there are more than one `authResources` which are resources matching the following filter: `resources.filter(resource => resource.category === 'auth' && resource.service === 'Cognito' && resource.providerPlugin === 'awscloudformation')`

https://github.com/aws-amplify/amplify-cli/blob/1ffdd27b8393f15912f016163de65d1e3821c23a/packages/amplify-provider-awscloudformation/src/push-resources.ts#L288

**Comment by benkirbycodes** [comment]
Same issue happening in 4.38.0

**Comment by hottayusuke** [comment]
I'm 4.40.0

**Comment by sytolk** [comment]
```
amplify --version
4.41.2
```
`UPDATE_FAILED authtagspaces96743d89 AWS::CloudFormation::Stack Tue Jan 26 2021 16:16:33 GMT+0200 (Eastern European Standard Time) Parameters: [hostedUIProviderCreds] do not exist in the template`

**Comment by GeorgeBellTMH** [comment]
I'm guessing the following might fix this: https://github.com/aws-amplify/amplify-cli/pull/6485

**Comment by bernardnongpoh** [comment]
Added the `hostedUIProviderCreds` in the `team-provider-info.json`. It works 

```
{
  "dev": {
    "awscloudformation": {
      ......
    },
    "categories": {
      "auth": {
        "backendName": {
          "hostedUIProviderCreds": "[{\"ProviderName\":\"Facebook\",\"client_id\":\"xxxxxxxxx\",\"client_secret\":\"xxxxxxxxx\"},{\"ProviderName\":\"Google\",\"client_id\":\"xxxxxxxxx\",\"client_secret\":\"xxxxxxxxx\"}]"
        },
        "userPoolGroups": {}
      }
    }
  }
}
```

**Comment by GeorgeBellTMH** [comment]
Sigh....the PR was reverted...

**Comment by ammarkarachi** [comment]
This fix is merged and released in the latest release let me know if you are still facing this issue
