### ISSUE TITLE
amplify pull failed how to trace down the issue?

### ISSUE THREAD

**Issue by dotku** [aws-amplify/amplify-cli#3704]
I'm trying to pull an amplify app from aws, but I got denied.

**Amplify CLI Version** 

amplify -v
4.6.0

**Provide additional details e.g. code snippets**

```
amplify pull

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html

? Do you want to use an AWS profile? Yes
? Please choose the profile you want to use default
? Which app are you working on? d1cjbqa09614a9
? Pick a backend environment: dev
Failed to pull the backend.
AccessDenied: Access Denied
    at Request.extractError (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/services/s3.js:816:35)
    at Request.callListeners (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  message: 'Access Denied',
  code: 'AccessDenied',
  region: null,
  time: 2020-03-19T01:55:05.585Z,
  requestId: 'C866AAF6A8762620',
  extendedRequestId: 'O1xn6OZtrlqxKlns0pN7slK7ostCbgiBeOv3epBoSGVO3whytmhQOBMGVAlbH7qtrr///1Z+M1s=',
  cfId: undefined,
  statusCode: 403,
  retryable: false,
  retryDelay: 37.21115007802855
}
```

**Comment by UnleashedMind** [comment]
You selected the default profile, please check that the default profile's credentials has permission to access the S3 bucket

**Comment by amuresia** [comment]
+1, facing the same issue.
The credentials in the profile map to AdministratorAccess in IAM.

**Comment by UnleashedMind** [comment]
@amuresia 
Your issue is different than @dotku 's issue. 
Your issue is not about permission, but missing artifacts in the deployment bucket. 
Have you recently modified contents in your S3 buckets?

**Comment by kaustavghosh06** [comment]
Closing due to lack of repsonse.
