### ISSUE TITLE
4.17.0 breaking changes

### ISSUE THREAD

**Issue by blazinaj** [aws-amplify/amplify-cli#3752]
v4.17.0 or v4.17.1 seems to include breaking changes. Got a failing build with an un-edited schema

```
                                 # Importing Amplify environment: dev (amplify env import)
2020-03-23T23:50:33.758Z [INFO]: Successfully added environment from your project
2020-03-23T23:50:33.779Z [INFO]: # Initializing existing Amplify environment: dev (amplify init)
2020-03-23T23:50:37.172Z [INFO]: Note: It is recommended to run this command from the root of your app directory
2020-03-23T23:50:41.009Z [WARNING]: - Initializing your environment: dev
2020-03-23T23:50:42.817Z [WARNING]: ✔ Initialized provider successfully.
2020-03-23T23:50:42.979Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
2020-03-23T23:50:42.979Z [WARNING]: ✖ There was an error initializing your environment.
2020-03-23T23:50:42.980Z [INFO]: init failed
2020-03-23T23:50:42.981Z [INFO]: { SchemaValidationError: Schema Errors:
                                 Unknown argument "keyName" on directive "@connection". Did you mean "name"?
                                 GraphQL request (53:56)
                                 52:   riskControlLinks: [RiskControlComplianceControlLink] @connection(name: "ComplianceRiskLink")
                                 53:   recommendations: [ControlRecommendation] @connection(keyName: "byControl", fields: ["id"])
                                 ^
                                 54:   changes: [ControlChange] @connection(keyName: "changesByControl", fields: ["id"])
                                 Unknown argument "fields" on directive "@connection". Did you mean "keyField"?
                                 GraphQL request (53:78)
                                 52:   riskControlLinks: [RiskControlComplianceControlLink] @connection(name: "ComplianceRiskLink")
                                 53:   recommendations: [ControlRecommendation] @connection(keyName: "byControl", fields: ["id"])
                                 ^
                                 54:   changes: [ControlChange] @connection(keyName: "changesByControl", fields: ["id"])
                                 Unknown argument "keyName" on directive "@connection". Did you mean "name"?
                                 GraphQL request (54:40)
                                 53:   recommendations: [ControlRecommendation] @connection(keyName: "byControl", fields: ["id"])
                                 54:   changes: [ControlChange] @connection(keyName: "changesByControl", fields: ["id"])
                                 ^
                                 55: }
                                 Unknown argument "fields" on directive "@connection". Did you mean "keyField"?
                                 GraphQL request (54:69)
                                 53:   recommendations: [ControlRecommendation] @connection(keyName: "byControl", fields: ["id"])
                                 54:   changes: [ControlChange] @connection(keyName: "changesByControl", fields: ["id"])
                                 ^
                                 55: }
                                 Unknown argument "fields" on directive "@connection". Did you mean "keyField"?
                                 GraphQL request (85:32)
                                 84:   controlID: ID!
                                 85:   control: Control @connection(fields: ["controlID"])
                                 ^
                                 86:   resolved: String
                                 Unknown argument "keyName" on directive "@connection". Did you mean "name"?
                                 GraphQL request (165:63)
                                 164:   riskControlOverrides: [RiskControlOverride]
                                 165:   informationAssets: [SystemInformationAssetLink] @connection(keyName: "bySystem", fields: ["id"])
                                 ^
                                 166:   organizationRisks: [OrganizationRiskSystemLink] @connection(keyName: "bySystem", fields: ["id"])
                                 Unknown argument "fields" on directive "@connection". Did you mean "keyField"?
                                 GraphQL request (165:84)
                                 164:   riskControlOverrides: [RiskControlOverride]
                                 165:   informationAssets: [SystemInformationAssetLink] @connection(keyName: "bySystem", fields: ["id"])
                                 ^
                                 166:   organizationRisks: [OrganizationRiskSystemLink] @connection(keyName: "bySystem", fields: ["id"])
                                 Unknown argument "keyName" on directive "@connection". Did you mean "name"?
                                 GraphQL request (166:63)
                                 165:   informationAssets: [SystemInformationAssetLink] @connection(keyName: "bySystem", fields: ["id"])
                                 166:   organizationRisks: [OrganizationRiskSystemLink] @connection(keyName: "bySystem", fields: ["id"])
                                 ^
                                 167:   controlCategories: [SystemControlCategoryLink] @connection(keyName: "systemByControlCategory", fields: ["id"])
                                 Unknown argument "fields" on directive "@connection". Did you mean "keyField"?
                                 GraphQL request (166:84)
                                 165:   informationAssets: [SystemInformationAssetLink] @connection(keyName: "bySystem", fields: ["id"])
                                 166:   organizationRisks: [OrganizationRiskSystemLink] @connection(keyName: "bySystem", fields: ["id"])
                                 ^
                                 167:   controlCategories: [SystemControlCategoryLink] @connection(keyName: "systemByControlCategory", fields: ["id"])
                                 Unknown argument "keyName" on directive "@connection". Did you mean "name"?
                                 GraphQL request (167:62)
                                 166:   organizationRisks: [OrganizationRiskSystemLink] @connection(keyName: "bySystem", fields: ["id"])
                                 167:   controlCategories: [SystemControlCategoryLink] @connection(keyName: "systemByControlCategory", fields: ["id"])
                                 ^
                                 168: }
                                 Unknown argument "fields" on directive "@connection". Did you mean "keyField"?
                                 GraphQL request (167:98)
                                 166:   organizationRisks: [OrganizationRiskSystemLink] @connection(keyName: "bySystem", fields: ["id"])
                                 167:   controlCategories: [SystemControlCategoryLink] @connection(keyName: "systemByControlCategory", fields: ["id"])
                                 ^
                                 168: }
                                 Unknown argument "fields" on directive "@connection". Did you mean "keyField"?
                                 GraphQL request (181:31)
                                 180:   informationAssetID: ID!
                                 181:   system: System! @connection(fields: ["systemID"])
                                 ^
                                 182:   informationAsset: InformationAsset! @connection(fields: ["informationAssetID"])
                                 Unknown argument "fields" on directive "@connection". Did you mean "keyField"?
                                 GraphQL request (182:51)
                                 181:   system: System! @connection(fields: ["systemID"])
                                 182:   informationAsset: InformationAsset! @connection(fields: ["informationAssetID"])
                                 ^
                                 183:   numberOfRecords: Int
                                 Unknown argument "keyName" on directive "@connection". Did you mean "name"?
                                 GraphQL request (194:53)
                                 193:   integrity: RatingScale
                                 194:   systems: [SystemInformationAssetLink] @connection(keyName: "byInformationAsset", fields: ["id"])
                                 ^
                                 195:   ownerGroup: String
                                 Unknown argument "fields" on directive "@connection". Did you mean "keyField"?
                                 GraphQL request (194:84)
                                 193:   integrity: RatingScale
                                 194:   systems: [SystemInformationAssetLink] @connection(keyName: "byInformationAsset", fields: ["id"])
                                 ^
                                 195:   ownerGroup: String
                                 Unknown argument "fields" on directive "@connection". Did you mean "keyField"?
                                 GraphQL request (286:52)
                                 285:   controlCategoryID: ID!
                                 286:   controlCategory: RiskControlCategory @connection(fields: ["controlCategoryID"])
                                 ^
                                 287:   riskControls: [RiskControl] @connection(name: "RiskControls")
                                 Unknown argument "keyName" on directive "@connection". Did you mean "name"?
                                 GraphQL request (288:64)
                                 287:   riskControls: [RiskControl] @connection(name: "RiskControls")
                                 288:   riskControlCategories: [RiskControlCategoryLink] @connection(keyName: "riskByControlCategory", fields: ["id"])
                                 ^
                                 289:   systems: [SystemRiskLink] @connection(name: "RiskSystemLink")
                                 Unknown argument "fields" on directive "@connection". Did you mean "keyField"?
                                 GraphQL request (288:98)
                                 287:   riskControls: [RiskControl] @connection(name: "RiskControls")
                                 288:   riskControlCategories: [RiskControlCategoryLink] @connection(keyName: "riskByControlCategory", fields: ["id"])
                                 ^
                                 289:   systems: [SystemRiskLink] @connection(name: "RiskSystemLink")
                                 Unknown argument "keyName" on directive "@connection". Did you mean "name"?
                                 GraphQL request (334:43)
                                 333:   ownerGroup: String
                                 334:   systems: [SystemThreatLink] @connection(keyName: "byThreat", fields: ["id"])
                                 ^
                                 335:   systemRiskLinks: [SystemRiskThreatLink] @connection(name: "SystemRiskLinkThreat")
                                 Unknown argument "fields" on directive "@connection". Did you mean "keyField"?
                                 GraphQL request (334:64)
                                 333:   ownerGroup: String
                                 334:   systems: [SystemThreatLink] @connection(keyName: "byThreat", fields: ["id"])
                                 ^
                                 335:   systemRiskLinks: [SystemRiskThreatLink] @connection(name: "SystemRiskLinkThreat")
                                 Unknown argument "fields" on directive "@connection". Did you mean "keyField"?
                                 GraphQL request (349:31)
                                 348:   threatID: ID!
                                 349:   system: System! @connection(fields: ["systemID"])
                                 ^
                                 350:   threat: Threat! @connection(fields: ["threatID"])
                                 Unknown argument "fields" on directive "@connection". Did you mean "keyField"?
                                 GraphQL request (350:31)
                                 349:   system: System! @connection(fields: ["systemID"])
                                 350:   threat: Threat! @connection(fields: ["threatID"])
                                 ^
                                 351:   ownerGroup: String
                                 Unknown argument "keyName" on directive "@connection". Did you mean "name"?
                                 GraphQL request (385:42)
                                 384:   description: String
                                 385:   subControls: [RiskControl] @connection(keyName: "byControlCategory", fields: ["id"])
                                 ^
                                 386:   systems: [SystemControlCategoryLink] @connection(keyName: "controlCategoryBySystem", fields: ["id"])
                                 Unknown argument "fields" on directive "@connection". Did you mean "keyField"?
                                 GraphQL request (385:72)
                                 384:   description: String
                                 385:   subControls: [RiskControl] @connection(keyName: "byControlCategory", fields: ["id"])
                                 ^
                                 386:   systems: [SystemControlCategoryLink] @connection(keyName: "controlCategoryBySystem", fields: ["id"])
                                 Unknown argument "keyName" on directive "@connection". Did you mean "name"?
                                 GraphQL request (386:52)
                                 385:   subControls: [RiskControl] @connection(keyName: "byControlCategory", fields: ["id"])
                                 386:   systems: [SystemControlCategoryLink] @connection(keyName: "controlCategoryBySystem", fields: ["id"])
                                 ^
                                 387: #  keyRiskIndicatorID: ID!
                                 Unknown argument "fields" on directive "@connection". Did you mean "keyField"?
                                 GraphQL request (386:88)
                                 385:   subControls: [RiskControl] @connection(keyName: "byControlCategory", fields: ["id"])
                                 386:   systems: [SystemControlCategoryLink] @connection(keyName: "controlCategoryBySystem", fields: ["id"])
                                 ^
                                 387: #  keyRiskIndicatorID: ID!
                                 Unknown argument "keyName" on directive "@connection". Did you mean "name"?
                                 GraphQL request (389:48)
                                 388: #  keyRiskIndicator: Risk @connection(fields: ["keyRiskIndicatorID"])
                                 389:   risks: [RiskControlCategoryLink] @connection(keyName: "controlCategoryByRisk", fields: ["id"])
                                 ^
                                 390: }
                                 Unknown argument "fields" on directive "@connection". Did you mean "keyField"?
                                 GraphQL request (389:82)
                                 388: #  keyRiskIndicator: Risk @connection(fields: ["keyRiskIndicatorID"])
                                 389:   risks: [RiskControlCategoryLink] @connection(keyName: "controlCategoryByRisk", fields: ["id"])
                                 ^
                                 390: }
                                 Unknown argument "fields" on directive "@connection". Did you mean "keyField"?
                                 GraphQL request (405:57)
                                 404:   riskID: ID!
                                 405:   riskControlCategory: RiskControlCategory! @connection(fields: ["riskControlCategoryID"])
                                 ^
                                 406:   risk: Risk! @connection(fields: ["riskID"])
                                 Unknown argument "fields" on directive "@connection". Did you mean "keyField"?
                                 GraphQL request (406:27)
                                 405:   riskControlCategory: RiskControlCategory! @connection(fields: ["riskControlCategoryID"])
                                 406:   risk: Risk! @connection(fields: ["riskID"])
                                 ^
                                 407: }
                                 Unknown argument "fields" on directive "@connection". Did you mean "keyField"?
                                 GraphQL request (422:57)
                                 421:   systemID: ID!
                                 422:   riskControlCategory: RiskControlCategory! @connection(fields: ["riskControlCategoryID"])
                                 ^
                                 423:   system: System! @connection(fields: ["systemID"])
                                 Unknown argument "fields" on directive "@connection". Did you mean "keyField"?
                                 GraphQL request (423:31)
                                 422:   riskControlCategory: RiskControlCategory! @connection(fields: ["riskControlCategoryID"])
                                 423:   system: System! @connection(fields: ["systemID"])
                                 ^
                                 424: }
                                 Unknown argument "fields" on directive "@connection". Did you mean "keyField"?
                                 GraphQL request (450:52)
                                 449:   controlCategoryID: ID!
                                 450:   controlCategory: RiskControlCategory @connection(fields: ["controlCategoryID"])
                                 ^
                                 451: }
                                 Unknown argument "keyName" on directive "@connection". Did you mean "name"?
                                 GraphQL request (535:53)
                                 534:   ownerGroup: String
                                 535:   systems: [OrganizationRiskSystemLink] @connection(keyName: "byOrganizationRisk", fields: ["id"])
                                 ^
                                 536: #  risks: [RiskOrganizationRiskLink] @connection(keyName: "risksByOrganizationRisk", fields: ["id"])
                                 Unknown argument "fields" on directive "@connection". Did you mean "keyField"?
                                 GraphQL request (535:84)
                                 534:   ownerGroup: String
                                 535:   systems: [OrganizationRiskSystemLink] @connection(keyName: "byOrganizationRisk", fields: ["id"])
                                 ^
                                 536: #  risks: [RiskOrganizationRiskLink] @connection(keyName: "risksByOrganizationRisk", fields: ["id"])
                                 Unknown argument "fields" on directive "@connection". Did you mean "keyField"?
                                 GraphQL request (547:51)
                                 546:   systemID: ID!
                                 547:   organizationRisk: OrganizationRisk! @connection(fields: ["organizationRiskID"])
                                 ^
                                 548:   system: System! @connection(fields: ["systemID"])
                                 Unknown argument "fields" on directive "@connection". Did you mean "keyField"?
                                 GraphQL request (548:31)
                                 547:   organizationRisk: OrganizationRisk! @connection(fields: ["organizationRiskID"])
                                 548:   system: System! @connection(fields: ["systemID"])
                                 ^
                                 549: }
                                 Expected type AuthStrategy, found public.
                                 GraphQL request (668:12)
                                 667:   { allow: groups, groups: ["Admin"] },
                                 668:   { allow: public, provider: iam }
                                 ^
                                 669: ]){
                                 Field "provider" is not defined by type AuthRule.
                                 GraphQL request (668:20)
                                 667:   { allow: groups, groups: ["Admin"] },
                                 668:   { allow: public, provider: iam }
                                 ^
                                 669: ]){
                                 Unknown argument "keyName" on directive "@connection". Did you mean "name"?
                                 GraphQL request (677:53)
                                 676:   targets: [Target] @connection(name: "AssessmentTargets")
                                 677:   findingLinks: [AssessmentFindingLink] @connection(keyName: "byAssessment", fields: ["id"])
                                 ^
                                 678:   pointOfContact: PointOfContact @connection(name: "AssessmentPointOfContact")
                                 Unknown argument "fields" on directive "@connection". Did you mean "keyField"?
                                 GraphQL request (677:78)
                                 676:   targets: [Target] @connection(name: "AssessmentTargets")
                                 677:   findingLinks: [AssessmentFindingLink] @connection(keyName: "byAssessment", fields: ["id"])
                                 ^
                                 678:   pointOfContact: PointOfContact @connection(name: "AssessmentPointOfContact")
                                 Expected type AuthStrategy, found public.
                                 GraphQL request (699:12)
                                 698:   { allow: groups, groups: ["Admin"] },
                                 699:   { allow: public, provider: iam }
                                 ^
                                 700: ]){
                                 Field "provider" is not defined by type AuthRule.
                                 GraphQL request (699:20)
                                 698:   { allow: groups, groups: ["Admin"] },
                                 699:   { allow: public, provider: iam }
                                 ^
                                 700: ]){
                                 Unknown argument "fields" on directive "@connection". Did you mean "keyField"?
                                 GraphQL request (704:39)
                                 703:   findingID: ID!
                                 704:   assessment: Assessment! @connection(fields: ["assessmentID"])
                                 ^
                                 705:   finding: Finding! @connection(fields: ["findingID"])
                                 Unknown argument "fields" on directive "@connection". Did you mean "keyField"?
                                 GraphQL request (705:33)
                                 704:   assessment: Assessment! @connection(fields: ["assessmentID"])
                                 705:   finding: Finding! @connection(fields: ["findingID"])
                                 ^
                                 706:   ownerGroup: String
                                 Expected type AuthStrategy, found public.
                                 GraphQL request (712:12)
                                 711:   { allow: groups, groups: ["Admin"] },
                                 712:   { allow: public, provider: iam }
                                 ^
                                 713: ]){
                                 Field "provider" is not defined by type AuthRule.
                                 GraphQL request (712:20)
                                 711:   { allow: groups, groups: ["Admin"] },
                                 712:   { allow: public, provider: iam }
                                 ^
                                 713: ]){
                                 Expected type AuthStrategy, found public.
                                 GraphQL request (747:12)
                                 746:   { allow: groups, groups: ["Admin"] },
                                 747:   { allow: public, provider: iam }
                                 ^
                                 748: ]){
                                 Field "provider" is not defined by type AuthRule.
                                 GraphQL request (747:20)
                                 746:   { allow: groups, groups: ["Admin"] },
                                 747:   { allow: public, provider: iam }
                                 ^
                                 748: ]){
                                 Unknown argument "keyName" on directive "@connection". Did you mean "name"?
                                 GraphQL request (764:56)
                                 763:   findingTargetId: String
                                 764:   assessmentLinks: [AssessmentFindingLink] @connection(keyName: "byFinding", fields: ["id"])
                                 ^
                                 765:   findingAssessmentId: String
                                 Unknown argument "fields" on directive "@connection". Did you mean "keyField"?
                                 GraphQL request (764:78)
                                 763:   findingTargetId: String
                                 764:   assessmentLinks: [AssessmentFindingLink] @connection(keyName: "byFinding", fields: ["id"])
                                 ^
                                 765:   findingAssessmentId: String
                                 Expected type AuthStrategy, found public.
                                 GraphQL request (773:12)
                                 772:   { allow: groups, groups: ["Admin"] },
                                 773:   { allow: public, provider: iam }
                                 ^
                                 774: ]){
                                 Field "provider" is not defined by type AuthRule.
                                 GraphQL request (773:20)
                                 772:   { allow: groups, groups: ["Admin"] },
                                 773:   { allow: public, provider: iam }
                                 ^
                                 774: ]){
                                 Unknown argument "keyName" on directive "@connection". Did you mean "name"?
                                 GraphQL request (801:42)
                                 800:   accountType: String
                                 801:   roleLinks:  [UserRoleLink] @connection(keyName: "byUser", fields: ["id"])
                                 ^
                                 802: }
                                 Unknown argument "fields" on directive "@connection". Did you mean "keyField"?
                                 GraphQL request (801:61)
                                 800:   accountType: String
                                 801:   roleLinks:  [UserRoleLink] @connection(keyName: "byUser", fields: ["id"])
                                 ^
                                 802: }
                                 Unknown argument "fields" on directive "@connection". Did you mean "keyField"?
                                 GraphQL request (815:27)
                                 814:   roleID: ID!
                                 815:   user: User! @connection(fields: ["userID"])
                                 ^
                                 816:   role: Role! @connection(fields: ["roleID"])
                                 Unknown argument "fields" on directive "@connection". Did you mean "keyField"?
                                 GraphQL request (816:27)
                                 815:   user: User! @connection(fields: ["userID"])
                                 816:   role: Role! @connection(fields: ["roleID"])
                                 ^
                                 817:   ownerGroup: String
                                 Unknown argument "keyName" on directive "@connection". Did you mean "name"?
                                 GraphQL request (845:41)
                                 844:   name: String!
                                 845:   userLinks: [UserRoleLink] @connection(keyName: "byRole", fields: ["id"])
                                 ^
                                 846:   roleConfig: AWSJSON
                                 Unknown argument "fields" on directive "@connection". Did you mean "keyField"?
                                 GraphQL request (845:60)
                                 844:   name: String!
                                 845:   userLinks: [UserRoleLink] @connection(keyName: "byRole", fields: ["id"])
                                 ^
                                 846:   roleConfig: AWSJSON
                                 Unknown argument "keyName" on directive "@connection". Did you mean "name"?
                                 GraphQL request (992:37)
                                 991:   ownerGroup: String
                                 992:   reviewers: [Reviewer] @connection(keyName: "byPolicyVersion", fields: ["id"])
                                 ^
                                 993:   policy: Policy @connection(name: "PolicyPolicyVersions")
                                 Unknown argument "fields" on directive "@connection". Did you mean "keyField"?
                                 GraphQL request (992:65)
                                 991:   ownerGroup: String
                                 992:   reviewers: [Reviewer] @connection(keyName: "byPolicyVersion", fields: ["id"])
                                 ^
                                 993:   policy: Policy @connection(name: "PolicyPolicyVersions")
                                 Unknown argument "fields" on directive "@connection". Did you mean "keyField"?
                                 GraphQL request (1010:44)
                                 1009:   policyVersionID: ID!
                                 1010:   policyVersion: PolicyVersion @connection(fields: ["policyVersionID"])
                                 ^
                                 1011: }
                                 at GraphQLTransform.transform (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/GraphQLTransform.js:191:19)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/amplifyUtils.js:100:49
                                 at step (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/amplifyUtils.js:43:23)
                                 at Object.next (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/amplifyUtils.js:24:53)
                                 at fulfilled (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/amplifyUtils.js:15:58) name: 'SchemaValidationError' }
2020-03-23T23:50:43.031Z [ERROR]: !!! Build failed
2020-03-23T23:50:43.031Z [ERROR]: !!! Non-Zero Exit Code detected
2020-03-23T23:50:43.031Z [INFO]: # Starting environment caching...
2020-03-23T23:50:43.032Z [INFO]: # Uploading environment cache artifact...
2020-03-23T23:50:43.127Z [INFO]: # Environment caching completed
Terminating logging...
```

Reverting back to 4.16.1 allows the build to success.

**Comment by attilah** [comment]
@blazinaj this should not be an issue, could you please share your schema with us? if you can't post it here, please send it to amplify-cli@amazon.com.

**Comment by kevstafford82** [comment]
> @blazinaj this should not be an issue, could you please share your schema with us? if you can't post it here, please send it to [amplify-cli@amazon.com](mailto:amplify-cli@amazon.com).

New to amplify but believe i am getting the same issue (though tried reverting version and still same message) - let me know if you dont get what you need to reproduce, I can share my schema.

Thanks

**Comment by thejool** [comment]
I have the same issue. Adding example type and error, but it's breaking for all types in the schema.

**Schema (one of the types)**

```
type Restaurant
  @model(subscriptions: null)
  @auth(
    rules: [
      { allow: owner }
      { allow: groups, groups: ["Admin"] }
      { allow: public, operations: [read] }
    ]
  ) {
  id: ID!
  createdAt: AWSDateTime
  updatedAt: AWSDateTime

  name: String!
  description: String
  cuisine: String
  rating: Float
  openingHours: AWSJSON
  priceRange: String
  image: String
  logo: String
  active: Boolean
  avgPickupTime: String
  city: City @connection(name: "RestaurantCity")
  location: AWSJSON
  carts: [Cart] @connection(name: "RestaurantCarts")
  orders: [Order] @connection(name: "RestaurantOrders")
  categories: [Category] @connection(name: "RestaurantCategory")
  items: [Item] @connection(keyName: "byRestaurant", keyField: ["id"])
}
```

**Error:**
```
{ SchemaValidationError: Schema Errors:
Expected type AuthStrategy, found public.
GraphQL request (35:16)
34:       { allow: groups, groups: ["Admin"] }
35:       { allow: public, operations: [read] }
^
36:     ]
Unknown argument "keyName" on directive "@connection". Did you mean "name"?
GraphQL request (57:29)
56:   categories: [Category] @connection(name: "RestaurantCategory")
57:   items: [Item] @connection(keyName: "byRestaurant", fields: ["id"])
^
58:   # items: [Item] @connection(name: "RestaurantItems")
Unknown argument "fields" on directive "@connection". Did you mean "keyField"?
GraphQL request (57:54)
56:   categories: [Category] @connection(name: "RestaurantCategory")
57:   items: [Item] @connection(keyName: "byRestaurant", fields: ["id"])
^
58:   # items: [Item] @connection(name: "RestaurantItems")
```

**Comment by kevstafford82** [comment]
Try changing the @connection in city, carts, orders and categories to be keyName rather than name.

**Comment by kaustavghosh06** [comment]
@blazinaj & @thejool Were you'll able to get unblocked based on @kevstafford82's recommendation?

**Comment by blazinaj** [comment]
It started to work again after I updated the CLI at a certain point. I don't know what version it was though. Seems to have been isolated to 4.17.x

**Comment by mansiva** [comment]
For anyone else running into this, make sure you have this option set in your build image settings
![image](https://user-images.githubusercontent.com/1873405/95118878-07b7e080-0719-11eb-9df1-18a5ba28fbf9.png)
