### ISSUE TITLE
ENOENT error on "Email Verification Link with Redirect" flow and subsequent push failure 

### ISSUE THREAD

**Issue by rdkelley** [aws-amplify/amplify-cli#3775]
**Describe the bug**
When attempting to add auth with the `Email Verification Link with Redirect` option selected, an ENOENT error is thrown after the prompt `Do you want to edit your verification-link function now?` The file in question is `CustomMessage.json.ejs` -- this file does exist on my system. The full error is printed below.

After, if I attempt a `amplify push` I get an error that says `Only one CloudFormation template is allowed in the resource directory`. The full error for this is also below.

**Amplify CLI Version**
4.17.1

**To Reproduce**
```
amplify init
amplify add auth
```
- Select Yes to `Do you want to configure advanced settings? ` 
- Check `Email Verification Link with Redirect`
- Answer the prompts -- the error is thrown when the `Do you want to edit your verification-link function now?` prompt appears.

After, `amplify push` fails with the error below.

**Expected behavior**
Complete the prompts without error.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node Version: 12.16.0

**Additional context**
```
 Do you want to use the default authentication and security configuration? Default configuration
 Warning: you will not be able to edit these selections.     
 How do you want users to be able to sign in? Email
 Do you want to configure advanced settings? Yes, I want to make some additional changes.
 Warning: you will not be able to edit these selections.
 What attributes are required for signing up? Email, Family Name (This attribute is not supported by Login With Amazon.), Given 
Name (This attribute is not supported by Login With Amazon.)
 Do you want to enable any of the following capabilities? Email Verification Link with Redirect
? Enter the URL that your users will be redirected to upon account confirmation: http://localhost:3000/
? Enter the subject for your custom account confirmation email: Welcome
? Enter the body text for your custom account confirmation email (this will appear before the link URL): 
Succesfully added the Lambda function locally
? Do you want to edit your verification-link function now? (Y/n) (node:5408) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '/C:\Users\Ryan\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-category-auth\provider-utils\awscloudformation\triggers\CustomMessage\cloudformation-templates\CustomMessage.json.ejs'
    at Object.statSync (fs.js:932:3)
    at Object.statSync (C:\Users\Ryan\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\graceful-fs\polyfills.js:308:16)
    at Object.isFile (C:\Users\Ryan\AppData\Roaming\npm\node_modules\@aws-amplify\cli\lib\context-extensions.js:136:43)
    at Object.generate (C:\Users\Ryan\AppData\Roaming\npm\node_modules\@aws-amplify\cli\lib\context-extensions.js:279:36)       
    at AmplifyToolkit.copyBatch [as _copyBatch] (C:\Users\Ryan\AppData\Roaming\npm\node_modules\@aws-amplify\cli\lib\extensions\amplify-helpers\copy-batch.js:17:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:5408) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5408) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

```
$ amplify push
√ Successfully pulled backend environment dev from the cloud.

Current Environment: dev

| Category | Resource name             | Operation | Provider plugin   |
| -------- | ------------------------- | --------- | ----------------- |
| Function | htdl2eeb32d0CustomMessage | Create    | awscloudformation |
| Auth     | htdl2eeb32d0              | Create    | awscloudformation |
? Are you sure you want to continue? Yes
Only one CloudFormation template is allowed in the resource directory
C:\projects\htdl\amplify\backend\function\htdl2eeb32d0CustomMessage
× An error occurred when pushing the resources to the cloud

Only one CloudFormation template is allowed in the resource directory
An error occured during the push operation: Only one CloudFormation template is allowed in the resource directory
```

**Comment by ammarkarachi** [comment]
@rdkelley We have deployed a new release (4.17.2) possibly fixing this error let me know if this fixes the issue.

**Comment by rdkelley** [comment]
Looks like it works! Thank you.

**Comment by dorontal** [comment]
Hello, I am not sure if we need to reopen this issue, but I have had an almost identical issue with version 4.18.0.  Here is a transcript:
```
> amplify add auth
Using service: Cognito, provided by: awscloudformation
 
 The current configured provider is Amazon Cognito. 
 
 Do you want to use the default authentication and security configuration? Default configuration
 Warning: you will not be able to edit these selections. 
 How do you want users to be able to sign in? Email
 Do you want to configure advanced settings? Yes, I want to make some additional changes.
 Warning: you will not be able to edit these selections. 
 What attributes are required for signing up? Email
 Do you want to enable any of the following capabilities? Email Verification Link with Redirect
? Enter the URL that your users will be redirected to upon account confirmation: https://localhost:4200/app/registration-redirect
? Enter the subject for your custom account confirmation email: Welcome to the Tracktunes music collaboration app!
? Enter the body text for your custom account confirmation email (this will appear before the link URL): Please click on the link below to verify (and complete) your registration:
Succesfully added the Lambda function locally
? Do you want to edit your verification-link function now? No
Error: ENOENT: no such file or directory, open '/home/dtal/repos/explore.tracktunes.org/amplify/backend/auth/exploretracktunesorg84e48a86/parameters.json'
    at Object.openSync (fs.js:454:3)
    at Proxy.writeFileSync (fs.js:1247:35)
    at Object.saveResourceParameters (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/resourceParams.js:25:6)
    at saveResourceParameters (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/provider-utils/awscloudformation/index.js:110:12)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/provider-utils/awscloudformation/index.js:146:7
    at processTicksAndRejections (internal/process/task_queues.js:88:5)
    at Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/index.js:305:3)
    at executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:158:7)
    at Object.executeCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:24:5)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/src/index.ts:47:5)
There was an error adding the auth resource
> amplify --version
4.18.0
```
