### ISSUE TITLE
InvalidParameterException: Domain cannot contain reserved word: cognito

### ISSUE THREAD

**Issue by andreialecu** [aws-amplify/amplify-cli#3854]
We were testing some changes related to `cognito` and created a new amplify environment called `newcognito`. 

Upon pushing changes related to auth and facebook federation, we noticed that pushes started failing. I had to dig through the CloudWatch logs to figure it out and noticed this error there:

```
2020-04-03T06:43:17.294Z	aecce830-794e-472e-8ad6-5b52de0ce89d	INFO	{ InvalidParameterException: Domain cannot contain reserved word: cognito
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
  message: 'Domain cannot contain reserved word: cognito',
  code: 'InvalidParameterException',
  time: 2020-04-03T06:43:17.254Z,
  requestId: '6f63c763-ef54-47fb-a527-540f861c2d60',
  statusCode: 400,
  retryable: false,
  retryDelay: 23.270292044054486 }
```

I realize this is a very niche problem but perhaps environment creation could check for reserved words and fail earlier.

**Comment by andreialecu** [comment]
Related: 
https://github.com/aws-amplify/amplify-cli/pull/1544 
https://github.com/aws-amplify/amplify-cli/issues/1513#issuecomment-595632762

**Comment by andreialecu** [comment]
Also a note here, I don't think the fix in https://github.com/aws-amplify/amplify-cli/pull/1544 is complete for this problem.

We do not use the hosted UI at all, this is a React Native app. The name `cognito` is not mentioned anywhere but in the amplify environment name. So the validation in the PR above doesn't check for this.

**Comment by brene** [comment]
We're going to introduce a better sanity check here, so customers won't run into this at a late stage.

**Comment by jhockett** [comment]
Hi @andreialecu does your project name have a '-' in it?

**Comment by kaustavghosh06** [comment]
Closing due to lack of response.

**Comment by andreialecu** [comment]
> Hi @andreialecu does your project name have a '-' in it?

There was no `-` in the project name, no.
