### ISSUE TITLE
Delete env is not work with message "Stack with id {stack_id} does not exist"

### ISSUE THREAD

**Issue by Sangkwun** [aws-amplify/amplify-cli#3876]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
I'm trying to delete environment of backend. but it doesn't work.

```
amplify env remove {env_name}
>> Stack with id {stack_id} does not exist
```
**Amplify CLI Version**
```
amplify -v
>> 4.17.2
```

**To Reproduce**
```
amplify env list
>>
| Environments |
| ------------ |
| *prod        |
| dev          |
| work         |
| deploy       |

amplify env checkout work
>>
✔ Initialized provider successfully.
Initialized your environment successfully.

amplify env remove prod
>>
? Are you sure you want to continue? (This would delete 'prod' environment of the project from the cloud) Yes
⠋ Deleting resources from the cloud. This may take a few minutes...
Deleting env:prod
⠙ Deleting resources from the cloud. This may take a few minutes...
Error in deleting env:prod
Stack with id amplify-lomin-api-platform-prod-71917 does not exist
✖ remove env failed: Stack with id amplify-lomin-api-platform-prod-71917 does not exist
Stack with id amplify-lomin-api-platform-prod-71917 does not exist
ValidationError: Stack with id amplify-lomin-api-platform-prod-71917 does not exist
    at Request.extractError (/home/sangkwun/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/home/sangkwun/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/sangkwun/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/sangkwun/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/sangkwun/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/sangkwun/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/sangkwun/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/sangkwun/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/sangkwun/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/sangkwun/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)

```

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Node Version: v12.16.1

**Comment by ammarkarachi** [comment]
@Sangkwun can you login to your console and check if the console exists?

**Comment by ammarkarachi** [comment]
Also a new version has been release (4.18.0) that ignores deleted stacks. Give that a try and let me know

**Comment by Sangkwun** [comment]
@ammarkarachi  Thank you for comment.
It worked with upgraded cli version.
But some resource like DynamoDB table(for appsync) or s3 bucket is still remain. 
Do I have to delete it manually?

```
# Update amplify cli to 4.18.0
$ npm i -g @aws-amplify/cli@latest

# check env list
$ amplify env list
| Environments |
| ------------ |
| prod         |
| *work        |

# remove env
$ amplify env remove prod
? Are you sure you want to continue? (This would delete 'prod' environment of the project from the cloud) Yes
⠋ Deleting resources from the cloud. This may take a few minutes...
Deleting env:prod
⠙ Deleting resources from the cloud. This may take a few minutes...Stack has already been deleted or does not exist
✔ Successfully removed environment from the cloud
Successfully removed environment from your project locally
```

**Comment by devth** [comment]
I'm on `4.18.0`. I tried deleting my env via amplify, but it kept erring with

```
Deleting resources from the cloud. This may take a few minutes...(node:49730) Un
handledPromiseRejectionWarning: AccessDenied: Access Denied
```

even though my `aws` cli was working and I created the env with `amplify` in the first place, just a day before.

So then I deleted it in the web console. Now I'm stuck in amplify purgatory.

```
± amplify env remove prod                                              <aws:prod>
? Are you sure you want to continue? (This would delete 'prod' environment of the
project from the cloud) Yes
⠋ Deleting resources from the cloud. This may take a few minutes...
Deleting env:prod
⠸ Deleting resources from the cloud. This may take a few minutes...Stack has alrea
dy been deleted or does not exist
```

**Comment by Sangkwun** [comment]
@devth 
Why don't you update aws-cli?
I think latest version of aws-cli can handle that exception.
