### ISSUE TITLE
Syntax Error when generating models

### ISSUE THREAD

**Issue by GeorgeBellTMH** [aws-amplify/amplify-cli#3887]
When running amplify codegen models I get the following (amplify codegen works fine)...note 'repeatable' does not occur in my schema, so not sure where this is coming from..
--

GraphQL schema compiled successfully.

Edit your schema at /Users/georgebell/Code/mobile/amplify/backend/api/jcmobile/schema.graphql or place .graphql files in a directory at /Users/georgebell/Code/mobile/amplify/backend/api/jcmobile/schema
Syntax Error: Expected "on", found Name "repeatable"
GraphQLError: Syntax Error: Expected "on", found Name "repeatable"
    at syntaxError (/Users/georgebell/Code/mobile/node_modules/graphql/error/syntaxError.js:24:10)
    at expectKeyword (/Users/georgebell/Code/mobile/node_modules/graphql/language/parser.js:1480:32)
    at parseDirectiveDefinition (/Users/georgebell/Code/mobile/node_modules/graphql/language/parser.js:1330:3)
    at parseTypeSystemDefinition (/Users/georgebell/Code/mobile/node_modules/graphql/language/parser.js:739:16)
    at parseDefinition (/Users/georgebell/Code/mobile/node_modules/graphql/language/parser.js:142:16)
    at many (/Users/georgebell/Code/mobile/node_modules/graphql/language/parser.js:1523:16)
    at parseDocument (/Users/georgebell/Code/mobile/node_modules/graphql/language/parser.js:113:18)
    at Object.parse (/Users/georgebell/Code/mobile/node_modules/graphql/language/parser.js:48:10)
    at /Users/georgebell/Code/mobile/node_modules/@graphql-codegen/core/node_modules/@graphql-toolkit/schema-merging/src/typedefs-mergers/merge-typedefs.ts:199:16
    at Array.map (<anonymous>)

**Comment by sammartinez** [comment]
This seems to be related to Amplify CLI. Transferring issue to them

**Comment by regenrek** [comment]
Can you post the schema.graphql?

**Comment by GeorgeBellTMH** [comment]
[schema.graphql.zip](https://github.com/aws-amplify/amplify-cli/files/4446399/schema.graphql.zip)

**Comment by GeorgeBellTMH** [comment]
this works with amplify-codegen@2.15.1 does not work with @2.15.5

**Comment by nikhname** [comment]
@GeorgeBellTMH just to clarify, you came across this error when running ```npx amplify-app```?

**Comment by nikhname** [comment]
Please comment if you are still facing this
