### ISSUE TITLE
amplify pull TypeError: Cannot redefine property: mfa

### ISSUE THREAD

**Issue by brothatru** [aws-amplify/amplify-cli#3946]
**Describe the bug**
```
╰─ amplify pull                                                                                                                            ─╯

Pre-pull status:

Current Environment: dev

| Category | Resource name  | Operation | Provider plugin   |
| -------- | -------------- | --------- | ----------------- |
| Auth     | userPoolGroups | Create    | awscloudformation |
| Auth     | AgentPortal    | Create    | awscloudformation |

Local changes detected.
Pulling changes from the cloud will override your local changes.
? Are you sure you would like to continue? Yes
✖ There was an error pulling the backend environment dev.
Cannot redefine property: mfa
TypeError: Cannot redefine property: mfa
    at Function.defineProperty (<anonymous>)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/shared-ini/ini-loader.js:11:14
    at Array.forEach (<anonymous>)
    at IniLoader.parseFile (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/shared-ini/ini-loader.js:8:26)
    at IniLoader.loadFrom (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/shared-ini/ini-loader.js:56:30)
    at Config.region (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/node_loader.js:100:36)
    at Config.set (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js:507:39)
    at Config.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js:342:12)
    at Config.each (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/util.js:507:32)
    at new Config (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js:341:19)
```

**Amplify CLI Version**
4.18.0

**To Reproduce**
amplify pull or amplify push

**Expected behavior**
Pull latest changes into local environment

**Desktop (please complete the following information):**
 - OS: MacOS Catalina (10.15.3)
 - Node Version: v12.13.1

**Additional context**
I was trying to add a new lambda function that will add a user to an existing group.

**Comment by brothatru** [comment]
I removed the following profile from my **~./aws/config** file and things appear to be working again.

```
[profile mfa]
region = us-east-1
```

**Comment by UnleashedMind** [comment]
Thanks, will mark this as an enhancement.

**Comment by brothatru** [comment]
I have an existing **mfa** profile that i use for running other **aws-cli** commands. 

There's a chance this could have caused conflicts when amplify tries to create a new "mfa" profile.

Maybe try prefixing with "amplify-mfa" to avoid potential profile name clashes.

**Comment by UnleashedMind** [comment]
What's the latest on this issue? are you still blocked?

**Comment by nikhname** [comment]
Closing this due to lack of activity. Please comment if there are further issues.
