### ISSUE TITLE
Specifying primary key via @key causes id field to be required in create input

### ISSUE THREAD

**Issue by kldeb** [aws-amplify/amplify-cli#3954]
**Describe the bug**
Specifying the field name using `@key` causes it to be required in create input. see steps below.

**Amplify CLI Version**
4.18.0

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable
1. create pk with @key, don't call the field id.
2. run `amplify api gql-compile`
3. see the pk is required in the input and the mutation create resolver doesn't respect the name. 

**Expected behavior**
Expect the gql compile to recognize the key field name and treat it like an id field. 

**Additional context**
Using more verbose field naming convention so Customer type has customerId field for pk.

**Comment by edwardfoyle** [comment]
Hi @kldeb could you elaborate on the behavior you expect here?

The following schema will compile and only require you to include "name" when creating a Todo:
```graphql
type Todo @model @key(fields: ["name"]) {
  id: ID
  name: String!
  description: String
}
```

Are you saying that in the above schema, if name was optional, a random UUID should be used if a name is not specified when creating the entity?

**Comment by kldeb** [comment]
@edwardfoyle 

I expect that if i do this: 

```gql
type Todo @model @key(fields: ["todoId"]) {
  todoId: ID!
  name: String!
  description: String
}

```

I expect: 

```gql
input CreateTodoInput {
  todoId: ID
  name: String!
  description: String
}
```

and the resolver to manage the todoId when not included in the input instead of what I get now: 

```gql
input CreateTodoInput {
  todoId: ID! 
  name: String!
  description: String
}
```

**Comment by marlonmarcello** [comment]
I stumbled upon this issue with the following schema:
```gql
type Project
  @model
  @key(fields: ["id", "name"]) {
  id: ID!
  name: String!
  url: String
}
```

**Comment by marlonmarcello** [comment]
The error when trying to create a new project
```sh
Error while executing Local DynamoDB
{
    "version": "2017-02-28",
    "operation": "PutItem",
    "key": {
        "id": {
            "S": "42e4138a-4020-4e30-9c34-67496ca99240"
        },
        "name": {
            "S": "Another proj"
        }
    },
    "attributeValues": {
        "name": {
            "S": "Another proj"
        },
        "categoryID": {
            "S": "0b4e95a2-91bf-47d0-b8f6-7af976c5c4d6"
        },
        "clientID": {
            "S": "0abd7e23-bb3d-4be9-8b33-58e6eebe3c4e"
        },
        "id": {
            "S": "42e4138a-4020-4e30-9c34-67496ca99240"
        },
        "createdAt": {
            "S": "2020-06-08T22:24:05.801Z"
        },
        "updatedAt": {
            "S": "2020-06-08T22:24:05.801Z"
        },
        "__typename": {
            "S": "Project"
        }
    },
    "condition": {
        "expression": "attribute_not_exists(#id)",
        "expressionNames": {
            "#id": "id"
        }
    }
}
ValidationException: The number of conditions on the keys is invalid
    at Request.extractError (/Users/marlonmarcello/npm/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.callListeners (/Users/marlonmarcello/npm/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/marlonmarcello/npm/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/marlonmarcello/npm/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/marlonmarcello/npm/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/marlonmarcello/npm/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/marlonmarcello/npm/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/marlonmarcello/npm/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/marlonmarcello/npm/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/marlonmarcello/npm/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  message: 'The number of conditions on the keys is invalid',
  code: 'ValidationException',
  time: 2020-06-08T22:24:05.815Z,
  requestId: '5ea9472e-a8cf-4bae-8c71-f6825b198826',
  statusCode: 400,
  retryable: false,
  retryDelay: 45.820020689568445
}
```

**Comment by MontoyaAndres** [comment]
any news about this?

**Comment by mamluka** [comment]
I have the same issue, any fixes?

**Comment by strange1120** [comment]
I am experiencing this as well.

**Comment by nat-n** [comment]
Encountered something similar.

I first tried creating a join table similar to:

```graphql
type ArticleTagJoin
  @model
  @key(fields: ["articleID", "tagID"]) {
  articleID: ID!
  tagID: ID!
}
```

But it seemed that the resulting DynamoDB table had the correct cols but the generated createArticleTagJoin resolver still assumed the existence of an ID field and so always failed.

So I added an ID column, but then started getting the same error as OP. `ValidationException: The number of conditions on the keys is invalid`

**Comment by alanionita** [comment]
Similar issues for me, but I'm tempted to say it's really a bug not an improvement

When I write the following schema

```graphql

type Train @model 
  @key(fields: ['yardKey", "zoneKey"])
  @key(name: "trainYardAndZone-index", fields:["yardZoneKey"], queryField: "trainsByYardZoneKey")
{
  id: ID!
  yardKey: String!
  zoneKey: String!
  yardZoneKey: String
}

```

Seems like the ID should auto-generate (which it does just fine), but the resolver expects id to be passed to the query.

If I pass an id to the query it gets ignore - maybe do to with the PK / SK setup.

```graphql
mutation MyMutation {
  createTrain(input: {yardKey: "East", zoneKey: "B3"}){
    yardKey
    zoneKey
  }
}
```

Returns 

```bash
Error while executing Local DynamoDB
{
    "version": "2018-05-29",
    "operation": "PutItem",
    "key": {
        "yardKey": {
            "S": "East"
        },
        "zoneKey": {
            "S": "B3"
        }
    },
    "attributeValues": {
        "yardKey": {
            "S": "East"
        },
        "zoneKey": {
            "S": "B3"
        },
        "id": {
            "S": "ffc3ea69-226e-4da3-86ef-0680e6738ba9"
        },
        "createdAt": {
            "S": "2021-05-07T08:37:39.545Z"
        },
        "updatedAt": {
            "S": "2021-05-07T08:37:39.545Z"
        },
        "__typename": {
            "S": "Train"
        }
    },
    "condition": {
        "expression": "attribute_not_exists(#id)",
        "expressionNames": {
            "#id": "id"
        }
    }
}
ConditionalCheckFailedException: The conditional request failed
```

Surely the query should not expect the id in this instance?

**Comment by bmilesp** [comment]
@edwardfoyle I agree with @alanionita that this should be a bug and not an enhancement as I share the same issue as @nat-n. 

Reason being, there currently is no workaround so I cannot add data locally for testing, so i'm stuck with cloud testing only which is hardly ideal. 

Could you please change this to a bug?

Thanks in advance.

**Comment by josefaidt** [comment]
Note: this is still occurring with the [`@primaryKey` directive](https://docs.amplify.aws/cli/graphql/data-modeling/#configure-a-primary-key)! Using the following schema:

```graphql
type Todo @model {
  todoId: ID! @primaryKey
  name: String!
  description: String
}
```

Upon running `amplify api gql-compile` we see the custom primary key field is still required as you were previously seeing with `@key`

```graphql
input CreateTodoInput {
  todoId: ID!
  name: String!
  description: String
}
```

However if we were to not specify a custom field as the primary key, `id` is not considered required in the create input

```graphql
type Todo @model {
  id: ID!
  name: String!
  description: String
}
```

```graphql
input CreateTodoInput {
  id: ID
  name: String!
  description: String
}
```

This feature request still stands for v2
