### ISSUE TITLE
amplify init fails to ask for type of app

### ISSUE THREAD

**Issue by okigan** [aws-amplify/amplify-cli#3996]
**Describe the bug**
When running locally amplify init in a fresh Create React App project the cli fails on the Choose the type of app that you're building-question. 

**Amplify CLI Version**
4.18.0

**To Reproduce**
`npx amplify init`

**Expected behavior**
Shall be able to select app type

**Screenshots**
`
? Choose the type of app that you're building (Use arrow keys)
(node:70100) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'value' of undefined
    at ListPrompt.getCurrentValue (/Users/.../node_modules/inquirer/lib/prompts/list.js:121:53)
    at MapSubscriber._next (/Users/.../node_modules/rxjs/internal/operators/map.js:49:35)
    at MapSubscriber.Subscriber.next (/Users/.../node_modules/rxjs/internal/Subscriber.js:66:18)
    at TakeSubscriber._next (/Users/.../node_modules/rxjs/internal/operators/take.js:54:30)
    at TakeSubscriber.Subscriber.next (/Users/.../node_modules/rxjs/internal/Subscriber.js:66:18)
    at Interface.handler (/Users/.../node_modules/rxjs/internal/observable/fromEvent.js:22:28)
    at Interface.emit (events.js:327:22)
    at Interface.EventEmitter.emit (domain.js:485:12)
    at Interface._onLine (readline.js:337:10)
    at Interface._line (readline.js:666:8)
(node:70100) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:70100) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`
**Desktop (please complete the following information):**
 - MacOS 
 - Node Version:v13.13.0

**Additional context**
Regression as in: https://github.com/aws-amplify/amplify-cli/issues/2746

**Comment by kaustavghosh06** [comment]
@okigan The CLI doesn’t support npx as of yet. Please install the CLI globally using ‘npm install -g @aws-amplify/cli’ command and then run the amplify init command.
