### ISSUE TITLE
Deleting an API, gives the error `Cannot read property 'awscloudformation' of undefined` when trying to push

### ISSUE THREAD

**Issue by taktran** [aws-amplify/amplify-cli#4005]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**

I tried to remove an API, and when I try to push the changes, I keep getting the following error

```
✖ There was an error pulling the backend environment dev.
An error occured during the push operation: Cannot read property 'awscloudformation' of undefined
```

**Amplify CLI Version**

```
$ amplify -v
4.16.1
```

**To Reproduce**

The steps I did to remove the API (called `graphql`) were

```
$ amplify remove api
? Choose the resource you would want to remove graphql

? Are you sure you want to delete the resource? This action deletes all files related to thi
s resource from the backend directory. Yes
Successfully removed resource

$ amplify status

Current Environment: dev

| Category | Resource name | Operation | Provider plugin   |
| -------- | ------------- | --------- | ----------------- |
| Api      | graphql       | Delete    | awscloudformation |

$ amplify push
✖ There was an error pulling the backend environment dev.
An error occured during the push operation: Cannot read property 'awscloudformation' of undefined
```

**Expected behavior**

Able to `amplify push` without an error, or have

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: `v12.16.1`

**Additional context**

I also tried a `amplify pull` and got

```
$ amplify pull
Cannot read property 'awscloudformation' of undefined
TypeError: Cannot read property 'awscloudformation' of undefined
    at Object.run (/Users/ttt/.nvm/versions/node/v12.16.1/lib/node_modules/@aws-amplify/cli/lib/commands/pull.js:18:64)
    at Object.executeAmplifyCommand (/Users/ttt/.nvm/versions/node/v12.16.1/lib/node_modules/@aws-amplify/cli/lib/index.js:96:25)
    at executePluginModuleCommand (/Users/ttt/.nvm/versions/node/v12.16.1/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:131:32)
    at async Object.executeCommand (/Users/ttt/.nvm/versions/node/v12.16.1/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:16:9)
    at async Object.run (/Users/ttt/.nvm/versions/node/v12.16.1/lib/node_modules/@aws-amplify/cli/lib/index.js:43:9)
```

Also, before trying to remove the api, I tried to update it and it gave me an error

```
$ amplify update api
? Please select from one of the below mentioned services: GraphQL
Parameters file not found
Error: ENOENT: no such file or directory, open '/Users/ttt/Work/Dev/pilea/amplify/backend/api/graphql/parameters.json'
    at Object.openSync (fs.js:457:3)
    at Object.readFileSync (fs.js:359:35)
    at AmplifyToolkit.readJsonFile [as _readJsonFile] (/Users/ttt/.nvm/versions/node/v12.16.1/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/read-json-file.js:10:35)
    at updateWalkthrough (/Users/ttt/.nvm/versions/node/v12.16.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.js:382:34)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.executeAmplifyCommand (/Users/ttt/.nvm/versions/node/v12.16.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/index.js:176:3)
    at async executePluginModuleCommand (/Users/ttt/.nvm/versions/node/v12.16.1/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:131:13)
    at async Object.executeCommand (/Users/ttt/.nvm/versions/node/v12.16.1/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:16:9)
    at async Object.run (/Users/ttt/.nvm/versions/node/v12.16.1/lib/node_modules/@aws-amplify/cli/lib/index.js:43:9)
Could not find a schema at /Users/ttt/Work/Dev/pilea/amplify/backend/api/graphql/schema.graphql
Error: Could not find a schema at /Users/ttt/Work/Dev/pilea/amplify/backend/api/graphql/schema.graphql
    at readSchema (/Users/ttt/.nvm/versions/node/v12.16.1/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/transformConfig.js:115:15)
    at async Object.loadProject (/Users/ttt/.nvm/versions/node/v12.16.1/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/transformConfig.js:41:20)
    at async updateWalkthrough (/Users/ttt/.nvm/versions/node/v12.16.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.js:390:19)
    at async Object.executeAmplifyCommand (/Users/ttt/.nvm/versions/node/v12.16.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/index.js:176:3)
    at async executePluginModuleCommand (/Users/ttt/.nvm/versions/node/v12.16.1/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:131:13)
    at async Object.executeCommand (/Users/ttt/.nvm/versions/node/v12.16.1/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:16:9)
    at async Object.run (/Users/ttt/.nvm/versions/node/v12.16.1/lib/node_modules/@aws-amplify/cli/lib/index.js:43:9)
```

**Comment by taktran** [comment]
Is there a command I can run that will revert the changes?

**Comment by SwaySway** [comment]
Hello @takran you can run the following command `amplify env restore <NAME_OF_ENV>` to restore your cloud environment. Regarding as to how you here what steps did you take to add your api?

**Comment by taktran** [comment]
Hi @SwaySway ,

To add the api, I just followed the docs and selected the defaults:

    amplify add api
    # ? Please select from one of the below mentioned services: GraphQL
    # ? Provide API name: graphql
    # ? Choose the default authorization type for the API API key
    # ? Enter a description for the API key: GraphqL API key
    # ? After how many days from now the API key should expire (1-365): 7
    # ? Do you want to configure advanced settings for the GraphQL API: Yes, I want to make some additional changes.
    # ? Configure additional auth types? No
    # ? Configure conflict detection? No
    # ? Do you have an annotated GraphQL schema? No
    # ? Do you want a guided schema creation? Yes
    # ? What best describes your project: Single object with fields (e.g., “Todo” with ID, name, description)
    # ? Do you want to edit the schema now? No

I've since deleted everything (`rm -rf amplify` as `amplify delete` didn't work) and started again, and it seems to be ok now.

**Comment by SwaySway** [comment]
Should a similar error come up again please comment below. Closing for now.

**Comment by alichherawalla** [comment]
I have the same issue

```
TypeError: Cannot read property 'awscloudformation' of undefined
    at Object.run (/Users/mac/.config/yarn/global/node_modules/@aws-amplify/cli/lib/commands/pull.js:18:64)
    at Object.executeAmplifyCommand (/Users/mac/.config/yarn/global/node_modules/@aws-amplify/cli/lib/index.js:110:25)
    at executePluginModuleCommand (/Users/mac/.config/yarn/global/node_modules/@aws-amplify/cli/lib/execution-manager.js:131:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

**Comment by mansdahlstrom1** [comment]
Also had this error but in another context (Github Action) and was getting the same error `Cannot read property 'awscloudformation' of undefined `. For me it turns out that the issue was originating from `team-provider-info.json` not having the current ´env´ as a key in the json file. 

Example of `dev` env and  

```
"dev": { // < ---  missing this key, generates the error
    "awscloudformation": {....}
}
```

In general i think Amplify should write out what file the error happend in, when error like `Cannot read property 'awscloudformation' of undefined ` happends.

Just putting this here in case some on is on the same debugging track as I aws just recently.
