### ISSUE TITLE
TypeError: Cannot destructure property 'serviceWalkthroughFilename' of 'serviceMetadata' as it is undefined.

### ISSUE THREAD

**Issue by adilusman51** [aws-amplify/amplify-cli#4059]
**Describe the bug**

```
amplify add function

Using service: Lambda, provided by: awscloudformation
? Provide a friendly name for your resource to be used as a label for this category in the project: addUserToGroup
? Provide the AWS Lambda function name: addUserToGroup
? Choose the function runtime that you want to use: NodeJS
? Choose the function template that you want to use: Hello World
? Do you want to access other resources created in this project from your Lambda function? Yes
? Select the category auth
? Auth has 2 resources in this project. Select the one you would like your Lambda to access biXXXXXXXXXXXXX55, userPoolGroups
? Select the operations you want to permit for biXXXXXXXXXXXXX55 read
? Select the operations you want to permit for userPoolGroups read, update
Could not get policies for auth: userPoolGroups
Policies cannot be added for auth

TypeError: Cannot destructure property 'serviceWalkthroughFilename' of 'serviceMetadata' as it is undefined.
    at Object.getPermissionPolicies (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/provider-utils/awscloudformation/index.js:587:11)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/index.js:277:59
    at Array.forEach (<anonymous>)
    at getPermissionPolicies (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/index.js:273:35)
    at Object.askExecRolePermissionsQuestions (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.js:132:78)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.createWalkthrough (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/service-walkthroughs/lambda-walkthrough.js:28:32)
    at async Object.addResource (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/index.js:29:9)
    at async Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/lib/index.js:130:5)
    at async executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:131:13)

You can access the following resource attributes as environment variables from your Lambda function
var environment = process.env.ENV
var region = process.env.REGION
var authBiXXXXXXXXXXXXX55UserPoolId = process.env.AUTH_BIXXXXXXXXXXXXX55_USERPOOLID

? Do you want to invoke this function on a recurring schedule? No
? Do you want to edit the local lambda function now? No
Successfully added resource addUserToGroup locally.

```

**Amplify CLI Version**
`amplify 4.18.0`

**To Reproduce**
`amplify add auth`
`amplify add api`
`amplify update auth` > Create or update Cognito user pool groups > `add multiple user pool groups`
`amplify add function` > `with options selection above`

**Expected behavior**
I am not sure

**Desktop (please complete the following information):**
 - OS: Mac 10.15.3 
 - Node Version: 13.11.0

**Comment by ammarkarachi** [comment]
@adilusman51 User pool group is not supported but giving access to Cognito would grant it access to the userPoolGroups

**Comment by ammarkarachi** [comment]
Closing issue for now do not hesitate to reopen if you are still facing issues
