### ISSUE TITLE
PostConfirmation failed with RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by jingxizhang** [aws-amplify/amplify-cli#4065]
**Describe the bug**
After update the PostComirmation lambda function by adding permission to existing DynamoDB, I got "RangeError: Maximum call stack size exceeded".

**Amplify CLI Version**
4.18.1

**To Reproduce**
1. Create PostComfirmation lambda function for adding user to a user group:
```
> amplify update auth
…
Do you want to enable any of the following capabilities? Add User to Group
…
? Do you want to configure Lambda Triggers for Cognito? Yes
? Which triggers do you want to enable for Cognito   Post Confirmation
? What functionality do you want to use for Post Confirmation Add User To Group
```
2. Push the update to cloud and make sure it works
`> amplify push`
3. Add permission to PostCormfirmation lambda function for access an existing DynamoDB:
```
>amplify update function
? Please select the Lambda Function you would want to update xxxxxxxPostConfirmation
? Do you want to update permissions granted to this Lambda function to perform on other resources in your project? Yes
? Select the category storage
? Storage has 5 resources in this project. Select the one you would like your Lambda to access <target DynamoDB name>
? Select the operations you want to permit for <targetDynamoDB name> read, update
? Do you want to invoke this function on a recurring schedule? No
? Do you want to edit the local lambda function now? No
Successfully updated resource
```
4. Push the update to cloud
`> amplify push`
5. From user sign-up GUI, create a new account. 
After confirmation I got "RangeError: Maximum call stack size exceeded"
In CloudWatch logging:
```
2020-04-24T16:35:12.511Z 109c27df-a040-4856-8e55-9d859d556541 ERROR Invoke Error 
{
    "errorType": "RangeError",
    "errorMessage": "Maximum call stack size exceeded",
    "stack": [
        "RangeError: Maximum call stack size exceeded",
        "    at Object.hasOwnProperty (<anonymous>)",
        "    at Function.NativeModule.exists (internal/bootstrap/loaders.js:199:33)",
        "    at Function.NativeModule.nonInternalExists (internal/bootstrap/loaders.js:217:27)",
        "    at Function.Module._resolveLookupPaths (internal/modules/cjs/loader.js:456:20)",
        "    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:629:20)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:562:25)",
        "    at Module.require (internal/modules/cjs/loader.js:692:17)",
        "    at require (internal/modules/cjs/helpers.js:25:18)",
        "    at exports.handler (/var/task/index.js:15:25)",
        "    at exports.handler (/var/task/index.js:16:5)"
    ]
}

```

**Expected behavior**
It should run the confirmation success without error because there is no any customized code was added to the PostConfirm lambda function.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node Version: v12.13.1

**Comment by jingxizhang** [comment]
@SwaySway 
How is the work going?
Thank you.

**Comment by yuth** [comment]
@jingxizhang was the lambda customized? Would it be possible to share the lambda function code?

**Comment by jingxizhang** [comment]
Hi Yuth,
The lambda function is auto generated by Amplify CLI. I did not modify it.

**Comment by yuth** [comment]
@jingxizhang this is a bug in Amplify CLIs function update flow. When the update flow overwrites `<proj-root>/amplify/backend/function/<fn-name>/parameters.json` and `<proj-root>/amplify/backend/function/<fn-name>/function-parameters.json`. Till we fix this you could work around this by adding the following to 

```diff
--- a/amplify/backend/function/fn-name/function-parameters.json
+++ b/amplify/backend/function/fn-name/function-parameters.json
@@ -1,4 +1,8 @@
 {
+    "trigger": true,
+    "modules": [
+        "add-to-group"
+    ],
     "parentResource": "postconf4167fde9",
     "functionName": "postconf4167fde9PostConfirmation",
     "resourceName": "postconf4167fde9PostConfirmation",
diff --git a/amplify/backend/function/fn-name/parameters.json b/amplify/backend/function/fn-name/parameters.json
index 13624db..3a915e2 100644
--- a/amplify/backend/function/postconf4167fde9PostConfirmation/parameters.json
+++ b/amplify/backend/function/postconf4167fde9PostConfirmation/parameters.json
@@ -1,3 +1,4 @@
 {
+    "modules": "add-to-group",
     "resourceName": "postconf4167fde9PostConfirmation"
 }
```
