### ISSUE TITLE
invalid graphql schema generation on `amplify add api` on CLI version 4.18.1

### ISSUE THREAD

**Issue by ninjabiscuit** [aws-amplify/amplify-cli#4087]
**Describe the bug**
When trying to add an API with `amplify add api` with the following selections:
```
? Do you want a guided schema creation? Yes
? What best describes your project: One-to-many relationship (e.g., “Blogs” with “Posts” and “Comments”)
? Do you want to edit the schema now? No
```
The command fails with 
```
InvalidDirectiveError: id field is not of type String
    at checkFieldsAgainstIndex (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-connection-transformer/src/ModelConnectionTransformer.ts:112:11)
    at ModelConnectionTransformer.connectionWithKey (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-connection-transformer/src/ModelConnectionTransformer.ts:581:7)
    at ModelConnectionTransformer.field (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-connection-transformer/src/ModelConnectionTransformer.ts:219:12)
    at GraphQLTransform.transformField (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/GraphQLTransform.ts:372:25)
    at GraphQLTransform.transformObject (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/GraphQLTransform.ts:350:12)
    at GraphQLTransform.transform (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/GraphQLTransform.ts:266:18)
    at _buildProject (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/util/amplifyUtils.ts:61:35)
    at Object.buildProject [as buildAPIProject] (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/util/amplifyUtils.ts:30:24)
    at transformGraphQLSchema (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/transform-graphql-schema.js:458:29)
    at serviceWalkthrough (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.js:283:3)
There was an error adding the API resource
```
It seems the the builder generates an invalid schema:

```
type Blog @model {
  id: ID!
  name: String!
  posts: [Post] @connection(keyName: "byBlog", fields: ["id"])
}

type Post @model @key(name: "byBlog", fields: ["blogID"]) {
  id: ID!
  title: String!
  blogID: String!
  blog: Blog @connection(fields: ["blogID"])
  comments: [Comment] @connection(keyName: "byPost", fields: ["id"])
}

type Comment @model @key(name: "byPost", fields: ["postID", "content"]) {
  id: ID!
  postID: ID!
  post: Post @connection(fields: ["postID"])
  content: String!
}
```
Where `blogID: String!` on line 10 should be `blogID: ID!`

When I duplicated this file and reran `amplify add api` with an amended schema path file (having changed `String!` to `ID!`) it works

**Amplify CLI Version**
4.18.1

**Comment by ninjabiscuit** [comment]
Looks like this is a dupe of https://github.com/aws-amplify/amplify-js/issues/5211 and fixed in https://github.com/aws-amplify/amplify-cli/pull/4070
