### ISSUE TITLE
'amplify api add-graphql-datasource' does not work for aurora postgresql serverless

### ISSUE THREAD

**Issue by hellaeon** [aws-amplify/amplify-cli#4191]
**Describe the bug**
When I run the command `amplify api add-graphql-datasource` with an aurora serverless postgresql cluster, I get an error `ERROR: unrecognized configuration parameter "databases"`
This is also discussed here #2738 

**Amplify CLI Version**
4.16.1

**To Reproduce**
1) create a new aurora serverless db and secrets object for it (i used the cmd line to ensure it was actually serverless) 
2) link to it using the above amplify command.

**Expected behavior**
I expect a new data source to be created in app sync for my project. It will be the aurora cluster I created above. This works if I use _**mysql**_, but it does not work for _**postgresql**_

**Screenshots**

> [Wed May 06 16:40:45] amplify api add-graphql-datasource
> Using datasource: Aurora Serverless, provided by: awscloudformation
> ? Provide the region in which your cluster is located: us-east-2
> 
> ? Select the Aurora Serverless cluster that will be used as the data source for your API: covr-cluster
> ? Select the secret used to access your Aurora Serverless cluster: aurora_login
> ⠇ Fetching Aurora Serverless cluster...BadRequestException: ERROR: unrecognized configuration parameter "databases"
>     at Object.extractError (/Users/hellaeon/.nvm/versions/node/v10.15.3/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/json.js:51:27)
>     at Request.extractError (/Users/hellaeon/.nvm/versions/node/v10.15.3/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
>     at Request.callListeners (/Users/hellaeon/.nvm/versions/node/v10.15.3/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
>     at Request.emit (/Users/hellaeon/.nvm/versions/node/v10.15.3/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
>     at Request.emit (/Users/hellaeon/.nvm/versions/node/v10.15.3/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
>     at Request.transition (/Users/hellaeon/.nvm/versions/node/v10.15.3/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
>     at AcceptorStateMachine.runTo (/Users/hellaeon/.nvm/versions/node/v10.15.3/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
>     at /Users/hellaeon/.nvm/versions/node/v10.15.3/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
>     at Request.<anonymous> (/Users/hellaeon/.nvm/versions/node/v10.15.3/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
>     at Request.<anonymous> (/Users/hellaeon/.nvm/versions/node/v10.15.3/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12)
> There was an error adding the datasource
> Fetching Aurora Serverless cluster...

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: 12.16.1

**Additional context**
From some investigation, amplify tries to do a simple handshake with your serverless db when you run `amplify api add-graphql-datasource`. Part of this payload is a request to the Data Api of the serverless instance:
` DataApiParams {
        secretArn:
         'arn:aws:secretsmanager:us-east-2:xxx:secret:mydb_db_secrets-uz6SNa',
        resourceArn: 'arn:aws:rds:us-east-2:xxx:cluster:my-cluster',
        sql: 'SHOW databases' },`

The issue with sending this to postgres flavours is it has no idea how to deal with `SHOW databases`.

I can emulate the same commands using the cli:
`aws rds-data execute-statement --secret-arn "arn:aws:secretsmanager:us-east-2:xxx:secret:mydb_db_secrets-uz6SNa" --resource-arn "arn:aws:rds:us-east-2:xxx:cluster:my-cluster" --database dbjuice --sql "show databases" --output json --region us-east-2
An error occurred (BadRequestException) when calling the ExecuteStatement operation: ERROR: unrecognized configuration parameter "databases"`

A real fix would be finding out the db type before running the command to handshake.
To get the actual names I used this sql instead: `SELECT datname FROM pg_database WHERE datistemplate = false;`

So although this is not the fix, this _**appears**_ to be the problem. Can anyone at AWS advise some more here?

cheers

**Comment by hellaeon** [comment]
With further investigation this seems a specific error that points out there is no actual postgresql support in amplify for aurora serverless from what I can see.

I modified https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-category-api/provider-utils/awscloudformation/service-walkthroughs/appSync-rds-walkthrough.js locally to get past the database part by considering if it was either mysql or postgres, but then realised `AuroraDataAPIClient` assumes a mysql endpoint.
