### ISSUE TITLE
NoSuchKey: The specified key does not exist.

### ISSUE THREAD

**Issue by MontoyaAndres** [aws-amplify/amplify-cli#4232]
**Which Category is your question related to?**

Api and s3 bucket for deployment

**Amplify CLI Version** 

4.18.1

**What AWS Services are you utilizing?**

Api AppSync

**Provide additional details e.g. code snippets**

I have removed the folder amplify-beitdev-dev-105810-deployment used for Amplify, I tried to restore it following this [issue](https://github.com/aws-amplify/amplify-cli/issues/1441) I just created the folder with `amplify-beitdev-dev-105810-deployment` and then I executed the command `amplify push` and I got this error:

```
andres@DESKTOP-61RLK6J:~/work/beit$ amplify push
⠏ Fetching updates to backend environment: dev from the cloud.(node:11249) UnhandledPromiseRejectionWarning: NoSuchKey: The specified key does not exist.
    at Request.extractError (/home/andres/.nvm/versions/node/v13.11.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/services/s3.js:835:35)
    at Request.callListeners (/home/andres/.nvm/versions/node/v13.11.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/andres/.nvm/versions/node/v13.11.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/andres/.nvm/versions/node/v13.11.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/andres/.nvm/versions/node/v13.11.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/andres/.nvm/versions/node/v13.11.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/andres/.nvm/versions/node/v13.11.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/andres/.nvm/versions/node/v13.11.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/andres/.nvm/versions/node/v13.11.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/andres/.nvm/versions/node/v13.11.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
(node:11249) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11249) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠧ Fetching updates to backend environment: dev from the cloud.
```

I don't know why happens this... This is the `àmplify-meta.json` file:

```
{
    "providers": {
        "awscloudformation": {
            "AuthRoleName": "amplify-beitdev-dev-105810-authRole",
            "UnauthRoleArn": "arn:aws:iam::413969749414:role/amplify-beitdev-dev-105810-unauthRole",
            "AuthRoleArn": "arn:aws:iam::413969749414:role/amplify-beitdev-dev-105810-authRole",
            "Region": "us-east-2",
            "DeploymentBucketName": "amplify-beitdev-dev-105810-deployment",
            "UnauthRoleName": "amplify-beitdev-dev-105810-unauthRole",
            "StackName": "amplify-beitdev-dev-105810",
            "StackId": "arn:aws:cloudformation:us-east-2:413969749414:stack/amplify-beitdev-dev-105810/bcf65420-7e68-11ea-9fc5-02402ec64522",
            "AmplifyAppId": "d3f2rxt3ihzd5c"
        },
        "categories": {
            "function": {
                "beitdevbeaa9d10PostConfirmation": {
                    "GROUP": ""
                }
            },
            "auth": {
                "beitdevbeaa9d10": {},
                "userPoolGroups": {}
            }
        }
    },
    "auth": {
        "beitdevbeaa9d10": {
            "service": "Cognito",
            "providerPlugin": "awscloudformation",
            "dependsOn": [
                {
                    "category": "function",
                    "resourceName": "beitdevbeaa9d10PostConfirmation",
                    "triggerProvider": "Cognito",
                    "attributes": [
                        "Arn",
                        "Name"
                    ]
                }
            ]
        },
        "userPoolGroups": {
            "service": "Cognito-UserPool-Groups",
            "providerPlugin": "awscloudformation",
            "dependsOn": [
                {
                    "category": "auth",
                    "resourceName": "beitdevbeaa9d10",
                    "attributes": [
                        "UserPoolId",
                        "AppClientIDWeb",
                        "AppClientID",
                        "IdentityPoolId"
                    ]
                }
            ]
        }
    },
    "api": {
        "beitdev": {
            "service": "AppSync",
            "providerPlugin": "awscloudformation",
            "output": {
                "authConfig": {
                    "additionalAuthenticationProviders": [],
                    "defaultAuthentication": {
                        "authenticationType": "AMAZON_COGNITO_USER_POOLS",
                        "userPoolConfig": {
                            "userPoolId": "authbeitdevbeaa9d10"
                        }
                    }
                }
            }
        }
    },
    "storage": {
        "amplifybeitbucket": {
            "service": "S3",
            "providerPlugin": "awscloudformation"
        }
    },
    "function": {
        "beitdevbeaa9d10PostConfirmation": {
            "build": true,
            "providerPlugin": "awscloudformation",
            "service": "Lambda"
        }
    }
}
```

And I also tried removing this env with `amplify env remove dev` and I got that same error...

**Comment by MontoyaAndres** [comment]
New update about this:

I could find this [comment](https://github.com/aws-amplify/amplify-cli/issues/3595#issuecomment-596787013) and I did what he wrote. I took the current `#current-cloud-backend` folder, zip it and I uploaded it to this bucket created before. The `amplify-beitdev-dev-105810-deployment`. Then I did `amplify push` and this command throws me this error:

```
andres@DESKTOP-61RLK6J:~/work/beit$ amplify push                                                                          ✖ There was an error pulling the backend environment dev.
An error occured during the push operation: ENOENT: no such file or directory, open '/home/andres/work/beit/amplify/#current-cloud-backend/amplify-meta.json'
```

So, I looked at this folder and I saw that this command creates two times the folder:

![image](https://user-images.githubusercontent.com/15065852/81636369-5024d980-93d9-11ea-8548-5f25836a2b56.png)

I tried removing it, and then do `amplify push` and I got the same error, and the two folders were created again...

**Comment by MontoyaAndres** [comment]
New update about this:

I tried now `amplify pull` because all the functionality was created before... but I got this:

![image](https://user-images.githubusercontent.com/15065852/81636887-92024f80-93da-11ea-84c0-8cf8bf2745e3.png)

This is the error:

```
andres@DESKTOP-61RLK6J:~/work/beit$ amplify pull

Pre-pull status:

Current Environment: dev

| Category | Resource name                   | Operation | Provider plugin   |
| -------- | ------------------------------- | --------- | ----------------- |
| Auth     | beitdevbeaa9d10                 | Update    | awscloudformation |
| Api      | beitdev                         | Update    | awscloudformation |
| Storage  | amplifybeitbucket               | Update    | awscloudformation |
| Function | beitdevbeaa9d10PostConfirmation | Update    | awscloudformation |
| Auth     | userPoolGroups                  | No Change | awscloudformation |

Local changes detected.
Pulling changes from the cloud will override your local changes.
? Are you sure you would like to continue? Yes
✖ There was an error pulling the backend environment dev.
ENOENT: no such file or directory, open '/home/andres/work/beit/amplify/#current-cloud-backend/amplify-meta.json'
Error: ENOENT: no such file or directory, open '/home/andres/work/beit/amplify/#current-cloud-backend/amplify-meta.json'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at AmplifyToolkit.readJsonFile [as _readJsonFile] (/home/andres/.nvm/versions/node/v13.11.0/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/read-json-file.js:14:33)
    at /home/andres/.nvm/versions/node/v13.11.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/initialize-env.js:35:50
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Within the folder `#current-cloud-backend` was created again with the same content. And within the folder `backend` was created the folder `#current-cloud-backend` with its content...

**Comment by MontoyaAndres** [comment]
New update:

I tried to update the CLI on its latest version but I got the same error:

![image](https://user-images.githubusercontent.com/15065852/81637736-b6f7c200-93dc-11ea-8e80-da8b6fe3f330.png)

**Comment by MontoyaAndres** [comment]
I could fix it 😅 and the solution was pretty easy.

When I uploaded the `#current-cloud-backend` file zipped it, this one was uploaded with a folder called `#current-cloud-backend` and within this the data... The solution was just zipping it without this folder.

Would be great if the CLI could handle this and give us feedback about these things :)

**Comment by UnleashedMind** [comment]
Yes, you found the solution. Thanks for your feedbacks. Closing this issue since you are not blocked anymore.

**Comment by IsaacTrevino** [comment]
After amplify push
Following resources failed
Resource Name: XXXXXXXXGraphQLSchema (AWS::AppSync::GraphQLSchema) Event Type: update Reason: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: XXXXXXX; S3 Extended Request ID: XXXXXX URL: https://console.aws.amazon.com/cloudformation/home?region=us-east-X#/stacks/XXX/events

given the XXX is my attempt to cover confidential info. I have the following resources,
`| Category | Resource name | Operation | Provider plugin |

| -------- | -------------------- | --------- | ----------------- |

| Storage | s3 | Create | awscloudformation |

| Auth | userPoolGroups | No Change | awscloudformation |

| Auth | myAuth | No Change | awscloudformation |

| Function | AdminQueries | No Change | awscloudformation |

| Api | AdminQueries | No Change | awscloudformation |

| Api | graphQL | No Change | awscloudformation |`

I believe it is due to the fact I am using dataStore as well, I just updated to 4.21.4
Using Node12.X

**Comment by aditi172** [comment]
> Yes, you found the solution. Thanks for your feedbacks. Closing this issue since you are not blocked anymore.

Actually I was having the same issue.... and I did what was told in the comments thread here but the error still persists... 
I did not have the deployement bucket in s3 so I created one with the same name and added the zipped #current-cloud-backend file and now the cli just hangs on "- Fetching updates to backend environment: dev from the cloud." on doing "amplify push"

Is there a way out of this?
