### ISSUE TITLE
amplify status doesn't work properly after npx amplify-app

### ISSUE THREAD

**Issue by drochetti** [aws-amplify/amplify-cli#4272]
**Describe the bug**
After creating a new Amplify.DataStore project using `npx amplify-app` I tried to run `amplify status` and got an error. The initial status output was shown but then I get a stacktrace saying there's a missing file:

```
Scanning for plugins...
Plugin scan successful
| Category | Resource name     | Operation | Provider plugin   |
| -------- | ----------------- | --------- | ----------------- |
| Api      | amplifyDatasource | Create    | awscloudformation |

ENOENT: no such file or directory, open '~/dev/workplace/AmplifyDataStoreNonModelCodegen/amplify/backend/amplify-meta.json'
Error: ENOENT: no such file or directory, open '~/dev/workplace/AmplifyDataStoreNonModelCodegen/amplify/backend/amplify-meta.json'
    at Object.openSync (fs.js:447:3)
    at Object.readFileSync (fs.js:349:35)
    at readJsonFile (~/.nvm/versions/node/v12.8.0/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/read-json-file.js:14:33)
    at AmplifyToolkit.getProjectMeta [as _getProjectMeta] (~/.nvm/versions/node/v12.8.0/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/get-project-meta.js:6:23)
    at showGraphQLURL (~/.nvm/versions/node/v12.8.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/display-helpful-urls.js:36:41)
    at displayHelpfulURLs (~/.nvm/versions/node/v12.8.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/display-helpful-urls.js:7:3)
    at Object.showHelpfulLinks (~/.nvm/versions/node/v12.8.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/index.js:83:10)
    at ~/.nvm/versions/node/v12.8.0/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/show-helpful-provider-links.js:14:40
    at Array.forEach (<anonymous>)
    at AmplifyToolkit.showHelpfulProviderLinks [as _showHelpfulProviderLinks] (~/.nvm/versions/node/v12.8.0/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/show-helpful-provider-links.js:12:13)
```

**Amplify CLI Version**
`4.19.0`

**To Reproduce**
1. Create a new project
1. Execute `npx amplify-app`
1. Try executing `amplify status` right after the previous command is done

**Expected behavior**

**Screenshots**
*N/A*

**Desktop (please complete the following information):**
 - OS: `MacOS 10.14.6`
 - Node Version: `v12.8.0`

**Additional context**
*N/A*

**Comment by amuresia** [comment]
+1
