### ISSUE TITLE
Stack trace when add api called from non-Amplify project

### ISSUE THREAD

**Issue by jamesonwilliams** [aws-amplify/amplify-cli#4283]
**Describe the bug**
I run `amplify add api` in a directory where `amplify init` _has not_ been run. The CLI tells me that's an error. This is expected.

What is _not_expected is the stack trace, below the message.

```
$ amplify add api 
You are not working inside a valid amplify project.
Use 'amplify init' in the root of your app directory to initialize your project with Amplify
Error: You are not working inside a valid amplify project.
Use 'amplify init' in the root of your app directory to initialize your project with Amplify
    at getAmplifyDirPath (/usr/local/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/path-manager.js:45:11)
    at getDotConfigDirPath (/usr/local/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/path-manager.js:48:37)
    at Object.getProjectConfigFilePath (/usr/local/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/path-manager.js:75:37)
    at getProjectConfig (/usr/local/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/get-project-config.js:5:47)
    at AmplifyToolkit.serviceSelectionPrompt [as _serviceSelectionPrompt] (/usr/local/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/service-select-prompt.js:54:27)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/commands/api/add.js:12:8)
    at Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/index.js:176:23)
    at executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:47:32)
    at async Object.executeCommand (/usr/local/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:15:9)
    at async Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/lib/index.js:41:9)
```

**Amplify CLI Version**
4.13.4

**To Reproduce**
```
mkdir foo
cd foo
amplify add api
```

**Expected behavior**
I expect this output, only.
```
$ amplify add api
You are not working inside a valid amplify project.
Use 'amplify init' in the root of your app directory to initialize your project with Amplify
```

**Desktop (please complete the following information):**
- Mac OS X 10.14.6 (18G3020)
- Node v12.12.0

**Comment by jamesonwilliams** [comment]
Closing as stale for now to clear my open issues list. Will re-open if I can reference this from a contributed PR.
