### ISSUE TITLE
UnhandledPromiseRejectionWarning: SlowDown: Please reduce your request rate.

### ISSUE THREAD

**Issue by aprilmintacpineda** [aws-amplify/amplify-cli#4381]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**

`amplify env delete dev` displays the following error:

```
amplify env remove dev
? Are you sure you want to continue? (This would delete 'dev' environment of the project from the cloud) Yes
⠋ Deleting resources from the cloud. This may take a few minutes...
Deleting env:dev
⠦ Deleting resources from the cloud. This may take a few minutes...(node:2166) UnhandledPromiseRejectionWarning: SlowDown: Please reduce your request rate.
    at Request.extractError (/Users/aprilmintacpineda/.nvm/versions/node/v14.0.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/services/s3.js:835:35)
    at Request.callListeners (/Users/aprilmintacpineda/.nvm/versions/node/v14.0.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/aprilmintacpineda/.nvm/versions/node/v14.0.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/aprilmintacpineda/.nvm/versions/node/v14.0.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/aprilmintacpineda/.nvm/versions/node/v14.0.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/aprilmintacpineda/.nvm/versions/node/v14.0.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/aprilmintacpineda/.nvm/versions/node/v14.0.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/aprilmintacpineda/.nvm/versions/node/v14.0.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/aprilmintacpineda/.nvm/versions/node/v14.0.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/aprilmintacpineda/.nvm/versions/node/v14.0.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2166) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2166) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠙ Deleting resources from the cloud. This may take a few minutes...
```

but the process keeps going anyway as you can see on the last line it still said `Deleting resources from the cloud. This may take a few minutes...`

**Amplify CLI Version**

4.18.0

**To Reproduce**

Run command above.

**Expected behavior**

Should not throw that error.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Node Version: v14.0.0

**Additional context**

None.

**Comment by aprilmintacpineda** [comment]
Update: the process hasn't stopped running since it started, does it really take this long?

**Comment by ammarkarachi** [comment]
@aprilmintacpineda you can CTRL + C out of it, can you try deleting the resources again?

**Comment by aprilmintacpineda** [comment]
@ammarkarachi I tried it, here's the output.

```
amplify env remove dev
Scanning for plugins...
Plugin scan successful
? Are you sure you want to continue? (This would delete 'dev' environment of the project from the cloud) Yes
⠋ Deleting resources from the cloud. This may take a few minutes...
Deleting env:dev
⠸ Deleting resources from the cloud. This may take a few minutes...Stack has already been deleted or does not exist
⠼ Deleting resources from the cloud. This may take a few minutes...(node:2491) UnhandledPromiseRejectionWarning: NoSuchKey: The specified key does not exist.
    at Request.extractError (/Users/aprilmintacpineda/.nvm/versions/node/v14.0.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/services/s3.js:835:35)
    at Request.callListeners (/Users/aprilmintacpineda/.nvm/versions/node/v14.0.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/aprilmintacpineda/.nvm/versions/node/v14.0.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/aprilmintacpineda/.nvm/versions/node/v14.0.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/aprilmintacpineda/.nvm/versions/node/v14.0.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/aprilmintacpineda/.nvm/versions/node/v14.0.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/aprilmintacpineda/.nvm/versions/node/v14.0.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/aprilmintacpineda/.nvm/versions/node/v14.0.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/aprilmintacpineda/.nvm/versions/node/v14.0.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/aprilmintacpineda/.nvm/versions/node/v14.0.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2491) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2491) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠦ Deleting resources from the cloud. This may take a few minutes...
```

It did say that the stack has been deleted, it threw an error but still did not exit and kept ongoing as you can see on the last line it says "Deleting resources from the cloud. This may take a few minutes...".

**Comment by aprilmintacpineda** [comment]
I did `amplify env add dev` after delete and it threw this error, what does it mean?

```
amplify env add dev
Note: It is recommended to run this command from the root of your app directory
? Do you want to use an existing environment? No
? Enter a name for the environment dev
Using default provider  awscloudformation
⠋ Initializing your environment: dev(node:2617) UnhandledPromiseRejectionWarning: NoSuchKey: The specified key does not exist.
    at Request.extractError (/Users/aprilmintacpineda/.nvm/versions/node/v14.0.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/services/s3.js:835:35)
    at Request.callListeners (/Users/aprilmintacpineda/.nvm/versions/node/v14.0.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/aprilmintacpineda/.nvm/versions/node/v14.0.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/aprilmintacpineda/.nvm/versions/node/v14.0.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/aprilmintacpineda/.nvm/versions/node/v14.0.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/aprilmintacpineda/.nvm/versions/node/v14.0.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/aprilmintacpineda/.nvm/versions/node/v14.0.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/aprilmintacpineda/.nvm/versions/node/v14.0.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/aprilmintacpineda/.nvm/versions/node/v14.0.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/aprilmintacpineda/.nvm/versions/node/v14.0.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2617) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2617) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠙ Initializing your environment: dev
```

**Comment by aprilmintacpineda** [comment]
After deletion everything that I do now throws that error.

**Comment by ammarkarachi** [comment]
Does your deployment bucket still exist?

**Comment by aprilmintacpineda** [comment]
Yes I can still see the deployment bucket of the supposedly deleted environment. Should that have been deleted?

**Comment by aprilmintacpineda** [comment]
Also, `amplify env list` still shows the supposedly deleted environment.

**Comment by aprilmintacpineda** [comment]
What I was trying to do was delete an existing environment and recreate it using the same name, I think it didn't work but I was able to create a new environment with different name.

**Comment by bob-lee** [comment]
I'm experiencing almost the same situation. I was to remove `mtubuntu` env:

```
$ amplify env list

| Environments |
| ------------ |
| mtubuntu     |
| *dev         |
| prod         |

```

>Ubuntu
amplify 4.18.0
nodejs 10.16.2

On first run, got `SlowDown` error.
On second run, got `NoSuchKey` error.

Now my vscode editor shows some untracked files under `amplify/mtubuntu` folder:

```
drwxrwxr-x 7 bob bob   4096 Sep  8 13:04 '#current-cloud-backend'/
-rw-rw-r-- 1 bob bob 235209 Sep  8 13:04 '#current-cloud-backend.zip'
```

Not sure if it is ok to do `amplify push` these changes?

**Comment by kaustavghosh06** [comment]
@aprilmintacpineda This is most probably tied to this issue - https://github.com/aws-amplify/amplify-cli/pull/6941 and should be fixed when this fix gets released as a part of our next release.
