### ISSUE TITLE
"There was an error adding the datasource" .BadRequestException: Access denied for user, 'admin'@'10.1.13.10' (using password: YES)

### ISSUE THREAD

**Issue by parthsoni42** [aws-amplify/amplify-cli#4384]
Hello team, 
I m facing this error while adding the datasource in my amplify project. I have check my amplify and its already to a latest version.

I m adding the data source by running **amplify api add-graphql-datasource**

**Output**
```
Provide the region in which your cluster is located: us-east-1
? Select the Aurora Serverless cluster that will be used as the data source for 
your API: ampify-datastoredb
⠙ Fetching Aurora Serverless cluster...BadRequestException: Access denied for user 'admin'@'10.1.13.10' (using password: YES)
    at Object.extractError (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.extractError (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12)
There was an error adding the datasource
⠹ Fetching Aurora Serverless cluster...
```
**Expected behaviour**

The database cluster should be added successfully.

Please guide on this.

**Comment by ammarkarachi** [comment]
@parthsoni42 what version of the cli are you using and can you check the credentials of IAM user?

**Comment by parthsoni42** [comment]
> @parthsoni42 what version of the cli are you using and can you check the credentials of IAM user?

**Comment by parthsoni42** [comment]
@ammarkarachi My cli version is **4.19.0**.

I have check my version by running **amplify --v** command. I have also check for the version update by running **npm install -g @aws-amplify/cli** command.

It always install the version **4.19.0** so its a latest version right?

**Comment by ammarkarachi** [comment]
The latest version would be 4.21.0 also **can you check the credentials for the IAM user?**

**Comment by ammarkarachi** [comment]
@parthsoni42 We are going to mark this as a bug but so that we could have a more graceful failure when access is denied

**Comment by parthsoni42** [comment]
> The latest version would be 4.21.0 also **can you check the credentials for the IAM user?**

@ammarkarachi thanks for your reply.

I have update my amplify version and its now 4.21.0. Also my IAM user have admin access for rds and other permissions but still I am not able to connect with my aurora serverless datasource.

Here is my **amplify version**. (I have check my current version by running **amplify --v**)

admin-168@admin168:/mnt/7159d57f-c9cb-4fd4-b5f1-a04f7bb9a8ae/Projects/Dinal/Demo/AmplifyDemo$ amplify --v
Scanning for plugins...
Plugin scan successful
4.21.0


**Please check the below logs for adding datasource:**

admin-168@admin168:/mnt/7159d57f-c9cb-4fd4-b5f1-a04f7bb9a8ae/Projects/Dinal/Demo/AmplifyDemo$ amplify api add-graphql-datasource

Using datasource: Aurora Serverless, provided by: awscloudformation
? Provide the region in which your cluster is located: us-east-1
? Select the Aurora Serverless cluster that will be used as the data source for 
your API: ampify-datastoredb

Fetching Aurora Serverless cluster...BadRequestException: Access denied for user 'admin'@'10.1.13.10' (using password: YES)
    at Object.extractError (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.extractError (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12)

There was an error adding the datasource

**Comment by hutber** [comment]
I can confirm I have having an identical error.

I have created multiple secrets now, some with `DefaultEncryptionKey` otherwise with every entry selected for permissions just to see if I could get it working.

```sh
Using datasource: Aurora Serverless, provided by: awscloudformation
? Provide the region in which your cluster is located: eu-west-2
? Select the Aurora Serverless cluster that will be used as the data source for your API: unsal
? Select the secret used to access your Aurora Serverless cluster: hutber
⠴ Fetching Aurora Serverless cluster...BadRequestException: Access denied for user 'jamie@hutber.com'@'10.1.6.36' (using password: YES)
    at Object.extractError (/home/hutber/.nvm/versions/node/v13.8.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.extractError (/home/hutber/.nvm/versions/node/v13.8.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/home/hutber/.nvm/versions/node/v13.8.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
```

**Comment by Theduud** [comment]
Was anyone able to resolve this? I'm having the same problem

**Comment by Tporkka** [comment]
Any updates on this? I'm having the same issue here with cli version 4.34.0 while trying to connect to Aurora MySQL instance.

**Comment by mattcech** [comment]
Any updates as to when this may be fixed? Having same issue, checked user permissions, and also updated cli version to latest.

**Comment by steve-hb** [comment]
Same issue here using 4.41.2 with Aurora PostgreSQL Serverless.
Has someone a workaround maybe?

```
ec2-user:~/environment/test $ amplify api add-graphql-datasource
Using datasource: Aurora Serverless, provided by: awscloudformation
? Provide the region in which your cluster is located: eu-central-1
? Select the Aurora Serverless cluster that will be used as the data source for your API: amplify
⠹ Fetching Aurora Serverless cluster...BadRequestException: FATAL: password authentication failed for user "test"
    at Object.extractError (/home/ec2-user/.nvm/versions/node/v10.23.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.extractError (/home/ec2-user/.nvm/versions/node/v10.23.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/home/ec2-user/.nvm/versions/node/v10.23.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/ec2-user/.nvm/versions/node/v10.23.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/ec2-user/.nvm/versions/node/v10.23.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/home/ec2-user/.nvm/versions/node/v10.23.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/ec2-user/.nvm/versions/node/v10.23.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/ec2-user/.nvm/versions/node/v10.23.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/ec2-user/.nvm/versions/node/v10.23.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/ec2-user/.nvm/versions/node/v10.23.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:690:12)
There was an error adding the datasource
⠧ Fetching Aurora Serverless cluster...^Aborted!```

**Comment by cjihrig** [comment]
If you are encountering this error, please double check the values in the secret you created to access the Aurora cluster. Aurora Serverless v1 does not support IAM database authentication. From my own testing, the issue was solved by using the cluster's username and password (not any IAM credentials) in the secret.

**Comment by edwardfoyle** [comment]
This has been addressed in the latest version of the CLI
