### ISSUE TITLE
An error occurred when creating the CloudFormation stack

### ISSUE THREAD

**Issue by jonnyarc** [aws-amplify/amplify-cli#4446]
Running `amplify init` Cannot create backend services for Todo App.

**Amplify CLI Version**
4.21.1

john@Johns-MacBook-Pro Todo % amplify init
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the environment dev
? Choose your default editor: Visual Studio Code
Using default provider  awscloudformation

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html

? Do you want to use an AWS profile? Yes
? Please choose the profile you want to use default
Adding backend environment dev to AWS Amplify Console app: d319mnphggk2wl
⠦ Initializing project in the cloud...An error occurred when creating the CloudFormation stack
✖ Root stack creation failed
init failed
OptInRequired: The AWS Access Key Id needs a subscription for the service
    at Request.extractError (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'OptInRequired',
  time: 2020-06-03T04:00:12.425Z,
  requestId: 'addae551-527d-4637-a5ac-5a33a6ebc21c',
  statusCode: 403,
  retryable: false,
  retryDelay: 82.1490966768707
}

**Comment by ammarkarachi** [comment]
@jonnyarc What access have you granted to your user in IAM?

**Comment by jonnyarc** [comment]
the IAM user has `AdministratorAccess`

**Comment by ammarkarachi** [comment]
@jonnyarc Have you tried this [approach](https://aws.amazon.com/premiumsupport/knowledge-center/error-access-service/)?

**Comment by jonnyarc** [comment]
That worked. After upgrading the user:

If you're using an account that was created in or after 2011, then update your account status.
