### ISSUE TITLE
Cannot read property 'value' of undefined when calling amplify init

### ISSUE THREAD

**Issue by screendriver** [aws-amplify/amplify-cli#4484]
**Describe the bug**

I wanted to create my very first "Hello World" app in `AWS Amplify` but when I call `amplify init` I get following error when I have to choose the type of app I want to use:

```sh
❯ npx amplify init     
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the project amplifyplayground
? Enter a name for the environment dev
? Choose your default editor: Visual Studio Code
? Choose the type of app that you're building 
(node:19168) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'value' of undefined
    at ListPrompt.getCurrentValue (/Users/me/project/node_modules/inquirer/lib/prompts/list.js:121:
53)
    at MapSubscriber._next (/Users/me/project/node_modules/rxjs/internal/operators/map.js:49:35)
    at MapSubscriber.Subscriber.next (/Users/me/project/node_modules/rxjs/internal/Subscriber.js:66
:18)
    at TakeSubscriber._next (/Users/me/project/node_modules/rxjs/internal/operators/take.js:54:30)
    at TakeSubscriber.Subscriber.next (/Users/me/project/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Interface.handler (/Users/me/project/node_modules/rxjs/internal/observable/fromEvent.js:22:28)
    at Interface.emit (events.js:327:22)
    at Interface.EventEmitter.emit (domain.js:485:12)
    at Interface._onLine (readline.js:337:10)
    at Interface._line (readline.js:666:8)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:19168) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19168) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Amplify CLI Version**

`4.21.1`

**To Reproduce**

I did nothing except `amplify init`

**Expected behavior**

Should initialise my project.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.5
 - Node Version: 14.2.0

**Comment by screendriver** [comment]
I did it a second time now and I guess the main problem is that I **don't** get any list here:

```sh
❯ npx amplify init
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the project amplifyplayground
? Enter a name for the environment dev
? Choose your default editor: Visual Studio Code
? Choose the type of app that you're building (Use arrow keys)
```

So I can't choose anything. When I now hit `Enter` I get the error above because I did not select anything, which I can't because nothing is shown.

**Comment by screendriver** [comment]
I found out that here is already an issue about this: https://github.com/aws-amplify/amplify-cli/issues/839

Installing the amplify CLI globally is unfortunately a show stopper for me.
