### ISSUE TITLE
[request] better errors when `amplify pull` can't find an app

### ISSUE THREAD

**Issue by sw-yx** [aws-amplify/amplify-cli#4506]
**Is your feature request related to a problem? Please describe.**
when I accidentally `amplify pull` an app that is set up in the wrong region (I was in `us-east-2` in the amplify web UI, but on my machine i was on `us-east-1`), the CLI shows a scary/verbose/unfriendly error (though it does point to the potential problem):

```bash
$amplify pull --appId d230y0haao0jdh --envName devn

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html

? Do you want to use an AWS profile? Yes
? Please choose the profile you want to use default
Amplify AppID: d230y0haao0jdh not found. Please ensure your local profile matches the AWS account or region in which the Amplify app exists.
NotFoundException: App d230y0haao0jdh not found.
    at Object.extractError (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.extractError (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12) {
  code: 'NotFoundException',
  time: 2020-06-09T19:01:19.550Z,
  requestId: '93d7da80-28bc-46a1-933c-cc8beb7cc5a1',
  statusCode: 404,
  retryable: false,
  retryDelay: 18.489274248027133
}
Failed to pull the backend.
NotFoundException: App d230y0haao0jdh not found.
    at Object.extractError (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.extractError (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12) {
  code: 'NotFoundException',
  time: 2020-06-09T19:01:19.550Z,
  requestId: '93d7da80-28bc-46a1-933c-cc8beb7cc5a1',
  statusCode: 404,
  retryable: false,
  retryDelay: 18.489274248027133
}
```

this requires me to then try to figure out what region i'm in.

**Describe the solution you'd like**

1. since `NotFoundException: App d230y0haao0jdh not found.` is a known error, we don't have to show the rest of the error stack.
2. show which region we are currently in, for user convenience
3. tell user how to figure out where to check their app's region.

the user is extremely unlikely to get here by randomly mashing buttons to guess an AppID - if we are showing this error its likely a region mismatch issue. So let's help them figure it out.

**Additional context**

![image](https://user-images.githubusercontent.com/6764957/84189628-2211e280-aac8-11ea-9484-5e3ef14c7630.png)

**Comment by SwaySway** [comment]
Hello @sw-yx 
Thanks for this request. This is something we looking at as a whole within the CLI in regards to better error messaging. Will review this feedback with the team. Thanks

**Comment by michelem09** [comment]
I have similar problem:

```
$ amplify add hosting
? Select the plugin module to execute Hosting with Amplify Console (Managed hosting with custom domains, Continuous deployment)
App d3ckx997pvqncj not found.
NotFoundException: App d3ckx997pvqncj not found.
    at Object.extractError (/Users/michele/.nvm/versions/node/v12.16.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.extractError (/Users/michele/.nvm/versions/node/v12.16.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/Users/michele/.nvm/versions/node/v12.16.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/michele/.nvm/versions/node/v12.16.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/michele/.nvm/versions/node/v12.16.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/Users/michele/.nvm/versions/node/v12.16.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/michele/.nvm/versions/node/v12.16.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/michele/.nvm/versions/node/v12.16.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/michele/.nvm/versions/node/v12.16.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/michele/.nvm/versions/node/v12.16.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:690:12)
```

**Comment by vnrshere** [comment]
having same issue 
 Select the plugin module to execute Hosting with Amplify Console (Managed hosting with custom domains, Continuous deployment)
App d1kt4zv29irias not found.
NotFoundException: App d1kt4zv29irias not found. 

i removed hosting added it back

**Comment by josefaidt** [comment]
Using the latest version of the CLI at the time of writing (10.5.2), the error message does not include the stack trace however can still be improved with helpful guidance as to why this might be occurring 

```
➜  amplify pull --appId d230y0haao0jdh --envName devn
? Select the authentication method you want to use: AWS profile

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

? Please choose the profile you want to use default
🛑 App d230y0haao0jdh not found.

Resolution: Check that the region of the Amplify App is matching the configured region.
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

Session Identifier: a5a4060a-3b1d-4789-be8e-dad51a282dba
```

**Comment by josefaidt** [comment]
Closing issue 🙂

**Comment by kylekirkby** [comment]
Hi @josefaidt ,

This is still an issue. We've just tried pulling down an environment and we're greeted with the `App xxxxxxxxx not found.` issue.. There are no further details on how to proceed. Running `amplify configure` tries to create a new IAM user which is not what we want.

**Comment by josefaidt** [comment]
Hey @kylekirkby thanks for bringing this up! Would you mind filing a separate [bug report](https://github.com/aws-amplify/amplify-cli/issues/new/choose) for this occurrence? While it appears related I'd like to capture the up-to-date details to track alongside the latest release 🙂
