### ISSUE TITLE
Problems publishing App 

### ISSUE THREAD

**Issue by yhuber** [aws-amplify/amplify-cli#4663]
I am trying to publish my App. It used to work fine, until I updated my auth with social Provider (federation). Now i get this error message:

2020-06-23T08:11:07.616Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
2020-06-23T08:11:07.616Z [WARNING]: ✖ There was an error initializing your environment.
2020-06-23T08:11:07.616Z [INFO]: init failed
2020-06-23T08:11:07.617Z [INFO]: TypeError: Cannot read property 'Mappings' of undefined
                                 at collectTemplates (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/splitStack.js:78:36)
                                 at Object.splitStack [as default] (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/splitStack.js:208:20)
                                 at TransformFormatter.format (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/TransformFormatter.js:25:50)
                                 at GraphQLTransform.transform (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/GraphQLTransform.js:207:26)
                                 at _buildProject (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/amplifyUtils.js:56:37)
2020-06-23T08:11:07.629Z [ERROR]: !!! Build failed
2020-06-23T08:11:07.629Z [ERROR]: !!! Non-Zero Exit Code detected
2020-06-23T08:11:07.629Z [INFO]: # Starting environment caching...
2020-06-23T08:11:07.630Z [INFO]: # Environment caching completed

**Comment by akshbhu** [comment]
Hi @yhuber 

It seems that your #current-cloud backend folder is missing amplify-meta.json file from error. Would you be able to send a zip file of your amplify folder to amplify-cli@amazon.com?It seems the amplify folder got messed up while you  applying this fix :https://github.com/aws-amplify/amplify-cli/issues/3576#issuecomment-596732233

**Comment by yhuber** [comment]
Hey @akshbhu  thanks for your answer. 
I just sent the zip file via e-mail to amplify-cli@amazon.com

**Comment by yhuber** [comment]
Okay the issue ("no such file #current-cloud-backend/amplify-meta.json") was because i zipped the folder instead of the files in the order... That works now.. So I can now initialize my backend again. However, when i push to the Cloud the error "Cannot read property 'Mappings' of undefined" remains... I deleted all copied files in the S3-Bucket as well as in the amplify backend folder in my app.

The only files that appear to be twice are some resolver files which have the exact same name (without any number after it), but have a different data-size.... 

I sent an e-mail to amplify-cli@amazon.com  with the new ZIP of #current-cloud-backend.

**Comment by yhuber** [comment]
> The only files that appear to be twice are some resolver files which have the exact same name (without any number after it), but have a different data-size....

Nevermind.. the files are called ".req.vtl" and ".res.vtl", my mistake..

**Comment by akshbhu** [comment]
Hi @yhuber 

I did receive a mail containing a zip file for currentcloudbackend. But the zip file doesn't contain amplify resources folder like api and auth. it only has images of your directory. I need that information to reproduce this issue.

Can you try and send the zip file again which has above said data to amplify-cli@amazon.com.

**Comment by yhuber** [comment]
Okay i just sent it.
