### ISSUE TITLE
Can't Use Amplify with Sandbox Profile

### ISSUE THREAD

**Issue by akefirad** [aws-amplify/amplify-cli#4824]
I'm trying to pull an application from our sandbox account, but Amplify CLI can't find the application. The credential is configured as follow:
```
[amplify-production]
aws_access_key_id=<key-id>
aws_secret_access_key=<secret-key>

[amplify-sandbox]
role_arn=arn:aws:iam::<account-id>:role/<sandbox-role-with-admin-policy>
source_profile=amplify-production
```
I can confirm that the credentials are properly configured since `aws --profile amplify-sandbox amplify list-apps` command shows my application.  
Is this known or is it a bug?

**Comment by UnleashedMind** [comment]
@akefirad 
Could you take a screenshot of the error message?

**Comment by akefirad** [comment]
```
# amplify pull --appId xxxxxxxxxxxxx --envName master

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html

? Do you want to use an AWS profile? Yes
? Please choose the profile you want to use sandbox
Amplify AppID: xxxxxxxxxxxxx not found. Please ensure your local profile matches the AWS account or region in which the Amplify app exists.
NotFoundException: App d1aol018ovhodw not found.
    at Object.extractError (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.extractError (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:690:12) {
  code: 'NotFoundException',
  time: 2020-07-16T12:20:10.956Z,
  requestId: 'f4184a33-0cb6-4dc4-b937-3a55cf61892c',
  statusCode: 404,
  retryable: false,
  retryDelay: 55.81935220357188
}
Failed to pull the backend.
App xxxxxxxxxxxxx not found.
NotFoundException: App xxxxxxxxxxxxx not found.
    at Object.extractError (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.extractError (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:690:12)

# aws --profile sandbox amplify list-apps
{
    "apps": [
        {
            "appId": "xxxxxxxxxxxxx",
            "appArn": "arn:aws:amplify:eu-central-1:xxxxxxxxxxxxx:apps/xxxxxxxxxxxxx",
            "name": "myapp",
            "tags": {},
            "platform": "WEB",
            "createTime": "2020-07-13T14:48:30.194000+02:00",
            "updateTime": "2020-07-13T14:48:30.194000+02:00",
            "environmentVariables": {
                "_LIVE_PACKAGE_UPDATES": "[{\"pkg\":\"@aws-amplify/cli\",\"type\":\"npm\",\"version\":\"latest\"}]"
            },
            "defaultDomain": "xxxxxxxxxxxxx.amplifyapp.com",
            "enableBranchAutoBuild": false,
            "enableBasicAuth": false,
            "customRules": [],
            "enableAutoBranchCreation": false
        }
    ]
}
```

**Comment by RossWilliams** [comment]
I assume your environment variable $AWS_PROFILE is set to amplify-sandbox ? otherwise its going to use the credentials under [default]

**Comment by akefirad** [comment]
No env var is set. I explicitly set the profile for each command. (it's shown above.)

**Comment by RossWilliams** [comment]
You said you are running ``` amplify pull --appId xxxxxxxxxxxxx --envName master ```, no profile is specified, so the default profile is used.

**Comment by compa-hq** [comment]
This is the part of the whole log I posted above.
```
# amplify pull --appId xxxxxxxxxxxxx --envName master
...
? Do you want to use an AWS profile? Yes
? Please choose the profile you want to use amplify-sandbox
```

**Comment by akefirad** [comment]
This is the part of the whole log I posted above.
```
# amplify pull --appId xxxxxxxxxxxxx --envName master
...
? Do you want to use an AWS profile? Yes
? Please choose the profile you want to use amplify-sandbox
```

**Comment by akefirad** [comment]
BTW how can I set the profile in the command? `--profile` won't work.

**Comment by RossWilliams** [comment]
sorry i missed this in your pasted code.

> This is the part of the whole log I posted above.
> 
> ```
> # amplify pull --appId xxxxxxxxxxxxx --envName master
> ...
> ? Do you want to use an AWS profile? Yes
> ? Please choose the profile you want to use amplify-sandbox
> ```

Sorry I missed this in your initial response.

**Comment by UnleashedMind** [comment]
Do you have a `~/.aws/config` file? what is the region set there for the two profiles? are they `eu-central-1`?

**Comment by akefirad** [comment]
```
# cat .aws/config
[default]
region=eu-central-1

[profile administrator]
region=eu-central-1

[profile sandbox]
region=eu-central-1

[profile amplify-production]
region=eu-central-1

[profile amplify-sandbox]
region=eu-central-1
```

**Comment by UnleashedMind** [comment]
Please double check and make sure that that role has all the permissions as stated in this document: 

https://docs.amplify.aws/cli/usage/iam

ListApps and GetApp are different permissions

**Comment by akefirad** [comment]
```
# aws sts get-caller-identity --query 'Arn'
"arn:aws:sts::123456789012:assumed-role/SandboxAccountDeveloperRole/botocore-session-1595355677"

# aws iam list-attached-role-policies --role-name SandboxAccountDeveloperRole --query 'AttachedPolicies'
[
    {
        "PolicyName": "AdministratorAccess",
        "PolicyArn": "arn:aws:iam::aws:policy/AdministratorAccess"
    }
]
```

**Comment by akefirad** [comment]
Also `aws amplify get-app --app-id applicationid` returns the application details, meaning the permission is there.

**Comment by akefirad** [comment]
As a side note, if there's a permission issue, it would fail with a clear message:

> AccessDeniedException: User: arn:aws:iam::123456789012:user/user-name is not authorized to perform: amplify:GetBackendEnvironment on resource: arn:aws:amplify:eu-central-1:123456789012:apps/abcdefghijklm/backendenvironments/master

**Comment by akefirad** [comment]
OK, this is getting weirder. when the profile env var (`AWS_PROFILE`) is not set, trying to pull an application from production account (with sandbox profile selected interactively) fails with a permission error (like above). Should be OK, but the thing is the error message is saying `arn:aws:iam::123456789012:user/user-name` doesn't have the permission, which is wrong, since I'm running is with sandbox profile (assumed role) not the give user in the error message (default profile).  
This buggy behavior is consistent in the case when I set the profile env var to administrator and try to pull the application from the production account. It succeeds even if I select sandbox profile (which should have failed like the previous attempt).  
Can you please elaborate the effect of having the profile env var set AND selecting a profile interactively.

**Comment by UnleashedMind** [comment]
The setting for the role should be in the `~/.aws/config` file instead of the `~/.aws/credentials` file. 
See the following doc:
https://docs.amplify.aws/cli/usage/iam-roles-mfa#n3-set-up-the-local-development-environment-dev-corp

The `~/.aws/config` file should contain the following contents:

```
[default]
region=eu-central-1

[profile administrator]
region=eu-central-1

[profile sandbox]
region=eu-central-1

[profile amplify-production]
region=eu-central-1

[profile amplify-sandbox]
role_arn=arn:aws:iam::<account-id>:role/<sandbox-role-with-admin-policy>
source_profile=amplify-production
region=eu-central-1
```

remove the following content from the `~/.aws/credentials` file: 
```
 [amplify-sandbox]
role_arn=arn:aws:iam::<account-id>:role/<sandbox-role-with-admin-policy>
source_profile=amplify-production
```

**Comment by akefirad** [comment]
OK seems to be mis-configuration on my side. It's working with your comment applied. Sorry about the false alarm.
