### ISSUE TITLE
Error deleting an env, using the amplify env remove command

### ISSUE THREAD

**Issue by balmacefa** [aws-amplify/amplify-cli#4848]
**Describe the bug**
Error deleting an env, using the amplify env remove:
```
Error in deleting env:dev
Cannot read property 'BucketName' of undefined
× remove env failed: Cannot read property 'BucketName' of undefined
```

**Amplify CLI Version**
`4.24.1`

**To Reproduce**
I checkout to a new env, and try to delete the dev env using this command:
`amplify env remove dev`

This the output from the console:
```

? Are you sure you want to continue? This CANNOT be undone. (This would delete 'dev' environment of the project from the cloud) Yes
- Deleting resources from the cloud. This may take a few minutes...
Deleting env:dev
- Deleting resources from the cloud. This may take a few minutes...
Error in deleting env:dev
Cannot read property 'BucketName' of undefined
× remove env failed: Cannot read property 'BucketName' of undefined
Cannot read property 'BucketName' of undefined
TypeError: Cannot read property 'BucketName' of undefined
    at getStorageBucket (C:\Users\fabia\AppData\Roaming\nvm\v12.17.0\node_modules\@aws-amplify\cli\node_modules\amplify-provider-awscloudformation\lib\delete-env.js:41:39)
    at Object.run (C:\Users\fabia\AppData\Roaming\nvm\v12.17.0\node_modules\@aws-amplify\cli\node_modules\amplify-provider-awscloudformation\lib\delete-env.js:21:29)
    at async Promise.all (index 0)
    at AmplifyToolkit.removeEnvFromCloud [as _removeEnvFromCloud] (C:\Users\fabia\AppData\Roaming\nvm\v12.17.0\node_modules\@aws-amplify\cli\src\extensions\amplify-helpers\remove-env-from-cloud.js:18:5)
    at Object.run (C:\Users\fabia\AppData\Roaming\nvm\v12.17.0\node_modules\@aws-amplify\cli\src\commands\env\remove.js:43:11)
    at Object.run (C:\Users\fabia\AppData\Roaming\nvm\v12.17.0\node_modules\@aws-amplify\cli\src\commands\env.js:27:9)
    at Object.executeAmplifyCommand (C:\Users\fabia\AppData\Roaming\nvm\v12.17.0\node_modules\@aws-amplify\cli\src\index.ts:138:3)
    at executePluginModuleCommand (C:\Users\fabia\AppData\Roaming\nvm\v12.17.0\node_modules\@aws-amplify\cli\src\execution-manager.ts:158:7)
    at Object.executeCommand (C:\Users\fabia\AppData\Roaming\nvm\v12.17.0\node_modules\@aws-amplify\cli\src\execution-manager.ts:24:5)
    at Object.run (C:\Users\fabia\AppData\Roaming\nvm\v12.17.0\node_modules\@aws-amplify\cli\src\index.ts:61:5)

```

**Expected behavior**
Delete the env from the cloud.

**Desktop (please complete the following information):**
 - Windows
 - Node Version. `v12.17.0`

**Comment by UnleashedMind** [comment]
I've reproduce the issue if there is storage resource that's in the `Create` status. 
To unblock your work, you can remove the storage resource in the env to be deleted by `amplify storage remove`, and then checkout to another env to delete the dev to be deleted.
We are working on a fix soon.

**Comment by balmacefa** [comment]
I still have the same error after using `amplify storage remove`

output -amplify storage remove:
```
No resources added for this category
```

**Comment by UnleashedMind** [comment]
did you run the ` amplify storage remove` in the `dev` env? 
No the env that you are running the command to remove `dev`

**Comment by balmacefa** [comment]
Yes, I checkout to `dev` and run `amplify storage remove`

**Comment by UnleashedMind** [comment]
in the `dev` env, go to the `amplify/#current-cloud-backend` folder, find the amplify-meta.json file, is there a storage resource with service "S3"? does it contain "output" field? and in the "output", is there a "BucketName"?

**Comment by balmacefa** [comment]
I have not modified any files in `#current-cloud-backend`.
This is what's inside `amplify-meta.json`:

```
"storage": {
    "s3a863611a": {
      "service": "S3",
      "providerPlugin": "awscloudformation",
      "dependsOn": [
        {
          "category": "function",
          "resourceName": "S3Trigger9028c8d9",
          "attributes": [
            "Name",
            "Arn",
            "LambdaExecutionRole"
          ]
        }
      ]
    }
  }
```

**Comment by UnleashedMind** [comment]
I'm not able to reproduce this issue anymore with the latest CLI version. 
Please let us know if you are still blocked.
