### ISSUE TITLE
TypeError: Cannot redefine property: ______ on amplify push

### ISSUE THREAD

**Issue by mruzekw** [aws-amplify/amplify-cli#4860]
**Describe the bug**

CLI seems to throw error at start of operation.

Some variant of:
```
TypeError: Cannot redefine property: zathom
```

My guess is that this refers to the AWS profile I'm using (and have used for several months).

Call stacks are here:

```zathom on  development [⇡$?] is 📦 v0.1.0 via ⬢ v12.12.0 took 3s
➜ amplify init
Note: It is recommended to run this command from the root of your app directory
? Do you want to use an existing environment? Yes
? Choose the environment you would like to use: willm
Using default provider  awscloudformation
✖ There was an error initializing your environment.
init failed
TypeError: Cannot redefine property: zathom
    at Function.defineProperty (<anonymous>)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/shared-ini/ini-loader.js:11:14
    at Array.forEach (<anonymous>)
    at IniLoader.parseFile (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/shared-ini/ini-loader.js:8:26)
    at IniLoader.loadFrom (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/shared-ini/ini-loader.js:56:30)
    at Config.region (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/node_loader.js:100:36)
    at Config.set (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js:514:39)
    at Config.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js:349:12)
    at Config.each (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/util.js:507:32)
    at new Config (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js:348:19)

zathom on  development [⇡$!?] is 📦 v0.1.0 via ⬢ v12.12.0 took 9s
➜ amplify env pull
✖ There was an error initializing your environment.
Cannot redefine property: zathom
TypeError: Cannot redefine property: zathom
    at Function.defineProperty (<anonymous>)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/shared-ini/ini-loader.js:11:14
    at Array.forEach (<anonymous>)
    at IniLoader.parseFile (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/shared-ini/ini-loader.js:8:26)
    at IniLoader.loadFrom (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/shared-ini/ini-loader.js:56:30)
    at Config.region (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/node_loader.js:100:36)
    at Config.set (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js:514:39)
    at Config.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js:349:12)
    at Config.each (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/util.js:507:32)
    at new Config (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js:348:19)
```

**Amplify CLI Version**

4.24.2

**To Reproduce**

I don't know the exact circumstances. It was working yesterday.

`amplify push -y`

**Expected behavior**

It pushes with no Amplify CLI error.

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: v12.12.0

**Comment by UnleashedMind** [comment]
Have you recently updated or removed these two files: `~/.aws/config` and `~/.aws/credentials`

**Comment by mruzekw** [comment]
I opened and saved them, but to my knowledge I didn’t change either of them.

I’ll play around with those.

**Comment by mruzekw** [comment]
Alright! It looks like I ended up with a duplicate profile somehow.

I deleted that, and I'm back up and running.

Thanks for the tip!
