### ISSUE TITLE
Cannot remove environment when resources no longer exist on cloud

### ISSUE THREAD

**Issue by krikork** [aws-amplify/amplify-cli#4871]
If I try to delete an environment for which the cloud resources have already been removed I get the following error and the environment is not removed from my local machine.

$ amplify env remove sandybox
? Are you sure you want to continue? This CANNOT be undone. (This would delete 'sandybox' environment of the project from the cloud) Yes
⠋ Deleting resources from the cloud. This may take a few minutes...
Deleting env:sandybox
⠏ Deleting resources from the cloud. This may take a few minutes...Unable to remove env: sandybox because deployment bucket amplify-core-sandybox-231856-deployment does not exist or has been deleted.
⠇ Deleting resources from the cloud. This may take a few minutes...Stack has already been deleted or does not exist
⠴ Deleting resources from the cloud. This may take a few minutes...
Error in deleting env:sandybox
App d36k5aveww5atu not found.
✖ remove env failed: App d36k5aveww5atu not found.
App d36k5aveww5atu not found.
NotFoundException: App d36k5aveww5atu not found.
    at Object.extractError (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.extractError (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:690:12)

**Comment by egyangel** [comment]
+1

**Comment by UnleashedMind** [comment]
The Amplify CLI uses AWS CloudFormation to manages it aws resources, if you manually delete the resources created by the AWS CloudFormation, it will complain when it is instruct to delete it. 
It's hard to recover, and since you are trying to remove all the resources, you might as well just manually remove all of them, then manually remove the stacks for the project in CloudFormation.

**Comment by nikhname** [comment]
@krikork Close due to lack of response, feel free to comment if there are further questions

**Comment by krikork** [comment]
Hi @UnleashedMind, all resources were removed through the AWS console using cloud formation, not manually. The CLI was still clueless about that.
