### ISSUE TITLE
CLI spewing errors about not being able to contact 52.95.18.70

### ISSUE THREAD

**Issue by jpignata** [aws-amplify/amplify-cli#4879]
**Describe the bug**
During an `amplify init` run this morning, I received very confusing errors that seemed unrelated to the operation I was running. Upon digging, it appears 52.95.18.70 is cloudformation.us-east-2.amazonaws.com, and I was unable to connect to it during the operation. The init operation appeared to succeed, even though the stack was not created.

**Amplify CLI Version**
4.24.3

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable

```console
$ amplify init
Scanning for plugins...
Plugin scan successful
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the project predictions
? Enter a name for the environment dev
? Choose your default editor: Visual Studio Code
? Choose the type of app that you're building android
Please tell us about your project
? Where is your Res directory:  app/src/main/res
Using default provider  awscloudformation

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html

? Do you want to use an AWS profile? Yes
? Please choose the profile you want to use pignataj+sdkintegration-Administrato
r
Adding backend environment dev to AWS Amplify Console app: d2hz7d4vbxccmm
⠋ Initializing project in the cloud...

CREATE_IN_PROGRESS DeploymentBucket              AWS::S3::Bucket            Mon Jul 20 2020 08:20:12 GMT-0400 (Eastern Daylight Time) Resource creation Initiated
CREATE_IN_PROGRESS AuthRole                      AWS::IAM::Role             Mon Jul 20 2020 08:20:12 GMT-0400 (Eastern Daylight Time) Resource creation Initiated
CREATE_IN_PROGRESS UnauthRole                    AWS::IAM::Role             Mon Jul 20 2020 08:20:12 GMT-0400 (Eastern Daylight Time) Resource creation Initiated
CREATE_IN_PROGRESS AuthRole                      AWS::IAM::Role             Mon Jul 20 2020 08:20:12 GMT-0400 (Eastern Daylight Time)
CREATE_IN_PROGRESS UnauthRole                    AWS::IAM::Role             Mon Jul 20 2020 08:20:12 GMT-0400 (Eastern Daylight Time)
CREATE_IN_PROGRESS DeploymentBucket              AWS::S3::Bucket            Mon Jul 20 2020 08:20:12 GMT-0400 (Eastern Daylight Time)
CREATE_IN_PROGRESS amplify-predictions-dev-81733 AWS::CloudFormation::Stack Mon Jul 20 2020 08:20:09 GMT-0400 (Eastern Daylight Time) User Initiated
⠙ Initializing project in the cloud...

CREATE_COMPLETE AuthRole   AWS::IAM::Role Mon Jul 20 2020 08:20:27 GMT-0400 (Eastern Daylight Time)
CREATE_COMPLETE UnauthRole AWS::IAM::Role Mon Jul 20 2020 08:20:27 GMT-0400 (Eastern Daylight Time)
⠙ Initializing project in the cloud...

CREATE_COMPLETE amplify-predictions-dev-81733 AWS::CloudFormation::Stack Mon Jul 20 2020 08:20:35 GMT-0400 (Eastern Daylight Time)
CREATE_COMPLETE DeploymentBucket              AWS::S3::Bucket            Mon Jul 20 2020 08:20:33 GMT-0400 (Eastern Daylight Time)
⠸ Initializing project in the cloud...TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at getUniqueStacksEvents (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js:481:24)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js:128:30
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:34542) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT 52.95.18.70:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1142:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:34542) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:34542) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✔ Successfully created initial AWS cloud resources for deployments.
✔ Initialized provider successfully.
Initialized your environment successfully.

Your project has been successfully initialized and connected to the cloud!

Some next steps:
"amplify status" will show you what you've added already and if it's locally configured or deployed
"amplify add <category>" will allow you to add features like user login or a backend API
"amplify push" will build all your local backend resources and provision it in the cloud
"amplify console" to open the Amplify Console and view your project status
"amplify publish" will build all your local backend and frontend resources (if you have hosting category added) and provision it in the cloud

Pro tip:
Try "amplify add api" to create a backend API and then "amplify publish" to deploy everything

TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at getUniqueStacksEvents (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js:481:24)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js:128:30
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:34542) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT 52.95.18.70:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1142:16)
(node:34542) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
```

**Expected behavior**
Less error output, or, clearer error output (to wit: could not create stack, please check your internet connectivity.)

**Screenshots**
Nope.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4
 - Node Version: Node.js 14.2.0

**Additional context**
Nope.

**Comment by cjihrig** [comment]
I believe the underlying issue was fixed in https://github.com/aws-amplify/amplify-cli/pull/7121. If this is still occurring, please let us know.
