### ISSUE TITLE
Expired token causes cli to hang forever

### ISSUE THREAD

**Issue by mulvaney** [aws-amplify/amplify-cli#4880]
_>**Note**:_ If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
Running an amplify command line with an expired AWS login causes the client to hang forever.

**Amplify CLI Version**
4.24.3

**To Reproduce**
I use saml2aws to login to AWS. After logging in, wait a while for the token to expire (in my case it seems to happen at least once every 2 hours, somewhat randomly.) Then run a command like  'amplify push'. You get a message that the token is expired, but then the command continues and blocks on the "Fetching updates..." step forever, requiring a kill -9 from a separate terminal.

**Expected behavior**
The client should stop after the ExpiredToken error

**Screenshots**
```
$ amplify push -y
Scanning for plugins...
Plugin scan successful
⠏ Fetching updates to backend environment: devdev from the cloud.(node:46651) UnhandledPromiseRejectionWarning: ExpiredToken: The provided token has expired.
    at Request.extractError (/Users/mm5830/.nvm/versions/node/v12.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/services/s3.js:831:35)
    at Request.callListeners (/Users/mm5830/.nvm/versions/node/v12.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/mm5830/.nvm/versions/node/v12.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/mm5830/.nvm/versions/node/v12.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/Users/mm5830/.nvm/versions/node/v12.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/mm5830/.nvm/versions/node/v12.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/mm5830/.nvm/versions/node/v12.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/mm5830/.nvm/versions/node/v12.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/mm5830/.nvm/versions/node/v12.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/Users/mm5830/.nvm/versions/node/v12.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
(node:46651) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:46651) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠧ Fetching updates to backend environment: devdev from the cloud.
```
**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Node: v12.18.1

**Additional context**

**Comment by pkreipke** [comment]
I've just run into the same issue. Was advised on Discord to add my info to this ticket. Happy to help test or color in more info if there's some debug flag etc that could help.

Amplify v4.31.1, MacOS 10.15.6, Node v14.8.0

I think I got the same stack frames as @mulvaney (did you ever get around the problem).

```
⠇ Fetching updates to backend environment: dev from the cloud.(node:3869) UnhandledPromiseRejectionWarning: ExpiredToken: The provided token has expired.
    at Request.extractError (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/services/s3.js:700:35)
    at Request.callListeners (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3869) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3869) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠧ Fetching updates to backend environment: dev from the cloud.Terminated: 15
```

**Comment by pkreipke** [comment]
Update: in `~/.aws/credentials` I found that there was an entry in the relevant profile the session token under `aws_session_token=...`. After removing that, the error went away and I'm facing a different issue - the access key or secret aren't correct perhaps.

I'm sorry that I didn't remember futzing with those settings. Thanks for looking into it.

**Comment by jamesonwilliams** [comment]
There is another similar way to hang the CLI. If you don't have any credentials at all (distinct from having expired ones.)

```console
$ amplify push
⠹ Fetching updates to backend environment: dev from the cloud.(node:35332) UnhandledPromiseRejectionWarning: CredentialsError: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/util.js:899:34)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:35332) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:35332) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠙ Fetching updates to backend environment: dev from the cloud.
⠸ Fetching updates to backend environment: dev from the cloud.
⠼ Fetching updates to backend environment: dev from the cloud.
⠦ Fetching updates to backend environment: dev from the cloud.
⠋ Fetching updates to backend environment: dev from the cloud.
⠹ Fetching updates to backend environment: dev from the cloud.
⠸ Fetching updates to backend environment: dev from the cloud.
⠴ Fetching updates to backend environment: dev from the cloud.
```

Note: the cause in my case is:
> CredentialsError: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1

Whereas @mulvaney's cause was:
> UnhandledPromiseRejectionWarning: ExpiredToken: The provided token has expired.

In either case, the CLI stops responding. More irksome, the interrupt (Ctrl-C) character is disrespected, so __I can't get out of the CLI__, one it enters this state. I have to `kill -9` the process, from another window.
