### ISSUE TITLE
`amplify configure` was failed.

### ISSUE THREAD

**Issue by saintsouth** [aws-amplify/amplify-cli#4890]
**Page**: [`/start/q/integration/angular`](https://docs.amplify.aws/start/q/integration/angular)

**Feedback**:

I tried new amplify project "tutorial".
I read this page, and execute `amplify configure`, but it was failed.

Error on my console.
```
Cannot read property 'v4' of undefined
TypeError: Cannot read property 'v4' of undefined
    at new UsageDataConfig (/home/user/tutorial/node_modules/@aws-amplify/cli/lib/app-config/config.js:52:48)
    at new Config (/home/user/tutorial/node_modules/@aws-amplify/cli/lib/app-config/config.js:38:32)
    at Function.get Instance [as Instance] (/home/user/tutorial/node_modules/@aws-amplify/cli/lib/app-config/config.js:42:29)
    at Object.init (/home/user/tutorial/node_modules/@aws-amplify/cli/lib/app-config/config.js:23:27)
    at Object.attachUsageData (/home/user/tutorial/node_modules/@aws-amplify/cli/lib/context-manager.js:16:33)
    at Object.run (/home/user/tutorial/node_modules/@aws-amplify/cli/lib/index.js:68:33)
```

My environment.
```
$ node -v
v12.18.2
$ npm -v
6.14.5
```

**Comment by nikhname** [comment]
@saintsouth do you still see the `Cannot read property 'v4' of undefined` error when using the latest CLI (4.24.3)

**Comment by saintsouth** [comment]
Thank you for reply. I found something.

Start on clean npm environment with `npm init` for each.
1. `npn install @aws-amplify/cli` first, and execute `amplify configure`, is successful.
2. But, `npm install @angular/cli` first, then `npm install @aws-amplify/cli`, appear this problem.
3. `npm install @aws-amplify/cli` first, then `npm install @angular/cli`, is successful.

Each `amplify configure` show me following message.
```
Scanning for plugins...
The following official plugins are missing or inactive:
    awscloudformation: provider | amplify-provider-awscloudformation@4.23.0
    analytics: category | amplify-category-analytics@2.17.6
    api: category | amplify-category-api@2.21.0
    auth: category | amplify-category-auth@2.17.0
    function: category | amplify-category-function@2.22.0
    hosting: category | amplify-category-hosting@undefined
    hosting: category | amplify-console-hosting@undefined
    interactions: category | amplify-category-interactions@2.4.6
    notifications: category | amplify-category-notifications@2.15.15
    predictions: category | amplify-category-predictions@2.4.6
    storage: category | amplify-category-storage@2.6.0
    xr: category | amplify-category-xr@2.4.6
    codegen: util | amplify-codegen@2.15.14
    android: frontend | amplify-frontend-android@2.13.4
    ios: frontend | amplify-frontend-ios@2.13.7
    javascript: frontend | amplify-frontend-javascript@2.15.4
    mock: util | amplify-util-mock@3.23.0
Plugin scan successful
```

**Comment by saintsouth** [comment]
Memo: I don't like installing npm packages in the global environment, so I've added `./node_modules/.bin` to my PATH so I can run it locally.

**Comment by nikhname** [comment]
@saintsouth We don't support local installation of the CLI at this time, the package must be installed globally to avoid this issue. Please comment if you have further questions.
