### ISSUE TITLE
Missing required key "appId" in params when running hosting add

### ISSUE THREAD

**Issue by Adonais0** [aws-amplify/amplify-cli#4918]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

I'm trying to deploy my nextjs app to amplify following the steps here https://www.youtube.com/watch?v=7VDdgKXAAP0,  but stuck with `Missing required key 'appId' in params` error when runing `amplify hosting add`. I've tried to `amplify init --appId <ID>` but doesn't resolve the error

`
Missing required key 'appId' in params
MissingRequiredParameter: Missing required key 'appId' in params
    at ParamValidator.fail (/Users/chuyao/.nvm/versions/node/v12.16.2/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/param_validator.js:50:37)
    at ParamValidator.validateStructure (/Users/chuyao/.nvm/versions/node/v12.16.2/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/param_validator.js:61:14)
    at ParamValidator.validateMember (/Users/chuyao/.nvm/versions/node/v12.16.2/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/param_validator.js:88:21)
    at ParamValidator.validate (/Users/chuyao/.nvm/versions/node/v12.16.2/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (/Users/chuyao/.nvm/versions/node/v12.16.2/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/event_listeners.js:126:42)
    at Request.callListeners (/Users/chuyao/.nvm/versions/node/v12.16.2/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at callNextListener (/Users/chuyao/.nvm/versions/node/v12.16.2/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at /Users/chuyao/.nvm/versions/node/v12.16.2/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/event_listeners.js:86:9
    at finish (/Users/chuyao/.nvm/versions/node/v12.16.2/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js:386:7)
    at /Users/chuyao/.nvm/versions/node/v12.16.2/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js:404:9
`
**Which Category is your question related to?**

**Amplify CLI Version** 
4.24.3

You can use `amplify -v` to check the amplify cli version on your system

**What AWS Services are you utilizing?**

**Provide additional details e.g. code snippets**

**Comment by nikhname** [comment]
@Adonais0 I was able to reproduce this with `amplify hosting add` but not after `amplify init --appId <ID>`. What error do you see in the latter case?

**Comment by rosmu** [comment]
Experienced same issue while adding hosting with `amplify add hosting`. The issue was that my account hit the max no.of app in a region. After deleting an app from the console I did a force push `amplify push --force` and I was able to add hosting after that.
