### ISSUE TITLE
`amplify console` command for auth returns error

### ISSUE THREAD

**Issue by rohandubal** [aws-amplify/amplify-cli#494]
**Describe the bug**
`amplify console` for `auth` returns the following error:

```bash
amplify console
? Please select the category or provider auth
/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/index.js:13
    throw up;
    ^

TypeError: plugin.console is not a function
    at Command.run (/usr/local/lib/node_modules/@aws-amplify/cli/src/commands/console.js:20:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by kaustavghosh06** [comment]
Console option for auth is not available yet, but we’ll provide a fix for better the error message.

**Comment by kaustavghosh06** [comment]
PR for this is submitted and approved -> #632
