### ISSUE TITLE
Adding @auth directive breaks amplify push

### ISSUE THREAD

**Issue by apiel51** [aws-amplify/amplify-cli#4944]
**Describe the bug**
Whenever I add `@auth` to one of my API models, I get a `Cannot read property 'fields' of undefined` exception when running `amplify push`. I do have Cognito authentication set up with my app and that works fine.

**Amplify CLI Version**
4.22.0

**To Reproduce**
Adding `@auth` to this model gives me the error:
```graphql
type UserAccount
  @model
  @key(
    name: "accountsByUser"
    fields: ["cognitoUserID"]
    queryField: "accountsByUser"
  )
  @auth(rules: [{ allow: owner }]) {
  id: ID!
  cognitoUserID: String!
  institutionName: String!
  institutionID: String!
  accessKey: String!
}
```

**Expected behavior**
Expected `@auth` to work fine.

**Screenshots**
```
 Cannot read property 'fields' of undefined
An error occurred during the push operation: Cannot read property 'fields' of undefined
```

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: 14.2

**Additional context**

**Comment by LukeShay** [comment]
@apiel51 You are missing some commas. 
```
@key(
    name: "accountsByUser"
    fields: ["cognitoUserID"]
    queryField: "accountsByUser"
  )
```

should be 

```
@key(
    name: "accountsByUser",
    fields: ["cognitoUserID"],
    queryField: "accountsByUser",
  )
```

**Comment by apiel51** [comment]
@LukeShay Actually the commas don't do anything. Added them and does not fix the problem 😕

**Comment by apiel51** [comment]
Did some more digging, looks like the error is coming from this function:
```javascript
addSubscriptionOwnerArgument(ctx, resolver, ownerRules, makeNonNull = false) {
        let subscription = ctx.getSubscription();
        let createField = subscription.fields.find(field => field.name.value === resolver.Properties.FieldName);
        const nameNode = makeNonNull ? graphql_transformer_common_1.makeNonNullType(graphql_transformer_common_1.makeNamedType('String')) : graphql_transformer_common_1.makeNamedType('String');
        const ownerArgumentList = ownerRules.map(rule => {
            return graphql_transformer_common_1.makeInputValueDefinition(rule.ownerField || constants_1.DEFAULT_OWNER_FIELD, nameNode);
        });
        createField = {
            ...createField,
            arguments: ownerArgumentList,
        };
        subscription = {
            ...subscription,
            fields: subscription.fields.map(field => (field.name.value === resolver.Properties.FieldName ? createField : field)),
        };
        ctx.putType(subscription);
    }
```

Here's the stacktrace:
```
Cannot read property 'fields' of undefined
TypeError: Cannot read property 'fields' of undefined
    at ModelAuthTransformer.addSubscriptionOwnerArgument (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-auth-transformer/src/ModelAuthTransformer.ts:1885:57)
    at ModelAuthTransformer.addSubscriptionResolvers (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-auth-transformer/src/ModelAuthTransformer.ts:1871:16)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-auth-transformer/src/ModelAuthTransformer.ts:1745:14
    at Array.forEach (<anonymous>)
    at ModelAuthTransformer.protectOnCreateSubscription (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-auth-transformer/src/ModelAuthTransformer.ts:1744:13)
    at ModelAuthTransformer.object (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-auth-transformer/src/ModelAuthTransformer.ts:418:12)
    at GraphQLTransform.transformObject (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/GraphQLTransform.ts:340:25)
    at GraphQLTransform.transform (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/GraphQLTransform.ts:266:18)
    at _buildProject (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/util/amplifyUtils.ts:63:35)
    at ensureMissingStackMappings (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/util/amplifyUtils.ts:137:23)
```

**Comment by bever1337** [comment]
I am experiencing the same bug. `amplify push`, `amplify update`, and `amplify gql-compile` all produce the same error. `amplify update` prints the stack trace:

```
TypeError: Cannot read property 'fields' of undefined
    at ModelAuthTransformer.addSubscriptionOwnerArgument (/Users/username/.nvm/versions/node/v12.4.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-auth-transformer/src/ModelAuthTransformer.ts:1906:57)
    at ModelAuthTransformer.addSubscriptionResolvers (/Users/username/.nvm/versions/node/v12.4.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-auth-transformer/src/ModelAuthTransformer.ts:1892:16)
    at /Users/username/.nvm/versions/node/v12.4.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-auth-transformer/src/ModelAuthTransformer.ts:1763:14
    at Array.forEach (<anonymous>)
    at ModelAuthTransformer.protectOnCreateSubscription (/Users/username/.nvm/versions/node/v12.4.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-auth-transformer/src/ModelAuthTransformer.ts:1762:13)
    at ModelAuthTransformer.object (/Users/username/.nvm/versions/node/v12.4.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-auth-transformer/src/ModelAuthTransformer.ts:421:12)
    at GraphQLTransform.transformObject (/Users/username/.nvm/versions/node/v12.4.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/GraphQLTransform.ts:340:25)
    at GraphQLTransform.transform (/Users/username/.nvm/versions/node/v12.4.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/GraphQLTransform.ts:266:18)
    at _buildProject (/Users/username/.nvm/versions/node/v12.4.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/util/amplifyUtils.ts:63:35)
    at ensureMissingStackMappings (/Users/username/.nvm/versions/node/v12.4.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/util/amplifyUtils.ts:137:23)
```

```
➜  foo git:(master) ✗ node --version
v12.4.0
➜  foo git:(master) ✗ npm --version
6.9.0
➜  foo git:(master) ✗ amplify --version
4.29.1
```

OS: macOS Catalina

```
type Player @model @auth(rules: [{ allow: owner }]) {
  name: ID!
}

type Query {
  player(name: ID!): Player
}

type Mutation {
  newPlayer(name: ID!): Player
}

schema {
  query: Query
  mutation: Mutation
}
```

**Comment by attilah** [comment]
@apiel51 I was not able to reproduce the issue with the provided schema, but thanks for the details that helped to locate the issue and you are right, the root cause is that `subscription` is not part of the `schema` element which can happen as in @bever1337 's case when `schema` is manually defined, now I'm making a fix for @bever1337 's case so it will add `subscription` member even if `schema` is manually defined but does not have the `subscription` operations type added.

@apiel51 could you provide some more details, do you have `schema` in your schema file defined? I want to make sure that we're covering the grounds, but based on the stacktrace my fix will cover it. If after PR merge and release you can still reproduce it, feel free to reopen the issue.
