### ISSUE TITLE
Custom CustomMessageConfirmationBucket S3 BucketName: Unable to upload trigger files to S3

### ISSUE THREAD

**Issue by mbecker** [aws-amplify/amplify-cli#4958]
**Describe the bug**
The idea is to use "amplify auth" with a custom message confirmation cognito / lamda trigger with a static S3 bucket to verify the user's email. The S3 Bucket URL should not be used in the email to verify the address; a custom domain URL from Route53 should be used for the public link.
Because of the Route53 alias for record sets the S3 bucket name must be exact the name of the sub-/domain in Route53.

With the current templates it's not possible to use a custom S3 Bucketname with the format like: "activation.mydomain.com" or "activation-dev.mydomain.com"

Modifying the the S3 Bucket cloudformation template as follows:
```yaml
File: amplify\backend\auth\xxx\xxx-cloudformation-template.yml


Line: 153
BucketName:  !If [ShouldNotCreateEnvResources, !Ref verificationBucketName, !Join ['',[!Ref verificationBucketName, '-', !Ref env]]]

To:
BucketName:  !If [ShouldNotCreateEnvResources, !Ref verificationBucketName, !Join ['',[!Ref verificationBucketName, '-', !Ref env, '.mydomain.com']]]
```
results in the following error

```sh
/ Uploading files...e AccessDenied: Access Denied
    at Request.extractError (C:\Users\matsb\AppData\Local\nvm\v12.18.0\node_modules\@aws-amplify\cli\node_modules\awsices\s3.js:831:35)
    at Request.callListeners (C:\Users\matsb\AppData\Local\nvm\v12.18.0\node_modules\@aws-amplify\cli\node_modules\awuential_executor.js:106:20)
    at Request.emit (C:\Users\matsb\AppData\Local\nvm\v12.18.0\node_modules\@aws-amplify\cli\node_modules\aws-sdk\libxecutor.js:78:10)
    at Request.emit (C:\Users\matsb\AppData\Local\nvm\v12.18.0\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib88:14)
    at Request.transition (C:\Users\matsb\AppData\Local\nvm\v12.18.0\node_modules\@aws-amplify\cli\node_modules\aws-st.js:22:10)
    at AcceptorStateMachine.runTo (C:\Users\matsb\AppData\Local\nvm\v12.18.0\node_modules\@aws-amplify\cli\node_modulb\state_machine.js:14:12)
    at C:\Users\matsb\AppData\Local\nvm\v12.18.0\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\state_machine
    at Request.<anonymous> (C:\Users\matsb\AppData\Local\nvm\v12.18.0\node_modules\@aws-amplify\cli\node_modules\aws-st.js:38:9)
    at Request.<anonymous> (C:\Users\matsb\AppData\Local\nvm\v12.18.0\node_modules\@aws-amplify\cli\node_modules\aws-st.js:690:12)
    at Request.callListeners (C:\Users\matsb\AppData\Local\nvm\v12.18.0\node_modules\@aws-amplify\cli\node_modules\awuential_executor.js:116:18) {
  code: 'AccessDenied',
  region: null,
  time: 2020-07-28T17:13:10.444Z,
  requestId: 'E3ACB97C974422C2',
  extendedRequestId: 'mHOWmRkW79X4g/KCxp7gZ5brVITrGcFPA6x1mxJORUo/ODKgdR2CjVtUt0sjvbDHy6tmAaAuDEs=',
  cfId: undefined,
  statusCode: 403,
  retryable: false,
  retryDelay: 24.62336353591641
}
× Error has occurred during file upload.
AccessDenied: Access Denied
    at Request.extractError (C:\Users\matsb\AppData\Local\nvm\v12.18.0\node_modules\@aws-amplify\cli\node_modules\awsices\s3.js:831:35)
    at Request.callListeners (C:\Users\matsb\AppData\Local\nvm\v12.18.0\node_modules\@aws-amplify\cli\node_modules\awuential_executor.js:106:20)
    at Request.emit (C:\Users\matsb\AppData\Local\nvm\v12.18.0\node_modules\@aws-amplify\cli\node_modules\aws-sdk\libxecutor.js:78:10)
    at Request.emit (C:\Users\matsb\AppData\Local\nvm\v12.18.0\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib88:14)
    at Request.transition (C:\Users\matsb\AppData\Local\nvm\v12.18.0\node_modules\@aws-amplify\cli\node_modules\aws-st.js:22:10)
b\state_machine.js:14:12)
    at C:\Users\matsb\AppData\Local\nvm\v12.18.0\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\state_machine
    at Request.<anonymous> (C:\Users\matsb\AppData\Local\nvm\v12.18.0\node_modules\@aws-amplify\cli\node_modules\aws-st.js:38:9)
    at Request.<anonymous> (C:\Users\matsb\AppData\Local\nvm\v12.18.0\node_modules\@aws-amplify\cli\node_modules\aws-st.js:690:12)
    at Request.callListeners (C:\Users\matsb\AppData\Local\nvm\v12.18.0\node_modules\@aws-amplify\cli\node_modules\awuential_executor.js:116:18)
× An error occurred when pushing the resources to the cloud

Unable to upload trigger files to S3
An error occurred during the push operation: Unable to upload trigger files to S3
```

**Amplify CLI Version**
4.24.3

**To Reproduce**
(1) Add a Custom Message Confirmation cognnito / lambda trigger function with a statis S§ bucket
(2) Try to create a Route53 domain for that S3 Bucket or modify the file as stated above
(3) Push

**Expected behavior**
Modifying only the line 153 in the file "amplify\backend\auth\xxx\xxx-cloudformation-template.yml" should not result in the error. The new S3 BucketName should be used to upload the files. The amplify name should not be generated in any upload scripts.

Feature request:
- Add custom domains / names for S3 Buckets to have a valid public redirect in Route53.
- Add a readme how to have a public (nice) URL for email verification

**Additional context**
- Route53 redirects only alias to S3 Buckets which have exactly the same name of the sub-/domain

Any idea how to use a public (nice) URL from Route53 and not the public S3 Bucket URL?

**Comment by ammarkarachi** [comment]
@mbecker The bucket-name is constructed and the trigger files are uploaded using this line
https://github.com/aws-amplify/amplify-cli/blob/4e5f5c62287252ff59ecda050390e9b3c2b00146/packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/trigger-file-uploader.js#L27

I will mark this as an enhancement. Can you also help us understand your use case for aliasing the bucket?

**Comment by kaustavghosh06** [comment]
Closing this issue. Please let us know if you're able to get around the issue with @ammarkarachi 's response above^.
