### ISSUE TITLE
Mock API - When Nodejs Lambda crash, the Mock API exit

### ISSUE THREAD

**Issue by anisg** [aws-amplify/amplify-cli#5066]
**Describe the bug**
When using the Mock API, if a lambda crash, the mock API will exit with error code 1. I don't know if that's expected, but for me it's a bit boring having to relaunch the Mock API everytime.
 
**Amplify CLI Version**
4.27.1

**To Reproduce**
- create a Nodejs lambda function with following content
```
exports.handler = () => {
	console.log('hello world');
	throw `test`;
}
```
- launch the mock api, and call it from your graphql API
- it will crash with following output
```
[api] hello world
[api] 2020-08-12T14:06:06.782Z - error: uncaughtException: Unexpected end of JSON input date=Wed Aug 12 2020 16:06:06 GMT+0200 (Central European Summer Time), pid=8538, uid=0, gid=0, cwd=/root/codecommit/learning-appsync/app-bidder, execPath=/usr/local/bin/node, version=v11.15.0, argv=[/usr/local/bin/node, /usr/local/bin/amplify, mock, api], rss=385626112, heapTotal=327823360, heapUsed=277517864, external=6222076, loadavg=[1.20947265625, 0.5478515625, 0.48583984375], uptime=9969, trace=[column=null, file=null, function=JSON.parse, line=null, method=parse, native=false, column=29, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-nodejs-function-runtime-provider/src/utils/invoke.ts, function=ChildProcess.lambdaFn.on, line=23, method=on, native=false, column=13, file=events.js, function=ChildProcess.emit, line=193, method=emit, native=false, column=20, file=domain.js, function=ChildProcess.EventEmitter.emit, line=481, method=emit, native=false, column=16, file=internal/child_process.js, function=maybeClose, line=999, method=null, native=false, column=5, file=internal/child_process.js, function=Process.ChildProcess._handle.onexit, line=266, method=onexit, native=false], stack=[SyntaxError: Unexpected end of JSON input,     at JSON.parse (<anonymous>),     at ChildProcess.lambdaFn.on (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-nodejs-function-runtime-provider/src/utils/invoke.ts:23:29),     at ChildProcess.emit (events.js:193:13),     at ChildProcess.EventEmitter.emit (domain.js:481:20),     at maybeClose (internal/child_process.js:999:16),     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)]
[api] amplify mock api exited with code 1
```

**Expected behavior**
- I would prefer instead of crashing, keeping the mock API running.

**Current Workaround**
Try Catch the whole Lambda, or Relaunch the mock api everytime it fails
```
while true; do echo starting mock...; amplify mock api; echo mock exited...;  sleep 2; done
```

**Comment by SwaySway** [comment]
Closing this in favor of #5061. We currently have a PR to address this as well https://github.com/aws-amplify/amplify-cli/pull/4978
