### ISSUE TITLE
amplify/cli not able to add apiKey as authorization type

### ISSUE THREAD

**Issue by ggmon** [aws-amplify/amplify-cli#5076]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
Mutliple Authorization

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system
4.27.1

**What AWS Services are you utilizing?**

**Provide additional details e.g. code snippets**

@auth directive with 'apiKey' provider found, but the project has no API Key authentication provider configured.
InvalidDirectiveError: @auth directive with 'apiKey' provider found, but the project has no API Key authentication provider configured.
    at ModelAuthTransformer.validateRuleAuthStrategy (/home/geegee/.nvm/versions/node/v10.1.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-auth-transformer/src/ModelAuthTransformer.ts:2121:13)
    at ModelAuthTransformer.validateRules (/home/geegee/.nvm/versions/node/v10.1.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-auth-transformer/src/ModelAuthTransformer.ts:950:12)
    at ModelAuthTransformer.object (/home/geegee/.nvm/versions/node/v10.1.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-auth-transformer/src/ModelAuthTransformer.ts:352:10)
    at GraphQLTransform.transformObject (/home/geegee/.nvm/versions/node/v10.1.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/GraphQLTransform.ts:340:25)
    at GraphQLTransform.transform (/home/geegee/.nvm/versions/node/v10.1.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/GraphQLTransform.ts:266:18)
    at _buildProject (/home/geegee/.nvm/versions/node/v10.1.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/util/amplifyUtils.ts:63:35)

**Comment by SwaySway** [comment]
Do you have `apiKey` enabled in the GraphQL API? You can run `amplify update api` to enabled apiKey auth.

**Comment by ggmon** [comment]
Sorry, Its working now, I had to use the arrowkeys and then make the selection by pressing the spacebar to enable apiKey authorization
