### ISSUE TITLE
Amplify init failing - "init failed Error: EISDIR: illegal operation on a directory, read"

### ISSUE THREAD

**Issue by emilpk** [aws-amplify/amplify-cli#5084]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
Hoping to get some help with a weird error I am getting every time I try to perform 'amplify init'

Essentially I run amplify init, I say No to using an existing environment, I pick my default editor 'Visual Studio Code', it asks me if I want to use an AWS profile.  To that I select Yes, I then pick my profile from the list, hit enter and then I get...

init failed
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:581:3)
    at tryReadSync (fs.js:357:20)
    at Proxy.readFileSync (fs.js:394:19)
    at Object.readFileSync (C:\Users\xuser\AppData\Roaming\npm\node_modules@aws-amplify\cli\node_modules\aws-sdk\lib\util.js:95:26)
    at IniLoader.parseFile (C:\Users\xuser\AppData\Roaming\npm\node_modules@aws-amplify\cli\node_modules\aws-sdk\lib\shared-ini\ini-loader.js:6:47)
    at IniLoader.loadFrom (C:\Users\xuser\AppData\Roaming\npm\node_modules@aws-amplify\cli\node_modules\aws-sdk\lib\shared-ini\ini-loader.js:56:30)
    at Config.region (C:\Users\xuser\AppData\Roaming\npm\node_modules@aws-amplify\cli\node_modules\aws-sdk\lib\node_loader.js:100:36)
    at Config.set (C:\Users\xuser\AppData\Roaming\npm\node_modules@aws-amplify\cli\node_modules\aws-sdk\lib\config.js:514:39)
    at Config.<anonymous> (C:\Users\xuser\AppData\Roaming\npm\node_modules@aws-amplify\cli\node_modules\aws-sdk\lib\config.js:349:12)
    at Config.each (C:\Users\xuser\AppData\Roaming\npm\node_modules@aws-amplify\cli\node_modules\aws-sdk\lib\util.js:507:32) {
  errno: -4068,
  syscall: 'read',
  code: 'EISDIR'
}

Running out of ideas.  So far I have tried re-installing both node JS and amplify cli but this error keeps poping up

**Amplify CLI Version**
4.27.1

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version. 14.7.0

**Comment by sw-yx** [comment]
i dont think this is an amplify issue. please see similar errors reported by windows users. https://www.google.com/search?q=windows+EISDIR+error&oq=windows+EISDIR+error&aqs=chrome..69i57.2210j0j7&sourceid=chrome&ie=UTF-8
