### ISSUE TITLE
Amplify CLI throwing error post install on Windows 10 Enterprise

### ISSUE THREAD

**Issue by geverghe** [aws-amplify/amplify-cli#512]
**Describe the bug**
I tried installing amplify cli using npm install -g @aws-amplifycli

It installs successfully

Logs
>npm install -g @aws-amplify/cli
npm WARN npm npm does not support Node.js v7.10.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN npm npm does not support Node.js v7.10.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
C:\Users\geverghe\AppData\Roaming\npm\amplify -> C:\Users\geverghe\AppData\Roaming\npm\node_modules\@aws-amplify\cli\bin\amplify
npm WARN graphql-import@0.4.5 requires a peer of graphql@^0.11.0 || ^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\@aws-amplify\cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ @aws-amplify/cli@0.1.35
added 2 packages from 1 contributor, removed 6 packages and updated 27 packages in 65.81s

**To Reproduce**
1. Post installation, I typed "amplify" on command prompt and I get the following error

\AppData\Roaming\npm\node_modules\@aws-amplify\cli\src\extensions\amplify-helpers\show-help.js:30
  );
  ^
SyntaxError: Unexpected token )
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\geverghe\AppData\Roaming\npm\node_modules\@aws-amplify\cli\src\extensions\amplify-helpers\show-all-help.js:2:22)

**Expected behavior**
Help Commands/Welcome message

**Screenshots**
![image](https://user-images.githubusercontent.com/16950956/49087160-3f7fb280-f27c-11e8-93bb-f33ff39282cf.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Command Prompt

**Comment by geverghe** [comment]
My apologies. I was running on an old node version.
