### ISSUE TITLE
cascading @searchable tables @connected to ES fails

### ISSUE THREAD

**Issue by ericowhadi** [aws-amplify/amplify-cli#5140]
**Describe the bug**
Creating a simple parent child table set @connected, both @searchable, the child table fails to index in elasticsearch returning an error in the log: TypeError: sequence item 1: expected str instance, float found

**Amplify CLI Version**
4.27.2
**To Reproduce**
using the following graphql schema:
```graphql
type Video @model @searchable @key(fields: ["id","companyId","projectId","version"]){
  id: ID!
  companyId: String! 
  projectId: String! 
  version: String! 
  s3Url: String!
  sentences: [Sentence!] @connection(keyName: "byVideo", fields: ["id","companyId","projectId","version"])
}

type Sentence @model @searchable @key(fields: ["id","index"])
@key(name: "byVideo", fields: ["videoId","companyId","projectId","version"]){
  id: ID!
  index: Int!
  videoId: ID!
  companyId: String! 
  projectId: String! 
  version: String! 
} 
```
create a sentence:
```graphql
mutation CreateSentence {
      createSentence(input:{
        id: "mysentenceuuid2",
        index: 0,
        videoId: "myUUID2",
        companyId: "png",
        projectId: "master",
        version: "000"
      }) {
          id
      index
      videoId
      companyId
      projectId
      version
      _version
      _deleted
      _lastChangedAt
      createdAt
      updatedAt
	  }
    }	
```
look at logs of DDB streamer to ES and find failure and actually no index created:
```
[DEBUG]	2020-08-20T18:21:35.184Z	17d278f7-84c1-494a-a86f-3b2e2b0632b7	Event: {'Records': [{'eventID': 'c593551d179746d2115ee0ca34f1c1af', 'eventName': 'INSERT', 'eventVersion': '1.1', 'eventSource': 'aws:dynamodb', 'awsRegion': 'us-east-2', 'dynamodb': {'ApproximateCreationDateTime': 1597947694.0, 'Keys': {'index': {'N': '0'}, 'id': {'S': 'mysentenceuuid2'}}, 'NewImage': {'createdAt': {'S': '2020-08-20T18:21:33.605Z'}, 'companyId': {'S': 'png'}, '_lastChangedAt': {'N': '1597947693618'}, '__typename': {'S': 'Sentence'}, 'companyId#projectId#version': {'S': 'png#master#000'}, 'index': {'N': '0'}, 'videoId': {'S': 'myUUID2'}, 'id': {'S': 'mysentenceuuid2'}, '_version': {'N': '1'}, 'projectId': {'S': 'master'}, 'version': {'S': '000'}, 'updatedAt': {'S': '2020-08-20T18:21:33.605Z'}}, 'SequenceNumber': '750700000000002564571071', 'SizeBytes': 254, 'StreamViewType': 'NEW_AND_OLD_IMAGES'}, 'eventSourceARN': 'arn:aws:dynamodb:us-east-2:307647979425:table/Sentence-2fx5ybalejhxddytgd7fceth5q-dev/stream/2020-08-20T13:58:06.688'}]}
[DEBUG]	2020-08-20T18:21:35.184Z	17d278f7-84c1-494a-a86f-3b2e2b0632b7	Record: {'eventID': 'c593551d179746d2115ee0ca34f1c1af', 'eventName': 'INSERT', 'eventVersion': '1.1', 'eventSource': 'aws:dynamodb', 'awsRegion': 'us-east-2', 'dynamodb': {'ApproximateCreationDateTime': 1597947694.0, 'Keys': {'index': {'N': '0'}, 'id': {'S': 'mysentenceuuid2'}}, 'NewImage': {'createdAt': {'S': '2020-08-20T18:21:33.605Z'}, 'companyId': {'S': 'png'}, '_lastChangedAt': {'N': '1597947693618'}, '__typename': {'S': 'Sentence'}, 'companyId#projectId#version': {'S': 'png#master#000'}, 'index': {'N': '0'}, 'videoId': {'S': 'myUUID2'}, 'id': {'S': 'mysentenceuuid2'}, '_version': {'N': '1'}, 'projectId': {'S': 'master'}, 'version': {'S': '000'}, 'updatedAt': {'S': '2020-08-20T18:21:33.605Z'}}, 'SequenceNumber': '750700000000002564571071', 'SizeBytes': 254, 'StreamViewType': 'NEW_AND_OLD_IMAGES'}, 'eventSourceARN': 'arn:aws:dynamodb:us-east-2:307647979425:table/Sentence-2fx5ybalejhxddytgd7fceth5q-dev/stream/2020-08-20T13:58:06.688'}
[DEBUG]	2020-08-20T18:21:35.184Z	17d278f7-84c1-494a-a86f-3b2e2b0632b7	doc_table=sentence-2fx5ybalejhxddytgd7fceth5q-dev, event_name=INSERT, seq=750700000000002564571071
[DEBUG]	2020-08-20T18:21:35.184Z	17d278f7-84c1-494a-a86f-3b2e2b0632b7	NewImage: {'createdAt': {'S': '2020-08-20T18:21:33.605Z'}, 'companyId': {'S': 'png'}, '_lastChangedAt': {'N': '1597947693618'}, '__typename': {'S': 'Sentence'}, 'companyId#projectId#version': {'S': 'png#master#000'}, 'index': {'N': '0'}, 'videoId': {'S': 'myUUID2'}, 'id': {'S': 'mysentenceuuid2'}, '_version': {'N': '1'}, 'projectId': {'S': 'master'}, 'version': {'S': '000'}, 'updatedAt': {'S': '2020-08-20T18:21:33.605Z'}}
[DEBUG]	2020-08-20T18:21:35.184Z	17d278f7-84c1-494a-a86f-3b2e2b0632b7	Deserialized doc_fields: {'createdAt': '2020-08-20T18:21:33.605Z', 'companyId': 'png', '_lastChangedAt': 1597947693618.0, '__typename': 'Sentence', 'companyId#projectId#version': 'png#master#000', 'index': 0.0, 'videoId': 'myUUID2', 'id': 'mysentenceuuid2', '_version': 1.0, 'projectId': 'master', 'version': '000', 'updatedAt': '2020-08-20T18:21:33.605Z'}
[ERROR]	2020-08-20T18:21:35.185Z	17d278f7-84c1-494a-a86f-3b2e2b0632b7	Traceback (most recent call last):
  File "/var/task/python_streaming_function.py", line 257, in lambda_handler
    return _lambda_handler(event, context)
  File "/var/task/python_streaming_function.py", line 207, in _lambda_handler
    doc_id = compute_doc_index(ddb['Keys'], ddb_deserializer)
  File "/var/task/python_streaming_function.py", line 135, in compute_doc_index
    return '|'.join(index)
TypeError: sequence item 1: expected str instance, float found
 ```
**Expected behavior**
Error should not happen, and sentence index should be created and data flowing to it from ddb to ES

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Node Version. You can use `node -v` to check the node version on your system
v12.18.1

**Comment by ericowhadi** [comment]
BTW, conflict detection is ON, with automerge policy.

**Comment by ericowhadi** [comment]
New info, if I change the type of Sentence "index" field from Int! to String!, the pipeline to elasticsearch works.
