### ISSUE TITLE
Headless Amplify pull fails

### ISSUE THREAD

**Issue by notbenoit** [aws-amplify/amplify-cli#5193]
**Describe the bug**
Running headless `amplify pull` fails. It used to work last week (around Aug 21st). Without any change made to our CI script, it started failing

**Amplify CLI Version**
Latest (`4.27.3`)

**To Reproduce**
```
amplify pull \
  --amplify "{\"projectName\":\"[REDACTED]\",\"appId\":\"[REDACTED]\",\"envName\":\"dev\",\"defaultEditor\":\"code\"}" \
  --frontend "{\"frontend\":\"ios\"}" \
  --providers "{\"awscloudformation\":{\"configLevel\":\"project\",\"useProfile\":true,\"profileName\":\"[REDACTED]\"}}" \
  --restore \
  --yes
```

**Expected behavior**
`amplify pull` should succeed.

**Screenshots/Snippets**
The command fails with : 
```
✔ Successfully pulled backend environment dev from the cloud.
✖ An error occurred when pushing the resources to the cloud
✖ There was an error initializing your environment.
Failed to pull the backend.
Cannot read property 'syncVersions' of undefined
TypeError: Cannot read property 'syncVersions' of undefined
    at ensureLayerVersion (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/provider-utils/awscloudformation/utils/packageLayer.ts:81:41)
    at packageLayer (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/provider-utils/awscloudformation/utils/packageLayer.ts:17:9)
    at packageResource (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/push-resources.js:228:68)
    at packageResources (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/push-resources.js:287:19)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/push-resources.js:44:11)
    at Object.pushResources (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/index.js:40:25)
    at /usr/local/lib/node_modules/@aws-amplify/cli/src/initialize-env.ts:84:53
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/promise-sequential/index.js:16:18
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version : `v14.5.0`

**Additional context**
N/A

**Comment by jhockett** [comment]
Hi @notbenoit, it looks like something went wrong getting information for a Lambda layer.

For each Lambda layer in your project, can you please verify that `<project-root>/amplify/backend/function/<layer-name>/layer-paramters.json` exists?

**Comment by notbenoit** [comment]
Thank you for getting back to me.
I'll check with our backend team and get back to you shortly.

**Comment by CamiloMartinezCDS** [comment]
Hi @jhockett, we checked every layer and each one has a `layer-parametrs.json` file. Is there something else that we should check related to the layers?

**Comment by jhockett** [comment]
This is looks like a bug with the old Lambda layer implementation. The best way to get unblocked would be to upgrade to the latest version of the CLI and [migrate](https://github.com/aws-amplify/amplify-cli/issues/4886#issuecomment-686798972) your layers and dependent functions.

N.B. After upgrading the CLI, newly created Lambda layers will have the `layer-parameters.json` file replaced by a `layer-runtimes.json` file.

**Comment by kaustavghosh06** [comment]
Closing this issue as @jhockett mentioned this would be fixed with the later version of the CLI (and requires a migration).
