### ISSUE TITLE
DataStore fails to codegen models when using @connection for 1 to 1 on @key with no name

### ISSUE THREAD

**Issue by ericowhadi** [aws-amplify/amplify-cli#5197]
**Describe the bug**
 codegen on the following schema works:

type Video @model  @key(fields: ["id","companyId","studyId","version"]){
  id: ID!
  companyId: String! 
  studyId: ID! 
  version: String!
  masterId: ID!
  masterVersion: String! 
  s3Url: String
  sentences: [Sentence!] @connection(keyName: "byVideo", fields: ["id","companyId","studyId","version"])
 # masterVideo: Video @connection(fields: ["id","companyId","masterId","masterVersion"])
}

type Sentence @model  @key(fields: ["id", "index"])
@key(name: "byVideo", fields: ["videoId","companyId","studyId","version"]){
  id: ID!
  index: String!
  videoId: ID! 
  companyId: String! 
  studyId: ID! 
  version: String! 
  tt: String!
#parentVideo: Video @connection (fields:  ["videoId","companyId","studyId","version"])
} 

if I uncomment ether of the commented one to one @connection, I get error below when doing codegen (while the amplify pushed schema works).

//uncommenting #parentVideo:
DataStore only support one key in field
Error: DataStore only support one key in field
    at Object.processConnections (C:\Users\owhadi\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-codegen-appsync-model-plugin\src\utils\process-connections.ts:144:17)
    at C:\Users\owhadi\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-codegen-appsync-model-plugin\src\visitors\appsync-visitor.ts:448:32
    at Array.forEach (<anonymous>)
    at C:\Users\owhadi\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-codegen-appsync-model-plugin\src\visitors\appsync-visitor.ts:447:20
    at Array.forEach (<anonymous>)
    at AppSyncModelJavascriptVisitor.processConnectionDirective (C:\Users\owhadi\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-codegen-appsync-model-plugin\src\visitors\appsync-visitor.ts:446:34)
    at AppSyncModelJavascriptVisitor.processDirectives (C:\Users\owhadi\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-codegen-appsync-model-plugin\src\visitors\appsync-visitor.ts:241:10)
    at AppSyncModelJavascriptVisitor.generate (C:\Users\owhadi\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-codegen-appsync-model-plugin\src\visitors\appsync-javascript-visitor.ts:48:10)
    at Object.exports.plugin (C:\Users\owhadi\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-codegen-appsync-model-plugin\src\plugin.ts:49:20)
    at Object.executePlugin (C:\Users\owhadi\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\@graphql-codegen\core\src\execute-plugin.ts:54:12)
	
//uncommenting #masterVideo
DataStore only support one key in field
Error: DataStore only support one key in field
    at Object.processConnections (C:\Users\owhadi\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-codegen-appsync-model-plugin\src\utils\process-connections.ts:144:17)
    at C:\Users\owhadi\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-codegen-appsync-model-plugin\src\visitors\appsync-visitor.ts:448:32
    at Array.forEach (<anonymous>)
    at C:\Users\owhadi\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-codegen-appsync-model-plugin\src\visitors\appsync-visitor.ts:447:20
    at Array.forEach (<anonymous>)
    at AppSyncModelJavascriptVisitor.processConnectionDirective (C:\Users\owhadi\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-codegen-appsync-model-plugin\src\visitors\appsync-visitor.ts:446:34)
    at AppSyncModelJavascriptVisitor.processDirectives (C:\Users\owhadi\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-codegen-appsync-model-plugin\src\visitors\appsync-visitor.ts:241:10)
    at AppSyncModelJavascriptVisitor.generate (C:\Users\owhadi\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-codegen-appsync-model-plugin\src\visitors\appsync-javascript-visitor.ts:48:10)
    at Object.exports.plugin (C:\Users\owhadi\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-codegen-appsync-model-plugin\src\plugin.ts:49:20)
    at Object.executePlugin (C:\Users\owhadi\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\@graphql-codegen\core\src\execute-plugin.ts:54:12)

Amplify Doc on dataStore specify this:
When using the @key directive with DataStore, as long as you specify a name you can use any value(s) in fields. However, if the name property is omitted, the first item in the fields array must be "id". E.g., @key(fields: ["id", "content"]).
This hint that what I am doing should work, and therefore this is a bug.

**Amplify CLI Version**
4.27.3

**To Reproduce**
see above, just uncomment one of the commented line and try amplify codegen models

**Expected behavior**
amplify codegen models should successfully generate code.

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version. v12.18.1

**Additional context**

**Comment by akshbhu** [comment]
Hi @ericowhadi 

You are getting the above error because the library currently doesn't have support for composite keys.

**Comment by ericowhadi** [comment]
Hi Akshbu, 
thanks for the quick response. Based on the documentation extract:
"When using the @key directive with DataStore, as long as you specify a name you can use any value(s) in fields. However, if the name property is omitted, the first item in the fields array must be "id". E.g., @key(fields: ["id", "content"])."
This looked supported based on the exemple provided. Are you going to add support sometime, or fix the documentation to officialize the limitation? Not supporting sort key on dynamoDB look somewhat problematic, right?

**Comment by akshbhu** [comment]
Hi @ericowhadi 

The problem is with @connection with multiple fields. Yes I am also marking this as bug for documentation for this limitation
