### ISSUE TITLE
Cannot set property 'defaultAuthentication' of undefined

### ISSUE THREAD

**Issue by roland-batovski** [aws-amplify/amplify-cli#5217]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
I cannot use `amplify update api` to update my GraphQL schema because of a fatal error

**Amplify CLI Version**
4.27.3

**To Reproduce**
Create a new Amplify environment with a GraphQL API, and try to add a model with a @key directive

**Expected behavior**
Expected the `amplify update api` to terminate gracefully

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. v14.8.0

**Additional context**

I updated to the latest version of the CLI, created a new environment for testing purposes, pushed my local amplify config onto the new environment (this was successful without any errors). I then tried updating the GraphQL schema and running `amplify update api` but it always ended early with the following error:

```
Rolands-MBP:dinenage.mobile rolandbatovski$ amplify update api
? Please select from one of the below mentioned services: GraphQL
? Select from the options below Walkthrough all configurations
? Choose the default authorization type for the API Amazon Cognito User Pool
Use a Cognito user pool configured as a part of this project.
? Do you want to configure advanced settings for the GraphQL API No, I am done.
Cannot set property 'defaultAuthentication' of undefined
TypeError: Cannot set property 'defaultAuthentication' of undefined
    at CfnApiArtifactHandler.updateArtifacts (/Users/rolandbatovski/.nvm/versions/node/v14.8.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/lib/provider-utils/awscloudformation/cfn-api-artifact-handler.js:78:50)
    at async Object.executeAmplifyCommand (/Users/rolandbatovski/.nvm/versions/node/v14.8.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/lib/index.js:147:5)
    at async executePluginModuleCommand (/Users/rolandbatovski/.nvm/versions/node/v14.8.0/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:153:5)
    at async Object.executeCommand (/Users/rolandbatovski/.nvm/versions/node/v14.8.0/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:34:9)
    at async Object.run (/Users/rolandbatovski/.nvm/versions/node/v14.8.0/lib/node_modules/@aws-amplify/cli/lib/index.js:94:9)
```

I tried reverting to an older version of the CLI, but I get the same error when trying to do `amplify update api` on the new environment.

Any help is appreciated. Many thanks!

**Comment by akshbhu** [comment]
Hi @roland-batovski 

Can you explain the ```local amplify config``` you mentioned so that I can reproduce this issue?
Also can you share the schema you are using redacting all secret information

**Comment by roland-batovski** [comment]
@akshbhu Thanks for your reply!

I use Amplify for Cognito, a GraphQL and a REST API, and several Lambda functions that interact with third party services.

```
Rolands-MBP:dinenage.mobile rolandbatovski$ amplify status
Scanning for plugins...
Plugin scan successful

Current Environment: prod

| Category | Resource name      | Operation | Provider plugin   |
| -------- | ------------------ | --------- | ----------------- |
| Auth     | dine*******   | No Change | awscloudformation |
| Function | contentLambda      | No Change | awscloudformation |
| Function | notificationLambda | No Change | awscloudformation |
| Function | pollsLambda        | No Change | awscloudformation |
| Function | pushAndroid        | No Change | awscloudformation |
| Function | campaignLambda     | No Change | awscloudformation |
| Api      | restapi            | No Change | awscloudformation |
| Api      | graphapi           | No Change | awscloudformation |
```

I recently pushed all of the resources above to the newly created environment `prod`. Both `amplify push` and `amplify pull` work as intended, it's just `amplify update api` that is throwing an error.

I was trying to add a @key directive to one of the models below so that I could index the Answer table:

```
type User @model {
  id: ID!
  name: String
  email: String!
  notificationToken: String
  active: Boolean
  seenDigest: String
}

type Answer @model @key(name: "gsi-answer", fields: ["userId"], queryField: "answersByUser") {
 id: ID!
 userId: String!
 questionId: String!
 answerId: String!
}
```
I'm not entirely sure if the error being thrown is because of misconfiguration in the new environment or due to the update to the latest version of the CLI. I tried reverting to a previous version and it didn't help. Let me know if you need anything else.

**Comment by akshbhu** [comment]
Hi @roland-batovski 

It seems there is some some problem with auth config. What authentication type you selected while adding api?
Also can you share your backend-config file after redacting all the secret from the file?

**Comment by roland-batovski** [comment]
I am using Amazon User Pools for the authentication type. Below is the backend-config.json file:

```\{
	"auth": {
		"dinena*******": {
			"service": "Cognito",
			"providerPlugin": "awscloudformation"
		}
	},
	"function": {
		"contentLambda": {
			"service": "Lambda",
			"providerPlugin": "awscloudformation",
			"build": true
		},
		"notificationLambda": {
			"service": "Lambda",
			"providerPlugin": "awscloudformation",
			"build": true
		},
		"pollsLambda": {
			"service": "Lambda",
			"providerPlugin": "awscloudformation",
			"build": true
		},
		"pushAndroid": {
			"service": "Lambda",
			"providerPlugin": "awscloudformation",
			"build": true
		},
		"pushAndroidLambda": {
			"service": "Lambda",
			"providerPlugin": "awscloudformation",
			"build": true
		},
		"teaserLambda": {
			"service": "Lambda",
			"providerPlugin": "awscloudformation",
			"build": true
		},
		"campaignLambda": {
			"service": "Lambda",
			"providerPlugin": "awscloudformation",
			"build": true
		}
	},
	"api": {
		"restapi": {
			"service": "API Gateway",
			"providerPlugin": "awscloudformation",
			"dependsOn": [
				{
					"category": "function",
					"resourceName": "contentLambda",
					"attributes": [
						"Name",
						"Arn"
					]
				},
				{
					"category": "function",
					"resourceName": "notificationLambda",
					"attributes": [
						"Name",
						"Arn"
					]
				},
				{
					"category": "function",
					"resourceName": "pushAndroid",
					"attributes": [
						"Name",
						"Arn"
					]
				},
				{
					"category": "function",
					"resourceName": "teaserLambda",
					"attributes": [
						"Name",
						"Arn"
					]
				},
				{
					"category": "function",
					"resourceName": "campaignLambda",
					"attributes": [
						"Name",
						"Arn"
					]
				}
			]
		},
	"graphapi": {
            "service": "AppSync",
            "providerPlugin": "awscloudformation",
            "output": {
                "authConfig": {
                    "additionalAuthenticationProviders": [],
                    "defaultAuthentication": {
                        "authenticationType": "AMAZON_COGNITO_USER_POOLS",
                        "userPoolConfig": {
                            "userPoolId": "authdinena********"
                        }
                    }
                }
            }
        }
	}
}
```

**Comment by cwoodrow89** [comment]
@akshbhu please note this issue has become business critical for our small start up, any escalation of this matter would be greatly appreciated. 🙏

**Comment by akshbhu** [comment]
Hi @roland-batovski 

Can you check the ```amplify-meta.json``` file if it has default authentication present in auth config for graphql api?

For the workaround you can do amplify pull command, it will sync up the latest changes pushed to cloud and then try updating api again.

**Comment by roland-batovski** [comment]
Hey @akshbhu 
Below is the 'graphQL' section of the `amplify-meta.json` file. It looks like a bit of the authentication object is missing, as you suspected:

```
"graphapi": {
			"service": "AppSync",
			"providerPlugin": "awscloudformation",
			"output": {
				"securityType": "AMAZON_COGNITO_USER_POOLS",
				"GraphQLAPIIdOutput": "2myr2d7***********",
				"GraphQLAPIEndpointOutput": "https://nbool4iyfjcebouk6tetobs74y.appsync-api.eu-west-1.amazonaws.com/graphql"
			},
			"providerMetadata": {
				"s3TemplateURL": "https://s3.amazonaws.com/amplify-dinenage-******-deployment/amplify-cfn-templates/api/cloudformation-template.json",
				"logicalId": "apigraphapi"
			},
			"lastPushTimeStamp": "2020-08-24T13:58:28.424Z",
			"lastPushDirHash": "K14SoIsnBnQ1A***********"
		}
```

However, I tried doing an `amplify pull` and I'm still getting the same error

**Comment by akshbhu** [comment]
Hi @roland-batovski 

Yeah , auth config is missing from ```amplify-meta.json```. One thing you can try to check if auth config object present in ```amplify-meta``` file present ```#currentCloudbackend``` folder and  paste the object to similar place in ```amplify-meta.json``` file present in ```backend``` folder. 
Your amplify-meta file should look something like this with authconfig present in output section:
```json
"graphapi": {
			"service": "AppSync",
			"providerPlugin": "awscloudformation",
			"output": {
                           "authConfig": {
                                "additionalAuthenticationProviders": [],
                                "defaultAuthentication": {
                                       "authenticationType": "AMAZON_COGNITO_USER_POOLS",
                                       "userPoolConfig": {
                                       "userPoolId": "*********"
                                }
                         }
                       }
				"securityType": "AMAZON_COGNITO_USER_POOLS",
				"GraphQLAPIIdOutput": "************",
				"GraphQLAPIEndpointOutput": "https://nbool4iyfjcebouk6tetobs74y.appsync-api.eu-west-1.amazonaws.com/graphql"
			},
			"providerMetadata": {
				"s3TemplateURL": "*******-deployment/amplify-cfn-templates/api/cloudformation-template.json",
				"logicalId": "apigraphapi"
			},
			"lastPushTimeStamp": "2020-08-24T13:58:28.424Z",
			"lastPushDirHash": "************"
		}
```

Before making these changes , ensure you have a copy of ```amplify-meta.json``` file.

Let me know if this solves your issue?

**Comment by roland-batovski** [comment]
@akshbhu your suggestion worked. I was able to run `amplify update api` successfully now. Thanks!

**Comment by akshbhu** [comment]
Nice to know it worked. Closing this issue
