### ISSUE TITLE
Failed to complete amplify add auth with Error: ENOENT: no such file or directory error in 4.28.0

### ISSUE THREAD

**Issue by anggras** [aws-amplify/amplify-cli#5219]
**Describe the bug**
Failed to complete ```amplify add auth``` with ```Error: ENOENT: no such file or directory``` error

**Amplify CLI Version**
4.28.0

**To Reproduce**
Run ```amplify add auth``` with the following settings:
```
The current configured provider is Amazon Cognito. 
 
 Do you want to use the default authentication and security configuration? Manual configuration
 Select the authentication/authorization services that you want to use: User Sign-Up, Sign-In, connected with AWS IAM controls (Enables per-user Storage features for images or other content, Analytics, and more)
 Please provide a friendly name for your resource that will be used to label this category in the project: <redacted>
 Please enter a name for your identity pool. <redacted>
 Allow unauthenticated logins? (Provides scoped down permissions that you can control via AWS IAM) No
 Do you want to enable 3rd party authentication providers in your identity pool? Yes
 Select the third party identity providers you want to configure for your identity pool: Amazon
  
 You've opted to allow users to authenticate via Amazon.  If you haven't already, you'll need to create an Amazon App ID. 
 
 Enter your Amazon App ID for your identity pool:  <redacted>
 Please provide a name for your user pool: <redacted>
 Warning: you will not be able to edit these selections. 
 How do you want users to be able to sign in? Email
 Do you want to add User Pool Groups? Yes
? Provide a name for your user pool group: Admins
? Do you want to add another User Pool Group No
✔ Sort the user pool groups in order of preference · Admins
 Do you want to add an admin queries API? Yes
? Do you want to restrict access to the admin queries API to a specific Group Yes
? Select the group to restrict access with: Admins
 Multifactor authentication (MFA) user login options: OPTIONAL (Individual users can use MFA)
 For user login, select the MFA types: SMS Text Message
 Please specify an SMS authentication message: Your authentication code is {####}
 Email based user registration/forgot password: Enabled (Requires per-user email entry at registration)
 Please specify an email verification subject: Your verification code
 Please specify an email verification message: Your verification code is {####}
 Do you want to override the default password policy for this User Pool? No
 Warning: you will not be able to edit these selections. 
 What attributes are required for signing up? Email
 Specify the app's refresh token expiration period (in days): 30
 Do you want to specify the user attributes this app can read and write? Yes
 Specify read attributes: Email, Email Verified?
 Specify write attributes: 
 Do you want to enable any of the following capabilities? Email Verification Link with Redirect
 Do you want to use an OAuth flow? Yes
 What domain name prefix do you want to use? <redacted>
 Enter your redirect signin URI: http://localhost:8080/
? Do you want to add another redirect signin URI No
 Enter your redirect signout URI: http://localhost:8080/
? Do you want to add another redirect signout URI No
 Select the OAuth flows enabled for this project. Authorization code grant
 Select the OAuth scopes enabled for this project. Phone, Email, OpenID, Profile, aws.cognito.signin.user.admin
 Select the social providers you want to configure for your user pool: Login With Amazon
  
 You've opted to allow users to authenticate via Amazon.  If you haven't already, you'll need to create an Amazon App ID. 
 
 Enter your Amazon App ID for your OAuth flow:  <redacted>
 Enter your Amazon App Secret for your OAuth flow:  <redacted>
? Do you want to configure Lambda Triggers for Cognito? Yes
? Which triggers do you want to enable for Cognito Custom Message
? What functionality do you want to use for Custom Message Send Account Confirmation Link w/ Redirect
? Enter the URL that your users will be redirected to upon account confirmation: http://localhost:8080/confirmed
? Enter the subject for your custom account confirmation email: Confirm Account
? Enter the body text for your custom account confirmation email (this will appear before the link URL): Please go to the following link to confirm your account
Successfully added resource <redacted> locally.

Next steps:
Check out sample function code generated in <project-dir>/amplify/backend/function/<redacted>/src
"amplify function build" builds all of your functions currently in the project
"amplify mock function <functionName>" runs your function locally
"amplify push" builds all of your local backend resources and provisions them in the cloud
"amplify publish" builds all of your local backend and front-end resources (if you added hosting category) and provisions them in the cloud
Successfully added the Lambda function locally
? Do you want to edit your verification-link function now? Yes
Please edit the file in your editor: /Users/anggra/Documents/project/amplify/backend/function/<redacted>/src/verification-link.js
? Press enter to continue 
Successfully added AdminQueries12345 function locally
Successfully added AdminQueries API locally
```

Following that, encountered ```ENOENT``` error as the following
```
Error: ENOENT: no such file or directory, stat '/Users/anggra/.nvm/versions/node/v13.8.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/lib/provider-utils/awscloudformation/triggers/CustomMessage/assets'
    at Object.statSync (fs.js:948:3)
    at Object.statSync (/Users/anggra/.nvm/versions/node/v13.8.0/lib/node_modules/@aws-amplify/cli/node_modules/graceful-fs/polyfills.js:307:34)
    at getStatsSync (/Users/anggra/.nvm/versions/node/v13.8.0/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/util/stat.js:58:18)
    at Object.checkPathsSync (/Users/anggra/.nvm/versions/node/v13.8.0/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/util/stat.js:90:33)
    at copySync (/Users/anggra/.nvm/versions/node/v13.8.0/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:24:38)
    at copyS3Assets (/Users/anggra/.nvm/versions/node/v13.8.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/provider-utils/awscloudformation/index.js:645:7)
    at /Users/anggra/.nvm/versions/node/v13.8.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/provider-utils/awscloudformation/index.js:151:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Object.executeAmplifyCommand (/Users/anggra/.nvm/versions/node/v13.8.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/index.js:312:3)
    at executePluginModuleCommand (/Users/anggra/.nvm/versions/node/v13.8.0/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:161:3)
There was an error adding the auth resource
```

**Expected behavior**
Auth resource should be successfully created,

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. 13.8.0

**Additional context**
- Downgraded to amplify-cli 4.27.3 with the same configuration and the resource can be created successfully

**Comment by akshbhu** [comment]
Thanks for reporting this. I have reproduced it.

**Comment by houmark** [comment]
Do you guys actually test?

**Comment by akshbhu** [comment]
Closing this issue in favour of #5223

**Comment by camhart** [comment]
This is occurring for me on Windows 10 using Amplify version 4.32.1
