### ISSUE TITLE
Root Stack Creation Fails with LimitExceededException, but we only have 5 active stacks

### ISSUE THREAD

**Issue by rdkelley** [aws-amplify/amplify-cli#5221]
**Describe the bug**
This is the error we get when trying to create a new environment on amplify init. My understanding is that there is a 200 stack limit on CloudFormation stacks, but we only have 5 active stacks. We have many (probably 200+) deleted stacks -- is CloudFormation counting deleted stacks as stacks for this limit? If so, is there a way to delete a deleted stack?
```
✖ Root stack creation failed
init failed
LimitExceededException: Limit for stack has been exceeded
    at Request.extractError (C:\Users\rdkel\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\protocol\query.js:50:29)
    at Request.callListeners (C:\Users\rdkel\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
    at Request.emit (C:\Users\rdkel\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (C:\Users\rdkel\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\request.js:688:14)
    at Request.transition (C:\Users\rdkel\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\Users\rdkel\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\Users\rdkel\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\Users\rdkel\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\Users\rdkel\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\request.js:690:12)
    at Request.callListeners (C:\Users\rdkel\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\sequential_executor.js:116:18) {
  code: 'LimitExceededException',
  time: 2020-09-01T18:15:15.647Z,
  requestId: '3a7b7d0a-141d-44a6-a540-dcfafbd042c0',
  statusCode: 400,
  retryable: false,
  retryDelay: 97.11873697246907
```

**Amplify CLI Version**
4.28.0

**To Reproduce**
```
$ amplify init
Note: It is recommended to run this command from the root of your app directory
? Do you want to use an existing environment? No
? Enter a name for the environment devryank
Using default provider  awscloudformation  

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html

? Do you want to use an AWS profile? Yes
```

**Expected behavior**
It should create a new stack.

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu]
Windows
 - Node Version. You can use `node -v` to check the node version on your system
12.18.1

**Comment by akshbhu** [comment]
Hi @rdkelley 

I don't think deleted stack will count in limit of 200 stacks. I guess there might some other problem.

- Can you check the complete stacks with selecting the option of view nested stacks also?

- Can you also check the deployment region is same as region in which you are were checking for 5 active stacks in AWS console? 

Let me know if this solves your problem?

**Comment by rdkelley** [comment]
@akshbhu Ah, I forgot about nested stacks -- that's what it is. We have exactly 200 nested stacks in that region. It appears it's creating a nested stack for each of our lambda functions, which is what is pushing the number of stacks ups per parent stack.

**Comment by akshbhu** [comment]
Thanks for the reply and good to know it worked for you. I am closing this issue for now , feel free to comment and I will reopen this again
