### ISSUE TITLE
datastore does not support 1 to 1 connection with both sides of connection when 1 to 1 connection with same id on both models is defined

### ISSUE THREAD

**Issue by pedramp20** [aws-amplify/amplify-cli#5249]
**Describe the bug**
if you have two models connected via connection directive and the dependent model is designed to use the same id as the first model and no other attribute is defined to store the dependent model's id , when codegen model is called the following error is thrown

datastore does not support 1 to 1 connection with both sides of connection as optional field

**Amplify CLI Version**
4.29.0

**To Reproduce**
defined two models as follows:

```

type Post
	@model{
	id: ID!
	postStat: PostStat @connection(fields: ["id"]) #post stat has the same id as the post

}

type PostStat
	@model(subscriptions: null){
	id: ID!
	owner: String!
	numberOfReactions: Int
}
```

**Expected behavior**
To be able to generate models via 

```
amplify codegen models
```

**Comment by akshbhu** [comment]
Hi @pedramp20 

I have tried with your schema and not able to reproduce the error on same version.
Steps I did:
```
amplify add api
amplify codegen models
```
This successfully generated models inside src folder.

Is there any other setting that you did which leads to this error?

**Comment by fkoner** [comment]
Hi @akshbhu :

I had a similar error:

```
DataStore does not support 1 to 1 connection with both sides of connection as optional field
Error: DataStore does not support 1 to 1 connection with both sides of connection as optional field
    at Object.processConnections (/home/paco/.nvm/versions/node/v10.20.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen-appsync-model-plugin/src/utils/process-connections.ts:201:17)
    at model.fields.forEach.field (/home/paco/.nvm/versions/node/v10.20.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen-appsync-model-plugin/src/visitors/appsync-visitor.ts:448:32)
    at Array.forEach (<anonymous>)
    at Object.values.forEach.model (/home/paco/.nvm/versions/node/v10.20.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen-appsync-model-plugin/src/visitors/appsync-visitor.ts:447:20)
    at Array.forEach (<anonymous>)
    at AppSyncModelJavascriptVisitor.processConnectionDirective (/home/paco/.nvm/versions/node/v10.20.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen-appsync-model-plugin/src/visitors/appsync-visitor.ts:446:34)
    at AppSyncModelJavascriptVisitor.processDirectives (/home/paco/.nvm/versions/node/v10.20.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen-appsync-model-plugin/src/visitors/appsync-visitor.ts:241:10)
    at AppSyncModelJavascriptVisitor.generate (/home/paco/.nvm/versions/node/v10.20.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen-appsync-model-plugin/src/visitors/appsync-javascript-visitor.ts:48:10)
    at Object.exports.plugin (/home/paco/.nvm/versions/node/v10.20.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen-appsync-model-plugin/src/plugin.ts:49:20)
    at Object.executePlugin (/home/paco/.nvm/versions/node/v10.20.1/lib/node_modules/@aws-amplify/cli/node_modules/@graphql-codegen/core/src/execute-plugin.ts:54:12)
```

I do not know if it is presented because the relationship is optional and is something similar to what @pedramp20 addresses.

Also if it helps, I created my schema with versions prior to 4.29.0, i was a little corious about what this command does, because the documentation not mentions it.

https://docs.amplify.aws/cli/graphql-transformer/codegen

**Comment by akshbhu** [comment]
Hi @fkoner 

I tried with an older version v4.28.0 to add api and ran above command with v4.29.0 and still it is working fine for me. I will try to debug more based on the error.

**Comment by pedramp20** [comment]
I removed auth directive from the models to simplify the case. Try to add auth directive and check if the issue can be reproduced.

```

type Post
	@auth(
		rules: [
			{ allow: owner, operations: [create, update, delete, read] }
			{ allow: groups, groups: ["Group1"], operations: [read] }
		]
	) {
	id: ID!
	postStat: PostStat @connection(fields: ["id"]) #post stat has the same id as the post

}

type PostStat
	@model(subscriptions: null)
	@auth(
		rules: [
			{ allow: owner, operations: [create, update, delete, read] }
			{ allow: private, provider: iam, operations: [update, read] }
			{ allow: groups, groups: ["Group1"], operations: [read] }
		]
	) {
	id: ID!
	owner: String!
	numberOfReactions: Int
}

```

**Comment by akshbhu** [comment]
Hi @pedramp20 

The above schema is also working fine.
This error occurs when you have connection fields either both optional or mandatory. I was able to reproduce this  when I used the schema below which has both ```id``` and ```postStat```  fields are mandatory.

``` graphql
type Post
	@auth(
		rules: [
			{ allow: owner, operations: [create, update, delete, read] }
			{ allow: groups, groups: ["Group1"], operations: [read] }
		]
	) {
	id: ID!
	owner: String!
	postStat: PostStat! @connection(fields: ["id"]) #post stat has the same id as the post

}

type PostStat
	@model(subscriptions: null)
	@auth(
		rules: [
			{ allow: owner, operations: [create, update, delete, read] }
			{ allow: private, provider: iam, operations: [update, read] }
			{ allow: groups, groups: ["Group1"], operations: [read] }
		]
	) {
	id: ID!
	owner: String!
	numberOfReactions: Int
}
```

Can you check if thats the case in your schema?

**Comment by pedramp20** [comment]
No, in my case one is mandatory and one is optional as I posted above.

**Comment by akshbhu** [comment]
Hi @pedramp20 

Is the above schema you mentioned is complete or are there any other types in the schema having @connection directive?

The schema you posted above works fine for me and generating models.This is generated index.js file from above schema
```javascript
import { initSchema } from '@aws-amplify/datastore';
import { schema } from './schema';



const { Post, PostStat } = initSchema(schema);

export {
  Post,
  PostStat
};
```
and schema.js file 
``` javascript
export const schema = {
    "models": {
        "Post": {
            "name": "Post",
            "fields": {
                "id": {
                    "name": "id",
                    "isArray": false,
                    "type": "ID",
                    "isRequired": true,
                    "attributes": []
                },
                "owner": {
                    "name": "owner",
                    "isArray": false,
                    "type": "String",
                    "isRequired": true,
                    "attributes": []
                },
                "postStat": {
                    "name": "postStat",
                    "isArray": false,
                    "type": {
                        "model": "PostStat"
                    },
                    "isRequired": false,
                    "attributes": [],
                    "association": {
                        "connectionType": "HAS_ONE",
                        "associatedWith": "id"
                    }
                }
            },
            "syncable": true,
            "pluralName": "Posts",
            "attributes": [
                {
                    "type": "model",
                    "properties": {}
                },
                {
                    "type": "auth",
                    "properties": {
                        "rules": [
                            {
                                "provider": "userPools",
                                "ownerField": "owner",
                                "allow": "owner",
                                "operations": [
                                    "create",
                                    "update",
                                    "delete",
                                    "read"
                                ],
                                "identityClaim": "cognito:username"
                            },
                            {
                                "groupClaim": "cognito:groups",
                                "provider": "userPools",
                                "allow": "groups",
                                "groups": [
                                    "Group1"
                                ],
                                "operations": [
                                    "read"
                                ]
                            }
                        ]
                    }
                }
            ]
        },
        "PostStat": {
            "name": "PostStat",
            "fields": {
                "id": {
                    "name": "id",
                    "isArray": false,
                    "type": "ID",
                    "isRequired": true,
                    "attributes": []
                },
                "owner": {
                    "name": "owner",
                    "isArray": false,
                    "type": "String",
                    "isRequired": true,
                    "attributes": []
                },
                "numberOfReactions": {
                    "name": "numberOfReactions",
                    "isArray": false,
                    "type": "Int",
                    "isRequired": false,
                    "attributes": []
                }
            },
            "syncable": true,
            "pluralName": "PostStats",
            "attributes": [
                {
                    "type": "model",
                    "properties": {
                        "subscriptions": null
                    }
                },
                {
                    "type": "auth",
                    "properties": {
                        "rules": [
                            {
                                "provider": "userPools",
                                "ownerField": "owner",
                                "allow": "owner",
                                "operations": [
                                    "create",
                                    "update",
                                    "delete",
                                    "read"
                                ],
                                "identityClaim": "cognito:username"
                            },
                            {
                                "allow": "private",
                                "provider": "iam",
                                "operations": [
                                    "update",
                                    "read"
                                ]
                            },
                            {
                                "groupClaim": "cognito:groups",
                                "provider": "userPools",
                                "allow": "groups",
                                "groups": [
                                    "Group1"
                                ],
                                "operations": [
                                    "read"
                                ]
                            }
                        ]
                    }
                }
            ]
        }
    },
    "enums": {},
    "nonModels": {},
    "version": "0a3649623829c7d99af321aa9db0c26c"
};
```

Can you try with amplify version v4.30.0 and check if this error still there?

**Comment by jamesalester** [comment]
This still isn't working on v4.32.0. I'm getting the same error with this schema: 

```
# Models
type Activity
  @model
  @key(name: "byClub", fields: ["clubId", "createdAt"], queryField: "getActivityByClub") {
  id: ID!
  clubId: ID!
  activityPeekId: ID
  peek: Peek @connection
  text: String
  createdAt: AWSDateTime
}

type Author
  @model {
  id: ID!
  firstName: String!
  middleName: String
  lastName: String!
  commonName: String!
  books: [BookAuthor] @connection(keyName: "byAuthor", fields: ["id"])
}

type BookAuthor
  @model(queries: null)
  @key(name: "byBook", fields: ["bookId", "authorId"])
  @key(name: "byAuthor", fields: ["authorId", "bookId"]) {
  id: ID!
  bookId: ID!
  authorId: ID!
  book: Book! @connection(fields: ["bookId"])
  author: Author! @connection(fields: ["authorId"])
}

type Book
  @model {
  id: ID!
  title: String!
  epub: S3Object!
  cover: S3Object
  authors: [BookAuthor] @connection(keyName: "byBook", fields: ["id"])
  blurb: String
  pubdate: AWSDate
  publisher: String
  language: String
  genre: [String]
}

type ClubBook
  @model
  @key(name: "byClub", fields: ["clubId"]) {
  id: ID!
  bookId: ID!
  clubId: ID!
  book: Book! @connection(fields: ["bookId"])
  club: Club! @connection(fields: ["clubId"])
  peeks: [Peek] @connection(keyName: "byBook", fields: ["id"])
}

type Club @model @key(name: "byCreator", fields: ["creatorId"]) {
  id: ID!
  name: String!
  genre: [String]
  description: String
  avatar: S3Object
  creatorId: ID!
  creator: User! @connection(fields: ["creatorId"])
  clubCurrentBookId: ID
  currentBook: ClubBook @connection
  pastBooks: [ClubBook] @connection(keyName: "byClub", fields: ["id"])
  membershipCost: Int
  members: [Membership] @connection(keyName: "byClub", fields: ["id"])
  activity: [Activity] @connection(keyName: "byClub", fields: ["id"])
}

type Membership
  @model(queries: null)
  @key(name: "byClub", fields: ["clubId", "memberId"])
  @key(name: "byMember", fields: ["memberId", "clubId"]) {
  id: ID!
  clubId: ID!
  memberId: ID!
  club: Club! @connection(fields: ["clubId"])
  member: User! @connection(fields: ["memberId"])
}

type Peek
  @model
  @key(name: "byBook", fields: ["bookId"])
  @key(name: "byCreator", fields: ["creatorId"])
  @key(name: "byParent", fields: ["peekParentId"]) {
  id: ID!
  creatorId: ID!
  creator: User! @connection(fields: ["creatorId"])
  bookId: ID!
  book: ClubBook! @connection(fields: ["bookId"])
  cfiRange: String!
  quote: String!
  comment: String
  recording: S3Object
  peekParentId: ID
  parent: Peek @connection
  replies: [Peek] @connection(keyName: "byParent", fields: ["id"])
}

type User @model {
  id: ID!
  firstName: String!
  lastName: String!
  email: AWSEmail!
  avatar: S3Object
  clubOwnerships: [Club] @connection(keyName: "byCreator", fields: ["id"])
  clubMemberships: [Membership] @connection(keyName: "byMember", fields: ["id"])
  books: [ClubBook]
  peeks: [Peek] @connection(keyName: "byCreator", fields: ["id"])
}

# Types
type S3Object {
  name: String
  bucket: String!
  region: String!
  key: String!
}
```

I'm not entirely sure which part of the schema is causing the issue though I assume it's the optional connections: the peek inside of Activity, the currentBook inside of Club and the parent inside of Peek. Ideally these should remain optional.
