### ISSUE TITLE
amplify env <subcommands> fails with: Found whitespace in your key name ..

### ISSUE THREAD

**Issue by kjetilge** [aws-amplify/amplify-cli#5286]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
```amplify env <subcommand>``` fails and leaves the following trace:

```
amplify env list
Found whitespace in your key name (use quotes to include) at line 22,8 >>><<<<<<< HEAD
        ...
Error: Found whitespace in your key name (use quotes to include) at line 22,8 >>><<<<<<< HEAD
        ...
    at error (/Users/kjetilge/.nvm/versions/node/v14.8.0/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:41:11)
    at keyname (/Users/kjetilge/.nvm/versions/node/v14.8.0/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:157:76)
    at object (/Users/kjetilge/.nvm/versions/node/v14.8.0/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:353:15)
    at value (/Users/kjetilge/.nvm/versions/node/v14.8.0/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:391:24)
    at object (/Users/kjetilge/.nvm/versions/node/v14.8.0/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:358:23)
    at value (/Users/kjetilge/.nvm/versions/node/v14.8.0/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:391:24)
    at object (/Users/kjetilge/.nvm/versions/node/v14.8.0/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:358:23)
    at value (/Users/kjetilge/.nvm/versions/node/v14.8.0/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:391:24)
    at object (/Users/kjetilge/.nvm/versions/node/v14.8.0/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:358:23)
    at legacyRootValue (/Users/kjetilge/.nvm/versions/node/v14.8.0/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:428:38)
```

**Amplify CLI Version**
4.29.0

**To Reproduce**
It happened the first time after I tried the following from my repos dev branch:
```
git checkout test
amplify env checkout test -> Error!
```

**Expected behavior**
At least in the case of ```amplify env remove test``` - there should be no error.

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version v14.8.0

**Comment by attilah** [comment]
@kjetilge could you take a look at what you have in your `amplify/team-provider-info.json` file's 22nd line? That is that being read by `env list` command.

Perhaps paste the whole file as an attachment but redact the account specific information.

**Comment by kjetilge** [comment]
The file amplify/team-provider-info.json file had indeed the offending line 👍 😃. How did you know that ? 🤔

**Comment by attilah** [comment]
@kjetilge so you found the issue and it is solved? if so, please close the issue.

I knew this because `env list` is getting the list of environments for the project from that file and the error message told where is the error: `line 22, 8`.

**Comment by kjetilge** [comment]
Ah... right! 😃 - learn something new every day 😎

**Comment by tyrainman427** [comment]
@kjetilge what did you change to fix this error?

**Comment by kjetilge** [comment]
I had to resolve all the conflicts following a git merge. In this case I had to resolve conflicts with the updated team-provider-info.json file. But this happens any time conflicts aren't resolved.

**Comment by pashka4281** [comment]
I'm having this when with `!If` conditions when I'm using yml template (converted json => yml using cloudformation designer tool)
This fails:
```yml
      FunctionName: !If
        - ShouldNotCreateEnvResources
        - apiLambda
        - !Join ['', ['apiLambda-', !Ref env]]
          - ''
          - - apiLambda-
            - !Ref env
   ```
with the `- ShouldNotCreateEnvResources` being shown as the line that triggers it

While this form works:
```yml
FunctionName: !If [ShouldNotCreateEnvResources, apiLambda, !Join ['', ['apiLambda-', !Ref env]]]
```

Amplify 4.46.1


<img width="1332" alt="Screenshot 2021-03-24 at 22 06 02" src="https://user-images.githubusercontent.com/91559/112407830-22910800-8ced-11eb-8337-525424b543f2.png">

**Comment by paolo573** [comment]
@pashka4281 i am having the same issue when trying to simply `cfn_tools.load_yaml` the CF template for any function in amplify/backend/function, and then dump
`
dumper = cfn_flip.yaml_dumper.get_dumper(clean_up=True, long_form=False)
raw_markup = yaml.dump(
        markup,
        Dumper=dumper,
        default_flow_style=False,
        allow_unicode=True
)`

The array for `ShouldNotCreateEnvResources` condition seems to be the offender

@attilah should we create a new issue for this?

**Comment by SwaySway** [comment]
@pashka4281 @paolo573 
This yaml template issue looks separate then the original can you open a new issue for this? (with steps on how to repro as well)

**Comment by paolo573** [comment]
@SwaySway done: https://github.com/aws-amplify/amplify-cli/issues/7138
