### ISSUE TITLE
Cannot initialize a new Amplify project

### ISSUE THREAD

**Issue by cwinters8** [aws-amplify/amplify-cli#5320]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
I am getting an error when attempting to run `amplify init` from my project root.

**Amplify CLI Version**
4.29.1

**To Reproduce**
```
$ amplify init
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the environment dev
? Choose your default editor: Visual Studio Code
Using default provider  awscloudformation

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

? Do you want to use an AWS profile? Yes
? Please choose the profile you want to use obc
init failed
MissingRequiredParameter: Missing required key 'name' in params
    at ParamValidator.fail (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/param_validator.js:50:37)
    at ParamValidator.validateStructure (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/param_validator.js:61:14)
    at ParamValidator.validateMember (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/param_validator.js:88:21)
    at ParamValidator.validate (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/event_listeners.js:132:42)
    at Request.callListeners (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at callNextListener (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/event_listeners.js:86:9
    at finish (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js:386:7)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js:404:9 {
  code: 'MissingRequiredParameter',
  time: 2020-09-12T19:21:18.462Z
}
```

**Expected behavior**
`amplify init` should initialize a project as expected.

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Node Version: v14.9.0

**Comment by cwinters8** [comment]
I figured this out. Because I had previously set up hosting in us-west-1, I had an existing amplify directory in the root of my project. I removed this and was able to initialize successfully.

**Comment by James-Perrin** [comment]
Thank you!
