### ISSUE TITLE
TypeError: Cannot read property 'fields' of undefined

### ISSUE THREAD

**Issue by nezz0746** [aws-amplify/amplify-cli#5332]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
I am getting a TypeError: Cannot read property 'fields' of undefined when trying to run amplify codegen models. I suspect it has to do with my connections or the new objects i've created, i can't figure out what's wrong.

**Amplify CLI Version**
4.29.1

**To Reproduce**
I have added more objects to my schema and the ```amplify codegen models``` command gives me this:

```
Cannot read property 'fields' of undefined
TypeError: Cannot read property 'fields' of undefined
    at getConnectedField (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen-appsync-model-plugin/src/utils/process-connections.ts:99:41)
    at Object.processConnections (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen-appsync-model-plugin/src/utils/process-connections.ts:120:28)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen-appsync-model-plugin/src/visitors/appsync-visitor.ts:448:32
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen-appsync-model-plugin/src/visitors/appsync-visitor.ts:447:20
    at Array.forEach (<anonymous>)
    at AppSyncModelJavascriptVisitor.processConnectionDirective (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen-appsync-model-plugin/src/visitors/appsync-visitor.ts:446:34)
    at AppSyncModelJavascriptVisitor.processDirectives (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen-appsync-model-plugin/src/visitors/appsync-visitor.ts:241:10)
    at AppSyncModelJavascriptVisitor.generate (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen-appsync-model-plugin/src/visitors/appsync-javascript-visitor.ts:48:10)
    at Object.exports.plugin (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen-appsync-model-plugin/src/plugin.ts:49:20)
```

``` graphql
enum EmployeeType {
  ADMIN
  CHAIRMAN
  EMPLOYEE
}

enum CouponType {
  INT
  TEXT
  BOOLEAN
  PAYMENT
}

enum LifeStatus {
  VALIDATED
  REFUSED
  DRAFT
  TOVALIDATE
}

enum CircularStatus {
  ACCEPTED
  READ
  UNREAD
}

type Establishment @model {
  id: ID!
  name: String!
  description: String
  employees: [Employee] @connection
  children: [Child] @connection
}

type Employee @model {
  id: ID!
  type: EmployeeType!
  firstName: String!
  lastName: String!
}

type BroadcastList @model @versioned {
  id: ID!
  name: String
  description: String
  archived: Boolean
  employees: [Employee] @connection
  establishment: Establishment @connection
}

type Parent @model {
  id: ID!
  email: String
  firstName: String
  lastName: String
  phoneNumber: String
  pushTokens: [String]
  children: [Child] @connection
}

type Child @model {
  id: ID!
  firstName: String
  lastName: String
  inscriptionCode: String
  parents: [Parent] @connection
  birthdate: String
  subs: [Subscription] @connection
}

type Subscription @model {
  id: ID!
  childID: ID!
  broadcastlistID: ID!
}

type Circular @model @versioned {
  id: ID!
  title: String!
  body: String
  eventDate: AWSTimestamp
  limitDate: AWSTimestamp
  stage: Int
  author: Employee
  circularResponse: CircularResponse @connection
  circularResponseStats: CircularResponseStats
  broadcastlists: [BroadcastList] @connection
  establishment: Establishment @connection
  lifeStatus: LifeStatus
}

type CircularResponse @model {
  id: ID!
  circularStatus: CircularStatus
  responseDate: AWSTimestamp
  isKoool: Boolean
  parent: Parent @connection
  couponResponse: CouponResponse
}

type Coupon {
  label: String
  order: Int
  type: CouponType
}

type CouponResponse {
  answer: String
  displayedLabel: String
  order: Int
  type: CouponType
}

type CircularResponseStats {
  ACCEPTED: Int
  READ: Int
  UNREAD: Int
}
```

**Desktop (please complete the following information):**
 - OS: Mac 10.15.15
 - Node 12.16.3

**Comment by nezz0746** [comment]
Hi ! I've managed to isolate the issue by just selecting model-by-model and line-by-line. It seems to come from the Child model:

```graphql
type Child @model {
  id: ID!
  firstName: String
  lastName: String
  inscriptionCode: String
  parents: [Parent] @connection
  birthdate: String
  # subs: [Subscription] @connection
}

type Subscription @model {
  id: ID!
  childID: ID!
  broadcastlistID: ID!
}
```

**Comment by attilah** [comment]
@nezz0746 the problem in your case is that you are using the "reserved" type name `Subscription`. which is used by Amplify's GQL compilation to store the generated subscriptions. As you saw your type was modified and extended with generated operations:

```graphql
type Subscription {
  id: ID!
  childID: ID!
  broadcastlistID: ID!
  onCreateChild: Child @aws_subscribe(mutations: ["createChild"])
  onUpdateChild: Child @aws_subscribe(mutations: ["updateChild"])
  onDeleteChild: Child @aws_subscribe(mutations: ["deleteChild"])
  onCreateSubscription: Subscription @aws_subscribe(mutations: ["createSubscription"])
  onUpdateSubscription: Subscription @aws_subscribe(mutations: ["updateSubscription"])
  onDeleteSubscription: Subscription @aws_subscribe(mutations: ["deleteSubscription"])
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
}
```

The easiest workaround is to don't use a reserved type name in your schema. If you need to use that, then you have to provide an alternative assignment for the `subscription` operation in the `schema` like:

```gql
type MySubscriptionOverride {
  onCustom: String
}

type Query {
  CustomQuery: String
}

schema {
  query: Query
subscription: MySubscriptionOverride
}
```

The downside is that if you do not require custom queries and subscriptions GraphQL specification does not allow empty members, so using some prefix or suffix on the Subscription type seems to be the solution here.

As a fix I'm adding validation to check in the `@model` transformer to prevent such code failures you were seeing.

**Comment by nezz0746** [comment]
@attilah oooh i get it, it makes sense. That is what i ended up doing anyway because i had other subscriptions to add, but thanks for adding a message and so glad i could help on the issue, cheers!
