### ISSUE TITLE
Deployment Issue with aws-amplify/cli@4.29.2

### ISSUE THREAD

**Issue by drixta** [aws-amplify/amplify-cli#5353]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
Version 4.29.2 causes the bug bellow when deploying an amplify project

 TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
                                 at promisify (internal/util.js:214:11)
                                 at Object.<anonymous> (/root/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/extract-zip/index.js:11:18)

**Amplify CLI Version**
Version 4.29.2

**To Reproduce**
2020-09-18T06:48:13.387Z [INFO]: > @aws-amplify/cli@4.29.2 postinstall /root/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli
                                 > node scripts/post-install.js
2020-09-18T06:48:13.608Z [INFO]: 
2020-09-18T06:48:13.609Z [INFO]: ----------------------------------------
2020-09-18T06:48:13.609Z [INFO]: Successfully installed the Amplify CLI
                                 ----------------------------------------
                                 JavaScript Getting Started - https://docs.amplify.aws/start
                                 Android Getting Started - https://docs.amplify.aws/start/q/integration/android
                                 iOS Getting Started - https://docs.amplify.aws/start/q/integration/ios
                                 Amplify CLI collects anonymized usage data, which is used to help understand
                                 how to improve the product. If you don't wish to send anonymized Amplify CLI
                                 usage data to AWS, run amplify configure --usage-data-off  to opt-out.
                                 Learn more - https://docs.amplify.aws/cli/reference/usage-data
2020-09-18T06:48:13.659Z [WARNING]: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/@aws-amplify/cli/node_modules/chokidar/node_modules/fsevents):
                                    npm WARN
2020-09-18T06:48:13.660Z [WARNING]: notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
                                    npm WARN ws@7.3.1 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
                                    npm WARN ws@7.3.1 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
2020-09-18T06:48:13.664Z [INFO]: + @aws-amplify/cli@4.29.2
                                 added 1064 packages from 723 contributors in 31.875s
2020-09-18T06:48:13.694Z [INFO]: # Executing command: amplifyPush --simple
2020-09-18T06:48:13.699Z [INFO]: # Getting Amplify CLI Cloud-Formation stack info from environment cache
2020-09-18T06:48:13.706Z [INFO]: # Start initializing Amplify environment: master
2020-09-18T06:48:13.706Z [INFO]: STACKINFO={
                                 "awscloudformation": {
                                 "AuthRoleName": "amplify-blastapplication-master-x-authRole",
                                 "UnauthRoleArn": "arn:aws:iam::x:role/amplify-blastapplication-master-x-unauthRole",
                                 "AuthRoleArn": "arn:aws:iam::x:role/amplify-blastapplication-master-x-authRole",
                                 "Region": "us-east-2",
                                 "DeploymentBucketName": "amplify-blastapplication-master-x-deployment",
                                 "UnauthRoleName": "amplify-blastapplication-master-x-unauthRole",
                                 "StackName": "amplify-blastapplication-master-x",
                                 "StackId": "arn:aws:cloudformation:us-east-2:x:stack/amplify-blastapplication-master-x/2096f390-c338-11ea-adcd-06ffde09431c",
                                 "AmplifyAppId": "1231313123213"
                                 },
                                 "categories": {
                                 "auth": {
                                 "blastAuth": {}
                                 },
                                 "function": {
                                 "blastCustomApiHandler": {},
                                 "blastOauthCallback": {},
                                 "blastPostExecutor": {},
                                 "S3Trigger7ead5c51": {}
                                 }
                                 }
                                 }
                                 # Importing Amplify environment: master (amplify env import)
2020-09-18T06:48:14.568Z [INFO]: Scanning for plugins...
2020-09-18T06:48:14.608Z [INFO]: Plugin scan successful
2020-09-18T06:48:14.665Z [INFO]: Successfully added environment from your project
2020-09-18T06:48:14.878Z [INFO]: # Initializing existing Amplify environment: master (amplify init)
2020-09-18T06:48:15.829Z [INFO]: Note: It is recommended to run this command from the root of your app directory
2020-09-18T06:48:16.162Z [INFO]: init failed
2020-09-18T06:48:16.164Z [INFO]: /root/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/extract-zip/index.js:1
                                 TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
                                 at promisify (internal/util.js:214:11)
                                 at Object.<anonymous> (/root/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/extract-zip/index.js:11:18)
                                 at Object.Module._extensions..js (module.js:664:10)
2020-09-18T06:48:16.171Z [ERROR]: !!! Build failed
2020-09-18T06:48:16.171Z [ERROR]: !!! Non-Zero Exit Code detected
2020-09-18T06:48:16.171Z [INFO]: # Starting environment caching...
2020-09-18T06:48:16.172Z [INFO]: # Uploading environment cache artifact...
2020-09-18T06:48:16.239Z [INFO]: # Environment caching completed

**Expected behavior**
The build should work just fine. I had to bump down to 4.29.1 in my build for the build to succeed.

**Desktop (please complete the following information):**
 - Node Version. You can use `node -v` to check the node version on your system

node v8.12.0 (npm v6.4.1)

**Comment by mormsbee** [comment]
Also started seeing a similar issue as of Wednesday, Sep 16.

**Comment by UnleashedMind** [comment]
There are multiple possible workflows on the Amplify Console, I tried to connect a new app and I was not to reproduce. 
Could you give us more information on how to reproduce? Did you have an existing project deployed on Amplify Console?

**Comment by drixta** [comment]
> There are multiple possible workflows on the Amplify Console, I tried to connect a new app and I was not to reproduce.
> Could you give us more information on how to reproduce? Is this for an existing project already deployed on Amplify Console?
> Node v8.x has been deprecated, could you update the node version to v12.x and try again?

It does seem like it's an issue with using Node 8. I deployed with 4.29.2 under node 12 and things seem to be working again.
