### ISSUE TITLE
CLI crashes when trying to add an API using an existing file for the schema

### ISSUE THREAD

**Issue by kurtroberts** [aws-amplify/amplify-cli#5428]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
When adding an api, the cli crashes if you try to supply an existing file path.

**Amplify CLI Version**
4.24.3

**To Reproduce**
- amplify init
- answer the prompts
- amplify cli add
- fill out the first prompts with valid answers
- when prompted " Do you have an annotated GraphQL schema?" choose Yes
- supply a file path

Result is:
```Error: ENOENT: no such file or directory, copyfile '~/Desktop/schema.graphql' -> '/Users/.../Desktop/.../starting-over/amplify/backend/api/startingover/schema.graphql'
    at Object.copyFileSync (fs.js:1912:3)
    at serviceWalkthrough (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.js:165:8)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/index.js:176:3)
    at executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:158:7)
    at Object.executeCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:24:5)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/src/index.ts:61:5)
There was an error adding the API resource
```

**Expected behavior**
I expected it to validate the schema and continue the provisioning process.

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.6
 - Node Version. 14.3.0

**Additional context**
I've been struggling with DataStore syncing reliably and so have had to add and remove the api a number of times as the datamodel evolved.  This would be hugely helpful.

**Comment by attilah** [comment]
@kurtroberts what was in the previous line before the stacktrace? it seems that we error out when the CLI cannot copy the file at the given path. It must have been something like:

`
Error: ENOENT: no such file or directory, copyfile.......
`

**Comment by UnleashedMind** [comment]
I can not reproduce the issue with the latest CLI version. 
closing the issue for lack of response. feel free to open another issue if you are still blocked.
