### ISSUE TITLE
amplify init failed: ERR_INVALID_ARG_TYPE The 'request' argument must be string

### ISSUE THREAD

**Issue by drewmullen** [aws-amplify/amplify-cli#5606]
```bash
$ amplify --version && node --version && npm --version
4.29.8
v12.18.4
6.14.6
```

im not a js developer but im attempting to follow through this tutorial: https://github.com/aws-samples/aws-serverless-webapp-workshop . please let me know what other info i can provide

```bash
$ amplify init
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the environment prod
? Choose your default editor: Visual Studio Code
Using default provider  awscloudformation

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

? Do you want to use an AWS profile? Yes
? Please choose the profile you want to use ampdm
Adding backend environment prod to AWS Amplify Console app: dtxspv9qxsix
⠋ Initializing project in the cloud...

CREATE_IN_PROGRESS AuthRole                      AWS::IAM::Role             Fri Oct 16 2020 11:53:24 GMT-0400 (GMT-04:00) Resource creation Initiated
CREATE_IN_PROGRESS UnauthRole                    AWS::IAM::Role             Fri Oct 16 2020 11:53:23 GMT-0400 (GMT-04:00) Resource creation Initiated
CREATE_IN_PROGRESS DeploymentBucket              AWS::S3::Bucket            Fri Oct 16 2020 11:53:23 GMT-0400 (GMT-04:00)
CREATE_IN_PROGRESS AuthRole                      AWS::IAM::Role             Fri Oct 16 2020 11:53:23 GMT-0400 (GMT-04:00)
CREATE_IN_PROGRESS UnauthRole                    AWS::IAM::Role             Fri Oct 16 2020 11:53:23 GMT-0400 (GMT-04:00)
CREATE_IN_PROGRESS amplify-wildrydes-prod-115317 AWS::CloudFormation::Stack Fri Oct 16 2020 11:53:18 GMT-0400 (GMT-04:00) User Initiated
⠸ Initializing project in the cloud...

CREATE_IN_PROGRESS DeploymentBucket AWS::S3::Bucket Fri Oct 16 2020 11:53:24 GMT-0400 (GMT-04:00) Resource creation Initiated
⠙ Initializing project in the cloud...

CREATE_COMPLETE AuthRole   AWS::IAM::Role Fri Oct 16 2020 11:53:37 GMT-0400 (GMT-04:00)
CREATE_COMPLETE UnauthRole AWS::IAM::Role Fri Oct 16 2020 11:53:36 GMT-0400 (GMT-04:00)
⠹ Initializing project in the cloud...

CREATE_COMPLETE amplify-wildrydes-prod-115317 AWS::CloudFormation::Stack Fri Oct 16 2020 11:53:47 GMT-0400 (GMT-04:00)
CREATE_COMPLETE DeploymentBucket              AWS::S3::Bucket            Fri Oct 16 2020 11:53:45 GMT-0400 (GMT-04:00)
✔ Successfully created initial AWS cloud resources for deployments.
init failed
TypeError [ERR_INVALID_ARG_TYPE]: The 'request' argument must be string. Received type undefined
    at Object.onSuccess (/Users/drmullen/git/training/WildRydesVue/node_modules/@aws-amplify/cli/src/init-steps/s9-onSuccess.ts:26:26)
    at Object.exports.run (/Users/drmullen/git/training/WildRydesVue/node_modules/@aws-amplify/cli/src/commands/init.ts:24:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Object.executeAmplifyCommand (/Users/drmullen/git/training/WildRydesVue/node_modules/@aws-amplify/cli/src/index.ts:185:5)
    at executePluginModuleCommand (/Users/drmullen/git/training/WildRydesVue/node_modules/@aws-amplify/cli/src/execution-manager.ts:161:3)
    at Object.executeCommand (/Users/drmullen/git/training/WildRydesVue/node_modules/@aws-amplify/cli/src/execution-manager.ts:26:5)
```

id also like to note that it was a PITA getting the provider awscloudformation found. `scan` kept not finding it so i had to manually point to it with:
```bash
$ find ./ -name amplify-provider-awscloudformation -type d -exec realpath {} +
$ amplify plugin add awscloudformation
#provide absolute path when prompted
```
i can open a separate issue if that is interesting (?)

**Comment by yuth** [comment]
@drewmullen how did you install the Amplify CLI? Was it using NPX script or did you do an global install using `npm install -g @aws-amplify/cli`

**Comment by drewmullen** [comment]
`npm install @aws-amplify/cli`

**Comment by yuth** [comment]
Amplify CLI needs to be installed globally for it to work. You can install it globally by adding `-g` flag to install

**Comment by kaustavghosh06** [comment]
@drewmullen Please let us know if you're stuck after installing the CLI globally. Closing the issue for now.
