### ISSUE TITLE
Granting batch operation permission to a function

### ISSUE THREAD

**Issue by pedramp20** [aws-amplify/amplify-cli#5624]
When a function is added by CLI, if **API** is chosen for Question **"Do you want to access other resources in this project from your Lambda function?"** provided options are as follow:
 **( ) create
 ( ) read
 ( ) update
 ( ) delete**
these permissions are reflected in the function-paramerters.json.
However, if batch operations are needed to be performed from the Lambda function, the following error is thrown:

```
error creating post:  ApolloError: GraphQL error: Not Authorized to access batchCreateXXX on type Mutation
    at new ApolloError (/var/task/node_modules/apollo-client/bundle.umd.js:85:32)
    at Object.next (/var/task/node_modules/apollo-client/bundle.umd.js:890:37)
    at notifySubscription (/var/task/node_modules/zen-observable/lib/Observable.js:135:18)
    at onNotify (/var/task/node_modules/zen-observable/lib/Observable.js:179:3)
    at SubscriptionObserver.next (/var/task/node_modules/zen-observable/lib/Observable.js:235:7)
    at notifySubscription (/var/task/node_modules/zen-observable/lib/Observable.js:135:18)
    at onNotify (/var/task/node_modules/zen-observable/lib/Observable.js:179:3)
    at SubscriptionObserver.next (/var/task/node_modules/zen-observable/lib/Observable.js:235:7)
    at notifySubscription (/var/task/node_modules/zen-observable/lib/Observable.js:135:18)
    at onNotify (/var/task/node_modules/zen-observable/lib/Observable.js:179:3) {
  graphQLErrors: [
    {
      path: [Array],
      data: null,
      errorType: 'Unauthorized',
      errorInfo: null,
      locations: [Array],
      message: 'Not Authorized to access batchCreateXXX on type Mutation'
    }
  ],
  networkError: null,
  extraInfo: undefined
}
```

This would not be resolved, if batchCreate is manually added to the function-parameters.json as I assume no IAM role for the batch operation is created and attached to the function role.

Please note that the batch operations are defined as custom resolvers and they work fine if called directly from the application.

**Comment by UnleashedMind** [comment]
@pedramp20 
We need more information to investigate this issue:
What is the auth type(s) that you set up when you add/update your GraphQL API? 
What does the GraphQL API's schema look like? did you use @auth directive?
How did you configure the appsync client, e.g. did you log in the UserPool as a user and then use its credentials to configure the client?

**Comment by kaustavghosh06** [comment]
Closing due to lack of response.
