### ISSUE TITLE
All builds/deploys fail after change to amplify.yml

### ISSUE THREAD

**Issue by tomhirschfeld** [aws-amplify/amplify-cli#5656]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
I made a change to amplify.yml to allow cypress testing, and now all of my builds are failing because amplify init cannot find src/package.json on a lambda layer

logs:

```
                                 }
                                 # Importing Amplify environment: master (amplify env import)
2020-10-22T00:25:29.933Z [INFO]: Successfully added environment from your project
2020-10-22T00:25:30.059Z [INFO]: # Initializing existing Amplify environment: master (amplify init)
2020-10-22T00:25:33.376Z [INFO]: Note: It is recommended to run this command from the root of your app directory
2020-10-22T00:25:36.460Z [WARNING]: - Initializing your environment: master
2020-10-22T00:25:37.443Z [WARNING]: ✔ Initialized provider successfully.
2020-10-22T00:25:50.476Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
2020-10-22T00:25:50.478Z [WARNING]: ✖ There was an error initializing your environment.
2020-10-22T00:25:50.479Z [INFO]: init failed
                                 { Error: ENOENT: no such file or directory, stat '/codebuild/output/src178161676/src/wesponsored-web/amplify/backend/function/shared/src/package.json'
                                 at Object.statSync (fs.js:855:3)
                                 at Object.statSync (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/graceful-fs/polyfills.js:308:16)
                                 at buildResource (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/build-resources.js:23:30)
                                 at packageResource (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/push-resources.js:215:12)
                                 at packageResources (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/push-resources.js:269:19)
                                 at Object.run (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/push-resources.js:35:10)
                                 at Object.pushResources (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/index.js:32:25)
                                 at providerPushTasks.push (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/src/lib/initialize-env.js:81:53)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/promise-sequential/index.js:16:18
                                 at process._tickCallback (internal/process/next_tick.js:68:7)
                                 errno: -2,
                                 syscall: 'stat',
                                 code: 'ENOENT',
                                 path:
                                 '/codebuild/output/src178161676/src/wesponsored-web/amplify/backend/function/shared/src/package.json' }
2020-10-22T00:25:53.759Z [INFO]: Note: It is recommended to run this command from the root of your app directory
2020-10-22T00:25:54.963Z [WARNING]: - Initializing your environment: master
2020-10-22T00:25:55.858Z [WARNING]: ✔ Initialized provider successfully.
2020-10-22T00:26:06.124Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
2020-10-22T00:26:06.125Z [WARNING]: ✖ There was an error initializing your environment.
2020-10-22T00:26:06.125Z [INFO]: init failed
2020-10-22T00:26:06.126Z [INFO]: { Error: ENOENT: no such file or directory, stat '/codebuild/output/src178161676/src/wesponsored-web/amplify/backend/function/shared/src/package.json'
                                 at Object.statSync (fs.js:855:3)
                                 at Object.statSync (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/graceful-fs/polyfills.js:308:16)
                                 at buildResource (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/build-resources.js:23:30)
                                 at packageResource (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/push-resources.js:215:12)
                                 at packageResources (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/push-resources.js:269:19)
                                 at Object.run (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/push-resources.js:35:10)
                                 at Object.pushResources (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/index.js:32:25)
                                 at providerPushTasks.push (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/src/lib/initialize-env.js:81:53)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/promise-sequential/index.js:16:18
                                 at process._tickCallback (internal/process/next_tick.js:68:7)
                                 errno: -2,
                                 syscall: 'stat',
                                 code: 'ENOENT',
                                 path:
                                 '/codebuild/output/src178161676/src/wesponsored-web/amplify/backend/function/shared/src/package.json' }
2020-10-22T00:26:06.145Z [ERROR]: !!! Build failed
2020-10-22T00:26:06.145Z [ERROR]: !!! Non-Zero Exit Code detected
2020-10-22T00:26:06.145Z [INFO]: # Starting environment caching...
2020-10-22T00:26:06.145Z [INFO]: # Uploading environment cache artifact...
2020-10-22T00:26:06.244Z [INFO]: # Environment caching completed
```

**Amplify CLI Version**
4.30.0

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu]
 - Node Version. You can use `node -v` to check the node version on your system

**Additional context**

**Comment by tomhirschfeld** [comment]
to clarify, the file it is looking for `{ Error: ENOENT: no such file or directory, stat '/codebuild/output/src178161676/src/wesponsored-web/amplify/backend/function/shared/src/package.json'` is part of a lambda layer, so src/package.json doesn't exist, and hasn't existed

**Comment by tomhirschfeld** [comment]
seems to be working again, needed to set CLI version from 4.30.0 to 4.29.0

**Comment by kaustavghosh06** [comment]
@tomhirschfeld Are you still stuck with v4.29.0 or were you able to mitigate this issue with a later version of the CLI?
