### ISSUE TITLE
Can't remove function created by the "Email Verification Link with Redirect" option

### ISSUE THREAD

**Issue by yaquawa** [aws-amplify/amplify-cli#5778]
**Describe the bug**
I have reported an issue related on the [Email Verification Link with Redirect](https://github.com/aws-amplify/amplify-cli/issues/5720) option before. Seems like the is a non working option? I tired to delete it by `amplify function remove`, but error occurred.

**Amplify CLI Version**
4.32.0

**To Reproduce**
```
amplify auth update
...
...
 Do you want to enable any of the following capabilities? (Press <space> to select, <a> to toggle all, <i> to invert selection)
 ◯ Add Google reCaptcha Challenge
❯ ● Email Verification Link with Redirect
 ◯ Add User to Group
 ◯ Email Domain Filtering (blacklist)
 ◯ Email Domain Filtering (whitelist)
 ◯ Custom Auth Challenge Flow (basic scaffolding - not for production)

amplify auth push
...
...
amplify function remove
? Choose the resource you would want to remove demoproject2713aa05CustomMessage (function)

? Are you sure you want to delete the resource? This action deletes all files related to this resource from the backend directory. Yes
Resource cannot be removed because it has a dependency on another resource
Dependency: Cognito:demoproject2713aa05
Error: Resource cannot be removed because it has a dependency on another resource
    at /Users/x/.npm-global/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/remove-resource.js:128:31
    at Array.forEach (<anonymous>)
    at /Users/x/.npm-global/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/remove-resource.js:124:40
    at Array.forEach (<anonymous>)
    at deleteResourceFiles (/Users/x/.npm-global/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/remove-resource.js:122:22)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.executeAmplifyCommand (/Users/x/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/lib/index.js:193:5)
    at async executePluginModuleCommand (/Users/x/.npm-global/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:153:5)
    at async Object.executeCommand (/Users/x/.npm-global/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:35:9)
    at async Object.run (/Users/x/.npm-global/lib/node_modules/@aws-amplify/cli/lib/index.js:82:9)
An error occurred when removing the function resource
```
**Desktop (please complete the following information):**
 - OS: MacOS
 - Node Version: v14.11.0

**Comment by akshbhu** [comment]
Hi @yaquawa 

From the error it seems your function has dependency on Auth category. If you check your ```amplify-meta.json``` you can see that auth category ```Cognito:demoproject2713aa05``` has a dependency on your function resource```demoproject2713aa05CustomMessage```

``` json
  "auth": {
    "demoproject2713aa05": {
      "service": "Cognito",
      "providerPlugin": "awscloudformation",
      "dependsOn": [
        {
          "category": "function",
          "resourceName": "demoproject2713aa05CustomMessage",
          "triggerProvider": "Cognito",
          "attributes": [
            "Arn",
            "Name"
          ]
        }
```

To resolve this , you need to remove auth category first and then try to remove the function again.

Let me know if this works for you?

**Comment by yaquawa** [comment]
@akshbhu I don't want to remove auth category. Is there any way to remove the `demoproject2713aa05CustomMessage` only?

**Comment by akshbhu** [comment]
Hi @yaquawa 

One thing you can do is try ```amplify update auth``` and select  ```manual configuration``` and deselect your ```email verification``` . After this setup you will be able to delete function as above step removes dependency.

Let me know if this works for you?
