### ISSUE TITLE
Deploys to remote envs on amplify console fail after canceling a deploy

### ISSUE THREAD

**Issue by tomhirschfeld** [aws-amplify/amplify-cli#5781]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
All attempted deploys to our production environment now fail with this log output:
```
                                 # Starting phase: build
                                 # Executing command: amplifyPush --simple
2020-11-05T05:37:03.826Z [INFO]: # Getting Amplify CLI Cloud-Formation stack info from environment cache
2020-11-05T05:37:03.832Z [INFO]: # Start initializing Amplify environment: master
2020-11-05T05:37:03.832Z [INFO]: STACKINFO={
                                 "awscloudformation": {
                                 "AuthRoleName": "amplify-wesponsored-web-master-213421-authRole",
                                 "UnauthRoleArn": "arn:aws:iam::272407951964:role/amplify-wesponsored-web-master-213421-unauthRole",
                                 "AuthRoleArn": "arn:aws:iam::272407951964:role/amplify-wesponsored-web-master-213421-authRole",
                                 "Region": "us-east-2",
                                 "DeploymentBucketName": "amplify-wesponsored-web-master-213421-deployment",
                                 "UnauthRoleName": "amplify-wesponsored-web-master-213421-unauthRole",
                                 "StackName": "amplify-wesponsored-web-master-213421",
                                 "StackId": "arn:aws:cloudformation:us-east-2:272407951964:stack/amplify-wesponsored-web-master-213421/046c4ab0-131c-11eb-b776-0296ed261c1a",
                                 "AmplifyAppId": "d1he6253vtkqx8"
                                 },
                                 "categories": {
                                 "auth": {
                                 "wesponsoredweb1966eb90": {}
                                 },
                                 "function": {
                                 "AdminQueries4d02c163": {},
                                 "userApprovalNotification": {},
                                 "userCampaignNotificationSender": {},
                                 "userConfirmationDynamoOnboarding": {},
                                 "userModelBackfill": {},
                                 "userProfileCreationEmailTrigger": {},
                                 "paypalPayout": {},
                                 "createCardForUserCampaign": {},
                                 "campaignReportGenerator": {},
                                 "cronCampaignNotificationSender": {},
                                 "shared": {},
                                 "authorizationRectifier": {},
                                 "listCampaignsForUser": {},
                                 "requestUserCampaignCreation": {},
                                 "campaignVisibilityActivityTrigger": {},
                                 "addReviews": {}
                                 }
                                 }
                                 }
                                 # Importing Amplify environment: master (amplify env import)
2020-11-05T05:37:06.962Z [INFO]: Successfully added environment from your project
2020-11-05T05:37:07.079Z [INFO]: # Initializing existing Amplify environment: master (amplify init)
2020-11-05T05:37:10.211Z [INFO]: Note: It is recommended to run this command from the root of your app directory
2020-11-05T05:37:14.078Z [WARNING]: - Initializing your environment: master
2020-11-05T05:37:15.175Z [WARNING]: ✔ Initialized provider successfully.
2020-11-05T05:37:29.903Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
2020-11-05T05:37:29.907Z [WARNING]: ✖ There was an error initializing your environment.
2020-11-05T05:37:29.908Z [INFO]: init failed
                                 { Error: ENOENT: no such file or directory, stat '/codebuild/output/src308321143/src/wesponsored-web/amplify/backend/function/shared/src/package.json'
                                 at Object.statSync (fs.js:855:3)
                                 at Object.statSync (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/graceful-fs/polyfills.js:308:16)
                                 at buildResource (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/build-resources.js:23:30)
                                 at packageResource (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/push-resources.js:215:12)
                                 at packageResources (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/push-resources.js:269:19)
                                 at Object.run (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/push-resources.js:35:10)
                                 at Object.pushResources (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/index.js:32:25)
                                 at providerPushTasks.push (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/src/lib/initialize-env.js:81:53)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/promise-sequential/index.js:16:18
                                 at process._tickCallback (internal/process/next_tick.js:68:7)
                                 errno: -2,
                                 syscall: 'stat',
                                 code: 'ENOENT',
                                 path:
                                 '/codebuild/output/src308321143/src/wesponsored-web/amplify/backend/function/shared/src/package.json' }
2020-11-05T05:37:33.117Z [INFO]: Note: It is recommended to run this command from the root of your app directory
2020-11-05T05:37:34.297Z [WARNING]: - Initializing your environment: master
2020-11-05T05:37:35.948Z [WARNING]: ✔ Initialized provider successfully.
2020-11-05T05:37:47.832Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
2020-11-05T05:37:47.833Z [WARNING]: ✖ There was an error initializing your environment.
2020-11-05T05:37:47.833Z [INFO]: init failed
```
"shared" is a lambda layer
this started after I cancelled a build using the cancel functionality on the console.

**Comment by tomhirschfeld** [comment]
Looks like we might be failing this check here in amplify cli


https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-provider-awscloudformation/src/push-resources.js
```
function packageResources(context, resources) {
  // Only build and package resources which are required
  resources = resources.filter(resource => resource.build);

  const packageResource = (context, resource) => {
    let s3Key;
    return (resource.service === FunctionServiceName.LambdaLayer ? packageLayer(context, resource) : buildResource(context, resource))
      .then(result => {
        // Upload zip file to S3
        s3Key = `amplify-builds/${result.zipFilename}`;
        return S3.getInstance(context).then(s3 => {
          const s3Params = {
            Body: fs.createReadStream(result.zipFilePath),
            Key: s3Key,
          };
          return s3.uploadFile(s3Params);
        });
      })

```

I attempted to add a package.json and src directory and it failed iwth the following message:

```
2020-11-05T07:57:47.736Z [WARNING]: ✔ Initialized provider successfully.
2020-11-05T07:58:03.934Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
2020-11-05T07:58:03.939Z [WARNING]: ✖ There was an error initializing your environment.
2020-11-05T07:58:03.940Z [INFO]: init failed
                                 TypeError: Cannot read property 'Type' of undefined
                                 at buildResource.then.then (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/push-resources.js:250:46)
                                 at process._tickCallback (internal/process/next_tick.js:68:7)
2020-11-05T07:58:07.183Z [INFO]: Note: It is recommended to run this command from the root of your app directory
2020-11-05T07:58:08.349Z [WARNING]: - Initializing your environment: master
2020-11-05T07:58:09.231Z [WARNING]: ✔ Initialized provider successfully.
2020-11-05T07:58:22.068Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
2020-11-05T07:58:22.070Z [WARNING]: ✖ There was an error initializing your environment.
2020-11-05T07:58:22.070Z [INFO]: init failed
2020-11-05T07:58:22.070Z [INFO]: TypeError: Cannot read property 'Type' of undefined
                                 at buildResource.then.then (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/push-resources.js:250:46)
                                 at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by tomhirschfeld** [comment]
I have tried with multiple versions of CLI in build, 4.32, 4.29, 4.17, no change

**Comment by akshbhu** [comment]
Hi @tomhirschfeld 

> this started after I cancelled a build using the cancel functionality on the console.

Can you elaborate more on this? It seems it used to work until you cancelled a build using console.

Also may I know what categories you added in your project?

**Comment by tomhirschfeld** [comment]
@akshbhu 

I pressed the cancel button on the deploy shortly after it started teh build phase and the build stopped. 
We are using
Auth, Function, Storage, and the graphql API

Logs for the cancelled thing are:

```
                                 # Starting phase: build
                                 # Executing command: amplifyPush --simple
2020-11-05T05:20:48.088Z [INFO]: # Getting Amplify CLI Cloud-Formation stack info from environment cache
2020-11-05T05:20:48.094Z [INFO]: # Start initializing Amplify environment: master
2020-11-05T05:20:48.094Z [INFO]: STACKINFO={
                                 "awscloudformation": {
                                 "AuthRoleName": "amplify-wesponsored-web-master-213421-authRole",
                                 "UnauthRoleArn": "arn:aws:iam::272407951964:role/amplify-wesponsored-web-master-213421-unauthRole",
                                 "AuthRoleArn": "arn:aws:iam::272407951964:role/amplify-wesponsored-web-master-213421-authRole",
                                 "Region": "us-east-2",
                                 "DeploymentBucketName": "amplify-wesponsored-web-master-213421-deployment",
                                 "UnauthRoleName": "amplify-wesponsored-web-master-213421-unauthRole",
                                 "StackName": "amplify-wesponsored-web-master-213421",
                                 "StackId": "arn:aws:cloudformation:us-east-2:272407951964:stack/amplify-wesponsored-web-master-213421/046c4ab0-131c-11eb-b776-0296ed261c1a",
                                 "AmplifyAppId": "d1he6253vtkqx8"
                                 },
                                 "categories": {
                                 "auth": {
                                 "wesponsoredweb1966eb90": {}
                                 },
                                 "function": {
                                 "AdminQueries4d02c163": {},
                                 "userApprovalNotification": {},
                                 "userCampaignNotificationSender": {},
                                 "userConfirmationDynamoOnboarding": {},
                                 "userModelBackfill": {},
                                 "userProfileCreationEmailTrigger": {},
                                 "paypalPayout": {},
                                 "createCardForUserCampaign": {},
                                 "campaignReportGenerator": {},
                                 "cronCampaignNotificationSender": {},
                                 "shared": {},
                                 "authorizationRectifier": {},
                                 "listCampaignsForUser": {},
                                 "requestUserCampaignCreation": {},
                                 "campaignVisibilityActivityTrigger": {},
                                 "addReviews": {}
                                 }
                                 }
                                 }
                                 # Importing Amplify environment: master (amplify env import)
2020-11-05T05:20:51.213Z [INFO]: Successfully added environment from your project
2020-11-05T05:20:51.332Z [INFO]: # Initializing existing Amplify environment: master (amplify init)
2020-11-05T05:20:54.440Z [INFO]: Note: It is recommended to run this command from the root of your app directory
2020-11-05T05:20:58.727Z [WARNING]: - Initializing your environment: master

**Comment by akshbhu** [comment]
Hi @tomhirschfeld 

Thanks for the response. 

One more thing, Is the same codebase working fine before you can cancelled and started again or have you done some changes after you cancelled the build?

**Comment by tomhirschfeld** [comment]
@akshbhu 

Yes,
Codebase was working fine. I can still push to my dev environments too, its just the remote builds in master and production that fail. If you want I can send you temp credentials to see first hand what is going on.

**Comment by tomhirschfeld** [comment]
it turned out we were setting the amplify version incorrectly, and the cli version was being set to the original version, like 1.1.12 or something

**Comment by akshbhu** [comment]
Are you talking about version in amplify.yml file?

**Comment by akshbhu** [comment]
Hi @tomhirschfeld 

One thing you can try as workaround is to set an environment variable for amplify version  in App settings in the console.
```
VERSION_AMPLIFY=4.32.0
```

Let me know if that works for you?

**Comment by adamMo** [comment]
@akshbhu I did set the variable in `/settings/variables` in console and in the build script, everytime `amplify version` is 1.12.0, am I missing something?

**Comment by akshbhu** [comment]
Are you doing that in AppSettings and under that section there will be environment variables?

**Comment by adamMo** [comment]
@akshbhu correct!

**Comment by akshbhu** [comment]
Hi @adamMo and @tomhirschfeld 

1) Are you guys using custom buildscript on console?

2) Have you modified the ```amplify version``` in the buildscript?

**Comment by adamMo** [comment]
@akshbhu Just like I wrote in #5791 I just had `amplifyPush -e dev` and no matter what I set in variables in console, the version stayed the same because.

**Comment by kaustavghosh06** [comment]
@tomhirschfeld Glad to know that you were able to resolve your issue by updating the CLI version in the Amplify Console Build settings.
@adamMo  You can read more about how to set build settings for the Console and updating the Amplify CLI version out here - https://docs.aws.amazon.com/amplify/latest/userguide/custom-build-image.html
