### ISSUE TITLE
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator)) in amplify push log

### ISSUE THREAD

**Issue by kylekirkby** [aws-amplify/amplify-cli#5841]
**Describe the bug**
I started a new amplify project and added `auth` and `cognito user groups`. Upon pushing these changes I'm now getting
```bash
⠋ Updating resources in the cloud. This may take a few minutes...TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at getUniqueStacksEvents (/home/god/.nvm/versions/node/v14.10.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js:477:24)
    at /home/god/.nvm/versions/node/v14.10.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js:129:30
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:27683) UnhandledPromiseRejectionWarning: UnknownEndpoint: Inaccessible host: `cloudformation.us-east-1.amazonaws.com'. This service may not be available in the `us-east-1' region.
    at Request.ENOTFOUND_ERROR (/home/god/.nvm/versions/node/v14.10.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/event_listeners.js:507:46)
    at Request.callListeners (/home/god/.nvm/versions/node/v14.10.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/god/.nvm/versions/node/v14.10.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/god/.nvm/versions/node/v14.10.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:688:14)
    at ClientRequest.error (/home/god/.nvm/versions/node/v14.10.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/event_listeners.js:339:22)
    at ClientRequest.<anonymous> (/home/god/.nvm/versions/node/v14.10.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/http/node.js:96:19)
    at ClientRequest.emit (events.js:314:20)
    at ClientRequest.EventEmitter.emit (domain.js:486:12)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:314:20)
(node:27683) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
⠧ Updating resources in the cloud. This may take a few minutes...TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at getUniqueStacksEvents (/home/god/.nvm/versions/node/v14.10.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js:477:24)
    at /home/god/.nvm/versions/node/v14.10.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js:129:30
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:27683) UnhandledPromiseRejectionWarning: UnknownEndpoint: Inaccessible host: `cloudformation.us-east-1.amazonaws.com'. This service may not be available in the `us-east-1' region.
    at Request.ENOTFOUND_ERROR (/home/god/.nvm/versions/node/v14.10.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/event_listeners.js:507:46)
    at Request.callListeners (/home/god/.nvm/versions/node/v14.10.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/god/.nvm/versions/node/v14.10.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/god/.nvm/versions/node/v14.10.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:688:14)
    at ClientRequest.error (/home/god/.nvm/versions/node/v14.10.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/event_listeners.js:339:22)
    at ClientRequest.<anonymous> (/home/god/.nvm/versions/node/v14.10.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/http/node.js:96:19)
    at ClientRequest.emit (events.js:314:20)
    at ClientRequest.EventEmitter.emit (domain.js:486:12)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:314:20)
(node:27683) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
```
**Amplify CLI Version**
4.32.1

**Expected behavior**
No TypeError.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 on WSL (Windows 10)
 - Node Version:  v14.10.1

**Comment by nikhname** [comment]
@kylekirkby Could you specify settings you chose when adding auth?

**Comment by kylekirkby** [comment]
@nikhname 

```bash
amplify add auth

? Do you want to use the default authentication and security configuration? Default configuration
? How do you want users to be able to sign in? Username
? Do you want to configure advanced settings? No, I am done.
```

Also, I believe I added add-to-group functionality.

**Comment by rajrajhans** [comment]
> @nikhname
> 
> https://dev.to/dabit3/the-complete-guide-to-next-js-authentication-2aco
> 
> ```shell
> amplify add auth
> 
> ? Do you want to use the default authentication and security configuration? Default configuration
> ? How do you want users to be able to sign in? Username
> ? Do you want to configure advanced settings? No, I am done.
> ```
> 
> Also, I believe I added add-to-group functionality.

I tried to reproduce by following these steps (added user groups as well), however, `amplify push` completed successfully without any error. My Amplify CLI version is 4.43.0. @kylekirkby are you still facing this issue in the latest version of the CLI?

**Comment by kylekirkby** [comment]
@rajrajhans - I have seen some random stack traces on occasion. But sadly, I did not keep a log of the exact message. I'll open an issue/add to this if I see it again. Cheers!

**Comment by ammarkarachi** [comment]
Closing in favor of https://github.com/aws-amplify/amplify-cli/issues/6660
