### ISSUE TITLE
Cannot add <lambda_name> due to a cyclic dependency

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#5880]
**Describe the bug**
I have a pre token generation lambda, and I want to give it update permission to the cognito auth resource. I did `amplify function update` and answered the questions to do that, at the end I got this error: 

I still did an amplify push, and at the end the auth environment variable "AUTH_<redact>_USERPOOLID" was incorrectly set to the literal string "auth<redact>UserPoolId"

```
% amplify update function
? Select which capability you want to update: Lambda function (serverless function)
? Select the Lambda function you want to update <redact>PreTokenGeneration
? Do you want to update the Lambda function permissions to access other resources in this project? Yes
? Select the category auth
Auth category has a resource called <redact>
? Select the operations you want to permit for <redact> update

You can access the following resource attributes as environment variables from your Lambda function
	AUTH_<redact>_USERPOOLID
? Do you want to invoke this function on a recurring schedule? No
? Do you want to configure Lambda layers for this function? No
Error: Cannot add <redact>PreTokenGeneration due to a cyclic dependency
    at checkForCyclicDependencies (/Users/hisham/.nvm/versions/node/v13.14.0/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/update-amplify-meta.js:199:15)
    at AmplifyToolkit.updateamplifyMetaAfterResourceUpdate [as _updateamplifyMetaAfterResourceUpdate] (/Users/hisham/.nvm/versions/node/v13.14.0/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/update-amplify-meta.js:116:9)
    at updateFunctionResource (/Users/hisham/.nvm/versions/node/v13.14.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/index.js:144:29)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.executeAmplifyCommand (/Users/hisham/.nvm/versions/node/v13.14.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/lib/index.js:193:5)
    at async executePluginModuleCommand (/Users/hisham/.nvm/versions/node/v13.14.0/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:153:5)
    at async Object.executeCommand (/Users/hisham/.nvm/versions/node/v13.14.0/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:35:9)
    at async Object.run (/Users/hisham/.nvm/versions/node/v13.14.0/lib/node_modules/@aws-amplify/cli/lib/index.js:82:9)
```

**Amplify CLI Version**
4.32.1

**Comment by hisham** [comment]
Is it because the auth resource itself depends on pre-token generation lambda? So then pre-token generation lambda can't reference the actual user pool id and there's where you get the cyclic dependency?

**Comment by hisham** [comment]
Ok I believe this is a duplicate of https://github.com/aws-amplify/amplify-cli/issues/2303. Will try the workarounds described there. Closing this issue.
