### ISSUE TITLE
After upgrade to npm install -g @aws-amplify/cli@multienv - credential errors

### ISSUE THREAD

**Issue by oldnerd** [aws-amplify/amplify-cli#590]
**Describe the bug**
after upgrading to  multienv version of the CLI via "npm install -g @aws-amplify/cli@multienv.", operations all fail with  Root stack creation failed
init fail with NOENT: no such file or directory, open 'C:\Users\Admin\.aws\credentials

 Init of new stack.
 Delete of existing stack.

 amplify status command worked, as did migrate.

Stack trace from init:
{ Error: ENOENT: no such file or directory, open 'C:\Users\Admin\.aws\credentials'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:348:35)
    at Object.readFileSync (C:\Users\Admin\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-provider-awscloudformation\node_modules\aws-sdk\lib\util.js:95:26)
    at IniLoader.parseFile (C:\Users\Admin\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-provider-awscloudformation\node_modules\aws-sdk\lib\shared-ini\ini-loader.js:7:40)
    at IniLoader.loadFrom (C:\Users\Admin\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-provider-awscloudformation\node_modules\aws-sdk\lib\shared-ini\ini-loader.js:56:46)
    at Config.region (C:\Users\Admin\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-provider-awscloudformation\node_modules\aws-sdk\lib\node_loader.js:99:36)
    at Config.set (C:\Users\Admin\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-provider-awscloudformation\node_modules\aws-sdk\lib\config.js:476:39)
    at Config.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-provider-awscloudformation\node_modules\aws-sdk\lib\config.js:311:12)
    at Config.each (C:\Users\Admin\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-provider-awscloudformation\node_modules\aws-sdk\lib\util.js:484:32)
    at new Config (C:\Users\Admin\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-provider-awscloudformation\node_modules\aws-sdk\lib\config.js:310:19)
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\Admin\\.aws\\credentials' }

**Expected behavior**
new project, delete of existing project, etc.  Dependent on command

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Windows
 - Browser Chrome
 - Version Windows 10 OS.
.

**Comment by CriPstian** [comment]
Encountered this problem when triggering `amplify init` inside a new project.
The option `? Do you want to use an AWS profile? => No` should not be possible and the cli should maybe skip it and set the `default` profile for the user.

**Comment by UnleashedMind** [comment]
@CriPstian 
The cli allows the user to enter keys directly.

**Comment by UnleashedMind** [comment]
closing this issue for now, feel free to reopen it if you still see problem.

**Comment by amarpulli1994** [comment]
I'm also having the same issue after second time run  `amplify configure` and without configure anything in console.aws.amazon.com.

```
ENOENT: no such file or directory, open 'C:\Users\user\.aws\credentials'
C:\Users\user\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\util.js:1
Error: ENOENT: no such file or directory, open 'C:\Users\user\.aws\credentials'
    at Object.openSync (fs.js:443:3)
    at Proxy.readFileSync (fs.js:343:35)
    at Object.readFileSync (C:\Users\user\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\util.js:95:26)
    at IniLoader.parseFile (C:\Users\user\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\shared-ini\ini-loader.js:6:47)
    at IniLoader.loadFrom (C:\Users\user\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\shared-ini\ini-loader.js:56:30)
    at Config.region (C:\Users\user\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\node_loader.js:100:36)
    at Config.set (C:\Users\user\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\config.js:485:39)
    at Config.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\config.js:320:12)
    at Config.each (C:\Users\user\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\util.js:507:32)
    at new Config (C:\Users\user\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\config.js:319:19)
```
please can anyone share how to resolve it.

Thanks ,
Amar.

**Comment by JxDarkAngel** [comment]
You have to install **aws**, the following link explains how to:

[https://medium.com/@yogeshdarji99/steps-to-install-awscli-on-mac-5bad783483a](url)

And then execute the command: **aws configure**
More information in the next link
[https://docs.aws.amazon.com/es_es/cli/latest/userguide/cli-chap-configure.html](url)
