### ISSUE TITLE
Error: EEXIST: file already exists, symlink '../semver/bin/semver' 

### ISSUE THREAD

**Issue by jesse-bonzo** [aws-amplify/amplify-cli#595]
When my project is being built in the amplify console I see the following error:

```
2018-12-17T19:42:48.287Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
2018-12-17T19:42:48.289Z [WARNING]: ✖ There was an error initializing your environment.
2018-12-17T19:42:48.290Z [INFO]: init failed
2018-12-17T19:42:48.292Z [INFO]: { Error: EEXIST: file already exists, symlink '../semver/bin/semver' -> '/codebuild/output/src313418654/src/bespin/amplify/#current-cloud-backend/function/casesForPropertyResolver/src/node_modules/.bin/semver'
    at Object.fs.symlinkSync (fs.js:1014:18)
    at onLink (/root/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:147:15)
    at getStats (/root/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:48:40)
    at startCopy (/root/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:37:10)
    at copyDirItem (/root/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:134:10)
    at fs.readdirSync.forEach.item (/root/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:127:39)
    at Array.forEach (<anonymous>)
    at copyDir (/root/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:127:23)
    at mayCopyDir (/root/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:117:10)
    at onDir (/root/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:108:12)
  errno: -17,
  code: 'EEXIST',
  syscall: 'symlink',
  path: '../semver/bin/semver',
  dest: '/codebuild/output/src313418654/src/bespin/amplify/#current-cloud-backend/function/casesForPropertyResolver/src/node_modules/.bin/semver' }
2018-12-17T19:42:48.304Z [ERROR]: !!! Build failed
2018-12-17T19:42:48.443Z [ERROR]: !!! Non-Zero Exit Code detected
2018-12-17T19:42:48.443Z [INFO]: # Starting Environment Caching...
2018-12-17T19:42:48.443Z [INFO]: Uploading environment cache artifact...
2018-12-17T19:42:48.606Z [INFO]: # Environment Caching completed
```

I am using the multienv branch of the amplify CLI, version "0.2.1-multienv.11". 
This doesn't seem to happen with every branch I have configured, but it does happen randomly with my development branch.

My amplify.yml looks like:
```
version: 0.1
backend:
  phases:
    # IMPORTANT - Please verify your build commands
    build:
      commands:
        - "# Get Amplify CLI Cloud-Formation stack info from environment cache"
        - export STACKINFO="$(envCache --get stackInfo)"
        - "# Execute Amplify CLI with the helper script"
        - amplifyPush --environment $AWS_BRANCH
        - "# Store Amplify CLI Cloud-Formation stack info in environment cache"
        - >-
          envCache --set stackInfo "$(amplify env get --json --name
          $AWS_BRANCH)"
frontend:
  phases:
    build:
      commands:
        - yarn
        - yarn run build
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: build
    files:
      - "**/*"
```

I have several lambda functions that are used as resolvers for my graphql API, along with a react frontend.

**Comment by jesse-bonzo** [comment]
Adding this to my amplify.yml seems to fix the issue:
`npm config set bin-links false`
