### ISSUE TITLE
`amplify import auth` yeilds Gateway Time-out

### ISSUE THREAD

**Issue by JaspreetDev** [aws-amplify/amplify-cli#5969]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
I'm trying to import existing user pool with `amplify import auth` but it yields the following error (note, amplify add auth works fine)
```
Initializing new Amplify CLI version...
Done initializing new version.
Scanning for plugins...
Plugin scan successful
Using service: Cognito, provided by: awscloudformation



Gateway Time-out
UnknownError: Gateway Time-out
    at Request.extractError (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.callListeners (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)

```

**Amplify CLI Version**
4.35.0

**To Reproduce**
The parent is a flutter project. I initialized amplify inside the **android** directory as an android project with `amplify init`. Then I tried `amplify import auth` which would yield this error.

**Expected behavior**
Import/config existing user pool/

**Desktop (please complete the following information):**
 - OS: Linux Mint 20
 - Node Version. v10.19.0

**Comment by GeorgeBellTMH** [comment]
Cognito is down is us-east-1...

**Comment by ammarkarachi** [comment]
@JaspreetDev https://status.aws.amazon.com/## AWS is experiencing some delays, you can keep a track of what is going on in the link. Don't hesitate to create a new issue or reopen after the status resolves
