### ISSUE TITLE
CLI doesn't display options when prompted

### ISSUE THREAD

**Issue by rfaulhaber** [aws-amplify/amplify-cli#6]
Do you want to request a feature or report a bug?
Bug

What is the current behavior?
When I enter `amplify configure` the prompt implies that I should see options to select from, but they're not displayed.
![screenshot from 2018-08-23 20-25-52](https://user-images.githubusercontent.com/9273534/44558575-0979e200-a713-11e8-8f0b-443731526b46.png)

When I enter `amplify init` I'm given at least one option, but when I select something I'm no longer given options. When I hit enter a second time, I'm given an error.
![screenshot from 2018-08-23 20-26-18](https://user-images.githubusercontent.com/9273534/44558606-2e6e5500-a713-11e8-8885-a67b536b4c91.png)
![screenshot from 2018-08-23 20-26-36](https://user-images.githubusercontent.com/9273534/44558611-31694580-a713-11e8-857a-1d7b6c427cdb.png)
![screenshot from 2018-08-23 20-30-21](https://user-images.githubusercontent.com/9273534/44558655-5fe72080-a713-11e8-8b88-c03f5e11c410.png)

The full error is here:
```
readline.js:1032
            throw err;
            ^

TypeError: Cannot read property 'value' of undefined
    at Prompt.getCurrentValue (/home/ryan/.config/yarn/global/node_modules/inquirer/lib/prompts/list.js:126:51)
    at tryCatcher (/home/ryan/.config/yarn/global/node_modules/rx-lite/rx.lite.js:67:31)
    at InnerObserver.next (/home/ryan/.config/yarn/global/node_modules/rx-lite/rx.lite.js:4495:43)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/ryan/.config/yarn/global/node_modules/rx-lite/rx.lite.js:1602:31)
    at InnerObserver.tryCatcher (/home/ryan/.config/yarn/global/node_modules/rx-lite/rx.lite.js:67:31)
    at AutoDetachObserverPrototype.next (/home/ryan/.config/yarn/global/node_modules/rx-lite/rx.lite.js:6495:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/ryan/.config/yarn/global/node_modules/rx-lite/rx.lite.js:1602:31)
    at TakeObserver.next (/home/ryan/.config/yarn/global/node_modules/rx-lite/rx.lite.js:4681:17)
    at TakeObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/ryan/.config/yarn/global/node_modules/rx-lite/rx.lite.js:1602:31)
    at TakeObserver.tryCatcher (/home/ryan/.config/yarn/global/node_modules/rx-lite/rx.lite.js:67:31)
```

What is the expected behavior?
That it should display options.

Which versions of Amplify CLI, and which  OS are affected by this issue? Did this work in previous versions?

Amplify CLI: 0.1.13
OS: Linux Mint 19
Terminal: zsh (tried it on bash, behaves the same way)
Installed with Yarn

**Comment by kaustavghosh06** [comment]
Hey Ryan. What’s the node version you’re running on?

**Comment by rfaulhaber** [comment]
10.9.0.

**Comment by kaustavghosh06** [comment]
@mattjennings  @rfaulhaber I tried to reproduce on my macOS 10.12 and Ubuntu 18.04 but couldn't reproduce this issue. Might need to use a virtual box to simulate the environments. I'm assigning an Investigating tag to this for now.

**Comment by kaustavghosh06** [comment]
@mattjennings  @rfaulhaber  I was able to reproduce the error when i used yarn instead on npm to install the CLI. Until we find out the root cause of this could you please use `npm install -g @aws-amplify/cli` to install the CLI?

**Comment by mattjennings** [comment]
Using npm instead of yarn solved it for me!

**Comment by rfaulhaber** [comment]
Sounds good to me, thank you!

**Comment by ceich** [comment]
Not sure why this was just closed. Is there a yarn issue that was created?
