### ISSUE TITLE
`amplify init` fails when using AWS profile for session credentials

### ISSUE THREAD

**Issue by jamesonwilliams** [aws-amplify/amplify-cli#6016]
I am trying to run `amplify init .` in a project.

I have a `~/.aws/config` file that looks like this:
```
[profile myusername-Admin]
output = json
region = us-west-2 
credential_process = proprietary_command_i_wont_mention_publicly --with-args myusername
```

My `~/.aws/credentials` is empty.

When I run `amplify init .`, it doesn't work:

```console
$ amplify init .
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the environment dev
? Choose your default editor: Vim (via Terminal, Mac OS only)
Using default provider  awscloudformation

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

? Do you want to use an AWS profile? Yes
? Please choose the profile you want to use myusername-Admin
init failed
MissingRequiredParameter: Missing required key 'name' in params
    at ParamValidator.fail (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/param_validator.js:50:37)
    at ParamValidator.validateStructure (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/param_validator.js:61:14)
    at ParamValidator.validateMember (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/param_validator.js:88:21)
    at ParamValidator.validate (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/event_listeners.js:132:42)
    at Request.callListeners (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at callNextListener (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/event_listeners.js:86:9
    at finish (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js:386:7)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js:428:9 {
  code: 'MissingRequiredParameter',
  time: 2020-11-30T22:23:59.344Z
}
```

I am using version `4.36.2`:

```console
$ amplify -v
4.36.2
```

**Comment by jamesonwilliams** [comment]
I tried the other approach, wherein session credentials are stored on disk in `~/.aws/credentials`:

`~/.aws/config` has:
[default]
region=us-west-2
output=json
```

`~/.aws/credentials` has:
```
[default]
aws_access_key_id=REDACTED
aws_secret_access_key=REDACTED
aws_session_token=REDACTED
```

And that meets the same fate:
```console
 amplify init .
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the environment dev
? Choose your default editor: Vim (via Terminal, Mac OS only)
Using default provider  awscloudformation

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

? Do you want to use an AWS profile? Yes
? Please choose the profile you want to use default
init failed
MissingRequiredParameter: Missing required key 'name' in params
    at ParamValidator.fail (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/param_validator.js:50:37)
    at ParamValidator.validateStructure (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/param_validator.js:61:14)
    at ParamValidator.validateMember (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/param_validator.js:88:21)
    at ParamValidator.validate (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/event_listeners.js:132:42)
    at Request.callListeners (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at callNextListener (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/event_listeners.js:86:9
    at finish (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js:386:7)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js:404:9 {
  code: 'MissingRequiredParameter',
  time: 2020-12-01T15:50:13.641Z
}
```

I'm totally blocked right now. I'm not willing to store long-lived credentials on disk.

**Comment by jamesonwilliams** [comment]
I was able to get running again with three additional steps:
1. Delete `amplify`, `~/.aws-amplify`, and `~/.graph*`
2. `touch ~/.aws/credentials`
3. `export AWS_SDK_LOAD_CONFIG=1`

**Comment by RobKraft** [comment]
Thanks Jameson, I was having the same problem and deleting those folders helped me resolve the problem.

**Comment by aspearman** [comment]
Just had this issue on amplify cli 4.39.0

**Comment by rmuellerjr** [comment]
Same here. I've deleted the above and doesn't help.

**Comment by jonicong** [comment]
Removing "amplify" folder on project folder as @rmuellerjr mention, do help me solve this issue. Thanks.

**Comment by ericnickus** [comment]
yup removing the amplify folder and re running amplify init did work for me as well

**Comment by kaustavghosh06** [comment]
This issue seems to be resolved and is occurring if there's already an existing amplify folder in the directory. Removing it and running the headless command seems to be solving the issue.

**Comment by jkgwm** [comment]
How can you simply delete your top-level amplify folder? It has all the backend in it. I'm confused.
