### ISSUE TITLE
Cannot push function resources. No meaningful error thrown.

### ISSUE THREAD

**Issue by boxcee** [aws-amplify/amplify-cli#6063]
**Describe the bug**
`amplify function push myFunction` fails with this error message:
```
✖ An error occurred when pushing the resources to the cloud

,,
Error: ,,
    at runPackageManager (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-nodejs-function-runtime-provider/src/utils/legacyBuild.ts:54:11)
    at installDependencies (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-nodejs-function-runtime-provider/src/utils/legacyBuild.ts:38:3)
    at Object.buildResource (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-nodejs-function-runtime-provider/src/utils/legacyBuild.ts:12:5)
    at Object.build (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-nodejs-function-runtime-provider/src/index.ts:44:22)
    at buildResource (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/build-resources.js:49:36)
    at async Promise.all (index 0)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/push-resources.js:50:5)
    at async Promise.all (index 0)
    at providersPush (/usr/local/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/push-resources.ts:92:3)
    at AmplifyToolkit.pushResources [as _pushResources] (/usr/local/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/push-resources.ts:68:7)
An error occurred when pushing the function resource
```

Then I tried running the same command with `DEBUG=* amplify function push myFunction`.

From the logs there is a line:
`2020-12-04T16:35:56.130Z - debug: Error thrown: crit: Required property Code missing for type AWS::Lambda::Function<LambdaFunction> (Resources > LambdaFunction > Properties)`

**Amplify CLI Version**
`4.37.1`

**Expected behavior**
At least throw an error message that can be acted upon. Missing permissions? Function needs to be built first? I don't know what to do now.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Node Version: v12.19.0

**Comment by ammarkarachi** [comment]
@boxcee If you don't mind sharing your Lambda CFN we can look into this further

**Comment by boxcee** [comment]
@ammarkarachi What is a CFN? Sorry, I am new to the game.

**Comment by kaustavghosh06** [comment]
@boxcee Can you just run ‘amplify push’ without the sub commands and see if that pushes your function?

**Comment by boxcee** [comment]
@kaustavghosh06 , no success.

```
√ graph-prototyping % amplify push
✔ Successfully pulled backend environment dev from the cloud.

Current Environment: dev

| Category | Resource name       | Operation | Provider plugin   |
| -------- | ------------------- | --------- | ----------------- |
| Function | slackExpress        | Update    | awscloudformation |
| Auth     | timelinese08e390b   | No Change | awscloudformation |
| Api      | timelines           | No Change | awscloudformation |
| Api      | tokenExchange       | No Change | awscloudformation |
| Api      | slackExpress        | No Change | awscloudformation |
| Function | tokenExchange       | No Change | awscloudformation |
| Function | expressDependencies | No Change | awscloudformation |
? Are you sure you want to continue? Yes
✖ An error occurred when pushing the resources to the cloud

,,
An error occurred during the push operation: ,,
```

**Comment by kaustavghosh06** [comment]
@boxcee Sorry for the late response. Could you please run `amplify function build` with the latest version of the CLI? That should provide a more descriptive error with the function build.

**Comment by edwardfoyle** [comment]
Closing due to lack of response. Please follow up if you are still experiencing issues

**Comment by boxcee** [comment]
```
?1 graph-prototyping % amplify function build
? Are you sure you want to continue building the resources? Yes
✖ An error occurred when building the resources.
Error: Packaging lambda failed function failed with the error 
Command failed with exit code 243: npm install
    at runPackageManager (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-nodejs-function-runtime-provider/src/utils/legacyBuild.ts:56:13)
    at installDependencies (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-nodejs-function-runtime-provider/src/utils/legacyBuild.ts:39:3)
    at Object.buildResource (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-nodejs-function-runtime-provider/src/utils/legacyBuild.ts:13:5)
    at Object.build (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-nodejs-function-runtime-provider/src/index.ts:44:22)
    at buildResource (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/build-resources.js:49:36)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/index.ts:212:3)
    at executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:181:3)
There was an error building the function resources
```
Definitely more logs now, still an error though. May I mention you to reopen @edwardfoyle ?

**Comment by kaustavghosh06** [comment]
@boxcee Okay, this means that the `npm install` command is failing when trying to build out your functions. It might be due to a non-existent package in the package.json for one of your NodeJS functions.
To debug further, you can go into your NodeJS function directory and run `npm install` and see which package is the faulty one causing this issue.
