### ISSUE TITLE
Cannot destructure property 'appId' of '_.get(...)' as it is undefined.

### ISSUE THREAD

**Issue by MontoyaAndres** [aws-amplify/amplify-cli#6087]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
I'm trying to use an environment on the cli but I get this error:

```
andres@DESKTOP-SKIUJ5M:~/Work/Logitool-Amplify-Project$ amplify env checkout master

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

? Do you want to use an AWS profile? Yes
? Please choose the profile you want to use logi
Cannot destructure property 'appId' of '_.get(...)' as it is undefined.
TypeError: Cannot destructure property 'appId' of '_.get(...)' as it is undefined.
    at persistLocalEnvConfig (/home/andres/.nvm/versions/node/v14.15.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/configuration-manager.js:408:11)
    at Object.onInitSuccessful (/home/andres/.nvm/versions/node/v14.15.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/configuration-manager.js:180:5)
    at Object.onInitSuccessful (/home/andres/.nvm/versions/node/v14.15.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/initializer.js:144:24)
    at Object.onInitSuccessful (/home/andres/.nvm/versions/node/v14.15.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/index.ts:43:22)
    at /home/andres/.nvm/versions/node/v14.15.1/lib/node_modules/@aws-amplify/cli/src/commands/env/checkout.ts:44:53
    at /home/andres/.nvm/versions/node/v14.15.1/lib/node_modules/@aws-amplify/cli/node_modules/promise-sequential/index.js:16:18
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Also, I tried:

```
andres@DESKTOP-SKIUJ5M:~/Work/Logitool-Amplify-Project$ amplify env pull --restore
⠹ Fetching updates to backend environment: master from the cloud.Could not initialize 'master': Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1
```

But I have the credentials on the file .aws/credentials

This happens when I try to change of enviroment 

**Amplify CLI Version**
4.37.1

**Expected behavior**
Change the environment without problems

**Desktop (please complete the following information):**
 - OS: WSL 2
 - Node Version. v14.15.1

**Comment by MontoyaAndres** [comment]
I could fix it by doing an amplify init 🤔

```
andres@andres:~/Work/Logitool-Amplify-Project$ amplify init
Note: It is recommended to run this command from the root of your app directory
? Do you want to use an existing environment? Yes
? Choose the environment you would like to use: master
Using default provider  awscloudformation

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

? Do you want to use an AWS profile? Yes
? Please choose the profile you want to use logi
✔ Initialized provider successfully.
Initialized your environment successfully.

Your project has been successfully initialized and connected to the cloud!
```

Why do I need to do this? Maybe this is because this is the first time I'm accessing to this branch? Maybe the message of error should be more descriptive?
