### ISSUE TITLE
Updating API Auth: Cannot read property 'StackName' of undefined

### ISSUE THREAD

**Issue by 24601** [aws-amplify/amplify-cli#6116]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
While trying to add a secondary API Auth method (API Key), the amplify CLI fails with a cryptic error message without much helpful info (I find this to be pretty common).

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system

4.38.0
**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable
```
amplify update api 
```

Choose options as specified below in "Screeenshots"

**Expected behavior**

Adds an API Key authorization method as a secondary

**Screenshots**
```
❯ amplify update api
? Please select from one of the below mentioned services: GraphQL
? Select from the options below Update auth settings
? Choose the default authorization type for the API Amazon Cognito User Pool
Use a Cognito user pool configured as a part of this project.
? Configure additional auth types? Yes
? Choose the additional authorization types you want to configure for the API API key
API key configuration
? Enter a description for the API key: test
? After how many days from now the API key should expire (1-365): 365
Cannot read property 'StackName' of undefined
TypeError: Cannot read property 'StackName' of undefined
    at getBucketName (/Users/basitmustafa/.nvm/versions/node/v14.15.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/transform-graphql-schema.ts:563:61)
    at transformGraphQLSchema (/Users/basitmustafa/.nvm/versions/node/v14.15.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/transform-graphql-schema.ts:431:38)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at CfnApiArtifactHandler.updateArtifacts (/Users/basitmustafa/.nvm/versions/node/v14.15.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/src/provider-utils/awscloudformation/cfn-api-artifact-handler.ts:116:5)
    at Object.executeAmplifyCommand (/Users/basitmustafa/.nvm/versions/node/v14.15.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/src/index.ts:188:3)
    at executePluginModuleCommand (/Users/basitmustafa/.nvm/versions/node/v14.15.1/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:163:3)
    at Object.executeCommand (/Users/basitmustafa/.nvm/versions/node/v14.15.1/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:28:5)
    at Object.run (/Users/basitmustafa/.nvm/versions/node/v14.15.1/lib/node_modules/@aws-amplify/cli/src/index.ts:102:5) 
```
**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu]
 - Node Version. You can use `node -v` to check the node version on your system
Mac OS X Big Sur
Node 14.15.1

**Additional context**

**Comment by attilah** [comment]
@24601 could you share with me how the project was created exactly? since based on the error it seems that it is an uninitialized project and there is no deployment bucket present in your `amplify-meta.json` file. Could you share the content of that file as well?

**Comment by 24601** [comment]
Used the amplify CLI as per the instructions in creating a React app. Happy to share the contents of the file but it seems to have data in there that shouldn't be publicly available (e.g. 3rd party app secrets?), is there a way to share this with you you prefer more securely?

**Comment by SwaySway** [comment]
You can send over the materials to our email amplify-cli@amazon.com

**Comment by kaustavghosh06** [comment]
@24601 Are you still blocked on this issue?
