### ISSUE TITLE
'amplify init' ignores AWS profiles with role_arn

### ISSUE THREAD

**Issue by ovcharenko** [aws-amplify/amplify-cli#613]
**Describe the bug**
`amplify init` ignores AWS profiles with role_arn.

**To Reproduce**
1. Run `amplify init`
2. During *awscloudformation* configuration there will be only profiles with credentials

**Expected behavior**
All supported by AWS CLI profiles should be listed.

**Desktop (please complete the following information):**
```
$ amplify -v
0.2.1-multienv.14
```

**Comment by ovcharenko** [comment]
@UnleashedMind Does it support running on instance or container with IAM role? I tried with different credentials providers, but always getting during `amplify env checkout`:

```
 uncaughtException: Missing credentials in config
   ...
   execPath=/usr/local/bin/node
   version=v10.14.1
   argv=[
      /usr/local/bin/node
      /usr/local/bin/amplify
      env
      checkout
      master
   ]
   ...
   stack=[
     CredentialsError: Missing credentials in config
       at Object.openSync (fs.js:436:3)
       at Object.readFileSync (fs.js:341:35)
       at Object.readFileSync (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/node_modules/aws-sdk/lib/util.js:95:26)
       at IniLoader.parseFile (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/node_modules/aws-sdk/lib/shared-ini/ini-loader.js:7:40)
       at IniLoader.loadFrom (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/node_modules/aws-sdk/lib/shared-ini/ini-loader.js:56:46)
       at SharedIniFileCredentials.load (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/node_modules/aws-sdk/lib/credentials/shared_ini_file_credentials.js:110:41)
       at SharedIniFileCredentials.coalesceRefresh (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/node_modules/aws-sdk/lib/credentials.js:205:12)
       at SharedIniFileCredentials.refresh (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/node_modules/aws-sdk/lib/credentials/shared_ini_file_credentials.js:190:10)
       at SharedIniFileCredentials.get (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/node_modules/aws-sdk/lib/credentials.js:122:12)
       at getAsyncCredentials (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/node_modules/aws-sdk/lib/config.js:360:24)
  ]
```
My `.aws/config` is like
```
[default]
credential_source = Environment
region = us-east-1
output = json
```
I tried two other providers from [AWS CLI](https://docs.aws.amazon.com/cli/latest/topic/config-vars.html) with same result.

**Comment by ovcharenko** [comment]
I see all required code exists in `amplify-provider-awscloudformation/node_modules/aws-sdk/lib/credentials/credential_provider_chain.js`, but looks like it never used.

**Comment by UnleashedMind** [comment]
If you execute `amplify configure project` and choose to remove project level configuration, then the cli will try to resolve the configuration by itself, in that case, if the cli is sunning in an EC2 instance, and the EC2 instance has been assigned a role, the cli will assume that role to access aws resources.

**Comment by ovcharenko** [comment]
> If you execute `amplify configure project` and choose to remove project level configuration, then the cli will try to resolve the configuration by itself, in that case, if the cli is running in an EC2 instance, and the EC2 instance has been assigned a role, the cli will assume that role to access aws resources.

And how to do so non-interactively?

**Comment by ovcharenko** [comment]
And it doesn't work:
```
? Start Command: ng serve
Using default provider  awscloudformation
AWS access credentials can not be found.
? Setup new user No

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html

? accessKeyId:  1
? secretAccessKey:  2
? region:  us-east-1
✖ Root stack creation failed
init failed
{ Error: ENOENT: no such file or directory, open '/root/.aws/credentials'
```

**Comment by UnleashedMind** [comment]
It does not look like you are using the latest version of the cli, please update to the latest and try again. 
Even if you remove the project specific configuration, you still need to provide the configuration through other means, such as the default profile stored in the shared configuration files inside ~/.aws/ or environment variables. 
For more information, check on these docs: 
[credentials](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-credentials-node.html)
[region](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-region.html)

**Comment by ovcharenko** [comment]
@UnleashedMind not sure what CLI version do you mean. `amplify-cli` version I'm using same as in the bug description. Anyway, I figured out what for some reason it requires both `config` and `credentials` files present. Even if you can put everything inside one file and AWS CLI will work just fine, `amplify-cli` will complain with not so obvious error `Missing credentials in config`.

**Comment by UnleashedMind** [comment]
yes, the amplify-cli stores and retrieves the credentials of a named profile in the separate ~/.aws/credentials file.

**Comment by kaustavghosh06** [comment]
@ovcharenko Are you unblocked?

**Comment by kaustavghosh06** [comment]
@ovcharenko We added this feature and would be merging it to prod by end of day today.
Checkout #645

**Comment by blazestudios23** [comment]
I just installed Amplify CLI yesterday and am unable to see my existing profiles, which all have Roles assigned.
