### ISSUE TITLE
Amplifypush gives Error: Missing required dependencies to package

### ISSUE THREAD

**Issue by simpian** [aws-amplify/amplify-cli#6166]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
Build works fine when i initialize the project, like no backend lambda functions, but as soon as add just one example lambda function, build starts failing. I'm able to do an amplify push on my local and backend can be deployed from local, but when i do a git push, and trigger the build, i get build failure, here is the log

my lambda functions are written in Java 11

```                                 # Starting phase: build
                                 # Executing command: amplifyPush --simple
2020-12-12T19:06:51.858Z [INFO]: 
2020-12-12T19:06:51.860Z [INFO]: [0mFor more information on AWS Profiles, see:[0m
                                 [0mhttps://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html[0m
2020-12-12T19:06:52.171Z [INFO]: [0mAmplify AppID found: dmby4dyvtonmc. Amplify App name is: xxx[0m
2020-12-12T19:06:52.219Z [INFO]: [0mBackend environment dev found in Amplify Console app: xxx[0m
2020-12-12T19:06:52.966Z [WARNING]: - Fetching updates to backend environment: dev from the cloud.
2020-12-12T19:06:53.240Z [WARNING]: ✔ Successfully pulled backend environment dev from the cloud.
2020-12-12T19:06:53.273Z [INFO]: 
2020-12-12T19:06:55.243Z [INFO]: [33mNote: It is recommended to run this command from the root of your app directory[39m
2020-12-12T19:07:00.103Z [WARNING]: - Initializing your environment: dev
2020-12-12T19:07:00.386Z [WARNING]: ✔ Initialized provider successfully.
2020-12-12T19:07:00.561Z [INFO]: [31mUnable to find Java version >=11 on the path. Download link: https://amzn.to/2UUljp9[39m
                                 [31mUnable to find Java compiler version >=11 on the path. Download link: https://amzn.to/2UUljp9[39m
                                 [31mUnable to find Gradle version >=5 on the path. Download link: https://bit.ly/3aGYDj6[39m
2020-12-12T19:07:00.562Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
2020-12-12T19:07:00.562Z [WARNING]: ✖ There was an error initializing your environment.
2020-12-12T19:07:00.564Z [INFO]: [31minit failed[39m
2020-12-12T19:07:00.565Z [INFO]: [0mError: Missing required dependencies to package User[0m
                                 [0m    at Object.buildResource (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/build-resources.js:30:11)[0m
                                 [0m    at processTicksAndRejections (internal/process/task_queues.js:97:5)[0m
                                 [0m    at packageResource (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/push-resources.ts:483:16)[0m
                                 [0m    at async Promise.all (index 0)[0m
                                 [0m    at Object.run (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/push-resources.ts:102:5)[0m
2020-12-12T19:07:00.581Z [ERROR]: !!! Build failed
2020-12-12T19:07:00.582Z [ERROR]: !!! Non-Zero Exit Code detected
2020-12-12T19:07:00.582Z [INFO]: # Starting environment caching...
2020-12-12T19:07:00.582Z [INFO]: # Environment caching completed
```
**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system
4.38.0

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable

**Expected behavior**
Amplify build should build with no issues.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu]
 - Node Version. You can use `node -v` to check the node version on your system

**Additional context**

**Comment by simpian** [comment]
opened in amplify console https://github.com/aws-amplify/amplify-console/issues/1368
