### ISSUE TITLE
Error with Sample Rest API Setup

### ISSUE THREAD

**Issue by fjnoyp** [aws-amplify/amplify-cli#6173]
1. Following the online instructions for setting up Rest API results in a non functioning project.  https://docs.amplify.aws/lib/restapi/getting-started/q/platform/android#initialize-amplify-api
2. 4.37.1
3. Same code as provided online except I use use path items instead of todo:
```
val options = RestOptions.builder()
    .addPath("/items")
    .addBody("{\"name\":\"Mow the lawn\"}".toByteArray())
    .build()

Amplify.API.post(options,
    { Log.i("MyAmplifyApp", "POST succeeded: $it") },
    { Log.e("MyAmplifyApp", "POST failed.", it) }
)
```
4. When I run the post request I get this error: 
```

2020-12-07 09:49:58.260 18936-19071/com.example.restapi E/MyAmplifyApp: POST failed.
    AmplifyException {message=Received an IO exception while making the request., cause=java.io.IOException: Failed to read credentials to sign the request., recoverySuggestion=Retry the request.}
        at com.amplifyframework.api.aws.operation.AWSRestOperation$OkHttpCallback.onFailure(AWSRestOperation.java:131)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:525)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.io.IOException: Failed to read credentials to sign the request.
        at com.amplifyframework.api.aws.sigv4.AppSyncSigV4SignerInterceptor.intercept(AppSyncSigV4SignerInterceptor.java:202)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
     Caused by: com.amazonaws.AmazonClientException: Failed to get credentials from Cognito Identity
        at com.amazonaws.mobile.client.AWSMobileClient.getCredentials(AWSMobileClient.java:374)
        at com.amplifyframework.api.aws.sigv4.AppSyncSigV4SignerInterceptor.intercept(AppSyncSigV4SignerInterceptor.java:194)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201) 
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
     Caused by: com.amazonaws.services.cognitoidentity.model.NotAuthorizedException: Unauthenticated access is not supported for this identity pool. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: NotAuthorizedException; Request ID: 7688d7be-9c6c-4e0e-8de5-64271e4d0640)

```
5. Any relevant guides or documentation you're referencing: All code and CLI setup based on amplify docs online. 

It appears the error is because I haven't used Amplify Cognito and pushed auth via the Amplify CLI.  However, there isn't any mention of adding this in the docs and during the cli instructions it says to allow unauthenticated access. 

![image](https://user-images.githubusercontent.com/11478656/101386982-b4762180-3872-11eb-9836-8d0f48071c97.png)

**Comment by kaustavghosh06** [comment]
@fjnoyp I'm not sure about the issue. Do you have a REST API or a GraphQL API? 
Can you show us the result in your terminal for `amplify status`.

**Comment by kaustavghosh06** [comment]
Closing due to lack of response.
