### ISSUE TITLE
DataStore Flutter - Unable to run add api command 

### ISSUE THREAD

**Issue by pkhivesara** [aws-amplify/amplify-cli#6202]
**Describe the bug**
Unable to run add api command on existing project

**To Reproduce**

    1. Go to terminal
    2. Type in amplify add api
    3. See error: Cannot read property 'includes' of undefined

**Expected behavior**
DataStore should be added successfully

**Platform**
Amplify Flutter current supports iOS and Android. This issue is reproducible in (check all that apply):
[x] Android
[x] iOS

**Additional context**

```Plugin scan successful
Cannot read property 'includes' of undefined
TypeError: Cannot read property 'includes' of undefined
    at Object.keys.forEach.service (/usr/local/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/service-select-prompt.js:31:30)
    at Array.forEach (<anonymous>)
    at filterServicesByEnabledProviders (/usr/local/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/service-select-prompt.js:30:36)
    at AmplifyToolkit.serviceSelectionPrompt [as _serviceSelectionPrompt] (/usr/local/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/service-select-prompt.js:79:25)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/lib/commands/api/add.js:10:14)
    at Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/lib/index.js:151:25)
    at /usr/local/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:169:51
    at executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:153:11)```

**Comment by yuth** [comment]
Could you include the flowing information 
1. What is the version of Amplify CLI you have installed
3. How is you project configured. Could you share `amplify/.config/local-aws-info.json` and `amplify/.config/project-config.json`

**Comment by pkhivesara** [comment]
@yuth Was able to get it working. Thank you! I shall close the issue.
