### ISSUE TITLE
JSONValidationError: File project: data should NOT have additional properties: 'frontend-ios'

### ISSUE THREAD

**Issue by henobi** [aws-amplify/amplify-cli#6210]
**Describe the bug**
I can not pull my app from amplify console.
```bash
$ amplify pull --appId XXXXX --envName staging                          
Amplify AppID found: XXXXXX. Amplify App name is: TodoApp
Backend environment staging found in Amplify Console app: TodoApp
Failed to pull the backend.
File project: data should NOT have additional properties: 'frontend-ios'
JSONValidationError: File project: data should NOT have additional properties: 'frontend-ios'
    at validator (/snapshot/node_modules/amplify-cli-core/lib/feature-flags/featureFlags.js:135:27)
    at featureFlagsValidator (/snapshot/node_modules/amplify-cli-core/lib/feature-flags/featureFlags.js:139:17)
    at FeatureFlags.validateFlags (/snapshot/node_modules/amplify-cli-core/lib/feature-flags/featureFlags.js:145:17)
    at FeatureFlags.loadValues (/snapshot/node_modules/amplify-cli-core/lib/feature-flags/featureFlags.js:203:18)
    at Function.reloadValues (/snapshot/node_modules/amplify-cli-core/lib/feature-flags/featureFlags.js:346:5)
    at Object.attachBackend (/snapshot/node_modules/@aws-amplify/cli/lib/attach-backend.js:40:13)
    at Object.exports.run (/snapshot/node_modules/@aws-amplify/cli/lib/commands/pull.js:62:9)
    at Object.executeAmplifyCommand (/snapshot/node_modules/@aws-amplify/cli/lib/index.js:180:9)
    at executePluginModuleCommand (/snapshot/node_modules/@aws-amplify/cli/lib/execution-manager.js:153:5)
    at Object.executeCommand (/snapshot/node_modules/@aws-amplify/cli/lib/execution-manager.js:35:9)
```

**Amplify CLI Version**
4.37.1

**To Reproduce**
Created a new backend app in Amplify Console and run ´amplify pull --appId XXXX --envName staging´ in the CLI

**Expected behavior**
A pull without a error stack trace

**Desktop (please complete the following information):**
- Mac OS X Big Sour
- Node v14.9.0

**Comment by yuth** [comment]
It looks like you have the project initalized with the CLI version 4.40.0, which has introduced an new FeatureFlag. You  will have to update your CLI to 4.40.0 so the CLI knows how to deal with the feature flag
