### ISSUE TITLE
Build failed after setting up the CI/CD 

### ISSUE THREAD

**Issue by mjza** [aws-amplify/amplify-cli#6234]
I followed [this tutorial](https://aws.amazon.com/getting-started/hands-on/build-react-app-amplify-graphql/module-three/) and then after editing the Build settings I see the following error:

```bash
                                 # Starting phase: build
                                 # Executing command: amplifyPush --simple
2020-12-22T14:07:51.752Z [INFO]: File project: data should NOT have additional properties: 'graphqltransformer'
2020-12-22T14:07:51.753Z [INFO]: JSONValidationError: File project: data should NOT have additional properties: 'graphqltransformer'
                                 at validator (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/feature-flags/featureFlags.js:136:27)
                                 at featureFlagsValidator (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/feature-flags/featureFlags.js:140:17)
                                 at FeatureFlags.validateFlags (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/feature-flags/featureFlags.js:146:17)
                                 at FeatureFlags.loadValues (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/feature-flags/featureFlags.js:204:18)
                                 at async Function.FeatureFlags.initialize (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/feature-flags/featureFlags.js:267:5)
                                 at async Object.run (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/lib/index.js:73:9)
2020-12-22T14:07:51.758Z [ERROR]: !!! Build failed
2020-12-22T14:07:51.758Z [ERROR]: !!! Non-Zero Exit Code detected
2020-12-22T14:07:51.758Z [INFO]: # Starting environment caching...
2020-12-22T14:07:51.758Z [INFO]: # Environment caching completed
Terminating logging...
```

Any suggestion?

**Comment by akshbhu** [comment]
Hi @mjza 

This error usually comes when you introduce a FF flag in ```cli.json``` on older cli versions. 
Please update to latest version ```v4.40.1``` and let me know if it works out for you?

**Comment by mjza** [comment]
@akshbhu 
Here are my versions:

> % aws --version
> aws-cli/2.1.13 Python/3.7.4 Darwin/20.2.0 exe/x86_64 prompt/off
> % amplify --version
> 4.40.1

**Comment by mjza** [comment]
Also here is my `cli.json`:

```json
{
  "features": {
    "graphqltransformer": {
      "addmissingownerfields": true,
      "validatetypenamereservedwords": true,
      "useexperimentalpipelinedtransformer": false,
      "enableiterativegsiupdates": false
    },
    "frontend-ios": {
      "enablexcodeintegration": true
    },
    "auth": {
      "enablecaseinsensitivity": true
    },
    "codegen": {
      "useappsyncmodelgenplugin": true
    }
  }
}
```

**Comment by mjza** [comment]
I compared this project with another project that I made last week with version 4.40.0 and there is the following differences:

1. In `cli.json` the following part is new:
```json
"frontend-ios": {
      "enablexcodeintegration": true
    },
    "auth": {
      "enablecaseinsensitivity": true
    },
    "codegen": {
      "useappsyncmodelgenplugin": true
    }
```

2. In `parameters.json` in line 52 this is new:
```json
"usernameCaseSensitive": false,
```
3. In `xyz-cloudformation-template.yml` also we have in two places:
```
usernameCaseSensitive: 
Type: String
```
and

```
UsernameConfiguration:
     CaseSensitive: false
```

I removed them, and tried `amplify push --y` but it fails to update cloud!

> ✖ An error occurred when pushing the resources to the cloud
>
> Resource is not in the state stackUpdateComplete
> An error occurred during the push operation: Resource is not in the state stackUpdateComplete

**Comment by mjza** [comment]
Anyway I solved the problem by creating `Amplify Backend` instead of `Amplify Webapp`. It solved my problem and I passed that error.

**Comment by akshbhu** [comment]
good to know it worked , Closing this issue as it seems to be solved.
