### ISSUE TITLE
Cannot Build Backend on`amplify auth import`

### ISSUE THREAD

**Issue by chrisyeung1121** [aws-amplify/amplify-cli#6252]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
I tried switching the auth to an imported one where I use CDK to customise it. However, after I did `amplify auth import` - the following error shows on Build > backend at Amplify console. 

```
[0mFor more information on AWS Profiles, see:[0m
                                 [0mhttps://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html[0m
2020-12-22T19:56:14.390Z [INFO]: [0mAmplify AppID found: d37y092esc33s1. Amplify App name is: awsamplifynuxt[0m
2020-12-22T19:56:14.472Z [INFO]: [0mBackend environment dev found in Amplify Console app: awsamplifynuxt[0m
2020-12-22T19:56:15.151Z [WARNING]: - Fetching updates to backend environment: dev from the cloud.
2020-12-22T19:56:15.337Z [WARNING]: ✔ Successfully pulled backend environment dev from the cloud.
2020-12-22T19:56:15.370Z [WARNING]: ✖ There was an error initializing your environment.
2020-12-22T19:56:15.371Z [INFO]: [31mFailed to pull the backend.[39m
2020-12-22T19:56:15.373Z [INFO]: [31mauth headless is missing the following inputParams userPoolId, webClientId, nativeClientId[39m
2020-12-22T19:56:15.382Z [INFO]: [0mError: auth headless is missing the following inputParams userPoolId, webClientId, nativeClientId[0m
                                 [0m    at ensureHeadlessParameters (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/provider-utils/awscloudformation/import/index.ts:1265:11)[0m
                                 [0m    at headlessImport (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/provider-utils/awscloudformation/import/index.ts:1122:40)[0m
                                 [0m    at exports.importedAuthEnvInit (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/provider-utils/awscloudformation/import/index.ts:898:18)[0m
                                 [0m    at processTicksAndRejections (internal/process/task_queues.js:97:5)[0m
                                 [0m    at updateConfigOnEnvInit (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/provider-utils/awscloudformation/index.js:51:72)[0m
                                 [0m    at /root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/index.js:300:22[0m
2020-12-22T19:56:15.399Z [ERROR]: !!! Build failed
2020-12-22T19:56:15.399Z [ERROR]: !!! Non-Zero Exit Code detected
```

**Amplify CLI Version**
4.40.0

**To Reproduce**
1. use `amplify auth import`
2. then git push to the branch to trigger a deployment
3. check the build tab for the console error

**Expected behavior**
headless auth should contain the following parameters `userPoolId, webClientId, nativeClientId`

**Screenshots**
<img width="1792" alt=" 2020-12-24 at 12 41 29 PM" src="https://user-images.githubusercontent.com/3488583/103061161-62a8f780-45e5-11eb-8a2c-0abd5c3126df.png">

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Node Version. v12.18.3

**Comment by nubpro** [comment]
A few had success doing the following:
https://github.com/aws-amplify/amplify-console/issues/206#issuecomment-660498668
https://github.com/aws-amplify/amplify-console/issues/206#issuecomment-552548466

**Comment by chrisyeung1121** [comment]
I can confirm that by adding Environment Variable it solves the issue. I hope this bug will be fixed soon with newer amplify cli.
