### ISSUE TITLE
Manually deleted amplify folder from project and can't use amplify CLI anymore

### ISSUE THREAD

**Issue by ammarasmro** [aws-amplify/amplify-cli#6263]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
I downloaded and set amplify up. The setup wasn't working for me (newbie) so I decided to clean my system and start over to see what went wrong. Tried running `amplify delete` and `amplify update auth`, they didn't help. So, I removed the `amplify` folder. Since then, I can't run any amplify commands in there without getting weird errors. I tried deleting the CLI globally and reinstalled. Still the same issues. I can't tell what is being cached that amplify just can't start over for this particular folder.

The CLI did work on other folders

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system
4.40.1

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable
Sample error of running `amplify status`
```
TypeError: Cannot read property 'forEach' of undefined
    at AmplifyToolkit.showHelpfulProviderLinks [as _showHelpfulProviderLinks] (/usr/local/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/show-helpful-provider-links.js:12:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.exports.run (/usr/local/lib/node_modules/@aws-amplify/cli/lib/commands/status.js:6:5)
    at async Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/lib/index.js:216:9)
    at async executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:166:5)
    at async Object.executeCommand (/usr/local/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:35:9)
    at async Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/lib/index.js:92:9)
```
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu] Mac
 - Node Version. You can use `node -v` to check the node version on your system
v12.18.3
Also tried on
v14.15.3

**Additional context**

**Comment by jhockett** [comment]
Hi @ammarasmro, you deleted the amplify project with `amplify delete`, so you can't perform an `auth update` or `status` because there is no amplify project. You need to run `amplify init` in order to create a new project.

**Comment by ammarasmro** [comment]
Right but that still doesn't solve the errors. It starts the questions from 
```
? Enter a name for the environment (dev)
```
Instead of asking for the project name
And even after following through. All Amplify commands fail with errors like the one posted above

**Comment by jhockett** [comment]
I see. It looks like the CLI is detecting it's in a project for some reason. Can you share your project structure?

To get unblocked, try `amplify init` in an empty directory and then copying the relevant files over from the broken project.
