### ISSUE TITLE
Better error message when cloud provider not yet configured

### ISSUE THREAD

**Issue by cwoolum** [aws-amplify/amplify-cli#6285]
**Describe the bug**
When trying to run the `amplify update api` command, I receive the following error. This is with a brand new install of the CLI and a brand new React App.

```
Cannot read property 'includes' of undefined
TypeError: Cannot read property 'includes' of undefined
    at C:\Users\chris\AppData\Roaming\npm\node_modules\@aws-amplify\cli\lib\extensions\amplify-helpers\service-select-prompt.js:31:30
    at Array.forEach (<anonymous>)
    at filterServicesByEnabledProviders (C:\Users\chris\AppData\Roaming\npm\node_modules\@aws-amplify\cli\lib\extensions\amplify-helpers\service-select-prompt.js:30:36)
    at AmplifyToolkit.serviceSelectionPrompt [as _serviceSelectionPrompt] (C:\Users\chris\AppData\Roaming\npm\node_modules\@aws-amplify\cli\lib\extensions\amplify-helpers\service-select-prompt.js:83:25) 
    at Object.run (C:\Users\chris\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-category-api\lib\commands\api\update.js:10:14)
    at Object.executeAmplifyCommand (C:\Users\chris\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-category-api\lib\index.js:166:25)
    at C:\Users\chris\AppData\Roaming\npm\node_modules\@aws-amplify\cli\lib\execution-manager.js:182:51
    at executePluginModuleCommand (C:\Users\chris\AppData\Roaming\npm\node_modules\@aws-amplify\cli\lib\execution-manager.js:166:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.executeCommand (C:\Users\chris\AppData\Roaming\npm\node_modules\@aws-amplify\cli\lib\execution-manager.js:35:9)
```

**Amplify CLI Version**
4.40.1

**To Reproduce**

1. Create an Amplify sandbox app
2. Install the Amplify CLI via NPM
3. Run the configure command `amplify configure --appId {yourappid} --envName staging`
4. Try to update the API with `amplify update api`

**Expected behavior**
I would expect the command would run successfully

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 - I have tried both WSL and Powershell and the error exists in both
 - Node Version. v12.18.2
 - NVM Version 0.35.3

**Additional context**

**Comment by edwardfoyle** [comment]
If you are pulling a newly deployed sandbox app, you should run `amplify pull --appId <appId> --envName staging` instead of configure.

That being said, marking this an an enhancement as we should throw a better error message in this case

**Comment by cwoolum** [comment]
Hey Edward, 

Yeah, I discovered yesterday that the first `pull` command I ran didn't work. After running it again, it fixed my problem. I created PR #6293 to handle the problem gracefully and added some tests as well.
