### ISSUE TITLE
auth headless is missing the following inputParams googleAppIdUserPool

### ISSUE THREAD

**Issue by PawanMude** [aws-amplify/amplify-cli#6302]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**

- amplify add auth
- Default configuration with Social Provider (Federation) 
- Username 
- No, I am done. 
- Accept default domain prefix 
- redirect sign-in and sign-out URI's added <<Valid Working URI>>  (another redirect sign-in and sign-out URI is not added) 
- Social Provider selected Google 
- Add Google Client Id and client Secret 

After following above steps code works on local ; when Amplify backend is integrated for CICD it throws error : "auth headless is missing the following inputParams googleAppIdUserPool" ; error screenshot is pasted below : 

![image](https://user-images.githubusercontent.com/29176181/103484857-e77ee700-4e17-11eb-9da4-35124b3aed59.png)

**Amplify CLI Version**
4.41.0

**To Reproduce**
Steps explained in Bug Description 

**Expected behavior**
Success Build with Amplify Backend integrated. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Amazon Linux 2 
 - Node Version.  10.23.0
![image](https://user-images.githubusercontent.com/29176181/103484910-5f4d1180-4e18-11eb-9624-294445959d63.png)

**Additional context**
Cloning Repository is successful ; Backend Build is failing ; details mentioned in screenshot below: 
![image](https://user-images.githubusercontent.com/29176181/103484954-aa672480-4e18-11eb-8435-d1dcf7009f83.png)

**Comment by akshbhu** [comment]
Hi @PawanMude 

It seems you are using Amplify Console for your builds. One thing you would need to include those input params as environment variables. An example of this is noted in this comment: https://github.com/aws-amplify/amplify-cli/issues/4790#issuecomment-656422252
Reference from Amplify Console Repo: https://github.com/aws-amplify/amplify-console/issues/206#issuecomment-660498668.

Let me know if this works for you?

**Comment by PawanMude** [comment]
@akshbhu  included  those input params (AMPLIFY_GOOGLE_CLIENT_ID, AMPLIFY_GOOGLE_CLIENT_SECRET) as environment variables in Amplify Console. Build is still failing with error code ELIFECYCLE , details mentioned below.

```
2021-01-05T14:05:18.337Z [INFO]: # Ensuring NPM package '@aws-amplify/cli' is version: 'latest'
2021-01-05T14:05:24.299Z [INFO]: # Patching NPM package '@aws-amplify/cli' from 4.29.4 to 4.41.0...
2021-01-05T14:06:06.602Z [INFO]: # Done patching NPM package '@aws-amplify/cli'
2021-01-05T14:06:12.334Z [INFO]: ## Starting Frontend Build
                                 # Starting phase: preBuild
                                 # Executing command: npm ci
2021-01-05T14:06:12.681Z [WARNING]: npm
2021-01-05T14:06:12.682Z [WARNING]: WARN prepare removing existing node_modules/ before installation
2021-01-05T14:06:26.217Z [INFO]: > core-js@2.6.12 postinstall /codebuild/output/src290553445/src/amplifyapp/node_modules/babel-runtime/node_modules/core-js
                                 > node -e "try{require('./postinstall')}catch(e){}"
2021-01-05T14:06:26.287Z [INFO]: > ejs@2.7.4 postinstall /codebuild/output/src290553445/src/amplifyapp/node_modules/ejs
                                 > node ./postinstall.js
2021-01-05T14:06:26.326Z [INFO]: Thank you for installing [35mEJS[0m: built with the [32mJake[0m JavaScript build tool ([32mhttps://jakejs.com/[0m)
2021-01-05T14:06:26.484Z [INFO]: > fsevents@1.2.13 install /codebuild/output/src290553445/src/amplifyapp/node_modules/webpack-dev-server/node_modules/fsevents
                                 > node install.js
2021-01-05T14:06:26.524Z [INFO]: 
2021-01-05T14:06:26.524Z [INFO]: Skipping 'fsevents' build as platform linux is not supported
2021-01-05T14:06:26.548Z [INFO]: > fsevents@1.2.13 install /codebuild/output/src290553445/src/amplifyapp/node_modules/watchpack-chokidar2/node_modules/fsevents
                                 > node install.js
2021-01-05T14:06:26.589Z [INFO]: 
2021-01-05T14:06:26.589Z [INFO]: Skipping 'fsevents' build as platform linux is not supported
2021-01-05T14:06:26.809Z [INFO]: > core-js@3.8.2 postinstall /codebuild/output/src290553445/src/amplifyapp/node_modules/core-js
                                 > node -e "try{require('./postinstall')}catch(e){}"
2021-01-05T14:06:27.160Z [INFO]: > core-js-pure@3.8.2 postinstall /codebuild/output/src290553445/src/amplifyapp/node_modules/core-js-pure
                                 > node -e "try{require('./postinstall')}catch(e){}"
2021-01-05T14:06:27.346Z [INFO]: added 2176 packages in 14.689s
2021-01-05T14:06:27.363Z [INFO]: # Completed phase: preBuild
                                 # Starting phase: build
                                 # Executing command: npm run build
2021-01-05T14:06:29.696Z [INFO]: > amplifyapp@0.1.0 build /codebuild/output/src290553445/src/amplifyapp
                                 > react-scripts build
2021-01-05T14:06:30.807Z [INFO]: Creating an optimized production build...
2021-01-05T14:06:31.794Z [INFO]: Failed to compile.
2021-01-05T14:06:31.794Z [INFO]: ./src/index.js
                                 Cannot find file './aws-exports' in './src'.
2021-01-05T14:06:31.805Z [WARNING]: npm
2021-01-05T14:06:31.806Z [WARNING]: ERR! code ELIFECYCLE
                                    npm ERR! errno 1
2021-01-05T14:06:31.808Z [WARNING]: npm
2021-01-05T14:06:31.808Z [WARNING]: ERR! amplifyapp@0.1.0 build: `react-scripts build`
                                    npm ERR! Exit status 1
                                    npm ERR!
                                    npm ERR! Failed at the amplifyapp@0.1.0 build script.
                                    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-01-05T14:06:31.816Z [WARNING]: 
2021-01-05T14:06:31.816Z [WARNING]: npm ERR! A complete log of this run can be found in:
                                    npm ERR!     /root/.npm/_logs/2021-01-05T14_06_31_808Z-debug.log
2021-01-05T14:06:31.816Z [HELP]: Outputting the npm debug log
                                 0 info it worked if it ends with ok
                                 1 verbose cli [
                                 1 verbose cli   '/root/.nvm/versions/node/v12.19.0/bin/node',
                                 1 verbose cli   '/root/.nvm/versions/node/v12.19.0/bin/npm',
                                 1 verbose cli   'run',
                                 1 verbose cli   'build'
                                 1 verbose cli ]
                                 2 info using npm@6.14.8
                                 3 info using node@v12.19.0
                                 4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
                                 5 info lifecycle amplifyapp@0.1.0~prebuild: amplifyapp@0.1.0
                                 6 info lifecycle amplifyapp@0.1.0~build: amplifyapp@0.1.0
                                 7 verbose lifecycle amplifyapp@0.1.0~build: unsafe-perm in lifecycle true
                                 8 verbose lifecycle amplifyapp@0.1.0~build: PATH: /root/.nvm/versions/node/v12.19.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/codebuild/output/src290553445/src/amplifyapp/node_modules/.bin:/usr/local/rvm/gems/ruby-2.4.6/bin:/usr/local/rvm/gems/ruby-2.4.6@global/bin:/usr/local/rvm/rubies/ruby-2.4.6/bin:/usr/local/rvm/bin:/root/.yarn/bin:/root/.config/yarn/global/node_modules/.bin:/root/.nvm/versions/node/v12.19.0/bin:/root/.local/bin:/root/.local/bin:/usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.dotnet/tools
                                 9 verbose lifecycle amplifyapp@0.1.0~build: CWD: /codebuild/output/src290553445/src/amplifyapp
                                 10 silly lifecycle amplifyapp@0.1.0~build: Args: [ '-c', 'react-scripts build' ]
                                 11 silly lifecycle amplifyapp@0.1.0~build: Returned: code: 1  signal: null
                                 12 info lifecycle amplifyapp@0.1.0~build: Failed to exec build script
                                 13 verbose stack Error: amplifyapp@0.1.0 build: `react-scripts build`
                                 13 verbose stack Exit status 1
                                 13 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v12.19.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
                                 13 verbose stack     at EventEmitter.emit (events.js:314:20)
                                 13 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v12.19.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
                                 13 verbose stack     at ChildProcess.emit (events.js:314:20)
                                 13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
                                 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
                                 14 verbose pkgid amplifyapp@0.1.0
                                 15 verbose cwd /codebuild/output/src290553445/src/amplifyapp
                                 16 verbose Linux 4.14.203-116.332.amzn1.x86_64
                                 17 verbose argv "/root/.nvm/versions/node/v12.19.0/bin/node" "/root/.nvm/versions/node/v12.19.0/bin/npm" "run" "build"
                                 18 verbose node v12.19.0
                                 19 verbose npm  v6.14.8
                                 20 error code ELIFECYCLE
                                 21 error errno 1
                                 22 error amplifyapp@0.1.0 build: `react-scripts build`
                                 22 error Exit status 1
                                 23 error Failed at the amplifyapp@0.1.0 build script.
                                 23 error This is probably not a problem with npm. There is likely additional logging output above.
                                 24 verbose exit [ 1, true ]
2021-01-05T14:06:31.820Z [ERROR]: !!! Build failed
2021-01-05T14:06:31.820Z [ERROR]: !!! Non-Zero Exit Code detected
2021-01-05T14:06:31.820Z [INFO]: # Starting environment caching...
2021-01-05T14:06:31.821Z [INFO]: # Environment caching completed
Terminating logging...

```

**Comment by akshbhu** [comment]
@PawanMude This doesnt seem like a problem with amplify as previous error was related to ```amplify push```

Can you try with clean your npm cache and removing node_modules folder and try again?

Let me know if that works for you?

**Comment by PawanMude** [comment]
@akshbhu : I created new c9 environment and re-done all steps mentioned in the Bug Description  + included those input params (AMPLIFY_GOOGLE_CLIENT_ID, AMPLIFY_GOOGLE_CLIENT_SECRET) as environment variables  ; still getting same error  
![image](https://user-images.githubusercontent.com/29176181/103793372-0379c700-506a-11eb-8707-53894bdb4af8.png)

**Comment by kaustavghosh06** [comment]
@PawanMude Are you still stuck with this issue?
One thing would be helpful for us to know is that have you pinned down a specific Amplify CLI version in our Amplify console build settings?

**Comment by PawanMude** [comment]
@kaustavghosh06 : Kindly refer to above logs : '@aws-amplify/cli' is version: 'latest' 
For now, i've moved ahead without amplify.
