### ISSUE TITLE
Amplify Publish fails. Amplifyhosting not found.

### ISSUE THREAD

**Issue by benoates** [aws-amplify/amplify-cli#6345]
**Trying to publish my Amplify app I get this:**

$ amplify publish

Please add hosting to your project before publishing your project
Command: amplify hosting add

$ amplify hosting add
? Select the plugin module to execute Hosting with 
 > Amplify Console (Managed hosting with custom domains, Continuous deployment)

Amplify Console hosting has already been enabled

**This is true. I do already have hosting enabled, and connected up to my repo, but it won't pull through any new code and it won't execute a publish. If I try any other variant of "amplify hosting" I get:**

```
Cannot read property 'amplifyhosting' of undefined
TypeError: Cannot read property 'amplifyhosting' of undefined
    at loadDeployType (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-console-hosting/hosting/index.js:146:41)
    at Object.configure (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-console-hosting/hosting/index.js:125:16)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-console-hosting/commands/configure.js:5:25)
    at Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-console-hosting/index.js:8:23)
    at /usr/local/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:182:51
    at executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:166:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
 
**Amplify CLI Version** 4.41.0

**Desktop (please complete the following information):**
 - OS: Ubuntu 20 running in WSL2 on Windows 10
 - Node Version. 10.19.0

**Comment by edwardfoyle** [comment]
@benoates Can you post the "hosting" block in your "amplify/backend/amplify-meta.json" file?

**Comment by benoates** [comment]
@edwardfoyle thanks, I took a look and that block was missing from that file. I have substituted in a block from another project and things seem to be going better now. I had been Googling this for a few days and couldn't find anything! Thanks again.
