### ISSUE TITLE
amplify env checkout prod|dev returns an error message

### ISSUE THREAD

**Issue by hadils** [aws-amplify/amplify-cli#6371]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**

Thank you for the provided information.

After dedicating whole day today, I'm finally able to replicate your issue on my end. To be precise, not exact error but close.

What I did was I used Amplify CLI to notifications: SMS, GCM to the local project then using AWS Pinpoint console to enable Email channel [1] before syncing the change back to local by using the command `amplify env pull --restore`. 

Below is the error I encountered 

```
✔ Initialized provider successfully.
✔ Channel is not setup for APNS 
✔ Channel information retrieved for FCM
✔ Channel information retrieved for Email
✔ Channel information retrieved for SMS
✖ update channel error
✖ There was an error initializing your environment.
There were 2 validation errors:
* MissingRequiredParameter: Missing required key 'FromAddress' in params.EmailChannelRequest
* MissingRequiredParameter: Missing required key 'Identity' in params.EmailChannelRequest
MultipleValidationErrors: There were 2 validation errors:
* MissingRequiredParameter: Missing required key 'FromAddress' in params.EmailChannelRequest
* MissingRequiredParameter: Missing required key 'Identity' in params.EmailChannelRequest
   at ParamValidator.validate (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/param_validator.js:40:28)
   at Request.VALIDATE_PARAMETERS (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/event_listeners.js:132:42)
   at Request.callListeners (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
   at callNextListener (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
   at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/event_listeners.js:86:9
   at finish (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js:386:7)
   at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js:404:9
   at Credentials.get (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/credentials.js:127:7)
   at getAsyncCredentials (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js:398:24)
   at Config.getCredentials (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js:418:9)


**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system
4.41.1

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable

1. Enable FCM/APNs/Email/SNS notfications using `amplify notifications add`
2. `amplify env checkout prod`
3. Causes the above error.
 
**Expected behavior**
A clear and concise description of what you expected to happen.

Check out of defined prod environment.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu]
 - Node Version. You can use `node -v` to check the node version on your system

MacOS 11.1
Node v12.13.1

**Additional context**
Add any other context about the problem here.

Reported to AWS support. Got workaround.

**Comment by attilah** [comment]
@hadils to make sure I understand correctly you execute `env checkout` after `notifications add`? And no push or anything in between?

**Comment by waltermvp** [comment]
Im experiencing the same behavior using 4.41.2

**Comment by waltermvp** [comment]
I have recently added apns to my project and this occurred when pushing merging into master/prod

**Comment by attilah** [comment]
@waltermvp could you provide exact repro steps to be able to help better?

**Comment by waltermvp** [comment]
1. `amplify add notifications` added APNS (in test env)
2. Pushed changes all seem to work ok
3. attempt to switch env and I see the following error

```
✔ Initialized provider successfully.
✔ Channel information retrieved for APNS
✔ Channel is not setup for FCM 
✔ Channel information retrieved for Email
✔ Channel information retrieved for SMS
✖ update channel error
✖ There was an error initializing your environment.
⠋ Updating SMS channel.There were 2 validation errors:
* MissingRequiredParameter: Missing required key 'FromAddress' in params.EmailChannelRequest
* MissingRequiredParameter: Missing required key 'Identity' in params.EmailChannelRequest
```

**Comment by waltermvp** [comment]
https://github.com/aws-amplify/amplify-cli/issues/5848

**Comment by mynameisguy** [comment]
any updates?

**Comment by giorgiocarniel** [comment]
Same error here after enabling Email on Pinpoint

**Comment by cristiandan** [comment]
I'm getting the same error, is there a solution for this?

**Comment by kaustavghosh06** [comment]
We pushed in a bunch of fixes in the latest cli version tied to notification bug fixes. Could you'll please give it a try and see if the issue still exists?
