### ISSUE TITLE
amplify env checkout NotAuthorizedException: Refresh Token has expired

### ISSUE THREAD

**Issue by ywroh** [aws-amplify/amplify-cli#6396]
**Describe the bug**
Amplify env checkout, a command that worked well in the past, suddenly encountered a NotAuthorizedException: Refresh Token has expired error.

**Amplify CLI Version**
amplify -v 4.41.0

**To Reproduce**
Failed to refresh tokens.
Failed to get credentials.
NotAuthorizedException: Refresh Token has expired
    at Request.extractError (/Users/ywroh/work/amplify-cli/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.callListeners (/Users/ywroh/work/amplify-cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/ywroh/work/amplify-cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/ywroh/work/amplify-cli/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/Users/ywroh/work/amplify-cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/ywroh/work/amplify-cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/ywroh/work/amplify-cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/ywroh/work/amplify-cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/ywroh/work/amplify-cli/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/Users/ywroh/work/amplify-cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'NotAuthorizedException',
  time: 2021-01-15T12:19:50.101Z,
  requestId: 'c0d*******1ff',
  statusCode: 400,
  retryable: false,
  retryDelay: 11.501672036823617
}

**Expected behavior**
I wanted amplify env to change from dev to test.

**Screenshots**
![스크린샷 2021-01-15 오후 9 47 09](https://user-images.githubusercontent.com/39849622/104729130-51ce4a80-577b-11eb-96a8-242d7d6d00d3.png)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.1
 - Node Version: v15.2.0

**Additional context**
[Solved]
As a result of checking the log through amplify-dev, it was confirmed that the configLevel, useProfile, and profileName of the env test in project/amplify/.config/local-aws-info.json were different, and it was fixed by modifying the same as dev.

**Comment by attilah** [comment]
Glad it's solved, closing the issue.
