### ISSUE TITLE
Error with DeploymentAwaiter on amplify push

### ISSUE THREAD

**Issue by jahluwalia** [aws-amplify/amplify-cli#6421]
I'm following the tutorial at [Zero effort container deployment](https://aws.amazon.com/blogs/mobile/zero-effort-container-deployment-for-graphql-and-rest-apis-and-web-hosting-with-amplify-cli/)

When I do an `amplify push` or `amplify push --forcePush --yes`, I get the following error.

```
CREATE_FAILED      DeploymentAwaiter                             AWS::CloudFormation::CustomResource Mon Jan 18 2021 23:24:25 GMT+0000 (Coordinated Universal Time) Failed to create resource. The execution didn't succeed  Logs: /aws/lambda/amplify-qeaas-dev-225403-AwaiterCustomCompleteHan-1DL4N6UBA969D      at Runtime.exports.handler (/var/task/index.js:102:13)     at processTicksAndRejections (internal/process/task_queues.js:97:5)
CREATE_FAILED      amplify-qeaas-dev-225403-apiqeaas-BI4LCNPE2NG AWS::CloudFormation::Stack          Mon Jan 18 2021 23:24:26 GMT+0000 (Coordinated Universal Time) The following resource(s) failed to create: [DeploymentAwaiter]. 
```
The steps taken were:

```
amplify init
amplify configure project
amplify add api
amplify push
```

Any suggestions?

Thanks,
Jas

**Comment by jahluwalia** [comment]
This issue has been resolved. It turns out the container was not building locally due to an error in the dockerfile. Once this was resolved, the amplify push succeeded.
