### ISSUE TITLE
Amplify GraphiQL error using @key with AWSTimestamp type

### ISSUE THREAD

**Issue by jaga810** [aws-amplify/amplify-cli#6436]
**Describe the bug**

DynamoDB local gives error message in running mutation via Amplify GraphiQL only when the type has GSI setting (@key) of AWSTimestamp.

**Amplify CLI Version**

Rproduced at v4.41.2 and v4.40.0.

**To Reproduce**

1. Create GraphQL API with below schema.graphql.
```schema.graphql
type Test
@model
  @key(name: "SortByTimestamp", fields:["type", "timestamp"], queryField: "testSortedByTimestamp")
{
  type: String!
  timestamp: AWSTimestamp!
}
```
2. run `$ amplify mock api`

2. Run below mutation at Amplify GraphiQL.
```Mutation Operation at Ampilfy GraphiQL
mutation MyMutation {
  createTest(input: {type: "test", timestamp: 111111}) {
    id
    timestamp
    type
  }
}
```

4. You got the error.
```Error Message on Amplify GraphiQL
{
  "data": {
    "createPost": null
  },
  "errors": [
    {
      "message": "One or more parameter values were invalid: Type mismatch for Index Key",
      "errorType": "DynamoDB:ValidationException",
      "data": null,
      "errorInfo": null,
      "path": [
        "createPost"
      ],
      "locations": [
        {
          "line": 2,
          "column": 3,
          "sourceName": "GraphQL request"
        }
      ]
    }
  ]
}
```

Please confirm it doesn't give error when you use `Int` instead of `AWSTimestamp`.
```schema.graphql
type Test
@model
  @key(name: "SortByTimestamp", fields:["type", "timestamp"], queryField: "byTimestamp")
{
  type: String!
  timestamp: Int!
}
```

Without @key it doesn't give error.
```schema.graphql
type Test
@model
{
  type: String!
  timestamp: Int!
}
```
If you call local api directly, it gives error.
```mutation.sh
script='mutation MyMutation {
  createTest(input: {type: \"test\", timestamp: 111111}) {
    id
    timestamp
    type
  }
}
'
script="$(echo $script)" 

curl -H "Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3ZDhjYTUyOC00OTMxLTQyNTQtOTI3My1lYTVlZTg1M2YyNzEiLCJjb2duaXRvOmdyb3VwcyI6W10sImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJhbGdvcml0aG0iOiJIUzI1NiIsImlzcyI6Imh0dHBzOi8vY29nbml0by1pZHAudXMtZWFzdC0xLmFtYXpvbmF3cy5jb20vdXMtZWFzdC0xX2Zha2VfaWRwIiwicGhvbmVfbnVtYmVyX3ZlcmlmaWVkIjp0cnVlLCJjb2duaXRvOnVzZXJuYW1lIjoidXNlcjMiLCJjb2duaXRvOnJvbGVzIjpbXSwiYXVkIjoiMmhpZmEwOTZiM2EyNG12bTNwaHNrdWFxaTMiLCJldmVudF9pZCI6IjE4ZjQwNjdlLTk5ODUtNGVhZS05ZjMzLWY0NWY0OTU0NzBkMCIsInRva2VuX3VzZSI6ImlkIiwicGhvbmVfbnVtYmVyIjoiKzEyMDYyMDYyMDE2IiwiZXhwIjoxNjExMTA0MjE0NCwiZW1haWwiOiJ1c2VyQGRvbWFpbi5jb20iLCJhdXRoX3RpbWUiOjE2MTEwMzQ2OTEsImlhdCI6MTYxMTAzNDY5MX0.oVnA7AnYGuU5X0cpiMZxAUfK1uWpkLJ_YuLAHwb21tQ" \
    -H 'Content-Type: application/json' \
    -X POST -d "{ \"query\": \"$script\"}" http://localhost:20002/graphql \
    | jq .
```

```Return
{
  "data": {
    "createTest": null
  },
  "errors": [
    {
      "message": "One or more parameter values were invalid: Type mismatch for Index Key",
      "errorType": "DynamoDB:ValidationException",
      "data": null,
      "errorInfo": null,
      "path": [
        "createTest"
      ],
      "locations": [
        {
          "line": 1,
          "column": 23,
          "sourceName": "GraphQL request"
        }
      ]
    }
  ]
}

```

**Expected behavior**

I expect operation execution success without error in Amplify Mocking using @key including AWSTimestamp fields.

**Screenshots**

![Screen Shot 2021-01-20 at 9 26 55](https://user-images.githubusercontent.com/13917206/105111479-5771ba80-5b04-11eb-82b6-e04f15e3fa75.png)

**Desktop (please complete the following information):**

- OS: Mac
- Node Version: 12.16.1
- $ java --version
  - java 12.0.2 2019-07-16
  - Java(TM) SE Runtime Environment (build 12.0.2+10)
  - Java HotSpot(TM) 64-Bit Server VM (build 12.0.2+10, mixed mode, sharing)

**Log output**

Amplify Mocking error log.
```
Error while executing Local DynamoDB
{
    "version": "2018-05-29",
    "operation": "PutItem",
    "key": {
        "id": {
            "S": "524aed48-c0a1-4bb0-a335-d90d1632ee35"
        }
    },
    "attributeValues": {
        "type": {
            "S": "test"
        },
        "timestamp": {
            "S": "111111"
        },
        "id": {
            "S": "524aed48-c0a1-4bb0-a335-d90d1632ee35"
        },
        "createdAt": {
            "S": "2021-01-20T00:26:26.892Z"
        },
        "updatedAt": {
            "S": "2021-01-20T00:26:26.892Z"
        },
        "__typename": {
            "S": "Test"
        }
    },
    "condition": {
        "expression": "attribute_not_exists(#id)",
        "expressionNames": {
            "#id": "id"
        }
    }
}
ValidationException: One or more parameter values were invalid: Type mismatch for Index Key
    at Request.extractError (/Users/daisnaga/.nodebrew/node/v12.16.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.callListeners (/Users/daisnaga/.nodebrew/node/v12.16.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/daisnaga/.nodebrew/node/v12.16.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/daisnaga/.nodebrew/node/v12.16.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/Users/daisnaga/.nodebrew/node/v12.16.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/daisnaga/.nodebrew/node/v12.16.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/daisnaga/.nodebrew/node/v12.16.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/daisnaga/.nodebrew/node/v12.16.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/daisnaga/.nodebrew/node/v12.16.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/Users/daisnaga/.nodebrew/node/v12.16.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  message: 'One or more parameter values were invalid: Type mismatch for Index Key',
  code: 'ValidationException',
  time: 2021-01-20T00:26:26.906Z,
  requestId: '88fea506-e7e7-4462-a144-f5c1d7df5aa4',
  statusCode: 400,
  retryable: false,
  retryDelay: 47.98286791023938
}
```
**Additional context**

N/A

**Comment by xitanggg** [comment]
Based on your log output, it seems the error is that `timestamp` is defined as a string type.
```
"timestamp": {
            "S": "111111"
        },
```

One possible source of error is that you first define your schema with `timestamp` as a `string` type and then later changes it to `int`. Note that this wouldn't work for DynamoDB if your table contains existing data with `timestamp` as a `string` since it is type cast and can't change type on the fly. You might want to delete your local database (as shown below) and retry it. 

```
.
└── mock-data/
    └── fake_us-fake-1.db
```

**Comment by kaustavghosh06** [comment]
@xitanggg  Did you get a chance to test out @xitanggg's recommendation?  Did that fix the issue?

**Comment by xitanggg** [comment]
> @xitanggg Did you get a chance to test out @xitanggg's recommendation? Did that fix the issue?

You @ me twice, @jaga810 should be included :)

Since I am here, @kaustavghosh06, do you know when will the next release for the cli be out? It has been 23 days since the last release. There are some new commits that fix some of the bugs I am encountering. Thanks.

**Comment by kaustavghosh06** [comment]
@xitanggg We're working on a release as we speak :)

**Comment by xitanggg** [comment]
@kaustavghosh06 Amazing, excited for it! Cheering for you and your team!

**Comment by jaga810** [comment]
Sorry I forgot to reply and I noticed I didn't reply this issue in reading [CHANGELOG of Amplify CLI v4.48.0](https://github.com/aws-amplify/amplify-cli/releases?after=amplify-category-auth%402.30.2) 
Thank you for update!!! This is awesome!
