### ISSUE TITLE
Amplify commands has TypeError preventing schema change

### ISSUE THREAD

**Issue by elcain** [aws-amplify/amplify-cli#6518]
> **Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the
> [Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
I am using Amplify with a React Native Project. I am realizing that I am not able to use `Amplify` commands on the CLI without an error: 

```bash
TypeError: Cannot read property 'forEach' of undefined
    at AmplifyToolkit.showHelpfulProviderLinks [as _showHelpfulProviderLinks] (/usr/local/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/show-helpful-provider-links.js:12:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.exports.run (/usr/local/lib/node_modules/@aws-amplify/cli/lib/commands/status.js:6:5)
    at async Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/lib/index.js:173:9)
    at async executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:153:5)
    at async Object.executeCommand (/usr/local/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:35:9)
    at async Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/lib/index.js:82:9)
```

**Amplify CLI Version**
4.32.1

**To Reproduce**
`Amplify status` or `Amplify push` 

**Expected behavior**
Amplify status will work, but show the error. `Amplify push` will fail because of this error. 

**Desktop (please complete the following information):**

- OS: Mac
- Node Version: v12.18.4

**Comment by jhockett** [comment]
Hi @elcain, can you try upgrading to the latest version of the CLI and see if you're still hit this error?

`npm install -g @aws-amplify/cli`

**Comment by elcain** [comment]
Hi @jhockett so I went ahead and upgraded. Now if I issue a command I get something that says: 

`Amplify has been upgraded to handle secrets more securely by migrating some values in team-provider-info.json to deployment-secrets.js
on
You can create a back up of the team-provider-info.json file before proceeding.`

If I hit no, the command just stops. If I hit yes, I get another error: 

`Error: File at path: '/Users/elijahcain/Documents/Sonar-current/amplify/backend/auth/sonarbdbce738/parameters.json' does not exist
    at Function.JSONUtilities.readJson (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/jsonUtilities.js:40:19)
    at StateManager.getData (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/state-manager/stateManager.js:215:56)
    at StateManager.getResourceParametersJson (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/state-manager/stateManager.js:112:25)`

I'm not sure what this `parameters.json` file is.

**Comment by jhockett** [comment]
Here's the docs on describing the `parameters.json` file: https://docs.amplify.aws/cli/reference/files#parametersjson

Those files are used for passing in values to the cloudformation templates.

Can you try creating an empty json file and then see if that allows you to continue?
`echo '{}' > /Users/elijahcain/Documents/Sonar-current/amplify/backend/auth/sonarbdbce738/parameters.json`

**Comment by elcain** [comment]
hmm ok when I go to the path up to `backend`, I actually don't have a `Auth` folder.

**Comment by jhockett** [comment]
@elcain what categories are you trying to use? Did you delete anything manually?

**Comment by elcain** [comment]
@jhockett I don't believe I deleted anything manually. I am using the Amplify Auth library, but not in the branch. I switched to my branch where I am using the Auth library and even there I do not have a `Auth` folder.

**Comment by ammarkarachi** [comment]
@elcain Do you have a json structure that looks like this in you `team-provider-info.json`?

**Comment by elcain** [comment]
@ammarkarachi it does have that json.

**Comment by jhockett** [comment]
Hi @elcain, can you please try running `amplify pull --restore` to restore your environment to the last pushed state?

**Comment by elcain** [comment]
Hey @jhockett so I just get the same error when I try and restore. I was looking back and the commits, and the `Auth` folder WAS accidentally deleted. Is there a way to re-generate the folder?

**Comment by dorontal** [comment]
I just saw this same error (I believe) with a newer version of Amplify: 4.42.0.

I noticed this error pop up just after an upgrade from some months-old version of the cli to version 4.42.0.

Here's my transcript of (seemingly) the same error:
```

Current Environment: dev

| Category | Resource name                      | Operation | Provider plugin   |
| -------- | ---------------------------------- | --------- | ----------------- |

...

Tag Changes Detected
Cannot read property 'forEach' of undefined
TypeError: Cannot read property 'forEach' of undefined
    at AmplifyToolkit.showHelpfulProviderLinks [as _showHelpfulProviderLinks] (/usr/local/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/show-helpful-provider-links.js:12:15)
    at processTicksAndRejections (internal/process/task_queues.js:88:5)
    at async Object.exports.run (/usr/local/lib/node_modules/@aws-amplify/cli/lib/commands/status.js:6:5)
    at async Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/lib/index.js:216:9)
    at async executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:166:5)
    at async Object.executeCommand (/usr/local/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:35:9)
    at async Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/lib/index.js:92:9)
dtal@thing5: amplify -v
4.42.0
```

@jhockett - I just tried your suggestion right after receiving this error and got another error. It's strange it reports "environment 'dev' not found because I did not remove that environment. Here is the new error trying to run your suggested cli command `amplify pull --restore`, then trying to add env because it seems to need it, and getting the error:
```
dtal@thing5: !2034
amplify pull --resotre
Environment 'dev' not found.
Try running "amplify env add" to add a new environment.
If this backend already exists, try restoring its definition in your team-provider-info.json file.
dtal@thing5: amplify env add
Note: It is recommended to run this command from the root of your app directory
? Do you want to use an existing environment? Yes
? Choose the environment you would like to use: dev
Using default provider  awscloudformation
init failed
TypeError [ERR_INVALID_ARG_TYPE]: The 'request' argument must be string. Received type undefined
    at onSuccess (/usr/local/lib/node_modules/@aws-amplify/cli/lib/init-steps/s9-onSuccess.js:53:28)
    at Object.exports.run (/usr/local/lib/node_modules/@aws-amplify/cli/lib/commands/init.js:29:19)
    at processTicksAndRejections (internal/process/task_queues.js:88:5)
dtal@thing5: 
```

**Comment by jhockett** [comment]
> Hey @jhockett so I just get the same error when I try and restore. I was looking back and the commits, and the `Auth` folder WAS accidentally deleted. Is there a way to re-generate the folder?

@elcain if the folder exists in an old git commit, you should be able to retrieve it from git.

**Comment by jhockett** [comment]
@dorontal do you know what version you upgraded from? Is the file `team-provider-info.json` present in the amplify folder?

**Comment by dorontal** [comment]
@jhockett Unfortunately I lost that information. Just checked the shell history and noticed that it was something installed around last summer via pip3 and resided in /usr/bin/aws, while the new one is all in /usr/local/bin.  Right now, however, I am rebuilding the entire project from scratch, just to make sure I did not report the above for some silly reason, trying to reproduce the problem to be sure it still exists -- will report once that is done.

**Comment by elcain** [comment]
@jhockett yup once I got that folder back I was able to use `amplify pull --restore` and everything works fine now.

**Comment by jhockett** [comment]
Glad to hear everything has been resolved!
