### ISSUE TITLE
Unable to push new env due to undefined resources

### ISSUE THREAD

**Issue by n3b** [aws-amplify/amplify-cli#6546]
**Describe the bug**
I have an existing env with auth, api, hosting and functions. I want to create a second env. 
According to docs calling `amplify env add` and `amplify push` should be sufficient. 
However amplify push fails complaining about undefined resources (user pool and rds, like: `Template error: instance of Fn::GetAtt references undefined resource auth******`) even though auth and api are stated as `create` when I do `amplify status`.

**Amplify CLI Version**
4.41.2

**To Reproduce**
`amplify env add`
`amplify push`

**Expected behavior**
The second environment is created in cloud successfully.

**Desktop (please complete the following information):**

- OS: [e.g. Mac/Windows/Ubuntu]
macOS
- Node Version. You can use `node -v` to check the node version on your system
- v15.5.0

**Log output**
```
ValidationError: Template error: instance of Fn::GetAtt references undefined resource auth******
    at Request.extractError (/Users/n3b/.nvm/versions/node/v15.5.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/query.js:50:29)
```

**Comment by jhockett** [comment]
Hi @n3b, can you please send your project's amplify folder to amplify-cli@amazon.com so that we can debug what's happening? Please redact any sensitive information prior to sending.

**Comment by n3b** [comment]
@jhockett sorry but I don't think I'd be able to find some time to filter out sensitive data. I also could possible remove something that is necessary for debugging.
Not sure if it matters, but when I create a new env everything in `team-provider-info.json` (except `awscloudformation` section) takes their ids/roles from previous env.

**Comment by jhockett** [comment]
@n3b no problem. According to the error message, auth is undefined at the point of failure during push. Can you try running `amplify push auth` and see what happens?

**Comment by n3b** [comment]
@jhockett I just created a new env, did `amplify push auth` and it completed successfully. 
However when I do `amplify push api` after auth created, it fails creating resolvers `No data source found named xxx_rds_DataSource (Service: AWSAppSync; Status Code: 404; Error Code: NotFoundException;` and it ends up with 
```
Resource is not in the state stackUpdateComplete
There was an error pushing the API resource
ResourceNotReady: Resource is not in the state stackUpdateComplete
```

Another small issue I noticed: when I want to use AWS profile from my profiles file amplify-cli shows a list with only the first profile, so I have to enter credentials each time. I've compared my profiles format with the doc and it seems to be correct.

**Comment by kaustavghosh06** [comment]
@n3b Were you able to resolve this issue? Did you import an RDS datasource in the environment you were trying to clone from?

**Comment by n3b** [comment]
@kaustavghosh06 no, I'm just not using multienv. Not sure I understand what'd you mean with "import an RDS" as it was created automatically in dev env by `amplify api add`.

**Comment by nickday** [comment]
I'm having a similar issue, cannot get auth deployed at all after creating a new environment, version 4.41.0.

Currently have a "sandbox" environment.

Added new "staging" environment:
`amplify env add`

`amplify status` shows everything ready to be created as expected.

`amplify push` fails with:
```
An error occurred during the push operation: Template error: instance of Fn::GetAtt references undefined resource authappnameXXXXXXXXXXXXXXXX
```

Try and push just auth with `amplify push auth` and fails with:
```
✔ All resources are updated in the cloud

Error: Cognito UserPool does not exists
    at getAuthResourceName (/Users/Nick/.nvm/versions/node/v12.18.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/utils/getAuthResourceName.js:10:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at uploadFiles (/Users/Nick/.nvm/versions/node/v12.18.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/provider-utils/awscloudformation/utils/trigger-file-uploader.js:20:26)
    at /Users/Nick/.nvm/versions/node/v12.18.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/commands/auth/push.js:14:9
    at Object.executeAmplifyCommand (/Users/Nick/.nvm/versions/node/v12.18.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/index.js:373:3)
    at executePluginModuleCommand (/Users/Nick/.nvm/versions/node/v12.18.3/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:181:3)
    at Object.executeCommand (/Users/Nick/.nvm/versions/node/v12.18.3/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:28:5)
    at Object.run (/Users/Nick/.nvm/versions/node/v12.18.3/lib/node_modules/@aws-amplify/cli/src/index.ts:105:5)
Error: Unable to upload trigger files to S3
    at uploadFiles (/Users/Nick/.nvm/versions/node/v12.18.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/provider-utils/awscloudformation/utils/trigger-file-uploader.js:49:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
There was an error pushing the auth resource
```

Any ideas what the problem is here? Totally blocked by this as can't get a new environment set up.
