### ISSUE TITLE
add function: access custom resource from lambda function throws error

### ISSUE THREAD

**Issue by alissaVrk** [aws-amplify/amplify-cli#6583]
**Describe the bug**
first, added a custom category with a kinesis resource successfully - kinesis stream was added in aws console.
then added a new lambda function 
``` amplify function add```
when prompted to select the other resources to access from my function 
``` 
Do you want to access other resources in this project from your Lambda function? Yes
 Select the category - myPretty
```
 my custom resource was listed as one of the options (as expected).
next prompt is to select the operations permitted
```Select the operations you want to permit for kinesisPretty create, read, update, delete```

selected all, clicked enter and got an error

```
TypeError: Cannot read property 'length' of undefined
    at AmplifyToolkit.getCategoryPluginInfo [as _getCategoryPluginInfo] (C:\Users\aliss\AppData\Roaming\npm\node_modules\@aws-amplify\cli\lib\extensions\amplify-helpers\get-category-pluginInfo.js:7:32)
    at AmplifyToolkit.exports.invokePluginMethod [as _invokePluginMethod] (C:\Users\aliss\AppData\Roaming\npm\node_modules\@aws-amplify\cli\lib\extensions\amplify-helpers\invoke-plugin-method.js:24:40)
    at Object.exports.askExecRolePermissionsQuestions (C:\Users\aliss\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-category-function\lib\provider-utils\awscloudformation\service-walkthroughs\execPermissionsWalkthrough.js:143:94)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.createWalkthrough (C:\Users\aliss\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-category-function\lib\provider-utils\awscloudformation\service-walkthroughs\lambda-walkthrough.js:43:78)
    at async addFunctionResource (C:\Users\aliss\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-category-function\lib\provider-utils\awscloudformation\index.js:58:9)
    at async Object.executeAmplifyCommand (C:\Users\aliss\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-category-function\lib\index.js:195:5)
    at async executePluginModuleCommand (C:\Users\aliss\AppData\Roaming\npm\node_modules\@aws-amplify\cli\lib\execution-manager.js:166:5)
    at async Object.executeCommand (C:\Users\aliss\AppData\Roaming\npm\node_modules\@aws-amplify\cli\lib\execution-manager.js:35:9)
    at async Object.run (C:\Users\aliss\AppData\Roaming\npm\node_modules\@aws-amplify\cli\lib\index.js:92:9)
```

**Amplify CLI Version**
4.41.1

**Expected behavior**
hopefully, add the selected permissions to the lambda function
otherwise, not listing the custom resource as an option

windows 10, node 12.18.4

**Comment by SwaySway** [comment]
Hello @alissaVrk 
A few questions here
- Did you follow this guide when adding in a custom resource? Docs: https://docs.amplify.aws/cli/usage/customcf#add-custom-aws-resources
- Could you provide a copy of how the custom resource was added? If it's sensitive you can email it over to us at amplify-cli@amazon.com

**Comment by alissaVrk** [comment]
thank you for the quick response
I did follow the documentation, but adding a dependency **on** the custom resource is not documented there, only the other way around.

any way, here is the backend-config:
```
"myPretty": {
    "kinesisPretty": {
      "service": "Kinesis",
      "providerPlugin": "awscloudformation"
    }
  },
"function": {
  "foofoo": { //this is the function that I wan to put items to the kinesis stream
      "build": true,
      "providerPlugin": "awscloudformation",
      "service": "Lambda",
      "dependsOn": [] // nothing added here by the cli
    },
...
}
```

in `amplify/backend/myPretty/kinesisPretty` I have 
template.json:
```
{
    "AWSTemplateFormatVersion": "2010-09-09",
    "Description": "Kinesis resource stack creation using Amplify CLI",
    "Parameters": {
        "env": {
            "Type":  "String"
        },
        "kinesisStreamName": {
            "Type": "String"
        },
        "kinesisStreamShardCount": {
            "Type": "Number",
            "Default": 1
        },
        "authPolicyName": {
            "Type": "String"
        },
        "unauthPolicyName": {
            "Type": "String"
        },
        "authRoleName": {
            "Type":  "String"
        },
        "unauthRoleName": {
            "Type":  "String"
        }
    },
    "Conditions": {
        "ShouldNotCreateEnvResources": {
            "Fn::Equals": [
                { "Ref": "env" },
                "NONE"
            ]
        }
    },
    "Resources": {
        "KinesisStream": {
            "Type": "AWS::Kinesis::Stream",
            "Properties": {
                "Name": {
                    "Fn::Join": [
                        "-",
                        [
                          { "Ref": "kinesisStreamName" },
                          { "Ref": "env"}
                        ]
                    ]
                },
                "ShardCount": { "Ref": "kinesisStreamShardCount" }
            }
        },
        "AuthRolePolicy": {
            "Type": "AWS::IAM::ManagedPolicy",
        },
        "CognitoUnauthPolicy": {
            "Type": "AWS::IAM::Policy",
            "Properties": {
                "PolicyName": {"Ref": "unauthPolicyName" },
                "Roles": [ 
                    {"Ref": "unauthRoleName" }
                ],
                "PolicyDocument": {
                    "Version": "2012-10-17",
                    "Statement": [{
                        "Effect": "Allow",
                        "Action": [
                            "kinesis:PutRecord",
                            "kinesis:PutRecords"
                        ],
                        "Resource": {
                            "Fn::GetAtt": ["KinesisStream", "Arn"]
                        }
                    }]
                }
            }
        },
        "CognitoAuthPolicy": {
            "Type": "AWS::IAM::Policy",
            "Properties": {
                "PolicyName": {"Ref": "authPolicyName" },
                "Roles": [ 
                    {"Ref": "authRoleName" }
                ],
                "PolicyDocument": {
                    "Version": "2012-10-17",
                    "Statement": [{
                        "Effect": "Allow",
                        "Action": [
                            "kinesis:PutRecord",
                            "kinesis:PutRecords"
                        ],
                        "Resource": {
                            "Fn::GetAtt": ["KinesisStream", "Arn"]
                        }
                    }]
                }
            }
        }
    },
    "Outputs": {
        "kinesisStreamArn": {
            "Value": {"Fn::GetAtt": ["KinesisStream", "Arn"] }
        },
        "kinesisStreamId": { 
            "Value": {"Ref": "KinesisStream" }
        },
        "kinesisStreamShardCount": {
            "Value": {"Ref": "kinesisStreamShardCount" }
        }
    }
}

```
I guess I don't need the cognito policies, since only the lambda is going to put items. (they are there cause I copied the template from the analytics category)

and parameters.json:
```
{
    "kinesisStreamName": "kinesisTest",
    "kinesisStreamShardCount": 1,
    "authRoleName": {
      "Ref": "AuthRoleName"
    },
    "unauthRoleName": {
      "Ref": "UnauthRoleName"
    },
    "authPolicyName": "kinesis_amplify_test",
    "unauthPolicyName": "kinesis_amplify_test"
  }
```

**Comment by alissaVrk** [comment]
btw, I managed to achieve what I want: 
both adding a function that puts records to the stream by a lambda function 
and adding a function that is triggered by this stream

by manually editing the `backend-config.json` and the `template.json` of both lambda functions
but I guess that this isn't the best way to do it, since all these files are autogenerated by amplify and I'm afraid of bugs in the future when I'll edit these functions via the cli

**Comment by alissaVrk** [comment]
any hope..? :)

**Comment by SwaySway** [comment]
You should be able to add a different policy under the function stack (example below) this way if you change anything else in functions it wont overwrite the iam policy resource
```json
"CustomResourcesPolicy": {
      "Type": "AWS::IAM::Policy",
      "DependsOn": [
        "LambdaExecutionRole"
      ],
      "Properties": {
        "PolicyName": "amplify-lambda-custom-execution-policy",
        "Roles": [
          {
            "Ref": "LambdaExecutionRole"
          }
        ],
        "PolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "kinesis:RemoveTagsFromStream",
                "kinesis:PutRecord",
                "kinesis:DeleteStream",
                "kinesis:DescribeStreamSummary",
                "kinesis:AddTagsToStream",
                "kinesis:DescribeStream",
                "kinesis:ListTagsForStream"
              ],
              "Resource": [
                {
                  "Fn::Sub": [
                    "${kinesisStreamArn}",
                    {
                      "kinesisStreamArn": {
                        "Ref": "kinesismycustomstreamkinesisStreamArn"
                      }
                    }
                  ]
                }
              ]
            }
          ]
        }
      }
    }
```
In the parameters file you can ref the output from the custom kinesis stack
```json
{
  "kinesismycustomstreamkinesisStreamArn": {
    "Fn::GetAtt": [
      "kinesismycustomstream",
      "Outputs.kinesisStreamArn"
    ]
  }
}
```
As for creating the trigger you can add the arn of the kinesis stream for that in the function workflow

**Comment by alissaVrk** [comment]
thanks, actually I figured this might help
I need to change the backend-config as well.. this gets overridden too

anyway I think that if it doesn't work,  at least remove the option to select the custom resource as dependency in the cli

**Comment by kaustavghosh06** [comment]
@alissaVrk Glad you were able to figure out the issue. Closing this issue.
