### ISSUE TITLE
amplify mock api fails with "Cannot destructure property 'timeout' of 'undefined' as it is undefined"

### ISSUE THREAD

**Issue by estyh** [aws-amplify/amplify-cli#6653]
**Describe the bug**
`amplify mock api` spins up a graphql server. The query types have a function directive that resolves to a lambda function. When trying to query the api, the server sends out an error:

```
Lambda Data source failed with the following error
TypeError: Cannot destructure property 'timeout' of 'undefined' as it is undefined.
    at getCancellableTimer (C:\Users\home\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-util-mock\src\func\index.ts:73:32)
    at Object.timeConstrainedInvoker (C:\Users\home\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-util-mock\src\func\index.ts:65:29)
    at Object.invoke (C:\Users\home\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-util-mock\src\api\api.ts:203:22)
    at LambdaDataLoader.<anonymous> (C:\Users\home\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-appsync-simulator\src\data-loader\lambda\index.ts:25:37)
    at step (C:\Users\home\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-appsync-simulator\lib\data-loader\lambda\index.js:33:23)
    at Object.next (C:\Users\home\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-appsync-simulator\lib\data-loader\lambda\index.js:14:53)
    at C:\Users\home\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-appsync-simulator\lib\data-loader\lambda\index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\home\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-appsync-simulator\lib\data-loader\lambda\index.js:4:12)
    at LambdaDataLoader.load (C:\Users\home\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-appsync-simulator\lib\data-loader\lambda\index.js:56:16)
```
_**This works perfectly with cli version 4.43.0**_

**Amplify CLI Version**
4.44.0

**To Reproduce**
Here are some relevant snippets...
From the schema.graphql file:
```
type Query {
  listCases: ModelCasesConnection @function(name: "bnxEnrollmentStats-${env}")
}

type ModelCasesConnection {
  items: [EnrollmentStatsCase]!
}

type EnrollmentStatsCase {
  id: Int!
  name: String!
}
```

_bnxEnrollmentStats/src/index.js_
```
/* Amplify Params - DO NOT EDIT
	ENV
	REGION
Amplify Params - DO NOT EDIT */

exports.handler = async (event) => {
  const response = {
    items: [
      {
        id:1,name:'abc'
      },
    ],
  };
  return response;
};
```

**Expected behavior**
No error...

**Desktop (please complete the following information):**

- OS: Windows 10
- Node Version. 14.15.3

**Comment by wbroek** [comment]
Same here when executing a graphql mutation with the function directive:
```
AppSync Mock endpoint is running at http://192.168.1.5:20002
Lambda Data source failed with the following error
TypeError: Cannot destructure property `timeout` of 'undefined' or 'null'.
    at getCancellableTimer (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/src/func/index.ts:73:29)
    at Object.timeConstrainedInvoker (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/src/func/index.ts:65:29)
    at Object.invoke (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/src/api/api.ts:203:22)
    at LambdaDataLoader.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-appsync-simulator/src/data-loader/lambda/index.ts:25:37)
    at step (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-appsync-simulator/lib/data-loader/lambda/index.js:33:23)
    at Object.next (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-appsync-simulator/lib/data-loader/lambda/index.js:14:53)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-appsync-simulator/lib/data-loader/lambda/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-appsync-simulator/lib/data-loader/lambda/index.js:4:12)
    at LambdaDataLoader.load (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-appsync-simulator/lib/data-loader/lambda/index.js:56:16)
TypeError: context.done is not a function
    at exports.handler (/Users/wouter/stack/Projects/Clinicards/Clinicards demo/amplify/backend/function/inviteesharedfunction/src/index.js:307:15)
    at Promise (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-nodejs-function-runtime-provider/lib/utils/execute.js:84:35)
    at new Promise (<anonymous>)
    at invokeFunction (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-nodejs-function-runtime-provider/lib/utils/execute.js:74:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:77480) UnhandledPromiseRejectionWarning: #<Object>
(node:77480) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:77480) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Looked into it and looks like @edwardfoyle forgot to see that the options variable can be undefined and needs to be optional (which it was previously); and when destructered (on undefined) it gets this error. The change was here: https://github.com/aws-amplify/amplify-cli/commit/0e5d85be780c800aad2322ebb2b5598187c97ae8#diff-2bafdb731bd3253953baa9f82dd6c82fee246902fb1717d0e05f38db85496359L67
Did not have the time for a PR yet; maybe later.....

**Amplify CLI Version**
4.44.0 (works with older versions)

**Desktop (please complete the following information):**

OS: Mac OS X 11.2.1
Node Version. 10.23.1

**Comment by estyh** [comment]
@wbroek brilliant, at least I have a workaround now!
`amplify mock api --timeout=20` works without errors
thanks

**Comment by edwardfoyle** [comment]
Hi @estyh thanks for reporting this. The timeout destructuring is a bug, will get a fix for that out soon.

It looks like you are also still using context.done() in your function. This behavior has been removed in the latest changes to mock as this has been deprecated by lambda for several years now. You'll need to change your lambdas to use the callback() function or async / await for them to continue to work with mock.

**Comment by estyh** [comment]
@edwardfoyle Thanks for looking into this.

Note sure what you mean about the context.done() - the lambda function is in the issue description above - using async/await (well, it's not awaiting anything...). I see the context.done() in the error stack, but it's not coming from my lambda code...

**Comment by wbroek** [comment]
@edwardfoyle yeah I know need upgrade that part :)

**Comment by edwardfoyle** [comment]
The fix for this has been released in the latest version of the CLI. Please upgrade to the latest version to try it out.

**Comment by wbroek** [comment]
@edwardfoyle works like a charm; thank you
