### ISSUE TITLE
Query returns incomplete response (despite limit value)

### ISSUE THREAD

**Issue by waltermvp** [aws-amplify/amplify-cli#6674]
I am using the latest version of the cli.

When I query a specific appsync query from a lamba function i get an incomplete result. 

this is the schema model

```
type MenuParticipation
  @model #(subscriptions: { level: public })
  @auth(
    rules: [
      { allow: owner }
      { allow: private, provider: iam }
      { allow: public }
    ]
  )
  @key(
    name: "byMenu"
    fields: ["menuID", "itemID"]
    queryField: "participationsByMenu"
  )
  @key(name: "byOwner", fields: ["owner"], queryField: "participationsByOwner")
  @key(
    name: "byItem"
    fields: ["itemID", "menuID"]
    queryField: "participationsByItem"
  ) {
  id: ID!
  menuID: ID!
  itemID: ID!
  owner: String!
  menu: Menu @connection(name: "MenuParticipation")
  item: MenuItem! @connection(name: "MenuItemParticipation")
}
```

This is where the call is made (from a lambda fruntion)
```
const allParticipationsForMenuFunction = async ({ menuID }) => {
  console.log("mebnydiiid", menuID);
  try {
    const result1 = await appSyncQuery({
      query: participationsByMenu,
      operationName: "ParticipationsByMenu",
      variables: {
        menuID,
        sortDirection: "DESC",
        limit: 999,
        // createdAt: { gt: since },
      },
    });
    return result1;
  } catch (e) {
    console.log("activeMenuQueryFunction error: ", e);
    throw e;
  }
};
```

The issue is that the response seems to be clipped. 

![Screen Shot 2021-02-18 at 10 36 41 PM](https://user-images.githubusercontent.com/1158238/108454137-d1977b00-7239-11eb-8811-70c951313582.png)
Notice the incomplete / cut off json . This incomplete JSON causes this error:

```

{     "errorType": "SyntaxError",     "errorMessage": "Unexpected end of JSON input",     "stack": [         "SyntaxError: Unexpected end of JSON input",         "    at JSON.parse (<anonymous>)",         "    at IncomingMessage.<anonymous> (/var/task/queryActiveMenubyRestaurant.js:344:22)",         "    at IncomingMessage.emit (events.js:314:20)",         "    at IncomingMessage.EventEmitter.emit (domain.js:483:12)",         "    at IncomingMessage.Readable.read (_stream_readable.js:507:10)",         "    at flow (_stream_readable.js:1007:34)",         "    at resume_ (_stream_readable.js:988:3)",         "    at processTicksAndRejections (internal/process/task_queues.js:84:21)"     ] }
--
```

I set the limit value but its still clipped not sure whats going on. Any help will be appreciated

**Comment by yuth** [comment]
@waltermvp could you try running this query on AppSync console and see if you're getting the same error?

**Comment by kaustavghosh06** [comment]
Closing due to lack of response.
