### ISSUE TITLE
Go functions build not working with 4.44.0

### ISSUE THREAD

**Issue by sky4git** [aws-amplify/amplify-cli#6679]
**Describe the bug**
On Windows local Go function build is not working with amplify-cli version 4.44.0

**Amplify CLI Version**
4.44.0

**To Reproduce**
amplify build function GOGunctionName -y

**Expected behavior**
Function should build normally like it does in 4.42.0

**Screenshots**
Sorry cannot put the screenshot here.

**Desktop (please complete the following information):**

- OS: Windows
- Node Version. 14.15.4
- NPM version: 6.14.11

**Log output**
`$ amplify build function MyGoFunction -y
Error: Command failed with exit code 1: C:\Users\pcuser\Desktop\aws\testproject\bin\build-lambda-zip.exe -o C:\Users\pcuser\Desktop\aws\testproject\amplify\backend\function\MyGoFunction\dist\latest-build.zip C:\Users\pcuser\Desktop\aws\testproject\amplify\backend\function\MyGoFunction\bin\main
failed to compress file: open C:\Users\pcuser\Desktop\aws\testproject\amplify\backend\function\MyGoFunction\bin\main: The system cannot find the file specified.
    at makeError (C:\Users\pcuser\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\execa\lib\error.js:59:11)
    at handlePromise (C:\Users\pcuser\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\execa\index.js:114:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async winZip (C:\Users\pcuser\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-go-function-runtime-provider\lib\runtime.js:145:5)
    at async Object.packageResource (C:\Users\pcuser\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-go-function-runtime-provider\lib\runtime.js:133:9)
    at async packageFunction (C:\Users\pcuser\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-category-function\lib\provider-utils\awscloudformation\utils\packageFunction.js:43:27)
    at async Object.run (C:\Users\pcuser\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-category-function\lib\commands\function\build.js:22:13)
    at async Object.executeAmplifyCommand (C:\Users\pcuser\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-category-function\lib\index.js:211:5)
    at async executePluginModuleCommand (C:\Users\pcuser\AppData\Roaming\npm\node_modules\@aws-amplify\cli\lib\execution-manager.js:166:5)`

**Additional context**
Go function build is working with 4.42.0. I have not checked in 4.43.0.

**Comment by edwardfoyle** [comment]
This has been fixed in version 4.44.1 of the CLI. Please upgrade to the latest version.
