### ISSUE TITLE
Node.js requirement is not actual

### ISSUE THREAD

**Issue by AutomationD** [aws-amplify/amplify-cli#6717]
**Describe the bug**
When creating an environment on nodejs 10.11.0 there is a bug:
```
$ amplify env add staging
Note: It is recommended to run this command from the root of your app directory
? Do you want to use an existing environment? No
? Enter a name for the environment staging
Using default provider  awscloudformation
init failed
/Users/dmitry/.nvm/versions/node/v10.11.0/lib/node_modules/@aws-amplify/cli/node_modules/jose/lib/jwk/key/rsa.js:1
TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type Function. Received type undefined
    at promisify (internal/util.js:257:11)
    at Object.<anonymous> (/Users/dmitry/.nvm/versions/node/v10.11.0/lib/node_modules/@aws-amplify/cli/node_modules/jose/lib/jwk/key/rsa.js:13:25)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
```

When switching to node `v10.16.0` it works without any issues.

**Amplify CLI Version**
```
4.41.2
```

**To Reproduce**
```
nvm use 10.11.0
amplify create env foobar
```

**Expected behavior**
```
Using default provider  awscloudformation

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

? Do you want to use an AWS profile? (Y/n) (node:45013) ExperimentalWarning: The fs.promises API is experimental
...
...
```

**Comment by jhockett** [comment]
@AutomationD Node10 is going to reach end of life soon: https://nodejs.org/en/about/releases/

Is there a particular use case you're trying to solve by using Node 10.11.0?

**Comment by AutomationD** [comment]
Not really, just due to https://github.com/aws-amplify/amplify-cli/blame/master/Readme.md#L37, where it says It *should* work with any `10.x.x` node.
