### ISSUE TITLE
["Unable to upload trigger files to S3"] Amplify Access Denied S3 error when trying to push

### ISSUE THREAD

**Issue by MarvinButh** [aws-amplify/amplify-cli#6764]
Describe the bug

So I have had a bit of a frustrating experience with Amplify for one week now. My Code simply would not push since last wednesday for various reasons. The error I am getting now after trying a lot of fixes is an Access denied error for S3. Amplify apparently cannot upload trigger files to S3. I have triple checked, that the IAM User I am using for the push has all required permissions including administrator access to ALL S3 Buckets and administrator access to the Amplify app.
What I have done up to this point:

    Opened a new backend environment and push the code there
    Opened a completely new amplify app but in the same region and push the code there
    Opened a completely new amplify app in a different region and push the code there
    Make new IAM users with all required access and try pushing through them
    Delete all my DynamoDB tables because of the initial error I had first (Tried to change primary index of a GraphQL type)
    Try pulling first -> rewriting my code -> then pushing again

The most recent "Access Denied" seems to have appeared when I last created the new amplify app and tried pushing my code there but it has happened to me before as well.
I really don't know if this is reproducable but I will try my best to describe steps to reproduce.

Screenshots

![amplify error1](https://user-images.githubusercontent.com/48585905/109573217-e3f19e80-7aee-11eb-9479-cf8b54fff68a.png)

To Reproduce

    Create new Amplify app with default settings
    Create new IAM user with following permissions:
    -AmazonS3FullAccess
    -AmazonDynamoDBFullAccess
    -AdministratorAccess
    -amplify-APPNAME-dev-APPID-APINAME-1KXA1A3WVSG85-AuthRolePolicy01-1NMRO18LGL14N
    -AdministratorAccess-Amplify
    -AmazonS3OutpostsFullAccess
    -AWSCodeDeployRoleForCloudFormation
    -AWSCloudFormationFullAccess
    Write some backend code including schema.graphql and two lambda functions
    Run "amplify push"

Expected behavior

The code pushes and the backend builds successfully.

Log output

Amplify CLI:
`\ Updating resources in the cloud. This may take a few minutes...e AccessDenied: Access Denied
at Request.extractError (C:\snapshot\node_modules\aws-sdk\lib\services\s3.js:700:35)
at Request.callListeners (C:\snapshot\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
at Request.emit (C:\snapshot\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
at Request.emit (C:\snapshot\node_modules\aws-sdk\lib\request.js:688:14)
at Request.transition (C:\snapshot\node_modules\aws-sdk\lib\request.js:22:10)
at AcceptorStateMachine.runTo (C:\snapshot\node_modules\aws-sdk\lib\state_machine.js:14:12)
at C:\snapshot\node_modules\aws-sdk\lib\state_machine.js:26:10
at Request. (C:\snapshot\node_modules\aws-sdk\lib\request.js:38:9)
at Request. (C:\snapshot\node_modules\aws-sdk\lib\request.js:690:12)
at Request.callListeners (C:\snapshot\node_modules\aws-sdk\lib\sequential_executor.js:116:18) {
code: 'AccessDenied',
region: null,
time: 2021-03-01T18:29:58.746Z,
requestId: '{REQUEST_ID}',
extendedRequestId: '{EXTENDED_REQUEST_ID}',
cfId: undefined,
statusCode: 403,
retryable: false,
retryDelay: 25.349775538283083
}
× Error has occurred during file upload.
AccessDenied: Access Denied
at Request.extractError (C:\snapshot\node_modules\aws-sdk\lib\services\s3.js:700:35)
at Request.callListeners (C:\snapshot\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
at Request.emit (C:\snapshot\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
at Request.emit (C:\snapshot\node_modules\aws-sdk\lib\request.js:688:14)
at Request.transition (C:\snapshot\node_modules\aws-sdk\lib\request.js:22:10)
at AcceptorStateMachine.runTo (C:\snapshot\node_modules\aws-sdk\lib\state_machine.js:14:12)
at C:\snapshot\node_modules\aws-sdk\lib\state_machine.js:26:10
at Request. (C:\snapshot\node_modules\aws-sdk\lib\request.js:38:9)
at Request. (C:\snapshot\node_modules\aws-sdk\lib\request.js:690:12)
at Request.callListeners (C:\snapshot\node_modules\aws-sdk\lib\sequential_executor.js:116:18)
× An error occurred when pushing the resources to the cloud

Unable to upload trigger files to S3
An error occurred during the push operation: Unable to upload trigger files to S3`

Build Log from amplify console:
[log.txt](https://github.com/aws-amplify/amplify-cli/files/6064031/log.txt)

Desktop (please complete the following information):

    OS: Windows_NT x64 10.0.18363
    Visual Studio Code Extension Host Version: 1.53.2
    AWS Toolkit Version: 1.20.0
    Amplify CLI version: 4.44.1

Additional context

I noticed, that "region" in the S3 response is null but I don't know if that's relevant or not.
I am actually getting frustrated. My deadline for this project was sunday and I can't upload it please help me!

**Comment by MarvinButh** [comment]
I also noticed this error in my Amplify console build log right before it initiated rollback:
`2021-03-01T17:24:50.125Z [INFO]: UPDATE_ROLLBACK_IN_PROGRESS amplify-{APPNAME}frontend-dev-{APPID} AWS::CloudFormation::Stack Mon Mar 01 2021 17:24:47 GMT+0000 (Coordinated Universal Time) The following resource(s) failed to update: [functioncreatePostAndTimeline].
                                 UPDATE_FAILED               functioncreatePostAndTimeline      AWS::CloudFormation::Stack Mon Mar 01 2021 17:24:46 GMT+0000 (Coordinated Universal Time) Value of property Parameters must be an object with String (or simple type) properties`

I had an AWSURL in the schema for this function before, but have replaced it with a standart String. I don't know why it keeps throwing this error

**Comment by MarvinButh** [comment]
I resolved this issue by nuking the whole AWS account and starting completely over. Gonna close this for now.
