### ISSUE TITLE
Build Failed when deploying amplify tutorial notes app with s3 storage

### ISSUE THREAD

**Issue by anettleship** [aws-amplify/amplify-cli#6778]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.15.5

### Amplify CLI Version

v4.44.2

### What operating system are you using?

Windows

### Amplify Categories

auth, storage

### Amplify Commands

Not applicable

### Describe the bug

I've followed the aws amplify notes app tutorial:
https://aws.amazon.com/getting-started/hands-on/build-react-app-amplify-graphql/module-five/?e=gs2020&p=build-a-react-app-four

and reached the last module where we add storage:
https://github.com/anettleship/amplifyapp/tree/master

The app functions correctly locally with npm start and successfully stores uploaded files in the configured s3 bucket.

When I push my code to the repository to initiate deployment, the build fails with the message:

Error: File at path: '/codebuild/output/src874258426/src/amplifyapp/amplify/backend/storage/imagestorage/parameters.json' does not exist

### Expected behavior

I expect the build to complete and for my code to deploy successfully.

### Reproduction steps

Add storage to project: amplify add storage
? Please select from one of the below mentioned services: Content (Images, audio, video, etc.)
? Please provide a friendly name for your resource that will be used to label this category in the project: 
imagestorage
? Please provide bucket name: amplifyapp2f7aee3344b2455ab02243bff9972adc
ers? create/update, read, delete
? Do you want to add a Lambda Trigger for your S3 Bucket? No
Successfully added resource imagestorage locally  

amplify push --y

√ All resources are updated in the cloud

Push modified tutorial code referencing 'imagestorage'. 

Check progress of Frontend Environment build in amplify console, deployment fails at build phase.

### Log output

```
# Put your logs below this line

Build log:

2021-03-02T23:19:45.050Z [INFO]: Git SSH Key acquired
2021-03-02T23:19:45.120Z [INFO]: # Cloning repository: git@github.com:anettleship/amplifyapp.git
2021-03-02T23:19:45.191Z [INFO]: Agent pid 135
2021-03-02T23:19:45.218Z [INFO]: Identity added: /root/.ssh/git_rsa (/root/.ssh/git_rsa)
2021-03-02T23:19:45.432Z [INFO]: Cloning into 'amplifyapp'...
2021-03-02T23:19:45.866Z [INFO]: Warning: Permanently added the RSA host key for IP address '140.82.121.3' to the list of known hosts.
2021-03-02T23:19:47.005Z [INFO]: # Switching to commit: 9608c48b850cc22f1cdbd0d7d046aba2d8d4dbf1
2021-03-02T23:19:47.012Z [INFO]: Agent pid 148
2021-03-02T23:19:47.015Z [INFO]: Identity added: /root/.ssh/git_rsa (/root/.ssh/git_rsa)
2021-03-02T23:19:47.020Z [INFO]: Note: switching to '9608c48b850cc22f1cdbd0d7d046aba2d8d4dbf1'.
                                 You are in 'detached HEAD' state. You can look around, make experimental
                                 changes and commit them, and you can discard any commits you make in this
                                 state without impacting any branches by switching back to a branch.
                                 If you want to create a new branch to retain commits you create, you may
                                 do so (now or later) by using -c with the switch command. Example:
                                 git switch -c <new-branch-name>
                                 Or undo this operation with:
                                 git switch -
                                 Turn off this advice by setting config variable advice.detachedHead to false
2021-03-02T23:19:47.020Z [INFO]: HEAD is now at 9608c48 check for changes
2021-03-02T23:19:47.025Z [INFO]: Successfully cleaned up Git credentials
2021-03-02T23:19:47.026Z [INFO]: # Checking for Git submodules at: /codebuild/output/src874258426/src/amplifyapp/.gitmodules
2021-03-02T23:19:47.046Z [INFO]: # Retrieving cache...
2021-03-02T23:19:51.227Z [INFO]: # Extracting cache...
2021-03-02T23:19:56.503Z [INFO]: # Extraction completed
2021-03-02T23:19:56.645Z [INFO]: # Retrieving environment cache...
2021-03-02T23:19:56.692Z [INFO]: # Retrieved environment cache
2021-03-02T23:19:56.693Z [INFO]: # Ensuring NPM package '@aws-amplify/cli' is version: 'latest'
2021-03-02T23:20:02.610Z [INFO]: # Patching NPM package '@aws-amplify/cli' from 4.29.4 to 4.44.2...
2021-03-02T23:20:51.012Z [INFO]: # Done patching NPM package '@aws-amplify/cli'
2021-03-02T23:20:56.661Z [INFO]: ## Starting Backend Build
                                 # Starting phase: build
                                 # Executing command: amplifyPush --simple
2021-03-02T23:21:05.514Z [INFO]: [0mAmplify AppID found: dstbtn3abtrm6. Amplify App name is: amplifyapp[0m
2021-03-02T23:21:05.601Z [INFO]: [0mBackend environment staging found in Amplify Console app: amplifyapp[0m
2021-03-02T23:21:06.258Z [WARNING]: - Fetching updates to backend environment: staging from the cloud.
2021-03-02T23:21:06.537Z [WARNING]: ✔ Successfully pulled backend environment staging from the cloud.
2021-03-02T23:21:06.573Z [INFO]: 
2021-03-02T23:21:08.539Z [INFO]: [33mNote: It is recommended to run this command from the root of your app directory[39m
2021-03-02T23:21:13.355Z [WARNING]: - Initializing your environment: staging
2021-03-02T23:21:13.787Z [WARNING]: ✔ Initialized provider successfully.
2021-03-02T23:21:13.902Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
2021-03-02T23:21:13.903Z [WARNING]: ✖ There was an error initializing your environment.
2021-03-02T23:21:13.905Z [INFO]: [31minit failed[39m
2021-03-02T23:21:13.906Z [INFO]: [0mError: File at path: '/codebuild/output/src874258426/src/amplifyapp/amplify/backend/storage/imagestorage/parameters.json' does not exist[0m
                                 [0m    at Function.JSONUtilities.readJson (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/jsonUtilities.ts:25:15)[0m
                                 [0m    at AmplifyToolkit.readJsonFile [as _readJsonFile] (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/read-json-file.ts:5:24)[0m
                                 [0m    at getBucketName (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/transform-graphql-schema.ts:570:44)[0m
                                 [0m    at Object.transformGraphQLSchema (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/transform-graphql-schema.ts:432:38)[0m
                                 [0m    at processTicksAndRejections (internal/process/task_queues.js:97:5)[0m
                                 [0m    at Object.run (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/push-resources.ts:108:5)[0m
2021-03-02T23:21:13.924Z [ERROR]: !!! Build failed
2021-03-02T23:21:13.924Z [ERROR]: !!! Non-Zero Exit Code detected
2021-03-02T23:21:13.924Z [INFO]: # Starting environment caching...
2021-03-02T23:21:13.925Z [INFO]: # Environment caching completed
Terminating logging...

**Comment by anettleship** [comment]
And there it is...

Amplify creates local files to provision the cloud storage it has set up in the 'amplify' folder, as well as setting things up in AWS.

If you forget to add these to your git commit before you push, the required files will not be present for Amplify to build.
