### ISSUE TITLE
init failed

### ISSUE THREAD

**Issue by Miamoto-Musashi** [aws-amplify/amplify-cli#6827]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm i -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v8.11.2

### Amplify CLI Version

4.45.0

### What operating system are you using?

MacOs BigSur 11.2.2 (20D80)

### Amplify Categories

Not applicable

### Amplify Commands

init

### Describe the bug

```bash
▶ amplify init
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the project xxx
? Enter a name for the environment dev
? Choose your default editor: Visual Studio Code
? Choose the type of app that you're building flutter
Please tell us about your project
? Where do you want to store your configuration file? ./lib/
Using default provider  awscloudformation
/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/extract-zip/index.js:1
TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
    at promisify (internal/util.js:209:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/extract-zip/index.js:11:18)
    at Object.Module._extensions..js (module.js:663:10)
    at Object.Module._extensions..js (module.js:663:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/attach-backend.js:5:17)
    at Object.Module._extensions..js (module.js:663:10)
    at Object.Module._extensions..js (module.js:663:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/index.js:4:29)
    at Object.Module._extensions..js (module.js:663:10)
    at Object.Module._extensions..js (module.js:663:10)
    at providers.forEach.provider (/usr/local/lib/node_modules/@aws-amplify/cli/lib/init-steps/s2-initProviders.js:36:32)
    at Array.forEach (<anonymous>)
    at initProviders (/usr/local/lib/node_modules/@aws-amplify/cli/lib/init-steps/s2-initProviders.js:35:15)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

### Expected behavior

no error

### Reproduction steps

1. amplify init
1. Enter a name for the project xxx
1. Enter a name for the environment dev
1. Choose your default editor: Visual Studio Code
1. Choose the type of app that you're building flutter

Please tell us about your project
1. Where do you want to store your configuration file? ./lib/

### Log output

```
# Put your logs below this line
 cat ~/.amplify/logs/amplify-cli-2021-03-08.log
2021-03-08T13:34:37.748Z|info : amplify init core
2021-03-08T13:37:30.713Z|info : amplify init core
2021-03-08T13:45:15.442Z|info : amplify version core

```

just updated npm to 6.14.8

**Comment by siegerts** [comment]
Hi @Miamoto-Musashi - thanks for reaching out.  Have you tried with a newer version of Node.js? 

The CLI pre-requisites are listed here - https://docs.amplify.aws/cli/start/install#pre-requisites-for-installation.

**Comment by attilah** [comment]
@Miamoto-Musashi Amplify CLI supports only NodeJS LTS versions as minimum, which is as of Today 10.x, but end of April 10.x gets out of LTS, to 14.x will be the version, but 12.x is also expected to function correctly. Update your NodeJS version and retry the `amplify init`.

**Comment by Miamoto-Musashi** [comment]
thanks after upgrading node with `brew upgrade node` the issue is solved

**Comment by Miamoto-Musashi** [comment]
solved
