### ISSUE TITLE
impossible to spot syntax errors

### ISSUE THREAD

**Issue by Miamoto-Musashi** [aws-amplify/amplify-cli#6850]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify CLI Version

4.45.0

### What operating system are you using?

Mac

### Amplify Categories

api

### Amplify Commands

codegen

### Describe the bug

I launch `amplify codegen models` and it complains about an error, the schema file is big, and is impossible to understand where the error is.

```bash
amplify codegen models
Syntax Error: Expected Name, found @
GraphQLError: Syntax Error: Expected Name, found @
    at syntaxError (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/error/syntaxError.js:15:10)
    at Parser.expectToken (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/language/parser.js:1404:40)
    at Parser.parseName (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/language/parser.js:94:22)
    at Parser.parseFieldDefinition (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/language/parser.js:857:21)
    at Parser.optionalMany (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/language/parser.js:1497:28)
    at Parser.parseFieldsDefinition (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/language/parser.js:846:17)
    at Parser.parseObjectTypeDefinition (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/language/parser.js:798:23)
    at Parser.parseTypeSystemDefinition (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/language/parser.js:696:23)
    at Parser.parseDefinition (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/language/parser.js:146:23)
    at Parser.many (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/language/parser.js:1518:26)
    at Parser.parseDocument (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/language/parser.js:111:25)
    at Object.parse (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/language/parser.js:36:17)
    at collectDirectivesByType (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/collectDirectives.ts:65:15)
    at Object.collectDirectivesByTypeNames (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/collectDirectives.ts:51:15)
    at transformGraphQLSchema (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/transform-graphql-schema.ts:460:24)
    at validateSchema (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/commands/models.js:92:3)
    at Object.generateModels (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/commands/models.js:38:3)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/commands/codegen/models.js:9:7)
    at Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/amplify-plugin-index.js:9:3)
    at executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:175:3)
    at Object.executeCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:28:5)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/src/index.ts:132:5)
```

### Expected behavior

the parser says the line where the error occurred

### Reproduction steps

launch command
see error

### Log output

```
# Put your logs below this line
2021-03-10T03:59:20.409Z|info : amplify models codegen  
2021-03-10T04:08:28.655Z|info : amplify models codegen  
2021-03-10T04:09:48.310Z|info : amplify models codegen  
2021-03-10T04:20:05.755Z|info : amplify models codegen  
2021-03-10T04:53:34.413Z|info : amplify models codegen  
2021-03-10T05:07:01.179Z|info : amplify models codegen  
2021-03-10T08:59:23.634Z|info : amplify models codegen  
2021-03-10T09:11:07.447Z|info : amplify models codegen  
2021-03-10T09:13:02.698Z|info : amplify models codegen  
2021-03-10T09:17:21.718Z|info : amplify models codegen  {"help":true,"yes":false}
2021-03-10T10:01:34.470Z|info : amplify models codegen  
2021-03-10T10:12:27.719Z|info : amplify models codegen  
2021-03-10T10:23:43.831Z|info : amplify models codegen  
2021-03-10T10:46:59.107Z|info : amplify models codegen  
2021-03-10T11:03:46.822Z|info : amplify version core 
```

schema file
```
type Organization @model {
  key: ID!
  id: ID!
  name: String
  imageUrl: String
  addresses: [Address] @connection(keyName: "byOrganization", fields: ["key"])
  wallet: Wallet @connection(keyName: "byOrganization", fields: ["key"])
  country: Country @connection(keyName: "byOrganization", fields: ["key"])
  phone: String
  MC: String
  DOT: String
  DUNS: String
  EIN: String
  dispatcher: User @connection(keyName: "byOrganization", fields: ["key"])
  entityType: String
  receivable: User @connection(keyName: "byOrganization", fields: ["key"])
  totalTrucks: Int
  trailers: [Trailer] @connection(keyName: "byOrganization", fields: ["key"])
  afterHrsPhone: String
  isDraft: Boolean
  isDetailed: Boolean
  isDocumented: Boolean
  isProfiled: Boolean
  isAccounted: Boolean
  isSigned: Boolean
  isActive: Boolean
}

type Address @model {
  @key(name: "byOrganization", fields: ["organizationID", "type"]) {
    id: ID!
    organizationID: ID!
  }
  addressNumber: String
  countryIso3Code: String
  geometry: Geometry @connection(name: "geometry")
  label: String
  municipality: String
  neighborhood: String
  postalCode: String
  region: String
  street: String
  subRegion: String
  isLegal: Boolean
  alias: String
  streetNumber: String
  formattedAddress: String
}

type Geometry @model {
  point: [Float]
}

type Wallet @model {
  key: ID!
  id: ID!
  name: String!
  currency: String
  balance: Float
  chargePayments: String
  orderIds: String
  status: String
}

type Country @model {
  key: ID!
  id: ID!
  name: String
  isoCode: String
  iso3Code: String
  phoneCode: Int
  code: String
  unitType: String
  lengthUnit: String
  weightUnit: String
  volumeUnit: String
  moneyUnit: String
  languageCode: String
  truckMaxWeight: Float
  trailMaxLength: Float

}

type User @model {
  key: ID!
  id: ID!
  firstName: String
  lastName: String
  username: String
  password: String
  issuer: String
  employerKey: String
  # always with country code
  phone: String
  email: String
  country: Country @connection(name: "country")
  cancelled: Boolean
  accessToken: String
  idToken: String
  refreshToken: String
  isEmailValid: Boolean
  isPhoneValid: Boolean
  isInvited: Boolean
  isEmployee: Boolean
}

type Trailer @model {
  @key(name: "byOrganization", fields: ["organizationID", "type"]) {
    id: ID!
    organizationID: ID!
    type: String!
  }
  key: ID!
  id: ID!
  dimension: TrailerDimension @connection(name: "dimensions")
  type: TrailerType @connection(name: "type")
}

enum TrailerDimension {
  ft24
  ft28
  ft48
  ft53
}

enum TrailerType {
  refrigerated
  dryVan
  flatbed
  stepdeck
  boxTruck
  powerOnly
}
```

**Comment by cjihrig** [comment]
This doesn't fix the reported issue, but running gql-compile does appear to provide more useful error information, which might help unblock you for now:

```
$ amplify api gql-compile
Syntax Error: Expected Name, found @

GraphQL request:30:3
29 | type Address @model {
30 |   @key(name: "byOrganization", fields: ["organizationID", "type"]) {
   |   ^
31 |     id: ID!
```

**Comment by attilah** [comment]
@Miamoto-Musashi yeah it seems that the root cause is the extra `{` after `type Address`.

This is a codegen issue and an enhancement to error reporting, we're transferring it to their repository.
