### ISSUE TITLE
Cannot destructure property 'timeout' of 'undefined' as it is undefined.

### ISSUE THREAD

**Issue by volkanunsal** [aws-amplify/amplify-cli#6875]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

4.44.0

### What operating system are you using?

mac

### Amplify Categories

function

### Amplify Commands

Not applicable

### Describe the bug

**Describe the bug**

 I'm trying to start the local development server. I followed the instructions in the manual and ran:

```
amplify mock
amplify mock function
```

This is the error I'm getting:

```
➜  showcase (ruby-2.5.5) git:(master) amplify mock function
? Provide the path to the event JSON object relative to /Users/newuser/x/rcv/showcase/amplify/backend/function/rcvce175542 src/event.json
Ensuring latest function changes are built...
Starting execution...
rcvce175542 failed with the following error:
TypeError: Cannot destructure property 'timeout' of 'undefined' as it is undefined.
    at getCancellableTimer (/Users/newuser/.volta/tools/image/packages/@aws-amplify/cli/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/src/func/index.ts:73:32)
    at Object.timeConstrainedInvoker (/Users/newuser/.volta/tools/image/packages/@aws-amplify/cli/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/src/func/index.ts:65:29)
    at Object.start (/Users/newuser/.volta/tools/image/packages/@aws-amplify/cli/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/src/func/index.ts:48:26)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at Object.run (/Users/newuser/.volta/tools/image/packages/@aws-amplify/cli/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/src/commands/mock/function.ts:14:5)
    at Object.executeAmplifyCommand (/Users/newuser/.volta/tools/image/packages/@aws-amplify/cli/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/src/amplify-plugin-index.ts:8:3)
    at executePluginModuleCommand (/Users/newuser/.volta/tools/image/packages/@aws-amplify/cli/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:181:3)
    at Object.executeCommand (/Users/newuser/.volta/tools/image/packages/@aws-amplify/cli/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:28:5)
    at Object.run (/Users/newuser/.volta/tools/image/packages/@aws-amplify/cli/lib/node_modules/@aws-amplify/cli/src/index.ts:105:5)
```

It looks like context.input.options is undefined in this line:

const result = await exports.timeConstrainedInvoker(invoker({ event }), context.input.options);
...around here:

 Object.timeConstrainedInvoker (/Users/newuser/.volta/tools/image/packages/@aws-amplify/cli/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/src/func/index.ts:65:29)
I worked around it by adding a fallback option , i.e.{ timeout: 10 }.

### Expected behavior

See the description above.

### Reproduction steps

See the description above.

### Log output

```
# Put your logs below this line

```

**Comment by cjihrig** [comment]
This appears to be a duplicate of https://github.com/aws-amplify/amplify-cli/issues/6653, which has been fixed and released. Can you try updating your version of the CLI.

**Comment by volkanunsal** [comment]
I'm using 4.44.0. Is it not the latest version?

**Comment by volkanunsal** [comment]
Ah, I see it's 4.45.2. Le me give it a try..

**Comment by volkanunsal** [comment]
Works. Thank you.
