### ISSUE TITLE
"amplify function push" times out with "Inaccessible host" error

### ISSUE THREAD

**Issue by tomhirschfeld** [aws-amplify/amplify-cli#6930]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

10

### Amplify CLI Version

4.45.2

### What operating system are you using?

mac

### Amplify Categories

function

### Amplify Commands

push

### Describe the bug

amplify push times out with error logged below

### Expected behavior

no error, push succeeds

### Reproduction steps

`amplify function push`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line

Inaccessible host: `amplify-wesponsored-web-hdev-170732-deployment.s3.us-east-2.amazonaws.com'. This service may not be available in the `us-east-2' region.
UnknownEndpoint: Inaccessible host: `amplify-wesponsored-web-hdev-170732-deployment.s3.us-east-2.amazonaws.com'. This service may not be available in the `us-east-2' region.
    at Request.ENOTFOUND_ERROR (/Users/tomhirschfeld/.nvm/versions/node/v13.12.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/event_listeners.js:507:46)
    at Request.callListeners (/Users/tomhirschfeld/.nvm/versions/node/v13.12.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/tomhirschfeld/.nvm/versions/node/v13.12.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/tomhirschfeld/.nvm/versions/node/v13.12.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:688:14)
    at ClientRequest.error (/Users/tomhirschfeld/.nvm/versions/node/v13.12.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/event_listeners.js:339:22)
    at ClientRequest.<anonymous> (/Users/tomhirschfeld/.nvm/versions/node/v13.12.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/http/node.js:96:19)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.EventEmitter.emit (domain.js:485:12)
    at TLSSocket.socketErrorListener (_http_client.js:432:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:485:12)
    at errorOrDestroy (internal/streams/destroy.js:128:12)
    at onwriteError (_stream_writable.js:406:3)
    at onwrite (_stream_writable.js:427:7)
    at internal/streams/destroy.js:60:7
    at TLSSocket.Socket._destroy (net.js:679:5)
    at TLSSocket.destroy (internal/streams/destroy.js:55:8)
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:93:12)
An error occurred when pushing the function resource


```

</details>

**Comment by kaustavghosh06** [comment]
@tomhirschfeld This seems like a network issue. I've seen this happen when I'm behind a proxy disallowing access to certain endpoints.

**Comment by tomhirschfeld** [comment]
@kaustavghosh06  
I'm not on a proxy to be clear

**Comment by kaustavghosh06** [comment]
@tomhirschfeld Few questions
1) Are you able to continuously repro this or is this intermittent? 
2) Can you try running `amplify push` instead of `amplify function push` as a workaround?

From this issue out here - https://github.com/aws/aws-sdk-js/issues/2618 looks like it's an intermittent S3 DNS issue.

**Comment by kaustavghosh06** [comment]
@tomhirschfeld Were you able to get past this issue?

**Comment by tomhirschfeld** [comment]
yea, it would be nice to have a better error message when this happens,
maybe a bullet point list of like:

"things to check to resolve this error:

1) confirm you have no proxy between you and amazon
2) confirm no internet connectivity issues in your network
3) check for outages on aws
4) this might be a transient issue related to aws internal networks, try
again in an hour
"
