### ISSUE TITLE
Trouble adding aurora mysql graphql datasource

### ISSUE THREAD

**Issue by georgeleeventures** [aws-amplify/amplify-cli#6989]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Describe the bug

When trying to add mysql graphql datasource (https://docs.amplify.aws/cli/graphql-transformer/relational), a non-descript error is being given to me (redaction = XXXXXXXXXX)

```
george:~/environment/(dev) $ amplify api add-graphql-datasource
Using datasource: Aurora Serverless, provided by: awscloudformation
? Provide the region in which your cluster is located: us-east-1
? Select the Aurora Serverless cluster that will be used as the data source for your AP
I: XXXXXXXXXX
✔ Fetched Aurora Serverless cluster.
? Select the database to use as the datasource: XXXXXXXXXX
Error: ENOENT: no such file or directory, open '/home/ec2-user/environment/XXXXXXXXXX/amplify/backend/api/XXXXXXXXXX/resolvers/Mutation.XXXXXXXXXX.req.vtl'
    at Object.openSync (fs.js:443:3)
    at Object.writeFileSync (fs.js:1194:35)
    at RelationalDBResolverGenerator.makeCreateRelationalResolver (/home/ec2-user/.nvm/versions/node/v10.23.2/lib/node_modules/@aws-amplify/cli/node_modules/graphql-relational-schema-transformer/src/RelationalDBResolverGenerator.ts:109:8)
    at typePrimaryKeyMap.forEach (/home/ec2-user/.nvm/versions/node/v10.23.2/lib/node_modules/@aws-amplify/cli/node_modules/graphql-relational-schema-transformer/src/RelationalDBResolverGenerator.ts:51:54)
    at Map.forEach (<anonymous>)
    at RelationalDBResolverGenerator.createRelationalResolvers (/home/ec2-user/.nvm/versions/node/v10.23.2/lib/node_modules/@aws-amplify/cli/node_modules/graphql-relational-schema-transformer/src/RelationalDBResolverGenerator.ts:47:28)
    at RelationalDBTemplateGenerator.addRelationalResolvers (/home/ec2-user/.nvm/versions/node/v10.23.2/lib/node_modules/@aws-amplify/cli/node_modules/graphql-relational-schema-transformer/src/RelationalDBTemplateGenerator.ts:52:72)
    at datasourceSelectionPrompt.then.then.then.graphqlSchemaContext (/home/ec2-user/.nvm/versions/node/v10.23.2/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/src/commands/api/add-graphql-datasource.js:146:38)
    at process._tickCallback (internal/process/next_tick.js:68:7)
There was an error adding the datasource
```

### Expected behavior

Expected that adding the aurora mysql graphql datasource would succeed as demonstrated here: https://docs.amplify.aws/cli/graphql-transformer/relational

### Reproduction steps

1. Follow directions and add mysql aurora datasource
2. run from the project directory: amplify api add-graphql-datasource
3. follow the prompts to select region, cluster, and database name

### Build Settings

```yaml
_No response_
```

Could this issue be a result of a naming conflict? I have 2 tables with the same name in mysql and dynamodb, so could it be a naming conflict? Another issue I noticed is: I do not have a resolvers folder in my api/XXXXXXXXXX directory -- when is this to be created?
I have the latest amplify CLI as well. 

Error: ENOENT: no such file or directory, open '/home/ec2-user/environment/XXXXXXXXXX/amplify/backend/api/XXXXXXXXXX/resolvers/Mutation.XXXXXXXXXX.req.vtl'

**Comment by georgeleeventures** [comment]
1) amplify version
4.46.1
2) Yes -- I have checked and some users have experienced similar issues after the select database step, but nothing specific to the error message I am getting. Is the resolvers folder supposed to be created after the step:
 ? Select the database to use as the datasource: XXXXXXXXXX
Or is the resolvers folder already supposed to be there?

**Comment by georgeleeventures** [comment]
@edwardfoyle No I did not do anything that caused it to be removed. Adding the resolvers folder did solve the issue but I still encountered the following error -- I think this is caused by me having type Query in my lambda function resolvers AND another type Query being added to rds.graphql schema. What should be the resolution? Is there some merging method that will resolve this?

Successfully added the Aurora Serverless datasource locally

Some next steps:
"amplify push" will build all your local backend resources and provision it in the cloud
"amplify publish" will build all your local backend and frontend resources (if you have hosting category added) and provision it in the cloud

2021-03-30T22:22:42.302Z - error: uncaughtException: There can be only one type named "Query". date=Tue Mar 30 2021 22:22:42 GMT+0000 (Coordinated Universal Time), pid=18670, uid=1000, gid=1000, cwd=/home/ec2-user/environment/XXXXXXXX, execPath=/home/ec2-user/.nvm/versions/node/v10.23.2/bin/node, version=v10.23.2, argv=[/home/ec2-user/.nvm/versions/node/v10.23.2/bin/node, /home/ec2-user/.nvm/versions/node/v10.23.2/bin/amplify, api, add-graphql-datasource], rss=892944384, heapTotal=430809088, heapUsed=386495688, external=367978785, loadavg=[1.28173828125, 0.30517578125, 0.1015625], uptime=20412, trace=[column=11, file=/home/ec2-user/.nvm/versions/node/v10.23.2/lib/node_modules/@aws-amplify/cli/node_modules/graphql/validation/validate.js, function=assertValidSDL, line=108, method=null, native=false, column=34, file=/home/ec2-user/.nvm/versions/node/v10.23.2/lib/node_modules/@aws-amplify/cli/node_modules/graphql/utilities/buildASTSchema.js, function=Object.buildASTSchema, line=71, method=buildASTSchema, native=false, column=18, file=/home/ec2-user/.nvm/versions/node/v10.23.2/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/validation.ts, function=Object.validateModelSchema, line=142, method=validateModelSchema, native=false, column=20, file=/home/ec2-user/.nvm/versions/node/v10.23.2/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/GraphQLTransform.ts, function=GraphQLTransform.transform, line=244, method=transform, native=false, column=35, file=/home/ec2-user/.nvm/versions/node/v10.23.2/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/util/amplifyUtils.ts, function=_buildProject, line=91, method=null, native=false, column=7, file=internal/process/next_tick.js, function=process._tickCallback, line=68, method=_tickCallback, native=false], stack=[Error: There can be only one type named "Query".,     at assertValidSDL (/home/ec2-user/.nvm/versions/node/v10.23.2/lib/node_modules/@aws-amplify/cli/node_modules/graphql/validation/validate.js:108:11),     at Object.buildASTSchema (/home/ec2-user/.nvm/versions/node/v10.23.2/lib/node_modules/@aws-amplify/cli/node_modules/graphql/utilities/buildASTSchema.js:71:34),     at Object.validateModelSchema (/home/ec2-user/.nvm/versions/node/v10.23.2/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/validation.ts:142:18),     at GraphQLTransform.transform (/home/ec2-user/.nvm/versions/node/v10.23.2/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/GraphQLTransform.ts:244:20),     at _buildProject (/home/ec2-user/.nvm/versions/node/v10.23.2/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/util/amplifyUtils.ts:91:35),     at process._tickCallback (internal/process/next_tick.js:68:7)]

**Comment by georgeleeventures** [comment]
Hello -- Is there any update here? If i use lambda resolvers, it is through type Query (), but the graphql datasource creates another type Query(). This will fail compilation. What is the recommended path here?

**Comment by kaustavghosh06** [comment]
@georgeleeventures Did you run the following commands before running the` amplify api add-graphql-datasource` command?
amplify init
amplify add api // with a simple type

**Comment by georgeleeventures** [comment]
@kaustavghosh06 Yes i have already have an existing graphql api that was added through amplify add api. I followed the guide https://docs.amplify.aws/cli/graphql-transformer/function which details adding lambda resolvers:
If you deployed your function using the ‘amplify function’ category

The Amplify CLI provides support for maintaining multiple environments out of the box. When you deploy a function via amplify add function, it will automatically add the environment suffix to your Lambda function name. For example if you create a function named echofunction using amplify add function in the dev environment, the deployed function will be named echofunction-dev. The @function directive allows you to use ${env} to reference the current Amplify CLI environment.

type Query {
  echo(msg: String): String @function(name: "echofunction-${env}")
}

But then one of the other issues is that when I ran amplify add graphql-datasource command, it creates another type Query {} which would conflict with the one from lambda functions

**Comment by kaustavghosh06** [comment]
@georgeleeventures Got it. 
I would recommend moving  `echo(msg: String): String @function(name: "echofunction-${env}")`  to the Query block created after importing the RDS datasource. We don't handle the merging of different query types at this moment within the schema.
