### ISSUE TITLE
amplify init fails for angular projects working inside a container

### ISSUE THREAD

**Issue by Karmavil** [aws-amplify/amplify-cli#7057]
### Before opening, please confirm:

I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Describe the bug

```console
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the project frontend
The following configuration will be applied:

Project information
| Name: frontend
| Environment: dev
| Default editor: Visual Studio Code
| App type: javascript
TypeError: Cannot read property 'projectPath' of undefined
    at getAngularConfig (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-javascript/lib/framework-config-mapping.js:57:52)
    at getProjectConfiguration (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-javascript/lib/framework-config-mapping.js:85:14)
    at Object.displayFrontendDefaults (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-javascript/lib/configuration-manager.js:173:32)
    at Object.displayFrontendDefaults (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-javascript/index.js:40:24)
    at displayAndSetDefaults (/usr/local/lib/node_modules/@aws-amplify/cli/lib/init-steps/s0-analyzeProject.js:83:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async analyzeProject (/usr/local/lib/node_modules/@aws-amplify/cli/lib/init-steps/s0-analyzeProject.js:99:9)
    at async Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/lib/commands/init.js:29:13)
    at async Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/lib/index.js:236:9)
    at async executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:164:5)
    at async Object.executeCommand (/usr/local/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:35:9)
    at async Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/lib/index.js:112:9)
```

### Expected behavior

```console
Project information
| Name: chorrimanguera
| Environment: dev
| Default editor: Visual Studio Code
| App type: javascript
| Javascript framework: none
| Source Directory Path: src
| Distribution Directory Path: dist
| Build Command: npm run-script build

? Initialize the project with the above configuration? No
? Enter a name for the environment (dev) 
```

### Reproduction steps

I have no idea.. let's see
1) Launch a container: node14.16-buster
2) Install globally npm packages: angular/cli 11.2.3 and aws-amplify/cli (4.47.1)
3) Start a new angular app.
4) Run amplify configure an set the credentials
5) In the app directory run amplify init

### Additional information

* I tried creating new IAM users but it does not help.
* The IAM user has admin rights but also the git user has full access to codecommit.

**Comment by Karmavil** [comment]
Noup I didn't get there yet.
Thank you very much @siegerts

**Comment by Karmavil** [comment]
I'm sorry for the bad news but it does not work. I get the same error 🤦🏽

**Comment by Karmavil** [comment]
All right this is weird.. it works when I run `amplify init` from the **JavaScript Debug Terminal**

**Comment by Karmavil** [comment]
In case you want to know I was using bash terminal not zsh, nor sh

**Comment by Lard4** [comment]
I'm facing the same issue right now.

**Comment by Karmavil** [comment]
All right I will reopen it, thank for the feedback (I'm not alone) It has something to do with the context.. I don't want to touch the code because it's huge and like every function make use of it but it is defined in specific steps.. It's a nightmare thank you angular this is definitely your kind of beauty

**Comment by Karmavil** [comment]
all right I got it.

> **amplify env add**

```console
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the project src
? Enter a name for the environment dev
? Choose your default editor: Visual Studio Code
? Choose the type of app that you're building javascript
Please tell us about your project
? What javascript framework are you using angular
? Source Directory Path:  src
? Distribution Directory Path: dist/src
? Build Command:  npm run-script build
? Start Command: ng serve
Using default provider  awscloudformation
```

@kaustavghosh06 
I'm closing the issue when you confirm .. or @Lard4
I'm currently using yarn for everything but I'm done for today, it's just too much. 
(I refuse to reinstall more packages for today)

**Comment by Karmavil** [comment]
ups... well that's what I'm talking about.. now it's closed
