### ISSUE TITLE
amplify init , amplify configure - Error: Cannot find module 'jsonschema'

### ISSUE THREAD

**Issue by vivekvt** [aws-amplify/amplify-cli#7070]
### Amplify Init

```
$ amplify init
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the project myapp
The following configuration will be applied:

Project information
| Name: myapp
| Environment: dev
| Default editor: Visual Studio Code
| App type: javascript
| Javascript framework: react
| Source Directory Path: src
| Distribution Directory Path: build
| Build Command: npm run-script build
| Start Command: npm run-script start

? Initialize the project with the above configuration? Yes
Using default provider  awscloudformation
/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-cdk/cloud-assembly-schema/lib/manifest.js:1
Error: Cannot find module 'jsonschema'
Require stack:
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-cdk/cloud-assembly-schema/lib/manifest.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-cdk/cloud-assembly-schema/lib/index.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-cdk/core/lib/annotations.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-cdk/core/lib/tag-aspect.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-cdk/core/lib/index.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-cdk/aws-appsync/lib/appsync.generated.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-cdk/aws-appsync/lib/index.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/graphql-transformer-core/lib/transformation/transform.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/graphql-transformer-core/lib/transformation/index.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/graphql-transformer-core/lib/index.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/graphql-transformer/transform-graphql-schema.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/transform-graphql-schema.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/push-resources.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/amplify-service-migrate.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/initializer.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/index.js
- /usr/local/lib/node_modules/@aws-amplify/cli/lib/init-steps/s2-initProviders.js
- /usr/local/lib/node_modules/@aws-amplify/cli/lib/commands/init.js
- /usr/local/lib/node_modules/@aws-amplify/cli/lib/index.js
- /usr/local/lib/node_modules/@aws-amplify/cli/bin/amplify
    at Object.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-cdk/cloud-assembly-schema/lib/manifest.ts:2:1)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-cdk/cloud-assembly-schema/lib/index.ts:3:1)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-cdk/core/lib/annotations.ts:1)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-cdk/core/lib/tag-aspect.ts:2:1)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-cdk/core/lib/index.ts:2:1)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-cdk/aws-appsync/lib/appsync.generated.ts:8:1)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-cdk/aws-appsync/lib/index.ts:2:1)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/graphql-transformer-core/src/transformation/transform.ts:3:1)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/graphql-transformer-core/src/transformation/index.ts:1)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/graphql-transformer-core/src/index.ts:3:1)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema.ts:7:1)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/transform-graphql-schema.ts:41:1)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/push-resources.ts:29:1)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/amplify-service-migrate.js:5:38)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/initializer.js:14:31)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/index.ts:2:21)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at /usr/local/lib/node_modules/@aws-amplify/cli/src/init-steps/s2-initProviders.ts:13:28
    at Array.forEach (<anonymous>)
    at initProviders (/usr/local/lib/node_modules/@aws-amplify/cli/src/init-steps/s2-initProviders.ts:12:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/src/commands/init.ts:29:7)
    at Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/index.ts:305:5)
    at executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:175:3)
    at Object.executeCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:28:5)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/src/index.ts:139:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-cdk/cloud-assembly-schema/lib/manifest.js',
    '/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-cdk/cloud-assembly-schema/lib/index.js',
    '/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-cdk/core/lib/annotations.js',
    '/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-cdk/core/lib/tag-aspect.js',
    '/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-cdk/core/lib/index.js',
    '/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-cdk/aws-appsync/lib/appsync.generated.js',
    '/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-cdk/aws-appsync/lib/index.js',
    '/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/graphql-transformer-core/lib/transformation/transform.js',
    '/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/graphql-transformer-core/lib/transformation/index.js',
    '/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/graphql-transformer-core/lib/index.js',
    '/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/graphql-transformer/transform-graphql-schema.js',
    '/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/transform-graphql-schema.js',
    '/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/push-resources.js',
    '/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/amplify-service-migrate.js',
    '/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/initializer.js',
    '/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/index.js',
    '/usr/local/lib/node_modules/@aws-amplify/cli/lib/init-steps/s2-initProviders.js',
    '/usr/local/lib/node_modules/@aws-amplify/cli/lib/commands/init.js',
    '/usr/local/lib/node_modules/@aws-amplify/cli/lib/index.js',
    '/usr/local/lib/node_modules/@aws-amplify/cli/bin/amplify'
  ]
}

```

### Amplify Configure

```
amplify configure
Cannot find module 'jsonschema'
Require stack:
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-cdk/cloud-assembly-schema/lib/manifest.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-cdk/cloud-assembly-schema/lib/index.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-cdk/core/lib/annotations.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-cdk/core/lib/tag-aspect.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-cdk/core/lib/index.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-cdk/aws-appsync/lib/appsync.generated.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-cdk/aws-appsync/lib/index.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/graphql-transformer-core/lib/transformation/transform.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/graphql-transformer-core/lib/transformation/index.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/graphql-transformer-core/lib/index.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/graphql-transformer/transform-graphql-schema.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/transform-graphql-schema.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/push-resources.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/amplify-service-migrate.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/initializer.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/index.js
- /usr/local/lib/node_modules/@aws-amplify/cli/lib/configure-new-user.js
- /usr/local/lib/node_modules/@aws-amplify/cli/lib/commands/configure.js
- /usr/local/lib/node_modules/@aws-amplify/cli/lib/index.js
- /usr/local/lib/node_modules/@aws-amplify/cli/bin/amplify
/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-cdk/cloud-assembly-schema/lib/manifest.js:1
Error: Cannot find module 'jsonschema'
Require stack:
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-cdk/cloud-assembly-schema/lib/manifest.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-cdk/cloud-assembly-schema/lib/index.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-cdk/core/lib/annotations.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-cdk/core/lib/tag-aspect.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-cdk/core/lib/index.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-cdk/aws-appsync/lib/appsync.generated.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-cdk/aws-appsync/lib/index.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/graphql-transformer-core/lib/transformation/transform.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/graphql-transformer-core/lib/transformation/index.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/graphql-transformer-core/lib/index.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/graphql-transformer/transform-graphql-schema.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/transform-graphql-schema.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/push-resources.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/amplify-service-migrate.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/initializer.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/index.js
- /usr/local/lib/node_modules/@aws-amplify/cli/lib/configure-new-user.js
- /usr/local/lib/node_modules/@aws-amplify/cli/lib/commands/configure.js
- /usr/local/lib/node_modules/@aws-amplify/cli/lib/index.js
- /usr/local/lib/node_modules/@aws-amplify/cli/bin/amplify
    at Object.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-cdk/cloud-assembly-schema/lib/manifest.ts:2:1)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-cdk/cloud-assembly-schema/lib/index.ts:3:1)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-cdk/core/lib/annotations.ts:1)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-cdk/core/lib/tag-aspect.ts:2:1)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-cdk/core/lib/index.ts:2:1)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-cdk/aws-appsync/lib/appsync.generated.ts:8:1)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-cdk/aws-appsync/lib/index.ts:2:1)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/graphql-transformer-core/src/transformation/transform.ts:3:1)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/graphql-transformer-core/src/transformation/index.ts:1)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/graphql-transformer-core/src/index.ts:3:1)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema.ts:7:1)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/transform-graphql-schema.ts:41:1)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/push-resources.ts:29:1)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/amplify-service-migrate.js:5:38)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/initializer.js:14:31)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/index.ts:2:21)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at /usr/local/lib/node_modules/@aws-amplify/cli/src/configure-new-user.ts:24:22
    at Array.forEach (<anonymous>)
    at Object.configureNewUser (/usr/local/lib/node_modules/@aws-amplify/cli/src/configure-new-user.ts:23:21)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/src/commands/configure.ts:37:5)
    at Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/index.ts:305:5)
    at executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:175:3)
    at Object.executeCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:28:5)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/src/index.ts:139:5)
```

**Amplify CLI Version** 

```
$ amplify -v
4.47.1
```

**Node Version** 
```
 node -v
v14.15.1
```

**Comment by jhockett** [comment]
@vivekvt how did you install Amplify CLI?

**Comment by vivekvt** [comment]
@jhockett 

I uninstalled @aws-amplify/cli

Then also manually delete this folder /usr/local/lib/node_modules/@aws-amplify

Again installed @aws-amplify/cli

```
sudo npm install -g @aws-amplify/cli
```

Now everything is working fine.
