### ISSUE TITLE
amplify pull into mobile apps has started di

### ISSUE THREAD

**Issue by kjones** [aws-amplify/amplify-cli#7162]
Attempting to pull backend environment into Android and iOS  projects. Any hints on how to figure out what is going wrong?

```
└ ▶ amplify pull
? Select the authentication method you want to use: AWS profile

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

? Please choose the profile you want to use amplify-temp
? Which app are you working on? d3gvpt38n902ka
? Pick a backend environment: kj
? Choose your default editor: Visual Studio Code
? Choose the type of app that you're building android
Please tell us about your project
? Where is your Res directory:  src/main/res

GraphQL schema compiled successfully.

Edit your schema at /Users/kjones/projects/nxt-flutter/packages/nxt_amplify/android/amplify/backend/api/pace/schema.graphql or place .graphql files in a directory at /Users/kjones/projects/nxt-flutter/packages/nxt_amplify/android/amplify/backend/api/pace/schema
Successfully generated models. Generated models can be found in /Users/kjones/projects/nxt-flutter/packages/nxt_amplify/android/src/main/java
? Do you plan on modifying this backend? Yes
✔ Successfully pulled backend environment kj from the cloud.
✖ There was an error initializing your environment.
Failed to pull the backend.
Cannot destructure property 'provider' of 'serviceMetadata' as it is undefined.
TypeError: Cannot destructure property 'provider' of 'serviceMetadata' as it is undefined.
    at updateConfigOnEnvInit (/Users/kjones/.npm-packages/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-storage/src/provider-utils/awscloudformation/index.js:66:11)
    at /Users/kjones/.npm-packages/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-storage/src/index.js:150:28
    at /Users/kjones/.npm-packages/lib/node_modules/@aws-amplify/cli/node_modules/promise-sequential/index.js:16:18
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by cjihrig** [comment]
> Any hints on how to figure out what is going wrong?

Are you able to log the value of `service` [here](https://github.com/aws-amplify/amplify-cli/blob/ec1a5a754bc1232f6f9808025d58413c0143bfd3/packages/amplify-category-storage/src/provider-utils/awscloudformation/index.js#L65)? It looks like the code is currently only able to handle S3 and DynamoDB there.

**Comment by kjones** [comment]
Excellent. That helped point me in the right direction. Someone on the team added a custom QLDB resource and put it in the storage category with a service type of "QLDB". Haven't tried it yet but I'm going to close this. Mostly because I'll forget to do that 2 hrs from now.
