### ISSUE TITLE
Adding prediction access to a function, results in an error

### ISSUE THREAD

**Issue by ianwijma** [aws-amplify/amplify-cli#7269]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.16.0

### Amplify CLI Version

4.50.2

### What operating system are you using?

Mac

### Amplify Categories

function, api, predictions

### Amplify Commands

update

### Describe the bug

When I try to add predictions `Resource access permissions` to a function, it throws an error. and does not process the change.

### Expected behavior

That predictions is being added

### Reproduction steps

1. Run `amplify function update`
2. Select `Lambda function (serverless function)`
3. Select the rest function you want to update
4. Select `Resource access permissions`
5. Add `predictions`
6. Select all the `predictions` permissions (full CRUD)
7. See the error

Error: 
```
Policies cannot be added for predictions
Error: Method getPermissionPolicies does not exist or not a function in category plugin: predictions.
    at AmplifyToolkit.invokePluginMethod [as _invokePluginMethod] (/Users/ian/.nvm/versions/node/v14.16.0/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/invoke-plugin-method.js:31:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.askExecRolePermissionsQuestions (/Users/ian/.nvm/versions/node/v14.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.js:122:72)
    at async Object.updateWalkthrough (/Users/ian/.nvm/versions/node/v14.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/service-walkthroughs/lambda-walkthrough.js:144:38)
    at async updateFunctionResource (/Users/ian/.nvm/versions/node/v14.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/index.js:146:22)
    at async Object.executeAmplifyCommand (/Users/ian/.nvm/versions/node/v14.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/lib/index.js:225:5)
    at async executePluginModuleCommand (/Users/ian/.nvm/versions/node/v14.16.0/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:164:5)
    at async Object.executeCommand (/Users/ian/.nvm/versions/node/v14.16.0/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:35:9)
    at async Object.run (/Users/ian/.nvm/versions/node/v14.16.0/lib/node_modules/@aws-amplify/cli/lib/index.js:112:9)
```

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
ian@Ians-MacBook-Pro transcription % amplify function update
? Select which capability you want to update: Lambda function (serverless function)
? Select the Lambda function you want to update importAwmItem
General information
| Name: importAwmItem
| Runtime: nodejs

Resource access permission
- transcription (Query, Mutation)

Scheduled recurring invocation
| Not configured

Lambda layers
- Not configured

? Which setting do you want to update? Resource access permissions
? Select the categories you want this function to have access to. api, predictions
? Api has 2 resources in this project. Select the one you would like your Lambda to access <project>
? Select the operations you want to permit on <project> Query, Mutation
? Select the operations you want to permit on identifyText6e28831a create
Policies cannot be added for predictions
Error: Method getPermissionPolicies does not exist or not a function in category plugin: predictions.
    at AmplifyToolkit.invokePluginMethod [as _invokePluginMethod] (/Users/ian/.nvm/versions/node/v14.16.0/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/invoke-plugin-method.js:31:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.askExecRolePermissionsQuestions (/Users/ian/.nvm/versions/node/v14.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.js:122:72)
    at async Object.updateWalkthrough (/Users/ian/.nvm/versions/node/v14.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/service-walkthroughs/lambda-walkthrough.js:144:38)
    at async updateFunctionResource (/Users/ian/.nvm/versions/node/v14.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/index.js:146:22)
    at async Object.executeAmplifyCommand (/Users/ian/.nvm/versions/node/v14.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/lib/index.js:225:5)
    at async executePluginModuleCommand (/Users/ian/.nvm/versions/node/v14.16.0/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:164:5)
    at async Object.executeCommand (/Users/ian/.nvm/versions/node/v14.16.0/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:35:9)
    at async Object.run (/Users/ian/.nvm/versions/node/v14.16.0/lib/node_modules/@aws-amplify/cli/lib/index.js:112:9)

You can access the following resource attributes as environment variables from your Lambda function
        API_<project>_GRAPHQLAPIENDPOINTOUTPUT
        API_<project>_GRAPHQLAPIIDOUTPUT
        API_<project>_GRAPHQLAPIKEYOUTPUT
? Do you want to edit the local lambda function now? No
```

</details>

**Comment by attilah** [comment]
@ianwijma what you see is by design, the CLI does not support assigning permissions to resources in the prediction category and it is not filtered out during the `update function` flow.

To better understand what you like to do please describe your use case.

I mark it as an enhancement for predictions category.

**Comment by renebrandel** [comment]
Hey, I'll still mark this as a bug because we shouldn't be showing a stack trace like that. We'll try to tackle this in our bug bash.

**Comment by attilah** [comment]
@renebrandel that is a different and separate issue, you can open a bug about that but the root cause here is enhancement.

**Comment by ianwijma** [comment]
@attilah I was working on migrating some code to functions, because it was not working on NextJS API ref: https://github.com/aws-amplify/amplify-js/issues/8221

We basically want to do some mass processing of images with text using textract, and doing this client side is slow and unreliable. So want to do it using a function. So I was hoping do set the correct permissions using the Amplify CLI. But without luck.

**Comment by attilah** [comment]
Changing back to enhancement as the DX part commented by @renebrandel is fixed in the PR.

**Comment by kaustavghosh06** [comment]
Pr for this is merged and released.

**Comment by renebrandel** [comment]
@kaustavghosh06 should this be closed or open?
