### ISSUE TITLE
Amplify push fails with An error occurred during the push operation: args.fields.forEach is not a function

### ISSUE THREAD

**Issue by tfendt** [aws-amplify/amplify-cli#7288]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

15.10.0

### Amplify CLI Version

4.50.2

### What operating system are you using?

Mac

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

When running amplify push with a graphql schema change that includes a 1 - 1 connection the following error occurs:
```
args.fields.forEach is not a function
An error occurred during the push operation: args.fields.forEach is not a function
```

I can push basic tables without any connection directives without issue. As soon as I add a connection I get the error above and nothing gets pushed.

### Expected behavior

Amplify push should push the changes and create the connection.

### Reproduction steps

1. Create a graph schema like the one added to this ticket.
2. Run amplify push

### GraphQL schema(s)

<details>

```graphql
type Waiver @model 
  @auth(
    rules: [
      {allow: owner},
      {allow: groups, groups: ["admin"]}
    ])
{
  id: ID!
  active: String!
  waiverText: String!
  createdAt: String!
}

type WaiverSignatures @model
  @auth(
    rules: [
      {allow: owner},
      {allow: groups, groups: ["admin"]}
    ])
{
  id: ID!
  waiverId: ID!
  waiver: Waiver @connection(fields: "waiverId")
  signature: String!
  email: String!
  createdAt: String!
}

```

</details>

### Log output

<details>

```
✖ An error occurred when pushing the resources to the cloud
2021-05-07T16:39:10.519Z [WARNING]: ✖ There was an error initializing your environment.
2021-05-07T16:39:10.531Z [INFO]: [0mTypeError: args.fields.forEach is not a function[0m
                                 [0m    at ModelConnectionTransformer.connectionWithKey (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-connection-transformer/src/ModelConnectionTransformer.ts:557:17)[0m
                                 [0m    at ModelConnectionTransformer.field (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-connection-transformer/src/ModelConnectionTransformer.ts:225:12)[0m
                                 [0m    at GraphQLTransform.transformField (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/GraphQLTransform.ts:376:25)[0m
                                 [0m    at GraphQLTransform.transformObject (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/GraphQLTransform.ts:354:12)[0m
                                 [0m    at GraphQLTransform.transform (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/GraphQLTransform.ts:270:18)[0m
                                 [0m    at _buildProject (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/util/amplifyUtils.ts:91:35)[0m
                                 [0m    at runMicrotasks (<anonymous>)[0m
                                 [0m    at processTicksAndRejections (internal/process/task_queues.js:97:5)[0m
                                 [0m    at ensureMissingStackMappings (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/util/amplifyUtils.ts:165:23)[0m
                                 [0m    at Object.buildProject (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/util/amplifyUtils.ts:50:3)[0m
                                 [0m    at Object.transformGraphQLSchema (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/transform-graphql-schema.ts:491:29)[0m
                                 [0m    at Object.run (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/push-resources.ts:125:5)[0m
2021-05-07T16:39:10.562Z [ERROR]: !!! Build failed


```

</details>

**Comment by attilah** [comment]
@tfendt you have to pass in an array for the `fields` property, instead of `"waiverId"` use `["waiverId"]` as the directive definition says.

The code fails because of a dependency error, the GraphQL parser should coerce the value into an array but that is not what we get hence the error, we know about this issue and once the dependency is updated this will be also working as you specified.
