### ISSUE TITLE
Build failures on 4.51.1 when adding storage table permissions to function

### ISSUE THREAD

**Issue by yiweixia** [aws-amplify/amplify-cli#7358]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

12.20.1

### Amplify CLI Version

4.51.1

### What operating system are you using?

Mac

### Amplify Categories

storage, function

### Amplify Commands

push

### Describe the bug

I've recently added a storage table using `amplify storage add` on amplify version 4.50.2, and I give one of my amplify functions permissions to access it using `amplify function update`. It deployed fine for me, but it fails to build in other environments running 4.51.2 (we've tested on another dev's mac using `amplify push`, and using amplify's build servers, both fail).

When downgrading the configured amplify version in the build settings in the amplify console, the deployment succeeds on amplify's build servers.

However, if I upgrade to 4.51.2 in my local environment after successfully deploying on 4.50.2, the new deployment still succeeds.

### Expected behavior

The changes should deploy successfully on 4.51.2.

### Reproduction steps

0. Use amplify 4.50.2
1. Add a new table to storage with `amplify storage add`
2. Give a function permissions to access the table using 
2.a `amplify function update`
2.b select function
2.c `resource access permissions`
2.d `storage`
2.e assign permissions
3. `amplify push`
4. push code, trigger build using 4.51.1
5. build should fail

### Log output

<details>

```
                                 # Starting phase: build
                                 # Executing command: amplifyPush --simple
2021-05-19T16:14:08.958Z [INFO]: [0mAmplify AppID found: d1he6253vtkqx8. Amplify App name is: wesponsored-web[0m
2021-05-19T16:14:09.083Z [INFO]: [0mBackend environment master found in Amplify Console app: wesponsored-web[0m
2021-05-19T16:14:11.585Z [WARNING]: - Fetching updates to backend environment: master from the cloud.
2021-05-19T16:14:13.357Z [WARNING]: ✔ Successfully pulled backend environment master from the cloud.
2021-05-19T16:14:13.380Z [WARNING]: - Retrieving channel information for APNS.
2021-05-19T16:14:13.481Z [WARNING]: ✔ Channel information retrieved for APNS
2021-05-19T16:14:13.482Z [WARNING]: - Retrieving channel information for FCM.
2021-05-19T16:14:13.564Z [WARNING]: ✔ Channel is not setup for FCM
2021-05-19T16:14:13.564Z [WARNING]: - Retrieving channel information for Email.
2021-05-19T16:14:13.691Z [WARNING]: ✔ Channel is not setup for Email
2021-05-19T16:14:13.692Z [WARNING]: - Retrieving channel information for SMS.
2021-05-19T16:14:13.780Z [WARNING]: ✔ Channel is not setup for SMS
2021-05-19T16:14:15.074Z [WARNING]: - Uploading files...
2021-05-19T16:14:15.858Z [INFO]: [0mAdding Lambda layer reportingShared to master environment.[0m
2021-05-19T16:14:15.884Z [INFO]: [0mAdding Lambda layer sharedv3 to master environment.[0m
2021-05-19T16:14:16.356Z [INFO]: 
2021-05-19T16:14:19.515Z [INFO]: [33mNote: It is recommended to run this command from the root of your app directory[39m
2021-05-19T16:14:24.990Z [WARNING]: - Initializing your environment: master
2021-05-19T16:15:10.460Z [WARNING]: ✔ Initialized provider successfully.
2021-05-19T16:15:10.484Z [WARNING]: - Retrieving channel information for APNS.
2021-05-19T16:15:10.609Z [WARNING]: ✔ Channel information retrieved for APNS
2021-05-19T16:15:10.610Z [WARNING]: - Retrieving channel information for FCM.
2021-05-19T16:15:10.735Z [WARNING]: ✔ Channel is not setup for FCM
2021-05-19T16:15:10.736Z [WARNING]: - Retrieving channel information for Email.
2021-05-19T16:15:10.878Z [WARNING]: ✔ Channel is not setup for Email
2021-05-19T16:15:10.879Z [WARNING]: - Retrieving channel information for SMS.
2021-05-19T16:15:11.040Z [WARNING]: ✔ Channel is not setup for SMS
2021-05-19T16:15:12.328Z [WARNING]: - Uploading files...
2021-05-19T16:15:13.909Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
2021-05-19T16:15:13.935Z [WARNING]: ✖ There was an error initializing your environment.
2021-05-19T16:15:13.941Z [INFO]: [0mTypeError: Cannot read property 'find' of undefined[0m
                                 [0m    at /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/provider-utils/awscloudformation/utils/getDependentFunction.ts:19:26[0m
                                 [0m    at Array.filter (<anonymous>)[0m
                                 [0m    at lambdasWithApiDependency (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/provider-utils/awscloudformation/utils/getDependentFunction.ts:15:44)[0m
                                 [0m    at AmplifyToolkit.invokePluginMethod [as _invokePluginMethod] (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/invoke-plugin-method.ts:29:10)[0m
                                 [0m    at Object.ensureValidFunctionModelDependencies (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/utils/remove-dependent-function.ts:18:33)[0m
                                 [0m    at Object.run (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/push-resources.ts:104:43)[0m
2021-05-19T16:15:14.016Z [ERROR]: !!! Build failed
2021-05-19T16:15:14.016Z [ERROR]: !!! Non-Zero Exit Code detected
2021-05-19T16:15:14.016Z [INFO]: # Starting environment caching...
2021-05-19T16:15:14.017Z [INFO]: # Uploading environment cache artifact...
2021-05-19T16:15:14.101Z [INFO]: # Environment caching completed
Terminating logging...


```

</details>

### Additional information

Our function also has dependencies on custom resources in our backend.config (2xSNS), not sure if that has any effect.

<details>

    "functionName1": {
      "build": true,
      "providerPlugin": "awscloudformation",
      "service": "Lambda",
      "dependsOn": [
        {
          "category": "api",
          "resourceName": "apiName",
          "attributes": [
            "GraphQLAPIIdOutput",
            "GraphQLAPIEndpointOutput",
            "GraphQLAPIKeyOutput"
          ]
        },
        {
          "category": "sns",
          "resourceName": "sns1",
          "attributes": [
            "Arn"
          ]
        },
        {
          "category": "sns",
          "resourceName": "sns2",
          "attributes": [
            "Arn"
          ]
        },
        {
          "category": "storage",
          "resourceName": "tableName1",
          "attributes": [
            "Name",
            "Arn"
          ]
        }
      ]
    },

</details>

**Comment by akshbhu** [comment]
Hi @yiweixia 

I have some questions: 

- Did you remove any models from the graphql scehma before pushing?
- Is the function config you shared above is same for environments where the build is failing?
- Can you also share function-parameters.json file after redacting any secret information from it?
