### ISSUE TITLE
Can't pull amplify app: operation not permitted, rename

### ISSUE THREAD

**Issue by oriklein195** [aws-amplify/amplify-cli#7448]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v13.14.0

### Amplify CLI Version

4.52.0

### What operating system are you using?

Windows 7

### Amplify Categories

Not applicable

### Amplify Commands

pull

### Describe the bug

using `amplify pull --appId <id> --envName <name>` breaks with the following error:
`EPERM: operation not permitted, rename 'C:\Users\Ori\Documents\tawkit\backend\am
plify' -> 'C:\Users\Ori\Documents\tawkit\backend\amplify-backup'
Error: EPERM: operation not permitted, rename 'C:\Users\Ori\Documents\tawkit\bac
kend\amplify' -> 'C:\Users\Ori\Documents\tawkit\backend\amplify-backup'
    at Object.renameSync (fs.js:754:3)
    at rename (C:\Program Files\nodejs\node_modules\@aws-amplify\cli\node_module
s\fs-extra\lib\move-sync\move-sync.js:31:8)
    at doRename (C:\Program Files\nodejs\node_modules\@aws-amplify\cli\node_modu
les\fs-extra\lib\move-sync\move-sync.js:26:10)
    at Object.moveSync (C:\Program Files\nodejs\node_modules\@aws-amplify\cli\no
de_modules\fs-extra\lib\move-sync\move-sync.js:17:10)
    at backupAmplifyFolder (C:\Program Files\nodejs\node_modules\@aws-amplify\cl
i\lib\attach-backend.js:107:12)
    at Object.attachBackend (C:\Program Files\nodejs\node_modules\@aws-amplify\c
li\lib\attach-backend.js:35:5)
    at Object.run (C:\Program Files\nodejs\node_modules\@aws-amplify\cli\lib\com
mands\pull.js:64:32)
    at Object.executeAmplifyCommand (C:\Program Files\nodejs\node_modules\@aws-a
mplify\cli\lib\index.js:238:29)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async executePluginModuleCommand (C:\Program Files\nodejs\node_modules\@a
ws-amplify\cli\lib\execution-manager.js:164:5)
    at async Object.executeCommand (C:\Program Files\nodejs\node_modules\@aws-am
plify\cli\lib\execution-manager.js:35:9)
    at async Object.run (C:\Program Files\nodejs\node_modules\@aws-amplify\cli\l
ib\index.js:114:9)`

### Expected behavior

amplify pulls correctly.

### Reproduction steps

amplify pull -appId <id> -envName <name>

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

looks like this issue: https://github.com/aws-amplify/amplify-cli/issues/6138#issuecomment-742730830
but it's still repro-ing.

**Comment by yuth** [comment]
@oriklein195 when you run `amplify pull` command do you have any files from `C:\Users\Ori\Documents\tawkit\backend` open in text editor?

**Comment by yuth** [comment]
@oriklein195 this is issue with windows, which locks the file if any application has it open. There isn't Amplify CLI can do, except show a nicer error message.
