### ISSUE TITLE
amplify configure fails

### ISSUE THREAD

**Issue by thrixton** [aws-amplify/amplify-cli#75]
**Do you want to request a feature or report a bug?**
Bug

**What is the current behavior?**
Unable to configure amplify

**Steps to reproduce the issue:**

1. `npm install -g @aws-amplify/cli`
2. `amplify configure`

**Result**
```
D:\Development>amplify configure
C:\Users\User1\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\gluegun\build\index.js:13
    throw up;
    ^

Error: You are not working inside a valid amplify project.
Use 'amplify init' in the root of your app directory to initialize your project with Amplify
    at getAmplifyDirPath (C:\Users\User1\AppData\Roaming\npm\node_modules\@aws-amplify\cli\src\extensions\amplify-helpers\path-manager.js:58:9)
    at getDotConfigDirPath (C:\Users\User1\AppData\Roaming\npm\node_modules\@aws-amplify\cli\src\extensions\amplify-helpers\path-manager.js:64:5)
    at Object.getProjectConfigFilePath (C:\Users\User1\AppData\Roaming\npm\node_modules\@aws-amplify\cli\src\extensions\amplify-helpers\path-manager.js:101:5)
    at Object.getProjectDetails (C:\Users\User1\AppData\Roaming\npm\node_modules\@aws-amplify\cli\src\extensions\amplify-helpers\get-project-details.js:5:45)
    at Command.run (C:\Users\User1\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-category-hosting\commands\hosting\configure.js:7:39)
    at Runtime.<anonymous> (C:\Users\User1\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\gluegun\build\runtime\run.js:90:58)
    at step (C:\Users\User1\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\gluegun\build\runtime\run.js:32:23)
    at Object.next (C:\Users\User1\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\gluegun\build\runtime\run.js:13:53)
    at C:\Users\User1\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\gluegun\build\runtime\run.js:7:71
    at new Promise (<anonymous>)
```

**What is the expected behavior?**
Configure amplify

**Additional environment details**

* **OS version (ie Windows 10 build X, macOS Sierra 10.12.6, etc.)**
OS Name	Microsoft Windows 10 Pro
Version	10.0.17134 Build 17134

* **Output of ``amplify --version``**:
0.1.14
* **Did this work in previous versions?**: 
Unknown

**Comment by kaustavghosh06** [comment]
@wstidolph  checkout @mwarger  post on using Windows Linux Subsystem(WSL) on native windows power shell out here - https://github.com/aws-amplify/amplify-cli/issues/13. I think it’s a great workaround and would highly recommend using WSL for the Amplify CLI as recommended on our main Readme page.

**Comment by kaustavghosh06** [comment]
Duplicate of https://github.com/aws-amplify/amplify-cli/issues/13
