### ISSUE TITLE
Can't Push or Pull Due to Bug saying my 'team-provider-info.json' does not exist, even though it does.

### ISSUE THREAD

**Issue by bks715** [aws-amplify/amplify-cli#7557]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

N/A

### Amplify CLI Version

5.0.0

### What operating system are you using?

Mac

### Amplify Categories

auth, storage, api, hosting

### Amplify Commands

pull, push

### Describe the bug

Any time I Try to push I pull I get an error saying File at path: '/Users/.../JXNMedical/Rash ID Swift UI/amplify/team-provider-info.json' does not exist.

### Expected behavior

I expect the changes to either push or pull.

### Reproduction steps

Just try to push or pull an environment. 

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line
Error: File at path: '/Users/bradensmith/JXNMedical/Rash ID Swift UI/amplify/team-provider-info.json' does not exist
    at Function.JSONUtilities.readJson (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/jsonUtilities.js:40:19)
    at StateManager.getData (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/state-manager/stateManager.js:223:56)
    at StateManager.getTeamProviderInfo (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/state-manager/stateManager.js:68:25)
    at Object.initializeEnv (/usr/local/lib/node_modules/@aws-amplify/cli/lib/initialize-env.js:19:66)
    at Object.pullBackend (/usr/local/lib/node_modules/@aws-amplify/cli/lib/pull-backend.js:30:28)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/lib/commands/pull.js:60:13)
    at async Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/lib/index.js:240:9)
    at async executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:164:5)
    at async Object.executeCommand (/usr/local/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:35:9)
    at async Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/lib/index.js:116:9)

```

</details>

### Additional information

Thanks for you help.

**Comment by kaustavghosh06** [comment]
@bks715 I think the issue might be tied to the app-project-name reflected in the app folder-name - "Rash ID Swift UI" Can you try removing the spaces and try again?

**Comment by attilah** [comment]
@bks715 I tried to reproduce it by creating the exact same project name to see if that is about spaces or not (which we have no problems with), and I was able to `push`, `pull` and also pulled to empty directory and worked as expected. Is it happening with other projects as well?

**Comment by bks715** [comment]
No even though I took the spaces out of the folder name it's still trying to find the file under the folder name with the spaces in it.

**Comment by bks715** [comment]
It's strange because I've pushed and pulled this environment many times before I updated the CLI.

**Comment by attilah** [comment]
@bks715 we need more data to be able to get to this, something must be wrong with the project itself.

1. pull the project with 4.5.2 into empty directory and send the log file from ~/.amplify/logs and then remove the log file
2. update cli to 5.0.1
3. pull the project with 4.5.2 into empty directory and send the log file from ~/.amplify/logs

paste them here separately or email to amplify-cli@amazon.com with issue number in the subject.

**Comment by bks715** [comment]
[amplify-cli-2021-06-23.log](https://github.com/aws-amplify/amplify-cli/files/6703176/amplify-cli-2021-06-23.log)

For some reason the 4.5 version didn't produce a log but here is the log from 5.0.1. It successfully pulled to this new folder. 
However I still can't pull anything into a folder that also contains the iOS project. I'm also using MacOS Monterey Beta, so I'm not sure if that may be causing a problem.

**Comment by bks715** [comment]
I deleted all of the amplify files from that project folder and was finally able to pull. Thank you very much for your help.

**Comment by attilah** [comment]
Sounds good, so it was some local issue as I suspected, glad you were able to solve it!
