### ISSUE TITLE
amplify configure throws error on fresh install 

### ISSUE THREAD

**Issue by mattcrox** [aws-amplify/amplify-cli#76]
**Do you want to request a feature or report a bug?**
Bug

**What is the current behavior?**
After installing amplify (npm install -g @aws-amplify/cli), I run 'amplify configure' (or just `amplify` itself and receive the following error: 

/usr/local/lib/node_modules/@aws-amplify/cli/src/commands/console.js:9
    const combinedPlugins = { ...categoryPlugins, ...providerPlugins };
                              ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.loadModule (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/loaders/module-loader.js:14:12)

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

**Steps to reproduce the issue:**

1. Install Amplify - npm install -g @aws-amplify/cli
2. Run amplify - amplify
3. 

**What is the expected behavior?**
Amplify does not throw an exception, and configures the backend services.

**Additional environment details**

* **OS version  - Mac OS High Sierra 10.13.6 
* **Output of ``amplify --version``**: Error thrown upon trying to retrieve version
* **Did this work in previous versions?**: Unsure - first install

**Comment by mattcrox** [comment]
@kaustavghosh06 I did check that I was on version 8, by running `node --version` - however, the update resolved the error so something around versioning must have been incorrect. Thanks for responding...
