### ISSUE TITLE
Cannot destructure property 'value' of 'layerConfig.runtimes[0]' as it is undefined.

### ISSUE THREAD

**Issue by axecopfire** [aws-amplify/amplify-cli#7622]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.17.1

### Amplify CLI Version

5.0.2

### What operating system are you using?

Debian

### Amplify Categories

auth, function, api, hosting

### Amplify Commands

status

### Describe the bug

I recently updated to the latest amplify-cli version and now I can't use amplicy-cli.

### Expected behavior

I expect I can use amplify-cli without getting errors.

### Reproduction steps

I am on a new computer and installed Amplify (I didn't realize that v5 vs v4 breaks backwards compatibility with lambda layers). I ran
```
amplify update auth
(Needed to update Admin Actions to allow for a particular group)
amplify push
```

I saw that the update was unsuccessful in Cloud Formation with the error:
`The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey;`
(I do not have the error I had locally from amplify-cli.)

I found [this answer](https://github.com/aws-amplify/amplify-cli/issues/4612#issuecomment-646711256), which suggests `amplify push --force`.

Now when I try to perform actions with amplify-cli I get this error:
```

$ > amplify status

Current Environment: main

Cannot destructure property 'value' of 'layerConfig.runtimes[0]' as it is undefined.
TypeError: Cannot destructure property 'value' of 'layerConfig.runtimes[0]' as it is undefined.
    at hashLayerVersion (/home/user/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/utils/layerHelpers.js:339:24)
    at hashLayerResource (/home/user/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/utils/layerHelpers.js:275:18)
    at isBackendDirModifiedSinceLastPush (/home/user/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js:46:32)
    at /home/user/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js:173:51
    at asyncForEach (/home/user/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js:271:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /home/user/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js:163:9
    at async asyncForEach (/home/user/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js:271:9)
    at async getResourcesToBeUpdated (/home/user/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js:161:5)
    at async getResourceStatus (/home/user/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js:289:32)
    at async AmplifyToolkit.showResourceTable [as _showResourceTable] (/home/user/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js:320:131)
    at async Object.run (/home/user/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/lib/commands/status.js:5:5)
    at async Object.executeAmplifyCommand (/home/user/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/lib/index.js:238:9)
    at async executePluginModuleCommand (/home/user/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:164:5)
    at async Object.executeCommand (/home/user/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:35:9)
    at async Object.run (/home/user/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/lib/index.js:116:9)
```

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line

```

</details>

**Comment by jhockett** [comment]
Hi @axecopfire, this issue will be fixed by https://github.com/aws-amplify/amplify-cli/pull/7603. It will be available in the next release.
