### ISSUE TITLE
Project already removed from cloud fails to delete local files on `amplify delete`

### ISSUE THREAD

**Issue by niallotuathail** [aws-amplify/amplify-cli#7631]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-adminui/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-adminui/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3tmm42htknpun

### Region

eu-west-1

### Environment name

dev

### Amplify CLI Version

5.0.0

### What operating system are you using?

Mac

### Browser type?

Chrome

### Describe the bug

I'm trying to do a fresh initialisation of Amplify for a project with two front-end clients. I ran amplify delete on one client folder and then tried to run amplify delete on the second to remove all of the local files. 

It wouldn't delete locally after discovering the app was already deleted in the Cloud.

### Expected behavior

amplify delete should recognise app has already been deleted and delete locally.

### Reproduction steps

Run amplify delete in first project folder
Run amplify delete in another project folder with same amplify project

### Additional information

Console output
```
niallotuathail@Nialls-Mac-mini PrimeForLife % amplify delete
? Are you sure you want to continue? This CANNOT be undone. (This will delete all the environments of the p
roject from the cloud and wipe out all the local files created by Amplify CLI) Yes
⠋ Deleting resources from the cloud. This may take a few minutes...
Deleting env:dev
⠹ Deleting resources from the cloud. This may take a few minutes...Unable to remove env: dev because deployment bucket amplify-primeforlife-dev-203747-deployment does not exist or has been deleted.
⠦ Deleting resources from the cloud. This may take a few minutes...Stack has already been deleted or does not exist
⠏ Deleting resources from the cloud. This may take a few minutes...
Error in deleting env:dev
App d3tmm42htknpun not found.
✖ Project delete failed
App d3tmm42htknpun not found.
NotFoundException: App d3tmm42htknpun not found.
    at Object.extractError (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.extractError (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at callNextListener (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at IncomingMessage.onEnd (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/event_listeners.js:313:13)
    at IncomingMessage.emit (node:events:377:35)
    at IncomingMessage.emit (node:domain:470:12)
    at endReadableNT (node:internal/streams/readable:1312:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
niallotuathail@Nialls-Mac-mini PrimeForLife % 
```

**Comment by hsspain** [comment]
@niallotuathail I am transferring this to the amplify-cli group as they should be able to help you with this issue.

**Comment by edwardfoyle** [comment]
Hi @niallotuathail I'll mark this as a feature request to skip the cloud deletion steps if already deleted. In the meantime, if you want to remove amplify from your local project you can run `rm -rf <project root>/amplify`

**Comment by niallotuathail** [comment]
Thanks Edward. Much appreciated.

**Comment by Bentheburrito** [comment]
Hello, I'd like to take this issue up :slightly_smiling_face:

**Comment by josefaidt** [comment]
Hey @Bentheburrito thanks for picking this up! I'll go ahead and assign to you 🙂 let us know if you run into any blockers as you're working through it

**Comment by Bentheburrito** [comment]
Thanks Josef!
