### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The 'request' argument must be string. 

### ISSUE THREAD

**Issue by aachman22** [aws-amplify/amplify-cli#7715]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v14.17.1

### Amplify CLI Version

5.1.1

### What operating system are you using?

Kubuntu

### Amplify Categories

Not applicable

### Amplify Commands

init

### Describe the bug

I'm trying to initialize amplify for my project and am running into this issue. I ran `amplify init` successfully a few days ago on a separate project without any issues. I am getting the following error message:

```
TypeError [ERR_INVALID_ARG_TYPE]: The 'request' argument must be string. Received type undefined
    at onSuccess (/home/aachman/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/src/init-steps/s9-onSuccess.ts:34:26)
    at Object.run (/home/aachman/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/src/commands/init.ts:29:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Object.executeAmplifyCommand (/home/aachman/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/src/index.ts:313:5)
    at executePluginModuleCommand (/home/aachman/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:177:3)
    at Object.executeCommand (/home/aachman/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:29:5)
    at Object.run (/home/aachman/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/src/index.ts:151:5)
```

### Expected behavior

I should not see any error messages.

### Reproduction steps

Run `amplify init`

Not sure why this issue is cropping up. I haven't done anything different from my previous successful attempt.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line

$ amplify init
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the environment dev
? Choose your default editor: Visual Studio Code
Using default provider  awscloudformation
? Select the authentication method you want to use: AWS profile

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

? Please choose the profile you want to use default
Adding backend environment dev to AWS Amplify Console app: d3686m009z6gth
⠋ Initializing project in the cloud...

CREATE_IN_PROGRESS amplify-insureproui-dev-195746 AWS::CloudFormation::Stack Tue Jul 13 2021 19:57:51 GMT+0530 (India Standard Time) User Initiated             
CREATE_IN_PROGRESS AuthRole                       AWS::IAM::Role             Tue Jul 13 2021 19:57:54 GMT+0530 (India Standard Time)                            
CREATE_IN_PROGRESS UnauthRole                     AWS::IAM::Role             Tue Jul 13 2021 19:57:54 GMT+0530 (India Standard Time)                            
CREATE_IN_PROGRESS DeploymentBucket               AWS::S3::Bucket            Tue Jul 13 2021 19:57:54 GMT+0530 (India Standard Time)                            
CREATE_IN_PROGRESS AuthRole                       AWS::IAM::Role             Tue Jul 13 2021 19:57:55 GMT+0530 (India Standard Time) Resource creation Initiated
CREATE_IN_PROGRESS UnauthRole                     AWS::IAM::Role             Tue Jul 13 2021 19:57:55 GMT+0530 (India Standard Time) Resource creation Initiated
CREATE_IN_PROGRESS DeploymentBucket               AWS::S3::Bucket            Tue Jul 13 2021 19:57:55 GMT+0530 (India Standard Time) Resource creation Initiated
⠧ Initializing project in the cloud...

CREATE_COMPLETE UnauthRole AWS::IAM::Role Tue Jul 13 2021 19:58:10 GMT+0530 (India Standard Time) 
CREATE_COMPLETE AuthRole   AWS::IAM::Role Tue Jul 13 2021 19:58:11 GMT+0530 (India Standard Time) 
⠇ Initializing project in the cloud...

CREATE_COMPLETE DeploymentBucket AWS::S3::Bucket Tue Jul 13 2021 19:58:17 GMT+0530 (India Standard Time) 
⠙ Initializing project in the cloud...

CREATE_COMPLETE amplify-insureproui-dev-195746 AWS::CloudFormation::Stack Tue Jul 13 2021 19:58:18 GMT+0530 (India Standard Time) 
✔ Successfully created initial AWS cloud resources for deployments.
TypeError [ERR_INVALID_ARG_TYPE]: The 'request' argument must be string. Received type undefined
    at onSuccess (/home/aachman/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/src/init-steps/s9-onSuccess.ts:34:26)
    at Object.run (/home/aachman/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/src/commands/init.ts:29:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Object.executeAmplifyCommand (/home/aachman/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/src/index.ts:313:5)
    at executePluginModuleCommand (/home/aachman/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:177:3)
    at Object.executeCommand (/home/aachman/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:29:5)
    at Object.run (/home/aachman/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/src/index.ts:151:5)


```

</details>

**Comment by ammarkarachi** [comment]
@aachman22 can you run `amplify plugin scan` and run the `amplify init` again?

**Comment by josefaidt** [comment]
Closing due to inactivity. @aachman22 if you feel this is in error are are still experiencing this issue with the [latest version of the Amplify CLI](https://github.com/aws-amplify/amplify-cli/releases/tag/v5.3.0) please reply back to this thread and we can re-open to investigate further 🙂
