### ISSUE TITLE
Amplify Build Timeout Period

### ISSUE THREAD

**Issue by martijnvdgrift** [aws-amplify/amplify-cli#7721]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

12

### Amplify CLI Version

5.1.1

### What operating system are you using?

Amazon Linux 2

### Amplify Categories

auth, storage, function, api, hosting

### Amplify Commands

init, push

### Describe the bug

When a new build is running in Amplify, the backend stage failes due to the following timeout error:

```
error: uncaughtException: Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.
```

I have tried this on multiple AWS accounts, both personal and corporate, so it seems not to be related to specific account setup.

### Expected behavior

Successful upload

### Reproduction steps

1. Create an amplify application
2. Connect a branch
3. Trigger a build pipeline via a Git commit.

### Log output

<details>

```
# Put your logs below this line
2021-07-14T10:50:27.613Z [WARNING]: 2021-07-14T10:50:27.612Z - error: uncaughtException: Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed. date=Wed Jul 14 2021 10:50:27 GMT+0000 (Coordinated Universal Time), pid=2159, uid=0, gid=0, cwd=/codebuild/output/src554480843/src/eredivisie-jackpot-app, execPath=/root/.nvm/versions/node/v12.21.0/bin/node, version=v12.21.0, argv=[/root/.nvm/versions/node/v12.21.0/bin/node, /root/.nvm/versions/node/v12.21.0/bin/amplify, init, --amplify, {"envName":"cathrine","appId":"dvmpttb4cm19h"}, --providers, {"awscloudformation":{"configLevel":"project","useProfile":true,"profileName":"default"}}, --codegen, {"generateCode":false,"generateDocs":false}, --yes, --forcePush], rss=468508672, heapTotal=290500608, heapUsed=276416984, external=15920570, arrayBuffers=13882606, loadavg=[0.91, 0.63, 0.28], uptime=441, trace=[column=35, file=/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/services/s3.js, function=Request.extractError, line=714, method=extractError, native=false, column=20, file=/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js, function=Request.callListeners, line=106, method=callListeners, native=false, column=10, file=/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js, function=Request.emit, line=78, method=emit, native=false, column=14, file=/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js, function=Request.emit, line=688, method=emit, native=false, column=10, file=/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js, function=Request.transition, line=22, method=transition, native=false, column=12, file=/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js, function=AcceptorStateMachine.runTo, line=14, method=runTo, native=false, column=10, file=/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js, function=null, line=26, method=null, native=false, column=9, file=/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js, function=null, line=38, method=null, native=false, column=12, file=/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js, function=null, line=690, method=null, native=false, column=18, file=/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js, function=Request.callListeners, line=116, method=callListeners, native=false, column=10, file=/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js, function=Request.emit, line=78, method=emit, native=false, column=14, file=/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js, function=Request.emit, line=688, method=emit, native=false, column=10, file=/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js, function=Request.transition, line=22, method=transition, native=false, column=12, file=/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js, function=AcceptorStateMachine.runTo, line=14, method=runTo, native=false, column=10, file=/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js, function=null, line=26, method=null, native=false, column=9, file=/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js, function=null, line=38, method=null, native=false, column=12, file=/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js, function=null, line=690, method=null, native=false, column=18, file=/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js, function=Request.callListeners, line=116, method=callListeners, native=false, column=12, file=/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js, function=callNextListener, line=96, method=null, native=false, column=13, file=/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/event_listeners.js, function=IncomingMessage.onEnd, line=336, method=onEnd, native=false, column=22, file=events.js, function=IncomingMessage.emit, line=326, method=emit, native=false, column=12, file=domain.js, function=IncomingMessage.EventEmitter.emit, line=483, method=emit, native=false, column=12, file=_stream_readable.js, function=endReadableNT, line=1241, method=null, native=false, column=21, file=internal/process/task_queues.js, function=processTicksAndRejections, line=84, method=null, native=false], stack=[RequestTimeout: Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.,     at Request.extractError (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/services/s3.js:714:35),     at Request.callListeners (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20),     at Request.emit (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10),     at Request.emit (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:688:14),     at Request.transition (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10),     at AcceptorStateMachine.runTo (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12),     at /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10,     at Request.<anonymous> (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9),     at Request.<anonymous> (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:690:12),     at Request.callListeners (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18),     at Request.emit (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10),     at Request.emit (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:688:14),     at Request.transition (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10),     at AcceptorStateMachine.runTo (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12),     at /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10,     at Request.<anonymous> (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9),     at Request.<anonymous> (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:690:12),     at Request.callListeners (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18),     at callNextListener (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:96:12),     at IncomingMessage.onEnd (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/event_listeners.js:336:13),     at IncomingMessage.emit (events.js:326:22),     at IncomingMessage.EventEmitter.emit (domain.js:483:12),     at endReadableNT (_stream_readable.js:1241:12),     at processTicksAndRejections (internal/process/task_queues.js:84:21)]
```

</details>

**Comment by ammarkarachi** [comment]
@martijnvdgrift which region are you deploying to?

**Comment by martijnvdgrift** [comment]
@ammarkarachi thanks for your response!

I've tried deploying to both eu-central-1 and eu-west-1, same result.
My backend project size:
![image](https://user-images.githubusercontent.com/6614641/125659612-6898ae3b-1a9f-4202-9cbf-7a4443a715ac.png)
Without Node modules:
![image](https://user-images.githubusercontent.com/6614641/125659807-5169b632-ce24-49f4-8979-e36d1d85e78d.png)

**Comment by martijnvdgrift** [comment]
I've played around with a few different versions, 5.1.0 works for me, so it seems that 5.1.1 introduced this (for our project).

**Comment by ammarkarachi** [comment]
@martijnvdgrift if you are deploying from or to `eu-central-1`, there were some events going on there yesterday morning. I don't see a change that would affect the upload part of the deployment by Amplify CLI.

**Comment by martijnvdgrift** [comment]
Yup, I have seen those events as well. But we still had problems today (till one hour ago). Moving to 5.1.0 solved it, for now. 
I'll try switching back to 5.1.1 later.

**Comment by kaustavghosh06** [comment]
@martijnvdgrift Are you still experiencing this issue?

**Comment by josefaidt** [comment]
Closing due to inactivity. @martijnvdgrift if you feel this is in error and are still experiencing the issue please reply back to this thread and we can re-open to investigate further. 🙂
