### ISSUE TITLE
envCache --get stackInfo returns empty on existing environment

### ISSUE THREAD

**Issue by adi518** [aws-amplify/amplify-cli#7753]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

14.17.0

### Amplify CLI Version

5.1.2

### What operating system are you using?

Linux

### Amplify Categories

Not applicable

### Amplify Commands

Not applicable

### Describe the bug

My CI fails on PR Preview `build` step because it `envCache --get stackInfo` returns empty on an existing environment. I can verify the stack exists under `CloudFormation -> Stacks`.

### Expected behavior

Get the existing environment and use it to continue the build.

### Reproduction steps

Run a Preview build.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line

                                 # Initializing new Amplify environment: prch (amplify init)
2021-07-20T11:40:51.826Z [INFO]: [33mNote: It is recommended to run this command from the root of your app directory[39m
2021-07-20T11:40:58.222Z [INFO]: [0mAmplify AppID found: dazj4he0xk1lv. Amplify App name is: deepdubapp[0m
2021-07-20T11:40:58.271Z [WARNING]: - Initializing project in the cloud...
2021-07-20T11:40:58.342Z [INFO]: [31m[39m
                                 [31mAn error occurred when creating the CloudFormation stack[39m
2021-07-20T11:40:58.344Z [WARNING]: ✖ Root stack creation failed
2021-07-20T11:40:58.349Z [INFO]: [0mAlreadyExistsException: Stack [amplify-deepdubapp-prch-103126] already exists[0m
                                 [0m    at Request.extractError (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/query.js:50:29)[0m
                                 [0m    at Request.callListeners (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)[0m
                                 [0m    at Request.emit (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)[0m
                                 [0m    at Request.emit (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:688:14)[0m
                                 [0m    at Request.transition (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)[0m
                                 [0m    at AcceptorStateMachine.runTo (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)[0m
                                 [0m    at /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10[0m
                                 [0m    at Request.<anonymous> (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)[0m
                                 [0m    at Request.<anonymous> (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:690:12)[0m
                                 [0m    at Request.callListeners (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)[0m
                                 [0m    at Request.emit (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)[0m
                                 [0m    at Request.emit (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:688:14)[0m
                                 [0m    at Request.transition (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)[0m
                                 [0m    at AcceptorStateMachine.runTo (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)[0m
                                 [0m    at /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10[0m
                                 [0m    at Request.<anonymous> (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)[0m
                                 [0m    at Request.<anonymous> (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:690:12)[0m
                                 [0m    at Request.callListeners (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)[0m
                                 [0m    at callNextListener (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:96:12)[0m
                                 [0m    at IncomingMessage.onEnd (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/event_listeners.js:336:13)[0m
                                 [0m    at IncomingMessage.emit (events.js:326:22)[0m
                                 [0m    at IncomingMessage.EventEmitter.emit (domain.js:483:12)[0m
                                 [0m    at endReadableNT (_stream_readable.js:1241:12)[0m
                                 [0m    at processTicksAndRejections (internal/process/task_queues.js:84:21) {[0m
                                 [0m  code: 'AlreadyExistsException',[0m
                                 [0m  time: 2021-07-20T11:40:58.341Z,[0m
                                 [0m  requestId: '1430a38b-6591-4d65-98bc-5ea580fc3f03',[0m
                                 [0m  statusCode: 400,[0m
                                 [0m  retryable: false,[0m
                                 [0m  retryDelay: 30.883168292505147[0m
                                 [0m}[0m
2021-07-20T11:40:58.365Z [ERROR]: !!! Build failed
2021-07-20T11:40:58.366Z [ERROR]: !!! Non-Zero Exit Code detected
```

</details>

**Comment by SwaySway** [comment]
This env cache param is related to amplify console. Transferring to their repo for more visibility.
