### ISSUE TITLE
Amplify Admin UI Deployment - auth headless is missing the following inputParams googleClientId, facebookAppId. 

### ISSUE THREAD

**Issue by matthewmichel** [aws-amplify/amplify-cli#7760]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.17.0

### Amplify CLI Version

5.1.2

### What operating system are you using?

Mac

### Amplify Categories

Not applicable

### Amplify Commands

pull

### Describe the bug

I'm attempting to "Enable DataStore and deploy" within the Amplify Admin UI Console under the "Data" section. I have auth and api (GraphQL) plugins enabled. Social logins were set up with the amplify cli and show up with the correct key/secret pairs in Cognito, but I'm getting the following error from the Admin UI upon deployment:

`auth headless is missing the following inputParams googleClientId, facebookAppId`

Here's the full error code:

```
Command failed with exit code 1: /root/.amplify/bin/amplify pull --amplify {"envName":"dev","defaultEditor":"code","appId":"d3pxrgvb8lbj8z"} --providers {"awscloudformation":{"configLevel":"project","useProfile":true,"profileName":"amplify-backend-processor"}} --frontend {"frontend":"javascript","framework":"react","config":{"SourceDir":"src","DistributionDir":"build","BuildCommand":"npm run-script build","StartCommand":"npm run-script start"}} --yes
- Fetching updates to backend environment: dev from the cloud.
✔ Successfully pulled backend environment dev from the cloud.
✖ There was an error initializing your environment.
[0mAmplify AppID found: d3pxrgvb8lbj8z. Amplify App name is: flourishmobile[0m
[0mBackend environment dev found in Amplify Console app: flourishmobile[0m
[31mFailed to pull the backend.[39m
[31mauth headless is missing the following inputParams googleClientId, facebookAppId[39m
[0mError: auth headless is missing the following inputParams googleClientId, facebookAppId[0m
[0m    at updateConfigOnEnvInit (/snapshot/node_modules/amplify-category-auth/lib/provider-utils/awscloudformation/index.js:92:23)[0m
[0m    at /snapshot/node_modules/amplify-category-auth/lib/index.js:229:34[0m
[0m    at /snapshot/node_modules/promise-sequential/index.js:16:18[0m
[0m    at runMicrotasks (<anonymous>)[0m
[0m    at processTicksAndRejections (internal/process/task_queues.js:97:5)[0m
```

I can't find a place to add environment variables within the Amplify Console because my project is a react native project without a frontend deployment.

I tried running `amplify update auth` and readding my keys for facebook and google sign ins, but still had the same issue in the Admin UI Console after `amplify push`.

### Expected behavior

I expected to be able to deploy changes via the Amplify Admin UI Console. Instead, deployments are failing because it can't seem to pull in my social login keys.

### Reproduction steps

1. Initialize Amplify
2. Add Auth with social login
3. Add API (GraphQL)
4. Enable Admin UI
5. Try to "Enable DataStore and deploy" under the "Data" section

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line
Command failed with exit code 1: /root/.amplify/bin/amplify pull --amplify {"envName":"dev","defaultEditor":"code","appId":"d3pxrgvb8lbj8z"} --providers {"awscloudformation":{"configLevel":"project","useProfile":true,"profileName":"amplify-backend-processor"}} --frontend {"frontend":"javascript","framework":"react","config":{"SourceDir":"src","DistributionDir":"build","BuildCommand":"npm run-script build","StartCommand":"npm run-script start"}} --yes
- Fetching updates to backend environment: dev from the cloud.
✔ Successfully pulled backend environment dev from the cloud.
✖ There was an error initializing your environment.
[0mAmplify AppID found: d3pxrgvb8lbj8z. Amplify App name is: flourishmobile[0m
[0mBackend environment dev found in Amplify Console app: flourishmobile[0m
[31mFailed to pull the backend.[39m
[31mauth headless is missing the following inputParams googleClientId, facebookAppId[39m
[0mError: auth headless is missing the following inputParams googleClientId, facebookAppId[0m
[0m    at updateConfigOnEnvInit (/snapshot/node_modules/amplify-category-auth/lib/provider-utils/awscloudformation/index.js:92:23)[0m
[0m    at /snapshot/node_modules/amplify-category-auth/lib/index.js:229:34[0m
[0m    at /snapshot/node_modules/promise-sequential/index.js:16:18[0m
[0m    at runMicrotasks (<anonymous>)[0m
[0m    at processTicksAndRejections (internal/process/task_queues.js:97:5)[0m

```

</details>

**Comment by SwaySway** [comment]
Looks like this might be an admin ui issue, transferring to their repo for more visibility.
