### ISSUE TITLE
Error: auth headless is missing the following inputParams userPoolId, webClientId, nativeClientId, identityPoolId

### ISSUE THREAD

**Issue by dperconti** [aws-amplify/amplify-cli#7855]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d39gw7seizrgo

### Region

us-east-1

### Amplify Console feature

Backend builds

### Describe the bug

Walking through `amplify init`. 

```
$ amplify init
> succeeds
$ amplify add auth
> succeeds
$ amplify add api
> succeeds
```

Then, when adding the frontend by connecting a github branch, I receive the following error:

```
2021-07-26T18:58:55.226Z [INFO]: Git SSH Key acquired
2021-07-26T18:58:55.302Z [INFO]: # Cloning repository: git@github.com:altum-education/altum-web.git
2021-07-26T18:58:55.312Z [INFO]: Agent pid 135
2021-07-26T18:58:55.352Z [INFO]: Identity added: /root/.ssh/git_rsa (/root/.ssh/git_rsa)
2021-07-26T18:58:55.707Z [INFO]: Cloning into 'altum-web'...
2021-07-26T18:58:56.085Z [INFO]: Warning: Permanently added the RSA host key for IP address '140.82.112.3' to the list of known hosts.
2021-07-26T18:58:57.450Z [INFO]: # Checking for Git submodules at: /codebuild/output/src524776023/src/altum-web/.gitmodules
2021-07-26T18:58:57.452Z [WARNING]: !Error: ENOENT: no such file or directory, open '/codebuild/output/src524776023/src/altum-web/amplify.yml'
2021-07-26T18:58:57.470Z [INFO]: # Retrieving environment cache...
2021-07-26T18:58:57.510Z [INFO]: # Retrieved environment cache
2021-07-26T18:58:57.510Z [INFO]: ---- Setting Up SSM Secrets ----
2021-07-26T18:58:57.510Z [WARNING]: SSM params {"Path":"/amplify/d39gw7seizrgo/dev/","WithDecryption":true}
2021-07-26T18:58:57.567Z [INFO]: # Ensuring NPM package '@aws-amplify/cli' is version: 'latest'
2021-07-26T18:59:03.526Z [INFO]: # Patching NPM package '@aws-amplify/cli' from 4.29.4 to 5.1.2...
2021-07-26T18:59:57.664Z [INFO]: # Done patching NPM package '@aws-amplify/cli'
2021-07-26T19:00:07.756Z [INFO]: ## Starting Backend Build
                                 # Starting phase: build
2021-07-26T19:00:17.107Z [INFO]: [0mAmplify AppID found: d39gw7seizrgo. Amplify App name is: Altum[0m
2021-07-26T19:00:17.225Z [INFO]: [0mBackend environment dev found in Amplify Console app: Altum[0m
2021-07-26T19:00:18.129Z [WARNING]: - Fetching updates to backend environment: dev from the cloud.
2021-07-26T19:00:18.464Z [WARNING]: ✔ Successfully pulled backend environment dev from the cloud.
2021-07-26T19:00:18.511Z [WARNING]: ✖ There was an error initializing your environment.
2021-07-26T19:00:18.513Z [INFO]: [31mFailed to pull the backend.[39m
2021-07-26T19:00:18.515Z [INFO]: [31mauth headless is missing the following inputParams userPoolId, webClientId, nativeClientId, identityPoolId[39m
2021-07-26T19:00:18.524Z [INFO]: [0mError: auth headless is missing the following inputParams userPoolId, webClientId, nativeClientId, identityPoolId[0m
                                 [0m    at ensureHeadlessParameters (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/provider-utils/awscloudformation/import/index.ts:1287:11)[0m
                                 [0m    at Object.headlessImport (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/provider-utils/awscloudformation/import/index.ts:1144:40)[0m
                                 [0m    at importedAuthEnvInit (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/provider-utils/awscloudformation/import/index.ts:921:18)[0m
                                 [0m    at processTicksAndRejections (internal/process/task_queues.js:97:5)[0m
                                 [0m    at updateConfigOnEnvInit (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/provider-utils/awscloudformation/index.js:50:72)[0m
                                 [0m    at /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/index.js:306:22[0m
2021-07-26T19:00:18.542Z [ERROR]: !!! Build failed
2021-07-26T19:00:18.542Z [ERROR]: !!! Non-Zero Exit Code detected
2021-07-26T19:00:18.542Z [INFO]: # Starting environment caching...
2021-07-26T19:00:18.543Z [INFO]: # Environment caching completed
Terminating logging...

```

### Expected behavior

I would expect a successful deployment of an amplify app when following the getting started guide. 

### Reproduction steps

Walk through this guide:
https://docs.amplify.aws/start/q/integration/react

Error occurs when connecting a github branch for the frontend.

**Comment by josefaidt** [comment]
Hey @dperconti before adding hosting for your frontend did you run `amplify push`?

**Comment by dperconti** [comment]
@josefaidt I did not. I went directly to adding auth, API, & connecting a branch. Let me try with a clean implementation to see if that resolves the issue and I will get back to you.

**Comment by dperconti** [comment]
I was able to get around this by pushing before adding hosting 👍
