### ISSUE TITLE
Android lex bot creation for the BookTrip sample bot does not work

### ISSUE THREAD

**Issue by minbi** [aws-amplify/amplify-cli#790]
Platform:
android

CLI versions:
0.1.34 and 0.1.44

Repro:
```
amplify init
amplify add interactions
amplify push
```

Logs:
```
2019-01-29 13:52:34.906 22917-22917/com.amazonaws.sample.lex E/Lex: InteractiveVoiceViewAdapter: Interaction error
    com.amazonaws.services.lexrts.model.DependencyFailedException: Invalid Bot Configuration: Lex is unable to assume the Service-Linked Role AWSServiceRoleForLexBots necessary to synthesize a speech response for this request.  Please confirm that this role exists within your account, or create it with the IAM Console or by using the CreateServiceLinkedRole operation in the IAM SDK. (Service: AmazonLexRuntime; Status Code: 424; Error Code: DependencyFailedException; Request ID: 303dbe1d-2410-11e9-bd00-e101dcc15f33)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:730)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:405)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
        at com.amazonaws.services.lexrts.AmazonLexRuntimeClient.invoke(AmazonLexRuntimeClient.java:660)
        at com.amazonaws.services.lexrts.AmazonLexRuntimeClient.postContent(AmazonLexRuntimeClient.java:457)
        at com.amazonaws.mobileconnectors.lex.interactionkit.InteractionClient$2.run(InteractionClient.java:411)
        at java.lang.Thread.run(Thread.java:764)
2019-01-29 13:52:34.910 22917-22917/com.amazonaws.sample.lex E/VoiceActivity: Error: Error from Bot
    com.amazonaws.services.lexrts.model.DependencyFailedException: Invalid Bot Configuration: Lex is unable to assume the Service-Linked Role AWSServiceRoleForLexBots necessary to synthesize a speech response for this request.  Please confirm that this role exists within your account, or create it with the IAM Console or by using the CreateServiceLinkedRole operation in the IAM SDK. (Service: AmazonLexRuntime; Status Code: 424; Error Code: DependencyFailedException; Request ID: 303dbe1d-2410-11e9-bd00-e101dcc15f33)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:730)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:405)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
        at com.amazonaws.services.lexrts.AmazonLexRuntimeClient.invoke(AmazonLexRuntimeClient.java:660)
        at com.amazonaws.services.lexrts.AmazonLexRuntimeClient.postContent(AmazonLexRuntimeClient.java:457)
        at com.amazonaws.mobileconnectors.lex.interactionkit.InteractionClient$2.run(InteractionClient.java:411)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by minbi** [comment]
Confirmed with @elorzafe that a configuration created in the JS flow worked in Android. There is something wrong in the native flow resource creation. @kaustavghosh06

**Comment by kaustavghosh06** [comment]
Fixed the issue and merged the PR for the same. It's in the pipeline and scheduled for a release tomorrow.
