### ISSUE TITLE
Unable to create custom interaction with Lambda. TypeError: Lambda is not a constructor

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/amplify-cli#7906]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

v16.5.0

### Amplify CLI Version

v5.3.0

### What operating system are you using?

Mac

### Amplify Categories

interactions

### Amplify Commands

add

### Describe the bug

When creating an interaction from scratch CLI fails to create when selecting "AWS Lambda Function" to fulfill the intent.

### Expected behavior

CLI should create interaction

### Reproduction steps

1. `amplify add interaction`
2. Choose "Start from scratch" instead of choosing a sample
3. step through prompts
4. Choose "AWS Lambda Function" when asked "How would you like the intent to be fulfilled?"
5. observe error `TypeError: Lambda is not a constructor`

```shell
> amplify add interaction
Using service: Lex, provided by: awscloudformation

Welcome to the Amazon Lex chatbot wizard
You will be asked a series of questions to help determine how to best construct your chatbot.

? Provide a friendly resource name that will be used to label this category in the project: lexbe5bf0d2
? Would you like to start with a sample chatbot or start from scratch? Start from scratch
? Enter a name for your bot: mybot
? Choose an output voice: None. This is only a text based application.
? After how long should the session timeout (in minutes)? 5
? Please indicate if your use of this bot is subject to the Children's Online Privacy Protection Act (COPPA).
Learn more: https://www.ftc.gov/tips-advice/business-center/guidance/complying-coppa-frequently-asked-questions No

First create an intent for your new chatbot. An intent represents an action that the user wants to perform.

? Give a unique name for the new intent: myintent
? Enter a sample utterance (spoken or typed phrase that invokes your intent. e.g. Book a hotel) hotel
? Would you like to add another utterance? No

Now, add a slot to your intent. A slot is data the user must provide to fulfill the intent.

? Enter a name for your slot (e.g. Location) location
? Would you like to choose an Amazon built-in slot type, a slot type you've already made, or create a new slot type? Amazon built-in slot t
ype
? Choose a slot type: AMAZON.AT_CITY
? Enter a prompt for your slot (e.g. What city?) what city?
? Should this slot be required? Yes
? Would you like to add another slot? No
? Would you like to add a confirmation prompt to your intent? No
? How would you like the intent to be fulfilled? AWS Lambda Function
TypeError: Lambda is not a constructor
    at Object.getLambdaFunctions (/Users/josef/.config/yarn/global/node_modules/amplify-provider-awscloudformation/src/utility-functions.js:160:31)
    at AmplifyToolkit.executeProviderUtils [as _executeProviderUtils] (/Users/josef/.config/yarn/global/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/execute-provider-utils.ts:7:46)
    at askLambda (/Users/josef/.config/yarn/global/node_modules/amplify-category-interactions/provider-utils/awscloudformation/service-walkthroughs/lex-walkthrough.js:699:49)
    at addIntent (/Users/josef/.config/yarn/global/node_modules/amplify-category-interactions/provider-utils/awscloudformation/service-walkthroughs/lex-walkthrough.js:430:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at configure (/Users/josef/.config/yarn/global/node_modules/amplify-category-interactions/provider-utils/awscloudformation/service-walkthroughs/lex-walkthrough.js:299:20)
    at Object.executeAmplifyCommand (/Users/josef/.config/yarn/global/node_modules/amplify-category-interactions/index.js:70:3)
    at executePluginModuleCommand (/Users/josef/.config/yarn/global/node_modules/@aws-amplify/cli/src/execution-manager.ts:177:3)
    at Object.executeCommand (/Users/josef/.config/yarn/global/node_modules/@aws-amplify/cli/src/execution-manager.ts:29:5)
    at Object.run (/Users/josef/.config/yarn/global/node_modules/@aws-amplify/cli/src/index.ts:151:5)
There was an error adding the interactions resource
```

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by AlessandroVol23** [comment]
I have exactly the same issue

**Comment by gabehollombe-aws** [comment]
I can confirm this issue exists for me as well, using Amplify CLI version 5.4.0 on macOS.
