### ISSUE TITLE
Migrate project to another AWS Account

### ISSUE THREAD

**Issue by drey-rotation** [aws-amplify/amplify-cli#7910]
This issue has been automatically locked since there hasn't been any recent activity after it was closed. Please open a [new issue](https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=&template=1.bug_report.yaml) for related bugs.

Looking for a help forum? We recommend joining the [Amplify Community Discord server](https://discord.com/invite/amplify) `*-help` channels for those types of questions.

_Originally posted by @github-actions[bot] in https://github.com/aws-amplify/amplify-cli/issues/3350#issuecomment-847483831_

**Comment by drey-rotation** [comment]
Just saw this post and wanted to point out that you can easily re-create resources in a different account. Here is what I did:

1. Clone repo to new folder
2. amplify init
  - Select an AWS Profile that will connect to the new account.  I use ssh and my keys are in ~/.ssh/credentials file.
  - Do not use an existing environment. 
 3. Amplify updates the amplify/team-provider-info.json file with the new environment name. If you then do an "amplify env list" command there should be an additional environment that is connected to the account of the profile.

**Comment by jhockett** [comment]
Thanks for the helpful information @drey-rotation! I think we should add a note in the docs about this. The task is tracked in this docs [issue](https://github.com/aws-amplify/docs/issues/2959).

**Comment by flozender** [comment]
Hi, may I pick this up?

**Comment by irSteve** [comment]
Hi, if you have auth, api, and/or functions defined, this does not work. In this case it is failing to find an API defined in the previous account/repo.

```pathnext@PathNexts-MacBook-Pro bisbee % amplify init
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the environment bisbeedev
Using default provider  awscloudformation
? Select the authentication method you want to use: AWS profile

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

? Please choose the profile you want to use bisbee
Adding backend environment bisbeedev to AWS Amplify app: dljlu2bo5h3gz
⠇ Initializing project in the cloud...

CREATE_IN_PROGRESS amplify-hpebigtime-bisbeedev-234736 AWS::CloudFormation::Stack Wed Mar 16 2022 23:47:47 GMT-0700 (Pacific Daylight Time) User Initiated             
CREATE_IN_PROGRESS DeploymentBucket                    AWS::S3::Bucket            Wed Mar 16 2022 23:47:50 GMT-0700 (Pacific Daylight Time)                            
CREATE_IN_PROGRESS AuthRole                            AWS::IAM::Role             Wed Mar 16 2022 23:47:50 GMT-0700 (Pacific Daylight Time)                            
CREATE_IN_PROGRESS UnauthRole                          AWS::IAM::Role             Wed Mar 16 2022 23:47:51 GMT-0700 (Pacific Daylight Time)                            
CREATE_IN_PROGRESS AuthRole                            AWS::IAM::Role             Wed Mar 16 2022 23:47:51 GMT-0700 (Pacific Daylight Time) Resource creation Initiated
CREATE_IN_PROGRESS DeploymentBucket                    AWS::S3::Bucket            Wed Mar 16 2022 23:47:52 GMT-0700 (Pacific Daylight Time) Resource creation Initiated
⠙ Initializing project in the cloud...

CREATE_IN_PROGRESS UnauthRole AWS::IAM::Role Wed Mar 16 2022 23:47:52 GMT-0700 (Pacific Daylight Time) Resource creation Initiated
⠇ Initializing project in the cloud...

CREATE_COMPLETE AuthRole   AWS::IAM::Role Wed Mar 16 2022 23:48:06 GMT-0700 (Pacific Daylight Time) 
CREATE_COMPLETE UnauthRole AWS::IAM::Role Wed Mar 16 2022 23:48:07 GMT-0700 (Pacific Daylight Time) 
⠇ Initializing project in the cloud...

CREATE_COMPLETE DeploymentBucket                    AWS::S3::Bucket            Wed Mar 16 2022 23:48:13 GMT-0700 (Pacific Daylight Time) 
CREATE_COMPLETE amplify-hpebigtime-bisbeedev-234736 AWS::CloudFormation::Stack Wed Mar 16 2022 23:48:15 GMT-0700 (Pacific Daylight Time) 
✔ Successfully created initial AWS cloud resources for deployments.
✔ Initialized provider successfully.
✖ There was an error initializing your environment.
Error: File at path: '/Users/pathnext/src/virtuosity/bisbee/amplify/backend/auth/hpebigtimefbc9d021/build/parameters.json' does not exist
    at Function.JSONUtilities.readJson (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/jsonUtilities.ts:25:15)
    at StateManager.getData (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/state-manager/stateManager.ts:399:32)
    at StateManager.getResourceParametersJson (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/state-manager/stateManager.ts:147:17)
    at ensureAmplifyMetaFrontendConfig (/usr/local/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/on-category-outputs-change.ts:84:55)
    at AmplifyToolkit.onCategoryOutputsChange [as _onCategoryOutputsChange] (/usr/local/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/on-category-outputs-change.ts:18:5)
    at initializeEnv (/usr/local/lib/node_modules/@aws-amplify/cli/src/initialize-env.ts:103:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at onSuccess (/usr/local/lib/node_modules/@aws-amplify/cli/src/init-steps/s9-onSuccess.ts:73:3)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/src/commands/init.ts:30:7)
    at Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/index.ts:373:5)
    at executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:178:3)
    at executeCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:30:5)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/src/index.ts:205:5)```

**Comment by NairiAreg** [comment]
Why is this issue closed?
It's nearly impossible to migrate from one account to another
The comments suggestions won't work
