### ISSUE TITLE
Using 3rd party libraries when mocking python lambda

### ISSUE THREAD

**Issue by martinmeinke** [aws-amplify/amplify-cli#7924]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

5.3.0

### What operating system are you using?

Ubuntu 20.04

### Amplify Categories

function

### Amplify Commands

Not applicable

### Describe the bug

I try to mock a python lambda function which uses the numpy library.

I added `import numpy` 
to the generated `src/index.py`.

I modified the generated `Pipfile` to include
```
[packages]
src = {editable = true, path = "./src"}
numpy = "*"
```

Then I ran:
`amplify mock function testampli59bb9ee0`

### Expected behavior

Local pipenv installs numpy and I can run the lambda using numpy features.

### Reproduction steps

1. `amplify init`
2. `amplify add function`
3. modify `Pipfile` to list numpy as a dependency
4. modify `index.py` to import numpy
5. `amplify mock function <>`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
martin@simba:/tmp/testampli/amplify/backend/function/testampli59bb9ee0$ amplify mock function testampli59bb9ee0
? Provide the path to the event JSON object relative to /tmp/testampli/amplify/backend/function/testampli59bb9ee0 src/event.json
Ensuring latest function changes are built...
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✔ Success! 
Updated Pipfile.lock (bbddef)!
Installing dependencies from Pipfile.lock (bbddef)...
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 1/1 — 00:00:07
Starting execution...
Warning: the environment variable LANG is not set!
We recommend setting this in ~/.profile (or equivalent) for proper expected behavior.
Creating a virtualenv for this project...
Pipfile: /tmp/testampli/amplify/backend/function/testampli59bb9ee0/Pipfile
Using /usr/bin/python3.8 (3.8.10) to create virtualenv...
⠇ Creating virtual environment...created virtual environment CPython3.8.10.final.0-64 in 431ms
  creator CPython3Posix(dest=/home/martin/.local/share/virtualenvs/testampli59bb9ee0-tGTOLLXm, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/martin/.local/share/virtualenv)
    added seed packages: pip==21.2.2, setuptools==57.4.0, wheel==0.36.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator

✔ Successfully created virtual environment! 
Virtualenv location: /home/martin/.local/share/virtualenvs/testampli59bb9ee0-tGTOLLXm
Traceback (most recent call last):
  File "/home/martin/.amplify/lib/amplify-python-function-runtime-provider/shim/shim.py", line 35, in <module>
    main(sys.argv[1:])
  File "/home/martin/.amplify/lib/amplify-python-function-runtime-provider/shim/shim.py", line 22, in main
    spec.loader.exec_module(handlerModule)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/testampli/amplify/backend/function/testampli59bb9ee0/src/index.py", line 2, in <module>
    import numpy
ModuleNotFoundError: No module named 'numpy'
testampli59bb9ee0 failed with the following error:
Error: Command failed with exit code 1: pipenv run python3 /home/martin/.amplify/lib/amplify-python-function-runtime-provider/shim/shim.py /tmp/testampli/amplify/backend/function/testampli59bb9ee0/src/index.py handler
Warning: the environment variable LANG is not set!
We recommend setting this in ~/.profile (or equivalent) for proper expected behavior.
Creating a virtualenv for this project...
Pipfile: /tmp/testampli/amplify/backend/function/testampli59bb9ee0/Pipfile
Using /usr/bin/python3.8 (3.8.10) to create virtualenv...
⠇ Creating virtual environment...created virtual environment CPython3.8.10.final.0-64 in 431ms
  creator CPython3Posix(dest=/home/martin/.local/share/virtualenvs/testampli59bb9ee0-tGTOLLXm, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/martin/.local/share/virtualenv)
    added seed packages: pip==21.2.2, setuptools==57.4.0, wheel==0.36.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator

✔ Successfully created virtual environment! 
Virtualenv location: /home/martin/.local/share/virtualenvs/testampli59bb9ee0-tGTOLLXm
Traceback (most recent call last):
  File "/home/martin/.amplify/lib/amplify-python-function-runtime-provider/shim/shim.py", line 35, in <module>
    main(sys.argv[1:])
  File "/home/martin/.amplify/lib/amplify-python-function-runtime-provider/shim/shim.py", line 22, in main
    spec.loader.exec_module(handlerModule)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/testampli/amplify/backend/function/testampli59bb9ee0/src/index.py", line 2, in <module>
    import numpy
ModuleNotFoundError: No module named 'numpy'
    at makeError (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.pythonInvoke (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-python-function-runtime-provider/src/util/invokeUtil.ts:33:22)
    at Object.timeConstrainedInvoker (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/src/func/index.ts:67:12)
    at Object.start (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/src/func/index.ts:48:20)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/src/commands/mock/function.ts:14:5)
    at Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/src/amplify-plugin-index.ts:8:3)
    at executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:177:3)
    at Object.executeCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:29:5)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/src/index.ts:151:5) {
  shortMessage: 'Command failed with exit code 1: pipenv run python3 /home/martin/.amplify/lib/amplify-python-function-runtime-provider/shim/shim.py /tmp/testampli/amplify/backend/function/testampli59bb9ee0/src/index.py handler',
  command: 'pipenv run python3 /home/martin/.amplify/lib/amplify-python-function-runtime-provider/shim/shim.py /tmp/testampli/amplify/backend/function/testampli59bb9ee0/src/index.py handler',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'Warning: the environment variable LANG is not set!\n' +
    'We recommend setting this in ~/.profile (or equivalent) for proper expected behavior.\n' +
    'Creating a virtualenv for this project...\n' +
    'Pipfile: /tmp/testampli/amplify/backend/function/testampli59bb9ee0/Pipfile\n' +
    'Using /usr/bin/python3.8 (3.8.10) to create virtualenv...\n' +
    '\r⠋ Creating virtual environment...\b\r⠙ Creating virtual environment...\b\r⠹ Creating virtual environment...\b\r⠸ Creating virtual environment...\b\r⠼ Creating virtual environment...\b\r⠴ Creating virtual environment...\b\r⠦ Creating virtual environment...\b\r⠧ Creating virtual environment...\b\r⠇ Creating virtual environment...created virtual environment CPython3.8.10.final.0-64 in 431ms\n' +
    '  creator CPython3Posix(dest=/home/martin/.local/share/virtualenvs/testampli59bb9ee0-tGTOLLXm, clear=False, no_vcs_ignore=False, global=False)\n' +
    '  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/martin/.local/share/virtualenv)\n' +
    '    added seed packages: pip==21.2.2, setuptools==57.4.0, wheel==0.36.2\n' +
    '  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator\n' +
    '\n' +
    '\b✔ Successfully created virtual environment! \n' +
    'Virtualenv location: /home/martin/.local/share/virtualenvs/testampli59bb9ee0-tGTOLLXm\n' +
    'Traceback (most recent call last):\n' +
    '  File "/home/martin/.amplify/lib/amplify-python-function-runtime-provider/shim/shim.py", line 35, in <module>\n' +
    '    main(sys.argv[1:])\n' +
    '  File "/home/martin/.amplify/lib/amplify-python-function-runtime-provider/shim/shim.py", line 22, in main\n' +
    '    spec.loader.exec_module(handlerModule)\n' +
    '  File "<frozen importlib._bootstrap_external>", line 848, in exec_module\n' +
    '  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed\n' +
    '  File "/tmp/testampli/amplify/backend/function/testampli59bb9ee0/src/index.py", line 2, in <module>\n' +
    '    import numpy\n' +
    "ModuleNotFoundError: No module named 'numpy'",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
Finished execution.


```

</details>

**Comment by akshbhu** [comment]
Hi @martinmeinke 

I executed the same steps and it is working for me. The one problem I see in error logs is this 
```
Warning: the environment variable LANG is not set!
We recommend setting this in ~/.profile (or equivalent) for proper expected behavior.
```

Can you try this and again try to mock this function?

Let me know if this works for you?

**Comment by martinmeinke** [comment]
Explicitly setting

```
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
```

in my `.zshrc` does not solve the problem.

**Comment by akshbhu** [comment]
Hi @martinmeinke 

One more thing to debug is , When you do ```amplify mock function``` , pipenv creates virtual environment to install project dependencies in your local. : **/home/martin/.local/share/virtualenvs/testampli59bb9ee0-tGTOLLXm**. Can you check on this path under sitePackage if numpy is present?

**Comment by martinmeinke** [comment]
```
martin@simba:<>$ ll site-packages/
total 60
drwxrwxr-x 11 martin martin 4096 Aug 12 04:41 ./
drwxrwxr-x  3 martin martin 4096 Aug 10 01:40 ../
drwxrwxr-x  2 martin martin 4096 Aug 10 01:40 _distutils_hack/
-rw-rw-r--  1 martin martin  152 Aug 10 01:40 distutils-precedence.pth
drwxrwxr-x  4 martin martin 4096 Aug 10 01:40 pip/
drwxrwxr-x  2 martin martin 4096 Aug 10 01:40 pip-21.2.2.dist-info/
-rw-rw-r--  1 martin martin    0 Aug 10 01:40 pip-21.2.2.virtualenv
drwxrwxr-x  5 martin martin 4096 Aug 10 01:40 pkg_resources/
drwxrwxr-x  2 martin martin 4096 Aug 12 04:41 __pycache__/
drwxrwxr-x  6 martin martin 4096 Aug 10 01:40 setuptools/
drwxrwxr-x  2 martin martin 4096 Aug 10 01:40 setuptools-57.4.0.dist-info/
-rw-rw-r--  1 martin martin    0 Aug 10 01:40 setuptools-57.4.0.virtualenv
-rw-rw-r--  1 martin martin   18 Aug 10 01:40 _virtualenv.pth
-rw-rw-r--  1 martin martin 5662 Aug 10 01:40 _virtualenv.py
drwxrwxr-x  4 martin martin 4096 Aug 10 01:40 wheel/
drwxrwxr-x  2 martin martin 4096 Aug 10 01:40 wheel-0.36.2.dist-info/
-rw-rw-r--  1 martin martin    0 Aug 10 01:40 wheel-0.36.2.virtualenv
```

**Comment by josefaidt** [comment]
Hey @martinmeinke :wave: just wanted to follow up and see if you are still experiencing this issue with the [latest version of the CLI](https://github.com/aws-amplify/amplify-cli/releases/tag/v6.3.1)? I am also unable to reproduce following the provided steps.

Here is the output of my `amplify mock function` execution

```console
> amplify mock function
⚠️ Amplify command hooks are disabled in the current execution environment.
⚠️ See https://docs.amplify.aws/cli/usage/command-hooks/ for more information.
? Provide the path to the event JSON object relative to /Users/josef/Documents/projects/aws-amplify/reproductions/7924/ampl
ify/backend/function/7924f5e86d1a src/event.json
Ensuring latest function changes are built...
Creating a virtualenv for this project...
Pipfile: /Users/josef/Documents/projects/aws-amplify/reproductions/7924/amplify/backend/function/7924f5e86d1a/Pipfile
Using /usr/bin/python3 (3.8.2) to create virtualenv...
⠹ Creating virtual environment...created virtual environment CPython3.8.2.final.0-64 in 874ms
  creator CPython3macOsFramework(dest=/Users/josef/.local/share/virtualenvs/7924f5e86d1a-q9HUaz1q, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/josef/Library/Application Support/virtualenv)
    added seed packages: pip==21.2.4, setuptools==58.1.0, wheel==0.37.0
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

✔ Successfully created virtual environment! 
Virtualenv location: /Users/josef/.local/share/virtualenvs/7924f5e86d1a-q9HUaz1q
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✔ Success! 
Updated Pipfile.lock (bbddef)!
Installing dependencies from Pipfile.lock (bbddef)...
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 2/2 — 00:00:12
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
Starting execution...


received event:
{'test': 'event'}
{"statusCode": 200, "headers": {"Access-Control-Allow-Headers": "*", "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Methods": "OPTIONS,POST,GET"}, "body": "\"Hello from your new Amplify Python lambda!\""}
Result:
{
  "statusCode": 200,
  "headers": {
    "Access-Control-Allow-Headers": "*",
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "OPTIONS,POST,GET"
  },
  "body": "\"Hello from your new Amplify Python lambda!\""
}
Finished execution.
```
