### ISSUE TITLE
Amplify LambdaInternal throttle

### ISSUE THREAD

**Issue by gakinson** [aws-amplify/amplify-cli#7932]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v12.22.1

### Amplify CLI Version

5.3.0

### What operating system are you using?

Mac

### Amplify Categories

function

### Amplify Commands

push

### Describe the bug

Hello,

I am trying to push all the latest changes to my environment and sync up with what the rest of the team has and I am getting endless throttle exceptions.

It seems to be something related with legacy lambda layer functions.

I just keep getting the below error over and over.

```
CREATE_FAILED      LambdaLayerPermissionPrivateLegacy63  AWS::Lambda::LayerVersionPermission Tue Aug 10 2021 17:21:21 GMT-0700 (Pacific Daylight Time) Rate exceeded (Service: AWSLambdaInternal; Status Code: 400; Error Code: ThrottlingException; Request ID: d6273ab7-afc3-4d6f-b8a6-e5e33bf28b9b; Proxy: null)
```

I am basically blocked on development unless I create a brand new environment.

### Expected behavior

amplify push works

### Reproduction steps

amplify push

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by akshbhu** [comment]
Hi @gakinson 

From the error ``` LambdaLayerPermissionPrivateLegacy63  AWS::Lambda::LayerVersionPermission Tue Aug 10 2021 17:21:21 GMT-0700 (Pacific Daylight Time) Rate exceeded (Service: AWSLambdaInternal; Status Code: 400; Error Code: ThrottlingException;``` 

It seems you have a lot of stale layers in the project as version is close to 63. Can you try to remove some of the stale layers using ```amplify remove function`` and then selecting those stale layers.

Let me know if this works for you?

**Comment by gakinson** [comment]
I got another error:

```
Cannot read property 'filter' of undefined
TypeError: Cannot read property 'filter' of undefined
    at /Users/geoffreykinson/.nvm/versions/node/v12.22.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/provider-utils/awscloudformation/utils/layerHelpers.ts:248:33
    at Array.filter (<anonymous>)
    at Object.getLambdaFunctionsDependentOnLayerFromMeta (/Users/geoffreykinson/.nvm/versions/node/v12.22.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/provider-utils/awscloudformation/utils/layerHelpers.ts:245:45)
    at Object.removeWalkthrough (/Users/geoffreykinson/.nvm/versions/node/v12.22.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/removeLayerWalkthrough.ts:25:43)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Object.run (/Users/geoffreykinson/.nvm/versions/node/v12.22.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/commands/function/remove.ts:30:29)
    at Object.executeAmplifyCommand (/Users/geoffreykinson/.nvm/versions/node/v12.22.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/index.ts:251:3)
    at executePluginModuleCommand (/Users/geoffreykinson/.nvm/versions/node/v12.22.1/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:177:3)
    at Object.executeCommand (/Users/geoffreykinson/.nvm/versions/node/v12.22.1/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:29:5)
    at Object.run (/Users/geoffreykinson/.nvm/versions/node/v12.22.1/lib/node_modules/@aws-amplify/cli/src/index.ts:151:5)


```

**Comment by akshbhu** [comment]
Hi @gakinson 

Can you share  ```<root>/amplify/backend/amplify-meta.json```  by redacting any secret info?

**Comment by gakinson** [comment]
My workaround was to go into my lambda layer in console and delete them manually (used script actually), then do amplify env checkout, then modified the lambda layer, then did a push.

**Comment by josefaidt** [comment]
Hey @gakinson :wave: can you try running `amplify remove function` to remove some of the older layer versions?

**Comment by josefaidt** [comment]
Closing due to inactivity. @gakinson if you are still experiencing this issue with the [latest version of the CLI](https://github.com/aws-amplify/amplify-cli/releases/tag/v7.6.3) please reply back to this thread and we can re-open to investigate further 🙂
