### ISSUE TITLE
Next.js deploy failed: Error: CloudFront input failed validation. Could not find next.js pages for "_next/image*"

### ISSUE THREAD

**Issue by dn-l** [aws-amplify/amplify-cli#7957]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

Deploy Next.js app through the CI

### Amplify CLI Version

5.3.0

### What operating system are you using?

Mac

### Amplify Categories

hosting

### Amplify Commands

Not applicable

### Describe the bug

```
2021-08-13T23:01:38.894Z [INFO]: Starting SSR Build...
2021-08-13T23:03:09.562Z [ERROR]: Error: CloudFront input failed validation. Could not find next.js pages for "_next/image*"
                                  at NextjsComponent.validatePathPatterns (/root/.//node_modules/@sls-next/-component/dist/component.js:97:19)
                                  at NextjsComponent.<anonymous> (/root/.//node_modules/@sls-next/-component/dist/component.js:346:18)
                                  at Generator.next (<anonymous>)
                                  at fulfilled (/root/.//node_modules/@sls-next/-component/dist/component.js:5:58)
                                  at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-08-13T23:03:09.563Z [ERROR]: [G[?25h[G[J
                                  70s › dv7gx4tsginir › Error: CloudFront input failed validation. Could not find next.js pages for "_next/image*"
                                  [G[?25h
Terminating logging...
```

### Expected behavior

Successful build

### Reproduction steps

1. git commit
2. git push

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

I'm not using `next/image`. Anything I should check?

**Comment by dn-l** [comment]
Tried to redeploy my old successful build - also failing

**Comment by edwardfoyle** [comment]
@dn-l based on the stacktrace above and the repro steps, this doesn't appear to be an Amplify CLI issue. Is this happening when deploying in Amplify Console? What CLI command is triggering the build failure? Are you able to build the next.js pages without using the CLI?
