### ISSUE TITLE
I did amplify pull, but can't change environment

### ISSUE THREAD

**Issue by tasugi** [aws-amplify/amplify-cli#7973]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

v14.15.3

### Amplify CLI Version

5.3.0

### What operating system are you using?

Mac

### Amplify Categories

auth, storage, function, api

### Amplify Commands

pull

### Describe the bug

Our repository includes only `aws-exports.js` and does not have backend configuration( backend configuration is managed in another repository).

With the current latest CLI, I did `amplify pull` to change environment( we have two environments, production and staging) and got the message below.

```
% amplify pull
Amplify AppID found: xxx. Amplify App name is: our-app
Backend environment production found in Amplify Console app: our-app

Added backend environment config object to your project.
Run 'amplify pull' to sync future upstream changes.
```

No options to select env are shown. So I was not able to change it.

With previous version of CLI, I can change env like this.

```
% amplify pull
? Select the authentication method you want to use: AWS profile

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

? Please choose the profile you want to use profile
? Which app are you working on? xxx
? Pick a backend environment: staging
? Choose your default editor: Visual Studio Code
? Choose the type of app that you're building javascript
Please tell us about your project
? What javascript framework are you using react-native
? Source Directory Path:  src
? Distribution Directory Path: /
? Build Command:  yarn build
? Start Command: yarn start
? Do you plan on modifying this backend? No

Added backend environment config object to your project.
Run 'amplify pull' to sync future upstream changes.
```

I checked that with cli@5.1.2 I changed env successfully but 5.3.0 or 5.2.1 I did not.

### Expected behavior

Backend environment can be changed.

### Reproduction steps

1. amplify pull

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by edwardfoyle** [comment]
@tasugi are you able to change environments using `amplify env checkout <other env>`?

**Comment by tasugi** [comment]
@edwardfoyle Unfortunately no. This is the message from CLI.

```
% amplify env checkout production
Current environment cannot be determined
Use 'amplify init' in the root of your app directory to initialize your project with Amplify
```

**Comment by edwardfoyle** [comment]
@tasugi can you try `amplify pull --appId <your app id> --envName production` and then `amplify env checkout production`?

**Comment by tasugi** [comment]
@edwardfoyle Thanks for your advice! I did it as you say. But `amplify env checkout` does not work yet. Here is the messages.(I hide some secrets)

```
% amplify pull --appId xyz --envName production
? Select the authentication method you want to use: AWS profile

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

? Please choose the profile you want to use xxx
Amplify AppID found: xyz. Amplify App name is: xxx
Backend environment production found in Amplify Console app: xxx
? Choose your default editor: Visual Studio Code
? Choose the type of app that you're building javascript
Please tell us about your project
? What javascript framework are you using react-native
? Source Directory Path:  src
? Distribution Directory Path: /
? Build Command:  yarn build
? Start Command: yarn start
? Do you plan on modifying this backend? No

Added backend environment config object to your project.
Run 'amplify pull' to sync future upstream changes.
```

```
% amplify env checkout production
✖ There was an error initializing your environment.
File at path: '/Users/sugi/path/to/repo/amplify/backend/backend-config.json' does not exist
Error: File at path: '/Users/sugi/path/to/repo/amplify/backend/backend-config.json' does not exist
    at Function.JSONUtilities.readJson (/Users/sugi/.config/yarn/global/node_modules/amplify-cli-core/src/jsonUtilities.ts:25:15)
    at StateManager.getData (/Users/sugi/.config/yarn/global/node_modules/amplify-cli-core/src/state-manager/stateManager.ts:341:32)
    at StateManager.getBackendConfig (/Users/sugi/.config/yarn/global/node_modules/amplify-cli-core/src/state-manager/stateManager.ts:123:17)
    at populateAmplifyMeta (/Users/sugi/.config/yarn/global/node_modules/@aws-amplify/cli/src/initialize-env.ts:113:38)
    at Object.initializeEnv (/Users/sugi/.config/yarn/global/node_modules/@aws-amplify/cli/src/initialize-env.ts:29:7)
    at Object.run (/Users/sugi/.config/yarn/global/node_modules/@aws-amplify/cli/src/commands/env/checkout.ts:51:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object.run (/Users/sugi/.config/yarn/global/node_modules/@aws-amplify/cli/src/commands/env.ts:30:7)
    at Object.executeAmplifyCommand (/Users/sugi/.config/yarn/global/node_modules/@aws-amplify/cli/src/index.ts:313:5)
    at executePluginModuleCommand (/Users/sugi/.config/yarn/global/node_modules/@aws-amplify/cli/src/execution-manager.ts:177:3)
    at Object.executeCommand (/Users/sugi/.config/yarn/global/node_modules/@aws-amplify/cli/src/execution-manager.ts:29:5)
    at Object.run (/Users/sugi/.config/yarn/global/node_modules/@aws-amplify/cli/src/index.ts:151:5)
```

**Comment by edwardfoyle** [comment]
@tasugi sorry my previous comment was wrong. You should be able to pull the production environment just using the first command: `amplify pull --appId <your app id> --envName production`.

The reason switching environments isn't working is because you are selecting "no" to "Do you plan on modifying this backend?" When that selection is "no" pull does not pull the amplify backend folder and you cannot switch environments with checkout

**Comment by tasugi** [comment]
@edwardfoyle I see. I don't think that `amplify pull` does not work as you intend.
At the first time I do `amplify pull`, it works well. I mean the backend is switched to the production by using `amplify pull --appId <your app id> --envName production`.

But after that,  I run the command `amplify pull --appId <your app id> --envName staging`, and there is no change in my working directory. Environment is still the production.
This is the command log.

```
% amplify pull --appId xyz --envName staging     
Amplify AppID found: xyz. Amplify App name is: my-app
Backend environment staging found in Amplify Console app: my-app

Added backend environment config object to your project.
Run 'amplify pull' to sync future upstream changes.
```

**Comment by edwardfoyle** [comment]
@tasugi I don't think I'm able to reproduce the error you're seeing. Just to make sure I've got the steps right, here's what I did:
1. `amplify init --yes`
2. `amplify add function` add a default function just so the project isn't empty
3. `amplify push --yes`
4. `amplify env add envB`
5. `amplify push --yes`
6. in a new directory, run `amplify pull --appId <app id of project> --envName envA` select all defaults except answer "no" to "Do you plan on modifying this backend?"
7. `amplify env list` observe that envA is checked out
8. `amplify pull --appId <app id of project> --envName envB`
9. `amplify env list` observe that envB is checked out

Am I missing any steps here?

**Comment by tasugi** [comment]
@edwardfoyle Thank you for the effort to reproduce it! I found that `amplify env list` worked well, but `aws-exports.js` was not changed after `amplify pull`.
I did following steps.

1. `amplify init --yes`
2. `amplify add api` to have `aws-exports.js` include backend info
3. `amplify push --yes`
4. `amplify env add envB`
5. `amplify push --yes`
6.  Created new directory, and inside it run `amplify pull --appId <app id of project> --envName envA` select all defaults except answer "no" to "Do you plan on modifying this backend?"
7. `amplify env list` observe that envA is checked out
8. `cat src/aws-exports.js` observe that the endpoint is that of envA
9. `amplify pull --appId <app id of project> --envName envB`
10. `amplify env list` observe that envB is checked out
11. `cat src/aws-exports.js` observe that the endpoint is **still that of envA**. The endpoint URL should be that of envB.

Could you try again with these steps?

**Comment by josefaidt** [comment]
Hey @tasugi thanks for the information and detailed reproduction steps! Given this exports file is created on initial pull in a clean directory (i.e. no existing `amplify` folder) and is [updated on `push`](https://docs.amplify.aws/cli/reference/files/#aws-exportsjs), there is currently not an effective solution to update/re-generate the exports file when selecting "No" to "Do you plan on modifying this backend?". Without the `backend-config.json` we are also unable to checkout envs and need to rely on `amplify pull --envName envB`, though unfortunately this will not update the exports file like you are experiencing.

I'll mark this as a feature request for the team to evaluate further. 🙂

**Comment by tasugi** [comment]
I'm glad you were able to reproduce it! I'm waiting for the fix of this issue. 😃

**Comment by taneba** [comment]
I'm facing this issue too and as a workaround, you can checkout by:
1. delete amplify/ and aws-exports.js
2. run amplify pull again and select the env you wanted to checkout

**Comment by tasugi** [comment]
I always use a similar workaround way.
But configuring options on every time I pull is irritating so I save my options in a file by using ways documented this page (https://docs.amplify.aws/cli/usage/headless/) and run commands like `rm -rf amplify && amplify pull --amplify $AMPLIFY --frontend $FRONTEND`

**Comment by josefaidt** [comment]
**NOTE**: this is still not currently possible

```
> amplify env list

| Environments |
| ------------ |
| next         |
| *dev         |


> amplify env checkout next
The local environment configuration does not allow modifying the backend.
Use amplify env pull --envName next
```

**Comment by ethan021021** [comment]
Any update on this? Will this functionality be supported in the future?

**Comment by armen-tractatus** [comment]
When I delete the `amplify` folder and run `amplify pull --appId <appId> --envName staging` the amplify CLI does pull the latest backend changes from the cloud. I can see the environment when I run `amplify env list` and everything seems to work fine.

However, I cannot add a second existing backend environment to the list. If I try running `amplify pull --appId <appId> --envName production`, amplify downloads the production backend successfully, but now `amplify env list` only shows `production` and `staging` has disappeared.

I would like to be able to access both existing backend environments and switch between them as needed.
