### ISSUE TITLE
amplify init fails

### ISSUE THREAD

**Issue by hanachan1026** [aws-amplify/amplify-cli#8039]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm i -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v15.5.0

### Amplify CLI Version

v5.3.1

### What operating system are you using?

Mac

### Amplify Categories

auth, function, api

### Amplify Commands

init

### Describe the bug

Below is the error log.

```
❯ amplify init
Note: It is recommended to run this command from the root of your app directory
? Do you want to use an existing environment? No
? Enter a name for the environment devhanaa
Using default provider  awscloudformation
✔ Initialized provider successfully.
✖ There was an error initializing your environment.
Error: File at path: '/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/../../../../amplify-category-auth/provider-utils/awscloudformation/triggers/UserMigrationAuth/UserMigrationAuth.map.json' does not exist
    at Function.JSONUtilities.readJson (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/jsonUtilities.ts:25:15)
    at AmplifyToolkit.getTriggerMetadata [as _getTriggerMetadata] (/usr/local/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/trigger-flow.ts:402:85)
    at AmplifyToolkit.getTriggerEnvInputs [as _getTriggerEnvInputs] (/usr/local/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/trigger-flow.ts:487:36)
    at initTriggerEnvs (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/provider-utils/awscloudformation/index.ts:428:43)
    at Object.updateConfigOnEnvInit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/provider-utils/awscloudformation/index.ts:374:25)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/index.ts:131:28
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/promise-sequential/index.js:16:18

```

### Expected behavior

`amplify init ` command to success without any errors.

### Reproduction steps

1. amplify init

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line
2021-08-26T04:36:21.389Z|info : amplify init core  
2021-08-26T04:36:21.449Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2021-08-26T04:36:34.518Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["mskun-hana"])
2021-08-26T04:36:34.519Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"ap-northeast-1"}])
2021-08-26T04:36:34.519Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["mskun-hana"])
2021-08-26T04:36:34.531Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["mskun-hana"])
2021-08-26T04:36:34.532Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"ap-northeast-1"}])
2021-08-26T04:36:34.532Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["mskun-hana"])
2021-08-26T04:36:34.538Z|info : amplify-provider-awscloudformation.zip-util.downloadZip.s3.getFile([{"Key":"[***]rent-[***]ud-[***]d.zip"},null])
2021-08-26T04:36:34.542Z|info : amplify-provider-awscloudformation.aws-s3.s3.getFile([{"Key":"[***]rent-[***]ud-[***]d.zip","Bucket":"[***]ify-[***]un-[***]anaa-[***]353-[***]ment"}])
2021-08-26T04:36:35.572Z|info : amplify-provider-awscloudformation.initialize-env.run.cfn.updateamplifyMetaFileWithStackOutputs([{"StackName":"[***]ify-[***]un-[***]anaa-[***]353"}])
2021-08-26T04:36:35.576Z|info : amplify-provider-awscloudformation.aws-cfn.updateamplifyMetaFileWithStackOutputs.cfn.describeStackResources([{"StackName":"[***]ify-[***]un-[***]anaa-[***]353"}])
2021-08-26T04:36:36.226Z|info : amplify-provider-awscloudformation.aws-s3.s3.getFile([{"Key":"[***]ify-[***]json","Bucket":"[***]ify-[***]un-[***]anaa-[***]353-[***]ment"}])
2021-08-26T04:47:35.511Z|info : amplify version core  {"version":true,"yes":false}


```

</details>

**Comment by kaustavghosh06** [comment]
Closing based on last response and no further communication or related issues tied to this. Please let us know if you're still stuck on this issue.
