### ISSUE TITLE
adding 2 lambda functions and configuring accesses causes an error

### ISSUE THREAD

**Issue by danielleadams** [aws-amplify/amplify-cli#8095]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.17.3

### Amplify CLI Version

5.3.1

### What operating system are you using?

mac

### Amplify Categories

function

### Amplify Commands

add

### Describe the bug

When adding 2 lambda functions and then configuring the 2nd's resource action, the CLI errors out with the following:

```sh
TypeError: Cannot read property 'service' of undefined
There was an error adding the function resource
```

### Expected behavior

User should be able to configure advanced options for the 2nd function successfully.

### Reproduction steps

1. `amplify function add` -> Default options -> Do not configure advanced functions
2. `amplify function add` -> Default options -> Configure advanced options
3. `Do you want to access other resources in this project from your Lambda function?` -> Select `Yes`
4. `Select the categories you want this function to have access to.` -> Select `function`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```sh
➜  ampapp git:(master) ✗ amplify add function
? Select which capability you want to add: Lambda function (serverless function)
? Provide an AWS Lambda function name: ampappx
? Choose the runtime that you want to use: NodeJS
? Choose the function template that you want to use: Hello World

Available advanced settings:
- Resource access permissions
- Scheduled recurring invocation
- Lambda layers configuration
- Environment variables configuration
- Secret values configuration

? Do you want to configure advanced settings? No
? Do you want to edit the local lambda function now? No
Successfully added resource ampappx locally.

Next steps:
Check out sample function code generated in <project-dir>/amplify/backend/function/ampappx/src
"amplify function build" builds all of your functions currently in the project
"amplify mock function <functionName>" runs your function locally
"amplify push" builds all of your local backend resources and provisions them in the cloud
"amplify publish" builds all of your local backend and front-end resources (if you added hosting category) and provisions them in the cloud

➜  ampapp git:(master) ✗ amplify add function
? Select which capability you want to add: Lambda function (serverless function)
? Provide an AWS Lambda function name: ampappy
? Choose the runtime that you want to use: NodeJS
? Choose the function template that you want to use: Hello World

Available advanced settings:
- Resource access permissions
- Scheduled recurring invocation
- Lambda layers configuration
- Environment variables configuration
- Secret values configuration

? Do you want to configure advanced settings? Yes
? Do you want to access other resources in this project from your Lambda function? Yes
? Select the categories you want this function to have access to. function
TypeError: Cannot read property 'service' of undefined
    at /Users/.nvm/versions/node/v14.17.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.js:70:184
    at Array.filter (<anonymous>)
    at Object.askExecRolePermissionsQuestions (/Users/.nvm/versions/node/v14.17.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.js:70:47)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.createWalkthrough (/Users/.nvm/versions/node/v14.17.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/service-walkthroughs/lambda-walkthrough.js:48:78)
    at async addFunctionResource (/Users/.nvm/versions/node/v14.17.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/index.js:77:9)
    at async Object.executeAmplifyCommand (/Users/.nvm/versions/node/v14.17.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/lib/index.js:254:5)
    at async executePluginModuleCommand (/Users/.nvm/versions/node/v14.17.3/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:164:5)
    at async Object.executeCommand (/Users/.nvm/versions/node/v14.17.3/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:35:9)
    at async Object.run (/Users/.nvm/versions/node/v14.17.3/lib/node_modules/@aws-amplify/cli/lib/index.js:159:9)
There was an error adding the function resource


```

</details>

**Comment by danielleadams** [comment]
Fixed in 5.4.0: https://github.com/aws-amplify/amplify-cli/releases/tag/v5.4.0
