### ISSUE TITLE
Cannot deploy custom GraphQL Transformers to live, the CI build errors

### ISSUE THREAD

**Issue by PeteDuncanson** [aws-amplify/amplify-cli#8113]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

v14.16.0

### Amplify CLI Version

5.4.0

### What operating system are you using?

Windows

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

I'm trying to use two custom transformers and have them setup as they should be. They used to deploy to my dev branch but won't deploy to live or dev now. Seems they just can't be "found" as part of the build.

https://github.com/hirochachacha/graphql-auto-transformer
https://github.com/trek10inc/graphql-default-value-transformer

I'm seemingly having the same problem as [this issue](https://github.com/trek10inc/graphql-default-value-transformer/issues/4) and I've implemented the "fix" mentioned in there to edit my build script to include `graphql-default-value-transformer` but still get the same error.

I tried changing my transform file to change the order (it was `graphql-default-value-transformer`  first then `graphql-auto-transformer` but I swapped them to try to rule out if it was just the `graphql-default-value-transformer` that was giving me problems) and its erroring for both of them regardless of order, as if it simply isn't installing them. 

### Expected behavior

Pushing a change into my git repos with the CI setup to watch that branch my build should be triggered, the `transform.conf.json` file should include my custom transformer and as a result my schema should compile.

### Reproduction steps

My `transform.conf.json` file:

```
{
  "Version": 5,
  "ElasticsearchWarning": true,
  "StackMapping": {
    "QueryjobCommentsByJobIDResolver": "JobComment"
  },
  "ResolverConfig": {
    "project": {
      "ConflictHandler": "AUTOMERGE",
      "ConflictDetection": "VERSION"
    }
  },
  "transformers": [
    "graphql-default-value-transformer",
    "graphql-auto-transformer"
  ]
}
```

my build settings (aka `amplify.yaml` this is just in the cloud and not in my repos), note the fix to load the `graphql-default-value-transformer` globally :
```
version: 3
backend:
  phases:
    build:
      commands:
        - '# Fix to get the tranformer working https://github.com/trek10inc/graphql-default-value-transformer/issues/3'
        - npm i -g graphql-default-value-transformer
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - '# Hack to get it running against node12 so it builds without errors - https://github.com/aws-amplify/amplify-cli/issues/3131'
        - nvm use 12
        - yarn install
    build:
      commands:
      - '# Make the commit ID available in the react app as REACT_APP_COMMIT_ID - https://codingblog.carterdan.net/2020/09/03/commit-hash-react-aws-amplify/'
      - REACT_APP_COMMIT_ID=$AWS_COMMIT_ID REACT_APP_BRANCH_NAME=$AWS_BRANCH yarn run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line

                                 # Starting phase: build
                                 # Executing command: npm i -g graphql-default-value-transformer
2021-09-07T15:21:58.886Z [INFO]: + graphql-default-value-transformer@2.0.1
                                 added 164 packages from 185 contributors in 3.381s
2021-09-07T15:22:08.848Z [INFO]: [0mAmplify AppID found: d1y0lxfx9s7bhz. Amplify App name is: FranchiseManager[0m
_modules/import-global/index.js[39m
                                 [31m- /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/transform-graphql-schema.js[39m
                                 [31m- /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/push-resources.js[39m
                                 [31m- /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/amplify-service-migrate.js[39m
                                 [31m- /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/initializer.js[39m
                                 [31m- /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/index.js[39m
                                 [31m- /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/lib/attach-backend-steps/a10-queryProvider.js[39m
                                 [31m- /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/lib/attach-backend.js[39m
                                 [31m- /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/lib/commands/pull.js[39m
                                 [31m- /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/lib/index.js[39m
                                 [31m- /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/bin/amplify[39m
2021-09-07T15:22:13.025Z [INFO]: [0m/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/import-global/index.js:1[0m
                                 [0mError: Cannot find module '/root/.nvm/versions/node/v12.21.0/lib/node_modules/graphql-auto-transformer'[0m
                                 [0mRequire stack:[0m
                                 [0m- /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/import-global/index.js[0m
                                 [0m- /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/transform-graphql-schema.js[0m
                                 [0m- /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/push-resources.js[0m
                                 [0m- /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/amplify-service-migrate.js[0m
                                 [0m- /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/initializer.js[0m
                                 [0m- /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/index.js[0m
                                 [0m- /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/lib/attach-backend-steps/a10-queryProvider.js[0m
                                 [0m- /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/lib/attach-backend.js[0m
                                 [0m- /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/lib/commands/pull.js[0m
                                 [0m- /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/lib/index.js[0m
                                 [0m- /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/bin/amplify[0m
                                 [0m    at Object.module.exports [as default] (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/import-global/index.js:9:10)[0m
                                 [0m    at /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/transform-graphql-schema.ts:113:44[0m
                                 [0m    at Array.map (<anonymous>)[0m
                                 [0m    at /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/transform-graphql-schema.ts:82:8[0m
                                 [0m    at getDirectiveDefinitions (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/transform-graphql-schema.ts:538:25)[0m
                                 [0m    at generateModels (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/commands/models.js:59:32)[0m
                                 [0m    at Object.postPullCodegen (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/amplify-service-helper.ts:38:5)[0m
                                 [0m    at onSuccess (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/attach-backend.ts:59:3)[0m
                                 [0m    at Object.attachBackend (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/attach-backend.ts:31:5)[0m
                                 [0m    at Object.run (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/commands/pull.ts:59:5)[0m
                                 [0m    at Object.executeAmplifyCommand (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/index.ts:362:5)[0m
                                 [0m    at executePluginModuleCommand (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:177:3)[0m
                                 [0m    at Object.executeCommand (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:29:5)[0m
                                 [0m    at Object.run (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/index.ts:200:5)[0m
2021-09-07T15:22:13.048Z [ERROR]: !!! Build failed
```

</details>

### Additional information

![image](https://user-images.githubusercontent.com/1674590/132373266-e8a772d1-37f0-4e3e-83e2-f91ef091773d.png)

**Comment by PeteDuncanson** [comment]
Can't get this working at all and its blocking my deploys so I've had to strip both 3rd party transformers out of my schema. Currently it seems I can't use any 3rd party transformer :(

**Comment by lazpavel** [comment]
Hello @PeteDuncanson ,

Thank you for raising this issue, I was able to reproduce it and marked as a bug for the team to pick up.

**Comment by PeteDuncanson** [comment]
Any ETA on this one, I'm currently paused on deploying until this is resolved. Only option open at the moment is to remove the transformers completely and push which I can do if a fix is a while off so would be good to have an idea before I bite the bullet.

**Comment by PeteDuncanson** [comment]
Still avoiding deploying any custom 3rd party transformers that I know of due to this bug. Got caught out with a empty required field that I added to my schema that killed my last deploy, this would normally have been handled by the default transformer :(

**Comment by lazpavel** [comment]
Hi @PeteDuncanson, sorry for late response. We believe this was fixed in the V2 transformer, which also adds support for [@default directive](https://docs.amplify.aws/cli/graphql/data-modeling/#assign-default-values-for-fields). 

Let us know if you still have this issue
