### ISSUE TITLE
AWS Amplify gets error when running "amplify push"

### ISSUE THREAD

**Issue by Vindi-Van** [aws-amplify/amplify-cli#8150]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2jtcbjir93tmj

### Region

us-west-2

### Amplify Console feature

Backend builds

### Describe the bug

Unable to run `amplify push` after either modifying graphql schema or making any `amplify update api` change. Keeps returning this error message below then rolling back.

Error Message:
`UPDATE_FAILED               authboredyetmeb57b6dd5           AWS::CloudFormation::Stack Thu Sep 09 2021 19:45:51 GMT-0700 
(Pacific Daylight Time) Parameters: [hostedUIDomainName, authProviders, hostedUI, oAuthMetadata, authProvidersUserPool, hostedUIProviderMeta, aliasAttributes, hostedUIProviderCreds] must have values`

URL generated for events also comes in completely blank:
https://console.aws.amazon.com/cloudformation/home?region=us-west-2#/stacks/arn%3Aaws%3Acloudformation%3Aus-west-2%3A646082359734%3Astack%2Famplify-boredyetme-develop-30227%2Fcd4d0110-686a-11eb-9129-029323e94e8b/events

Deployment status constantly says fetching logs, unable to see recent logs.
![image](https://user-images.githubusercontent.com/57526880/132792076-80f24909-fac1-4a05-b335-ab74e6d7e78a.png)

*not working for develop, test, and prod environment

### Expected behavior

`amplify push` should update the specified environment with modified changes from local

### Reproduction steps

1. modify graphql schema (made a property nullable)
2. run amplify push

**Comment by Vindi-Van** [comment]
> Hi 👋, thanks for raising. I'm going to transfer to the CLI repo to get some more eyes on it.
> 
> In the meantime, do you mind verifying that:
> 
> * You're you're using the latest version of the Amplify CLI (![](https://camo.githubusercontent.com/85c06963f50b19a42640e71eeea2c2db2b660db0e17be1f723b7db421ba7b809/68747470733a2f2f696d672e736869656c64732e696f2f6e706d2f762f406177732d616d706c6966792f636c692e737667)). Run `amplify version` to check.

I did update to version 5.5.0 amplify CLI and re-ran the same steps and faced the same error.

**Comment by Vindi-Van** [comment]
> Hi 👋, thanks for raising. I'm going to transfer to the CLI repo to get some more eyes on it.
> 
> In the meantime, do you mind verifying that:
> 
> * You're you're using the latest version of the Amplify CLI (![](https://camo.githubusercontent.com/85c06963f50b19a42640e71eeea2c2db2b660db0e17be1f723b7db421ba7b809/68747470733a2f2f696d672e736869656c64732e696f2f6e706d2f762f406177732d616d706c6966792f636c692e737667)). Run `amplify version` to check.

@siegerts  any updates on the above issue?

**Comment by josefaidt** [comment]
Hey @Vindi-Van as a temporary workaround can you try running `amplify update auth` and following the prompts? Then, may you post the diff of your auth resource's `parameters.json` file omitting sensitive information?

**Comment by CodySwannGT** [comment]
@josefaidt We've hit the same problem and the solution you suggested doesn't help.

We're on v6.0.0

Specifically, we're running into this error:

``Parameters: [aliasAttributes] must have values``

If we take your suggestion and run:

``$ amplify update auth``

We get: 

````
TypeError: Cannot read property 'length' of undefined
    at Object.run (/Users/cody/.nvm/versions/node/v14.17.5/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/lib/commands/auth/update.js:38:56)
    at Object.executeAmplifyCommand (/Users/cody/.nvm/versions/node/v14.17.5/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/lib/index.js:294:25)
    at /Users/cody/.nvm/versions/node/v14.17.5/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:180:51
    at executePluginModuleCommand (/Users/cody/.nvm/versions/node/v14.17.5/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:164:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.executeCommand (/Users/cody/.nvm/versions/node/v14.17.5/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:35:9)
    at async Object.run (/Users/cody/.nvm/versions/node/v14.17.5/lib/node_modules/@aws-amplify/cli/lib/index.js:162:9)
````

If we manually add 

``"aliasAttributes": [],`` to parameters.json

We get: 

``Existing schema attributes cannot be modified or deleted. ``

When trying to push the changes.

We're pretty much dead in the water until this gets resolved.

**Comment by josefaidt** [comment]
Hey @CodySwannGT :wave: thanks for adding your notes. I believe this issue you are experiencing regarding `aliasAttributes` is new and has a different root cause. Would you mind filing a separate [bug report](https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=&template=1.bug_report.yaml)?

**Comment by CodySwannGT** [comment]
[Done](https://github.com/aws-amplify/amplify-cli/issues/8221)

**Comment by josefaidt** [comment]
Hey @Vindi-Van :wave: just wanted to follow up and see if you are still experiencing this issue with the [latest version of Amplify CLI (v6.0.0)](https://github.com/aws-amplify/amplify-cli/releases/tag/v6.0.1) and whether the proposed workaround alleviated your issue in the meantime?

**Comment by josefaidt** [comment]
Closing due to inactivity. @CodySwannGT if you are still experiencing this issue please reply back to this thread and we can re-open to investigate further 🙂
