### ISSUE TITLE
Lambda storage triggers that write S3 data - are they unsupported, or is this a bug?

### ISSUE THREAD

**Issue by jamescrowley** [aws-amplify/amplify-cli#8229]
**Which Category is your question related to?**

Storage & Functions

**Amplify CLI Version** 

6.0.0

**What AWS Services are you utilizing?**

S3 / Lambda

**Provide additional details e.g. code snippets**

I can't figure out the 'supported' way of achieving this.

- Adding storage 'write' permissions to a lambda that is also a trigger results in cyclic dependencies (see Scenario A and scenario B). I understand why you might block that - given you could end up infinitely recursive.
- I could fix this by using prefixes on the lambda trigger - but this doesn't appear to be a configuration option, and the above would block me anyway.
- I could write to a secondary bucket to avoid the infinite recursion risk entirely, but you only support one bucket.

Are there any alternatives, beyond manually creating stuff in AWS outside of the scope of Amplify?

--------
Scenario A: 

1. Creating a lambda function via `add function`
2. Adding permissions to access Storage
3. Adding as a trigger via `update storage`
then I get

✅ Successfully updated resource BucketNameTrigger8ba9f268 locally
🛑 Cannot add BucketName due to a cyclic dependency
✅ Successfully updated resource

Scenario B:

1. Creating a lambda function via `add function`
2. Adding as a trigger via `update storage`
3. Adding permissions to access Storage via `update function`

then I get
```
Error: Cannot add S3Trigger8ba9f268 due to a cyclic dependency
    at checkForCyclicDependencies (/Users/jcrowley/.nvm/versions/node/v12.17.0/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/update-amplify-meta.js:224:15)
    at AmplifyToolkit.updateamplifyMetaAfterResourceUpdate [as _updateamplifyMetaAfterResourceUpdate] (/Users/jcrowley/.nvm/versions/node/v12.17.0/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/update-amplify-meta.js:132:9)
    at updateFunctionResource (/Users/jcrowley/.nvm/versions/node/v12.17.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/index.js:150:29)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.executeAmplifyCommand (/Users/jcrowley/.nvm/versions/node/v12.17.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/lib/index.js:254:5)
    at async executePluginModuleCommand (/Users/jcrowley/.nvm/versions/node/v12.17.0/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:164:5)
    at async Object.executeCommand (/Users/jcrowley/.nvm/versions/node/v12.17.0/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:35:9)
    at async Object.run (/Users/jcrowley/.nvm/versions/node/v12.17.0/lib/node_modules/@aws-amplify/cli/lib/index.js:162:9)
```

**Comment by attilah** [comment]
@jamescrowley cyclic dependency resolution is behind a feature flag what you can find [here](https://docs.amplify.aws/cli/reference/feature-flags/#breakCircularDependency), enabling it would make it possible to create the triggers.

About the infinite loop problem you are right, there is no way around it, coming from the nature of what you try to achieve, [official documentation](https://docs.aws.amazon.com/lambda/latest/dg/with-s3.html) also suggests 2 buckets or use of prefixes.

As of Today you cannot create multiple S3 buckets within the same amplify project through `add storage`, but it is an active feature request we are tracking.

What you could do is create the additional bucket through our custom resource support by adding your own CFN stack to the amplify project. 

About prefixes you can customize the `NotificationConfiguration.LambdaConfigurations` with prefixes/suffixes if you like after `add storage` then it will be pushed and preserved until you run `update storage` and changing the inputs for the given bucket.

Let me know if I answered all your questions

**Comment by jamescrowley** [comment]
@attilah thanks for all the info, very useful. The feature flag you mention seems to be specifically for auth triggers, as opposed to storage though?

**Comment by attilah** [comment]
Yes that is correct, that's for triggers + circular dependency (chicken-egg)

Closing the issue as the question has been answered.

**Comment by jamescrowley** [comment]
@attilah understood - was just making the point the feature flag you mentioned doesn't actually resolve my scenario, which is using a storage trigger rather than an auth trigger (at least it didn't seem to make any difference in my testing)
