### ISSUE TITLE
Cyclic Dependency in `backend-config.json` causing crash on `amplify init`

### ISSUE THREAD

**Issue by MichaelKilbane** [aws-amplify/amplify-cli#8321]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v15.5.1

### Amplify CLI Version

6.1.0

### What operating system are you using?

Windows

### Amplify Categories

auth, function

### Amplify Commands

init, status

### Describe the bug

The `backend-config.json` file in my project has a cyclic dependency in that the user pool depends on an export value of the post-confirmation trigger function and vice versa. The contents of this file can be seen below:

```json
{
  "auth": {
    "hydrantd11bc70b": {
      "service": "Cognito",
      "providerPlugin": "awscloudformation",
      "dependsOn": [
        {
          "category": "function",
          "resourceName": "hydrantd11bc70bPostConfirmation",
          "triggerProvider": "Cognito",
          "attributes": [
            "Arn",
            "Name"
          ]
        }
      ],
      "customAuth": false,
      "frontendAuthConfig": {
        "loginMechanisms": [],
        "signupAttributes": [
          "EMAIL"
        ],
        "passwordProtectionSettings": {
          "passwordPolicyMinLength": 8,
          "passwordPolicyCharacters": []
        },
        "mfaConfiguration": "OFF",
        "mfaTypes": [
          "SMS"
        ],
        "verificationMechanisms": [
          "EMAIL"
        ]
      }
    },
    "userPoolGroups": {
      "service": "Cognito-UserPool-Groups",
      "providerPlugin": "awscloudformation",
      "dependsOn": [
        {
          "category": "auth",
          "resourceName": "hydrantd11bc70b",
          "attributes": [
            "UserPoolId",
            "AppClientIDWeb",
            "AppClientID",
            "IdentityPoolId"
          ]
        }
      ]
    }
  },
  "api": {
    "hydrant": {
      "service": "AppSync",
      "providerPlugin": "awscloudformation",
      "output": {
        "authConfig": {
          "defaultAuthentication": {
            "authenticationType": "AMAZON_COGNITO_USER_POOLS",
            "userPoolConfig": {
              "userPoolId": "authhydrantd11bc70b"
            }
          },
          "additionalAuthenticationProviders": [
            {
              "authenticationType": "AWS_IAM"
            }
          ]
        }
      }
    }
  },
  "function": {
    "hydrantd11bc70bPostConfirmation": {
      "build": true,
      "providerPlugin": "awscloudformation",
      "service": "Lambda",
      "dependsOn": [
        {
          "category": "api",
          "resourceName": "hydrant",
          "attributes": [
            "GraphQLAPIIdOutput",
            "GraphQLAPIEndpointOutput"
          ]
        },
        {
          "category": "auth",
          "resourceName": "hydrantd11bc70b",
          "attributes": [
            "UserPoolId"
          ]
        },
        {
          "category": "function",
          "resourceName": "hydrantappsyncLayer",
          "attributes": [
            "Arn"
          ]
        }
      ]
    },
    "hydrantappsyncLayer": {
      "providerPlugin": "awscloudformation",
      "service": "LambdaLayer",
      "build": true
    }
  },
  "hosting": {
    "S3AndCloudFront": {
      "service": "S3AndCloudFront",
      "providerPlugin": "awscloudformation"
    }
  }
}
```

In this state, running `amplify init` causes the node runtime to run out of memory.

However, breaking the cyclic dependency in the `backend-config.json` file by removing `hydrantd11bc70bPostConfirmation`'s dependency on `hydrantd11bc70b` enables `amplify init` to run successfully.

Once the project has been initialised, the dependency can be replaced and deployed with no issue.

### Expected behavior

`amplify init` can be executed with the presence of a valid circular dependency. Else, the program should output appropriate error messages.

The issue of circular dependencies in trigger lambdas seems to be addressed in #4568, so this should be a valid use case.

### Reproduction steps

1. Create a project a circular dependency similar to that seen in the above `backend-config.json` file.
2. Save the project to a repository (or otherwise remove the ignored files).
3. Run `amplify init`.
4. Input the same answers as those seen in the CLI output (where relevant).

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line
PS C:\Development\Test2\hydrant> amplify init
Note: It is recommended to run this command from the root of your app directory
? Do you want to use an existing environment? No
? Enter a name for the environment devfour
? Choose your default editor: None
Using default provider  awscloudformation
? Select the authentication method you want to use: AWS profile

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

? Please choose the profile you want to use default
Adding backend environment devfour to AWS Amplify Console app: d2abof6lf3mk8l
/ Initializing project in the cloud...

CREATE_IN_PROGRESS UnauthRole       AWS::IAM::Role  Fri Oct 01 2021 00:02:54 GMT+1000 (GMT+10:00)

CREATE_IN_PROGRESS AuthRole         AWS::IAM::Role  Fri Oct 01 2021 00:02:55 GMT+1000 (GMT+10:00)

CREATE_IN_PROGRESS DeploymentBucket AWS::S3::Bucket Fri Oct 01 2021 00:02:55 GMT+1000 (GMT+10:00)

CREATE_IN_PROGRESS UnauthRole       AWS::IAM::Role  Fri Oct 01 2021 00:02:55 GMT+1000 (GMT+10:00) Resource creation Initiated
/ Initializing project in the cloud...

CREATE_IN_PROGRESS DeploymentBucket AWS::S3::Bucket Fri Oct 01 2021 00:02:57 GMT+1000 (GMT+10:00) Resource creation Initiated
CREATE_IN_PROGRESS AuthRole         AWS::IAM::Role  Fri Oct 01 2021 00:02:59 GMT+1000 (GMT+10:00) Resource creation Initiated
| Initializing project in the cloud...

CREATE_COMPLETE DeploymentBucket AWS::S3::Bucket Fri Oct 01 2021 00:03:19 GMT+1000 (GMT+10:00)
| Initializing project in the cloud...

CREATE_COMPLETE UnauthRole AWS::IAM::Role Fri Oct 01 2021 00:03:24 GMT+1000 (GMT+10:00)
\ Initializing project in the cloud...

CREATE_COMPLETE AuthRole                      AWS::IAM::Role             Fri Oct 01 2021 00:03:28 GMT+1000 (GMT+10:00)
CREATE_COMPLETE amplify-hydrant-devfour-00251 AWS::CloudFormation::Stack Fri Oct 01 2021 00:03:30 GMT+1000 (GMT+10:00)
√ Successfully created initial AWS cloud resources for deployments.
√ Initialized provider successfully.

<--- Last few GCs --->

[22168:0000021F638B4060]    86251 ms: Mark-sweep 1402.8 (1456.7) -> 1071.2 (1124.5) MB, 534.8 / 0.1 ms  (+ 0.3 ms in 2 steps since start of marking, biggest step 0.2 ms, walltime since start of marking 2690 ms) (average mu = 0.983, current mu = 0.849) all[22168:0000021F638B4060]    87949 ms: Scavenge 1645.0 (1698.3) -> 1645.0 (1698.3) MB, 77.6 / 0.0 ms  (average mu = 0.983, current mu = 0.849) allocation failure


<--- JS stacktrace --->

FATAL ERROR: invalid array length Allocation failed - JavaScript heap out of memory
 1: 00007FF70DE72E6F v8::internal::Isolate::ArchiveSpacePerThread+4447
 2: 00007FF70DE0DE56 DSA_meth_get_flags+65078
 3: 00007FF70DE0ED56 node::OnFatalError+294
 4: 00007FF70E70B36E v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF70E6EFA3D v8::SharedArrayBuffer::Externalize+781
 6: 00007FF70E588A6C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1468
 7: 00007FF70E5AFD3F v8::internal::Factory::NewUninitializedFixedArray+111
 8: 00007FF70E470F50 v8::debug::Script::GetIsolate+7280
 9: 00007FF70E2F6A97 v8::internal::CompilationCache::IsEnabledScriptAndEval+62151
10: 00007FF70E79267D v8::internal::SetupIsolateDelegate::SetupHeap+456749
11: 00000018F23989E8

```

</details>

**Comment by marcvberg** [comment]
Hi @MichaelKilbane,

We have a feature flag that's meant to help with this, could you take a look at https://docs.amplify.aws/cli/reference/feature-flags/#breakCircularDependency and let us know if it fixes it for you?

**Comment by MichaelKilbane** [comment]
Hi @marcvberg,

Yes, that feature flag is enabled and has been since the project was initialised (created after it became the default).

This seems to be an issue with the environment creation code that may recursively check the dependencies of each resource without a stopping condition.

**Comment by akshbhu** [comment]
Hi @MichaelKilbane 

I am not sure how your  ```backend.config.json``` file got into that state. Is there any other steps you have done apart from the steps mentioned below.

Here are steps I tried :

- `amplify** add auth` and selected post confirmation function

```
{
  "auth": {
    "authtest94b4361694b43616": {
      "service": "Cognito",
      "providerPlugin": "awscloudformation",
      "dependsOn": [
        {
          "category": "function",
          "resourceName": "authtest94b4361694b43616PostConfirmation",
          "triggerProvider": "Cognito",
          "attributes": [
            "Arn",
            "Name"
          ]
        }
      ],
      "customAuth": false,
      "frontendAuthConfig": {
        "loginMechanisms": [
          "EMAIL"
        ],
        "signupAttributes": [
          "EMAIL"
        ],
        "passwordProtectionSettings": {
          "passwordPolicyMinLength": 8,
          "passwordPolicyCharacters": []
        },
        "mfaConfiguration": "OFF",
        "mfaTypes": [
          "SMS"
        ],
        "verificationMechanisms": [
          "EMAIL"
        ]
      }
    }
  },
  "function": {
    "authtest94b4361694b43616PostConfirmation": {
      "build": true,
      "providerPlugin": "awscloudformation",
      "service": "Lambda"
    }
  }
}
```

- amplify update function to add dependency on API 

```
{
  "auth": {
    "authtest94b4361694b43616": {
      "service": "Cognito",
      "providerPlugin": "awscloudformation",
      "dependsOn": [
        {
          "category": "function",
          "resourceName": "authtest94b4361694b43616PostConfirmation",
          "triggerProvider": "Cognito",
          "attributes": [
            "Arn",
            "Name"
          ]
        }
      ],
      "customAuth": false,
      "frontendAuthConfig": {
        "loginMechanisms": [
          "EMAIL"
        ],
        "signupAttributes": [
          "EMAIL"
        ],
        "passwordProtectionSettings": {
          "passwordPolicyMinLength": 8,
          "passwordPolicyCharacters": []
        },
        "mfaConfiguration": "OFF",
        "mfaTypes": [
          "SMS"
        ],
        "verificationMechanisms": [
          "EMAIL"
        ]
      }
    }
  },
  "function": {
    "authtest94b4361694b43616PostConfirmation": {
      "build": true,
      "providerPlugin": "awscloudformation",
      "service": "Lambda",
      "dependsOn": [
        {
          "category": "api",
          "resourceName": "authtest",
          "attributes": [
            "GraphQLAPIIdOutput",
            "GraphQLAPIEndpointOutput",
            "GraphQLAPIKeyOutput"
          ]
        }
      ]
    }
  },
  "api": {
    "authtest": {
      "service": "AppSync",
      "providerPlugin": "awscloudformation",
      "output": {
        "authConfig": {
          "defaultAuthentication": {
            "authenticationType": "API_KEY",
            "apiKeyConfig": {
              "apiKeyExpirationDays": 7,
              "description": ""
            }
          },
          "additionalAuthenticationProviders": []
        }
      }
    }
  }
}
```

- amplify update function to add dependency on auth


```
{
  "auth": {
    "authtest94b4361694b43616": {
      "service": "Cognito",
      "providerPlugin": "awscloudformation",
      "dependsOn": [
        {
          "category": "function",
          "resourceName": "authtest94b4361694b43616PostConfirmation",
          "triggerProvider": "Cognito",
          "attributes": [
            "Arn",
            "Name"
          ]
        }
      ],
      "customAuth": false,
      "frontendAuthConfig": {
        "loginMechanisms": [
          "EMAIL"
        ],
        "signupAttributes": [
          "EMAIL"
        ],
        "passwordProtectionSettings": {
          "passwordPolicyMinLength": 8,
          "passwordPolicyCharacters": []
        },
        "mfaConfiguration": "OFF",
        "mfaTypes": [
          "SMS"
        ],
        "verificationMechanisms": [
          "EMAIL"
        ]
      }
    }
  },
  "function": {
    "authtest94b4361694b43616PostConfirmation": {
      "build": true,
      "providerPlugin": "awscloudformation",
      "service": "Lambda",
      "dependsOn": [
        {
          "category": "api",
          "resourceName": "authtest",
          "attributes": [
            "GraphQLAPIIdOutput",
            "GraphQLAPIEndpointOutput",
            "GraphQLAPIKeyOutput"
          ]
        }
      ]
    }
  },
  "api": {
    "authtest": {
      "service": "AppSync",
      "providerPlugin": "awscloudformation",
      "output": {
        "authConfig": {
          "defaultAuthentication": {
            "authenticationType": "API_KEY",
            "apiKeyConfig": {
              "apiKeyExpirationDays": 7,
              "description": ""
            }
          },
          "additionalAuthenticationProviders": []
        }
      }
    }
  }
}
```

Error thrown:
 
```
You can access the following resource attributes as environment variables from your Lambda function
        API_AUTHTEST_GRAPHQLAPIENDPOINTOUTPUT
        API_AUTHTEST_GRAPHQLAPIIDOUTPUT
        API_AUTHTEST_GRAPHQLAPIKEYOUTPUT
        AUTH_AUTHTEST94B4361694B43616_USERPOOLID
Error: Cannot add authtest94b4361694b43616PostConfirmation due to a cyclic dependency
    at checkForCyclicDependencies (/Users/akz/workspace/amplify-cli/packages/amplify-cli/lib/extensions/amplify-helpers/update-amplify-meta.js:226:15)
    at AmplifyToolkit.updateamplifyMetaAfterResourceUpdate [as _updateamplifyMetaAfterResourceUpdate] (/Users/akz/workspace/amplify-cli/packages/amplify-cli/lib/extensions/amplify-helpers/update-amplify-meta.js:134:9)
    at updateFunctionResource (/Users/akz/workspace/amplify-cli/packages/amplify-category-function/lib/provider-utils/awscloudformation/index.js:150:29)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.executeAmplifyCommand (/Users/akz/workspace/amplify-cli/packages/amplify-category-function/lib/index.js:254:5)
    at async executePluginModuleCommand (/Users/akz/workspace/amplify-cli/packages/amplify-cli/lib/execution-manager.js:187:5)
    at async Object.executeCommand (/Users/akz/workspace/amplify-cli/packages/amplify-cli/lib/execution-manager.js:35:9)
    at async Object.run (/Users/akz/workspace/amplify-cli/packages/amplify-cli/lib/index.js:162:9)
There was an error adding the function resource
```

**Comment by MichaelKilbane** [comment]
Hi @akshbhu,

I believe I added the dependency between the Post-Confirmation Lambda and the User Pool at some stage, however, this is a [documented use case](https://docs.amplify.aws/cli/usage/customcf/#3-optional-reference-existing-parameters). I'm not sure how the template code for the "Add user to group" functionality is supposed to run without access to the User Pool ID.

Once deployed, the lambda is able to access these values without issue.

**Comment by akshbhu** [comment]
Hi @MichaelKilbane 

When you add the the post confirmation lambda via `amplify add auth` , amplify automatically adds a dependency between post-confirmation lambda and userpool. Amazon Cognito passes event information to your PostConfirmation lambda  function which returns the same event object back to Amazon Cognito with any changes in the response
```
{
    "version": "string",
    "triggerSource": "string",
    "region": AWSRegion,
    "userPoolId": "string",
    "userName": "string",
    "callerContext": 
        {
            "awsSdkVersion": "string",
            "clientId": "string"
        },
    "request":
        {
            "userAttributes": {
                "string": "string",
                ....
            }
        },
    "response": {}
}
```

you can get more information here: https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html#cognito-user-pools-lambda-trigger-sample-event-parameter-shared

**Comment by samuelmburu** [comment]
I'm running into the same issue -- I had been building and rebuilding this project several times today, and then I started getting out of memory errors. I've been trying different versions of the amplify-cli(v4.52-6.5.0) and node(14.x-16.x) with varying levels of "success."

I  tried the `GENERATE_SOURCEMAP` flag and set the node memory to 10GB via vars exported by my `~/.zshrc`.  

'm not sure what I'm doing wrong, but it feels as though if I look at my templates the wrong way, things just blow up. I've been working on this project for a few months and 

(below node version lts/fermium)
```shell
❯ GENERATE_SOURCEMAP=false amplify init

Note: It is recommended to run this command from the root of your app directory
? Do you want to use an existing environment? Yes
? Choose the environment you would like to use: apidev
Using default provider  awscloudformation
✔ Initialized provider successfully.

<--- Last few GCs --->

[53714:0x104d40000]    21249 ms: Scavenge 1033.0 (1081.4) -> 1033.0 (1081.4) MB, 38.0 / 0.0 ms  (average mu = 0.997, current mu = 0.997) allocation failure
[53714:0x104d40000]    23198 ms: Scavenge 1415.6 (1464.0) -> 1415.6 (1464.0) MB, 66.8 / 0.0 ms  (average mu = 0.997, current mu = 0.997) allocation failure
[53714:0x104d40000]    26151 ms: Scavenge 1989.4 (2037.8) -> 1989.4 (2037.8) MB, 99.0 / 0.0 ms  (average mu = 0.997, current mu = 0.997) allocation failure


<--- JS stacktrace --->

FATAL ERROR: invalid array length Allocation failed - JavaScript heap out of memory
 1: 0x101319fc5 node::Abort() (.cold.1) [/Users/samuel/.nvm/versions/node/v14.18.1/bin/node]
 2: 0x1000b6169 node::Abort() [/Users/samuel/.nvm/versions/node/v14.18.1/bin/node]
 3: 0x1000b62df node::OnFatalError(char const*, char const*) [/Users/samuel/.nvm/versions/node/v14.18.1/bin/node]
 4: 0x100200ba7 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/Users/samuel/.nvm/versions/node/v14.18.1/bin/node]
 5: 0x100200b43 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/samuel/.nvm/versions/node/v14.18.1/bin/node]
 6: 0x1003aec55 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/samuel/.nvm/versions/node/v14.18.1/bin/node]
 7: 0x100386726 v8::internal::Factory::NewUninitializedFixedArray(int) [/Users/samuel/.nvm/versions/node/v14.18.1/bin/node]
 8: 0x100513752 v8::internal::(anonymous namespace)::ElementsAccessorBase<v8::internal::(anonymous namespace)::FastPackedObjectElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)2> >::GrowCapacity(v8::internal::Handle<v8::internal::JSObject>, unsigned int) [/Users/samuel/.nvm/versions/node/v14.18.1/bin/node]
 9: 0x1006de7d4 v8::internal::Runtime_GrowArrayElements(int, unsigned long*, v8::internal::Isolate*) [/Users/samuel/.nvm/versions/node/v14.18.1/bin/node]
10: 0x100a8deb9 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/Users/samuel/.nvm/versions/node/v14.18.1/bin/node]
[1]    53714 abort      GENERATE_SOURCEMAP=false amplify init
```

Thanks for all your help.

**Comment by sachscode** [comment]
@samuelmburu 
1. The "amplify function remove" related "out of memory" error has been fixed in the latest version of the Amplify CLI ( 7.6.11 ). Could you please upgrade to that and check if it resolves for you.
2. Could you please confirm if you have breakcirculardependency is set for you.

**Comment by sachscode** [comment]
@MichaelKilbane 
could you please let us know if this method [ https://github.com/aws-amplify/amplify-cli/issues/8321#issuecomment-940546451 ]  helped you resolve the issue ?

**Comment by cjihrig** [comment]
Closing due to a lack of followup, but we can revisit this issue if needed.
