### ISSUE TITLE
amplify mock function error with Python 3.8 ( "ModuleNotFoundError: No module named 'pipenv'")

### ISSUE THREAD

**Issue by CGarces** [aws-amplify/amplify-cli#8337]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

6.1.0

### What operating system are you using?

Windows 10

### Amplify Categories

function

### Amplify Commands

Not applicable

### Describe the bug

amplify mock function foobar not works, raise an error without execute the mock code.

**Error:**

```
Error: Command failed with exit code 1: pipenv run python C:\Users\foo\.amplify\lib\amplify-python-function-runtime-provider\shim\shim.py C:\desarrollos\foobar\amplify\backend\function\foobar1ec3db6a\src\index.py handler
Traceback (most recent call last):
  File "c:\users\foo\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
  File "c:\users\foo\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\foo\AppData\Roaming\Python\Python38\Scripts\pipenv.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'pipenv'

```

Entire Stacktrace:
<details>

```
PS C:\desarrollos\foobar> amplify mock function foobar1ec3db6a          
? Provide the path to the event JSON object relative to C:\desarrollos\foobar\amplify\backend\function\foobar1ec3db6a src/event.json
Ensuring latest function changes are built...
Creating a virtualenv for this project...
Pipfile: C:\desarrollos\foobar\amplify\backend\function\foobar1ec3db6a\Pipfile
Using C:/Users/foo/AppData/Local/Programs/Python/Python38/python.exe (3.8.10) to create virtualenv...
[=== ] Creating virtual environment...created virtual environment CPython3.8.10.final.0-64 in 2730ms
  creator CPython3Windows(dest=C:\Users\foo\.virtualenvs\foobar1ec3db6a-2tgakUoW, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\foo\AppData\Local\pypa\virtualenv)
    added seed packages: pip==21.2.4, setuptools==57.4.0, wheel==0.37.0
  activators BashActivator,BatchActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

Successfully created virtual environment!
Virtualenv location: C:\Users\foo\.virtualenvs\foobar1ec3db6a-2tgakUoW
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
 Locking...Building requirements...
Resolving dependencies...
Success!
Updated Pipfile.lock (e02f68)!
Installing dependencies from Pipfile.lock (e02f68)...
  ================================ 1/1 - 00:00:07
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
Starting execution...
Traceback (most recent call last):
  File "c:\users\foo\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\foo\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\foo\AppData\Roaming\Python\Python38\Scripts\pipenv.exe\__main__.py", line 4, in <module>  
ModuleNotFoundError: No module named 'pipenv'
foobar1ec3db6a failed with the following error:
Error: Command failed with exit code 1: pipenv run python C:\Users\foo\.amplify\lib\amplify-python-function-runtime-provider\shim\shim.py C:\desarrollos\foobar\amplify\backend\function\foobar1ec3db6a\src\index.py handler
Traceback (most recent call last):
  File "c:\users\foo\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
  File "c:\users\foo\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\foo\AppData\Roaming\Python\Python38\Scripts\pipenv.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'pipenv'
    at makeError (C:\Users\foo\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Users\foo\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\execa\index.js:118:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object.pythonInvoke (C:\Users\foo\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-python-function-runtime-provider\src\util\invokeUtil.ts:33:22)
    at Object.timeConstrainedInvoker (C:\Users\foo\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-util-mock\src\func\index.ts:67:12)
    at Object.start (C:\Users\foo\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-util-mock\src\func\index.ts:48:20)
    at Object.run (C:\Users\foo\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-util-mock\src\commands\mock\function.ts:14:5)
    at Object.executeAmplifyCommand (C:\Users\foo\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-util-mock\src\amplify-plugin-index.ts:8:3)
    at executePluginModuleCommand (C:\Users\foo\AppData\Roaming\npm\node_modules\@aws-amplify\cli\src\execution-manager.ts:177:3)
    at Object.executeCommand (C:\Users\foo\AppData\Roaming\npm\node_modules\@aws-amplify\cli\src\execution-manager.ts:29:5)
    at Object.run (C:\Users\foo\AppData\Roaming\npm\node_modules\@aws-amplify\cli\src\index.ts:205:5) {
  shortMessage: 'Command failed with exit code 1: pipenv run python C:\\Users\\foo\\.amplify\\lib\\amplify-python-function-runtime-provider\\shim\\shim.py C:\\desarrollos\\foobar\\amplify\\backend\\function\\foobar1ec3db6a\\src\\index.py handler',
  command: 'pipenv run python C:\\Users\\foo\\.amplify\\lib\\amplify-python-function-runtime-provider\\shim\\shim.py C:\\desarrollos\\foobar\\amplify\\backend\\function\\foobar1ec3db6a\\src\\index.py handler', 
  escapedCommand: 'pipenv run python "C:\\Users\\foo\\.amplify\\lib\\amplify-python-function-runtime-provider\\shim\\shim.py" "C:\\desarrollos\\foobar\\amplify\\backend\\function\\foobar1ec3db6a\\src\\index.py" handler',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'Traceback (most recent call last):\r\n' +
    '  File "c:\\users\\foo\\appdata\\local\\programs\\python\\python38\\lib\\runpy.py", line 194, in _run_module_as_main\r\n' +
    '    return _run_code(code, main_globals, None,\r\n' +
    '  File "c:\\users\\foo\\appdata\\local\\programs\\python\\python38\\lib\\runpy.py", line 87, in _run_code\r\n' +
    '    exec(code, run_globals)\r\n' +
    '  File "C:\\Users\\foo\\AppData\\Roaming\\Python\\Python38\\Scripts\\pipenv.exe\\__main__.py", line 4, in <module>\r\n' +
    "ModuleNotFoundError: No module named 'pipenv'",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
Finished execution.
```

</details>

### Expected behavior

Execute the python lambda with mock data.

### Reproduction steps

amplify init
amplify add function (select python runtime)
 amplify mock function

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line
2021-10-01T15:12:52.127Z|info : amplify function mock foobar1ec3db6a 
2021-10-01T15:12:52.230Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2021-10-01T15:13:19.815Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["default"])
2021-10-01T15:13:19.825Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"eu-west-1"}])
2021-10-01T15:13:19.825Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["default"])
2021-10-01T15:16:25.349Z|info : amplify version core  {"version":true,"yes":false}
2021-10-01T15:16:54.020Z|info : amplify version core  


```

</details>

**Comment by josefaidt** [comment]
Hey @CGarces :wave: thanks for raising this! Can you confirm whether `pipenv` is installed and available in your `$PATH` variable? To confirm whether `pipenv` is installed we can run `where.exe pipenv` in Windows.

**Comment by CGarces** [comment]
Hi

Additional info as requested.

where.exe pipenv
`C:\Users\foo\AppData\Roaming\Python\Python38\Scripts\pipenv.exe`

pipenv --version
`pipenv, version 2020.11.15`

Path enviroment

```
C:\Users\foo\AppData\Roaming\Python\Python38\Scripts\
C:\Users\foo\AppData\Local\Programs\Python\Python38\Scripts\
C:\Users\foo\AppData\Local\Programs\Python\Python38\
```

**Comment by josefaidt** [comment]
Hey @CGarces thanks for clarifying! It seems as if we need to start the virtual env for this Python Lambda. Using the following example steps, are you able to successfully mock the Lambda?

```shell
cd amplify/backend/function/your-function-name
pipenv shell
pipenv install boto3
```

reference: https://docs.amplify.aws/guides/functions/dynamodb-from-python-lambda/q/platform/js/

**Comment by CGarces** [comment]
Hi @josefaidt 
Partially works after do this workaround:

```
cd amplify/backend/function/your-function-name
pipenv shell
pipenv install pipenv
```
So `pipenv = "*"` is needed on Pipfile in my case.

**Comment by josefaidt** [comment]
Ah that's good to hear you're up and running. Did that alleviate the issue you were experiencing all together?

**Comment by CGarces** [comment]
> Did that alleviate the issue you were experiencing all together?
Partially
I'm not sure why pipenv is needed as dependency, and I can't debug on VSCode, but maybe must be handled as a different issue, so  I'll close this.
Thanks @josefaidt for your support.
