### ISSUE TITLE
Amplify init behind a proxy (Ex: Zscaler)

### ISSUE THREAD

**Issue by Olivier-STMicroelectronics** [aws-amplify/amplify-cli#8361]
Do you have guidelines to be able to run "amplify init" command for people behind a company proxy like Zscaler?  I'm facing the error below. 
I'm working on Windows 10 in a "cmd" terminal. I have set HTTP_PROXY, HTTPS_PROXY, http_proxy and https_proxy.
Thank you

```
Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1514:34)
    at TLSSocket.emit (events.js:400:28)
    at TLSSocket.emit (domain.js:470:12)
    at TLSSocket._finishInit (_tls_wrap.js:936:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:708:12) {
  code: 'NetworkingError',
  region: 'eu-west-1',
  hostname: 'amplify.eu-west-1.amazonaws.com',
  retryable: true,
  time: 2021-10-05T08:01:07.179Z
}
```

**Comment by yuth** [comment]
From the error it looks like the SSL the proxy might be using self signed SSL certificate. Could you install the self signed certificate as trusted certificate.

Another insecure work around which will disable certificate validation by setting environment variable `NODE_TLS_REJECT_UNAUTHORIZED` to `0`. This disables checks for SSL and use of this is **highly discouraged** .

**Comment by josefaidt** [comment]
Closing due to inactivity. @Olivier-STMicroelectronics if you are still experiencing this issue please reply back to this thread and we can re-open to investigate further 🙂
