### ISSUE TITLE
Inconsistent behaviour with "amplify pull" in CI scenario

### ISSUE THREAD

**Issue by pcolmer** [aws-amplify/amplify-cli#8491]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v14.18.1

### Amplify CLI Version

6.3.1

### What operating system are you using?

Ubuntu 20.04

### Amplify Categories

auth, storage, function, api, analytics

### Amplify Commands

pull

### Describe the bug

I am putting together a container and some scripts to ensure a consistent workflow for `amplify push` for our internal developers and the CI/CD servers.

To that end, the script that runs within the container does this:

```
amplify pull --restore --y
amplify push --y
```

On occasions, `amplify pull` will fail with something like this:

```
✔ Successfully pulled backend environment develop from the cloud.
✖ There was an error initializing your environment.
auth headless is missing the following inputParams googleAppIdUserPool, googleAppSecretUserPool
Error: auth headless is missing the following inputParams googleAppIdUserPool, googleAppSecretUserPool
    at updateConfigOnEnvInit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/provider-utils/awscloudformation/index.js:134:15)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/index.js:304:28
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/promise-sequential/index.js:16:18
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

In those situations, *sometimes* using `amplify pull --appId "${APP_ID}" --envName "${BUILD_ENV}" --y` instead works but not always. I am struggling to find the correct syntax/combination of options for `amplify pull` that ensures that the workflow works 100%.

### Expected behavior

I am expecting 100% consistent behaviour, i.e. that `amplify pull` (with the correct parameters) will *always* update the "local" environment from the cloud so that `amplify push` then works correctly.

### Reproduction steps

All I can say is that I'm running `amplify pull --restore --y` and *sometimes* it fails but, when it fails, it seems to be really difficult to get it out of the failed state.

At the time of writing this bug report, my environment is in a failed state and I cannot find a combination of parameters for `amplify pull` that will succeed. All tried permutations are currently failing.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line
2021-10-19T10:43:42.514Z|info : amplify pull core  {"restore":true,"yes":true}
2021-10-19T10:43:42.596Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2021-10-19T10:43:52.172Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["AmplifyBuildProfile"])
2021-10-19T10:43:52.175Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2021-10-19T10:43:52.175Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["AmplifyBuildProfile"])
2021-10-19T10:43:52.186Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["AmplifyBuildProfile"])
2021-10-19T10:43:52.186Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2021-10-19T10:43:52.187Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["AmplifyBuildProfile"])
2021-10-19T10:43:52.193Z|info : amplify-provider-awscloudformation.zip-util.downloadZip.s3.getFile([{"Key":"[***]rent-[***]ud-[***]d.zip"},null])
2021-10-19T10:43:52.206Z|info : amplify-provider-awscloudformation.aws-s3.s3.getFile([{"Key":"[***]rent-[***]ud-[***]d.zip","Bucket":"[***]ify-[***]eshub-[***]lop-[***]858-[***]ment"}])
2021-10-19T10:43:57.128Z|info : amplify-provider-awscloudformation.aws-s3.getAllObjectKey.s3.listObjectVersions([{"Bucket":"[***]ify-[***]eshub-[***]lop-[***]858-[***]ment","Prefix":"hooks/"}])
2021-10-19T10:43:57.581Z|info : amplify-provider-awscloudformation.initialize-env.run.cfn.updateamplifyMetaFileWithStackOutputs([{"StackName":"[***]ify-[***]eshub-[***]lop-[***]858"}])
2021-10-19T10:43:57.592Z|info : amplify-provider-awscloudformation.aws-cfn.updateamplifyMetaFileWithStackOutputs.cfn.describeStackResources([{"StackName":"[***]ify-[***]eshub-[***]lop-[***]858"}])
2021-10-19T10:43:58.314Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]HubAnalytics-[***]NPHZUP/[***]bec0-[***]97-[***]eb-[***]f2-[***]9136b"}])
2021-10-19T10:43:58.318Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]cesHub-[***]AQHP1/[***]7930-[***]59-[***]eb-[***]be-[***]0d557"}])
2021-10-19T10:43:58.321Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]ub5749acda-[***]2OVXZY/[***]2fd0-[***]9b-[***]eb-[***]4f-[***]4acd1"}])
2021-10-19T10:43:58.325Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]olGroups-[***]TJYN7/[***]a1c0-[***]9b-[***]eb-[***]69-[***]33fbd"}])
2021-10-19T10:43:58.328Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]riesa5721c39-[***]0MSTJ/[***]ee60-[***]96-[***]eb-[***]af-[***]a5385"}])
2021-10-19T10:43:58.331Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]erea186e1b-[***]FJYNC/[***]2980-[***]e1-[***]eb-[***]39-[***]c3a21"}])
2021-10-19T10:43:58.335Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]ivateResource-[***]G8LR9/[***]2b30-[***]d1-[***]eb-[***]02-[***]d5d0c"}])
2021-10-19T10:43:58.338Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]ewResource-[***]WD2CP2/[***]5660-[***]d1-[***]eb-[***]39-[***]55b13"}])
2021-10-19T10:43:58.342Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]PutObjectS3URL-[***]JFVUX/[***]8620-[***]1a-[***]eb-[***]07-[***]1c6b9"}])
2021-10-19T10:43:58.345Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]deoSubtitles-[***]5ELM1S/[***]cc60-[***]53-[***]eb-[***]cb-[***]7557f"}])
2021-10-19T10:43:58.349Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]leteUser-[***]TJC16/[***]45d0-[***]1b-[***]eb-[***]e7-[***]c2bc2"}])
2021-10-19T10:43:58.352Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]tionSignedUrl-[***]G0MUM/[***]4070-[***]1a-[***]eb-[***]8a-[***]53619"}])
2021-10-19T10:43:58.355Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]rceSignedUrl-[***]B7F5Y/[***]e070-[***]92-[***]eb-[***]ad-[***]a3521"}])
2021-10-19T10:43:58.357Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]geSignedUrl-[***]OOXFS/[***]35d0-[***]fd-[***]eb-[***]0b-[***]9f19f"}])
2021-10-19T10:43:58.360Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]sForResource-[***]KW28J/[***]8c80-[***]1a-[***]eb-[***]18-[***]05527"}])
2021-10-19T10:43:58.363Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]oSignedUrl-[***]BULKFE/[***]d0e0-[***]1a-[***]eb-[***]a0-[***]4d2e3"}])
2021-10-19T10:43:58.365Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]geCompany-[***]QM0HHZ/[***]ab80-[***]61-[***]eb-[***]f1-[***]31a5b"}])
2021-10-19T10:43:58.368Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]ailTemplates-[***]3XHP7A/[***]5fd0-[***]a1-[***]eb-[***]d2-[***]09c1f"}])
2021-10-19T10:43:58.371Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]geGroups-[***]DZHS5/[***]d040-[***]74-[***]eb-[***]25-[***]e55d9"}])
2021-10-19T10:43:58.374Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]articipant-[***]ZJ7566/[***]27d0-[***]fd-[***]eb-[***]0b-[***]392f9"}])
2021-10-19T10:43:58.376Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]eResources-[***]Y2YPV/[***]6a80-[***]11-[***]eb-[***]a9-[***]bcb75"}])
2021-10-19T10:43:58.378Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]vateResource-[***]0HX3V/[***]64d0-[***]1a-[***]eb-[***]42-[***]f230b"}])
2021-10-19T10:43:58.381Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]yResource-[***]LDBCS/[***]b7d0-[***]1a-[***]eb-[***]f9-[***]caebf"}])
2021-10-19T10:43:58.384Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]vateResource-[***]MO4XD/[***]3770-[***]1a-[***]eb-[***]dc-[***]7557f"}])
2021-10-19T10:43:58.386Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]eResource-[***]2MK428/[***]f310-[***]1a-[***]eb-[***]99-[***]02d6d"}])
2021-10-19T10:43:58.389Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]sHubHelpers-[***]Q5R6P/[***]e690-[***]27-[***]eb-[***]50-[***]92d53"}])
2021-10-19T10:43:58.392Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]daPostConfirmation-[***]HK998/[***]2700-[***]9a-[***]eb-[***]fd-[***]01035"}])
2021-10-19T10:43:58.394Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]49acdaPreSignup-[***]08XNZ/[***]fe90-[***]21-[***]eb-[***]ee-[***]eb989"}])
2021-10-19T10:43:58.396Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]aPreTokenGeneration-[***]WAXU7Q/[***]d570-[***]a0-[***]eb-[***]f5-[***]ded49"}])
2021-10-19T10:43:58.398Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]ndEmail-[***]UZFJ7/[***]3880-[***]98-[***]eb-[***]82-[***]80e95"}])
2021-10-19T10:43:58.401Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]tResourceUrl-[***]1XL0Q/[***]bd80-[***]4b-[***]eb-[***]59-[***]fa46d"}])
2021-10-19T10:43:58.403Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]aGraphQL-[***]3Y2ONE/[***]6430-[***]70-[***]eb-[***]e3-[***]4f729"}])
2021-10-19T10:43:58.405Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]ationUpdate-[***]EP92D/[***]e140-[***]fd-[***]eb-[***]ea-[***]a039d"}])
2021-10-19T10:43:58.407Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]arams-[***]87QT9/[***]e320-[***]db-[***]eb-[***]c1-[***]fad97"}])
2021-10-19T10:43:58.408Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]ceStorage-[***]675RC/[***]8b00-[***]e1-[***]eb-[***]1f-[***]c1ab7"}])
2021-10-19T10:43:58.409Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]VideoService-[***]YVQAL/[***]2760-[***]83-[***]eb-[***]54-[***]b4763"}])
2021-10-19T10:44:00.874Z|error : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]aGraphQL-[***]3Y2ONE/[***]6430-[***]70-[***]eb-[***]e3-[***]4f729"}])
Throttling: Rate exceeded
2021-10-19T10:44:00.881Z|error : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]ceStorage-[***]675RC/[***]8b00-[***]e1-[***]eb-[***]1f-[***]c1ab7"}])
Throttling: Rate exceeded
2021-10-19T10:44:00.956Z|error : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]tResourceUrl-[***]1XL0Q/[***]bd80-[***]4b-[***]eb-[***]59-[***]fa46d"}])
Throttling: Rate exceeded
2021-10-19T10:44:00.979Z|error : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]ndEmail-[***]UZFJ7/[***]3880-[***]98-[***]eb-[***]82-[***]80e95"}])
Throttling: Rate exceeded
2021-10-19T10:44:01.119Z|error : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]VideoService-[***]YVQAL/[***]2760-[***]83-[***]eb-[***]54-[***]b4763"}])
Throttling: Rate exceeded
2021-10-19T10:44:01.223Z|error : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]ationUpdate-[***]EP92D/[***]e140-[***]fd-[***]eb-[***]ea-[***]a039d"}])
Throttling: Rate exceeded
2021-10-19T10:44:01.243Z|error : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]arams-[***]87QT9/[***]e320-[***]db-[***]eb-[***]c1-[***]fad97"}])
Throttling: Rate exceeded
2021-10-19T10:44:05.876Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]aGraphQL-[***]3Y2ONE/[***]6430-[***]70-[***]eb-[***]e3-[***]4f729"}])
2021-10-19T10:44:05.883Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]ceStorage-[***]675RC/[***]8b00-[***]e1-[***]eb-[***]1f-[***]c1ab7"}])
2021-10-19T10:44:05.957Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]tResourceUrl-[***]1XL0Q/[***]bd80-[***]4b-[***]eb-[***]59-[***]fa46d"}])
2021-10-19T10:44:05.980Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]ndEmail-[***]UZFJ7/[***]3880-[***]98-[***]eb-[***]82-[***]80e95"}])
2021-10-19T10:44:06.121Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]VideoService-[***]YVQAL/[***]2760-[***]83-[***]eb-[***]54-[***]b4763"}])
2021-10-19T10:44:06.225Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]ationUpdate-[***]EP92D/[***]e140-[***]fd-[***]eb-[***]ea-[***]a039d"}])
2021-10-19T10:44:06.244Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]arams-[***]87QT9/[***]e320-[***]db-[***]eb-[***]c1-[***]fad97"}])
2021-10-19T10:44:08.153Z|error : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]ceStorage-[***]675RC/[***]8b00-[***]e1-[***]eb-[***]1f-[***]c1ab7"}])
Throttling: Rate exceeded
2021-10-19T10:44:08.221Z|error : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]ndEmail-[***]UZFJ7/[***]3880-[***]98-[***]eb-[***]82-[***]80e95"}])
Throttling: Rate exceeded
2021-10-19T10:44:08.258Z|error : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]aGraphQL-[***]3Y2ONE/[***]6430-[***]70-[***]eb-[***]e3-[***]4f729"}])
Throttling: Rate exceeded
2021-10-19T10:44:08.262Z|error : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]tResourceUrl-[***]1XL0Q/[***]bd80-[***]4b-[***]eb-[***]59-[***]fa46d"}])
Throttling: Rate exceeded
2021-10-19T10:44:13.154Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]ceStorage-[***]675RC/[***]8b00-[***]e1-[***]eb-[***]1f-[***]c1ab7"}])
2021-10-19T10:44:13.222Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]ndEmail-[***]UZFJ7/[***]3880-[***]98-[***]eb-[***]82-[***]80e95"}])
2021-10-19T10:44:13.259Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]aGraphQL-[***]3Y2ONE/[***]6430-[***]70-[***]eb-[***]e3-[***]4f729"}])
2021-10-19T10:44:13.262Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]78:stack/[***]ify-[***]eshub-[***]lop-[***]858-[***]tResourceUrl-[***]1XL0Q/[***]bd80-[***]4b-[***]eb-[***]59-[***]fa46d"}])
2021-10-19T10:44:13.971Z|info : amplify-provider-awscloudformation.aws-s3.s3.getFile([{"Key":"[***]ify-[***]json","Bucket":"[***]ify-[***]eshub-[***]lop-[***]858-[***]ment"}])
```

</details>

**Comment by kylekirkby** [comment]
@edwardfoyle

**Comment by josefaidt** [comment]
Hey @pcolmer :wave: thanks for raising this and apologies for the delay!! If you are still experiencing this issue may you try running `amplify pull` without the `-y` flag and manually accept the incoming changes to see if that alleviates the issue?
