### ISSUE TITLE
preSignUp triggers don't work when using email sign-up and Hosted UI / SIWA in parallel 

### ISSUE THREAD

**Issue by jacobsapps** [aws-amplify/amplify-cli#8553]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.17.3

### Amplify CLI Version

5.1.2

### What operating system are you using?

Mac

### Amplify Categories

auth

### Amplify Commands

add, update

### Describe the bug

I've been trying to implement Sign In With Apple to my app with some difficulty. 

I think I've finally got it working, but the last hurdle I have is getting it to gel nicely with the existing sign-up logic I have. 

I have a preSignUp trigger [as seen in this example](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-pre-sign-up.html#aws-lambda-triggers-pre-registration-example-2) to automatically confirm user emails. 

Since implementing SIWA using the Hosted UI, the preSignUp trigger no longer works. I printed the event/context/callback in the cloudwatch logs:  

```
2021-10-25T11:01:22.567Z	56a35a81-6ec0-4473-a183-7daf056e7096	INFO	{
  callbackWaitsForEmptyEventLoop: [Getter/Setter],
  succeed: [Function (anonymous)],
  fail: [Function (anonymous)],
  done: [Function (anonymous)],
  functionVersion: '$LATEST',
  functionName: 'carbnPreSignup-test',
  memoryLimitInMB: '128',
  logGroupName: '/aws/lambda/carbnPreSignup-test',
  logStreamName: '2021/10/25/[$LATEST]1cd67473b9b54a338d02c155b27dced3',
  clientContext: undefined,
  identity: undefined,
  invokedFunctionArn: 'arn:aws:lambda:eu-west-2:271591594744:function:carbnPreSignup-test',
  awsRequestId: '56a35a81-6ec0-4473-a183-7daf056e7096',
  getRemainingTimeInMillis: [Function: getRemainingTimeInMillis]
}
```
```
2021-10-25T11:00:22.120Z	baef75c7-895c-4372-8f8a-e1b82d28253d	ERROR	Invoke Error 	
{
    "errorType": "TypeError",
    "errorMessage": "Cannot set property 'autoConfirmUser' of undefined",
    "stack": [
        "TypeError: Cannot set property 'autoConfirmUser' of undefined",
        "    at exports.handler (/var/task/custom.js:4:34)",
        "    at Runtime.exports.handler (/var/task/index.js:11:5)",
        "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
    ]
}
```

Neither the SIWA emails or the normal email sign-ups are getting confirmed. This is breaking my auth flow as they need to be confirmed in order to sign in. It seems like the SIWA implementation overwrites the preSignUp trigger somehow, or maybe it triggers but is structured differently?

Please help! 

Thank you

### Expected behavior

Expect preSignUp trigger to work 

### Reproduction steps

1. Use email sign-up 
2. Have a pre-sign-up trigger
3. Attempt to add SIWA using Hosted UI
4. Experience issues and ask github!

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
Hey @jacobsapps :wave: are you still experiencing this issue? Was SIWA added with the Amplify CLI?

**Comment by josefaidt** [comment]
Hey @jacobsapps :wave: just wanted to follow-up on this one to see if SIWA was added with the Amplify CLI or through the Console?

**Comment by abdallahshaban557** [comment]
Hi @jacobsapps  - are you still facing this issue?

**Comment by josefaidt** [comment]
Closing due to inactivity and no longer able to reproduce
