### ISSUE TITLE
Unable to pull resources from cloud: "No Amplify backend project files detected within this folder"

### ISSUE THREAD

**Issue by sophieyuge** [aws-amplify/amplify-cli#8608]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm i -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v16.5.0

### Amplify CLI Version

6.3.1

### What operating system are you using?

Mac

### Amplify Categories

Not applicable

### Amplify Commands

pull

### Describe the bug

```
Name: NotInitializedError : Message:
      No Amplify backend project files detected within this folder. Either initialize a new Amplify project or pull an existing project.
      - "amplify init" to initialize a new Amplify project
      - "amplify pull <app-id>" to pull your existing Amplify project. Find the <app-id> in the AWS Console or Amplify Admin UI.
```

### Expected behavior

It should display the status of the backend resources and successfully pull resources from cloud

### Reproduction steps

  Created a new folder
  ran `amplify pull --appId XXX --envName XX`
  ran `amplify pull`
  ran `amplify status`
  got Error

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

No log provided

**Comment by josefaidt** [comment]
Hey @sophieyuge :wave: thanks for raising this! After the initial pull command did you select "Yes" to "Do you plan on modifying this backend?"?

**Comment by sophieyuge** [comment]
@josefaidt Hi Jose,
I don’t think I have even seen this prompt in the latest `amplify init`. 

Previously, I had always chosen “yes” whenever I was asked this question.

**Comment by josefaidt** [comment]
Hey @sophieyuge our initial pull command will look something like this where the question noted above is the last prompt of the workflow:

```
amplify pull --appId xxx --envName dev
⚠️ Amplify command hooks are disabled in the current execution environment.
⚠️ See https://docs.amplify.aws/cli/usage/command-hooks/ for more information.
? Select the authentication method you want to use: AWS profile

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

? Please choose the profile you want to use default
Amplify AppID found: xxx. Amplify App name is: 8069
Backend environment dev found in Amplify Console app: 8069
? Choose your default editor: Visual Studio Code
? Choose the type of app that you're building javascript
Please tell us about your project
? What javascript framework are you using none
? Source Directory Path:  src
? Distribution Directory Path: dist
? Build Command:  npm run-script build
? Start Command: npm run-script start
? Do you plan on modifying this backend? Yes
✔ Successfully pulled backend environment dev from the cloud.


Successfully pulled backend environment dev from the cloud.
Run 'amplify pull' to sync future upstream changes.
```

By selecting "Yes" the Amplify CLI will pull your app's backend definition locally, creating the `amplify/` folder in your working directory. This will enable us to subsequently run commands such as `amplify pull` and `amplify status`

**Comment by sophieyuge** [comment]
Hi Jose, I understand it and I have indeed seen those prompts in the past.
However, now the process just fails and get aborted straightaway as soon as I run the initial pull command with the error message mentioned above, which is not helpful, because the suggested next steps from the error message are exactly what I have done to encounter this error

**Comment by josefaidt** [comment]
Hey @sophieyuge thanks for clarifying. Are you experiencing this after the initial, successful pull when attempting to run `amplify status` or `amplify pull`? Do you see the `amplify/` backend folder as well?

**Comment by sophieyuge** [comment]
Hi @josefaidt ,

I was experiencing it when attempting to run all of the commands you mentioned. I had `amplify/` backend folder from my last successful pull but `amplofy-meta.json` is missing. 

Since yesterday, I've made a few more attempts to try unblock myself. Here is what I have done:
1. found the deployment bucket name from `team-provider-info.json`
2. downloaded `#current_cloud_backend.zip`, saved a copy of it somewhere else and unzipped it
3. found `amplify-meta.json` missing in the unzipped folder, so I added one which I also downloaded from the s3 bucket (at folder root)
4. zipped the content of the folder and rename the folder to `#current_cloud_backend.zip`
5. uploaded `#current_cloud_backend.zip` to S3
6. ran `amplify pull --appId xxx --envName xxx`
7. getting the following error:
```
 % amplify pull --appId xxx --envName xxx
Opening link: https://us-west-2.admin.amplifyapp.com/admin/{appId}/{envName}/verify/
✔ Successfully received Amplify Admin tokens.
Amplify AppID found: xxx. Amplify App name is: xxx
Backend environment xxx found in Amplify Console app: xxx
? Choose your default editor: Visual Studio Code
? Choose the type of app that you're building javascript
Please tell us about your project
? What javascript framework are you using react-native
? Source Directory Path:  src
? Distribution Directory Path: /
? Build Command:  npm run-script build
? Start Command: npm run-script start
Failed to pull the backend.
File at path: '/Users/{username}/{projectName}/amplify/backend/auth/xxx/parameters.json' does not exist
Error: File at path: '/Users/{username}/{projectName}/amplify/backend/auth/xxx/parameters.json' does not exist
    at Function.JSONUtilities.readJson (/Users/{username}//.nvm/versions/node/v16.5.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/jsonUtilities.ts:25:15)
    at StateManager.getData (/Users/{username}//.nvm/versions/node/v16.5.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/state-manager/stateManager.ts:373:32)
    at StateManager.getResourceParametersJson (/Users/{username}//.nvm/versions/node/v16.5.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/state-manager/stateManager.ts:150:17)
    at ensureAmplifyMetaFrontendConfig (/Users/{username}//.nvm/versions/node/v16.5.0/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/on-category-outputs-change.ts:84:55)
    at AmplifyToolkit.onCategoryOutputsChange [as _onCategoryOutputsChange] (/Users/{username}/.nvm/versions/node/v16.5.0/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/on-category-outputs-change.ts:18:5)
    at Object.generateFiles (/Users/{username}/.nvm/versions/node/v16.5.0/lib/node_modules/@aws-amplify/cli/src/attach-backend-steps/a40-generateFiles.ts:45:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.attachBackend (/Users/{username}//.nvm/versions/node/v16.5.0/lib/node_modules/@aws-amplify/cli/src/attach-backend.ts:30:5)
    at Object.run (/Users/{username}//.nvm/versions/node/v16.5.0/lib/node_modules/@aws-amplify/cli/src/commands/pull.ts:59:5)
    at Object.executeAmplifyCommand (/Users/{username}//.nvm/versions/node/v16.5.0/lib/node_modules/@aws-amplify/cli/src/index.ts:373:5)
    at executePluginModuleCommand (/Users/{username}//.nvm/versions/node/v16.5.0/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:178:3)
    at Object.executeCommand (/Users/{username}//.nvm/versions/node/v16.5.0/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:30:5)
    at Object.run (/Users/{username}//.nvm/versions/node/v16.5.0/lib/node_modules/@aws-amplify/cli/src/index.ts:205:5)
```

**Comment by josefaidt** [comment]
Hey @sophieyuge does the mentioned file exist? Are you able to restore the `parameters.json` file for auth?

**Comment by sophieyuge** [comment]
@josefaidt 
In `#current_cloud_backend.zip` from the bucket, there are only two files in it after unzipping: `cli.json` and `tag.json` so I added `amplify-meta.json` as told. It seems that all of the files in the cloud backend folder are just gone.

I just tried to add all of the content in my local backend folder to it and uploaded to S3, just like what I did with `amplify-meta.json`, and now I am able to pull from cloud again.

However, when I made changes to `schema.graphql` in `amplify/backend/api/api/` and tried to push the changes, here is what I got:
```
amplify push
✔ Successfully pulled backend environment devtest from the cloud.

    Current Environment: devtest

┌───────────────┬──────────────────────┬───────────┬───────────────────┐
│ Category      │ Resource name        │ Operation │ Provider plugin   │
├───────────────┼──────────────────────┼───────────┼───────────────────┤
│ Api           │ api                  │ Update    │ awscloudformation │
├───────────────┼──────────────────────┼───────────┼───────────────────┤
│ Auth          │ ***                  │ No Change │ awscloudformation │
├───────────────┼──────────────────────┼───────────┼───────────────────┤
│ Api           │ ***                  │ No Change │ awscloudformation │
├───────────────┼──────────────────────┼───────────┼───────────────────┤
│ Function      │ ***                  │ No Change │ awscloudformation │
├───────────────┼──────────────────────┼───────────┼───────────────────┤
│ Notifications │ ***                  │ No Change │                   │
├───────────────┼──────────────────────┼───────────┼───────────────────┤
│ Analytics     │ ***                  │ No Change │ awscloudformation │
├───────────────┼──────────────────────┼───────────┼───────────────────┤
│ Storage       │ ***                  │ No Change │ awscloudformation │
└───────────────┴──────────────────────┴───────────┴───────────────────┘
? Are you sure you want to continue? Yes

GraphQL schema compiled successfully.

Edit your schema at /Users/sophieyuge/github/taco/amplify/backend/api/api/schema.graphql or place .graphql files in a directory at /Users/sophieyuge/github/taco/amplify/backend/api/api/schema
✖ An error occurred when pushing the resources to the cloud
🛑
Cannot read property 'diff' of null
An error occurred during the push operation: Cannot read property 'diff' of null
```

**Comment by josefaidt** [comment]
Are you able to run `amplify push --force` to forcefully push local content? This should update the `#current-cloud-backend` folder with the necessary files.

**Comment by sophieyuge** [comment]
Just tried to force push, same result as above

**Comment by josefaidt** [comment]
Hey @sophieyuge could you try creating a new environment, pushing, then run a `git merge` back onto the affected env and see if that allows you to push successfully? If not there is a "Detect Drift" button in the CloudFormation console that we can utilize to revert changes until there is no drift.
![image](https://user-images.githubusercontent.com/5033303/139747944-635a130e-e769-42e2-9359-ffff26a1a1fe.png)

**Comment by josefaidt** [comment]
Hey @sophieyuge are you still experiencing this issue?

**Comment by josefaidt** [comment]
Closing due to inactivity. @sophieyuge if you are still experiencing this issue please reply back to this thread and we can re-open to investigate further 🙂

**Comment by ggmon** [comment]
It is still a problem I am having similar issues,  please investiage

**Comment by AllanBengco** [comment]
Adding my report to this thread. As of today, I suddenly found my amplify backend folder missing! I believe this happened after a successful pull a few days ago.

**Comment by Modullah** [comment]
@AllanBengco Thank you so much. I deleted the entire amplify folder and then pulled the existing project as you suggested. This worked for me as well. Thanks again!

**Comment by renatobcsilva** [comment]
@AllanBengco and @Modullah , thank you very much, your comments helped me with the same issue!

**Comment by betomoedano** [comment]
> To resolve the issue, I deleted the entire amplify folder, then pulled the existing project:
> 
> `amplify pull --appId <your project id> --envName <environment>`

This works but you have to select "Yes" for:
```bash
? Do you plan on modifying this backend? Yes
```
