### ISSUE TITLE
Using new stacks functionality in 1.1.0 results in error and missing files after CloudFormation failure during push command

### ISSUE THREAD

**Issue by lookitsatravis** [aws-amplify/amplify-cli#864]
**Describe the bug**
I'm using @aws-amplify/cli v. 1.1.0 in order to make use of the new custom stacks/resolvers feature of the AppSync integration. I created a CF template which ultimately failed to deploy because it was misconfigured. However, after the failed deployment, the contents of my API directory were wiped out and replaced with what looks like a CF template dump with keys as directories, and values as files.

**To Reproduce**
1. Added a "stacks" directory inside my GraphQL API backend directory
2. Added a .json file with my resolver resource info
3. `amplify push`
4. Confirm the change and confirm the new migration warning.
5. Wait for deploy to fail due to CF error
6. Get the following error:

```
✖ An error occured when migrating the API project.
Reverting API migration.
Invalid CloudFormation template: /Users/myself/test/api/amplify/backend/api/graphql/template
✖ An error occurred when pushing the resources to the cloud

Could not determine file type. Check your template is not malformed. EISDIR: illegal operation on a directory, read
```

7. Contents of `./amplify/backend/api/[name]/` now look like the following. Almost like the content of a CF template were dumped replacing the previous contents.

![image](https://user-images.githubusercontent.com/606978/52673455-829a0b00-2ee6-11e9-9236-9f6115862f88.png)

**Expected behavior**
I expect the contents of the named API directory to remain the same if the deployment fails (minus, perhaps, the build directory).

**Desktop (please complete the following information):**
 - OS: macOS

**Additional context**
N/A

**Comment by kaustavghosh06** [comment]
@lookitsatravis Sorry for that. We'll have to dig into the root-cause and this since I'm not able to reproduce this behavior on my machine. That being said, if you backed up yoour project before the migration, you could probably just copy paste the amplify/backend/api/<resource-name> directory and put it in place of your malformed directory. You could do it from your amplify/#current-cloud-backend/api/<resource-name> directory as well if it's not malformed.

**Comment by lookitsatravis** [comment]
Thanks @kaustavghosh06. Yep I had a backup, so nothing lost. Happy to provide more information if you need anything.

**Comment by jesse-bonzo** [comment]
This is happening for me in the Amplify console.

**Comment by kaustavghosh06** [comment]
@jesse-bonzo Amplify console hasn't updated the latest build of the CLI, although they're actively working on getting the CLI build ready for a release soon. 
Please continue using the @multienv version of the CLI, if you're actively using the Amplify console.

**Comment by jesse-bonzo** [comment]
The `amplify --version` command returns 1.1.0 in the Amplify console, and the file not found errors are seen. It seems very similar to me.

```
# Starting phase: build
# Executing command: amplify --version
2019-02-12T23:52:54.754Z [INFO]: 1.1.0
2019-02-12T23:52:54.761Z [INFO]: # Executing command: npm config set bin-links false
2019-02-12T23:52:54.931Z [INFO]: # Executing command: export STACKINFO={ "awscloudformation": { "AuthRoleName": "bespin-20190109095849-authRole", "UnauthRoleArn": "arn:aws:iam::111229220926:role/bespin-20190109095849-unauthRole", "AuthRoleArn": "arn:aws:iam::111229220926:role/bespin-20190109095849-authRole", "Region": "us-west-2", "DeploymentBucketName": "bespin-20190109095849-deployment", "UnauthRoleName": "bespin-20190109095849-unauthRole", "StackName": "bespin-20190109095849", "StackId": "arn:aws:cloudformation:us-west-2:111229220926:stack/bespin-20190109095849/37c03be0-1438-11e9-82b2-503aca41a0fd" }, "categories": { "auth": { "cognito1cb72e70": {} } } }
2019-02-12T23:52:54.935Z [INFO]: # Executing command: amplifyPush --environment jbonzo
2019-02-12T23:52:54.937Z [INFO]: # Start initializing Amplify environment: jbonzo
2019-02-12T23:52:54.937Z [INFO]: # Importing Amplify environment: jbonzo (amplify env import)
2019-02-12T23:52:56.347Z [INFO]: Successfully added environment from your project
2019-02-12T23:52:56.354Z [INFO]: # Initializing existing Amplify environment: jbonzo (amplify init)
2019-02-12T23:52:57.760Z [INFO]: Note: It is recommended to run this command from the root of your app directory
2019-02-12T23:52:57.761Z [INFO]: You're initializing your project with a beta version of the CLI which supports multiple environments of your project
2019-02-12T23:52:59.124Z [WARNING]: - Initializing your environment: jbonzo
2019-02-12T23:52:59.791Z [WARNING]: ✔ Initialized provider successfully.
2019-02-12T23:53:04.228Z [INFO]: 
Migrating your API. This may take a few minutes.
2019-02-12T23:53:04.238Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
2019-02-12T23:53:04.240Z [WARNING]: ✖ There was an error initializing your environment.
2019-02-12T23:53:04.241Z [INFO]: init failed
2019-02-12T23:53:04.265Z [INFO]: { Error: ENOENT: no such file or directory, open '/codebuild/output/src091921849/src/bespin/amplify/backend/api/bespin/build/cloudformation-template.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at /home/circleci/repo/packages/graphql-transformer-core/src/util/amplifyUtils.ts:790:8
    at step (/root/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/amplifyUtils.js:40:23)
    at Object.next (/root/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/amplifyUtils.js:21:53)
    at /root/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/amplifyUtils.js:15:71
    at new Promise (<anonymous>)
    at __awaiter (/root/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/amplifyUtils.js:11:12)
    at updateToIntermediateProject (/root/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/amplifyUtils.js:924:12)
    at Object.<anonymous> (/home/circleci/repo/packages/graphql-transformer-core/src/util/amplifyUtils.ts:510:11)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/codebuild/output/src091921849/src/bespin/amplify/backend/api/bespin/build/cloudformation-template.json' }
2019-02-12T23:53:04.273Z [ERROR]: !!! Build failed
2019-02-12T23:53:04.432Z [ERROR]: !!! Non-Zero Exit Code detected
2019-02-12T23:53:04.432Z [INFO]: # Starting Environment Caching...
2019-02-12T23:53:04.432Z [INFO]: Uploading environment cache artifact...
2019-02-12T23:53:04.515Z [INFO]: # Environment Caching completed
Terminating logging...
```

**Comment by swaminator** [comment]
@jesse-bonzo What steps did you take in the Console?
1) Can I take a look at your build settings?
2) What amplify CLI categories have you enabled?

**Comment by jesse-bonzo** [comment]
When I make a change and push my code, a build is triggered in amplify console, and then the error is seen.

My amplify.yml:
```
version: 0.1
backend:
  phases:
    # IMPORTANT - Please verify your build commands
    build:
      commands:
        # print out the version so we can know what's been fixed in amplify
        - amplify --version
        # setting bin-links false to prevent issues on the build server
        - npm config set bin-links false
        - "# Get Amplify CLI Cloud-Formation stack info from environment cache"
        - export STACKINFO="$(envCache --get stackInfo)"
        - "# Execute Amplify CLI with the helper script"
        - amplifyPush --environment $AWS_BRANCH
        - "# Store Amplify CLI Cloud-Formation stack info in environment cache"
        - >-
          envCache --set stackInfo "$(amplify env get --json --name
          $AWS_BRANCH)"
frontend:
  phases:
    build:
      commands:
        - yarn
        - CI=true yarn test
        - yarn run build
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: build
    files:
      - "**/*"
```

The categories enabled are Function, API, Auth, Hosting, and Storage.

**Comment by swaminator** [comment]
@jesse-bonzo can you run `amplify push` from your local workstation? How many environments do you currently have (including Console+CLI)?

**Comment by jesse-bonzo** [comment]
@nikhil-dabhade Yes, amplify push works from my local workstation, but the version is "0.2.2-multienv.1". We have 5 environments setup in Console, and 3 local environments.

**Comment by nikhil-dabhade** [comment]
@swaminator ^^

**Comment by garyleefight** [comment]
@jesse-bonzo We tried to reproduce your issue and do find some bugs on the CLI. But the error message is slightly different from yours. We are not sure whether we fixed the issue for you. 
Try to rebuild your project online (We have updated CLI version to 1.1.2).
If your project still won't work, please send email to aws-amplify-customer@amazon.com.

**Comment by kaustavghosh06** [comment]
@jesse-bonzo  Were you able to deploy successfully?

**Comment by jesse-bonzo** [comment]
Unfortunately no, I am still getting the same error in the Amplify Console

```
2019-02-21T17:20:14.171Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
2019-02-21T17:20:14.172Z [WARNING]: ✖ There was an error initializing your environment.
2019-02-21T17:20:14.173Z [INFO]: init failed
2019-02-21T17:20:14.203Z [INFO]: { Error: ENOENT: no such file or directory, open '/codebuild/output/src127021109/src/bespin/amplify/backend/api/bespin/build/cloudformation-template.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at /home/circleci/repo/packages/graphql-transformer-core/src/util/amplifyUtils.ts:790:8
    at step (/root/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/amplifyUtils.js:40:23)
    at Object.next (/root/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/amplifyUtils.js:21:53)
    at /root/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/amplifyUtils.js:15:71
    at new Promise (<anonymous>)
    at __awaiter (/root/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/amplifyUtils.js:11:12)
    at updateToIntermediateProject (/root/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/amplifyUtils.js:924:12)
    at Object.<anonymous> (/home/circleci/repo/packages/graphql-transformer-core/src/util/amplifyUtils.ts:510:11)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/codebuild/output/src127021109/src/bespin/amplify/backend/api/bespin/build/cloudformation-template.json' }
2019-02-21T17:20:14.235Z [ERROR]: !!! Build failed
2019-02-21T17:20:14.347Z [ERROR]: !!! Non-Zero Exit Code detected
2019-02-21T17:20:14.347Z [INFO]: # Starting Environment Caching...
2019-02-21T17:20:14.348Z [INFO]: Uploading environment cache artifact...
2019-02-21T17:20:14.500Z [INFO]: # Environment Caching completed
```

I've worked around the issue by installing an older version of the amplify cli in my build script.

**Comment by kaustavghosh06** [comment]
@lookitsatravis Are you still stuck on this?

**Comment by lookitsatravis** [comment]
@kaustavgbosh06 No. I had a back up and after making some corrections to some CF templates it deployed successfully. I was merely reporting the original issue. It seemed to only happen during a deploy failure on the attempt which also does the update/migration to the new structure. Once it was successfully upgraded, future failed deployments did not result in this behavior.
