### ISSUE TITLE
Error: Found '}' where a key name was expected (check your syntax or use quotes if the key name includes {}[],: or whitespace) at line 3,7 >>>      }

### ISSUE THREAD

**Issue by awhig** [aws-amplify/amplify-cli#8837]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.0.0

### Amplify CLI Version

Upgraded to latest cli today and can't run any amplify commands

### What operating system are you using?

Mac

### Amplify Categories

Not applicable

### Amplify Commands

push

### Describe the bug

any ampllify commands come backs with this error.

`amplify version `as well

`amplify
Found '}' where a key name was expected (check your syntax or use quotes if the key name includes {}[],: or whitespace) at line 3,7 >>>      },
      "last ...
Error: Found '}' where a key name was expected (check your syntax or use quotes if the key name includes {}[],: or whitespace) at line 3,7 >>>      },
      "last ...
    at error (/Users/rcook/.nvm/versions/node/v16.0.0/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:41:11)
    at keyname (/Users/rcook/.nvm/versions/node/v16.0.0/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:163:9)
    at object (/Users/rcook/.nvm/versions/node/v16.0.0/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:353:15)
    at legacyRootValue (/Users/rcook/.nvm/versions/node/v16.0.0/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:434:28)
    at Object.module.exports (/Users/rcook/.nvm/versions/node/v16.0.0/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:454:23)
    at Function.JSONUtilities.parse (/Users/rcook/.nvm/versions/node/v16.0.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/jsonUtilities.js:91:22)
    at Function.JSONUtilities.readJson (/Users/rcook/.nvm/versions/node/v16.0.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/jsonUtilities.js:47:32)
    at StateManager.getData (/Users/rcook/.nvm/versions/node/v16.0.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/state-manager/stateManager.js:278:56)
    at StateManager.getMeta (/Users/rcook/.nvm/versions/node/v16.0.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/state-manager/stateManager.js:42:31)
    at checkIfMobileHubProject (/Users/rcook/.nvm/versions/node/v16.0.0/lib/node_modules/@aws-amplify/cli/lib/utils/mobilehub-support.js:19:50)
    at Object.ensureMobileHubCommandCompatibility (/Users/rcook/.nvm/versions/node/v16.0.0/lib/node_modules/@aws-amplify/cli/lib/utils/mobilehub-support.js:7:5)
    at Object.run (/Users/rcook/.nvm/versions/node/v16.0.0/lib/node_modules/@aws-amplify/cli/lib/index.js:158:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
`

### Expected behavior

should be able to get version or push or publish

### Reproduction steps

amplify version

or amplify push

or amplify publish

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by awhig** [comment]
Trying to track down what's wrong.

It looks like the exception is happening when it's trying to parse this json file in my project.

`/amplify/backend/amplify-meta.json`

When I open that file, it seems to be corrupted.

If I open the file in the terminal, it thinks it's a binary file and shows junk. If I open it in VSCode, it gives me a warning, but I can open it anyway. After the junk bytes, it shows the following lines, and the rest of the file seems to look ok.

If someone can tell me what this first part of the file should look like, I probably can fix it. I do not know why this happened though. I think I CTRL-C during a push or publish earlier today. Could that have caused it?


`yPoolName": "r8spedapp34a14510_identitypool_34a14510__devagain",
        "UserPoolName": "r8spedapp34a14510_userpool_34a14510"
      },
      "lastPushDirHash": "Te6gXcKI9WW/WpVTXw1MMEk2pGc="
    },
    "userPoolGroups": {`

**Comment by yuth** [comment]
Do you know how the file got corrupted? Was there a git merge? Or was it opened in some editor which could have caused this?

 Could you try to restore this file from your version control like git and see if it works.

**Comment by awhig** [comment]
@yuth I do not know how it got corrupted. The whole amplify directory is in gitignore, so this file is not tracked. I've never opened this file until now, trying to fix this issue.  Can I delete this file, and maybe amplify recreates it or something? I do not know how this file is used.

**Comment by awhig** [comment]
I found in the `amplify/#current-cloud-backend` directory another copy/version of the `amplify-meta.json` file. I ended replacing the corrupted file with this version. I haven't changed the backend code since the previous push, so I believe everything there is up to date. I'm hoping this is an ok solution. 

Since the whole amplify push/publish process is opaque to me, I'm not 100% sure I'm not screwing up anything, but I think it's ok. If anyone knows for sure to let me know that would be great.  If this issue is something that can occur, and break the whole thing, maybe the file should not be placed in the .gitignore file so that previous versions can be retrieved in case of corruption.

**Comment by yuth** [comment]
The way to restore this file would be to run [`amplify pull`](https://docs.amplify.aws/cli/teams/commands/#environment-cli-commands) command. If you want to restore it to a new project you could use 
```shell
$ amplify pull --appId <app-id-from-amplify-console> --envName <env-name>
```

> Since the whole amplify push/publish process is opaque to me, I'm not 100% sure I'm not screwing up anything, but I think it's ok. If anyone knows for sure to let me know that would be great. If this issue is something that can occur, and break the whole thing, maybe the file should not be placed in the .gitignore file so that previous versions can be retrieved in case of corruption.

Amplify CLI zips the backend directory and ts content and uploads them to S3 deployment bucket. This file is downloaded and unzipped to `amplify/#current-cloud-backend` when pull command is executed. We dont track them using git as these folders contain information about environment and merging between branches will cause issues.

Please feel free to comment if the issue happens in the future with detail repro steps so we can investigate this further
