### ISSUE TITLE
`TypeError: args.fields.forEach is not a function` when generating transformers

### ISSUE THREAD

**Issue by maniramezan** [aws-amplify/amplify-cli#8899]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

nom

### If applicable, what version of Node.js are you using?

v17.0.1

### Amplify CLI Version

7.3.2

### What operating system are you using?

macOS (12.1 Beta (21C5031d))

### Amplify Categories

api

### Amplify Commands

add

### Describe the bug

Using `amplify api gql-compile` or `amplify api rebuild` with the attached graphql schema causes the amplify crashes during generating transformers

### Expected behavior

It runs and builds the resolvers

### Reproduction steps

1. Run `amplify api add`
2. Add empty graphql api
3. Update `schema.graphql` with the attached content
4. Run `amplify api gql-compile` or `amplify api rebuild`
5. Notice the error message instead of success

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
enum GameSessionStatus {
  PENDING
  ONGOING
  ANSWERING
  FINISHED
}

type GameSession @model(subscriptions: null) {
  id: ID!
  game: Game! @connection
  startedTimeUTC: AWSDateTime
  votingTimeSec: Int
  hintsRevealTimeSec: Int
  gameCode: Int
  status: GameSessionStatus!
  multiDeviceMode: Boolean
  teams: [Team] @connection(keyName: "byGameSession", fields: ["id"])
}

type Game @model(subscriptions: null, timestamps: null) {
  id: ID!
  title: String
  description: String
  isAdvanced: Boolean!
  grade: String
  questions: [Question] @connection(keyName: "byGame", fields: ["id"])
}

type Question
  @model(subscriptions: null, timestamps: null)
  @key(name: "byGame", fields: ["gameId", "id"]) {
  id: ID!
  gameId: ID!
  question: String!
  answer: String!
  trickAnswers: AWSJSON
  imageUrl: String
  instructions: AWSJSON
}

type Team
  @model(subscriptions: null)
  @key(name: "byGameSession", fields: ["gameSessionId"]) {
  id: ID!
  name: String!
  gameSessionId: ID!
  questionId: ID!
  question: Question @connection(fields: "questionId")
  trickiestAnswerID: ID!
  teamMembers: [TeamMember] @connection(keyName: "byTeam", fields: ["id"])
}

type TeamMember
  @model(subscriptions: null)
  @key(name: "byTeam", fields: ["teamId"]) {
  id: ID!
  teamId: ID!
  team: Team! @connection(fields: ["timeId"])
  submittedAnswer: SubmittedAnswer
    @connection(keyName: "byTeamMember", fields: ["id"])
  isFacilitator: Boolean
}

type SubmittedAnswer
  @model(timestamps: { createdAt: "submittedDateTimeUTC", updatedAt: null })
  @key(name: "byTeam", fields: ["teamMemberId", "submittedDateTimeUTC"]) {
  id: ID!
  teamMemberId: ID!
  isChosenTrickAnswer: Boolean
  isChosenBySystem: Boolean
  text: String
  submittedDateTimeUTC: AWSDateTime!
}


```

</details>

### Log output

<details>

```
# Put your logs below this line
2021-11-16T06:02:07.296Z|info : amplify help core  
2021-11-16T06:02:14.177Z|info : amplify init core help 
2021-11-16T06:02:14.213Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2021-11-16T06:04:25.335Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["righton"])
2021-11-16T06:04:25.337Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2021-11-16T06:04:25.338Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["righton"])
2021-11-16T06:04:25.348Z|info : amplify-provider-awscloudformation.amplify-service-permission-check.checkAmplifyServiceIAMPermission.amplifyClient.listApps([])
2021-11-16T06:04:25.572Z|info : amplify-provider-awscloudformation.amplify-service-manager.init.amplifyClient.createApp([{"name":"[***]ile","environmentVariables":{"_LIVE_PACKAGE_UPDATES":"[{\"pkg\":\"@aws-amplify/cli\",\"type\":\"npm\",\"version\":\"latest\"}]"}}])
2021-11-16T06:04:28.998Z|info : amplify-provider-awscloudformation.amplify-service-manager.init.amplifyClient.getBackendEnvironment([{"appId":"[***]0xdfv4","environmentName":"[***]ev"}])
2021-11-16T06:04:29.111Z|error : amplify-provider-awscloudformation.amplify-service-manager.init.amplifyClient.getBackendEnvironment([{"appId":"[***]0xdfv4","environmentName":"[***]ev"}])
NotFoundException: BackendEnvironment dev does not exist.
2021-11-16T06:04:29.112Z|info : amplify-provider-awscloudformation.amplify-service-manager.init.amplifyClient.getBackendEnvironment([{"appId":"[***]0xdfv4","environmentName":"[***]ev","stackName":"[***]ify-[***]ile-[***]ev-[***]25","deploymentArtifacts":"amplify-mobile-dev-10425-deployment"}])
2021-11-16T06:04:29.219Z|info : amplify-provider-awscloudformation.aws-cfn.cfnModel.createStack([{"StackName":"[***]ify-[***]ile-[***]ev-[***]25","Capabilities":["CAPABILITY_NAMED_IAM","CAPABILITY_AUTO_EXPAND"],"TemplateBody":"{\"AWSTemplateFormatVersion\":\"2010-09-09\",\"Description\":\"Root Stack for AWS Amplify CLI\",\"Parameters\":{\"[***]cketName\":{\"Description\":\"Name of the common deployment bucket provided by the parent stack\",\"Type\":\"String\",\"Default\":\"DeploymentBucket\"},\"[***]eName\":{\"Type\":\"String\",\"Default\":\"AuthRoleName\"},\"[***]leName\":{\"Type\":\"String\",\"Default\":\"UnauthRoleName\"}},\"Resources\":{\"DeploymentBucket\":{\"Type\":\"AWS::S3::Bucket\",\"DeletionPolicy\":\"Retain\",\"Properties\":{\"BucketName\":{\"Ref\":\"DeploymentBucketName\"},\"BucketEncryption\":{\"ServerSideEncryptionConfiguration\":[{\"ServerSideEncryptionByDefault\":{\"SSEAlgorithm\":\"AES256\"}}]}}},\"AuthRole\":{\"Type\":\"AWS::IAM::Role\",\"Properties\":{\"RoleName\":{\"Ref\":\"AuthRoleName\"},\"AssumeRolePolicyDocument\":{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"\",\"Effect\":\"Deny\",\"Principal\":{\"Federated\":\"cognito-identity.amazonaws.com\"},\"Action\":\"sts:AssumeRoleWithWebIdentity\"}]}}},\"UnauthRole\":{\"Type\":\"AWS::IAM::Role\",\"Properties\":{\"RoleName\":{\"Ref\":\"UnauthRoleName\"},\"AssumeRolePolicyDocument\":{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"\",\"Effect\":\"Deny\",\"Principal\":{\"Federated\":\"cognito-identity.amazonaws.com\"},\"Action\":\"sts:AssumeRoleWithWebIdentity\"}]}}}},\"Outputs\":{\"Region\":{\"Description\":\"CloudFormation provider root stack Region\",\"Value\":{\"Ref\":\"AWS::Region\"},\"Export\":{\"Name\":{\"Fn::Sub\":\"${AWS::StackName}-Region\"}}},\"StackName\":{\"Description\":\"CloudFormation provider root stack ID\",\"Value\":{\"Ref\":\"AWS::StackName\"},\"Export\":{\"Name\":{\"Fn::Sub\":\"${AWS::StackName}-StackName\"}}},\"StackId\":{\"Description\":\"CloudFormation provider root stack name\",\"Value\":{\"Ref\":\"AWS::StackId\"},\"Export\":{\"Name\":{\"Fn::Sub\":\"${AWS::StackName}-StackId\"}}},\"DeploymentBucketName\":{\"Description\":\"CloudFormation provider root stack deployment bucket name\",\"Value\":{\"Ref\":\"DeploymentBucketName\"},\"Export\":{\"Name\":{\"Fn::Sub\":\"${AWS::StackName}-DeploymentBucketName\"}}},\"AuthRoleArn\":{\"Value\":{\"Fn::GetAtt\":[\"AuthRole\",\"Arn\"]}},\"UnauthRoleArn\":{\"Value\":{\"Fn::GetAtt\":[\"UnauthRole\",\"Arn\"]}},\"AuthRoleName\":{\"Value\":{\"Ref\":\"AuthRole\"}},\"UnauthRoleName\":{\"Value\":{\"Ref\":\"UnauthRole\"}}}}","Parameters":[{"ParameterKey":"DeploymentBucketName","ParameterValue":"amplify-mobile-dev-10425-deployment"},{"ParameterKey":"AuthRoleName","ParameterValue":"amplify-mobile-dev-10425-authRole"},{"ParameterKey":"UnauthRoleName","ParameterValue":"amplify-mobile-dev-10425-unauthRole"}],"Tags":[{"Key":"[***]tack","Value":"dev"},{"Key":"[***]ication","Value":"mobile"}]}])
2021-11-16T06:04:29.619Z|info : amplify-provider-awscloudformation.aws-cfn.cfnModel.createStack([{"StackName":"[***]ify-[***]ile-[***]ev-[***]25","Capabilities":["CAPABILITY_NAMED_IAM","CAPABILITY_AUTO_EXPAND"],"TemplateBody":"{\"AWSTemplateFormatVersion\":\"2010-09-09\",\"Description\":\"Root Stack for AWS Amplify CLI\",\"Parameters\":{\"[***]cketName\":{\"Description\":\"Name of the common deployment bucket provided by the parent stack\",\"Type\":\"String\",\"Default\":\"DeploymentBucket\"},\"[***]eName\":{\"Type\":\"String\",\"Default\":\"AuthRoleName\"},\"[***]leName\":{\"Type\":\"String\",\"Default\":\"UnauthRoleName\"}},\"Resources\":{\"DeploymentBucket\":{\"Type\":\"AWS::S3::Bucket\",\"DeletionPolicy\":\"Retain\",\"Properties\":{\"BucketName\":{\"Ref\":\"DeploymentBucketName\"},\"BucketEncryption\":{\"ServerSideEncryptionConfiguration\":[{\"ServerSideEncryptionByDefault\":{\"SSEAlgorithm\":\"AES256\"}}]}}},\"AuthRole\":{\"Type\":\"AWS::IAM::Role\",\"Properties\":{\"RoleName\":{\"Ref\":\"AuthRoleName\"},\"AssumeRolePolicyDocument\":{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"\",\"Effect\":\"Deny\",\"Principal\":{\"Federated\":\"cognito-identity.amazonaws.com\"},\"Action\":\"sts:AssumeRoleWithWebIdentity\"}]}}},\"UnauthRole\":{\"Type\":\"AWS::IAM::Role\",\"Properties\":{\"RoleName\":{\"Ref\":\"UnauthRoleName\"},\"AssumeRolePolicyDocument\":{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"\",\"Effect\":\"Deny\",\"Principal\":{\"Federated\":\"cognito-identity.amazonaws.com\"},\"Action\":\"sts:AssumeRoleWithWebIdentity\"}]}}}},\"Outputs\":{\"Region\":{\"Description\":\"CloudFormation provider root stack Region\",\"Value\":{\"Ref\":\"AWS::Region\"},\"Export\":{\"Name\":{\"Fn::Sub\":\"${AWS::StackName}-Region\"}}},\"StackName\":{\"Description\":\"CloudFormation provider root stack ID\",\"Value\":{\"Ref\":\"AWS::StackName\"},\"Export\":{\"Name\":{\"Fn::Sub\":\"${AWS::StackName}-StackName\"}}},\"StackId\":{\"Description\":\"CloudFormation provider root stack name\",\"Value\":{\"Ref\":\"AWS::StackId\"},\"Export\":{\"Name\":{\"Fn::Sub\":\"${AWS::StackName}-StackId\"}}},\"DeploymentBucketName\":{\"Description\":\"CloudFormation provider root stack deployment bucket name\",\"Value\":{\"Ref\":\"DeploymentBucketName\"},\"Export\":{\"Name\":{\"Fn::Sub\":\"${AWS::StackName}-DeploymentBucketName\"}}},\"AuthRoleArn\":{\"Value\":{\"Fn::GetAtt\":[\"AuthRole\",\"Arn\"]}},\"UnauthRoleArn\":{\"Value\":{\"Fn::GetAtt\":[\"UnauthRole\",\"Arn\"]}},\"AuthRoleName\":{\"Value\":{\"Ref\":\"AuthRole\"}},\"UnauthRoleName\":{\"Value\":{\"Ref\":\"UnauthRole\"}}}}","Parameters":[{"ParameterKey":"DeploymentBucketName","ParameterValue":"amplify-mobile-dev-10425-deployment"},{"ParameterKey":"AuthRoleName","ParameterValue":"amplify-mobile-dev-10425-authRole"},{"ParameterKey":"UnauthRoleName","ParameterValue":"amplify-mobile-dev-10425-unauthRole"}],"Tags":[{"Key":"[***]tack","Value":"dev"},{"Key":"[***]ication","Value":"mobile"}]}])
2021-11-16T06:04:34.629Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]ify-[***]ile-[***]ev-[***]25"}])
2021-11-16T06:04:34.777Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]rmation:us-[***]st-[***]49:stack/[***]ify-[***]ile-[***]ev-[***]25/[***]8140-[***]a3-[***]ec-[***]68-[***]758a1"}])
2021-11-16T06:04:39.625Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]ify-[***]ile-[***]ev-[***]25"}])
2021-11-16T06:04:39.772Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]rmation:us-[***]st-[***]49:stack/[***]ify-[***]ile-[***]ev-[***]25/[***]8140-[***]a3-[***]ec-[***]68-[***]758a1"}])
2021-11-16T06:04:44.628Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]ify-[***]ile-[***]ev-[***]25"}])
2021-11-16T06:04:44.769Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]rmation:us-[***]st-[***]49:stack/[***]ify-[***]ile-[***]ev-[***]25/[***]8140-[***]a3-[***]ec-[***]68-[***]758a1"}])
2021-11-16T06:04:49.627Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]ify-[***]ile-[***]ev-[***]25"}])
2021-11-16T06:04:49.771Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]rmation:us-[***]st-[***]49:stack/[***]ify-[***]ile-[***]ev-[***]25/[***]8140-[***]a3-[***]ec-[***]68-[***]758a1"}])
2021-11-16T06:04:54.630Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]ify-[***]ile-[***]ev-[***]25"}])
2021-11-16T06:04:54.784Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]rmation:us-[***]st-[***]49:stack/[***]ify-[***]ile-[***]ev-[***]25/[***]8140-[***]a3-[***]ec-[***]68-[***]758a1"}])
2021-11-16T06:04:59.633Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]ify-[***]ile-[***]ev-[***]25"}])
2021-11-16T06:04:59.773Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]rmation:us-[***]st-[***]49:stack/[***]ify-[***]ile-[***]ev-[***]25/[***]8140-[***]a3-[***]ec-[***]68-[***]758a1"}])
2021-11-16T06:05:04.631Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]ify-[***]ile-[***]ev-[***]25"}])
2021-11-16T06:05:09.631Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]ify-[***]ile-[***]ev-[***]25"}])
2021-11-16T06:05:14.633Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]ify-[***]ile-[***]ev-[***]25"}])
2021-11-16T06:05:19.634Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]ify-[***]ile-[***]ev-[***]25"}])
2021-11-16T06:05:24.634Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]ify-[***]ile-[***]ev-[***]25"}])
2021-11-16T06:05:29.637Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]ify-[***]ile-[***]ev-[***]25"}])
2021-11-16T06:05:30.130Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["righton"])
2021-11-16T06:05:30.130Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2021-11-16T06:05:30.130Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["righton"])
2021-11-16T06:05:30.137Z|info : amplify-provider-awscloudformation.attach-backend.storeCurrentCloudBackend.s3.uploadFile([{"Key":"[***]rent-[***]ud-[***]d.zip"}])
2021-11-16T06:05:30.138Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Key":"[***]rent-[***]ud-[***]d.zip","Bucket":"[***]ify-[***]ile-[***]ev-[***]25-[***]ment"}])
2021-11-16T06:05:30.416Z|info : amplify-provider-awscloudformation.attach-backend.uploadFile.s3.uploadFile([{"Key":"[***]ify-[***]json"}])
2021-11-16T06:05:30.416Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Key":"[***]ify-[***]json","Bucket":"[***]ify-[***]ile-[***]ev-[***]25-[***]ment"}])
2021-11-16T06:05:30.551Z|info : amplify-provider-awscloudformation.aws-s3.deleteDirectory.s3.getAllObjectVersions([{"BucketName":"[***]ify-[***]ile-[***]ev-[***]25-[***]ment"}])
2021-11-16T06:05:30.551Z|info : amplify-provider-awscloudformation.aws-s3.getAllObjectKey.s3.listObjectVersions([{"Bucket":"[***]ify-[***]ile-[***]ev-[***]25-[***]ment","Prefix":"hooks/"}])
2021-11-16T06:05:30.685Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Key":"[***]ks/[***]st-[***]sample","Bucket":"[***]ify-[***]ile-[***]ev-[***]25-[***]ment"}])
2021-11-16T06:05:30.838Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Key":"[***]ks/[***]re-[***]sample","Bucket":"[***]ify-[***]ile-[***]ev-[***]25-[***]ment"}])
2021-11-16T06:05:31.007Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Key":"[***]ks/[***]E.md","Bucket":"[***]ify-[***]ile-[***]ev-[***]25-[***]ment"}])
2021-11-16T06:06:58.733Z|info : amplify add api  
2021-11-16T06:06:58.772Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2021-11-16T06:08:14.038Z|info : amplify help api  
2021-11-16T06:08:24.747Z|info : amplify gql-compile api  
2021-11-16T06:08:24.786Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2021-11-16T06:09:08.091Z|info : amplify gql-compile api  
2021-11-16T06:09:08.128Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2021-11-16T06:09:31.818Z|info : amplify gql-compile api  
2021-11-16T06:09:31.856Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2021-11-16T06:11:40.020Z|info : amplify gql-compile api  
2021-11-16T06:11:40.057Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2021-11-16T06:12:43.837Z|info : amplify gql-compile api  
2021-11-16T06:12:43.876Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2021-11-16T06:14:16.865Z|info : amplify gql-compile api  
2021-11-16T06:14:16.902Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2021-11-16T06:18:10.810Z|info : amplify gql-compile api  
2021-11-16T06:18:10.850Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2021-11-16T06:18:21.340Z|info : amplify rebuild api  
2021-11-16T06:18:21.379Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2021-11-16T06:18:45.789Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["righton"])
2021-11-16T06:18:45.790Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2021-11-16T06:18:45.790Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["righton"])
2021-11-16T06:18:46.122Z|error : amplify-provider-awscloudformation.push-resources.run([{"resourcesToBeCreated":[{"service":"AppSync","providerPlugin":"[***]rmation","output":{"authConfig":{"defaultAuthentication":{"authenticationType":"API_KEY","apiKeyConfig":{"apiKeyExpirationDays":7}},"additionalAuthenticationProviders":[]}},"resourceName":"[***]ile","category":"api"}],"resourcesToBeUpdated":[],"resourcesToBeSynced":[],"resourcesToBeDeleted":[],"tagsUpdated":false,"allResources":[{"service":"AppSync","providerPlugin":"[***]rmation","output":{"authConfig":{"defaultAuthentication":{"authenticationType":"API_KEY","apiKeyConfig":{"apiKeyExpirationDays":7}},"additionalAuthenticationProviders":[]}},"resourceName":"[***]ile","category":"api"}]}])
TypeError: args.fields.forEach is not a function
2021-11-16T06:21:10.084Z|info : amplify rebuild api  
2021-11-16T06:21:10.123Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2021-11-16T06:23:01.333Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["righton"])
2021-11-16T06:23:01.334Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2021-11-16T06:23:01.334Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["righton"])
2021-11-16T06:23:01.734Z|error : amplify-provider-awscloudformation.push-resources.run([{"resourcesToBeCreated":[{"service":"AppSync","providerPlugin":"[***]rmation","output":{"authConfig":{"defaultAuthentication":{"authenticationType":"API_KEY","apiKeyConfig":{"apiKeyExpirationDays":7}},"additionalAuthenticationProviders":[]}},"resourceName":"[***]ile","category":"api"}],"resourcesToBeUpdated":[],"resourcesToBeSynced":[],"resourcesToBeDeleted":[],"tagsUpdated":false,"allResources":[{"service":"AppSync","providerPlugin":"[***]rmation","output":{"authConfig":{"defaultAuthentication":{"authenticationType":"API_KEY","apiKeyConfig":{"apiKeyExpirationDays":7}},"additionalAuthenticationProviders":[]}},"resourceName":"[***]ile","category":"api"}]}])
TypeError: args.fields.forEach is not a function
2021-11-16T06:31:15.131Z|info : amplify rebuild api  
2021-11-16T06:31:15.171Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2021-11-16T06:31:21.866Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["righton"])
2021-11-16T06:31:21.867Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2021-11-16T06:31:21.867Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["righton"])
2021-11-16T06:31:22.482Z|error : amplify-provider-awscloudformation.push-resources.run([{"resourcesToBeCreated":[{"service":"AppSync","providerPlugin":"[***]rmation","output":{"authConfig":{"defaultAuthentication":{"authenticationType":"API_KEY","apiKeyConfig":{"apiKeyExpirationDays":7}},"additionalAuthenticationProviders":[]}},"resourceName":"[***]ile","category":"api"}],"resourcesToBeUpdated":[],"resourcesToBeSynced":[],"resourcesToBeDeleted":[],"tagsUpdated":false,"allResources":[{"service":"AppSync","providerPlugin":"[***]rmation","output":{"authConfig":{"defaultAuthentication":{"authenticationType":"API_KEY","apiKeyConfig":{"apiKeyExpirationDays":7}},"additionalAuthenticationProviders":[]}},"resourceName":"[***]ile","category":"api"}]}])
TypeError: args.fields.forEach is not a function
2021-11-16T06:33:17.179Z|info : amplify gql-compile api  
2021-11-16T06:33:17.219Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2021-11-16T06:35:48.492Z|info : amplify gql-compile api  
2021-11-16T06:35:48.530Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2021-11-16T06:42:36.305Z|info : amplify gql-compile api  
2021-11-16T06:42:36.344Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2021-11-16T17:58:52.061Z|info : amplify gql-compile api  
2021-11-16T17:58:52.100Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2021-11-16T18:50:20.455Z|info : amplify version core  

```

</details>

### Additional information

Logs from when running `amplify api rebuild`

```
✖ An error occurred when pushing the resources to the cloud
args.fields.forEach is not a function
TypeError: args.fields.forEach is not a function
    at ModelConnectionTransformer.connectionWithKey (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/graphql-connection-transformer/src/ModelConnectionTransformer.ts:557:17)
    at ModelConnectionTransformer.field (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/graphql-connection-transformer/src/ModelConnectionTransformer.ts:225:12)
    at GraphQLTransform.transformField (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/GraphQLTransform.ts:377:25)
    at GraphQLTransform.transformObject (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/GraphQLTransform.ts:355:12)
    at GraphQLTransform.transform (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/GraphQLTransform.ts:271:18)
    at _buildProject (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/util/amplifyUtils.ts:92:35)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at ensureMissingStackMappings (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/util/amplifyUtils.ts:166:23)
    at Object.buildProject (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/util/amplifyUtils.ts:51:3)
    at Object.transformGraphQLSchema (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/transform-graphql-schema.ts:516:29)
    at Object.run (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/push-resources.ts:150:5)
    at async Promise.all (index 0)
    at providersPush (/opt/homebrew/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/push-resources.ts:175:3)
    at AmplifyToolkit.pushResources [as _pushResources] (/opt/homebrew/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/push-resources.ts:84:9)
    at Object.executeAmplifyCommand (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/src/index.ts:204:3)
    at executePluginModuleCommand (/opt/homebrew/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:178:3)
    at Object.executeCommand (/opt/homebrew/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:30:5)
    at Object.run (/opt/homebrew/lib/node_modules/@aws-amplify/cli/src/index.ts:205:5)
```

**Comment by cjihrig** [comment]
> question: Question @connection(fields: "questionId")

You should be able to work around this bug by placing "questionId" in an array.

**Comment by maniramezan** [comment]
@cjihrig Perfect, thanks! That workaround worked : )
