### ISSUE TITLE
Error building Amplify Cognito with React on AWS Amplify

### ISSUE THREAD

**Issue by sisaku8** [aws-amplify/amplify-cli#8908]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

7.3.3

### What operating system are you using?

Windows

### Amplify Categories

auth

### Amplify Commands

Not applicable

### Describe the bug

Dear all,

I have created a simple Frontend React-App. Afterwards I have implemented the Cognito Environment from AWS. Everything works on my local machine but on AWS Amplify itself, the build does not work. I have searched for hours but I cannot find an answers that helps me solving the problem. I get an error that a certain JSON file cannot be found. I would be glad about your help. Thanks in advance!

### Expected behavior

Since the local build works, I would expect that the build on AWS works as well.

### Reproduction steps

Try to build my Git-Repo on AWS

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line
2021-11-16T23:22:36.041Z [INFO]: Git SSH Key acquired
2021-11-16T23:22:36.200Z [INFO]: Identity added: /root/.ssh/git_rsa (/root/.ssh/git_rsa)
2021-11-16T23:22:36.418Z [INFO]: Cloning into 'create-react-app-auth-amplify'...
2021-11-16T23:22:41.887Z [INFO]: # Checking for Git submodules at: /codebuild/output/src033637649/src/create-react-app-auth-amplify/.gitmodules
2021-11-16T23:22:41.973Z [INFO]: # Retrieving environment cache...
2021-11-16T23:22:42.000Z [INFO]: # Retrieved environment cache
2021-11-16T23:22:42.000Z [INFO]: ---- Setting Up SSM Secrets ----
2021-11-16T23:22:42.000Z [INFO]: SSM params {"Path":"/amplify/d2ntvw7kn00s80/devb/","WithDecryption":true}
2021-11-16T23:22:42.051Z [INFO]: # Ensuring NPM package '@aws-amplify/cli' is version: 'latest'
2021-11-16T23:22:48.040Z [INFO]: # Patching NPM package '@aws-amplify/cli' from 4.29.4 to 7.3.4...
2021-11-16T23:25:56.611Z [INFO]: # Done patching NPM package '@aws-amplify/cli'
2021-11-16T23:25:56.680Z [INFO]: # Retrieving cache...
2021-11-16T23:25:56.722Z [INFO]: # Extracting cache...
2021-11-16T23:25:56.731Z [INFO]: # Extraction completed
2021-11-16T23:26:05.311Z [INFO]: ## Starting Backend Build
                                 # Starting phase: build
2021-11-16T23:26:10.247Z [INFO]: [33mNote: It is recommended to run this command from the root of your app directory[39m
2021-11-16T23:26:15.951Z [INFO]: [0mAmplify AppID found: d2ntvw7kn00s80. Amplify App name is: create-react-app-auth-amplify[0m
2021-11-16T23:26:16.002Z [INFO]: [0mAdding backend environment devb to AWS Amplify Console app: d2ntvw7kn00s80[0m
2021-11-16T23:26:16.062Z [WARNING]: - Initializing project in the cloud...
2021-11-16T23:26:21.377Z [INFO]: 
2021-11-16T23:26:21.381Z [INFO]: CREATE_IN_PROGRESS amplify-authcra-devb-232615 AWS::CloudFormation::Stack Tue Nov 16 2021 23:26:16 GMT+0000 (Coordinated Universal Time) User Initiated
                                 CREATE_IN_PROGRESS DeploymentBucket            AWS::S3::Bucket            Tue Nov 16 2021 23:26:19 GMT+0000 (Coordinated Universal Time)
                                 CREATE_IN_PROGRESS UnauthRole                  AWS::IAM::Role             Tue Nov 16 2021 23:26:19 GMT+0000 (Coordinated Universal Time)
                                 CREATE_IN_PROGRESS AuthRole                    AWS::IAM::Role             Tue Nov 16 2021 23:26:19 GMT+0000 (Coordinated Universal Time)
                                 CREATE_IN_PROGRESS DeploymentBucket            AWS::S3::Bucket            Tue Nov 16 2021 23:26:20 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
                                 CREATE_IN_PROGRESS UnauthRole                  AWS::IAM::Role             Tue Nov 16 2021 23:26:21 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
                                 CREATE_IN_PROGRESS AuthRole                    AWS::IAM::Role             Tue Nov 16 2021 23:26:21 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
2021-11-16T23:26:46.384Z [INFO]: 
2021-11-16T23:26:46.386Z [INFO]: CREATE_COMPLETE AuthRole                    AWS::IAM::Role             Tue Nov 16 2021 23:26:41 GMT+0000 (Coordinated Universal Time)
                                 CREATE_COMPLETE UnauthRole                  AWS::IAM::Role             Tue Nov 16 2021 23:26:41 GMT+0000 (Coordinated Universal Time)
                                 CREATE_COMPLETE DeploymentBucket            AWS::S3::Bucket            Tue Nov 16 2021 23:26:42 GMT+0000 (Coordinated Universal Time)
                                 CREATE_COMPLETE amplify-authcra-devb-232615 AWS::CloudFormation::Stack Tue Nov 16 2021 23:26:44 GMT+0000 (Coordinated Universal Time)
2021-11-16T23:26:46.452Z [WARNING]: ✔ Successfully created initial AWS cloud resources for deployments.
2021-11-16T23:26:46.607Z [WARNING]: - Uploading files...
2021-11-16T23:26:46.657Z [WARNING]: - Uploading files...
2021-11-16T23:26:46.937Z [WARNING]: - Uploading files...
2021-11-16T23:26:46.987Z [WARNING]: - Uploading files...
2021-11-16T23:26:47.031Z [WARNING]: - Uploading files...
2021-11-16T23:26:47.078Z [WARNING]: - Initializing your environment: devb
2021-11-16T23:26:47.079Z [WARNING]: ✔ Initialized provider successfully.
2021-11-16T23:26:47.488Z [WARNING]: - Updating resources in the cloud. This may take a few minutes...
2021-11-16T23:26:54.050Z [INFO]: 
2021-11-16T23:26:54.052Z [INFO]: UPDATE_IN_PROGRESS amplify-authcra-devb-232615    AWS::CloudFormation::Stack Tue Nov 16 2021 23:26:48 GMT+0000 (Coordinated Universal Time) User Initiated
                                 CREATE_IN_PROGRESS authcognitocf0c6096            AWS::CloudFormation::Stack Tue Nov 16 2021 23:26:53 GMT+0000 (Coordinated Universal Time)
                                 CREATE_IN_PROGRESS UpdateRolesWithIDPFunctionRole AWS::IAM::Role             Tue Nov 16 2021 23:26:53 GMT+0000 (Coordinated Universal Time)
2021-11-16T23:26:59.039Z [INFO]: 
2021-11-16T23:26:59.041Z [INFO]: CREATE_IN_PROGRESS authcognitocf0c6096            AWS::CloudFormation::Stack Tue Nov 16 2021 23:26:54 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
                                 CREATE_IN_PROGRESS UpdateRolesWithIDPFunctionRole AWS::IAM::Role             Tue Nov 16 2021 23:26:54 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
2021-11-16T23:26:59.108Z [INFO]: 
2021-11-16T23:26:59.108Z [INFO]: CREATE_IN_PROGRESS amplify-authcra-devb-232615-authcognitocf0c6096-1HYNDND2HX3EB AWS::CloudFormation::Stack Tue Nov 16 2021 23:26:54 GMT+0000 (Coordinated Universal Time) User Initiated
2021-11-16T23:27:04.108Z [INFO]: 
2021-11-16T23:27:04.109Z [INFO]: CREATE_IN_PROGRESS SNSRole AWS::IAM::Role Tue Nov 16 2021 23:27:00 GMT+0000 (Coordinated Universal Time)
                                 CREATE_IN_PROGRESS SNSRole AWS::IAM::Role Tue Nov 16 2021 23:27:01 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
2021-11-16T23:27:19.041Z [INFO]: 
2021-11-16T23:27:19.042Z [INFO]: CREATE_COMPLETE UpdateRolesWithIDPFunctionRole AWS::IAM::Role Tue Nov 16 2021 23:27:16 GMT+0000 (Coordinated Universal Time)
2021-11-16T23:27:24.127Z [INFO]: 
2021-11-16T23:27:24.128Z [INFO]: CREATE_COMPLETE SNSRole AWS::IAM::Role Tue Nov 16 2021 23:27:23 GMT+0000 (Coordinated Universal Time)
2021-11-16T23:27:29.131Z [INFO]: 
2021-11-16T23:27:29.133Z [INFO]: CREATE_IN_PROGRESS UserPool AWS::Cognito::UserPool Tue Nov 16 2021 23:27:26 GMT+0000 (Coordinated Universal Time)
                                 CREATE_IN_PROGRESS UserPool AWS::Cognito::UserPool Tue Nov 16 2021 23:27:28 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
2021-11-16T23:27:29.317Z [INFO]: 
2021-11-16T23:27:29.317Z [INFO]: CREATE_COMPLETE UserPool AWS::Cognito::UserPool Tue Nov 16 2021 23:27:29 GMT+0000 (Coordinated Universal Time)
2021-11-16T23:27:34.146Z [INFO]: 
2021-11-16T23:27:34.149Z [INFO]: CREATE_IN_PROGRESS UserPoolClient    AWS::Cognito::UserPoolClient Tue Nov 16 2021 23:27:31 GMT+0000 (Coordinated Universal Time)
                                 CREATE_IN_PROGRESS UserPoolClientWeb AWS::Cognito::UserPoolClient Tue Nov 16 2021 23:27:31 GMT+0000 (Coordinated Universal Time)
                                 CREATE_IN_PROGRESS UserPoolClient    AWS::Cognito::UserPoolClient Tue Nov 16 2021 23:27:32 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
                                 CREATE_COMPLETE    UserPoolClient    AWS::Cognito::UserPoolClient Tue Nov 16 2021 23:27:32 GMT+0000 (Coordinated Universal Time)
                                 CREATE_IN_PROGRESS UserPoolClientWeb AWS::Cognito::UserPoolClient Tue Nov 16 2021 23:27:33 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
                                 CREATE_COMPLETE    UserPoolClientWeb AWS::Cognito::UserPoolClient Tue Nov 16 2021 23:27:33 GMT+0000 (Coordinated Universal Time)
2021-11-16T23:27:39.124Z [INFO]: 
2021-11-16T23:27:39.125Z [INFO]: CREATE_IN_PROGRESS UserPoolClientRole AWS::IAM::Role Tue Nov 16 2021 23:27:35 GMT+0000 (Coordinated Universal Time)
                                 CREATE_IN_PROGRESS UserPoolClientRole AWS::IAM::Role Tue Nov 16 2021 23:27:38 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
2021-11-16T23:27:59.150Z [INFO]: 
2021-11-16T23:27:59.151Z [INFO]: CREATE_COMPLETE UserPoolClientRole AWS::IAM::Role Tue Nov 16 2021 23:27:58 GMT+0000 (Coordinated Universal Time)
2021-11-16T23:28:04.161Z [INFO]: 
2021-11-16T23:28:04.163Z [INFO]: CREATE_IN_PROGRESS UserPoolClientLambda AWS::Lambda::Function Tue Nov 16 2021 23:28:01 GMT+0000 (Coordinated Universal Time)
                                 CREATE_IN_PROGRESS UserPoolClientLambda AWS::Lambda::Function Tue Nov 16 2021 23:28:03 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
                                 CREATE_COMPLETE    UserPoolClientLambda AWS::Lambda::Function Tue Nov 16 2021 23:28:04 GMT+0000 (Coordinated Universal Time)
2021-11-16T23:28:09.163Z [INFO]: 
2021-11-16T23:28:09.164Z [INFO]: CREATE_IN_PROGRESS UserPoolClientLambdaPolicy AWS::IAM::Policy Tue Nov 16 2021 23:28:06 GMT+0000 (Coordinated Universal Time)
                                 CREATE_IN_PROGRESS UserPoolClientLambdaPolicy AWS::IAM::Policy Tue Nov 16 2021 23:28:07 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
2021-11-16T23:28:29.178Z [INFO]: 
2021-11-16T23:28:29.180Z [INFO]: CREATE_COMPLETE UserPoolClientLambdaPolicy AWS::IAM::Policy Tue Nov 16 2021 23:28:27 GMT+0000 (Coordinated Universal Time)
2021-11-16T23:28:34.173Z [INFO]: 
2021-11-16T23:28:34.175Z [INFO]: CREATE_IN_PROGRESS UserPoolClientLogPolicy AWS::IAM::Policy Tue Nov 16 2021 23:28:30 GMT+0000 (Coordinated Universal Time)
                                 CREATE_IN_PROGRESS UserPoolClientLogPolicy AWS::IAM::Policy Tue Nov 16 2021 23:28:32 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
2021-11-16T23:28:54.193Z [INFO]: 
2021-11-16T23:28:54.194Z [INFO]: CREATE_COMPLETE UserPoolClientLogPolicy AWS::IAM::Policy Tue Nov 16 2021 23:28:52 GMT+0000 (Coordinated Universal Time)
2021-11-16T23:28:59.224Z [INFO]: 
2021-11-16T23:28:59.225Z [INFO]: CREATE_IN_PROGRESS UserPoolClientInputs Custom::LambdaCallout Tue Nov 16 2021 23:28:54 GMT+0000 (Coordinated Universal Time)
                                 CREATE_IN_PROGRESS UserPoolClientInputs Custom::LambdaCallout Tue Nov 16 2021 23:28:57 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
                                 CREATE_COMPLETE    UserPoolClientInputs Custom::LambdaCallout Tue Nov 16 2021 23:28:58 GMT+0000 (Coordinated Universal Time)
2021-11-16T23:29:04.205Z [INFO]: 
2021-11-16T23:29:04.206Z [INFO]: CREATE_IN_PROGRESS IdentityPool AWS::Cognito::IdentityPool Tue Nov 16 2021 23:29:00 GMT+0000 (Coordinated Universal Time)
                                 CREATE_IN_PROGRESS IdentityPool AWS::Cognito::IdentityPool Tue Nov 16 2021 23:29:02 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
                                 CREATE_COMPLETE    IdentityPool AWS::Cognito::IdentityPool Tue Nov 16 2021 23:29:03 GMT+0000 (Coordinated Universal Time)
2021-11-16T23:29:09.207Z [INFO]: 
2021-11-16T23:29:09.208Z [INFO]: CREATE_IN_PROGRESS IdentityPoolRoleMap AWS::Cognito::IdentityPoolRoleAttachment Tue Nov 16 2021 23:29:06 GMT+0000 (Coordinated Universal Time)
                                 CREATE_IN_PROGRESS IdentityPoolRoleMap AWS::Cognito::IdentityPoolRoleAttachment Tue Nov 16 2021 23:29:07 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
                                 CREATE_COMPLETE    IdentityPoolRoleMap AWS::Cognito::IdentityPoolRoleAttachment Tue Nov 16 2021 23:29:07 GMT+0000 (Coordinated Universal Time)
2021-11-16T23:29:14.212Z [INFO]: 
2021-11-16T23:29:14.213Z [INFO]: CREATE_COMPLETE amplify-authcra-devb-232615-authcognitocf0c6096-1HYNDND2HX3EB AWS::CloudFormation::Stack Tue Nov 16 2021 23:29:10 GMT+0000 (Coordinated Universal Time)
2021-11-16T23:29:34.131Z [INFO]: 
2021-11-16T23:29:34.132Z [INFO]: CREATE_COMPLETE authcognitocf0c6096 AWS::CloudFormation::Stack Tue Nov 16 2021 23:29:32 GMT+0000 (Coordinated Universal Time)
2021-11-16T23:29:39.129Z [INFO]: 
2021-11-16T23:29:39.130Z [INFO]: CREATE_IN_PROGRESS UpdateRolesWithIDPFunction AWS::Lambda::Function Tue Nov 16 2021 23:29:34 GMT+0000 (Coordinated Universal Time)
                                 CREATE_IN_PROGRESS UpdateRolesWithIDPFunction AWS::Lambda::Function Tue Nov 16 2021 23:29:37 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
                                 CREATE_COMPLETE    UpdateRolesWithIDPFunction AWS::Lambda::Function Tue Nov 16 2021 23:29:37 GMT+0000 (Coordinated Universal Time)
2021-11-16T23:29:44.142Z [INFO]: 
2021-11-16T23:29:44.144Z [INFO]: CREATE_IN_PROGRESS UpdateRolesWithIDPFunctionOutputs Custom::LambdaCallout Tue Nov 16 2021 23:29:39 GMT+0000 (Coordinated Universal Time)
                                 CREATE_IN_PROGRESS UpdateRolesWithIDPFunctionOutputs Custom::LambdaCallout Tue Nov 16 2021 23:29:43 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
                                 CREATE_COMPLETE    UpdateRolesWithIDPFunctionOutputs Custom::LambdaCallout Tue Nov 16 2021 23:29:43 GMT+0000 (Coordinated Universal Time)
2021-11-16T23:29:49.143Z [INFO]: 
2021-11-16T23:29:49.145Z [INFO]: UPDATE_COMPLETE_CLEANUP_IN_PROGRESS amplify-authcra-devb-232615 AWS::CloudFormation::Stack Tue Nov 16 2021 23:29:46 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_COMPLETE                     amplify-authcra-devb-232615 AWS::CloudFormation::Stack Tue Nov 16 2021 23:29:46 GMT+0000 (Coordinated Universal Time)
2021-11-16T23:29:49.513Z [INFO]: Error: File at path: '/codebuild/output/src033637649/src/create-react-app-auth-amplify/amplify/backend/auth/cognitocf0c6096/build/parameters.json' does not exist
                                 at Function.JSONUtilities.readJson (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/jsonUtilities.ts:25:15)
                                 at AmplifyToolkit.readJsonFile [as _readJsonFile] (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/read-json-file.ts:5:24)
                                 at uploadFiles (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/provider-utils/awscloudformation/utils/trigger-file-uploader.js:27:43)
                                 at runMicrotasks (<anonymous>)
                                 at processTicksAndRejections (internal/process/task_queues.js:97:5)
                                 at Object.uploadAuthTriggerFiles (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/upload-auth-trigger-files.js:5:5)
                                 at Object.run (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/push-resources.ts:335:5)
2021-11-16T23:29:49.513Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
                                    ✖ There was an error initializing your environment.
2021-11-16T23:29:49.516Z [INFO]: [0mError: Unable to upload trigger files to S3[0m
                                 [0m    at uploadFiles (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/provider-utils/awscloudformation/utils/trigger-file-uploader.js:49:11)[0m
                                 [0m    at runMicrotasks (<anonymous>)[0m
                                 [0m    at processTicksAndRejections (internal/process/task_queues.js:97:5)[0m
                                 [0m    at Object.uploadAuthTriggerFiles (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/upload-auth-trigger-files.js:5:5)[0m
                                 [0m    at Object.run (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/push-resources.ts:335:5)[0m
2021-11-16T23:29:49.553Z [ERROR]: !!! Build failed
2021-11-16T23:29:49.553Z [ERROR]: !!! Non-Zero Exit Code detected
2021-11-16T23:29:49.554Z [INFO]: # Starting environment caching...
2021-11-16T23:29:49.554Z [INFO]: # Environment caching completed
Terminating logging...


```

</details>

**Comment by kaustavghosh06** [comment]
@sisaku8 How did you implemented the Cognito Environment from AWS which you've mentioned above? And how did you connect this local environment to the Amplify console? What were the exact steps taken?

**Comment by kaustavghosh06** [comment]
@sisaku8 We just published a new CLI version with a fix for this. If you're using the latest tag of the Amplify CLI for your CI/CD you can go ahead and re-build/deploy to verify that this issue is resolved.
Please let us know if you're still stuck.

**Comment by sisaku8** [comment]
I don't know what you fixed but it's working! Thank you very much!
