### ISSUE TITLE
Amplify auth : There was an error adding the auth resource

### ISSUE THREAD

**Issue by NicolasRoehm** [aws-amplify/amplify-cli#892]
**Describe the bug**
I can not add the Auth resource @1.1.2. I'm still getting **There was an error adding the auth resource**

**To Reproduce**
- Using `amplify auth add`
- or `amplify api add` / `amplify api update` with Amazon Cognito User Pool as authorization type for the API

**Expected behavior**
I was expecting the CLI to add an Auth resource to my backend.

**Logs**
```
Error: ENOENT: no such file or directory, open 'D:\projects\my-app\amplify\backend\auth\cognito94708cf9\parameters.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at Object.saveResourceParameters (C:\Users\Nicolas\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-provider-awscloudformation\src\resourceParams.js:29:6)
    at saveResourceParameters (C:\Users\Nicolas\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-category-auth\provider-utils\awscloudformation\index.js:59:12)
    at serviceQuestions.then (C:\Users\Nicolas\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-category-auth\provider-utils\awscloudformation\index.js:96:7)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
There was an error adding the auth resource
```

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by kaustavghosh06** [comment]
@NicolasRoehm Could you tell me what do you see when you do an `amplify status`?

**Comment by NicolasRoehm** [comment]
@kaustavghosh06 `amplify status` gives the following :

Current Environment: dev

| Category | Resource name | Operation | Provider plugin |
| -------- | ------------- | --------- | --------------- |

**Comment by kaustavghosh06** [comment]
@NicolasRoehm  Looks like you havent added auth succesfully. Can you run `amplify add auth` again and check amplify status? It should have an auth entry in it.

**Comment by NicolasRoehm** [comment]
@kaustavghosh06 Here are the complete logs :
```
PS D:\projects\my-app> amplify add auth
Using service: Cognito, provided by: awscloudformation
 The current configured provider is Amazon Cognito.
 Do you want to use the default authentication and security configuration? Yes, use the default configuration.
Error: ENOENT: no such file or directory, open 'D:\projects\my-app\amplify\backend\auth\cognito627ca25a\parameters.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at Object.saveResourceParameters (C:\Users\Nicolas\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-provider-awscloudformation\src\resourceParams.js:29:6)
    at saveResourceParameters (C:\Users\Nicolas\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-category-auth\provider-utils\awscloudformation\index.js:59:12)
    at serviceQuestions.then (C:\Users\Nicolas\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-category-auth\provider-utils\awscloudformation\index.js:96:7)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
There was an error adding the auth resource
PS D:\projects\my-app> amplify status

Current Environment: dev

| Category | Resource name | Operation | Provider plugin |
| -------- | ------------- | --------- | --------------- |
```

**Comment by yuth** [comment]
@NicolasRoehm could you try installing latest version of Amplify CLI. I tried adding auth in windows 10 and cmd and could not reproduce this error.

**Comment by NicolasRoehm** [comment]
Hi @yuth, I get the exact same logs using `@aws-amplify/cli@1.1.7`

<details>
  <summary>Details</summary>
  <div>

```
PS D:\projects\my-app> amplify auth add
Using service: Cognito, provided by: awscloudformation
 The current configured provider is Amazon Cognito.
 Do you want to use the default authentication and security configuration? Yes, use the default configuration.
Error: ENOENT: no such file or directory, open 'D:\projects\my-app\amplify\backend\auth\cognito915fc809\parameters.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at Object.saveResourceParameters (C:\Users\Nicolas\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-provider-awscloudformation\src\resourceParams.js:29:6)
    at saveResourceParameters (C:\Users\Nicolas\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-category-auth\provider-utils\awscloudformation\index.js:59:12)
    at serviceQuestions.then (C:\Users\Nicolas\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-category-auth\provider-utils\awscloudformation\index.js:96:7)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
There was an error adding the auth resource
PS D:\projects\my-app> amplify status

Current Environment: dev

| Category | Resource name | Operation | Provider plugin |
| -------- | ------------- | --------- | --------------- |
```

  </div>
</details>

**Comment by yuth** [comment]
@NicolasRoehm I couldn't reproduce this on Windows 10. Could you try running the same command with [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10) and see if this is still happens.

**Comment by NicolasRoehm** [comment]
`amplify status` shows `Current Environment: undefined` after the same error returned by `amplify auth add` :
```
nicolas@DESKTOP-42O95JU:~/code/my-app$ amplify auth add
Using service: Cognito, provided by: awscloudformation
 The current configured provider is Amazon Cognito.
 Do you want to use the default authentication and security configuration? Yes, use the default configuration.
Error: ENOENT: no such file or directory, open '/home/nicolas/code/my-app/amplify/backend/amplify-meta.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.updateamplifyMetaAfterResourceAdd (/usr/local/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/update-amplify-meta.js:71:37)
    at amplify.serviceSelectionPrompt.then.then (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/commands/auth/enable.js:35:17)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
There was an error adding the auth resource
nicolas@DESKTOP-42O95JU:~/code/my-app$ amplify status

Current Environment: undefined

/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/index.js:13
    throw up;
    ^

Error: ENOENT: no such file or directory, open '/home/nicolas/code/my-app/amplify/backend/amplify-meta.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at getResourceStatus (/usr/local/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/resource-status.js:207:37)
    at Object.showResourceTable (/usr/local/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/resource-status.js:268:13)
    at Command.run (/usr/local/lib/node_modules/@aws-amplify/cli/src/commands/status.js:5:27)
    at Runtime.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/runtime/run.js:90:58)
    at step (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/runtime/run.js:32:23)
    at Object.next (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/runtime/run.js:13:53)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/runtime/run.js:7:71
    at new Promise (<anonymous>)
```

**Comment by NicolasRoehm** [comment]
Yes, it works! Thank you @lucaspelloni2 👍

**Comment by nonbeing** [comment]
Still hitting the same problem in Oct 2020 with amplify CLI version`4.29.4`

```
    "@aws-amplify/ui-react": "^0.2.23",
    "aws-amplify": "^3.3.3"
```

Unbelievable that Amplify is still riddled with all sorts of errors - even old ones like this bug.
Luckily, the workaround mentioned @lucaspelloni2 still works: thanks for that.

**Comment by automed-os** [comment]
I had this same issue on an existing project. The issue was that the local development version was out of sync with the amplify version. I tried to run amplify push and it gives you the following error; 

`An error occurred during the push operation: Current environment cannot be determined
Use 'amplify init' in the root of your app directory to initialize your project with Amplify`

To fix it run 'amplify init' make sure you use the same settings as before and then when this is done then run 'amplify pull'

I was then able to use 'amplify add api'.

Also, note that it may through this error;
`Backup folder at /xyz/amplify-backup already exists, remove the folder and retry the operation.`

just delete it and re-run 'amplify pull'

hope this helps.
