### ISSUE TITLE
Failed to pull the backend. ENOENT: no such file or directory, stat '/Users/nano/Projects/caak-next/amplify/.temp/#current-cloud-backend/function/caakmnlayerAPI/lib/nodejs/node_modules/.bin/nanoid'

### ISSUE THREAD

**Issue by 1stNaNo** [aws-amplify/amplify-cli#8959]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm install @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v16.11.0

### Amplify CLI Version

7.4.2

### What operating system are you using?

Mac

### Amplify Categories

function

### Amplify Commands

pull

### Describe the bug

Failed to pull the backend. (see log output for stack trace)

### Expected behavior

pull down existing environment configuration

### Reproduction steps

1. amplify push from windows
2. amplify pull from mac

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
ENOENT: no such file or directory, stat '/Users/nano/Projects/caak-next/amplify/.temp/#current-cloud-backend/function/caakmnlayerAPI/lib/nodejs/node_modules/.bin/nanoid'
Error: ENOENT: no such file or directory, stat '/Users/nano/Projects/caak-next/amplify/.temp/#current-cloud-backend/function/caakmnlayerAPI/lib/nodejs/node_modules/.bin/nanoid'
    at Object.statSync (node:fs:1536:3)
    at Object.statSync (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/graceful-fs/polyfills.js:311:34)
    at getStatsSync (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/util/stat.js:58:18)
    at Object.checkPathsSync (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/util/stat.js:90:33)
    at copyDirItem (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:119:29)
    at /opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:39
    at Array.forEach (<anonymous>)
    at copyDir (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:23)
    at mkDirAndCopy (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:108:3)
    at onDir (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:99:25)
    at getStats (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:45:37)
    at startCopy (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
    at copyDirItem (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:120:10)
    at /opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:39
    at Array.forEach (<anonymous>)
    at copyDir (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:23)
    at mkDirAndCopy (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:108:3)
    at onDir (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:99:25)
    at getStats (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:45:37)
    at startCopy (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
    at copyDirItem (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:120:10)
    at /opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:39
    at Array.forEach (<anonymous>)
    at copyDir (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:23)
    at mkDirAndCopy (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:108:3)
    at onDir (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:99:25)
    at getStats (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:45:37)
    at startCopy (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
    at copyDirItem (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:120:10)
    at /opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:39
    at Array.forEach (<anonymous>)
    at copyDir (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:23)
    at mkDirAndCopy (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:108:3)
    at onDir (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:99:25)
    at getStats (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:45:37)
    at startCopy (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
    at copyDirItem (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:120:10)
    at /opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:39
    at Array.forEach (<anonymous>)
    at copyDir (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:23)
    at mkDirAndCopy (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:108:3)
    at onDir (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:99:25)
    at getStats (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:45:37)
    at startCopy (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
    at copyDirItem (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:120:10)
    at /opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:39
    at Array.forEach (<anonymous>)
    at copyDir (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:23)
    at mkDirAndCopy (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:108:3)
    at onDir (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:99:25)
    at getStats (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:45:37)
    at startCopy (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
    at copyDirItem (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:120:10)
    at /opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:39
    at Array.forEach (<anonymous>)
    at copyDir (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:23)
    at onDir (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:103:10)
    at getStats (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:45:37)
    at startCopy (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
    at handleFilterAndCopy (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:33:10)
    at Object.copySync (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:26:10)
    at downloadBackend (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/attach-backend.js:369:8)
    at Object.run (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/attach-backend.js:78:3)
    at Object.attachBackend (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/index.ts:60:3)
    at Object.queryProvider (/opt/homebrew/lib/node_modules/@aws-amplify/cli/src/attach-backend-steps/a10-queryProvider.ts:12:3)
    at Object.attachBackend (/opt/homebrew/lib/node_modules/@aws-amplify/cli/src/attach-backend.ts:20:5)
    at Object.run (/opt/homebrew/lib/node_modules/@aws-amplify/cli/src/commands/pull.ts:59:5)
    at Object.executeAmplifyCommand (/opt/homebrew/lib/node_modules/@aws-amplify/cli/src/index.ts:373:5)
    at executePluginModuleCommand (/opt/homebrew/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:204:3)
    at Object.executeCommand (/opt/homebrew/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:30:5)
    at Object.run (/opt/homebrew/lib/node_modules/@aws-amplify/cli/src/index.ts:205:5)


```

</details>

**Comment by edwardfoyle** [comment]
Hi @1stNaNo this issue is most likely caused by symlinks in your function's build artifacts which cannot be properly zipped and unzipped. See [this issue](https://github.com/aws-amplify/amplify-cli/issues/6144) for some more details on the problem.

**Comment by charlesdarkwind** [comment]
Hi, I had the had the same issue, here was the steps to fix.

Errors can also look like this during pull, init, env checkout operations on linux systems:

`ENOENT: no such file or directory, lstat '/home/myUser/myProject/amplify/#current-cloud-backend/function/myFunction'` \
`EEXIST: file already exists, symlink '..\sshpk\bin\sshpk-conv' -> '/home/myUser/myProject/amplify/.temp/#current-cloud-backend/function/myLayer/lib/nodejs/node_modules/.bin/sshpk-conv'`

steps to fix:
1. Go to s3 and download ZIP `s3://amplify-*-deployment/#current-cloud-backend.zip`
2. Backup the ZIP, Unzip and delete the `node_modules/` under the path in the error
3. re-upload the zip
