### ISSUE TITLE
Issues with `Error: 'jsonString' argument missing or empty` 

### ISSUE THREAD

**Issue by demonintherough** [aws-amplify/amplify-cli#8969]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.13.0

### Amplify CLI Version

7.4.2

### What operating system are you using?

Mac

### Amplify Categories

Not applicable

### Amplify Commands

add, pull, push, status

### Describe the bug

When I run a pull/push/status I'm getting the following error.

`Error: 'jsonString' argument missing or empty
    at Function.JSONUtilities.parse (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/jsonUtilities.js:79:15)
    at Function.JSONUtilities.readJson (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/jsonUtilities.js:47:32)
    at StateManager.getData (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/state-manager/stateManager.js:290:56)
    at StateManager.getCLIJSON (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/state-manager/stateManager.js:235:25)
    at FeatureFlagFileProvider.loadConfig (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/feature-flags/featureFlagFileProvider.js:35:65)
    at FeatureFlagFileProvider.load (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/feature-flags/featureFlagFileProvider.js:21:48)
    at FeatureFlags.loadValues (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/feature-flags/featureFlags.js:220:60)
    at Function.FeatureFlags.initialize (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/feature-flags/featureFlags.js:497:20)
    at async Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/lib/index.js:146:9)
`

### Expected behavior

The function to run correctly

### Reproduction steps

I'm not sure, I am working on an existing project and moving to a new computer. This hasn't worked correctly once I completed the installation.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line
Error: 'jsonString' argument missing or empty
    at Function.JSONUtilities.parse (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/jsonUtilities.js:79:15)
    at Function.JSONUtilities.readJson (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/jsonUtilities.js:47:32)
    at StateManager.getData (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/state-manager/stateManager.js:290:56)
    at StateManager.getCLIJSON (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/state-manager/stateManager.js:235:25)
    at FeatureFlagFileProvider.loadConfig (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/feature-flags/featureFlagFileProvider.js:35:65)
    at FeatureFlagFileProvider.load (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/feature-flags/featureFlagFileProvider.js:21:48)
    at FeatureFlags.loadValues (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/feature-flags/featureFlags.js:220:60)
    at Function.FeatureFlags.initialize (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/feature-flags/featureFlags.js:497:20)
    at async Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/lib/index.js:146:9)


```

</details>

**Comment by demonintherough** [comment]
When running the commands in an empty dir there is no issue. This only occurs while in my projects root dir.

**Comment by kaustavghosh06** [comment]
@demonintherough Do you have the cli.json (feature flag file) in your `amplify/` folder?

**Comment by demonintherough** [comment]
> @demonintherough Do you have the cli.json (feature flag file) in your `amplify/` folder?

So I have the cli.json file but there's nothing in it.

**Comment by demonintherough** [comment]
I went to my amplify s3 bucket and got the current-cloud-backend. Pulled that and got the cli.json. Updated the cli.json file in the amplify folder and that fixed the issue.
