### ISSUE TITLE
Custom amplify init script no longer working in Amplify CI/CD with imported auth

### ISSUE THREAD

**Issue by cwdcwd** [aws-amplify/amplify-cli#9023]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

locally I'm using npm but this breakage is inside the Amplify build process itself so it is using whatever is installed in the image

### If applicable, what version of Node.js are you using?

v16.3.0

### Amplify CLI Version

7.4.4

### What operating system are you using?

OSX 11.6 Big Sur

### Amplify Categories

Not applicable

### Amplify Commands

init

### Describe the bug

Within our `amplify.yaml` we're calling a shell script to perform `amplify init` and generate our `aws-exports.js` config. 
As of this past Friday this is throwing the following error: 

```
2021-11-22T17:08:45.115Z [INFO]: [33mNote: It is recommended to run this command from the root of your app directory[39m
2021-11-22T17:08:51.416Z [WARNING]: - Initializing your environment: dev
2021-11-22T17:08:52.815Z [WARNING]: - Building resource auth/torcidentityfd5750d1
2021-11-22T17:08:52.828Z [WARNING]: - Building resource storage/devIdentity
2021-11-22T17:08:52.909Z [WARNING]: - Building resource storage/badgestable
2021-11-22T17:08:52.909Z [WARNING]: - Building resource storage/GithubToken
2021-11-22T17:08:52.961Z [WARNING]: ✔ Initialized provider successfully.
2021-11-22T17:08:53.776Z [WARNING]: ✖ There was an error initializing your environment.
2021-11-22T17:08:53.780Z [INFO]: [0mTypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined[0m
                                 [0m    at validateString (internal/validators.js:120:11)[0m
                                 [0m    at Object.join (path.js:1039:7)[0m
                                 [0m    at PathManager.constructPath (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/state-manager/pathManager.ts:253:34)[0m
                                 [0m    at PathManager.getResourceDirectoryPath (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/state-manager/pathManager.ts:142:10)[0m
                                 [0m    at PathManager.getResourceParametersFilePath (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/state-manager/pathManager.ts:149:34)[0m
                                 [0m    at StateManager.setResourceParametersJson (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/state-manager/stateManager.ts:284:34)[0m
                                 [0m    at updateStateFiles (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/provider-utils/awscloudformation/import/index.ts:728:16)[0m
                                 [0m    at Object.headlessImport (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/provider-utils/awscloudformation/import/index.ts:1277:26)[0m
                                 [0m    at runMicrotasks (<anonymous>)[0m
                                 [0m    at processTicksAndRejections (internal/process/task_queues.js:97:5)[0m
                                 [0m    at importedAuthEnvInit (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/provider-utils/awscloudformation/import/index.ts:946:12)[0m
                                 [0m    at updateConfigOnEnvInit (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/provider-utils/awscloudformation/index.js:52:72)[0m
                                 [0m    at /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/index.js:349:22 {[0m
                                 [0m  code: 'ERR_INVALID_ARG_TYPE'[0m
                                 [0m}[0m
2021-11-22T17:08:53.807Z [ERROR]: !!! Build failed
```

### Expected behavior

I expect init to run and create an `aws-exports.js` file

### Reproduction steps

[amplify.yml.txt](https://github.com/aws-amplify/amplify-cli/files/7583419/amplify.yml.txt
[init.sh.txt](https://github.com/aws-amplify/amplify-cli/files/7583424/init.sh.txt)
)

attaching using `.txt` 

### Log output

<details>

```
2021-11-22T18:12:36.592Z [INFO]: 7.4.5
2021-11-22T18:12:46.607Z [INFO]: [33mNote: It is recommended to run this command from the root of your app directory[39m
2021-11-22T18:12:47.111Z [WARNING]: - Initializing your environment: dev
2021-11-22T18:12:48.386Z [WARNING]: - Building resource auth/torcidentityfd5750d1
2021-11-22T18:12:48.395Z [WARNING]: - Building resource storage/devIdentity
2021-11-22T18:12:48.462Z [WARNING]: - Building resource storage/badgestable
2021-11-22T18:12:48.462Z [WARNING]: - Building resource storage/GithubToken
2021-11-22T18:12:48.507Z [WARNING]: ✔ Initialized provider successfully.
2021-11-22T18:12:49.369Z [WARNING]: ✖ There was an error initializing your environment.
2021-11-22T18:12:49.373Z [INFO]: [0mTypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined[0m
                                 [0m    at validateString (internal/validators.js:120:11)[0m
                                 [0m    at Object.join (path.js:1039:7)[0m
                                 [0m    at PathManager.constructPath (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/state-manager/pathManager.ts:253:34)[0m
                                 [0m    at PathManager.getResourceDirectoryPath (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/state-manager/pathManager.ts:142:10)[0m
                                 [0m    at PathManager.getResourceParametersFilePath (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/state-manager/pathManager.ts:149:34)[0m
                                 [0m    at StateManager.setResourceParametersJson (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/state-manager/stateManager.ts:284:34)[0m
                                 [0m    at updateStateFiles (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/provider-utils/awscloudformation/import/index.ts:728:16)[0m
                                 [0m    at Object.headlessImport (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/provider-utils/awscloudformation/import/index.ts:1277:26)[0m
                                 [0m    at runMicrotasks (<anonymous>)[0m
                                 [0m    at processTicksAndRejections (internal/process/task_queues.js:97:5)[0m
                                 [0m    at importedAuthEnvInit (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/provider-utils/awscloudformation/import/index.ts:946:12)[0m
                                 [0m    at updateConfigOnEnvInit (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/provider-utils/awscloudformation/index.js:52:72)[0m
                                 [0m    at /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/index.js:349:22 {[0m
                                 [0m  code: 'ERR_INVALID_ARG_TYPE'[0m
                                 [0m}[0m
2021-11-22T18:12:49.397Z [ERROR]: !!! Build failed
2021-11-22T18:12:49.397Z [ERROR]: !!! Non-Zero Exit Code detected
2021-11-22T18:12:49.397Z [INFO]: # Starting environment caching...
2021-11-22T18:12:49.397Z [INFO]: # Uploading environment cache artifact...
2021-11-22T18:12:49.474Z [INFO]: # Environment caching completed
Terminating logging...

```

</details>

**Comment by kaustavghosh06** [comment]
@cwdcwd Do you have an imported auth resource?

**Comment by cwdcwd** [comment]
@kaustavghosh06 yes I do

**Comment by kaustavghosh06** [comment]
@cwdcwd I tried to run CI/CD after importing auth using latest CLI  version and was able to deploy. Here are my configs and logs. Do you have a similar config? If you can send us a link to fetch your amplify directory at amplify-cli@amazon.com, we'd be happy to take a look and investigate further.

<img width="1371" alt="Screen Shot 2021-11-22 at 12 44 00 PM" src="https://user-images.githubusercontent.com/7247658/142933955-bc437d03-e550-4bcc-a3d7-0c18f644178b.png">
g
<img width="1713" alt="Screen Shot 2021-11-22 at 9 50 15 AM" src="https://user-images.githubusercontent.com/7247658/142933966-a4ac39d3-4c7c-42c2-8380-00b786ba27e6.png">
?

**Comment by cwdcwd** [comment]
surely @kaustavghosh06 
should I just zip up my `.amplify` folder and share a dropbox link with that email address?

**Comment by kaustavghosh06** [comment]
Yes, that should be good

**Comment by cwdcwd** [comment]
file sent. thanks @kaustavghosh06 !

**Comment by kaustavghosh06** [comment]
@cwdcwd Got a chance to review your files and for some reason (not able to repro it) for the imported auth resource - the parameters.json file for the auth resource (`amplify/backend/auth/torcidentityfd5750d1`) seems to be inside the `amplify/backend/auth/torcidentityfd5750d1/build/` directory. If you move it one level up and remove the build/ directory - like the auth resource I've shown up in my comment, then you should be able to continue. Please let me know if you need more clarification or information.

**Comment by cwdcwd** [comment]
thanks @kaustavghosh06 
I will give that a try and let you know how it works out.

**Comment by cwdcwd** [comment]
that worked! thanks so much @kaustavghosh06 
CC @callmekatootie
