### ISSUE TITLE
After Updating to Amplify CLI 7.5.0 OAuth problems

### ISSUE THREAD

**Issue by kundarmah** [aws-amplify/amplify-cli#9061]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.16.0

### Amplify CLI Version

7.5.0

### What operating system are you using?

Mac

### Amplify Categories

auth

### Amplify Commands

add

### Describe the bug

After updating AWS Cli to 7.5.0 when I do `amplify add auth`

Then using "Default configuration with Social Provider (Federation)" after inputting Facebook App ID and Secret it shows

`Cannot read property 'filter' of undefined
TypeError: Cannot read property 'filter' of undefined
    at mergeDeploymentSecrets (/Users/gianfrancodelmundo/.nvm/versions/node/v14.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/deploymentSecretsHelper.ts:13:57)
    at AmplifyToolkit.saveEnvResourceParameters [as _saveEnvResourceParameters] (/Users/gianfrancodelmundo/.nvm/versions/node/v14.16.0/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/envResourceParams.ts:81:31)
    at /Users/gianfrancodelmundo/.nvm/versions/node/v14.16.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/provider-utils/awscloudformation/handlers/resource-handlers.ts:59:21
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object.executeAmplifyCommand (/Users/gianfrancodelmundo/.nvm/versions/node/v14.16.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/index.js:421:3)
    at executePluginModuleCommand (/Users/gianfrancodelmundo/.nvm/versions/node/v14.16.0/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:204:3)
    at executeCommand (/Users/gianfrancodelmundo/.nvm/versions/node/v14.16.0/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:30:5)
    at Object.run (/Users/gianfrancodelmundo/.nvm/versions/node/v14.16.0/lib/node_modules/@aws-amplify/cli/src/index.ts:205:5)`

### Expected behavior

Should Create Auth with Social Federation

### Reproduction steps

1. amplify init
2. amplify add auth
3. Select Default Configuration with Social Provider
4. Select Facebook/Google
5. Add App ID or Secret

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
2021-11-24T01:39:55.305Z|info : amplify add auth  
2021-11-24T01:40:03.141Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2021-11-24T01:41:34.967Z|info : amplify push core  
2021-11-24T01:41:41.084Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2021-11-24T01:41:41.371Z|info : amplify-provider-awscloudformation.aws-s3.deleteDirectory.s3.getAllObjectVersions([{"BucketName":"[***]ify-[***]atest-[***]ev-[***]53-[***]ment"}])
2021-11-24T01:41:41.372Z|info : amplify-provider-awscloudformation.aws-s3.getAllObjectKey.s3.listObjectVersions([{"Bucket":"[***]ify-[***]atest-[***]ev-[***]53-[***]ment","Prefix":"hooks/"}])
2021-11-24T01:41:42.070Z|info : amplify-provider-awscloudformation.aws-s3.deleteAllObjects.s3.deleteObjects (0 of 1)([{"Bucket":"[***]ify-[***]atest-[***]ev-[***]53-[***]ment"}])
2021-11-24T01:41:42.518Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Key":"[***]ks/[***]st-[***]sample","Bucket":"[***]ify-[***]atest-[***]ev-[***]53-[***]ment"}])
2021-11-24T01:41:43.022Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Key":"[***]ks/[***]re-[***]sample","Bucket":"[***]ify-[***]atest-[***]ev-[***]53-[***]ment"}])
2021-11-24T01:41:43.324Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Key":"[***]ks/[***]E.md","Bucket":"[***]ify-[***]atest-[***]ev-[***]53-[***]ment"}])
2021-11-24T01:41:43.831Z|info : amplify-provider-awscloudformation.zip-util.downloadZip.s3.getFile([{"Key":"[***]rent-[***]ud-[***]d.zip"},null])
2021-11-24T01:41:43.833Z|info : amplify-provider-awscloudformation.aws-s3.s3.getFile([{"Key":"[***]rent-[***]ud-[***]d.zip","Bucket":"[***]ify-[***]atest-[***]ev-[***]53-[***]ment"}])
2021-11-24T01:41:44.233Z|info : amplify-provider-awscloudformation.initialize-env.run.cfn.updateamplifyMetaFileWithStackOutputs([{"StackName":"[***]ify-[***]atest-[***]ev-[***]53"}])
2021-11-24T01:41:44.235Z|info : amplify-provider-awscloudformation.aws-cfn.updateamplifyMetaFileWithStackOutputs.cfn.describeStackResources([{"StackName":"[***]ify-[***]atest-[***]ev-[***]53"}])
2021-11-24T01:41:44.498Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]ify-[***]atest-[***]ev-[***]53"}])
2021-11-24T01:41:45.048Z|info : amplify-provider-awscloudformation.aws-s3.s3.getFile([{"Key":"[***]ify-[***]json","Bucket":"[***]ify-[***]atest-[***]ev-[***]53-[***]ment"}])


```

</details>

**Comment by lazpavel** [comment]
Hi @kundarmah, thank you for raising this issue.
I am unable to reproduce following the reproduction steps. Can you provide following information:
- output from `amplify status`
- if possible can you send the contents of the `amplify` directory at ampify-cli@amazon.com

**Comment by attilah** [comment]
@kundarmah could you paste the contents of the `~/.aws/amplify/depolyment-secrets.json` file, but REMOVE the values, we just need to see the structure of that file.

**Comment by raphkim** [comment]
I had the same issue and I fixed it by just deleting `~/.aws/amplify/deployment-secrets.json` file. Going through the CLI flow for setting up federated auth again regenerated the file with correct parameters.

old:
```
{
  "url": "censored"
}
```

new:
```
{
  "appSecrets": [
    {
      "rootStackId": “censor”ed,
      "environments": {
        "dev": {
          "auth": {
            “App-name”: {
              "hostedUIProviderCreds": “censored”
            }
          }
        }
      }
    }
  ]
}
```

**Comment by attilah** [comment]
@raphkim don't know how that url was written to your file, but the fix will work for that use case as well.
