### ISSUE TITLE
Failed to pull the backend - AWS Amplify

### ISSUE THREAD

**Issue by poboisvert** [aws-amplify/amplify-cli#9085]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.13.0

### Amplify CLI Version

7.5.2

### What operating system are you using?

Mac

### Amplify Categories

auth

### Amplify Commands

init

### Describe the bug

When I pull the amplify to setup my local environment. It crashes

### Expected behavior

To be able to pull the credentials and queries

### Reproduction steps

Use the same software as stated
in the terminal, run: amplify pull --appId d12xdglpojx0 --envName staging

### GraphQL schema(s)

<details>

```graphql
No GraphQL


```

</details>

### Log output

<details>

```
Error: Unknown directive "connection".

Unknown directive "connection".

Unknown directive "key".

Unknown directive "connection".
Failed to pull the backend.
Unknown directive "connection".

Unknown directive "connection".

Unknown directive "key".

Unknown directive "connection".
Error: Unknown directive "connection".

Unknown directive "connection".

Unknown directive "key".

Unknown directive "connection".
    at assertValidSDL (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/validation/validate.js:108:11)
    at Object.buildASTSchema (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/utilities/buildASTSchema.js:71:34)
    at Object.codegen (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@graphql-codegen/core/src/codegen.ts:41:25)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/commands/models.js:126:23
    at Array.map (<anonymous>)
    at generateModels (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/commands/models.js:125:46)
    at postPullCodegen (/usr/local/lib/node_modules/@aws-amplify/cli/src/amplify-service-helper.ts:38:5)
    at onSuccess (/usr/local/lib/node_modules/@aws-amplify/cli/src/attach-backend.ts:59:3)
    at attachBackend (/usr/local/lib/node_modules/@aws-amplify/cli/src/attach-backend.ts:31:5)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/src/commands/pull.ts:59:5)
    at Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/index.ts:373:5)
    at executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:204:3)
    at executeCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:30:5)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/src/index.ts:205:5)


```

</details>

**Comment by cjihrig** [comment]
Does running the pull command with `--no-codegen` allow it to succeed?

**Comment by poboisvert** [comment]
Yes. It worked!
