### ISSUE TITLE
Amplify add env returns "Cannot read property 'serviceType' of undefined"

### ISSUE THREAD

**Issue by alexhouse** [aws-amplify/amplify-cli#9094]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm -g

### If applicable, what version of Node.js are you using?

14.18.1

### Amplify CLI Version

7.5.2

### What operating system are you using?

OSX 12.0.1

### Amplify Categories

Not applicable

### Amplify Commands

env

### Describe the bug

I've been prompted to upgrade my GraphQL API during a recent api update, and to test it by adding an environment.

Running `amplify env add` errors out with `Cannot read property 'serviceType' of undefined` as does `amplify status`

```
❯ amplify env add
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the environment test
Using default provider  awscloudformation
? Select the authentication method you want to use: AWS profile

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

? Please choose the profile you want to use default
Adding backend environment test to AWS Amplify app: {amplifyAppId}
⠧ Initializing project in the cloud...

CREATE_IN_PROGRESS amplify-{project}-test-{accountId} AWS::CloudFormation::Stack Thu Nov 25 2021 23:20:41 GMT+0000 (Greenwich Mean Time) User Initiated
CREATE_IN_PROGRESS DeploymentBucket             AWS::S3::Bucket            Thu Nov 25 2021 23:20:45 GMT+0000 (Greenwich Mean Time)
CREATE_IN_PROGRESS AuthRole                     AWS::IAM::Role             Thu Nov 25 2021 23:20:45 GMT+0000 (Greenwich Mean Time)
CREATE_IN_PROGRESS UnauthRole                   AWS::IAM::Role             Thu Nov 25 2021 23:20:45 GMT+0000 (Greenwich Mean Time)
CREATE_IN_PROGRESS UnauthRole                   AWS::IAM::Role             Thu Nov 25 2021 23:20:46 GMT+0000 (Greenwich Mean Time) Resource creation Initiated
CREATE_IN_PROGRESS AuthRole                     AWS::IAM::Role             Thu Nov 25 2021 23:20:46 GMT+0000 (Greenwich Mean Time) Resource creation Initiated
⠇ Initializing project in the cloud...

CREATE_IN_PROGRESS DeploymentBucket AWS::S3::Bucket Thu Nov 25 2021 23:20:47 GMT+0000 (Greenwich Mean Time) Resource creation Initiated
⠸ Initializing project in the cloud...

CREATE_COMPLETE UnauthRole AWS::IAM::Role Thu Nov 25 2021 23:21:00 GMT+0000 (Greenwich Mean Time)
CREATE_COMPLETE AuthRole   AWS::IAM::Role Thu Nov 25 2021 23:21:00 GMT+0000 (Greenwich Mean Time)
⠧ Initializing project in the cloud...

CREATE_COMPLETE DeploymentBucket             AWS::S3::Bucket            Thu Nov 25 2021 23:21:08 GMT+0000 (Greenwich Mean Time)
CREATE_COMPLETE amplify-{project}-test-{accountId} AWS::CloudFormation::Stack Thu Nov 25 2021 23:21:10 GMT+0000 (Greenwich Mean Time)
✔ Successfully created initial AWS cloud resources for deployments.
✔ Initialized provider successfully.
✖ There was an error initializing your environment.
TypeError: Cannot read property 'serviceType' of undefined
    at getResourcesToBeCreated (/Users/alex/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/resource-status-data.ts:220:65)
    at AmplifyToolkit.getResourceStatus [as _getResourceStatus] (/Users/alex/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/resource-status-data.ts:117:35)
    at initEnv (/Users/alex/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/index.ts:118:108)
    at /Users/alex/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/src/initialize-env.ts:45:52
    at /Users/alex/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/promise-sequential/index.js:16:18
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

### Expected behavior

An additional environment should be added

### Reproduction steps

I've not yet found a way to reproduce this despite spending a few hours on it.

The only possibility I can think of (given it's been prompted by a GraphQL upgrade) is to create a v1 GraphQL, then create a new environment perhaps? But I'm not sure how best to accomplish that.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line
2021-11-25T23:41:38.012Z|info : amplify env core add
2021-11-25T23:41:43.000Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["default"])
2021-11-25T23:41:43.001Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"eu-west-1","output":"table","s3":"","max_concurrent_requests":"20","max_queue_size":"10000","multipart_threshold":"64MB","multipart_chunksize":"16MB","signature_version":"s3v4"}])
2021-11-25T23:41:43.001Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["default"])
2021-11-25T23:41:57.897Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["default"])
2021-11-25T23:41:57.898Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"eu-west-1","output":"table","s3":"","max_concurrent_requests":"20","max_queue_size":"10000","multipart_threshold":"64MB","multipart_chunksize":"16MB","signature_version":"s3v4"}])
2021-11-25T23:41:57.898Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["default"])
2021-11-25T23:41:57.903Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["default"])
2021-11-25T23:41:57.903Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"eu-west-1","output":"table","s3":"","max_concurrent_requests":"20","max_queue_size":"10000","multipart_threshold":"64MB","multipart_chunksize":"16MB","signature_version":"s3v4"}])
2021-11-25T23:41:57.903Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["default"])
2021-11-25T23:41:57.909Z|info : amplify-provider-awscloudformation.amplify-service-permission-check.checkAmplifyServiceIAMPermission.amplifyClient.listApps([])
2021-11-25T23:41:58.212Z|info : amplify-provider-awscloudformation.amplify-service-manager.init.amplifyClient.listApps([{"maxResults":25}])
2021-11-25T23:41:58.339Z|info : amplify-provider-awscloudformation.amplify-service-manager.init.amplifyClient.getBackendEnvironment([{"appId":"[***]","environmentName":"[***]upg"}])
2021-11-25T23:41:58.446Z|error : amplify-provider-awscloudformation.amplify-service-manager.init.amplifyClient.getBackendEnvironment([{"appId":"[***]","environmentName":"[***]upg"}])
NotFoundException: BackendEnvironment testupg does not exist.
2021-11-25T23:41:58.447Z|info : amplify-provider-awscloudformation.amplify-service-manager.init.amplifyClient.getBackendEnvironment([{"appId":"[***]","environmentName":"[***]upg","stackName":"[***]ify-[***]-[***]upg-[***]","deploymentArtifacts":"amplify-[***]-testupg-[***]-deployment"}])
2021-11-25T23:41:58.568Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["default"])
2021-11-25T23:41:58.568Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"eu-west-1","output":"table","s3":"","max_concurrent_requests":"20","max_queue_size":"10000","multipart_threshold":"64MB","multipart_chunksize":"16MB","signature_version":"s3v4"}])
2021-11-25T23:41:58.568Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["default"])
2021-11-25T23:41:58.575Z|info : amplify-provider-awscloudformation.aws-cfn.cfnModel.createStack([{"StackName":"[***]ify-[***]-[***]upg-[***]","Capabilities":["CAPABILITY_NAMED_IAM","CAPABILITY_AUTO_EXPAND"],"TemplateBody":"{\"AWSTemplateFormatVersion\":\"2010-09-09\",\"Description\":\"{\\\"createdOn\\\":\\\"Mac\\\",\\\"createdBy\\\":\\\"Amplify\\\",\\\"createdWith\\\":\\\"7.5.2\\\",\\\"stackType\\\":\\\"root\\\",\\\"metadata\\\":{}}\",\"Parameters\":{\"[***]cketName\":{\"Description\":\"Name of the common deployment bucket provided by the parent stack\",\"Type\":\"String\",\"Default\":\"DeploymentBucket\"},\"[***]eName\":{\"Type\":\"String\",\"Default\":\"AuthRoleName\"},\"[***]leName\":{\"Type\":\"String\",\"Default\":\"UnauthRoleName\"}},\"Resources\":{\"DeploymentBucket\":{\"Type\":\"AWS::S3::Bucket\",\"DeletionPolicy\":\"Retain\",\"Properties\":{\"BucketName\":{\"Ref\":\"DeploymentBucketName\"},\"BucketEncryption\":{\"ServerSideEncryptionConfiguration\":[{\"ServerSideEncryptionByDefault\":{\"SSEAlgorithm\":\"AES256\"}}]}}},\"AuthRole\":{\"Type\":\"AWS::IAM::Role\",\"Properties\":{\"RoleName\":{\"Ref\":\"AuthRoleName\"},\"AssumeRolePolicyDocument\":{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"\",\"Effect\":\"Deny\",\"Principal\":{\"Federated\":\"cognito-identity.amazonaws.com\"},\"Action\":\"sts:AssumeRoleWithWebIdentity\"}]}}},\"UnauthRole\":{\"Type\":\"AWS::IAM::Role\",\"Properties\":{\"RoleName\":{\"Ref\":\"UnauthRoleName\"},\"AssumeRolePolicyDocument\":{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"\",\"Effect\":\"Deny\",\"Principal\":{\"Federated\":\"cognito-identity.amazonaws.com\"},\"Action\":\"sts:AssumeRoleWithWebIdentity\"}]}}}},\"Outputs\":{\"Region\":{\"Description\":\"CloudFormation provider root stack Region\",\"Value\":{\"Ref\":\"AWS::Region\"},\"Export\":{\"Name\":{\"Fn::Sub\":\"${AWS::StackName}-Region\"}}},\"StackName\":{\"Description\":\"CloudFormation provider root stack ID\",\"Value\":{\"Ref\":\"AWS::StackName\"},\"Export\":{\"Name\":{\"Fn::Sub\":\"${AWS::StackName}-StackName\"}}},\"StackId\":{\"Description\":\"CloudFormation provider root stack name\",\"Value\":{\"Ref\":\"AWS::StackId\"},\"Export\":{\"Name\":{\"Fn::Sub\":\"${AWS::StackName}-StackId\"}}},\"DeploymentBucketName\":{\"Description\":\"CloudFormation provider root stack deployment bucket name\",\"Value\":{\"Ref\":\"DeploymentBucketName\"},\"Export\":{\"Name\":{\"Fn::Sub\":\"${AWS::StackName}-DeploymentBucketName\"}}},\"AuthRoleArn\":{\"Value\":{\"Fn::GetAtt\":[\"AuthRole\",\"Arn\"]}},\"UnauthRoleArn\":{\"Value\":{\"Fn::GetAtt\":[\"UnauthRole\",\"Arn\"]}},\"AuthRoleName\":{\"Value\":{\"Ref\":\"AuthRole\"}},\"UnauthRoleName\":{\"Value\":{\"Ref\":\"UnauthRole\"}}}}","Parameters":[{"ParameterKey":"DeploymentBucketName","ParameterValue":"amplify-[***]-testupg-[***]-deployment"},{"ParameterKey":"AuthRoleName","ParameterValue":"amplify-[***]-testupg-[***]-authRole"},{"ParameterKey":"UnauthRoleName","ParameterValue":"amplify-[***]-testupg-[***]-unauthRole"}],"Tags":[{"Key":"[***]tack","Value":"prod"},{"Key":"[***]ication","Value":"[***]"}]}])
2021-11-25T23:41:58.834Z|info : amplify-provider-awscloudformation.aws-cfn.cfnModel.createStack([{"StackName":"[***]ify-[***]-[***]upg-[***]","Capabilities":["CAPABILITY_NAMED_IAM","CAPABILITY_AUTO_EXPAND"],"TemplateBody":"{\"AWSTemplateFormatVersion\":\"2010-09-09\",\"Description\":\"{\\\"createdOn\\\":\\\"Mac\\\",\\\"createdBy\\\":\\\"Amplify\\\",\\\"createdWith\\\":\\\"7.5.2\\\",\\\"stackType\\\":\\\"root\\\",\\\"metadata\\\":{}}\",\"Parameters\":{\"[***]cketName\":{\"Description\":\"Name of the common deployment bucket provided by the parent stack\",\"Type\":\"String\",\"Default\":\"DeploymentBucket\"},\"[***]eName\":{\"Type\":\"String\",\"Default\":\"AuthRoleName\"},\"[***]leName\":{\"Type\":\"String\",\"Default\":\"UnauthRoleName\"}},\"Resources\":{\"DeploymentBucket\":{\"Type\":\"AWS::S3::Bucket\",\"DeletionPolicy\":\"Retain\",\"Properties\":{\"BucketName\":{\"Ref\":\"DeploymentBucketName\"},\"BucketEncryption\":{\"ServerSideEncryptionConfiguration\":[{\"ServerSideEncryptionByDefault\":{\"SSEAlgorithm\":\"AES256\"}}]}}},\"AuthRole\":{\"Type\":\"AWS::IAM::Role\",\"Properties\":{\"RoleName\":{\"Ref\":\"AuthRoleName\"},\"AssumeRolePolicyDocument\":{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"\",\"Effect\":\"Deny\",\"Principal\":{\"Federated\":\"cognito-identity.amazonaws.com\"},\"Action\":\"sts:AssumeRoleWithWebIdentity\"}]}}},\"UnauthRole\":{\"Type\":\"AWS::IAM::Role\",\"Properties\":{\"RoleName\":{\"Ref\":\"UnauthRoleName\"},\"AssumeRolePolicyDocument\":{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"\",\"Effect\":\"Deny\",\"Principal\":{\"Federated\":\"cognito-identity.amazonaws.com\"},\"Action\":\"sts:AssumeRoleWithWebIdentity\"}]}}}},\"Outputs\":{\"Region\":{\"Description\":\"CloudFormation provider root stack Region\",\"Value\":{\"Ref\":\"AWS::Region\"},\"Export\":{\"Name\":{\"Fn::Sub\":\"${AWS::StackName}-Region\"}}},\"StackName\":{\"Description\":\"CloudFormation provider root stack ID\",\"Value\":{\"Ref\":\"AWS::StackName\"},\"Export\":{\"Name\":{\"Fn::Sub\":\"${AWS::StackName}-StackName\"}}},\"StackId\":{\"Description\":\"CloudFormation provider root stack name\",\"Value\":{\"Ref\":\"AWS::StackId\"},\"Export\":{\"Name\":{\"Fn::Sub\":\"${AWS::StackName}-StackId\"}}},\"DeploymentBucketName\":{\"Description\":\"CloudFormation provider root stack deployment bucket name\",\"Value\":{\"Ref\":\"DeploymentBucketName\"},\"Export\":{\"Name\":{\"Fn::Sub\":\"${AWS::StackName}-DeploymentBucketName\"}}},\"AuthRoleArn\":{\"Value\":{\"Fn::GetAtt\":[\"AuthRole\",\"Arn\"]}},\"UnauthRoleArn\":{\"Value\":{\"Fn::GetAtt\":[\"UnauthRole\",\"Arn\"]}},\"AuthRoleName\":{\"Value\":{\"Ref\":\"AuthRole\"}},\"UnauthRoleName\":{\"Value\":{\"Ref\":\"UnauthRole\"}}}}","Parameters":[{"ParameterKey":"DeploymentBucketName","ParameterValue":"amplify-[***]-testupg-[***]-deployment"},{"ParameterKey":"AuthRoleName","ParameterValue":"amplify-[***]-testupg-[***]-authRole"},{"ParameterKey":"UnauthRoleName","ParameterValue":"amplify-[***]-testupg-[***]-unauthRole"}],"Tags":[{"Key":"[***]tack","Value":"prod"},{"Key":"[***]ication","Value":"[***]"}]}])
2021-11-25T23:42:03.843Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]ify-[***]-[***]upg-[***]"}])
2021-11-25T23:42:03.996Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]rmation:eu-[***]st-[***]53:stack/[***]ify-[***]-[***]upg-[***]/[***]2d50-[***]49-[***]ec-[***]4c-[***]025b7"}])
2021-11-25T23:42:08.839Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]ify-[***]-[***]upg-[***]"}])
2021-11-25T23:42:08.988Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]rmation:eu-[***]st-[***]53:stack/[***]ify-[***]-[***]upg-[***]/[***]2d50-[***]49-[***]ec-[***]4c-[***]025b7"}])
2021-11-25T23:42:13.841Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]ify-[***]-[***]upg-[***]"}])
2021-11-25T23:42:14.008Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]rmation:eu-[***]st-[***]53:stack/[***]ify-[***]-[***]upg-[***]/[***]2d50-[***]49-[***]ec-[***]4c-[***]025b7"}])
2021-11-25T23:42:18.841Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]ify-[***]-[***]upg-[***]"}])
2021-11-25T23:42:18.999Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]rmation:eu-[***]st-[***]53:stack/[***]ify-[***]-[***]upg-[***]/[***]2d50-[***]49-[***]ec-[***]4c-[***]025b7"}])
2021-11-25T23:42:23.840Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]ify-[***]-[***]upg-[***]"}])
2021-11-25T23:42:23.993Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]rmation:eu-[***]st-[***]53:stack/[***]ify-[***]-[***]upg-[***]/[***]2d50-[***]49-[***]ec-[***]4c-[***]025b7"}])
2021-11-25T23:42:28.842Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]ify-[***]-[***]upg-[***]"}])
2021-11-25T23:42:28.999Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]rmation:eu-[***]st-[***]53:stack/[***]ify-[***]-[***]upg-[***]/[***]2d50-[***]49-[***]ec-[***]4c-[***]025b7"}])
2021-11-25T23:42:38.435Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["default"])
2021-11-25T23:42:38.436Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"eu-west-1","output":"table","s3":"","max_concurrent_requests":"20","max_queue_size":"10000","multipart_threshold":"64MB","multipart_chunksize":"16MB","signature_version":"s3v4"}])
2021-11-25T23:42:38.437Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["default"])
2021-11-25T23:42:38.448Z|info : amplify-provider-awscloudformation.attach-backend.storeCurrentCloudBackend.s3.uploadFile([{"Key":"[***]rent-[***]ud-[***]d.zip"}])
2021-11-25T23:42:38.455Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.upload([{"Key":"[***]rent-[***]ud-[***]d.zip","Bucket":"[***]ify-[***]-[***]upg-[***]-[***]ment"}])
2021-11-25T23:42:58.295Z|info : amplify-provider-awscloudformation.attach-backend.uploadFile.s3.uploadFile([{"Key":"[***]ify-[***]json"}])
2021-11-25T23:42:58.299Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Key":"[***]ify-[***]json","Bucket":"[***]ify-[***]-[***]upg-[***]-[***]ment"}])
2021-11-25T23:42:58.468Z|info : amplify-provider-awscloudformation.attach-backend.uploadFile.s3.uploadFile([{"Key":"[***]end-[***].json"}])
2021-11-25T23:42:58.469Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Key":"[***]end-[***].json","Bucket":"[***]ify-[***]-[***]upg-[***]-[***]ment"}])
2021-11-25T23:42:58.667Z|info : amplify-provider-awscloudformation.aws-s3.deleteDirectory.s3.getAllObjectVersions([{"BucketName":"[***]ify-[***]-[***]upg-[***]-[***]ment"}])
2021-11-25T23:42:58.668Z|info : amplify-provider-awscloudformation.aws-s3.getAllObjectKey.s3.listObjectVersions([{"Bucket":"[***]ify-[***]-[***]upg-[***]-[***]ment","Prefix":"hooks/"}])

```

</details>

### Additional information

I'm currently a bit stuck as I can't create a new environment to check if the GraphQL upgrade breaks anything! 

Attempts to re-add the environment after the first add results in:

```
❯ amplify env add
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the environment testupg
Using default provider  awscloudformation
⠸ Initializing your environment: testupgCould not initialize 'testupg': Cannot read property 'serviceType' of undefined
```

(this _was_ run from the git root)

Attempted reverting all the way back to CLI 7.3.0 but hitting exactly the same error. Couldn't go to <7 due to cli.json blocks.

**Comment by renebrandel** [comment]
hi @alexhouse - can you try the instructions that @kaustavghosh06 provided here: https://github.com/aws-amplify/amplify-cli/issues/9025 the error seems to be very similar.

**Comment by alexhouse** [comment]
> hi @alexhouse - can you try the instructions that @kaustavghosh06 provided here: #9025 the error seems to be very similar.

You genius. I spent about two hours yesterday just trying different CLI versions & constantly googling different phrases to try and find anyone with the same issue. Apparently I didn't use exactly the right phrases!

Took me another half hour combing through my backend-config.json thinking there was nothing wrong until I decided I couldn't trust my manual process so came up with this stupid script that immediately found the issue:

```javascript
config = require('./backend-config.json');
for (category in config) {
  console.debug(`Checking ${category}...`);
  for (mod in config[category]) {
    if ('dependsOn' in config[category][mod]) {
      for (dependency of config[category][mod].dependsOn) {
        console.debug(`-> ${mod} depends on ${dependency.category}/${dependency.resourceName}`, dependency.resourceName in config[dependency.category]);
      }
    }
  }
}
```

Turns out that indeed one of my functions depended on a lambda layer that had been deleted long ago. Removed that, tidied up some duplicate GraphQL dependencies (with very slightly different attributes) and bingo bango, you've solved my soon-to-be-baldness.

Thanks @renebrandel!
