### ISSUE TITLE
S3 trigger event does not work in the mock mode

### ISSUE THREAD

**Issue by laboone** [aws-amplify/amplify-cli#9128]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.18.1

### Amplify CLI Version

7.5.3

### What operating system are you using?

Mac

### Amplify Categories

storage

### Amplify Commands

Not applicable

### Describe the bug

When I uploaded a photo using `Storage.put({identityId: 'xxxxx', ...})` in amplify mock mode, the amplify mock command crashed with the following error.

```
2021-11-28T13:14:48.871Z - error: uncaughtException: The "path" argument must be of type string. Received undefined
:
stack=[TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined,
at new NodeError (internal/errors.js:322:7),     
at validateString (internal/validators.js:124:11),     
at Object.join (path.js:1148:7),     
at loadLambdaConfig (/Users/hoge/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/src/utils/lambda/load-lambda-config.ts:27:29),
at runMicrotasks (<anonymous>),     
at processTicksAndRejections (internal/process/task_queues.js:95:5),     
at StorageServer.<anonymous> (/Users/hoge/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/src/storage/storage.ts:133:22)]
```

This error occurred after migrating to amplify-cli ver7. (https://docs.amplify.aws/cli/migration/override/)

In the previous version, S3 trigger event worked properly.
My cloudformation template file(`amplify/backend/storage/hoge/s3-cloudformation-template.json`) was as follows.

<details><summary>amplify/backend/storage/hoge/s3-cloudformation-template.json</summary>

```json
:
                "NotificationConfiguration": {
                    "LambdaConfigurations": [
                        {
                            "Event": "s3:ObjectCreated:*",
                            "Function": {
                                "Ref": "functionS3Trigger51e7dea0Arn"
                            }
                        }
                    ]
                },
:
```

</details>

The value of `triggerName` variable was assigned [here](https://github.com/aws-amplify/amplify-cli/blob/acfa82c9b275df0a7347ae0700a919dd8c03a4de/packages/amplify-util-mock/src/storage/storage.ts#L106) in this template file.

--

In the latest version(v7.5.3), my cloudformation template file(`amplify/backend/storage/hoge/build/cloudformation-template.json`) was as follows.

<details><summary>amplify/backend/storage/hoge/build/cloudformation-template.json</summary>

```json
"NotificationConfiguration": {
          "LambdaConfigurations": [
            {
              "Event": "s3:ObjectCreated:*",
              "Filter": {
                "S3Key": {
                  "Rules": [
                    {
                      "Name": "prefix",
                      "Value": {
                        "Fn::Join": [
                          "",
                          [
                            "protected/",
                            {
                              "Ref": "AWS::Region"
                            }
                          ]
                        ]
                      }
                    }
                  ]
                }
              },
              "Function": {
                "Ref": "functionS3Trigger51e7dea0Arn"
              }
            },
            {
              "Event": "s3:ObjectCreated:*",
              "Filter": {
                "S3Key": {
                  "Rules": [
                    {
                      "Name": "prefix",
                      "Value": {
                        "Fn::Join": [
                          "",
                          [
                            "private/",
                            {
                              "Ref": "AWS::Region"
                            }
                          ]
                        ]
                      }
                    }
                  ]
                }
              },
              "Function": {
                "Ref": "functionS3Trigger51e7dea0Arn"
              }
            },
            {
              "Event": "s3:ObjectCreated:*",
              "Filter": {
                "S3Key": {
                  "Rules": [
                    {
                      "Name": "prefix",
                      "Value": {
                        "Fn::Join": [
                          "",
                          [
                            "public/",
                            {
                              "Ref": "AWS::Region"
                            }
                          ]
                        ]
                      }
                    }
                  ]
                }
              },
              "Function": {
                "Ref": "functionS3Trigger51e7dea0Arn"
              }
            },
            {
              "Event": "s3:ObjectRemoved:*",
              "Filter": {
                "S3Key": {
                  "Rules": [
                    {
                      "Name": "prefix",
                      "Value": {
                        "Fn::Join": [
                          "",
                          [
                            "protected/",
                            {
                              "Ref": "AWS::Region"
                            }
                          ]
                        ]
                      }
                    }
                  ]
                }
              },
              "Function": {
                "Ref": "functionS3Trigger51e7dea0Arn"
              }
            },
            {
              "Event": "s3:ObjectRemoved:*",
              "Filter": {
                "S3Key": {
                  "Rules": [
                    {
                      "Name": "prefix",
                      "Value": {
                        "Fn::Join": [
                          "",
                          [
                            "private/",
                            {
                              "Ref": "AWS::Region"
                            }
                          ]
                        ]
                      }
                    }
                  ]
                }
              },
              "Function": {
                "Ref": "functionS3Trigger51e7dea0Arn"
              }
            },
            {
              "Event": "s3:ObjectRemoved:*",
              "Filter": {
                "S3Key": {
                  "Rules": [
                    {
                      "Name": "prefix",
                      "Value": {
                        "Fn::Join": [
                          "",
                          [
                            "public/",
                            {
                              "Ref": "AWS::Region"
                            }
                          ]
                        ]
                      }
                    }
                  ]
                }
              },
              "Function": {
                "Ref": "functionS3Trigger51e7dea0Arn"
              }
            }
          ]
        }
```

</details>

As far as I investigated, the value of `node` variable was assigned [here](https://github.com/aws-amplify/amplify-cli/blob/acfa82c9b275df0a7347ae0700a919dd8c03a4de/packages/amplify-util-mock/src/storage/storage.ts#L115). 
But [`keyName`](https://github.com/aws-amplify/amplify-cli/blob/acfa82c9b275df0a7347ae0700a919dd8c03a4de/packages/amplify-util-mock/src/storage/storage.ts#L110) did not include the region.
So [this line](https://github.com/aws-amplify/amplify-cli/blob/acfa82c9b275df0a7347ae0700a919dd8c03a4de/packages/amplify-util-mock/src/storage/storage.ts#L123
) was never executed and `triggerName` was never assigned.
As a result, the error occurred.

In my local environment, I made the following modifications, and the error was resolved.

```diff
Index: packages/amplify-util-mock/src/storage/storage.ts
<+>UTF-8
===================================================================
diff --git a/packages/amplify-util-mock/src/storage/storage.ts b/packages/amplify-util-mock/src/storage/storage.ts
--- a/packages/amplify-util-mock/src/storage/storage.ts	(revision b6504ca858be264fbb19b377c9a38343cbb7c313)
+++ b/packages/amplify-util-mock/src/storage/storage.ts	(date 1638163618919)
@@ -112,7 +112,7 @@
           for (let rules of prefix_arr) {
             let node;
             if (typeof rules.Value === 'object') {
-              node = String(Object.values(rules.Value)[0][1][0] + String(region) + ':');
+              node = String(Object.values(rules.Value)[0][1][0]);
             }
 
             if (typeof rules.Value === 'string') {
```

### Expected behavior

Lambda function is executed by S3 trigger event.

### Reproduction steps

Please see `Describe the bug` section.

**Comment by lazpavel** [comment]
Hi @laboone, thank you for raising this issue. I marked it as a bug for the team to pick up.

**Comment by sachscode** [comment]
@laboone 
The following PR is being raised to fix the change in the notificationTrigger template .  
https://github.com/aws-amplify/amplify-cli/pull/9235
an example of the policy after the fix is:
   "NotificationConfiguration": {
          "LambdaConfigurations": [
            {
              "Event": "s3:ObjectCreated:*",
              "Function": {
                "Ref": "functionnewtrigger87c981caArn"
              }
            },
            {
              "Event": "s3:ObjectRemoved:*",
              "Function": {
                "Ref": "functionnewtrigger87c981caArn"
              }
            }
          ]
        }

Hence the following will continue to work with the next release: 
String(obj.Function.Ref).split('function')[1].split('Arn')[0];

**Comment by sachscode** [comment]
Closing this, since fix has been merged.
