### ISSUE TITLE
Backend build fails for lack of /amplify/backend/api/AdminQueries/api-params.json

### ISSUE THREAD

**Issue by lseemann** [aws-amplify/amplify-cli#9172]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

12

### Amplify CLI Version

7.5.5

### What operating system are you using?

MacOS

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

I upgrade CLI from 6.3.1 to 7.5.5. I was able to successfully push to a test env.

Build Settings had previously been set to use `6.3.1`, so I changed to `latest`.

Now build fails with the following error:

```
2021-12-01T18:37:11.648Z [INFO]: 🛑 Error reading api-params.json file for AdminQueries resource
2021-12-01T18:37:11.814Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
2021-12-01T18:37:11.820Z [WARNING]: ✖ There was an error initializing your environment.
2021-12-01T18:37:11.823Z [INFO]: [0mError: File at path: '/codebuild/output/src554795478/src/Meltzer-Hellrung-Portal/amplify/backend/api/AdminQueries/api-params.json' does not exist
```

I see that our other APIs have an `api-params.json`, but AdminQueries has never had one.

### Expected behavior

The build should work.

### Reproduction steps

1. Use latest CLI in build settings
2. Build

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
2021-12-01T18:37:11.648Z [INFO]: 🛑 Error reading api-params.json file for AdminQueries resource
2021-12-01T18:37:11.814Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
2021-12-01T18:37:11.820Z [WARNING]: ✖ There was an error initializing your environment.
2021-12-01T18:37:11.823Z [INFO]: [0mError: File at path: '/codebuild/output/src554795478/src/Meltzer-Hellrung-Portal/amplify/backend/api/AdminQueries/api-params.json' does not exist

```

</details>

**Comment by josefaidt** [comment]
Hey @lseemann :wave: thanks for filing this! The team is currently investigating 🙂

**Comment by daniellorenzin** [comment]
I think  I have an issue related to this as well, after the recently version I also get the following error:
`Do you want to migrate api resource "apiEvents"? (Y/n) · yes
🛑 Cannot read properties of undefined (reading 'forEach')
TypeError: Cannot read properties of undefined (reading 'forEach')
    at ApigwInputState.migrateApigwResource (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-api/lib/provider-utils/awscloudformation/apigw-input-state.js:132:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-api/lib/commands/api/override.js:81:17)
    at async Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-api/lib/index.js:201:9)
    at async executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:187:5)
    at async executeCommand (/usr/local/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:35:9)
    at async Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/lib/index.js:162:9)`

**Comment by jhockett** [comment]
@daniellorenzin can you paste the content of `amplify/backend/api/apiEvents/api-params.json` here?

**Comment by daniellorenzin** [comment]
It was just an empty json object

`{}`

**Comment by jhockett** [comment]
@daniellorenzin sorry I missed your reply until now. The migration is expecting your api definition in `api-params.json`, that's why the migration failed. There's been an improvement to the error handling here that's been merged, but not yet released. If you're blocked, can you open a new issue so we can track it?

@lseemann a fix for this issue has been released.
