### ISSUE TITLE
headless pull results in Error: auth headless is missing the following inputParams userPoolId, webClientId, nativeClientId

### ISSUE THREAD

**Issue by david-wb** [aws-amplify/amplify-cli#9191]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.10.0

### Amplify CLI Version

7.4.0

### What operating system are you using?

Ubuntu 18.04

### Amplify Categories

auth, hosting

### Amplify Commands

pull

### Describe the bug

I am trying to pull an amplify app in a headless manner, like below.

```bash
REACTCONFIG="{\
\"SourceDir\":\"src\",\
\"DistributionDir\":\"build\",\
\"BuildCommand\":\"npm run-script build\",\
\"StartCommand\":\"npm run-script start\"\
}"
AWSCLOUDFORMATIONCONFIG="{\
\"configLevel\":\"project\",\
\"useProfile\":true,\
\"profileName\":\"ci-dev\",\
\"region\":\"us-west-2\"\
}"
AMPLIFY="{\
\"projectName\":\"corewebapp\",\
\"appId\":\"d1dkk89c3sv7mb\",\
\"envName\":\"dev\",\
\"defaultEditor\":\"code\"\
}"
FRONTEND="{\
\"frontend\":\"javascript\",\
\"framework\":\"react\",\
\"config\":$REACTCONFIG\
}"
PROVIDERS="{\
\"awscloudformation\":$AWSCLOUDFORMATIONCONFIG\
}"

amplify pull \
--amplify $AMPLIFY \
--frontend $FRONTEND \
--providers $PROVIDERS \
--yes 

```

This results in the following error:

```bash
$ ./scripts/amplify-pull-dev.sh 
{"projectName":"corewebapp","appId":"d1dkk89c3sv7mb","envName":"dev","defaultEditor":"code"}
{"frontend":"javascript","framework":"react","config":{"SourceDir":"src","DistributionDir":"build","BuildCommand":"npm run-script build","StartCommand":"npm run-script start"}}
{"awscloudformation":{"configLevel":"project","useProfile":true,"profileName":"ci-dev","region":"us-west-2"}}
Amplify AppID found: d1dkk89c3sv7mb. Amplify App name is: corewebapp
Backend environment dev found in Amplify Console app: corewebapp
✔ Successfully pulled backend environment dev from the cloud.
✖ There was an error initializing your environment.
Failed to pull the backend.
auth headless is missing the following inputParams userPoolId, webClientId, nativeClientId
Error: auth headless is missing the following inputParams userPoolId, webClientId, nativeClientId
    at ensureHeadlessParameters (/home/david/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/provider-utils/awscloudformation/import/index.ts:1312:11)
    at Object.headlessImport (/home/david/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/provider-utils/awscloudformation/import/index.ts:1169:40)
    at importedAuthEnvInit (/home/david/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/provider-utils/awscloudformation/import/index.ts:946:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at updateConfigOnEnvInit (/home/david/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/provider-utils/awscloudformation/index.js:52:72)
    at /home/david/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/index.js:349:22
```

### Expected behavior

Pull command should pull the app without errors.

### Reproduction steps

1. Create an amplify app with auth
2. Run the headless pull script that I provided above.

**Comment by akshbhu** [comment]
Hi @david-wb 

Can you update your pull script with this info mentioned here: https://docs.amplify.aws/cli/usage/headless/#--categories

Updated pull script should look like this:
```
REACTCONFIG="{\
\"SourceDir\":\"src\",\
\"DistributionDir\":\"build\",\
\"BuildCommand\":\"npm run-script build\",\
\"StartCommand\":\"npm run-script start\"\
}"
AWSCLOUDFORMATIONCONFIG="{\
\"configLevel\":\"project\",\
\"useProfile\":true,\
\"profileName\":\"ci-dev\",\
\"region\":\"us-west-2\"\
}"
AMPLIFY="{\
\"projectName\":\"corewebapp\",\
\"appId\":\"d1dkk89c3sv7mb\",\
\"envName\":\"dev\",\
\"defaultEditor\":\"code\"\
}"
FRONTEND="{\
\"frontend\":\"javascript\",\
\"framework\":\"react\",\
\"config\":$REACTCONFIG\
}"
PROVIDERS="{\
\"awscloudformation\":$AWSCLOUDFORMATIONCONFIG\
}"

AUTHCONFIG="{\
\"userPoolId\": \"myproject-userpool-id\",\
\"webClientId\": \"appid-web\",\
\"nativeClientId\": \"appid-native\",\
}"

CATEGORIES="{\
\"auth\":$AUTHCONFIG\
}"

amplify pull \
--amplify $AMPLIFY \
--frontend $FRONTEND \
--providers $PROVIDERS \
--categories $CATEGORIES \
--yes 

```

**Comment by david-wb** [comment]
@akshbhu It seems the `pull` command does not accept a `--categories` argument.

**Comment by david-wb** [comment]
Ok, I tried that @akshbhu, and categories arg is accepted, but now I am getting a different error:

```bash
$ ./scripts/amplify-pull-dev.sh 
Amplify AppID found: d1dkk89c3sv7mb. Amplify App name is: corewebapp
Backend environment dev found in Amplify Console app: corewebapp
Failed to pull the backend.
File at path: '/home/david/github/bavard/core-web-app-aws/amplify/backend/auth/corewebappabb25022/parameters.json' does not exist
Error: File at path: '/home/david/github/bavard/core-web-app-aws/amplify/backend/auth/corewebappabb25022/parameters.json' does not exist
    at Function.JSONUtilities.readJson (/home/david/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/jsonUtilities.ts:25:15)
    at StateManager.getData (/home/david/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/state-manager/stateManager.ts:399:32)
    at StateManager.getResourceParametersJson (/home/david/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/state-manager/stateManager.ts:147:17)
    at ensureAmplifyMetaFrontendConfig (/home/david/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/on-category-outputs-change.ts:84:55)
    at AmplifyToolkit.onCategoryOutputsChange [as _onCategoryOutputsChange] (/home/david/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/on-category-outputs-change.ts:18:5)
    at generateFiles (/home/david/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/src/attach-backend-steps/a40-generateFiles.ts:45:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at attachBackend (/home/david/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/src/attach-backend.ts:30:5)
    at Object.run (/home/david/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/src/commands/pull.ts:59:5)
    at Object.executeAmplifyCommand (/home/david/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/src/index.ts:373:5)
    at executePluginModuleCommand (/home/david/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:204:3)
    at executeCommand (/home/david/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:30:5)
    at Object.run (/home/david/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/src/index.ts:205:5)
```

**Comment by akshbhu** [comment]
Can you check if the parameters.json present in the auth folder , if its present inside build dir , You can move that file outside build folder and try again ?

Are you using imported auth ??

**Comment by david-wb** [comment]
@akshbhu I can confirm the parameters.json file exists, but the pull command still fails.

![Screenshot from 2021-12-03 14-41-22](https://user-images.githubusercontent.com/1855225/144676456-2d124968-002e-42c5-a6c5-33e22d25f7a5.png)

And yes this is imported auth.

**Comment by akshbhu** [comment]
Thank you for this info .

Can you try the same operation with our latest version 7.6.2?

**Comment by david-wb** [comment]
I am using 7.6.2. If I downgrade to 7.4.0, it works.

**Comment by akshbhu** [comment]
Hmm , this is strange : /home/david/github/core-web-app-aws/amplify/backend/auth/corewebappabb25022/parameters.json

this filepath exists based on your screenshots

Can you check in the #current-cloud-backend , the parameters file exists  on same path ?

Can you mail your amplify folder to amplify-cli@amazon.com with issue number as subject and redacting any secret info present?

Ill try to repro this on my end

**Comment by david-wb** [comment]
@akshbhu Sure, I'll do that. Please not that everything works on version 7.4.0 using the `--categories` arg. 

However, on version 7.6.2, I get the parameters.json file not found error. 

I can see that on 7.4.0 the parameters.json file is inside the `auth/<app>/build/` folder, but on 7.6.2 it is in `auth/<app>/` folder.

**Comment by akshbhu** [comment]
yes , 

for imported resources , parameters.json shouldn't be inside build folder. we have changed that , Just wanted to know why its failing in your case , since you have parameters.json present at right path .

Might be in your #current-cloud-backend , parameters.json is still present in build folder

**Comment by akshbhu** [comment]
I can see that your cloudformation is still present in build folder i. #current-cloud-backend. 

You can try a forcePush to update #current-cloud-backend as same as your backend and try pull script again.

Let me know if these steps works for you?

**Comment by david-wb** [comment]
Yes it worked for me finally after doing an amplify push --force. Thank you.

**Comment by josefaidt** [comment]
Closing based on comment above. Glad to hear you're back up and running @david-wb 🙂
