### ISSUE TITLE
amplify remove env fails

### ISSUE THREAD

**Issue by gearoidgit** [aws-amplify/amplify-cli#9194]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.9.1

### Amplify CLI Version

7.6.1

### What operating system are you using?

Mac

### Amplify Categories

auth, function, api

### Amplify Commands

env

### Describe the bug

Checkout a new git branch from an branch that has an existing amplify enviroment ( `env1` )
Create  new amplify environment (`env2`)
Do not push the new environment
Checkout the orginal amplify environment (`env1`)
Run `amplify env remove env2`
Get the following error, and the env is not removed
```
⠼ Deleting resources from the cloud. This may take a few minutes...
Error occurred while deleting env: env2.
null
✖ remove env failed: null
BadRequest: 
    at Request.extractError ( /.nvm/versions/node/v16.9.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/services/s3.js:690:35)
    at Request.callListeners ( /.nvm/versions/node/v16.9.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit ( /.nvm/versions/node/v16.9.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit ( /.nvm/versions/node/v16.9.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition ( /.nvm/versions/node/v16.9.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo ( /.nvm/versions/node/v16.9.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at  /.nvm/versions/node/v16.9.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> ( /.nvm/versions/node/v16.9.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> ( /.nvm/versions/node/v16.9.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners ( /.nvm/versions/node/v16.9.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit ( /.nvm/versions/node/v16.9.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    
    at Request.emit ( /.nvm/versions/node/v16.9.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition ( /.nvm/versions/node/v16.9.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo ( /.nvm/versions/node/v16.9.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at  /.nvm/versions/node/v16.9.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> ( /.nvm/versions/node/v16.9.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> ( /.nvm/versions/node/v16.9.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners ( /.nvm/versions/node/v16.9.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at callNextListener ( /.nvm/versions/node/v16.9.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at IncomingMessage.onEnd ( /.nvm/versions/node/v16.9.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/event_listeners.js:335:13)
    at IncomingMessage.emit (node:events:406:35)
    at IncomingMessage.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

### Expected behavior

Environment gets removed

### Reproduction steps

See bug description

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line
2021-12-02T21:57:07.957Z|info : amplify env core remove env2
2021-12-02T21:57:50.254Z|info : amplify-provider-awscloudformation.aws-s3.ifBucketExists.s3.headBucket([{"BucketName":"[REDACTED]"}])
2021-12-02T21:57:50.706Z|error : amplify-provider-awscloudformation.aws-s3.ifBucketExists.s3.headBucket([{"BucketName":"REDACTED"}])
BadRequest: null

```

</details>

**Comment by danielleadams** [comment]
@gearoidgit when you run `amplify env list` - is the environment listed? Also, can you confirm that the environment was successfully created? Environment names are only alphabetic (without numbers), so it looks like the environment wasn't created successfully in the first place. What was the command you used to create the environment?

**Comment by gearoidgit** [comment]
Yes the envrionment is listed.  
I used a generic env name in my example - I didn't use numbers in the actual env names.

For further information the aws cli does delete the environment
`aws amplify delete-backend-environment --app-id <> --environment-name <>`

**Comment by gearoidgit** [comment]
While using `aws amplify delete-backend-environment` has deleted the environment it is still listed when running `amplify env list`.   The local list of environments does not seem to be refreshed because it now shows the deleted environment and does not show other newly addd environments.

**Comment by sachscode** [comment]
Hi @gearoidgit 
[amplify env delete problem ]
Could you please check your Cloudformation logs to root-cause why the deletion of the environment fail ? 

[delete-backend-environment error] 
Could you please try running an  `amplify pull` in an empty folder to confirm if the environment is deleted.

**Comment by cjihrig** [comment]
Closing due to a lack of followup, but we can revisit this issue if needed.

**Comment by ddivita** [comment]
I am running into this same issue on `10.4.0`. 

I am seeing environments that have been removed from amplify using the console and `amplify env remove`. Are there local files holding onto that data?

**Comment by ddivita** [comment]
Seems there is a `local-aws-info.json` file that holds it. Once I removed the environments from the file they disappear from the list.
