### ISSUE TITLE
Amplify migrate api works on sandbox deployment, breaks CI

### ISSUE THREAD

**Issue by jayKayEss** [aws-amplify/amplify-cli#9245]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

v16.13.0

### Amplify CLI Version

7.6.2

### What operating system are you using?

mac

### Amplify Categories

auth, storage, api

### Amplify Commands

Not applicable

### Describe the bug

We have multiple developers, each working in their own sandbox deployment, under their own App ID, using their own IAM credentials.

We also have a shared App ID, connected to git, with two statically-configured deployments for `master` and `develop` branches, and the Branch Autodetect feature enabled for feature branches.

Using `amplify api migrate` to migrate to GraphQL Transformer v2 works in sandbox deployments and on a newly-created autodetected branch, but fails CI on existing branches once the changes are merged with the following error:

```
2021-12-07T15:08:29.908Z [INFO]: [0mSchemaValidationError: Your GraphQL Schema is using "@hasOne" directive from the newer version of the GraphQL Transformer. Visit https://docs.amplify.aws/cli/migration/transformer-migration/ to learn how to migrate your GraphQL schema.[0m
                                 [0m    at GraphQLTransform.transform (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/GraphQLTransform.ts:247:13)[0m
                                 [0m    at _buildProject (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/util/amplifyUtils.ts:92:35)[0m
                                 [0m    at processTicksAndRejections (internal/process/task_queues.js:97:5)[0m
                                 [0m    at ensureMissingStackMappings (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/util/amplifyUtils.ts:166:23)[0m
                                 [0m    at buildProject (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/util/amplifyUtils.ts:51:3)[0m
                                 [0m    at transformGraphQLSchema (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/transform-graphql-schema.ts:534:29)[0m
                                 [0m    at Object.run (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/push-resources.ts:166:5)[0m
```

After the merge, our `amplify/cli.json` file looks like this:

```
{
  "features": {
    "graphqltransformer": {
      "addmissingownerfields": true,
      "improvepluralization": true,
      "validatetypenamereservedwords": true,
      "useexperimentalpipelinedtransformer": true,
      "enableiterativegsiupdates": true,
      "secondarykeyasgsi": true,
      "skipoverridemutationinputtypes": true,
      "transformerversion": 2,
      "suppressschemamigrationprompt": true
    },
    "frontend-ios": {
      "enablexcodeintegration": true
    },
    "auth": {
      "enablecaseinsensitivity": true,
      "useinclusiveterminology": true,
      "breakcirculardependency": true,
      "forcealiasattributes": false
    },
    "codegen": {
      "useappsyncmodelgenplugin": true,
      "usedocsgeneratorplugin": true,
      "usetypesgeneratorplugin": true,
      "cleangeneratedmodelsdirectory": true,
      "retaincasestyle": true,
      "addtimestampfields": true,
      "handlelistnullabilitytransparently": true,
      "emitauthprovider": true,
      "generateindexrules": true,
      "enabledartnullsafety": true
    },
    "appsync": {
      "generategraphqlpermissions": true
    },
    "latestregionsupport": {
      "pinpoint": 1,
      "translate": 1,
      "transcribe": 1,
      "rekognition": 1,
      "textract": 1,
      "comprehend": 1
    },
    "project": {
      "overrides": true
    }
  }
}
```

### Expected behavior

The app should deploy successfully using the migrated GraphQL schema.

### Reproduction steps

git co -b migration
amplify api migrate
amplify push
// this results in a SUCCESSFUL deployment in my sandbox environment, using its own App ID

git commit
git push
// this results in a SUCCESSFUL branch deployment using our shared App ID & autodetect branches feature

git co develop
git merge migration
git commit
// this results in a FAILED deploy to our existing `develop` branch deployment

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
enum Role {
  ADMINISTRATOR
  CONTRIBUTOR
  MEMBER
}

type CompanyUser @model @auth(rules: [{allow: private}]) {
  id: ID!
  company_id: ID
  company: Company @hasOne(fields: ["company_id"])
  user_id: ID
  position: String
  phone: String
  email: String
  address: Address
  roles: Role
}

type User @model @auth(rules: [{allow: private}]) {
  id: ID!
  companys: [ID]
}

enum AccountType {
  CHECKING
  SAVING
}

type ACHPaymentMethodInformation {
  routing: Int
  account_number: Int
  account_type: AccountType
}

enum ACHMethodEnum {
  ONLY
  PREFERRED
  ACCEPTED
}

type ACHPaymentMethod {
  preference: ACHMethodEnum
  information: ACHPaymentMethodInformation
}

type PaymentMethods {
  ach: ACHMethodEnum
  vcard: String
  check: String
}

type Address {
  address1: String
  address2: String
  city: String
  state: String
  country: String
  postal_code: String
}

enum PriorityStatus {
  APPROVED
  CANCELED
  CLOSED
  DECLINED
  RECEIVED
  SUSPENDED
  UNDERREVIEW
}

enum CompanyStatus {
  VALUE
}

type Company @model @searchable @auth(rules: [{allow: private}]) {
  id: ID!
  slug: String!
  legal_name: String
  status: CompanyStatus
  account_balance: String
  name: String!
  dba: String
  ein: String
  mcc: String
  corp_type: String
  industry: String
  company_email: String
  customer_facing_email: String
  company_phone: String
  website: String
  company_address: Address
  customer_facing_address: Address
  legal_address: Address
  admin_user_id: String
  accounts_payable_user_id: String
  accounts_receivable_user_id: String
  payment_methods: PaymentMethods
  payment_thresholds: String
  speedscore: Int
  priority_status: PriorityStatus
  priority_buyer_id: String
  deleted_at: AWSDateTime
  company_id: String!
  logo: String
}

type ModelCompanyConnection {
  items: [Company]
  nextToken: String
  total: Int
}

enum PaymentFileQueueStatusEnum {
  PROCESSED
  QUEUED
}

type PaymentFileQueue @model @auth(rules: [{allow: private}]) {
  id: ID!
  key: String!
  status: PaymentFileQueueStatusEnum!
  queued_at: AWSDateTime
  processed_at: AWSDateTime
  company_id: ID
  company: Company @hasOne(fields: ["company_id"])
}


```

</details>

### Log output

<details>

```
# Put your logs below this line
                                 # Starting phase: build
                                 # Executing command: node -v
2021-12-07T15:08:02.729Z [INFO]: v12.21.0
2021-12-07T15:08:14.077Z [INFO]: [0mAmplify AppID found: ddzxwz9kd3xor. Amplify App name is: speedchainr2[0m
2021-12-07T15:08:14.149Z [INFO]: [0mBackend environment develop found in Amplify Console app: speedchainr2[0m
2021-12-07T15:08:15.418Z [WARNING]: - Fetching updates to backend environment: develop from the cloud.
2021-12-07T15:08:16.284Z [WARNING]: - Building resource auth/speedchainr2726bb6be726bb6be
2021-12-07T15:08:16.343Z [WARNING]: - Building resource api/speedchainr2
2021-12-07T15:08:16.459Z [INFO]: ⚠️ Your instance type for OpenSearch is t2.small.elasticsearch, you may experience performance issues or data loss. Consider reconfiguring with the instructions here https://docs.amplify.aws/cli-legacy/graphql-transformer/searchable/
2021-12-07T15:08:16.758Z [WARNING]: - Building resource storage/speedchainstorage
2021-12-07T15:08:16.853Z [WARNING]: ✔ Successfully pulled backend environment develop from the cloud.
2021-12-07T15:08:16.881Z [INFO]: 
2021-12-07T15:08:21.919Z [INFO]: [33mNote: It is recommended to run this command from the root of your app directory[39m
2021-12-07T15:08:27.859Z [WARNING]: - Initializing your environment: develop
2021-12-07T15:08:29.076Z [WARNING]: - Building resource auth/speedchainr2726bb6be726bb6be
2021-12-07T15:08:29.133Z [WARNING]: - Building resource api/speedchainr2
2021-12-07T15:08:29.245Z [INFO]: ⚠️ Your instance type for OpenSearch is t2.small.elasticsearch, you may experience performance issues or data loss. Consider reconfiguring with the instructions here https://docs.amplify.aws/cli-legacy/graphql-transformer/searchable/
2021-12-07T15:08:29.496Z [WARNING]: - Building resource storage/speedchainstorage
2021-12-07T15:08:29.556Z [WARNING]: ✔ Initialized provider successfully.
2021-12-07T15:08:29.639Z [INFO]: ⚠️ Your instance type for OpenSearch is t2.small.elasticsearch, you may experience performance issues or data loss. Consider reconfiguring with the instructions here https://docs.amplify.aws/cli-legacy/graphql-transformer/searchable/
2021-12-07T15:08:29.891Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
2021-12-07T15:08:29.892Z [WARNING]: ✖ There was an error initializing your environment.
2021-12-07T15:08:29.908Z [INFO]: [0mSchemaValidationError: Your GraphQL Schema is using "@hasOne" directive from the newer version of the GraphQL Transformer. Visit https://docs.amplify.aws/cli/migration/transformer-migration/ to learn how to migrate your GraphQL schema.[0m
                                 [0m    at GraphQLTransform.transform (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/GraphQLTransform.ts:247:13)[0m
                                 [0m    at _buildProject (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/util/amplifyUtils.ts:92:35)[0m
                                 [0m    at processTicksAndRejections (internal/process/task_queues.js:97:5)[0m
                                 [0m    at ensureMissingStackMappings (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/util/amplifyUtils.ts:166:23)[0m
                                 [0m    at buildProject (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/util/amplifyUtils.ts:51:3)[0m
                                 [0m    at transformGraphQLSchema (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/transform-graphql-schema.ts:534:29)[0m
                                 [0m    at Object.run (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/push-resources.ts:166:5)[0m
2021-12-07T15:08:29.932Z [ERROR]: !!! Build failed
2021-12-07T15:08:29.933Z [ERROR]: !!! Non-Zero Exit Code detected
2021-12-07T15:08:29.933Z [INFO]: # Starting environment caching...
2021-12-07T15:08:29.933Z [INFO]: # Uploading environment cache artifact...
2021-12-07T15:08:30.000Z [INFO]: # Environment caching completed
Terminating logging...

```

</details>

**Comment by akshbhu** [comment]
Hi @jayKayEss 

Can you check the cli.json in #current-cloud-backend folder if the transformerversion FF is set to 2 ?

**Comment by jayKayEss** [comment]
Hi @akshbhu 

Our `amplify/#current-cloud-backend` folder is gitignore'd according to rules that the Amplify CLI inserted... should that be changed?

```
#amplify-do-not-edit-begin
amplify/\#current-cloud-backend
amplify/.config/local-*
amplify/logs
amplify/mock-data
amplify/backend/amplify-meta.json
amplify/backend/awscloudformation
amplify/backend/.temp
build/
dist/
node_modules/
aws-exports.js
awsconfiguration.json
amplifyconfiguration.json
amplifyconfiguration.dart
amplify-build-config.json
amplify-gradle-config.json
amplifytools.xcconfig
.secret-*
.env
**.sample
#amplify-do-not-edit-end
```

**Comment by akshbhu** [comment]
No , I just want to know the transformerVersion FF value present in ```cli.json``` as posted above.

So the problem I see here is when merging the migration branch with develop branch and push , some how deploy is going into V1 transformer flow which doesn't recognize new V2 directives. This is only possible if the cli.json has transfomer version present as 2 in cli.json file.

**Comment by jayKayEss** [comment]
So, forgive me if I misunderstand here... looking at the deployment bucket for that build, I see `#current-cloud-backend.zip`, which when I download it has this:

```
{
  "features": {
    "graphqltransformer": {
      "addmissingownerfields": true,
      "improvepluralization": true,
      "validatetypenamereservedwords": true,
      "useexperimentalpipelinedtransformer": false,
      "enableiterativegsiupdates": true,
      "secondarykeyasgsi": true,
      "skipoverridemutationinputtypes": true
    },
    "frontend-ios": {
      "enablexcodeintegration": true
    },
    "auth": {
      "enablecaseinsensitivity": true,
      "useinclusiveterminology": true,
      "breakcirculardependency": true,
      "forcealiasattributes": false
    },
    "codegen": {
      "useappsyncmodelgenplugin": true,
      "usedocsgeneratorplugin": true,
      "usetypesgeneratorplugin": true,
      "cleangeneratedmodelsdirectory": true,
      "retaincasestyle": true,
      "addtimestampfields": true,
      "handlelistnullabilitytransparently": true,
      "emitauthprovider": true,
      "generateindexrules": true,
      "enabledartnullsafety": true
    },
    "appsync": {
      "generategraphqlpermissions": true
    },
    "latestregionsupport": {
      "pinpoint": 1,
      "translate": 1,
      "transcribe": 1,
      "rekognition": 1,
      "textract": 1,
      "comprehend": 1
    },
    "project": {
      "overrides": true
    }
  }
}
```

Since we're not caching that folder, and there's no `#current-cloud-backend/` folder in git, I'm not sure how `amplifyPush --simple` is deriving those values, which don't match `amplify/cli.json` in git.

**Comment by jayKayEss** [comment]
Hi @akshbhu I was able to resolve this issue by manually pushing to our staging environment, although the behavior of the migration tool was unexpected to me:

EXPECTATION:
```
amplify api migrate
amplify push # to my sandbox environment
git commit
# CI will apply the migration automatically in the next staging deploy
```

ACTUAL:
```
amplify pull --appId OurProductionAppID --envName staging
amplify api migrate
amplify push # manually to staging
git commit
```

This was unexpected because the staging deploy will fail unless an `amplify push` is executed manually by a developer. My expectation is that automated deploys shouldn't require human intervention.

Is this the intended use case for the migration tool? The [migration guide](https://docs.amplify.aws/cli/migration/transformer-migration/) mentions that the migration tool is available but doesn't go into detail on how to use it.

**Comment by akshbhu** [comment]
AFAIK , transformer V2 is an opt-in feature, so for each env , you specifically have to do an ```amplify migrate api```  for each env to migrate to use new transformer functionality.

CI wont apply migration automatically , since its an opt-in feature for existing projects.

**Comment by AustinAmoruso** [comment]
This is broken for me as well

**Comment by josefaidt** [comment]
Hey @jayKayEss :wave: I have been unable to reproduce this issue starting from Amplify CLI 5.4.0 to create a GraphQL API on two environments, however upon re-reading the original post I noticed something that stood out to me: your `cli.json` file was not updated in the `#current-cloud-backend`. I believe this is due to a difference between the `amplifyPush` helper script and running `amplify push` locally; as you pointed out running manually `amplify push` mitigates the issue.

Continuing to investigate 🙂

**Comment by josefaidt** [comment]
cc @edwardfoyle @swaminator for feature-flags re-work
