### ISSUE TITLE
🔴  Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by hackrx** [aws-amplify/amplify-cli#9248]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

7.6.2

### What operating system are you using?

Mac

### Amplify Categories

Not applicable

### Amplify Commands

pull

### Describe the bug

I have two envs deployed in the amplify. 
1. staging
2. rtestapis
I was working in the dev env, and then I checkout to `rtestapis` env, after that I pulled changes from amplify and then made some changes in lambda functions.
Then I executed `amplify push` it resulted in this error: 
```
amplify push
? Select the authentication method you want t
o use: AWS profile
Failed to get profile: Profile configuration is missing for: undefined
``
Then I again pulled from backend, which  resulted in this error: 
```
Local changes detected.
Pulling changes from the cloud will override your local changes.
? Are you sure you would like to continue? Yes
? Select the authentication method you want to use: AWS profile
**Failed to get profile: Profile configuration is missing for: undefined**
⠼ Fetching updates to backend environment: rtestapis from the cloud.%      
```

Then I tried `amplify configure`  which resulted in success. 
But again same  error while pull or push.
Then I executed logout command, `amplify logout --appID xxxxxx` then 
`amplify pull --appID xxxx -env xxxx` now it is giving error: 
```
amplify pull --appId d2nxxxxxj6ne --envName rtestapis
Failed to pull the backend.
invalid json response body at https://prod.us-east-1.appstate.amplifyapp.com/AppState/?appId=d2nxxxxxxpj6ne reason: Unexpected token < in JSON at position 0
FetchError: invalid json response body at https://prod.us-east-1.appstate.amplifyapp.com/AppState/?appId=d2nqxxxxxxne reason: Unexpected token < in JSON at position 0
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at isAmplifyAdminApp (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/utils/admin-helpers.ts:24:18)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/attach-backend.js:32:17)
    at Object.attachBackend (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/index.ts:62:3)
    at queryProvider (/usr/local/lib/node_modules/@aws-amplify/cli/src/attach-backend-steps/a10-queryProvider.ts:12:3)
    at attachBackend (/usr/local/lib/node_modules/@aws-amplify/cli/src/attach-backend.ts:20:5)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/src/commands/pull.ts:59:5)
    at Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/index.ts:373:5)
    at executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:204:3)
    at executeCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:30:5)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/src/index.ts:205:5)
```

### Expected behavior

amplify checkout env, should not create this type of issue. 
When the token is invalid, cli must reauthenticate the user if user is logged out and pulling the project, in this case, it should open admin UI for the token, but it is throwing this error.

### Reproduction steps

I already mentioned in the bug.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by jk171505** [comment]
I'm having exactly the same problem now...

**Comment by hackrx** [comment]
1. [old similar issue](https://github.com/aws-amplify/amplify-cli/issues/1355)
2. [Profile configuration is missing for: undefined](https://github.com/aws-amplify/amplify-cli/issues/8438)

**Comment by jonesnxt** [comment]
This looks like it is related to `us-east-1` having outages as the endpoint `https://prod.us-east-1.appstate.amplifyapp.com/AppState/?appId=[app_id]` is giving me a 504 error about half the time I request it.

**Comment by hackrx** [comment]
But my amplify project is deployed in the `us-east-2` region.

**Comment by jk171505** [comment]
> This looks like it is related to `us-east-1` having outages as the endpoint `https://prod.us-east-1.appstate.amplifyapp.com/AppState/?appId=[app_id]` is giving me a 504 error about half the time I request it.

I noticed that in logs, but I wonder what `us-east-1` has to do with my app, since it's deployed in `eu-central-1`...

**Comment by ammarkarachi** [comment]
Thanks @jonesnxt, I will mark this as an enhancement to improve on the error handling.

**Comment by jonesnxt** [comment]
> Thanks @jonesnxt, I will mark this as an enhancement to improve on the error handling.

👍  Some retry logic would be great here as it looks like it's only failing about half the time.

**Comment by jk171505** [comment]
@ammarkarachi isn't this a problem that outage in completely different region affects the deployment in another one?

**Comment by ammarkarachi** [comment]
@jk171505 The underlying service for admin ui is on `us-east-1`

**Comment by jk171505** [comment]
@ammarkarachi to me it only shows how serious the problem is. For me it failed 4-5 times in a row.
It looks like the deployment of probably all apps in probably all regions fails because of the outage in `us-east-1`.

**Comment by josefaidt** [comment]
Hey @hackrx and folks in the thread, this issue appears to have been caused by the [outage on December 7, 2021](https://aws.amazon.com/message/12721/). Closing due to outage
