### ISSUE TITLE
Amplify import auth: Cannot parse arn: 'undefined'.

### ISSUE THREAD

**Issue by david-wb** [aws-amplify/amplify-cli#9286]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify CLI Version

7.6.2

### What operating system are you using?

Ubuntu 18.04

### Amplify Categories

auth, hosting

### Amplify Commands

Not applicable

### Describe the bug

I'm trying to use `amplify import auth` to import a pre-existing user-pool and identity-pool but I get the following error.

```bash
$ amplify import auth
Using service: Cognito, provided by: awscloudformation
✔ What type of auth resource do you want to import? · Cognito User Pool and Identity Pool
✔ Select the User Pool you want to import: · us-west-2_ZmfhLLaT3
✔ Only one Web app client found: 'users-client' was automatically selected.
✔ Only one Native app client found: 'users-client' was automatically selected.
⚠️ It is recommended to use different app client for web and native application.
✔ Only one Identity Pool resource found: 'users-identity-pool' (us-west-2:723b23dd-3d04-43bb-86ba-cf5c71eac149) was automatically selected.
Cannot parse arn: 'undefined'.
Error: Cannot parse arn: 'undefined'.
    at IdentityPoolService.getResourceNameFromArn (/home/david/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/aws-utils/IdentityPoolService.ts:108:13)
    at IdentityPoolService.getIdentityPoolRoles (/home/david/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/aws-utils/IdentityPoolService.ts:91:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at importServiceWalkthrough (/home/david/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/provider-utils/awscloudformation/import/index.ts:322:74)
    at Object.importResource (/home/david/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/provider-utils/awscloudformation/import/index.ts:45:42)
    at Object.executeAmplifyCommand (/home/david/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/index.js:421:3)
    at executePluginModuleCommand (/home/david/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:204:3)
    at executeCommand (/home/david/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:30:5)
    at Object.run (/home/david/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/src/index.ts:205:5)
```

### Expected behavior

Importing auth should work without errors.

### Reproduction steps

1. Create user-pool and identity pool.
2. Import them with `amplify import auth`.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by lazpavel** [comment]
Hi @david-wb, thank you for raising this issue, I was able to reproduce it and working on a fix

**Comment by lazpavel** [comment]
In the meantime can you go to console and find the identity pool your trying to import and make sure you have assigned values for `Unauthenticated role` and `Authenticated role` fields

**Comment by david-wb** [comment]
@lazpavel Thank you, I added auth and unauth roles to the identity pool and now the import works.
