### ISSUE TITLE
amplify env checkout dev: There was an error initializing your environment.

### ISSUE THREAD

**Issue by YikSanChan** [aws-amplify/amplify-cli#931]
** Which Category is your question related to? **
multienv

** What AWS Services are you utilizing? **
Amplify

** Provide additional details e.g. code snippets **
I am following Nader's tutorials on multienv step by step. Things went well before I tried to run `amplify env checkout dev`. It complains:
```
✖ There was an error initializing your environment.
2019-02-24T02:44:15.212Z - error: uncaughtException: Cannot read property 'blanktest' of undefined date=Sat Feb 23 2019 18:44:15 GMT-0800 (Pacific Standard Time), pid=50968, uid=501, gid=20, cwd=/Users/evan/source/blanktest, execPath=/usr/local/Cellar/node/11.7.0/bin/node, version=v11.7.0, argv=[/usr/local/Cellar/node/11.7.0/bin/node, /usr/local/bin/amplify, env, checkout, dev], rss=121004032, heapTotal=91738112, heapUsed=64332920, external=749631, loadavg=[2.87158203125, 2.7958984375, 2.763671875], uptime=381939, trace=[column=43, file=/Users/evan/.config/yarn/global/node_modules/amplify-provider-awscloudformation/lib/initialize-env.js, function=Object.keys.forEach, line=63, method=forEach, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=false, column=44, file=/Users/evan/.config/yarn/global/node_modules/amplify-provider-awscloudformation/lib/initialize-env.js, function=Object.keys.forEach, line=62, method=forEach, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=false, column=32, file=/Users/evan/.config/yarn/global/node_modules/amplify-provider-awscloudformation/lib/initialize-env.js, function=S3.then.then.then.then.then, line=61, method=then, native=false, column=5, file=internal/process/next_tick.js, function=processTicksAndRejections, line=81, method=null, native=false], stack=[TypeError: Cannot read property 'blanktest' of undefined,     at Object.keys.forEach (/Users/evan/.config/yarn/global/node_modules/amplify-provider-awscloudformation/lib/initialize-env.js:63:43),     at Array.forEach (<anonymous>),     at Object.keys.forEach (/Users/evan/.config/yarn/global/node_modules/amplify-provider-awscloudformation/lib/initialize-env.js:62:44),     at Array.forEach (<anonymous>),     at S3.then.then.then.then.then (/Users/evan/.config/yarn/global/node_modules/amplify-provider-awscloudformation/lib/initialize-env.js:61:32),     at processTicksAndRejections (internal/process/next_tick.js:81:5)]
```
But I am still able checkout to env `dev`:
```
➜  blanktest amplify env list

| Environments |
| ------------ |
| *dev         |
| apifeature   |
```
What is the problem under that error?

**Comment by kaustavghosh06** [comment]
@YikSanChan Provided a fix for it in #934 
Will update this thread after a release

**Comment by kaustavghosh06** [comment]
@YikSanChan We published a new version of the CLI. Please let me know if you're still facing the issue.

**Comment by YikSanChan** [comment]
I just tried, the error no longer appeared. Thanks @kaustavghosh06
