### ISSUE TITLE
'amplify update auth' is broken for new projects for new create-react-app@5.0.0 ?

### ISSUE THREAD

**Issue by peter-greekbase** [aws-amplify/amplify-cli#9359]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v14.17.1

### Amplify CLI Version

7.6.4

### What operating system are you using?

Ubuntu 20.04

### Amplify Categories

auth

### Amplify Commands

update

### Describe the bug

I've recently had two issues, one has something to do with the date and time, when I'm manually configuring cognito the amplify api settings, the second which is occurring now has to do with the amplify update auth:

I've followed the [instruction](https://docs.amplify.aws/start/getting-started/installation/q/integration/react/#option-1-watch-the-video-guide) verbatim, however I may be worried I've deleted a role or policy on my account by accident that may allow for using parts of the amplify cli. I'm not sure.

When I get to the stage where I amplify add api, I can make the generic taskapp without issue, it will generate the tables, and I can run mutations and queries. However when I try to run 'amplify update auth' and utilize cognito user pools for the next part, where auth is included, I get the following:  

```
amplify update api? Select from one of the below mentioned services: GraphQL
🛑 Cannot read property 'serviceType' of undefined
TypeError: Cannot read property 'serviceType' of undefined
    at getResourcesToBeCreated (/home/papi/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/resource-status-data.ts:220:65)
    at AmplifyToolkit.getResourceStatus [as _getResourceStatus] (/home/papi/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/resource-status-data.ts:117:35)
    at updateWalkthrough (/home/papi/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.ts:439:50)
    at updateNonContainerResource (/home/papi/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-api/src/provider-utils/awscloudformation/index.ts:260:63)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Object.executeAmplifyCommand (/home/papi/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-api/src/index.ts:223:5)
    at executePluginModuleCommand (/home/papi/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:204:3)
    at executeCommand (/home/papi/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:30:5)
    at Object.run (/home/papi/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/src/index.ts:205:5)
```

a similar result follows if I try amplify update auth

### Expected behavior

Before, I had no problems, and I was able to go through the workflow, and make my user groups, and add auth to the application.

Right now there's something very frustrating and unexplained happening. I'm not sure if I've somehow deleted a key permission or role. Something is wrong.

### Reproduction steps

[verbatim](https://docs.amplify.aws/start/getting-started/installation/q/integration/react/#option-1-watch-the-video-guide)

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line
$amplify update api

Select from one of the below mentioned services: GraphQL
🛑 Cannot read property 'serviceType' of undefined
TypeError: Cannot read property 'serviceType' of undefined
    at getResourcesToBeCreated (/home/papi/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/resource-status-data.ts:220:65)
    at AmplifyToolkit.getResourceStatus [as _getResourceStatus] (/home/papi/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/resource-status-data.ts:117:35)
    at updateWalkthrough (/home/papi/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-api/src/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.ts:439:50)
    at updateNonContainerResource (/home/papi/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-api/src/provider-utils/awscloudformation/index.ts:260:63)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Object.executeAmplifyCommand (/home/papi/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-api/src/index.ts:223:5)
    at executePluginModuleCommand (/home/papi/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:204:3)
    at executeCommand (/home/papi/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:30:5)
    at Object.run (/home/papi/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/src/index.ts:205:5)

$amplify update auth
Please note that certain attributes may not be overwritten if you choose to use defaults settings.

You have configured resources that might depend on this Cognito resource.  Updating this Cognito resource could have unintended side effects.

Cannot read property 'serviceType' of undefined
TypeError: Cannot read property 'serviceType' of undefined
    at getResourcesToBeCreated (/home/papi/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/resource-status-data.ts:220:65)
    at AmplifyToolkit.getResourceStatus [as _getResourceStatus] (/home/papi/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/resource-status-data.ts:117:35)
    at getAuthResourceName (/home/papi/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/utils/getAuthResourceName.ts:4:50)
    at Object.run (/home/papi/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/commands/auth/update.ts:58:49)
    at Object.executeAmplifyCommand (/home/papi/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/index.js:421:23)
    at /home/papi/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:222:45
    at executePluginModuleCommand (/home/papi/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:204:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at executeCommand (/home/papi/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:30:5)
    at Object.run (/home/papi/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/src/index.ts:205:5)


```

</details>

**Comment by akshbhu** [comment]
Hi @peter-greekbase 

Can you paste ```amplify-meta.json``` file here , will help in debugging the issue?
Make sure to redact any secret info present in the file

**Comment by cjihrig** [comment]
@peter-greekbase if you're still having problems, please open a new issue or provide the requested information here and we can reopen.
