### ISSUE TITLE
How to use snippet "secrets from SSM"?

### ISSUE THREAD

**Issue by SteeveGL** [aws-amplify/amplify-cli#9405]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system

7.6.5

**What AWS Services are you utilizing?**

Lambda

**Provide additional details e.g. code snippets**

I added a secret to my javascript function lambda. The Amplify CLI added a snippet to my app.js but I cannot figure out how to implement this.

*The snippet:*
```
/*
Use the following code to retrieve configured secrets from SSM:

const aws = require('aws-sdk');

const { Parameters } = await (new aws.SSM())
  .getParameters({
    Names: ["SECRET_ID"].map(secretName => process.env[secretName]),
    WithDecryption: true,
  })
  .promise();

Parameters will be of the form { Name: 'secretName', Value: 'secretValue', ... }[]
*/
```

*I did:*
```
const aws = require('aws-sdk');

const { Parameters } = await (new aws.SSM())
  .getParameters({
    Names: ["SECRET_ID"].map(secretName => process.env[secretName]),
    WithDecryption: true,
  })
  .promise();

Parameters().then((parameters) => {
  console.log(parameters)
})
```

return error:
```
{
    "errorType": "ReferenceError",
    "errorMessage": "await is not defined",
    "stack": [
        "ReferenceError: await is not defined",
        "    at Object.<anonymous> (/var/task/app.js:3:24)",
        "    at Module._compile (internal/modules/cjs/loader.js:1085:14)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)",
        "    at Module.load (internal/modules/cjs/loader.js:950:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:790:12)",
        "    at Module.require (internal/modules/cjs/loader.js:974:19)",
        "    at require (internal/modules/cjs/helpers.js:93:18)",
        "    at Object.<anonymous> (/var/task/index.js:2:13)",
        "    at Module._compile (internal/modules/cjs/loader.js:1085:14)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)"
    ]
}
```

**Comment by josefaidt** [comment]
Hey @SteeveGL :wave: can you try moving the secrets snippet inside your handler function?

```js
exports.handler = async event => {
  const { Parameters } = await (new aws.SSM())
    .getParameters({
      Names: ["SECRET_ID"].map(secretName => process.env[secretName]),
      WithDecryption: true,
    })
    .promise();

  // ...
}
```

By uncommenting the provided example it will try to use [top-level await](https://github.com/tc39/proposal-top-level-await), which unfortunately is not supported in CommonJS and is the cause of the error you're experiencing.

**Comment by SteeveGL** [comment]
Thanks @josefaidt for your reply. I'm using `Serverless ExpressJS function (Integration with API Gateway)`

I tried to add `async` to `exports.handler` without success:

**index.js**
```
const awsServerlessExpress = require('aws-serverless-express');
const app = require('./app');

const server = awsServerlessExpress.createServer(app);

exports.handler = async (event, context) => {
  console.log(`EVENT: ${JSON.stringify(event)}`);
  return awsServerlessExpress.proxy(server, event, context, 'PROMISE').promise;
};

```

**app.js**
```
var express = require('express')
var bodyParser = require('body-parser')
var awsServerlessExpressMiddleware = require('aws-serverless-express/middleware')

// declare a new express app
var app = express()
app.use(bodyParser.json())
app.use(awsServerlessExpressMiddleware.eventContext())

// Enable CORS for all methods
app.use(function(req, res, next) {
  res.header("Access-Control-Allow-Origin", "*")
  res.header("Access-Control-Allow-Headers", "*")
  next()
});


/**********************
 * Example get method *
 **********************/

app.get('/item', function(req, res) {
  // Add your code here
  res.json({success: 'get call succeed!', url: req.url});
});

app.get('/item/*', function(req, res) {
  // Add your code here
  res.json({success: 'get call succeed!', url: req.url});
});

...
```

**Comment by josefaidt** [comment]
Hey @SteeveGL we'll also want to add the SSM snippet in the handler code in `index.js`:

```diff
  // index.js
+ const aws = require("aws-sdk");
  const awsServerlessExpress = require("aws-serverless-express");
  const app = require("./app");

  const server = awsServerlessExpress.createServer(app);

- exports.handler = (event, context) => {
+ exports.handler = async (event, context) => {
    console.log(`EVENT: ${JSON.stringify(event)}`);
+   const { Parameters } = await new aws.SSM()
+     .getParameters({
+       Names: ["my_secret"].map((secretName) => process.env[secretName]),
+       WithDecryption: true,
+     })
+     .promise();
+   console.log({ Parameters });
    return awsServerlessExpress.proxy(server, event, context, "PROMISE").promise;
  };
```

Then after we push the latest changes and call the API route we should see the parameters logged to the Lambda's CloudWatch logs

![image](https://user-images.githubusercontent.com/5033303/148264096-4cc93f3e-d591-4cc5-a54c-38101fa8fcf0.png)

**Comment by SteeveGL** [comment]
@josefaidt you clearly make me moving forward. thanks.

The `Parameters` is require inside the `app.js`. I succeed but I'm not sure if it's the best way.

Here is what I get done:
```diff
// index.j
const app = require('./app');
const aws = require("aws-sdk");
const awsServerlessExpress = require('aws-serverless-express');

const server = awsServerlessExpress.createServer(app);

exports.handler = async (event, context) => {
  console.log(`EVENT: ${JSON.stringify(event)}`);
  const { Parameters } = await new aws.SSM()
    .getParameters({
      Names: ["SECRET_ID"].map((secretName) => process.env[secretName]),
      WithDecryption: true,
    })
    .promise();
+  app.locals.parameters = Parameters;
  return awsServerlessExpress.proxy(server, event, context, 'PROMISE').promise;
};
```

```diff
// app.js
var express = require('express')
var bodyParser = require('body-parser')
var awsServerlessExpressMiddleware = require('aws-serverless-express/middleware')

// declare a new express app
var app = express()
app.use(bodyParser.json())
app.use(awsServerlessExpressMiddleware.eventContext())

// Enable CORS for all methods
app.use(function(req, res, next) {
  res.header("Access-Control-Allow-Origin", "*")
  res.header("Access-Control-Allow-Headers", "*")
  next()
});


/**********************
 * Example get method *
 **********************/

app.get('/item', function(req, res) {
+  console.log(app.locals.parameters)
  res.json({success: 'get call succeed!', url: req.url});
});

...
```

**Comment by josefaidt** [comment]
Ah glad to hear you are back up and running @SteeveGL ! What you have looks like a great solution to pass those parameters through to the Express app! Another approach I've seen taken is to overwrite the `process.env` values with the fetched values from SSM.
