### ISSUE TITLE
Unable to launch amplify command with npm scripts

### ISSUE THREAD

**Issue by clementAC** [aws-amplify/amplify-cli#945]
**Describe the bug**
When I try to run amplify through npm scripts i have errors whereas launching it in the command line cause me no errors

**To Reproduce**
1. Add amplify cli to your dev dependencie project
2. Add some command in a npm script (eg. publishThings)
3. npm run publishThings
4. feel the despair

**Expected behavior**
Be able to run amplify cli through npm scripts

**Error**
```bash
home/user/Documents/project/node_modules/gluegun/build/index.js:13
    throw up;
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received type undefined
    at Module.require (internal/modules/cjs/loader.js:631:11)
    at require (internal/modules/cjs/helpers.js:22:18)
    at context.exeInfo.projectConfig.providers.forEach (/home/user/Documents/project/node_modules/@aws-amplify/cli/src/commands/env/checkout.js:39:30)
    at Array.forEach (<anonymous>)
    at Command.run (//home/user/Documents/project/node_modules/@aws-amplify/cli/src/commands/env/checkout.js:38:45)
    at Runtime.<anonymous> (/home/user/Documents/project/node_modules/gluegun/build/runtime/run.js:90:58)
    at step (/home/user/Documents/project/node_modules/gluegun/build/runtime/run.js:32:23)
    at Object.next (//home/user/Documents/project/node_modules/gluegun/build/runtime/run.js:13:53)
    at/home/user/Documents/project/node_modules/gluegun/build/runtime/run.js:7:71
    at new Promise (<anonymous>)
```

**Desktop (please complete the following information):**
 - OS: Linux
 - Amlify: 1.1.6

**Comment by lennybr** [comment]
@clementAC Amplify CLI should run when launched thru an NPM script -- I use them daily without any problems. Can you post your NPM script for reference. From your error message re `The "id" argument must be of type string` I think it might be something else. Some possible suggestions:

- Have you tried a clean install of the latest Amplify CLI `npm install -g @aws-amplify/cli@latest`
- Initiating a new amplify project `amplify init`
- In your package.json file, you don't have to do anything fancy except reference the Amplify CLI command, an example ```"scripts": { "gql-compile": "amplify api gql-compile" }```

**Comment by yuth** [comment]
@clementAC what command are you trying to run from npm script. Could you share the scripts section from your package.json

**Comment by clementAC** [comment]
Ok my bad. I had amplify cli into my project dependency and npm script was using this one. 
After removing it, the global install was taken and everything was fine.  Thanks for your time @lennybr @yuth
