### ISSUE TITLE
unable to initialize project with auth from git, missing `auth/.../build/parameters.json`

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/amplify-cli#9508]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

pnpm

### If applicable, what version of Node.js are you using?

16.13.1

### Amplify CLI Version

7.6.8

### What operating system are you using?

mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

auth

### Amplify Commands

init

### Describe the bug

Unable to initialize new environment from an Amplify project after freshly cloning from git due to missing `parameters.json` in the auth resource's `build/` directory. As a workaround, we can run `amplify build` to generate the missing file and allow us to initialize an environment.

Note: we are also unable to use the `--app` parameter of `init` to initialize a project from git:
	  ```
	  amplify init --app git@github.com:josefaidt/missingauth.git
	  ```

```
✔ Successfully created initial AWS cloud resources for deployments.
✔ Initialized provider successfully.
✖ There was an error initializing your environment.
Error: File at path: '/Users/josef/Documents/projects/aws-amplify/reproductions/missingauth2/amplify/backend/auth/missingauthbf3f264f/build/parameters.json' does not exist
at Function.JSONUtilities.readJson (/Users/josef/.fnm/node-versions/v16.13.1/installation/pnpm-global/5/node_modules/.pnpm/amplify-cli-core@2.4.7/node_modules/amplify-cli-core/src/jsonUtilities.ts:25:15)
    at StateManager.getData (/Users/josef/.fnm/node-versions/v16.13.1/installation/pnpm-global/5/node_modules/.pnpm/amplify-cli-core@2.4.7/node_modules/amplify-cli-core/src/state-manager/stateManager.ts:399:32)
    at StateManager.getResourceParametersJson (/Users/josef/.fnm/node-versions/v16.13.1/installation/pnpm-global/5/node_modules/.pnpm/amplify-cli-core@2.4.7/node_modules/amplify-cli-core/src/state-manager/stateManager.ts:147:17)
    at ensureAmplifyMetaFrontendConfig (/Users/josef/.fnm/node-versions/v16.13.1/installation/pnpm-global/5/node_modules/.pnpm/@aws-amplify+cli@7.6.8/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/on-category-outputs-change.ts:84:55)
    at AmplifyToolkit.onCategoryOutputsChange [as _onCategoryOutputsChange] (/Users/josef/.fnm/node-versions/v16.13.1/installation/pnpm-global/5/node_modules/.pnpm/@aws-amplify+cli@7.6.8/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/on-category-outputs-change.ts:18:5)
    at initializeEnv (/Users/josef/.fnm/node-versions/v16.13.1/installation/pnpm-global/5/node_modules/.pnpm/@aws-amplify+cli@7.6.8/node_modules/@aws-amplify/cli/src/initialize-env.ts:103:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at onSuccess (/Users/josef/.fnm/node-versions/v16.13.1/installation/pnpm-global/5/node_modules/.pnpm/@aws-amplify+cli@7.6.8/node_modules/@aws-amplify/cli/src/init-steps/s9-onSuccess.ts:68:3)
    at Object.run (/Users/josef/.fnm/node-versions/v16.13.1/installation/pnpm-global/5/node_modules/.pnpm/@aws-amplify+cli@7.6.8/node_modules/@aws-amplify/cli/src/commands/init.ts:30:7)
    at Object.executeAmplifyCommand (/Users/josef/.fnm/node-versions/v16.13.1/installation/pnpm-global/5/node_modules/.pnpm/@aws-amplify+cli@7.6.8/node_modules/@aws-amplify/cli/src/index.ts:373:5)
    at executePluginModuleCommand (/Users/josef/.fnm/node-versions/v16.13.1/installation/pnpm-global/5/node_modules/.pnpm/@aws-amplify+cli@7.6.8/node_modules/@aws-amplify/cli/src/execution-manager.ts:178:3)
    at executeCommand (/Users/josef/.fnm/node-versions/v16.13.1/installation/pnpm-global/5/node_modules/.pnpm/@aws-amplify+cli@7.6.8/node_modules/@aws-amplify/cli/src/execution-manager.ts:30:5)
    at Object.run (/Users/josef/.fnm/node-versions/v16.13.1/installation/pnpm-global/5/node_modules/.pnpm/@aws-amplify+cli@7.6.8/node_modules/@aws-amplify/cli/src/index.ts:205:5)
```

### Expected behavior

New or existing environment is initialized

### Reproduction steps

1. `amplify init -y`
2. `amplify add auth` > choose defaults with username
3. `amplify push -y`
4. add to git (sample: https://github.com/josefaidt/missingauth.git)
5. cd to an empty sibling directory, `mkdir ../missingauthtmp; cd ../missingauthtmp`
6. clone from git `git clone git@github.com:josefaidt/missingauth.git`
7. attempt to initialize the project with `amplify init` > create new environment
8. observe error

### Workaround

1. run `amplify build`
2. observe resource build directory is created and populated
3. initialize with `amplify init`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by stevenlafl** [comment]
+1 Having the same problem. Same service, auth.

**Comment by adi518** [comment]
Getting the exact same bug. So unacceptable. Our preview builds don't work because of this. The workaround didn't work either, nor do I see how it should help. I already pulled the environment and pushed whatever updates it had to the branch I'm building an environment from.

**Comment by Leandros** [comment]
Same issue here. Our entire auth stack is gone.

**Comment by swaminator** [comment]
@Leandros @adi518 can you please provide repro steps?

**Comment by adi518** [comment]
Build a preview environment with the latest major version of the cli and it should fail when using a social auth provider (e.g., Google). I finally managed to work around it today by tapping into the Amplify config before it starts creating the environment and removing any social providers, so it skips the problem altogether. I should say this pipeline used to work fine with a much older version of the cli. However, since the sabotage in `colors.js`, the cli had to be inevitably upgraded to the latest (the sabotage was purposely released as a patch), which lead to these new regressions when deploying a preview environment.

**Comment by phaedonmit** [comment]
Is there a recommended fix for this?

**Comment by danshev** [comment]
Same -- does anyone from AWS ever respond?

**Comment by may215** [comment]
I have the same issue here? Any updates??

**Comment by Straubulous** [comment]
This is fixed in 8.0.1 @may215

**Comment by duranmla** [comment]
I'm having this issue on the CI, wonder how to deal with this if the build is something that runs on the CI. 🤔

**Comment by WebManifestation** [comment]
> 



> Just FYI @josefaidt if worth something, I had this problem with amplify CLI 10.3.0, I try to update the auth resource but it didn't work so I went to build settings and change to amplify 10.2.3 and it worked, perhaps this latest version is introducing an issue.
> 
> `Project Identifier: 7c991c00dbf89c25ef50f4c169fe031e`

Thanks, this worked. But would really like to know why this happened with this newer version of amplify cli.

**Comment by priyaprabhakar07** [comment]
I have the same error message with parameter.json while trying to initialise amplify environment, once I downgrade to 10.2.3 it is fixed

I am keen to know why this happened in the latest amplify cli version(10.3.0) and 
how to track whether this is fixed in the latest version?

**Comment by josefaidt** [comment]
Hey folks :wave: I was able to reproduce this issue using the following steps:

1. `amplify init -y`
2. `amplify add auth`
3. `amplify update auth` > add user pool groups
4. `amplify push -y`
5. `git clean -fXd` remove gitignored from local directory (to simulate fresh clone)
6. `amplify init --envName dev --yes` 

I've reopened this issue to track with 10.3.0

**Comment by josefaidt** [comment]
Revisiting this, I'm going to re-close in favor of tracking the new active bug as a regression https://github.com/aws-amplify/amplify-cli/issues/11211
