### ISSUE TITLE
Cannot add xx  due to cyclic dependancy

### ISSUE THREAD

**Issue by glidaa** [aws-amplify/amplify-cli#9516]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify CLI Version

7.6.9

### What operating system are you using?

mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no

### Amplify Categories

auth

### Amplify Commands

update

### Describe the bug

sudo amplify auth update
Please note that certain attributes may not be overwritten if you choose to use defaults settings.

You have configured resources that might depend on this Cognito resource.  Updating this Cognito resource could have unintended side effects.

Using service: Cognito, provided by: awscloudformation
 What do you want to do? Apply default configuration without Social Provider (Federation)
Successfully updated the Cognito trigger locally
Error: Cannot add fsCognito due to a cyclic dependency
    at checkForCyclicDependencies (/usr/local/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/update-amplify-meta.ts:289:11)
    at AmplifyToolkit.updateamplifyMetaAfterResourceUpdate [as _updateamplifyMetaAfterResourceUpdate] (/usr/local/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/update-amplify-meta.ts:164:5)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/provider-utils/awscloudformation/utils/amplify-meta-updaters.ts:70:21
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/provider-utils/awscloudformation/handlers/resource-handlers.ts:164:48
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/commands/auth/update.ts:74:36)
    at Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/index.js:421:3)
    at executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:178:3)
    at executeCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:30:5)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/src/index.ts:205:5)
🛑 There was an error updating the auth resource
✅ Successfully updated resource update locally

✅ Some next steps:

### Expected behavior

it to work

### Reproduction steps

go to my code github.com/glidaa/fs 
try to deploy or update like above

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by johnpc** [comment]
can you check your `amplify/cli.json` for the `breakCircleDepedency` flag? Is it enabled?

**Comment by josefaidt** [comment]
Hey @glidaa :wave: thanks for raising this! To add on to @johnpc 's comment above, can you try running `amplify update function` to update your Post Confirmation trigger and remove the access to `auth`? I was able to successfully reproduce the issue you're seeing after cloning your project but I was unable to get a new project into that state due to the CLI preventing the circular dependency. Although your [feature flag](https://docs.amplify.aws/cli/reference/feature-flags/#breakCircularDependency) is set to false, the CloudFormation template does appear to have the appropriate permissions and the access does not seem to be used in the function code.

After removing auth resource access from the function we are able to successfully update the auth resource. Let me know if this works for you!

**Comment by josefaidt** [comment]
Closing due to inactivity. @glidaa if you are still experiencing this issue please reply back to this thread and we can re-open to investigate further 🙂

**Comment by olliethedev** [comment]
I seem to have encountered the same `Cannot add xx due to cyclic dependancy` error, but when I try to add the `auth` Resource access permissions to my existing lambda.
