### ISSUE TITLE
OpenSearch mapping getting out of sync (drifting) with GraphQL schema, how to correct?

### ISSUE THREAD

**Issue by PeteDuncanson** [aws-amplify/amplify-cli#9536]
**Which Category is your question related to?**

API and @searchable I guess.

We've been adding to our schema as we've been developing and we've noticed that at some point the @searchable results are no longer updating or at least are out of date. We've think this is due to our schema changing for some of the models we have @searchable set on.

This has caused a few questions and issues.

* Will Amplify keep the mapping (the list of which fields/types it should store) for ES up to date when we make schema changes? I don't think it does. If not then how best to update the mappings?
* If we make changes to the mappings I assume we will have to re-import or clear and re-import or refresh the data in ES. How best to do that?

We've "had a go" at this in our dev environment. I used the devtools in Kiana (aka OpenSearch Dashboard, there is a link to this on your ES instance in the AWS ES Console) to delete our existing index and then recreated the mapping to match what we had in the schema.graphql file for that model. I used the other existing mappings as a guide and think I got it right...

Then we used the python script mentioned here (https://docs.amplify.aws/cli-legacy/graphql-transformer/searchable/#configure-environment-opensearch-instance-type) to back fill our index. This has worked in the past but now it doesn't seem to. It runs without any errors and says its updated loads of records but we don't see any records listed in the index at all, theres nothing to update! We also saw that the import script is set to "MODIFY" rather than "CREATE" as I would expect if importing data for the first time, we tried changing it and rerunning but same result, no new documents imported. In the terminal no errors are reported but in CloudFront we caught a few: 

Seems its getting confused trying to convert between floats and longs but I'm not sure why, its set as float in the mapping so where is the long coming from?

```
Can't serialize value (/searchAddresss/items[1]/_lastChangedAt) : Unable to serialize 1.6190332464E12 as a valid timestamp. Ensure that the value provided is an Integer that lies within the limits specified in this scalar's description.
```

We wondered if the _version field might be causing issues so tried to exclude it from our script and now we get this:

```
2022-01-14T13:27:11.754+00:00

Copy
[ERROR]	2022-01-14T13:27:11.754Z	3d869918-bc74-4267-ba5a-197f97327cfc	Traceback (most recent call last):
  File "/var/task/python_streaming_function.py", line 261, in lambda_handler
    return _lambda_handler(event, context)
  File "/var/task/python_streaming_function.py", line 255, in _lambda_handler
    post_to_es(es_payload)  # Post to ES with exponential backoff
  File "/var/task/python_streaming_function.py", line 102, in post_to_es
    payload, es_region, creds, es_endpoint, '/_bulk')
  File "/var/task/python_streaming_function.py", line 76, in post_data_to_es
    raise ES_Exception(res.status_code, res._content)
python_streaming_function.ES_Exception: ES_Exception: status_code=400, payload=b'
{
    "error": {
        "root_cause": [
            {
                "type": "illegal_argument_exception",
                "reason": "Action/metadata line [1] contains an unknown parameter [_version]"
            }
        ],
        "type": "illegal_argument_exception",
        "reason": "Action/metadata line [1] contains an unknown parameter [_version]"
    },
    "status": 400
}
```

So short version. What have we done wrong?
Are we on the right track for fixing it?
Is my assumption that the ES Mappings aren't automatically kept up to date with schema changes correct?
How best to put it right?

Due to DynamoDB's limited searching options we have to use ElasticSearch (or OpenSearch as it is now) but other than the initial "just and @searchable, push and magic!" recommendation I can't find much at all on how to do house keeping tasks like reindexing :(

As usual this is currently blocking us going live as our users can't search for customers and addresses.

Cheers

Pete

Name dropping @josefaidt again so he can pick this up after last night discussion, thanks in advance :)

**Amplify CLI Version** 

7.6.8

**What AWS Services are you utilizing?**

OpenSearch

**Provide additional details e.g. code snippets**

**Comment by PeteDuncanson** [comment]
If it helps here how I deleted the existing index:

```
DELETE /address
```

And this is the mapping I created manually to add in via the devtools:

```
PUT /address
{
  "mappings": {
      "properties": {
        "__typename": {"type":"text"},
        "_deleted": {"type":"boolean"},
        "_lastChangedAt": {"type":"long"},
        "id": {"type":"text"},
        "companyName": {"type":"text"},
        "addressLine1": {"type":"text"},
        "addressLine2": {"type":"text"},
        "addressLine3": {"type":"text"},
        "town": {"type":"text"},
        "county": {"type":"text"},
        "postcode": {"type":"text"},
        "phoneNumber": {"type":"text"},
        "bedrooms": {"type":"long"},
        "houseTypeID": {"type":"text"},
        "hasConservatory": {"type":"boolean"},
        "customerID": {"type":"text"},
        "addressStatus": {"type":"text"},
        "importantVisitSummary": {"type":"text"},
        "importantCAMSummary": {"type":"text"},
        "sectorID": {"type":"text"},
        "areaID": {"type":"text"},
        "hasGeocodingIssues": {"type":"boolean"},
        "buildNumber": {"type":"text"},
        "buildName": {"type":"text"},
        "premise": {"type":"text"},
        "postcodeOutward": {"type":"text"},
        "postcodeInward": {"type":"text"},
        "signUpDate": {"type":"date"},
        "safePlaceToStoreMoney": {"type":"text"},
        "legacyCleanerPlannerID": {"type":"text"},
        "signedUpPreSUDS": {"type":"boolean"},
        "updatedAt": {"type":"date"},
        "createdAt": {"type":"date"}
      
    }
  }
}
```

**Comment by PeteDuncanson** [comment]
I also have a nested type in there normally for location but that doesn't seem to be working either so while testing round I stripped it. My understanding is if ES gets sent a field it doesn't have a mapping for it will ignore it but I'm not 100% on that one, thats the hope anyway.

That did look like this:

```
...
"areaID": {"type":"text"},
"geoCords.lat": { "type":"float"},
"goeCords.lon": {"type":"float"},
"hasGeocodingIssues": {"type":"boolean"},
...
```

Again that was complaining about converting longs to floats or visa versa, sadly I cna't seem to easily get to the logs for that from this morning (been trying lots of things and generated a lot of log entries!).

**Comment by marcvberg** [comment]
Hi @PeteDuncanson,

To give some clarification on how `@searchable` works:
1. The mappings are not created by the CLI, the CLI creates a lambda function to take records from a DynamoDB stream attached to your searchable enabled table, and it publishes those records to OpenSearch which dynamically creates mappings based on input. Once a mapping is created, the mapping is immutable, changes to how a field is mapped require a new index
2. Because the records are streamed from DynamoDB to OpenSearch, only the values in the DynamoDB table are streamed. While the VTL resolvers in AppSync we generate understand the connections between models, the streaming lambda does not, so any complex objects within your model will not show up in OpenSearch
3. The "MODIFY" in the streaming script is a code for DynamoDB, not OpenSearch, it's meant to pretend to be a Dynamo record that has been modified and sent in a DynamoDB stream
4. I notice that you deleted the `address` index and created a new one, but when I look at your above error message it seems like the index is named `searchAddress`
5. You shouldn't need to create a mapping for the index or even create the index itself, the streaming lambda invoked by the streaming script you referenced above should take care of that
6. If you do something that changes the mapping, i.e. changing a field type so that the type will be incompatible in OpenSearch, you would need to delete the index and re-stream the data

I hope this helps answer some of the questions you have above, let us know what problems you still have afterward and we can go from there

**Comment by PeteDuncanson** [comment]
Hey @marcvberg 

Thank you so much, thats filled it a lot of blanks and corrected a lot of wrong information in my mental model, that really helps give me some clarity and hope. Excellent response :)

Some questions/points if I may:

1. "Once a mapping is created, the mapping is immutable, changes to how a field is mapped require a new index" - by this do you mean I need to the steps in your 6th point: "If you do something that changes the mapping, i.e. changing a field type so that the type will be incompatible in OpenSearch, you would need to delete the index and re-stream the data"?

2. searchAddress is the graphql result that comes back, under the hood I believe its storing these in the /address index (as there is no /searchAddress index listed in OpenSearch. So think I'm looking at the right one.
3. So I don't have a /address index in my ES instance at the minute. From what you are saying I should be able to run the python script and it should just slurp it all up and create a new one. So I tried it. Still no index is created called /address or anything like it. Whats going wrong there?
![image](https://user-images.githubusercontent.com/1674590/150412300-dcb69708-feaf-4400-bee3-7c9c28cfe445.png)

I'm running the script with this command:

```
python ddb_to_es.py --rn 'eu-west-1' --tn 'Address-petessecretid-localdev' --lf 'arn:aws:lambda:eu-west-1:123456789:function:DdbToEsFn-petessecretid-localdev' --esarn 'arn:aws:dynamodb:eu-west-1:123456789:table/Address-petessecretid-localdev' 
```

So thats the region, the table name and the arn of the lambda that was created for hoovering up the data for me as part of adding ES via amplify. It reports as working writing out 100 results at a time to the console but nothing appears. Its like I'm firing it somewhere else, or not looking at the right thing or its quietly erroring? But checking the logs it seems to be doing as it should, lots of entries where its firing a batch of data then processing it. Think I'm doing something wrong I'm just not sure what...what can I check or do to rule out something stupid?

Many thanks for your time, this suddenly feels doable, like its a setting I'm missing or something and it will just "work" once get it right.

Pete

**Comment by sachscode** [comment]
Hi @PeteDuncanson  
1. Which version of the GraphQL transformer are you using ?
2. Is the above (data-sync) script running Python 3 ? Did it complete successfully  and sync all records from DDB to OpenSearch ?

**Comment by PeteDuncanson** [comment]
@sachscode I'm using V1. don't know what version of python its written in I'm affraid, how best to check? Its the one from the docs site https://docs.amplify.aws/cli-legacy/graphql-transformer/searchable/#configure-environment-opensearch-instance-type which links to https://github.com/aws-amplify/amplify-cli/blob/master/packages/graphql-elasticsearch-transformer/scripts/ddb_to_es.py

**Comment by PeteDuncanson** [comment]
@marcvberg @sachscode any more pointers on where to look/what to check/what it might be that I can try next? I have go live in 2 weeks and I really need this cleared and off my todo list so I can sleep at night. One less thing to go wrong :)

Cheers

Pete

**Comment by PeteDuncanson** [comment]
Hey @marcvberg 

Using: Python 3.9.2

Script seems to report its completed happily. No errors output to the console or anything. I've double checked that the values I'm using for the command line script are all pointing to the right tables too.

In OS I'm seeing no `address` index being made though at all which makes me thing either its going somewhere else or something it swallowing an error somewhere. I've enabled error logging on OS but nothing shows up.

Running the cat-indices commands seems to render out the same as the indices tab in the OS Console and as shown in my previous screenshots. Notice no address index listed again.

![image](https://user-images.githubusercontent.com/1674590/151112778-96537ecb-58d6-49de-8d59-e10d01c2920e.png)

**Comment by PeteDuncanson** [comment]
Ok so I've double checked everything again, using the instructions here (https://github.com/aws-amplify/amplify-cli/issues/9521#issuecomment-1012578273) I know I'm looking at the right instance of OS and I'm using the right table names.

Tried it with the customer table too and the number of docs didn't change at all and that one has twice the number it should in it (we only have about 9000 customers currently in the system).

So something smells fishy but I don't know what. How best to sanity check this some more?

**Comment by PeteDuncanson** [comment]
Hi @marcvberg 

Thanks for getting back. I sort of tried that and had no luck. Happy to have another go but every time I run the back fill it reports it done everything but no index appears. Double checked I'm pointing at the right instance for my environment so at a bit of a loss as to what it might be. Might be worth a quick zoom to just sanity check that what I'm seeing/doing is right. I believe it is from the docs and from your suggestions here. 

Additional (as a backup) is there a easy way to just blitz the whole ES instance in a safe amplify cli friendly way and get it to spin it up again? I don't care about the data in there as it's rubbish so happy to kill it but don't want to delete it if that will mess with ES or Amplify. Guessing I could delete each index individually and then try a reindeer with the back fill script? That's sort of what I'm doing at the minute but just for the one index (although I have several in that instance of other models).

Cheers

Pete

**Comment by marcvberg** [comment]
Yeah I'll just reach out and we can set something up, don't delete the instance manually because that will create state drift which we'll need to correct separately from all of this weird behavior

**Comment by PeteDuncanson** [comment]
hi @marcvberg thanks for the time to do a screen share and see what the issue was.

For those following behind this was the issue, hope it helps you.

Our setup was:

* We had versioning enabled as we had been using DataStore in the past, this meant that every model has to have a _version field on it
* Its an old project (18+ months) and we were initially on ElasticSearch, in the meantime AWS has moved to using OpenSearch which is more or less the same as ElasticSearch but not quite...there are differences!
* We are running on V1 of the graphql transformers not on the new V2 yet (although we tried to upgrade a few times without luck)

Our instance of ES had manually been upgraded to OpenSearch in prep for moving to the new V2 of the transformers. Sadly that upgrade to V2 transfomers failed for us but our search stayed as the OpenSearch setup and nothing seemed to complain so we assumed it was working the same. Turns out it was not. No updates to our data where getting indexed.

This was caused by a minor difference in the way ES and OS work with version fields. When you add @searchable to your schema Amplify automatically adds in a Lambda which will index your models into ES, however when you upgrade it needs to update this Lambda as there is a change in the way it handles versioning between ES and OpenSeach. For whatever reason this Lambda wasn't updated so it was failing to do the index.

As a work around you can manually edit the Lamdba (which begins with "DdbToEsFn" if you want to find it within the Lambda console). On lines 221 and 245 change `('_version', doc_fields['_version'])` to be `('version', doc_fields['_version'])` and now your index will work again. 

You might have to reindex the table again using the script mentioned here  https://github.com/aws-amplify/amplify-cli/blob/master/packages/graphql-elasticsearch-transformer/scripts/ddb_to_es.py

Note that if you have different environments using different ES and OS versions then this will be over-written when you push so you will have to keep making the change! Ideally the fix is to get upgraded to V2 transformers and all this will go away!

Additionally Marc cleared up when a reindex would be needed and for which schema changes. If you are doing additions to your schema then it will work as you expect and will be indexed as you hope even with new fields etc. If on the other hand you are changing an existing field that is when you might have to clear your index and reindex as it won't pick up the change.

**Comment by Robbie-Cook** [comment]
Hey guys, that last link is now at https://github.com/aws-amplify/amplify-category-api/blob/HEAD/packages/graphql-elasticsearch-transformer/streaming-lambda/python_streaming_function.py I believe
