### ISSUE TITLE
Adding storage to a project with imported auth

### ISSUE THREAD

**Issue by ftrsau** [aws-amplify/amplify-cli#9545]
**Which Category is your question related to?**

- Imported Auth
- S3 storage

**Amplify CLI Version** 

`7.21.0`

**What AWS Services are you utilizing?**

- Cognito 
- amplify

**Provide additional details e.g. code snippets**
Trying to add a storage service to my amplify project. but I keep getting the following error:

```
🛑 Current auth configuration is: userPoolOnly, but identityPoolAndUserPool was required.
🛑 An error occurred when adding the storage resource
Error: Current auth configuration is: userPoolOnly, but identityPoolAndUserPool was required.
    at checkStorageAuthenticationRequirements (/Users/username/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-storage/src/provider-utils/awscloudformation/service-walkthroughs/s3-auth-api.ts:68:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at addWalkthrough (/Users/username/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-storage/src/provider-utils/awscloudformation/service-walkthroughs/s3-walkthrough.ts:99:5)
    at Object.executeAmplifyCommand (/Users/username/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-storage/src/index.ts:185:3)
    at executePluginModuleCommand (/Users/username/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:178:3)
    at executeCommand (/Users/username/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:30:5)
    at Object.run (/Users/username/.nvm/versions/node/v14.17.1/lib/node_modules/@aws-amplify/cli/src/index.ts:205:5)
```

I have imported the auth from another amplify project. and I can't seem to edit the auth. How can add the storage?

**Comment by lazpavel** [comment]
Hi @ftrsau,

`identityPoolAndUserPool` is required in order to be able to `amplify add storage`. Can you remove the auth category `amplify remove auth` and re-import? When re-importing please be sure to select `Cognito User Pool and Identity Pool` to the `What type of auth resource do you want to import?` question.

**Comment by josefaidt** [comment]
Closing due to inactivity. @ftrsau if you are still experiencing this issue please reply back to this thread and we can re-open to investigate 🙂

**Comment by Mavlarn** [comment]
I have a similar issues like [this](https://github.com/aws-amplify/amplify-cli/issues/8962). And it is also related with this "identityPoolAndUserPool" problem.
My step is:
1. create app and add auth with only user pool (the second option).
2. push and run the app, it works well.
3. add rest api and lambda function. during this step, there is a message "Current auth configuration is: userPoolOnly, but identityPoolAndUserPool was required".
4. when I try to push, there will be error.
5. Then I updated the auth, changed to use second option, which is "User Sign-Up, Sign-In, connected with AWS IAM controls ..."
6. when I try to push, there is an error: Parameters: [authwebappUsersIdentityPoolId] do not exist in the template.

it looks like there will be some kind of error if only I modify the auth type.
