### ISSUE TITLE
Groups authorization not working as expected for GraphQL transformer v2 - Not Authorized

### ISSUE THREAD

**Issue by malcomm** [aws-amplify/amplify-cli#9598]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.13.2

### Amplify CLI Version

7.6.12

### What operating system are you using?

macos

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no

### Amplify Categories

auth, api

### Amplify Commands

Not applicable

### Describe the bug

Getting:

`Not Authorized to access listFoo on type Query`

When performing a list on the model 

```
this.apiService.ListFoo();
```

### Expected behavior

Group authentication should work as documented

### Reproduction steps

1. auth rule for groups
2. cognito user with admin
3. try to access model data restricting to admin group

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type Foo
  @model
  @auth(rules: [
    { allow: groups, groups: ["admin"]},
    { allow: groups, groupsField: "groupsCanAccess", operations: [read] }
  ])
{
  name: String!
  groupsCanAccess: [String]
}

```

</details>

### Log output

<details>

```
# Put your logs below this line
error: Error: Uncaught (in promise): Object: {"data":{"listFoos":null},"errors":[{"path":["listFoos"],"data":null,"errorType":"Unauthorized","errorInfo":null,"locations":[{"line":2,"column":3,"sourceName":null}],"message":"Not Authorized to access listFoos on type Query"}]}
    at qe (polyfills.js:1:150135)
    at polyfills.js:1:149161
    at c (main.js:1:251763)
    at S.invoke (polyfills.js:1:140059)
    at Object.onInvoke (main.js:1:147119)
    at S.invoke (polyfills.js:1:139998)
    at S.run (polyfills.js:1:135092)
    at polyfills.js:1:150973
    at S.invokeTask (polyfills.js:1:140745)
    at Object.onInvokeTask (main.js:1:146929)

```

</details>

**Comment by danielleadams** [comment]
@malcomm - can you give more specifics with how you set up your auth and user groups? Also, how are you making your mutations/create requests? This feature works as expected, so I think you are setting up auth and/or creating records with the incorrect access. Thank you.

**Comment by malcomm** [comment]
@danielleadams - note: this project was previously a transformer v1 implementation. 

My setup:

- Cognito User
- Cognito group: `admin`
- Add user to the `admin` group
- Just trying to list out all the items gives me this error, I'm calling this code:

```this.apiService.ListFoo();```

**Comment by malcomm** [comment]
@danielleadams - I even deleted my environment and started over from a brand new environment. Still not working. I've tried multiple models to query and no matter what I do the `groups` auth is not work.

**Comment by danielleadams** [comment]
@malcomm What client library are using and is this a mocked or deployed server?

**Comment by malcomm** [comment]
@danielleadams - I'm using Angular on the frontend and calling the generated `APIService` for the graphql/DynamoDB backend. I have deployed servers that I'm hitting via the standard `amplify push`. Here's my `amplify status`:

```
> amplify status

    Current Environment: devthree
    
┌───────────┬─────────────────────────┬───────────┬───────────────────┐
│ Category  │ Resource name           │ Operation │ Provider plugin   │
├───────────┼─────────────────────────┼───────────┼───────────────────┤
│ Auth      │ foof6ac14a6.            │ No Change │ awscloudformation │
├───────────┼─────────────────────────┼───────────┼───────────────────┤
│ Api       │ fooapi                  │ No Change │ awscloudformation │
├───────────┼─────────────────────────┼───────────┼───────────────────┤
│ Analytics │ fooui                   │ No Change │ awscloudformation │
└───────────┴─────────────────────────┴───────────┴───────────────────┘
```

Foo is not the name on the resources, just omitted those to keep it generic for the ticket. I'm happy to supply the specifics of my environments via other channels.

**Comment by malcomm** [comment]
@danielleadams - also of note: it looks like the permissions are setup correctly from the API perspective:

```
> amplify status api -acm IssueComment

userPools:staticGroup:admin
  ┌───────────┬────────┬──────┬────────┬────────┐
  │  (index)  │ create │ read │ update │ delete │
  ├───────────┼────────┼──────┼────────┼────────┤
  │    id     │  true  │ true │  true  │  true  │
  │  issueID  │  true  │ true │  true  │  true  │
  │ createdAt │  true  │ true │  true  │  true  │
  │ updatedAt │  true  │ true │  true  │  true  │
  │  author   │  true  │ true │  true  │  true  │
  │  comment  │  true  │ true │  true  │  true  │
  └───────────┴────────┴──────┴────────┴────────┘
userPools:staticGroup:practitioner
  ┌───────────┬────────┬──────┬────────┬────────┐
  │  (index)  │ create │ read │ update │ delete │
  ├───────────┼────────┼──────┼────────┼────────┤
  │    id     │  true  │ true │  true  │  true  │
  │  issueID  │  true  │ true │  true  │  true  │
  │ createdAt │  true  │ true │  true  │  true  │
  │ updatedAt │  true  │ true │  true  │  true  │
  │  author   │  true  │ true │  true  │  true  │
  │  comment  │  true  │ true │  true  │  true  │
  └───────────┴────────┴──────┴────────┴────────┘

```

**Comment by danielleadams** [comment]
Hey @malcomm - I've been doing some testing on my end, and it appears the ACM is correct. I'm not able to reproduce your issue with the auth setup you've shared. Do you mind running the queries in AppSync to see if we can isolate the issue to either the front end or the backend?

**Comment by malcomm** [comment]
@danielleadams - I was able to run the query from AppSync when logged into Cognito.

**Comment by malcomm** [comment]
@danielleadams - I looked at my config and setup and it's all pretty standard. The one thing I forgot to mention:

```
    "aws-amplify": "^4.3.13",
```

I'm also not using the `@aws-amplify/ui-angular` package. Instead, I'm handling authentication using my own authentication service. But in the end, it does the same thing:

```
import { Auth } from 'aws-amplify';

...

  async login(username: string, password: string): Promise<CognitoUser> {
    const user = await Auth.signIn(username, password);
    this.currentUser = user;
    return user;
  }
```

This was all working great under Transformer v1.

**Comment by danielleadams** [comment]
@malcomm I'm going to transfer this to amplify-js repo so you can chat with that team. Unfortunately, I don't have much knowledge on the library.
