### ISSUE TITLE
Export to CDK: LogicalId missing for new layer version

### ISSUE THREAD

**Issue by IsaacTrevino** [aws-amplify/amplify-cli#9636]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.8.3

### Amplify CLI Version

7.6.13

### What operating system are you using?

WSL Ubuntu

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No Manual Changes Made

### Amplify Categories

auth, function

### Amplify Commands

export

### Describe the bug

`amplify export --out <export-cdk-project>` seems to throw an error

LogicalId missing for new layer version: <layer-name>

### Expected behavior

Exported Amplify Backend to CDK successful.

### Reproduction steps

`amplify export --out <export-cdk-project>`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by IsaacTrevino** [comment]
As an alternative, I removed all the dependencies of the shared layer and removed it completely.
`amplify export --out <export-cdk-project>` worked after that.

Still not a solution...

**Comment by josefaidt** [comment]
Hey @IsaacTrevino :wave: thanks for raising this! I was able to recreate this issue using the following steps:

1. create a new project `amplify init -y`
2. add a Lambda Layer with `amplify add function`
3. push with `amplify push -y` (note: this shouldn't be necessary but due to the expected error the export process never finishes)
4. `amplify export --out tmp`
5. observe error

```
LogicalId missing for new layer version: 9636layer84e8481c.
Error: LogicalId missing for new layer version: 9636layer84e8481c.
    at packageLayer (/Users/josef/.fnm/node-versions/v16.13.1/installation/pnpm-global/5/node_modules/.pnpm/amplify-category-function@3.4.1/node_modules/amplify-category-function/src/provider-utils/awscloudformation/utils/packageLayer.ts:83:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at /Users/josef/.fnm/node-versions/v16.13.1/installation/pnpm-global/5/node_modules/.pnpm/amplify-provider-awscloudformation@5.9.1/node_modules/amplify-provider-awscloudformation/src/resource-package/resource-packager.ts:156:40
    at async Promise.all (index 1)
    at ResourceExport.packageResources (/Users/josef/.fnm/node-versions/v16.13.1/installation/pnpm-global/5/node_modules/.pnpm/amplify-provider-awscloudformation@5.9.1/node_modules/amplify-provider-awscloudformation/src/resource-package/resource-packager.ts:151:12)
    at ResourceExport.packageBuildWriteResources (/Users/josef/.fnm/node-versions/v16.13.1/installation/pnpm-global/5/node_modules/.pnpm/amplify-provider-awscloudformation@5.9.1/node_modules/amplify-provider-awscloudformation/src/resource-package/resource-export.ts:72:31)
    at Object.run (/Users/josef/.fnm/node-versions/v16.13.1/installation/pnpm-global/5/node_modules/.pnpm/amplify-provider-awscloudformation@5.9.1/node_modules/amplify-provider-awscloudformation/src/export-resources.ts:40:31)
    at exportBackend (/Users/josef/.fnm/node-versions/v16.13.1/installation/pnpm-global/5/node_modules/.pnpm/@aws-amplify+cli@7.6.15/node_modules/@aws-amplify/cli/src/commands/export.ts:74:5)
    at Object.run (/Users/josef/.fnm/node-versions/v16.13.1/installation/pnpm-global/5/node_modules/.pnpm/@aws-amplify+cli@7.6.15/node_modules/@aws-amplify/cli/src/commands/export.ts:62:5)
    at Object.executeAmplifyCommand (/Users/josef/.fnm/node-versions/v16.13.1/installation/pnpm-global/5/node_modules/.pnpm/@aws-amplify+cli@7.6.15/node_modules/@aws-amplify/cli/src/index.ts:373:5)
    at executePluginModuleCommand (/Users/josef/.fnm/node-versions/v16.13.1/installation/pnpm-global/5/node_modules/.pnpm/@aws-amplify+cli@7.6.15/node_modules/@aws-amplify/cli/src/execution-manager.ts:178:3)
    at executeCommand (/Users/josef/.fnm/node-versions/v16.13.1/installation/pnpm-global/5/node_modules/.pnpm/@aws-amplify+cli@7.6.15/node_modules/@aws-amplify/cli/src/execution-manager.ts:30:5)
    at Object.run (/Users/josef/.fnm/node-versions/v16.13.1/installation/pnpm-global/5/node_modules/.pnpm/@aws-amplify+cli@7.6.15/node_modules/@aws-amplify/cli/src/index.ts:205:5)
```

Marking as a bug 🙂
