### ISSUE TITLE
Upgrade to GraphQL transformer v2 when using named @connection directives

### ISSUE THREAD

**Issue by Booligoosh** [aws-amplify/amplify-cli#9663]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**
API migration

**Amplify CLI Version** 

7.6.13

**What AWS Services are you utilizing?**

Amplify

**Provide additional details e.g. code snippets**

My schema uses the `@connection` directive with a `name` parameter, similar to the [examples used in the legacy docs](https://docs.amplify.aws/cli-legacy/graphql-transformer/overview/). When running `amplify api migrate`, I get the following error:
```
You are using the deprecated parameterization of @connection which cannot be automatically migrated.
```

If I try removing all the `name` parameters from connections in my schema, I then get the error described in #3923 when running `amplify push`.

My question is - **Is there a supported way to upgrade to the GraphQL transformer v2 for projects that use `@connection(name: "...")`, without deleting all Dynamo tables and starting from scratch?** This application is running in a production environment and contains thousands of records.

**Comment by cjihrig** [comment]
@Booligoosh we recommend migrating to a v1 schema that can be auto-migrated before trying to migrate to v2. That should avoid any data loss. Can you try migrating one `@connection` directive at a time, wish a push after each change?

**Comment by Booligoosh** [comment]
Hi @cjihrig, thanks for the reply. When I try removing the `name` parameter from a `@connection` directive, I get the error `Attempting to add and remove a global secondary index at the same time`. Is this not expected behaviour?

How do we remove the name parameter correctly so that the v1 schema can be auto-migrated?

**Comment by marcvberg** [comment]
HI @Booligoosh what are the contents of your `amplify/cli.json`? If you do not have the flag `enableIterativeGSIUpdates` set to `true` under `graphQLTransformer` I recommend setting that and trying again

**Comment by Booligoosh** [comment]
Thanks @marcvberg, that worked!

**Comment by emmafass** [comment]
I cam across the same error and this fix worked for me. However, I am now getting: ` Error encountered migrating schemas` `Syntax Error: Unexpected <EOF>` 

It says my schema compiles correctly and then throws this error. 

I have my schema broken into multiple .graphql files under my `/schema` directory.

Any ideas?

<img width="1118" alt="Screen Shot 2022-02-25 at 1 46 28 PM" src="https://user-images.githubusercontent.com/13208951/155771281-4b863d7e-b873-4fcb-b809-5c6e35079889.png">

```
amplify migrate api


GraphQL schema compiled successfully.

Edit your schema at /Users/emmafass/ringside-ionic/amplify/backend/api/RingSide/schema.graphql or place .graphql files in a directory at /Users/emmafass/ringside-ionic/amplify/backend/api/RingSide/schema

⚠️ Warning: The migration will not carry over any existing comments in your GraphQL schema, you'll be able to manually copy them in from the back-ups stored at /Users/emmafass/ringside-ionic/amplify/backend/api/RingSide/.migration-backup.

🛑 Error encountered migrating schemas
Restoring original schemas
🛑 Syntax Error: Unexpected <EOF>
GraphQLError: Syntax Error: Unexpected <EOF>
    at syntaxError (/Users/emmafass/.nvm/versions/node/v14.16.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql/error/syntaxError.js:15:10)
    at Parser.unexpected (/Users/emmafass/.nvm/versions/node/v14.16.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql/language/parser.js:1463:41)
    at Parser.parseDefinition (/Users/emmafass/.nvm/versions/node/v14.16.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql/language/parser.js:157:16)
    at Parser.many (/Users/emmafass/.nvm/versions/node/v14.16.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql/language/parser.js:1518:26)
    at Parser.parseDocument (/Users/emmafass/.nvm/versions/node/v14.16.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql/language/parser.js:111:25)
    at parse (/Users/emmafass/.nvm/versions/node/v14.16.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql/language/parser.js:36:17)
    at migrateGraphQLSchema (/Users/emmafass/.nvm/versions/node/v14.16.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/graphql-transformer-migrator/src/schema-migrator.ts:118:21)
    at runMigration (/Users/emmafass/.nvm/versions/node/v14.16.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/graphql-transformer-migrator/src/schema-migrator.ts:107:29)
    at attemptV2TransformerMigration (/Users/emmafass/.nvm/versions/node/v14.16.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/graphql-transformer-migrator/src/schema-migrator.ts:64:5)
    at Object.run (/Users/emmafass/.nvm/versions/node/v14.16.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-api/src/commands/api/migrate.ts:39:3)
    at Object.executeAmplifyCommand (/Users/emmafass/.nvm/versions/node/v14.16.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-api/src/index.ts:223:5)
    at executePluginModuleCommand (/Users/emmafass/.nvm/versions/node/v14.16.0/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:178:3)
    at executeCommand (/Users/emmafass/.nvm/versions/node/v14.16.0/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:30:5)
    at Object.run (/Users/emmafass/.nvm/versions/node/v14.16.0/lib/node_modules/@aws-amplify/cli/src/index.ts:205:5)
```

**Comment by emmafass** [comment]
I figured it out. I had a model commented out in one of my files. That was causing the EOF error

**Comment by bishoym** [comment]
> @Booligoosh we recommend migrating to a v1 schema that can be auto-migrated before trying to migrate to v2. That should avoid any data loss. Can you try migrating one `@connection` directive at a time, wish a push after each change?

Hi @Booligoosh, can you expand on this statement please? I'm currently facing the same error and wanted to know what aspects of the v1 schema need to be migrated manually in order to enable auto-migration. I have way too many `@connection` calls to do manually, so I'd appreciate some clarity around what an "auto-migration ready v1 schema" looks like. Is it just the `name` parameter or are there others I need to be aware of? Thanks!
