### ISSUE TITLE
amplify configure or init fails

### ISSUE THREAD

**Issue by veeragoni** [aws-amplify/amplify-cli#97]
**Do you want to request a feature or report a bug?**
bug

**What is the current behavior?**
unable to setup amplify on my machine

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

**Steps to reproduce the issue:**
```
me@laptop  ~/Projects/amplify-cli-test  amplify configure
/usr/local/lib/node_modules/@aws-amplify/cli/src/commands/console.js:9
    const combinedPlugins = { ...categoryPlugins, ...providerPlugins };
                              ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.loadModule (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/loaders/module-loader.js:14:12)
 ✘ me@laptop  ~/Projects/amplify-cli-test  amplify init
/usr/local/lib/node_modules/@aws-amplify/cli/src/commands/console.js:9
    const combinedPlugins = { ...categoryPlugins, ...providerPlugins };
                              ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.loadModule (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/loaders/module-loader.js:14:12)
 ✘ me@laptop  ~/Projects/amplify-cli-test  npm --version
6.4.1
 me@laptop  ~/Projects/amplify-cli-test  node --version
v8.2.1
```

**What is the expected behavior?**
should configure or initialize

**Additional environment details**
on mac, OSX version: 10.12.6. npm and node versions are above

* **OS version (ie Windows 10 build X, macOS Sierra 10.12.6, etc.)**
* **Output of ``amplify --version``**:
```
me@laptop  ~  npm install -g @aws-amplify/cli
npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
/usr/local/bin/amplify -> /usr/local/lib/node_modules/@aws-amplify/cli/bin/amplify
+ @aws-amplify/cli@0.1.16
updated 3 packages in 38.499s
 me@laptop  ~  amplify version
/usr/local/lib/node_modules/@aws-amplify/cli/src/commands/console.js:9
    const combinedPlugins = { ...categoryPlugins, ...providerPlugins };
                              ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.loadModule (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/loaders/module-loader.js:14:12)
```

* **Did this work in previous versions?**: Y/N
N

**Comment by kaustavghosh06** [comment]
@veeragoni Seems like a Old nose version issue. Could you update to the latest Node version?

**Comment by veeragoni** [comment]
cool. thats the issue. fixed now. thanks @kaustavghosh06

**Comment by kapilajayant** [comment]
> @veeragoni Seems like an old Node version issue. Could you update to the latest Node version and try again?

Can you tell which version of node and npm are required to configure amplify?
Also, it would be better if you could write the command to update the same.
