### ISSUE TITLE
Mock function fails with "No module named 'pipenv'"

### ISSUE THREAD

**Issue by a-y-klimovich** [aws-amplify/amplify-cli#9720]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

curl

### Amplify CLI Version

7.6.15

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

function

### Amplify Commands

Not applicable

### Describe the bug

I can't run  a lambda functions locally

### Expected behavior

I should be able to run lambda function locally

### Reproduction steps

1. Add Python lambda function with Hello World template
`  amplify add function`
2. Run test function locally
`  amplify mock function test`
3. Execution fails with "No module named 'pipenv'" error
 

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line

Traceback (most recent call last):
  File "c:\program files\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\alexander.klimovich\AppData\Roaming\Python\Python38\Scripts\pipenv.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'pipenv'

```

</details>

### Additional information

Python 3.8.10
pipenv, version 2022.1.8

**Comment by ammarkarachi** [comment]
@a-y-klimovich have you tried `pip install pipenv` and then run the mock function?

**Comment by a-y-klimovich** [comment]
@ammarkarachi 
> @a-y-klimovich have you tried `pip install pipenv` and then run the mock function?

Yes, I installed **pipenv** but id didn't help. The same error.

**Comment by josefaidt** [comment]
Hey @a-y-klimovich can you confirm whether `pipenv` is in your PATH? If you run `which.exe pipenv` does it return the path where pipenv was installed to?

**Comment by a-y-klimovich** [comment]
@josefaidt 

> Hey @a-y-klimovich can you confirm whether `pipenv` is in your PATH? If you run `where.exe pipenv` does it return the path where pipenv was installed to?

Pipenv was in my PATH. 

`C:\Users\alexander.klimovich>where.exe pipenv
C:\Users\alexander.klimovich\AppData\Roaming\Python\Python38\Scripts\pipenv.exe

C:\Users\alexander.klimovich>pipenv --version
pipenv, version 2022.1.8`

It was installed as recommended
`pip install --user pipenv`

**Comment by a-y-klimovich** [comment]
> Hey @a-y-klimovich may you post the full error message that you're receiving when attempting to mock your function?

@josefaidt , Please find attached
[mock.log](https://github.com/aws-amplify/amplify-cli/files/8068678/mock.log)

**Comment by josefaidt** [comment]
Hey @a-y-klimovich :wave: thanks for including the log! Can you confirm `python`/`python3` is pointing to Python 3.8? I'm unable to reproduce this issue on mac and windows. Can you try force reinstalling? `pip3 install pipenv --force-reinstall`

**Comment by a-y-klimovich** [comment]
@josefaidt 

> Can you confirm `python`/`python3` is pointing to Python 3.8?
`PS D:\Work\amplifytest> python3 --version
Python 3.8.10
PS D:\Work\amplifytest> python --version 
Python 3.8.10`

> Can you try force reinstalling? `pip3 install pipenv --force-reinstall`
Done. Check logs.
[reinstall_pipenv.log](https://github.com/aws-amplify/amplify-cli/files/8088561/reinstall_pipenv.log)


Now I'm unable to mock at all.
`PS D:\Work\amplifytest> amplify mock function test
? Provide the path to the event JSON object relative to D:\Work\amplifytest\amplify\backend\function\test src/event.json
Ensuring latest function changes are built...
You must have pipenv installed and available on your PATH as "pipenv". It can be installed by running "pip3 install --user pipenv".
You must have virtualenv installed and available on your PATH as "venv". It can be installed by running "pip3 install venv".
Missing required dependencies to package test
`

How can I satisfy **venv** dependency?

`PS D:\Work\amplifytest> pip3 install --user pipenv
Requirement already satisfied: pipenv in c:\users\alexander.klimovich\appdata\roaming\python\python38\site-packages (2022.1.8)
Requirement already satisfied: pip>=18.0 in c:\users\alexander.klimovich\appdata\roaming\python\python38\site-packages (from pipenv) (22.0.3)
Requirement already satisfied: certifi in c:\users\alexander.klimovich\appdata\roaming\python\python38\site-packages (from pipenv) (2021.10.8)
Requirement already satisfied: virtualenv in c:\users\alexander.klimovich\appdata\roaming\python\python38\site-packages (from pipenv) (20.13.1)
Requirement already satisfied: virtualenv-clone>=0.2.5 in c:\users\alexander.klimovich\appdata\roaming\python\python38\site-packages (from pipenv) (0.5.7)
Requirement already satisfied: setuptools>=36.2.1 in c:\users\alexander.klimovich\appdata\roaming\python\python38\site-packages (from pipenv) (60.9.2)
Requirement already satisfied: filelock<4,>=3.2 in c:\users\alexander.klimovich\appdata\roaming\python\python38\site-packages (from virtualenv->pipenv) (3.5.1)
Requirement already satisfied: distlib<1,>=0.3.1 in c:\users\alexander.klimovich\appdata\roaming\python\python38\site-packages (from virtualenv->pipenv) (0.3.4)
Requirement already satisfied: six<2,>=1.9.0 in c:\users\alexander.klimovich\appdata\roaming\python\python38\site-packages (from virtualenv->pipenv) (1.16.0)
Requirement already satisfied: platformdirs<3,>=2 in c:\users\alexander.klimovich\appdata\roaming\python\python38\site-packages (from virtualenv->pipenv) (2.5.0)


PS D:\Work\amplifytest> pip3 install venv
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement venv (from versions: none)
ERROR: No matching distribution found for venv


PS D:\Work\amplifytest> pip3 install virtualenv
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: virtualenv in c:\users\alexander.klimovich\appdata\roaming\python\python38\site-packages (20.13.1)
Requirement already satisfied: distlib<1,>=0.3.1 in c:\users\alexander.klimovich\appdata\roaming\python\python38\site-packages (from virtualenv) (0.3.4)
Requirement already satisfied: six<2,>=1.9.0 in c:\users\alexander.klimovich\appdata\roaming\python\python38\site-packages (from virtualenv) (1.16.0)
Requirement already satisfied: platformdirs<3,>=2 in c:\users\alexander.klimovich\appdata\roaming\python\python38\site-packages (from virtualenv) (2.5.0)
Requirement already satisfied: filelock<4,>=3.2 in c:\users\alexander.klimovich\appdata\roaming\python\python38\site-packages (from virtualenv) (3.5.1)`

**Comment by josefaidt** [comment]
Hey @a-y-klimovich thank you for clarifying! Apologies for not thinking about this before but can you try the workaround noted here? https://github.com/aws-amplify/amplify-cli/issues/8337#issuecomment-933776737

```
cd amplify/backend/function/your-function-name
pipenv shell
```

Based on the latest comment it appears the user-installed packages do not work. How was the Amplify CLI installed?

**Comment by a-y-klimovich** [comment]
@josefaidt 

> How was the Amplify CLI installed?
As [recommended ](https://docs.amplify.aws/cli/start/install/)for windows - using cURL option.

**Comment by josefaidt** [comment]
Hey @a-y-klimovich can you try the steps noted in the previous comment to see if that mitigates the issue?

**Comment by a-y-klimovich** [comment]
@josefaidt ,

I've reinstalled python and now I'm able to run build and mock commands again.

I've run _pipenv shell_ and installed _pipenv_. But it didn't fixed the issue. Still have the same exception.
[pipenv_install.log](https://github.com/aws-amplify/amplify-cli/files/8110835/pipenv_install.log)
[mock_test.log](https://github.com/aws-amplify/amplify-cli/files/8110836/mock_test.log)
[where_app.log](https://github.com/aws-amplify/amplify-cli/files/8110838/where_app.log)

**Comment by josefaidt** [comment]
Hey @a-y-klimovich thank you for clarifying! When you ran `pipenv shell` was it from the function's src directory?

**Comment by josefaidt** [comment]
Hey @a-y-klimovich can you try:

1. cd to function's directory (not src/, excuse me on that one)
2. run `pipenv shell`
3. run `pipenv install`
4. attempt mocking the function

for reference: https://www.xiegerts.com/post/slack-app-bolt-python-amplify/

**Comment by a-y-klimovich** [comment]
Hi @josefaidt 

> * cd to function's directory (not src/, excuse me on that one)
> * run `pipenv shell`
> * run `pipenv install`
> * attempt mocking the function

I still getting  the same error.
[mock_pipenv_install.txt](https://github.com/aws-amplify/amplify-cli/files/8132230/mock_pipenv_install.txt)

**Comment by josefaidt** [comment]
Hey @a-y-klimovich looking at the logs I see a note about site-packages not being writeable and defaulting to user installation. Can you try reinstalling pipenv with python3? 

```
python3 -m pip install pipenv
```

**Comment by a-y-klimovich** [comment]
Hi @josefaidt 
>  looking at the logs I see a note about site-packages not being writeable and defaulting to user installation.
As I mentioned, I reinstalled python Feb 21. As it's installed in the user directory I don't see any messages about "writable directories".

> Can you try reinstalling pipenv with python3?
Sure. Please find log attached. 
[pipenv_reinstall.log](https://github.com/aws-amplify/amplify-cli/files/8141350/pipenv_reinstall.log)

**Comment by josefaidt** [comment]
Hey @a-y-klimovich :wave: apologies for the delay! After reinstalling pipenv with python3 are you able to push the python function?

**Comment by josefaidt** [comment]
Hey @a-y-klimovich :wave: just wanted to follow-up on this one to see if you are still experiencing this issue and if you're whether to mitigate the issue after reinstalling pipenv with python3?

**Comment by josefaidt** [comment]
Closing due to inactivity
