### ISSUE TITLE
unable to `amplify pull` project with auth, missing `auth/.../build/parameters.json`

### ISSUE THREAD

**Issue by jimxzai** [aws-amplify/amplify-cli#9778]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

curl -sL https://aws-amplify.github.io/amplify-cli/install | bash && $SHELL

### If applicable, what version of Node.js are you using?

v12.20.1

### Amplify CLI Version

7.6.20

### What operating system are you using?

mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no

### Amplify Categories

auth

### Amplify Commands

pull

### Describe the bug

the environment has been working fine but now can't pull because of the failure:

amplify pull                                                                                                              
? Select the authentication method you want to use: AWS profile

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

? Please choose the profile you want to use aws-dev
? Which app are you working on? dg3jaboxeesrd
? Pick a backend environment: test
? Choose your default editor: Visual Studio Code
? Choose the type of app that you're building ios
Failed to pull the backend.
File at path: '..._backend/amplify/backend/auth/alphamdcitycb7a0a83cb7a0a83/build/parameters.json' does not exist
Error: File at path: '...backend/amplify/backend/auth/alphamdcitycb7a0a83cb7a0a83/build/parameters.json' does not exist
    at Function.readJson (/snapshot/node_modules/amplify-cli-core/lib/jsonUtilities.js:40:19)
    at StateManager.getData (/snapshot/node_modules/amplify-cli-core/lib/state-manager/stateManager.js:298:56)
    at StateManager.getResourceParametersJson (/snapshot/node_modules/amplify-cli-core/lib/state-manager/stateManager.js:122:25)
    at ensureAmplifyMetaFrontendConfig (/snapshot/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/on-category-outputs-change.js:101:60)
    at AmplifyToolkit.onCategoryOutputsChange [as _onCategoryOutputsChange] (/snapshot/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/on-category-outputs-change.js:41:9)
    at generateFiles (/snapshot/node_modules/@aws-amplify/cli/lib/attach-backend-steps/a40-generateFiles.js:58:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at attachBackend (/snapshot/node_modules/@aws-amplify/cli/lib/attach-backend.js:44:9)
    at Object.run (/snapshot/node_modules/@aws-amplify/cli/lib/commands/pull.js:68:9)
    at Object.executeAmplifyCommand (/snapshot/node_modules/@aws-amplify/cli/lib/index.js:288:9)
    at executePluginModuleCommand (/snapshot/node_modules/@aws-amplify/cli/lib/execution-manager.js:164:5)
    at executeCommand (/snapshot/node_modules/@aws-amplify/cli/lib/execution-manager.js:35:9)
    at Object.run (/snapshot/node_modules/@aws-amplify/cli/lib/index.js:162:9)

but in the build folder there is leftover  of .gitignore which has build/

#amplify-do-not-edit-begin
amplify/\#current-cloud-backend
amplify/.config/local-*
amplify/logs
amplify/mock-data
amplify/backend/amplify-meta.json
amplify/backend/.temp
build/
dist/
node_modules/
aws-exports.js
awsconfiguration.json
amplifyconfiguration.json
amplifyconfiguration.dart
amplify-build-config.json
amplify-gradle-config.json
amplifytools.xcconfig
.secret-*
**.sample
#amplify-do-not-edit-end

### Expected behavior

should be able to pull the specs for the second client or new machine, but failed.

### Reproduction steps

1. amplify push from the backend development machine : success
2. from the 2nd machine or a new empty folder :  amplify pull  failed.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line

ackend/amplify/backend/auth/alphamdcitycb7a0a83cb7a0a83/build/parameters.json' does not exist
    at Function.readJson (/snapshot/node_modules/amplify-cli-core/lib/jsonUtilities.js:40:19)
    at StateManager.getData (/snapshot/node_modules/amplify-cli-core/lib/state-manager/stateManager.js:298:56)
    at StateManager.getResourceParametersJson (/snapshot/node_modules/amplify-cli-core/lib/state-manager/stateManager.js:122:25)
    at ensureAmplifyMetaFrontendConfig (/snapshot/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/on-category-outputs-change.js:101:60)
    at AmplifyToolkit.onCategoryOutputsChange [as _onCategoryOutputsChange] (/snapshot/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/on-category-outputs-change.js:41:9)
    at generateFiles (/snapshot/node_modules/@aws-amplify/cli/lib/attach-backend-steps/a40-generateFiles.js:58:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at attachBackend (/snapshot/node_modules/@aws-amplify/cli/lib/attach-backend.js:44:9)
    at Object.run (/snapshot/node_modules/@aws-amplify/cli/lib/commands/pull.js:68:9)
    at Object.executeAmplifyCommand (/snapshot/node_modules/@aws-amplify/cli/lib/index.js:288:9)
    at executePluginModuleCommand (/snapshot/node_modules/@aws-amplify/cli/lib/execution-manager.js:164:5)
    at executeCommand (/snapshot/node_modules/@aws-amplify/cli/lib/execution-manager.js:35:9)
    at Object.run (/snapshot/node_modules/@aws-amplify/cli/lib/index.js:162:9)
jimxiao@jims-MacBook-Pro mise_backend % code .      

```
even manual copy the files there and verified with ls still complain the file does not exist
</details>

**Comment by jimxzai** [comment]
Thank you JoseFaidt,  I tried both. our situation is not 'init' but 'amplify pull' to get backend specs for the front end development machine. but failed.  1: before the amplify pull , folder asked to be empty (manual copy from backend development machine will be wiped out); 2: after the failure only 2 files: .gitnigore and .vscode. in the .gitignore generated as above has build in the list to ignore.

**Comment by josefaidt** [comment]
Hey @jimxzai thank you for clarifying! I've relabeled this issue accordingly and updated the title. Although it appears to be the same root cause I'm leaving this open due to the different workflow (`pull` is affected vs `init`)

**Comment by jimxzai** [comment]
resolved, 

root cause is because of  ~/.aws/amplify/deployment-secrets.json was wiped out during upgrade and it is not checked in git. need to regenerate it from old security way through teamp-provider-info.json

**Comment by SidMorad** [comment]
> Hi @jimxzai
> 
> I was not able to reproduce this on my end following the same steps as mentioned above.
> 
> Based on the error , it seems the `parameters.json` file is missing from s3 bucket as we download backend from s3 bucket during `amplify pull`.
> 
> `.gitignore` isn't useful here as we don't git pull the project during `amplify pull`.
> 
> Can you check if the file is present in S3 bucket ?

@jimxzai I'm facing this issue, would you please tell me should `parameters.json` be present in root folder of s3 bucket? if not which path should I check?

Please not my backend environment will get updated with CI builds only, and after a commit which had nothing to do with auth related config, this issue occurred! so I don't know how to reproduce this. but I willing to provide more information if needed? thank you.

**Comment by SidMorad** [comment]
@akshbhu I find something that might helps to reproduce, If I change amplify version from `latest` to `10.2.3` in build setting then CI pipeline will run okay.
