### ISSUE TITLE
can't pull or switch environment

### ISSUE THREAD

**Issue by jimxzai** [aws-amplify/amplify-cli#9780]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

us-east-1

### Describe the bug

```
 % amplify env checkout test
✔ Initialized provider successfully.
✔ Channel information retrieved for APNS
✔ Channel is not setup for FCM 
✔ Channel is not setup for Email 
✔ Channel is not setup for SMS 
Initialized your environment successfully.
jimxiao@jims-MacBook-Pro u-call-us-backend % amplify status

    Current Environment: test
    
┌───────────────┬─────────────────────────────┬───────────┬───────────────────┐
│ Category      │ Resource name               │ Operation │ Provider plugin   │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Auth          │ alphamdcitycb7a0a83cb7a0a83 │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Storage       │ s32eebcc0e                  │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Api           │ alphamdcity                 │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Api           │ userAdmin                   │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Api           │ media                       │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Api           │ alphamdcityInvite           │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Api           │ alphamdcityStripe           │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Api           │ alphamdcityPaymentRecord    │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Api           │ alphamdcityZipcode          │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Api           │ alphamdcityRecommend        │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Api           │ alphamdcityStripeHook       │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function      │ alphamdcityUserAdmin        │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function      │ S3Trigger49bf7ecf           │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function      │ alphamdcityMedia            │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function      │ alphamdcityPDFMaker         │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function      │ alphamdcitySocialCounter    │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function      │ alphamdcityServiceCounter   │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function      │ alphamdcityInvite           │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function      │ alphamdcityServiceRating    │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function      │ alphamdcityStripe           │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function      │ alphamdcityPaymentRecord    │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function      │ alphamdcityZipcode          │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function      │ alphamdcityProjStatemachine │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function      │ alphamdcityRecommend        │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function      │ alphamdcityStripeHook       │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function      │ alphamdcityNewUserReward    │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Analytics     │ alphamdcity                 │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Notifications │ alphamdcity                 │ No Change │                   │
└───────────────┴─────────────────────────────┴───────────┴───────────────────┘

Pinpoint URL to track events https://us-east-1.console.aws.amazon.com/pinpoint/home/?region=us-east-1#/apps/b5f1dc16085f439bae660ce39f8b184e/analytics/overview
GraphQL endpoint: https://u4lgiuprlrgq3jfsqw3igjfqye.appsync-api.us-east-1.amazonaws.com/graphql
GraphQL API KEY: da2-blz4fhdhgbgmjllvc2ssv7mfp4

GraphQL transformer version: 1
REST API endpoint: https://4id31qvbuh.execute-api.us-east-1.amazonaws.com/test
Hosted UI Endpoint: https://alphamdcitycb7a0a83-cb7a0a83-test.auth.us-east-1.amazoncognito.com/
Test Your Hosted UI Endpoint: https://alphamdcitycb7a0a83-cb7a0a83-test.auth.us-east-1.amazoncognito.com/login?response_type=code&client_id=666cvihd78729s3jsjifsigsb0&redirect_uri=alphamdcity://

% amplify push
✔ Successfully pulled backend environment test from the cloud.

    Current Environment: test
    
┌───────────────┬─────────────────────────────┬───────────┬───────────────────┐
│ Category      │ Resource name               │ Operation │ Provider plugin   │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Auth          │ alphamdcitycb7a0a83cb7a0a83 │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Storage       │ s32eebcc0e                  │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Api           │ alphamdcity                 │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Api           │ userAdmin                   │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Api           │ media                       │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Api           │ alphamdcityInvite           │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Api           │ alphamdcityStripe           │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Api           │ alphamdcityPaymentRecord    │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Api           │ alphamdcityZipcode          │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Api           │ alphamdcityRecommend        │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Api           │ alphamdcityStripeHook       │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function      │ alphamdcityUserAdmin        │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function      │ S3Trigger49bf7ecf           │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function      │ alphamdcityMedia            │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function      │ alphamdcityPDFMaker         │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function      │ alphamdcitySocialCounter    │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function      │ alphamdcityServiceCounter   │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function      │ alphamdcityInvite           │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function      │ alphamdcityServiceRating    │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function      │ alphamdcityStripe           │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function      │ alphamdcityPaymentRecord    │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function      │ alphamdcityZipcode          │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function      │ alphamdcityProjStatemachine │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function      │ alphamdcityRecommend        │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function      │ alphamdcityStripeHook       │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function      │ alphamdcityNewUserReward    │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Analytics     │ alphamdcity                 │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Notifications │ alphamdcity                 │ No Change │                   │
└───────────────┴─────────────────────────────┴───────────┴───────────────────┘

No changes detected
% amplify pull

Pre-pull status:

    Current Environment: test
    
┌───────────────┬─────────────────────────────┬───────────┬───────────────────┐
│ Category      │ Resource name               │ Operation │ Provider plugin   │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Auth          │ alphamdcitycb7a0a83cb7a0a83 │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Storage       │ s32eebcc0e                  │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Api           │ alphamdcity                 │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Api           │ userAdmin                   │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Api           │ media                       │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Api           │ alphamdcityInvite           │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Api           │ alphamdcityStripe           │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Api           │ alphamdcityPaymentRecord    │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Api           │ alphamdcityZipcode          │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Api           │ alphamdcityRecommend        │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Api           │ alphamdcityStripeHook       │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function      │ alphamdcityUserAdmin        │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function      │ S3Trigger49bf7ecf           │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function      │ alphamdcityMedia            │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function      │ alphamdcityPDFMaker         │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function      │ alphamdcitySocialCounter    │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function      │ alphamdcityServiceCounter   │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function      │ alphamdcityInvite           │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function      │ alphamdcityServiceRating    │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function      │ alphamdcityStripe           │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function      │ alphamdcityPaymentRecord    │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function      │ alphamdcityZipcode          │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function      │ alphamdcityProjStatemachine │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function      │ alphamdcityRecommend        │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function      │ alphamdcityStripeHook       │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function      │ alphamdcityNewUserReward    │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Analytics     │ alphamdcity                 │ No Change │ awscloudformation │
├───────────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Notifications │ alphamdcity                 │ No Change │                   │
└───────────────┴─────────────────────────────┴───────────┴───────────────────┘

✔ Successfully pulled backend environment test from the cloud.
✔ Channel information retrieved for APNS
✔ Channel is not setup for FCM 
✔ Channel is not setup for Email 
✔ Channel is not setup for SMS 
✖ There was an error initializing your environment.
'jsonString' argument missing or empty
Error: 'jsonString' argument missing or empty
    at Function.parse (/snapshot/node_modules/amplify-cli-core/lib/jsonUtilities.js:79:15)
    at Function.readJson (/snapshot/node_modules/amplify-cli-core/lib/jsonUtilities.js:47:32)
    at StateManager.getDeploymentSecrets (/snapshot/node_modules/amplify-cli-core/lib/state-manager/stateManager.js:60:51)
    at AmplifyToolkit.saveEnvResourceParameters [as _saveEnvResourceParameters] (/snapshot/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/envResourceParams.js:74:67)
    at /snapshot/node_modules/@aws-amplify/amplify-category-auth/lib/index.js:275:29
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)


% amplify env checkout dev
✔ Initialized provider successfully.
✔ Channel information retrieved for APNS
✔ Channel is not setup for FCM 
✔ Channel is not setup for Email 
✔ Channel information retrieved for SMS
✖ There was an error initializing your environment.
'jsonString' argument missing or empty
Error: 'jsonString' argument missing or empty
    at Function.parse (/snapshot/node_modules/amplify-cli-core/lib/jsonUtilities.js:79:15)
    at Function.readJson (/snapshot/node_modules/amplify-cli-core/lib/jsonUtilities.js:47:32)
    at StateManager.getDeploymentSecrets (/snapshot/node_modules/amplify-cli-core/lib/state-manager/stateManager.js:60:51)
    at AmplifyToolkit.saveEnvResourceParameters [as _saveEnvResourceParameters] (/snapshot/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/envResourceParams.js:74:67)
    at /snapshot/node_modules/@aws-amplify/amplify-category-auth/lib/index.js:275:29
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

### Expected behavior

expecting success

### Reproduction steps

1. make change of schema
2. push
3. pull /change environment. failed

**Comment by josefaidt** [comment]
Hey @jimxzai :wave: can you confirm whether you have the following file? If not, are you able to provide minimal reproduction steps to reproduce this behavior? Was this project created on another machine and then pulled to your machine?

```
~/.aws/amplify/deployment-secrets.json
```

**Comment by jimxzai** [comment]
-rw-------  1 jimxiao  staff  0 Dec 27 00:02 ~/amplify/deployment-secrets.json

**Comment by jimxzai** [comment]
amplify pull --appId dg3jaboxeesrd --envName test this is the command used.

**Comment by jimxzai** [comment]
resolved

root cause is because of  ~/.aws/amplify/deployment-secrets.json was wiped out during upgrade and it is not checked in git. need to regenerate it from old security way through teamp-provider-info.json

**Comment by jimxzai** [comment]
2nd reason because of system variable missing, still playing with work around  https://bleepcoder.com/amplify-console/510729558/amplify-console-build-failure-facebookappid-amazonappid.
