### ISSUE TITLE
@searchable directive does not index existing documents

### ISSUE THREAD

**Issue by chrisco255** [aws-amplify/amplify-cli#98]
**Do you want to request a feature or report a bug?**
Bug

**What is the current behavior?**
When adding `@searchable` directive to an existing model (one with entries already in Dynamo), the ElasticSearch service does not index existing documents. It will only index new documents added after the `@searchable` directive is added.

**Steps to reproduce the issue:**

1. Create a model in /amplify/backend/api/schema.graphql
2. Use `amplify push` to deploy CloudFormation template and publish API
3. Use AppSync GraphQL explorer to create new documents for that model
4. Go back to schema.graphql file and add `@searchable` directive
5. Use `amplify push` to update resources

**What is the expected behavior?**
Elasticsearch service should index all existing documents for a given model, and not just new ones.

**Additional environment details**

* **OS version (ie Windows 10 build X, macOS Sierra 10.12.6, etc.)**: Ubuntu 18, Node v.8.9.3
* **Output of ``amplify --version``**: 0.1.16
* **Did this work in previous versions?**: N?

**Comment by mikeparisstuff** [comment]
This is a feature request. Backfilling data is a goal in the future but is not immediately in scope.

**Comment by hisham** [comment]
+1. I am running into this too. Is there a workaround in the meantime like using https://www.npmjs.com/package/dynamodb-to-elasticsearch to backfill the data?

**Comment by edfinegan** [comment]
+1 for this feature. Is there an easy way to manually do this?

**Comment by artista7** [comment]
@mikeparisstuff +1 for the feature.

**Comment by FatimahSanni** [comment]
+1 for this feature.

**Comment by claytonrogers** [comment]
+1 for this feature

**Comment by monaye** [comment]
+1 enterprise must-have.

**Comment by aldegoeij** [comment]
If you have DDB Stream -> Lambda -> ES setup then you could easily add a field e.g. 'migration_run:1' to all existing records in a DynamoDB table to stream it to Elastic?
Put some throttling or scheduling in place to not impact normal operation.

**Comment by malcomm** [comment]
Any updates on this? Without this, it makes it pretty hard to use `@ searchable`. Even if we had a manual workaround that would be great.

**Comment by houmark** [comment]
@malcomm The fix is fairly simple. Create a migration Lamda function. Query all documents. Make it update one "migration" field in each document. DynamoDB will then sync the entire document to Elasticsearch. You can then delete the "migration" field or keep it around for a future DB migration.

**Comment by brene** [comment]
Hi everyone - we've added a section in our documentation explaining how to backfill existing data https://docs.amplify.aws/cli/graphql-transformer/directives#backfill-your-elasticsearch-index-from-your-dynamodb-table

**Comment by clodal** [comment]
Thanks @brene  the script works beautifully! For anyone looking to put together the script by brene, you can find the _Lambda function ARN_ in `AWS > Services > Lambda`. There really is a lambda generated called `DdbToEsFn` to my surprise as I didn't know since it was auto-generated. Also, you can find the _Event source ARN_ in `AWS > DynamoDB > <Your Table> > Overview Tab > Stream details`

**Comment by GeorgeBellTMH** [comment]
It would be even better if the CLI did this easily via something like:
 amplify api reindex

- Delete Existing indexes
- Repush all @searchable fields via the above lambda
- Cleanup

**Comment by bart** [comment]
@clodal Is there any way to use it from the CLI?

**Comment by renanbronchart** [comment]
> Hi everyone - we've added a section in our documentation explaining how to backfill existing data https://docs.amplify.aws/cli/graphql-transformer/directives#backfill-your-elasticsearch-index-from-your-dynamodb-table

I have a problem when I try to run the script.
Here my log :
```
INFO:root:dynamodb: dynamodb.ServiceResource()
INFO:root:table: dynamodb.Table(name='Brand-7ei4hrcnvjeudbj6vxwbg67fne-dev')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/botocore/httpsession.py", line 314, in send
    urllib_response = conn.urlopen(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/util/retry.py", line 386, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <botocore.awsrequest.AWSHTTPSConnection object at 0x10b6cc9a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/renanbronchart/sites/wenose/wenose-app/ddb_to_es.py", line 96, in <module>
    main()
  File "/Users/renanbronchart/sites/wenose/wenose-app/ddb_to_es.py", line 34, in main
    import_dynamodb_items_to_es(args.tn, args.sk, args.ak, args.st, args.rn, args.esarn, args.lf, scan_limit)
  File "/Users/renanbronchart/sites/wenose/wenose-app/ddb_to_es.py", line 49, in import_dynamodb_items_to_es
    ddb_keys_name = [a['AttributeName'] for a in table.key_schema]
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/boto3/resources/factory.py", line 339, in property_loader
    self.load()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/boto3/resources/factory.py", line 505, in do_action
    response = action(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/botocore/client.py", line 662, in _make_api_call
    http, parsed_response = self._make_request(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/botocore/client.py", line 682, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/botocore/endpoint.py", line 136, in _send_request
    while self._needs_retry(attempts, operation_model, request_dict,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/botocore/endpoint.py", line 253, in _needs_retry
    responses = self._event_emitter.emit(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/botocore/retryhandler.py", line 250, in __call__
    should_retry = self._should_retry(attempt_number, response,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/botocore/retryhandler.py", line 316, in __call__
    checker_response = checker(attempt_number, response,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/botocore/retryhandler.py", line 222, in __call__
    return self._check_caught_exception(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/botocore/endpoint.py", line 200, in _do_get_response
    http_response = self._send(request)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/botocore/endpoint.py", line 269, in _send
    return self.http_session.send(request)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/botocore/httpsession.py", line 343, in send
    raise EndpointConnectionError(endpoint_url=request.url, error=e)
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://dynamodb.ue-west-2.amazonaws.com/"
```

Can you help me? 
Is it possible to run this script with ue-west-2 region?

**Comment by mattfysh** [comment]
I'm confused... the docs link back to this issue, but the issue is now closed? Will CLI integration be coming, or is the python script it for now?
