### ISSUE TITLE
Unable to change auth rules

### ISSUE THREAD

**Issue by JackWSargent** [aws-amplify/amplify-cli#9818]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

15.14.0

### Amplify CLI Version

7.6.21

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

I had changed the auth rules mode to Cognito User Pools. It was set to API key before.

### Amplify Categories

auth, api

### Amplify Commands

update

### Describe the bug

The bug comes up when I am changing the auth rules mode to Cognito User Pools before being set to using an API key. 

An error occurred during the push operation: authRules.map is not a function

### Expected behavior

The expected behavior is that it would change the auth rules mode without this error arising.

### Reproduction steps

1. Create Auth and use an API key for the authorization mode.
2. Create a graphql database and write the following into the schema:
`type User @model @auth(rules: [{ allow: owner }]) {
id: ID!
} `
3. Run 'amplify update api' 
4. Select GraphQL -> Authorization modes -> Amazon Cognito User Pool -> No

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type User @model @auth(rules: [{ allow: owner }]) {
id: ID!
} 

```

</details>

### Log output

<details>

```
# Put your logs below this line
authRules.map is not a function
TypeError: authRules.map is not a function
    at ModelAuthTransformer.getAuthRulesFromDirective (/Users/jacksargent/.nvm/versions/node/v15.14.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-auth-transformer/src/ModelAuthTransformer.ts:2319:22)
    at ModelAuthTransformer.object (/Users/jacksargent/.nvm/versions/node/v15.14.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-auth-transformer/src/ModelAuthTransformer.ts:359:55)
    at GraphQLTransform.transformObject (/Users/jacksargent/.nvm/versions/node/v15.14.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/GraphQLTransform.ts:345:25)
    at GraphQLTransform.transform (/Users/jacksargent/.nvm/versions/node/v15.14.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/GraphQLTransform.ts:271:18)
    at _buildProject (/Users/jacksargent/.nvm/versions/node/v15.14.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/util/amplifyUtils.ts:92:35)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at ensureMissingStackMappings (/Users/jacksargent/.nvm/versions/node/v15.14.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/util/amplifyUtils.ts:166:23)
    at buildProject (/Users/jacksargent/.nvm/versions/node/v15.14.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/util/amplifyUtils.ts:51:3)
    at transformGraphQLSchema (/Users/jacksargent/.nvm/versions/node/v15.14.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/transform-graphql-schema.ts:534:29)
    at CfnApiArtifactHandler.updateArtifacts (/Users/jacksargent/.nvm/versions/node/v15.14.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-api/src/provider-utils/awscloudformation/cfn-api-artifact-handler.ts:133:7)
    at Object.executeAmplifyCommand (/Users/jacksargent/.nvm/versions/node/v15.14.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-api/src/index.ts:223:5)
    at executePluginModuleCommand (/Users/jacksargent/.nvm/versions/node/v15.14.0/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:178:3)
    at executeCommand (/Users/jacksargent/.nvm/versions/node/v15.14.0/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:30:5)
    at Object.run (/Users/jacksargent/.nvm/versions/node/v15.14.0/lib/node_modules/@aws-amplify/cli/src/index.ts:205:5)

```

</details>

**Comment by josefaidt** [comment]
Hey @JackWSargent :wave: thanks for raising this! Unfortunately I was not able to reproduce using the provided reproduction steps. Did you push before attempting to update the API?

1. `amplify init -y`
2. `amplify add auth` > Default configuration
3. `amplify add api` > accept defaults (with API Key)
4. replace sample schema contents with `type User @model @auth(rules: [{ allow: owner }]) { id: ID! }`
5. `amplify update api` > change primary auth mode to Amazon Cognito User Pool
6. push with `amplify push -y`

**Comment by JackWSargent** [comment]
Yes I pushed after `amplify add api` @josefaidt

**Comment by josefaidt** [comment]
Hey @JackWSargent thank you for clarifying! Unfortunately I was still not able to reproduce, however I've updated the steps in my previous comment to reflect the push in-between changing the schema contents. Can you identify the difference in the steps you took versus what's documented in my comment?

**Comment by JackWSargent** [comment]
@josefaidt Should I try deleting the API and recreating it? I'm not really sure how I can say to reproduce this. I am open to getting on a call as well if that would help in order to show you.

**Comment by josefaidt** [comment]
Hey @JackWSargent before we go through the hassle of deleting and recreating I'd like to understand the root cause a bit further. Is it possible there was an empty or invalid ruleset for an auth rule elsewhere in the schema? Something like:

```graphql
@auth(rules: {})
```

**Comment by JackWSargent** [comment]
@josefaidt There was not. I tried again and now all the sudden it works. I don't what I changed or even if I changed anything.

**Comment by josefaidt** [comment]
Hey @JackWSargent :wave: I was able to reproduce a similar error by modifying my schema mid-push, and with that I will mark this as a bug 🙂 

```
✖ An error occurred when pushing the resources to the cloud
🛑 An error occurred during the push operation: rules is not iterable
```

1. Before pushing we have the following schema
	  ```graphql
	  type Todo @model @auth(rules: [{ allow: owner }]) {
	    name: String!
	    description: String
	  }
	  ```
2. On push, and after the schema compiles successfully, modify the schema to:
	  ```graphql
	  type Todo @model @auth(rules: { allow: owner }) {
	    name: String!
	    description: String
	  }
	  ```
3. Allow the push to finish successfully
4. Attempt to push another change
5. observe error noted above
