### ISSUE TITLE
Cannot deploy Go function  Command failed with exit code 1: go mod tidy -v

### ISSUE THREAD

**Issue by wattanakorn495** [aws-amplify/amplify-cli#9819]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d36sxqv26t5op5

### Region

ap-southeast-1

### Amplify Console feature

Backend builds, Build settings, Custom builds

### Describe the bug

Everything work find when deploy with amplify push cmd
but I got this error in CI/CD 

```
2022-02-02T07:47:04.158Z [WARNING]: go: downloading github.com/aws/aws-lambda-go v1.24.0
                                    go: downloading github.com/awslabs/aws-lambda-go-api-proxy v0.10.0
2022-02-02T07:47:04.159Z [WARNING]: go: downloading github.com/machinebox/graphql v0.2.2
                                    go: downloading github.com/labstack/echo/v4 v4.1.17
2022-02-02T07:47:04.294Z [WARNING]: go: downloading github.com/pkg/errors v0.8.1
2022-02-02T07:47:04.356Z [WARNING]: go: downloading github.com/labstack/gommon v0.3.0
2022-02-02T07:47:04.482Z [WARNING]: go: downloading github.com/stretchr/testify v1.6.1
2022-02-02T07:47:04.515Z [WARNING]: go: downloading github.com/valyala/fasttemplate v1.2.1
2022-02-02T07:47:04.534Z [WARNING]: go: downloading github.com/mattn/go-isatty v0.0.12
2022-02-02T07:47:04.616Z [WARNING]: go: downloading golang.org/x/net v0.0.0-20200822124328-c89045814202
2022-02-02T07:47:04.621Z [WARNING]: go: downloading github.com/onsi/gomega v1.10.1
2022-02-02T07:47:04.629Z [WARNING]: go: downloading github.com/pmezard/go-difflib v1.0.0
2022-02-02T07:47:04.780Z [WARNING]: go: downloading github.com/mattn/go-colorable v0.1.8
2022-02-02T07:47:04.801Z [WARNING]: go: downloading golang.org/x/crypto v0.0.0-20200820211705-5c72a883971a
2022-02-02T07:47:04.834Z [WARNING]: go: downloading github.com/onsi/ginkgo v1.14.0
2022-02-02T07:47:04.876Z [WARNING]: go: downloading github.com/matryer/is v1.4.0
2022-02-02T07:47:04.899Z [WARNING]: go: downloading golang.org/x/sys v0.0.0-20201016160150-f659759dc4ca
2022-02-02T07:47:04.903Z [WARNING]: go: downloading gopkg.in/yaml.v3 v3.0.0-20200615113413-eeeca48fe776
2022-02-02T07:47:04.925Z [WARNING]: go: downloading github.com/valyala/bytebufferpool v1.0.0
2022-02-02T07:47:04.933Z [WARNING]: go: downloading github.com/davecgh/go-spew v1.1.1
2022-02-02T07:47:04.972Z [WARNING]: go: downloading golang.org/x/text v0.3.3
2022-02-02T07:47:05.007Z [WARNING]: go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
2022-02-02T07:47:05.045Z [WARNING]: go: downloading github.com/nxadm/tail v1.4.4
2022-02-02T07:47:05.074Z [WARNING]: go: downloading gopkg.in/yaml.v2 v2.3.0
2022-02-02T07:47:05.076Z [WARNING]: go: downloading gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
2022-02-02T07:47:05.082Z [WARNING]: go: downloading gopkg.in/check.v1 v1.0.0-20190902080502-41f04d3bba15
2022-02-02T07:47:05.097Z [WARNING]: go: downloading github.com/kr/pretty v0.1.0
2022-02-02T07:47:05.101Z [WARNING]: go: downloading golang.org/x/xerrors v0.0.0-20191204190536-9bdfabe68543
2022-02-02T07:47:05.248Z [WARNING]: go: downloading github.com/fsnotify/fsnotify v1.4.9
2022-02-02T07:47:05.291Z [WARNING]: go: downloading github.com/golang/protobuf v1.4.2
2022-02-02T07:47:05.329Z [WARNING]: go: downloading github.com/kr/text v0.1.0
2022-02-02T07:47:05.339Z [WARNING]: go: downloading google.golang.org/protobuf v1.25.0
2022-02-02T07:47:05.570Z [WARNING]: go: downloading github.com/google/go-cmp v0.5.0
2022-02-02T07:47:15.398Z [WARNING]: go: downloading github.com/aws/aws-sdk-go v1.39.5
2022-02-02T07:47:15.413Z [WARNING]: go: downloading github.com/gocarina/gocsv v0.0.0-20210516172204-ca9e8a8ddea8
2022-02-02T07:47:15.423Z [WARNING]: go: downloading github.com/pkg/errors v0.9.1
2022-02-02T07:47:15.428Z [WARNING]: go: downloading gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405
2022-02-02T07:47:20.143Z [WARNING]: go: downloading github.com/jmespath/go-jmespath v0.4.0
2022-02-02T07:47:20.147Z [WARNING]: go: downloading golang.org/x/net v0.0.0-20210614182718-04defd469f4e
2022-02-02T07:47:20.229Z [WARNING]: go: downloading github.com/jmespath/go-jmespath/internal/testify v1.5.1
2022-02-02T07:47:20.253Z [WARNING]: go: downloading gopkg.in/yaml.v2 v2.2.8
2022-02-02T07:47:20.345Z [WARNING]: go: downloading golang.org/x/text v0.3.6
2022-02-02T07:47:26.807Z [WARNING]: go: downloading github.com/aws/aws-lambda-go v1.25.0
2022-02-02T07:47:26.810Z [WARNING]: go: downloading github.com/aws/aws-sdk-go v1.40.2
2022-02-02T07:47:26.810Z [WARNING]: go: downloading github.com/labstack/echo/v4 v4.4.0
2022-02-02T07:47:26.856Z [WARNING]: go: downloading golang.org/x/sys v0.0.0-20210423082822-04245dca01da
2022-02-02T07:47:26.876Z [WARNING]: go: downloading golang.org/x/crypto v0.0.0-20210322153248-0c34fe9e7dc2
2022-02-02T07:47:26.877Z [WARNING]: go: downloading golang.org/x/time v0.0.0-20201208040808-7e3f01d25324
2022-02-02T07:47:30.167Z [WARNING]: lambda imports
                                    github.com/labstack/echo/v4/middleware tested by
                                    github.com/labstack/echo/v4/middleware.test imports
                                    io/fs: package io/fs is not in GOROOT (/root/.goenv/versions/1.14.12/src/io/fs)
                                    lambda imports
                                    github.com/labstack/echo/v4/middleware tested by
                                    github.com/labstack/echo/v4/middleware.test imports
                                    testing/fstest: package testing/fstest is not in GOROOT (/root/.goenv/versions/1.14.12/src/testing/fstest)
2022-02-02T07:47:30.587Z [WARNING]: go: downloading github.com/lithammer/shortuuid/v3 v3.0.7
2022-02-02T07:47:30.865Z [WARNING]: go: downloading github.com/google/uuid v1.2.0
2022-02-02T07:47:39.348Z [WARNING]: go: downloading github.com/awslabs/aws-lambda-go-api-proxy v0.11.0
2022-02-02T07:47:39.351Z [WARNING]: go: downloading github.com/eclipse/paho.mqtt.golang v1.3.5
2022-02-02T07:47:39.356Z [WARNING]: go: downloading golang.org/x/net v0.0.0-20210405180319-a5a99cb37ef4
2022-02-02T07:47:39.372Z [WARNING]: go: downloading golang.org/x/sys v0.0.0-20210403161142-5e06dd20ab57
2022-02-02T07:47:39.442Z [WARNING]: go: downloading github.com/gorilla/websocket v1.4.2
2022-02-02T07:47:39.911Z [WARNING]: lambda imports
                                    github.com/labstack/echo/v4/middleware tested by
                                    github.com/labstack/echo/v4/middleware.test imports
                                    io/fs: package io/fs is not in GOROOT (/root/.goenv/versions/1.14.12/src/io/fs)
                                    lambda imports
                                    github.com/labstack/echo/v4/middleware tested by
                                    github.com/labstack/echo/v4/middleware.test imports
                                    testing/fstest: package testing/fstest is not in GOROOT (/root/.goenv/versions/1.14.12/src/testing/fstest)
2022-02-02T07:47:49.282Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
2022-02-02T07:47:49.311Z [WARNING]: ✖ There was an error initializing your environment.
2022-02-02T07:47:49.321Z [INFO]: [0mError: Command failed with exit code 1: go mod tidy -v[0m
                                 [0m    at makeError (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/execa/lib/error.js:60:11)[0m
                                 [0m    at Function.module.exports.sync (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/execa/index.js:194:17)[0m
                                 [0m    at executeCommand (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-go-function-runtime-provider/src/runtime.ts:31:24)[0m
                                 [0m    at Object.buildResource [as build] (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-go-function-runtime-provider/src/runtime.ts:98:19)[0m
                                 [0m    at buildFunction (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/provider-utils/awscloudformation/utils/buildFunction.ts:41:36)[0m
                                 [0m    at prepareResource (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/push-resources.ts:605:33)[0m
                                 [0m    at async Promise.all (index 4)[0m
                                 [0m    at prepareBuildableResources (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/push-resources.ts:601:10)[0m
                                 [0m    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/push-resources.ts:173:5) {[0m
                                 [0m  shortMessage: 'Command failed with exit code 1: go mod tidy -v',[0m
                                 [0m  command: 'go mod tidy -v',[0m
                                 [0m  escapedCommand: 'go mod tidy -v',[0m
                                 [0m  exitCode: 1,[0m
                                 [0m  signal: undefined,[0m
                                 [0m  signalDescription: undefined,[0m
                                 [0m  stdout: undefined,[0m
                                 [0m  stderr: undefined,[0m
                                 [0m  failed: true,[0m
                                 [0m  timedOut: false,[0m
                                 [0m  isCanceled: false,[0m
                                 [0m  killed: false[0m
                                 [0m}[0m
2022-02-02T07:47:49.366Z [ERROR]: !!! Build failed
2022-02-02T07:47:49.366Z [ERROR]: !!! Non-Zero Exit Code detected
2022-02-02T07:47:49.366Z [INFO]: # Starting environment caching...
2022-02-02T07:47:49.367Z [INFO]: # Uploading environment cache artifact...
2022-02-02T07:47:49.424Z [INFO]: # Environment caching completed
Terminating logging...
```

### Expected behavior

build success

### Reproduction steps

git push

### Build Settings

```yaml
version: 1
backend:
  phases:
    preBuild:
      commands:
        # - yum install golang -y
        # - go version
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  #cache:
  #  paths:
  #    - node_modules/**/*
```

### Additional information
Using custom image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
_No response_

**Comment by josefaidt** [comment]
Hey @wattanakorn495 :wave: thanks for raising this! Are you able to install this function's dependencies locally? Or are you able to mock the function locally?

**Comment by josefaidt** [comment]
Closing due to inactivity. @wattanakorn495 if you are still experiencing this issue please reply back to this thread and we can re-open to investigate further 🙂
