### ISSUE TITLE
Cannot init or env add with new account

### ISSUE THREAD

**Issue by nunesky** [aws-amplify/amplify-cli#9831]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

7.6.21

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

Not applicable

### Amplify Commands

env, init

### Describe the bug

I'm trying to deploy amplify on a second AWS account, but when I try to add the new environment (be it with `amplify init` or `amplify env add`, I get the following error:

TypeError: Cannot read properties of undefined (reading 'Region')
    at Object.init (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/amplify-service-manager.js:77:47)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/initializer.ts:45:71)

I confirm:
- I'm using Amplify's most current version
- My second account has been correctly configured with `amplify configure`

### Expected behavior

Amplify should add a new enviroment on a new account

### Reproduction steps

1. amplify env add
2. Enter a name for the environment **prod**
3.Select the authentication method you want to use: **AWS profile**
4. Please choose the profile you want to use **profile-name**

And then it breaks

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line
TypeError: Cannot read properties of undefined (reading 'Region')
    at Object.init (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/amplify-service-manager.js:77:47)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/initializer.ts:45:71)

```

</details>

**Comment by sundersc** [comment]
@nunesky - Could you check whether the `team-provider-info.json` file contains a valid value for the `Region`.

> `currentEnv` > `awscloudformation` > `Region`.

**Comment by nunesky** [comment]
Thanks, @sundersc. My team-provider-info.json contains 2 environments. One of them seems to be "more complete" than the other:

```json
{
    "develop": {
      "awscloudformation": {
        "AuthRoleName": "redacted",
        "UnauthRoleArn": "redacted",
        "AuthRoleArn": "redacted",
        "Region": "eu-west-1",
        "DeploymentBucketName": "redacted",
        "UnauthRoleName": "redacted",
        "StackName": "redacted",
        "StackId": "redacted",
        "AmplifyAppId": "redacted",
        "AuthTriggerTemplateURL": "redacted"
      },
      "categories": {
        "auth": {
          "redacted": {},
          "userPoolGroups": {}
        },
        "function": {
          "redactedPreSignup": {
            "deploymentBucketName": "redacted",
            "s3Key": "redacted"
          },
          "redactedrestapi": {
            "deploymentBucketName": "redacted",
            "s3Key": "redacted",
            "rdsHostname": "redacted"
          }
        },
        "hosting": {
          "amplifyhosting": {
            "appId": "redacted",
            "type": "redacted"
          }
        }
      }
    },
    "staging": {
      "categories": {
        "function": {
          "redactedrestapi": {
            "rdsHostname": "redacted"
          }
        }
      }
    }
  }
```

**Comment by sundersc** [comment]
Though it is possible to have different configuration in amplify environments, at some point this needs to merged and deployed. 

Based on your team-provider-info.json file, it looks like `develop` environment is the healthy one. You can either switch to this environment (or) `amplify pull --appId <AppId> --envName develop`, then try to init or add a new environment.

**Comment by nunesky** [comment]
Thank you. It only worked when I deleted the staging environment from team-provider-info, though. 
Is there a way to regenerate  team-provider-info so I can get a healthy staging blob for the deployed staging environment?
Thanks :)

**Comment by sundersc** [comment]
`amplify env checkout staging` should do that. In case if that doesn't work, run `amplify pull` then execute the env checkout command.

**Comment by josefaidt** [comment]
Closing due to inactivity. @nunesky if you are still experiencing this issue please reply back to this thread and we can re-open to investigate further 🙂
