### ISSUE TITLE
addUserToGroup intermittently returns UserNotFoundException 

### ISSUE THREAD

**Issue by GeorgeBellTMH** [aws-amplify/amplify-cli#9869]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

latest

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

auth, function, api

### Amplify Commands

Not applicable

### Describe the bug

When running /addUserToGroup in a loop as part of admin queries from lambda, I am getting intermittent UserNotFoundException even though previously it was successful in the same loop (with same user)...

```
2022-02-28T02:50:45.315Z	8402c4f3-8142-4fc0-9ccf-140183b3ca55	INFO	Attempting to add d774d244-7423-42d4-a1e7-7a5acafcee33 to productMarkBaker
2022-02-28T02:50:45.512Z	8402c4f3-8142-4fc0-9ccf-140183b3ca55	INFO	Success adding d774d244-7423-42d4-a1e7-7a5acafcee33 to productMarkBaker


2022-02-28T02:50:51.063Z	6a87ee54-d247-4b5e-bbc7-66153153e2f7	INFO	Attempting to add d774d244-7423-42d4-a1e7-7a5acafcee33 to subscriptionValid
2022-02-28T02:50:51.208Z	6a87ee54-d247-4b5e-bbc7-66153153e2f7	INFO	UserNotFoundException: User does not exist.
    at Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'UserNotFoundException',
  time: 2022-02-28T02:50:51.207Z,
  requestId: '05a359b8-08da-41b0-b159-ac388ac90b2e',
  statusCode: 400,
  retryable: false,
  retryDelay: 59.60987418809198
}
```

### Expected behavior

User should be added to the group

### Reproduction steps

1. Create a lambda/cognito with multiple groups 
2. Create a user
3. From lambda try to add user to all groups in a loop...

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
Hey @GeorgeBellTMH :wave: thanks for raising this! Can you confirm there is a valid Cognito User Pool ID in the `addUserToGroup` function? If so, this may be an SDK issue or related to Cognito. For reference, https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminAddUserToGroup.html#API_AdminAddUserToGroup_Errors

**Comment by GeorgeBellTMH** [comment]
Yes, the userPoolID was there (confirmed with a console.log)...I resolved the issue by reverting the package/package-lock to use a previous set of dependencies...

**Comment by ykethan** [comment]
Hello @GeorgeBellTMH, glad to hear that the issues was mitigated. Following up to see if you are experiencing any issues with this.

**Comment by ykethan** [comment]
closing the issue due to inactivity, please feel free in reaching out to us again.
