### ISSUE TITLE
amplify add storage: folder and files not created 

### ISSUE THREAD

**Issue by Emillos** [aws-amplify/amplify-cli#988]
** Which Category is your question related to? **
amplify add storage

** Provide additional details e.g. code snippets **
While attempting to add Storage and then doing amplify push - it failed and performed a rollback. 
I fixed a few a things, and went to try again - and the following happens:

**from the CLI**

```
$ amplify add storage
? Please select from one of the below mentioned services Content (Images, audio, video, etc.)
Amazon S3 storage was already added to your project.
$ amplify push

Current Environment: master

| Category | Resource name   | Operation | Provider plugin   |
| -------- | --------------- | --------- | ----------------- |
| Storage  | rocketandart    | Create    | awscloudformation |
| Api      | r0ck3t          | Update    | awscloudformation |
| Auth     | cognito130c7752 | No Change | awscloudformation |

? Are you sure you want to continue? Yes

ENOENT: no such file or directory, scandir '/Users/filtenborg/tjalfe/r0k3t/amplify/backend/storage/rocketandart'
```

I haven't touched any files in  /amplify/backend/ folders

How do i proceed from here?
- Should i manually remove the relation somewhere?
- Should i manually add it to '/amplify/backend/storage/rocketandart/ ?
- Can i remove storage and then add it again?

Im not sure how to go about this.

Thanks in advance
Filtenborg

**Comment by UnleashedMind** [comment]
What did you manually fix? 
Yes, you can try to remove storage and try again.

**Comment by Emillos** [comment]
Thank you for replying :)

The fixes I did was in the schema.graphql, I don't think they are related to this.

Anyway when I attempt to remove storage i get an error.
```
$ amplify remove storage
? Choose the resource you would want to remove rocketandart
? Are you sure you want to delete the resource? This action deletes all files related to this resource from the backend directory. Yes
TypeError: Cannot read property 'rocketandart' of undefined
    at updateBackendConfigAfterResourceRemove (/usr/local/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/update-backend-config.js:39:30)
    at context.amplify.confirmPrompt.run.then (/usr/local/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/remove-resource.js:67:13)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
An error occurred when removing the resources from the local directory
```
Any idea how i can fix this?

Kind regards 
Filtenborg

**Comment by UnleashedMind** [comment]
Please follow these steps to restore your local amplify directory

1. **Very important**, backup your entire project, so if things don't go smoothly, you can try again. 
2. update your cli to the latest version. `npm install -g @aws-amplify/cli@latest`
3. In the backend folder, remove this subfolder if it exists: `/Users/filtenborg/tjalfe/r0k3t/amplify/backend/storage/`
4. In the backend folder, update the amplify-meta.json file by removing the entire 'storage' property if it exists.
5. In the backend folder, update the backend-config.json file by removing the entire 'storage' property if it exists.

After the above steps. 
1. run `amplify -v` and tell us what your cli version is.
2. add the storage using the normal workflow and then push.

**Comment by Emillos** [comment]
Right, so i updated my version to the latest and i'm now on @aws-amplify/cli@1.1.7

I didn't have any references to the storage module in any of the folder you mentioned, so i suppose that 'amplify remove storage' did its thing despite the error.

I successfully added the storage component again.

However when I do amplify push as prompted - it seems to attempt to create an already existing Dynamodb resource thus failing, and in turn performs a rollback.

```
$ amplify push

Current Environment: master

| Category | Resource name   | Operation | Provider plugin   |
| -------- | --------------- | --------- | ----------------- |
| Storage  | art             | Create    | awscloudformation |
| Auth     | cognito130c7752 | Update    | awscloudformation |
| Api      | r0ck3t          | Update    | awscloudformation |
? Are you sure you want to continue? Yes
? The CLI is going to take the following actions during the migration step:

1. If you have a GraphQL API, we will update the corresponding Cloudformation stack to support larger annotated schemas and custom resolvers.
In this process, we will be making Cloudformation API calls to update your GraphQL API Cloudformation stack. This operation will result in deletion of your AppSync resolvers and then the creation of new ones and for a brief while your AppSync API will be unavailable until the migration finishes

2. We will be updating your local Cloudformation files present inside the ‘amplify/‘ directory of your app project, for the GraphQL API service

3. If for any reason the migration fails, the CLI will rollback your cloud and local changes and you can take a look at https://aws-amplify.github.io/docs/cli/migrate?sdk=js for manually migrating your project so that it’s compatible with the latest version of the CLI

4. ALL THE ABOVE MENTIONED OPERATIONS WILL NOT DELETE ANY DATA FROM ANY OF YOUR DATA STORES

Before the migration, please be aware of the following things:

1. Make sure to have an internet connection through the migration process

2. Make sure to not exit/terminate the migration process (by interrupting it explicitly in the middle of migration), as this will lead to inconsistency within your project

3. Make sure to take a backup of your entire project (including the amplify related config files)

Do you want to continue?
 Yes

Migrating your API. This may take a few minutes.
⠋ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS r0ck3t-20190103131644 AWS::CloudFormation::Stack Mon Mar 11 2019 10:06:50 GMT+0100 (CET) User Initiated
⠏ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS authcognito130c7752 AWS::CloudFormation::Stack Mon Mar 11 2019 10:06:56 GMT+0100 (CET)
⠋ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE    authcognito130c7752 AWS::CloudFormation::Stack Mon Mar 11 2019 10:06:56 GMT+0100 (CET)
UPDATE_IN_PROGRESS apir0ck3t           AWS::CloudFormation::Stack Mon Mar 11 2019 10:07:00 GMT+0100 (CET)
⠏ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS r0ck3t-20190103131644-apir0ck3t-R59XZQU8F6UK AWS::CloudFormation::Stack Mon Mar 11 2019 10:07:01 GMT+0100 (CET) User Initiated
⠏ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS ElasticSearchDomain AWS::Elasticsearch::Domain  Mon Mar 11 2019 10:07:09 GMT+0100 (CET)
CREATE_IN_PROGRESS ChangelogTable      AWS::DynamoDB::Table        Mon Mar 11 2019 10:07:10 GMT+0100 (CET)
CREATE_FAILED      ChangelogTable      AWS::DynamoDB::Table        Mon Mar 11 2019 10:07:10 GMT+0100 (CET) Changelog-qotsqvvhtvfrzmmtmxzq7tvrl4-master already exists in stack arn:aws:cloudformation:(removed arn)
UPDATE_FAILED      GraphQLSchema       AWS::AppSync::GraphQLSchema Mon Mar 11 2019 10:07:10 GMT+0100 (CET) Resource update cancelled
UPDATE_FAILED      GraphQLAPIKey       AWS::AppSync::ApiKey        Mon Mar 11 2019 10:07:10 GMT+0100 (CET) Resource update cancelled
UPDATE_FAILED      ElasticSearchDomain AWS::Elasticsearch::Domain  Mon Mar 11 2019 10:07:11 GMT+0100 (CET) Resource update cancelled
⠹ Updating resources in the cloud. This may take a few minutes...

UPDATE_ROLLBACK_IN_PROGRESS r0ck3t-20190103131644-apir0ck3t-R59XZQU8F6UK AWS::CloudFormation::Stack Mon Mar 11 2019 10:07:12 GMT+0100 (CET) The following resource(s) failed to create: [ChangelogTable]. The following resource(s) failed to update: [GraphQLAPIKey, ElasticSearchDomain, GraphQLSchema].
⠸ Updating resources in the cloud. This may take a few minutes...

UPDATE_FAILED               apir0ck3t             AWS::CloudFormation::Stack Mon Mar 11 2019 10:07:23 GMT+0100 (CET) Embedded stack arn:aws:cloudformation:(removed arn) was not successfully updated. Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: The following resource(s) failed to create: [ChangelogTable]. The following resource(s) failed to update: [GraphQLAPIKey, ElasticSearchDomain, GraphQLSchema].
UPDATE_ROLLBACK_IN_PROGRESS r0ck3t-20190103131644 AWS::CloudFormation::Stack Mon Mar 11 2019 10:07:24 GMT+0100 (CET) The following resource(s) failed to update: [apir0ck3t].
⠸ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS authcognito130c7752 AWS::CloudFormation::Stack Mon Mar 11 2019 10:07:41 GMT+0100 (CET)
⠴ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE    authcognito130c7752 AWS::CloudFormation::Stack Mon Mar 11 2019 10:07:41 GMT+0100 (CET)
UPDATE_IN_PROGRESS apir0ck3t           AWS::CloudFormation::Stack Mon Mar 11 2019 10:07:42 GMT+0100 (CET)
⠹ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS ElasticSearchDomain AWS::Elasticsearch::Domain  Mon Mar 11 2019 10:08:11 GMT+0100 (CET)
UPDATE_COMPLETE    GraphQLAPIKey       AWS::AppSync::ApiKey        Mon Mar 11 2019 10:08:11 GMT+0100 (CET)
UPDATE_COMPLETE    GraphQLSchema       AWS::AppSync::GraphQLSchema Mon Mar 11 2019 10:08:11 GMT+0100 (CET)
⠇ Updating resources in the cloud. This may take a few minutes...
```

And then it hangs forever.
How come it attempts to recreate this, and how can i prevent it from doing so?

Kind regards
Filtenborg

**Comment by kaustavghosh06** [comment]
@Emillos You might want to delete the "Changelog-qotsqvvhtvfrzmmtmxzq7tvrl4-master" table from the AWS console and try this again. Cloudformation errors out if it sees an already existing table with the same name when deploying a new stack.

**Comment by Emillos** [comment]
I 'solved it' by doing a `amplify env pull --restore` and then redoing the changes I needed in schema.grphql - for some reason it appears as if I got out of sync.
Thanks to all for taking your time to reply :)
