### ISSUE TITLE
amplify auth add fails with Error: Found ']' where a key name was expected (check your syntax or use quotes if the key name includes {}[],: or whitespace) at line 21,3 >>>

### ISSUE THREAD

**Issue by thgibbs** [aws-amplify/amplify-cli#9917]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

7.6.22

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

auth

### Amplify Commands

add

### Describe the bug

I have a project that I deleted all the amplify code from (using amplify delete) and now I'm trying to recreate it (via amplify init and then amplify add auth).  The amplify add auth fails (other commands such as amplify add api succeed).

Running amplify add auth results in

amplify add auth
Using service: Cognito, provided by: awscloudformation
 
 The current configured provider is Amazon Cognito. 
 
 Do you want to use the default authentication and security configuration? Default configuration
 Warning: you will not be able to edit these selections. 
 How do you want users to be able to sign in? Email
 Do you want to configure advanced settings? No, I am done.
Found ']' where a key name was expected (check your syntax or use quotes if the key name includes {}[],: or whitespace) at line 21,3 >>>  ]
}
 ...
Error: Found ']' where a key name was expected (check your syntax or use quotes if the key name includes {}[],: or whitespace) at line 21,3 >>>  ]
}
 ...
    at error (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:41:11)
    at keyname (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:163:9)
    at object (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:353:15)
    at value (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:391:24)
    at array (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:304:20)
    at value (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:392:24)
    at object (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:358:23)
    at legacyRootValue (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:428:38)
    at Object.module.exports (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:454:23)
    at Function.JSONUtilities.parse (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/jsonUtilities.js:91:22)
    at Function.JSONUtilities.readJson (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/jsonUtilities.js:47:32)
    at StateManager.getDeploymentSecrets (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/state-manager/stateManager.js:60:51)
    at AmplifyToolkit.saveEnvResourceParameters [as _saveEnvResourceParameters] (/usr/local/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/envResourceParams.js:74:67)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/lib/provider-utils/awscloudformation/handlers/resource-handlers.js:38:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/lib/index.js:336:5)
    at async executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:164:5)
    at async executeCommand (/usr/local/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:35:9)
    at async Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/lib/index.js:162:9)

### Expected behavior

amplify add auth should add the new cognito user pool.

### Reproduction steps

amplify init
amplify add auth
causes the issue even in an empty directory.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

Found ']' where a key name was expected (check your syntax or use quotes if the key name includes {}[],: or whitespace) at line 21,3 >>>  ]
}
 ...
Error: Found ']' where a key name was expected (check your syntax or use quotes if the key name includes {}[],: or whitespace) at line 21,3 >>>  ]
}
 ...
    at error (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:41:11)
    at keyname (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:163:9)
    at object (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:353:15)
    at value (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:391:24)
    at array (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:304:20)
    at value (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:392:24)
    at object (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:358:23)
    at legacyRootValue (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:428:38)
    at Object.module.exports (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:454:23)
    at Function.JSONUtilities.parse (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/jsonUtilities.js:91:22)
    at Function.JSONUtilities.readJson (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/jsonUtilities.js:47:32)
    at StateManager.getDeploymentSecrets (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/state-manager/stateManager.js:60:51)
    at AmplifyToolkit.saveEnvResourceParameters [as _saveEnvResourceParameters] (/usr/local/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/envResourceParams.js:74:67)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/lib/provider-utils/awscloudformation/handlers/resource-handlers.js:38:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/lib/index.js:336:5)
    at async executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:164:5)
    at async executeCommand (/usr/local/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:35:9)
    at async Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/lib/index.js:162:9)

```
# Put your logs below this line


```

</details>

**Comment by thgibbs** [comment]
This was caused by an issue with .aws/amplify/deployment-secrets.json being outdated or corrupt.  I deleted the file and it worked.
