### ISSUE TITLE
We've fixed this issue (tied to amplify delete) in he latest version of the CLI. Please feel free to re-open this if you're still seeing this issue.

### ISSUE THREAD

**Issue by vedanthpadigelwar** [aws-amplify/amplify-cli#9951]
I am facing the same issue again in latest aws cli version 7.6.23

We've fixed this issue (tied to amplify delete) in he latest version of the CLI. Please feel free to re-open this if you're still seeing this issue.

_Originally posted by @kaustavghosh06 in https://github.com/aws-amplify/amplify-cli/issues/1323#issuecomment-491430783_

× There was an error initializing your environment.
Unexpected token 'export'
C:\Users\vedan\Documents\Quidich\qt-histo\qt_history_frontend\src\aws-exports.js:36
export default awsmobile;
^^^^^^

SyntaxError: Unexpected token 'export'
    at compileFunction (<anonymous>)
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at getCurrentAWSExports (C:\Users\vedan\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-frontend-javascript\lib\frontend-config-creator.js:281:18)
    at getAWSExports (C:\Users\vedan\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-frontend-javascript\lib\frontend-config-creator.js:146:35)
    at createAWSExports (C:\Users\vedan\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-frontend-javascript\lib\frontend-config-creator.js:138:31)
    at Object.createFrontendConfigs (C:\Users\vedan\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-frontend-javascript\index.js:47:16)
    at AmplifyToolkit.onCategoryOutputsChange [as _onCategoryOutputsChange] (C:\Users\vedan\AppData\Roaming\npm\node_modules\@aws-amplify\cli\src\extensions\amplify-helpers\on-category-outputs-change.ts:21:33)
    at initializeEnv (C:\Users\vedan\AppData\Roaming\npm\node_modules\@aws-amplify\cli\src\initialize-env.ts:103:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at pullBackend (C:\Users\vedan\AppData\Roaming\npm\node_modules\@aws-amplify\cli\src\pull-backend.ts:33:3)
    at Object.run (C:\Users\vedan\AppData\Roaming\npm\node_modules\@aws-amplify\cli\src\commands\pull.ts:60:7)
    at Object.executeAmplifyCommand (C:\Users\vedan\AppData\Roaming\npm\node_modules\@aws-amplify\cli\src\index.ts:373:5)
    at executePluginModuleCommand (C:\Users\vedan\AppData\Roaming\npm\node_modules\@aws-amplify\cli\src\execution-manager.ts:178:3)   
    at executeCommand (C:\Users\vedan\AppData\Roaming\npm\node_modules\@aws-amplify\cli\src\execution-manager.ts:30:5)
    at Object.run (C:\Users\vedan\AppData\Roaming\npm\node_modules\@aws-amplify\cli\src\index.ts:205:5)

**Comment by josefaidt** [comment]
Hey @vedanthpadigelwar :wave: thanks for raising this! Would you mind porting this over to our [bug report template](https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=&template=1.bug_report.yaml)? This will help us gather additional context around your issue and better identify the root cause. From the error message this appears to be an issue with the frontend build?

**Comment by heyheman11** [comment]
Hey, this is also happening to our team. We have 3 applications sharing a backend, but strangely only one of the projects are failing the backend build with this same error message .... 

I'm happy to create a bug report for this as well

**Comment by josefaidt** [comment]
Hey @heyheman11 yes please create a new bug report with the context for your occurrence

**Comment by josefaidt** [comment]
Closing due to inactivity
