### ISSUE TITLE
amplify mockup through error `s3-cloudformation-template.json` does not exist when use dynamoDb and S3 storage in same project

### ISSUE THREAD

**Issue by ducxinh201** [aws-amplify/amplify-cli#9972]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

v16.13.1

### Amplify CLI Version

4.52.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Not

### Amplify Categories

storage

### Amplify Commands

Not applicable

### Describe the bug

I got following error when run command amplify mock storage
```
amplify/backend/storage/postsDB/s3-cloudformation-template.json' does not exist
amplify-cli-core/src/jsonUtilities.ts:25:15
amplify-util-mock/src/storage/storage.ts:68:43
amplify-storage-simulator/src/server/S3server.ts:87:12
amplify-storage-simulator/src/server/S3server.ts:238:12
```

### Expected behavior

File uploaded success and I can get that file

### Reproduction steps

I'm using following services
```
Current Environment: dev

| Category | Resource name                | Operation | Provider plugin   |
| -------- | ---------------------------- | --------- | ----------------- |
| Storage  | postsDB                             | No Change | awscloudformation |
| Storage  | postImages                       | No Change | awscloudformation |
| Function | postFunction                    | No Change | awscloudformation |
| Function | helloWorldFunc                | No Change | awscloudformation |
| Api          | blogRestApi                       | No Change | awscloudformation |
| Auth       | tutorialamplifyreactaf90dab7 | No Change | awscloudformation |

REST API endpoint: {url}/dev
```
The issue related to storage category. I'm using both s3 and DynamoDB
  + S3: postImages 
  + dynamoDB: postsDB
 
When I run: `amplify mock storage` or `amplify mock storage postImages`
Result: Mock Storage endpoint is running at http://localhost:20005

Then my code handle push file to s3 postImages
```bash
const file = event.target.files[0];
const imageInfo = await Storage.put(file.name, file)
```
After the file is pushed It stop mockup running and  through the following error in command line
```
amplify/backend/storage/postsDB/s3-cloudformation-template.json' does not exist
amplify-cli-core/src/jsonUtilities.ts:25:15
amplify-util-mock/src/storage/storage.ts:68:43
amplify-storage-simulator/src/server/S3server.ts:87:12
amplify-storage-simulator/src/server/S3server.ts:238:12
```
```js
// aws-exports.js
const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_dynamodb_all_tables_region": "ap-northeast-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "posts-dev",
            "region": "ap-northeast-1"
        }
    ],
    "aws_user_files_s3_bucket": "undefined-dev",
    "aws_user_files_s3_bucket_region": "ap-northeast-1",
    "aws_user_files_s3_dangerously_connect_to_http_endpoint_for_testing": true,
    "aws_cloud_logic_custom": [
        {
            "name": "blogRestApi",
            "endpoint": "....",
            "region": "ap-northeast-1"
        }
    ],
    "aws_cognito_identity_pool_id": "...",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "",
    "aws_user_pools_web_client_id": "",
    "oauth": {}
};


export default awsmobile;
```

Look like 

### Log output

```
File at path: '/Users/nguyenducxinh/Documents/workspace/aws/amplify/tutorial-amplify-react/amplify/backend/storage/postsDB/s3-cloudformation-template.json' does not exist,     at Function.JSONUtilities.readJson (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/jsonUtilities.ts:25:15),     at StorageServer.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/src/storage/storage.ts:68:43),     at StorageServer.emit (node:events:390:28),     at StorageServer.emit (node:domain:475:12),     at StorageServer.handleRequestPut (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-storage-simulator/src/server/S3server.ts:238:12),     at StorageServer.handleRequestAll (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-storage-simulator/src/server/S3server.ts:87:12),     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/express/lib/router/layer.js:95:5),     at trim_prefix (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/express/lib/router/index.js:317:13),     at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/express/lib/router/index.js:284:7,     at Function.process_params (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/express/lib/router/index.js:335:12),     at next (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/express/lib/router/index.js:275:10),     at serveStatic (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/serve-static/index.js:75:16),     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/express/lib/router/layer.js:95:5),     at trim_prefix (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/express/lib/router/index.js:317:13),     at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/express/lib/router/index.js:284:7,     at Function.process_params (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/express/lib/router/index.js:335:12),     at next (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/express/lib/router/index.js:275:10),     at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/body-parser/lib/read.js:130:5,     at invokeCallback (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/body-parser/node_modules/raw-body/index.js:224:16),     at done (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/body-parser/node_modules/raw-body/index.js:213:7),     at IncomingMessage.onEnd (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/body-parser/node_modules/raw-body/index.js:273:7),     at IncomingMessage.emit (node:events:402:35),     at IncomingMessage.emit (node:domain:475:12),     at endReadableNT (node:internal/streams/readable:1343:12),     at processTicksAndRejections (node:internal/process/task_queues:83:21)]
```

**Comment by ykethan** [comment]
Hello @ducxinh201 , Thank you for reaching out. On replicating in my local environment I was unable to reproduce the issue. I utilized the following steps on creating my amplify application. 

1. `amplify add auth`
2. `amplify push`
3. `amplify add storage`
4. selected Content(s3 storage)
5. `amplify add storage`
6. selected NoSQL Database(dynamoDB)
7. Added the following code in my App.js
```js
const file = e.target.files[0];
    try {
      await Storage.put(file.name, file, {
        contentType: "image/png", // contentType is optional
      });
    } catch (error) {
      console.log("Error uploading file: ", error);
    }
```
```html
<div className="App">
      <input type="file" onChange={onChange} />
    </div>
```

8. opened two CLI's and performed the following commands one in each.
   `amplify mock storage <s3 storage name>`
   `npm start`

On performing this, in my local host I uploaded a image file but did not experience a error.

In order to further dive deeper into the issue, Could you please provide me the Amplify CLI version. We can obtain this by running `amplify -version` in your local CLI.
Please do let me know if there were any additonal steps taken while adding the storage or any other inforamtion that may help us in diving deeper.

**Comment by josefaidt** [comment]
Closing due to inactivity
