### ISSUE TITLE
Error: FeatureFlags is not initialized

### ISSUE THREAD

**Issue by multimeric** [aws-amplify/amplify-cli#9987]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

` sudo npm i -g @aws-amplify/cli@latest`

### If applicable, what version of Node.js are you using?

`v16.14.0`

### Amplify CLI Version

7.6.24

### What operating system are you using?

Ubuntu 21.04

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

Not applicable

### Amplify Commands

init

### Describe the bug

When I run and amplify command, I get the error: `Error: FeatureFlags is not initialized`

### Expected behavior

I expect these commands to work as usual.

### Reproduction steps

1. `sudo npm i -g @aws-amplify/cli@latest`
2. `cd $(mktemp -d)` (go into a temporary directory)
3. `amplify init`

The logs below will then be output.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line
$ amplify init
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the project tmp8GuVX05LUj
The following configuration will be applied:

Project information
| Name: tmp8GuVX05LUj
| Environment: dev
| Default editor: Visual Studio Code
| App type: javascript
| Javascript framework: none
| Source Directory Path: src
| Distribution Directory Path: dist
| Build Command: npm run-script build
| Start Command: npm run-script start

? Initialize the project with the above configuration? Yes
Using default provider  awscloudformation
Error: FeatureFlags is not initialized
    at Function.FeatureFlags.ensureInitialized (/usr/lib/node_modules/amplify-provider-awscloudformation/node_modules/amplify-cli-core/src/feature-flags/featureFlags.ts:211:13)
    at Function.FeatureFlags.getNumber (/usr/lib/node_modules/amplify-provider-awscloudformation/node_modules/amplify-cli-core/src/feature-flags/featureFlags.ts:132:18)
    at Object.<anonymous> (/usr/lib/node_modules/amplify-provider-awscloudformation/src/aws-predictions-regions.js:2:45)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/lib/node_modules/amplify-provider-awscloudformation/src/index.ts:18:30)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /usr/lib/node_modules/@aws-amplify/cli/src/init-steps/s2-initProviders.ts:13:28
    at Array.forEach (<anonymous>)
    at initProviders (/usr/lib/node_modules/@aws-amplify/cli/src/init-steps/s2-initProviders.ts:12:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.run (/usr/lib/node_modules/@aws-amplify/cli/src/commands/init.ts:30:7)
    at Object.executeAmplifyCommand (/usr/lib/node_modules/@aws-amplify/cli/src/index.ts:373:5)
    at executePluginModuleCommand (/usr/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:178:3)
    at executeCommand (/usr/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:30:5)
    at Object.run (/usr/lib/node_modules/@aws-amplify/cli/src/index.ts:205:5)


```

</details>

### Additional information

This relates to https://github.com/aws-amplify/amplify-cli/issues/7507 and https://github.com/aws-amplify/amplify-cli/issues/7068, although I am now getting this with *every* `amplify` command.

**Comment by multimeric** [comment]
> Do you also experience this issue when installing the CLI from npm without sudo

I assume you mean a local installation because `npm install -g` without sudo fails for me because I'm on Linux:
```bash
$ npm install -g @aws-amplify/cli@latest
npm WARN ERESOLVE overriding peer dependency
npm ERR! code EACCES
npm ERR! syscall rename
npm ERR! path /usr/lib/node_modules/@aws-amplify/cli
npm ERR! dest /usr/lib/node_modules/@aws-amplify/.cli-Ix9UYkXP
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, rename '/usr/lib/node_modules/@aws-amplify/cli' -> '/usr/lib/node_modules/@aws-amplify/.cli-Ix9UYkXP'
npm ERR!  [Error: EACCES: permission denied, rename '/usr/lib/node_modules/@aws-amplify/cli' -> '/usr/lib/node_modules/@aws-amplify/.cli-Ix9UYkXP'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'rename',
npm ERR!   path: '/usr/lib/node_modules/@aws-amplify/cli',
npm ERR!   dest: '/usr/lib/node_modules/@aws-amplify/.cli-Ix9UYkXP'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/migwell/.npm/_logs/2022-03-15T23_18_25_131Z-debug-0.log
```

When I install it locally I get:

```
$ npm install @aws-amplify/cli
$ npx amplify
The following official plugins are missing or inactive:
    analytics: category | amplify-category-analytics@3.2.23
    function: category | amplify-category-function@3.5.4
    geo: category | amplify-category-geo@2.4.3
    hosting: category | amplify-category-hosting@3.2.23
    hosting: category | amplify-console-hosting@2.2.23
    hosting: category | amplify-container-hosting@2.4.26
    interactions: category | amplify-category-interactions@3.2.23
    notifications: category | amplify-category-notifications@2.19.6
    predictions: category | amplify-category-predictions@3.2.23
    xr: category | amplify-category-xr@3.2.23
    codegen: util | amplify-codegen@2.28.0
    flutter: frontend | amplify-frontend-flutter@1.3.3
    android: frontend | amplify-frontend-android@3.3.3
    ios: frontend | amplify-frontend-ios@3.3.23
    javascript: frontend | amplify-frontend-javascript@3.3.23
    mock: util | amplify-util-mock@4.3.10
The following official plugins have mismatched packages:
Expected:
    awscloudformation: provider | amplify-provider-awscloudformation@5.9.10
Found:
    awscloudformation: provider | amplify-provider-awscloudformation@5.9.7
```

> I'd also be curious if you also experience this issue with the CLI installed via curl

It does work! I wasn't aware of this installation method, but it seems to resolve my issue for the moment! 

```
$ curl -sL https://aws-amplify.github.io/amplify-cli/install | bash && $SHELL


 Installing the AWS Amplify CLI...

 Downloading binary...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   660    0   660    0     0   1382      0 --:--:-- --:--:-- --:--:--  1383
100  196M  100  196M    0     0  9776k      0  0:00:20  0:00:20 --:--:-- 11.0M
 Download complete!
 Extracting binary...
 Extraction complete!

 Added ~/.amplify/bin to fish_user_paths universal variable.
Successfully installed the Amplify CLI.
Run 'amplify help' to get started!
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
$ which amplify
/home/migwell/.amplify/bin/amplify
$ amplify init 
...
```
At this point the rest of the `init` process worked. Up to and including `amplify push`. However I have the issue that I'm not sure how to install custom amplify plugins which I need, because there is no `node_modules` for the  `~/.amplify/bin/amplify` directory that I can find.

**Comment by josefaidt** [comment]
Hey @multimeric I'm glad to hear you're back up and running with Amplify CLI 🙌 to resolve the global npm installation issue please take a look through the [npm doc for resolving EACCESS issues](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally)

**Comment by multimeric** [comment]
The EACCESS error isn't a real issue though, it's just what happens on Linux when you try to run an installation that needs `sudo`, without having `sudo`. I still have a feeling that this `FeatureFlags` error is a bug because amplify used to work fine for me even using a global `sudo` installation.

**Comment by josefaidt** [comment]
Hey @multimeric do you receive a stack trace along with the FeatureFlags issue?

**Comment by multimeric** [comment]
Yep! Have a look at the "Log Output" section in my original post.

**Comment by josefaidt** [comment]
Ah thank you @multimeric for clarifying 🙏 would you be willing to share the `amplify/cli.json` file if it exists in the project? Or is the parent directory an Amplify project by chance?

**Comment by multimeric** [comment]
Well in my above example I'm running `amplify` in an empty directory, so there is nothing that already exists. Not an Amplify project, and not any config files.

**Comment by josefaidt** [comment]
Hey @multimeric to clarify, our current working directory is not a child directory of another Amplify project? Something like:

```
| Documents/
|-  some-amplify-project/
|--   amplify/
|--   my-current-project/   # we are here
|---     src/
```

**Comment by multimeric** [comment]
That is correct. I can reproduce this with a fresh amplify install **inside an empty folder in my temporary directory**:

```bash
$ pwd
/tmp/tmp.Ej3SH7e49s
$ /usr/bin/amplify --version
7.6.25
$ /usr/bin/amplify init
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the project tmpEj3SH7e49s
The following configuration will be applied:

Project information
| Name: tmpEj3SH7e49s
| Environment: dev
| Default editor: Visual Studio Code
| App type: javascript
| Javascript framework: none
| Source Directory Path: src
| Distribution Directory Path: dist
| Build Command: npm run-script build
| Start Command: npm run-script start

? Initialize the project with the above configuration? Yes
Using default provider  awscloudformation
Error: FeatureFlags is not initialized
    at Function.FeatureFlags.ensureInitialized (/usr/lib/node_modules/amplify-provider-awscloudformation/node_modules/amplify-cli-core/src/feature-flags/featureFlags.ts:211:13)
    at Function.FeatureFlags.getNumber (/usr/lib/node_modules/amplify-provider-awscloudformation/node_modules/amplify-cli-core/src/feature-flags/featureFlags.ts:132:18)
    at Object.<anonymous> (/usr/lib/node_modules/amplify-provider-awscloudformation/src/aws-predictions-regions.js:2:45)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/lib/node_modules/amplify-provider-awscloudformation/src/index.ts:18:30)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /usr/lib/node_modules/@aws-amplify/cli/src/init-steps/s2-initProviders.ts:13:28
    at Array.forEach (<anonymous>)
    at initProviders (/usr/lib/node_modules/@aws-amplify/cli/src/init-steps/s2-initProviders.ts:12:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.run (/usr/lib/node_modules/@aws-amplify/cli/src/commands/init.ts:30:7)
    at Object.executeAmplifyCommand (/usr/lib/node_modules/@aws-amplify/cli/src/index.ts:373:5)
    at executePluginModuleCommand (/usr/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:178:3)
    at executeCommand (/usr/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:30:5)
    at Object.run (/usr/lib/node_modules/@aws-amplify/cli/src/index.ts:205:5)

```

**Comment by josefaidt** [comment]
Hey @multimeric thank you for clarifying. The path used in the sample above appears to be using the sudo-installed version, do you also experience this with the version installed with curl (`/home/migwell/.amplify/bin/amplify`)?

**Comment by multimeric** [comment]
No, I don't encounter this issue with the local version. But like I said, I would like the global installation to work, as I want to be able to develop my amplify plugin, and you can't install extra packages into a local install.

**Comment by josefaidt** [comment]
Can you try setting an npm prefix that's local to your user profile (`~/.npm-global`) and re-attempt the global install? How was Node installed?

**Comment by multimeric** [comment]
It still fails if I do this:
```bash
$ mkdir ~/.npm-global
$ NPM_CONFIG_PREFIX=~/.npm-global npm install -g @aws-amplify/cli
added 1703 packages, and audited 1729 packages in 3m
$ cd (mktemp -d)
$ NPM_CONFIG_PREFIX=~/.npm-global ~/.npm-global/bin/amplify init
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the project tmpGLv8Nh9Vv0
The following configuration will be applied:

Project information
| Name: tmpGLv8Nh9Vv0
| Environment: dev
| Default editor: Visual Studio Code
| App type: javascript
| Javascript framework: none
| Source Directory Path: src
| Distribution Directory Path: dist
| Build Command: npm run-script build
| Start Command: npm run-script start

? Initialize the project with the above configuration? Yes
Using default provider  awscloudformation
Error: FeatureFlags is not initialized
    at Function.FeatureFlags.ensureInitialized (/usr/lib/node_modules/amplify-provider-awscloudformation/node_modules/amplify-cli-core/src/feature-flags/featureFlags.ts:211:13)
    at Function.FeatureFlags.getNumber (/usr/lib/node_modules/amplify-provider-awscloudformation/node_modules/amplify-cli-core/src/feature-flags/featureFlags.ts:132:18)
    at Object.<anonymous> (/usr/lib/node_modules/amplify-provider-awscloudformation/src/aws-predictions-regions.js:2:45)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/lib/node_modules/amplify-provider-awscloudformation/src/index.ts:18:30)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /home/migwell/.npm-global/lib/node_modules/@aws-amplify/cli/src/init-steps/s2-initProviders.ts:13:28
    at Array.forEach (<anonymous>)
    at initProviders (/home/migwell/.npm-global/lib/node_modules/@aws-amplify/cli/src/init-steps/s2-initProviders.ts:12:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.run (/home/migwell/.npm-global/lib/node_modules/@aws-amplify/cli/src/commands/init.ts:30:7)
    at Object.executeAmplifyCommand (/home/migwell/.npm-global/lib/node_modules/@aws-amplify/cli/src/index.ts:373:5)
    at executePluginModuleCommand (/home/migwell/.npm-global/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:178:3)
    at executeCommand (/home/migwell/.npm-global/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:30:5)
    at Object.run (/home/migwell/.npm-global/lib/node_modules/@aws-amplify/cli/src/index.ts:205:5)
```

I think I installed node using the Ubuntu PPA ie a binary package install.

**Comment by multimeric** [comment]
Although, weirdly if you look at that call stack, it goes from `.npm-global` to `/usr/lib` at a certain point. Which is weird.

**Comment by multimeric** [comment]
Interestingly, if I uninstall the `/usr/lib` installation, it still fails, I think because I still have some residual amplify libraries installed in /usr/lib`:
```bash
$ sudo npm uninstall -g @aws-amplify/cli 

removed 1728 packages, and audited 1 package in 4s
$ NPM_CONFIG_PREFIX=~/.npm-global ~/.npm-global/bin/amplify init                                                                                     (base) 
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the project tmpGLv8Nh9Vv0
The following configuration will be applied:

Project information
| Name: tmpGLv8Nh9Vv0
| Environment: dev
| Default editor: Visual Studio Code
| App type: javascript
| Javascript framework: none
| Source Directory Path: src
| Distribution Directory Path: dist
| Build Command: npm run-script build
| Start Command: npm run-script start

? Initialize the project with the above configuration? Yes
Using default provider  awscloudformation
Error: FeatureFlags is not initialized
    at Function.FeatureFlags.ensureInitialized (/usr/lib/node_modules/amplify-provider-awscloudformation/node_modules/amplify-cli-core/src/feature-flags/featureFlags.ts:211:13)
    at Function.FeatureFlags.getNumber (/usr/lib/node_modules/amplify-provider-awscloudformation/node_modules/amplify-cli-core/src/feature-flags/featureFlags.ts:132:18)
    at Object.<anonymous> (/usr/lib/node_modules/amplify-provider-awscloudformation/src/aws-predictions-regions.js:2:45)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/lib/node_modules/amplify-provider-awscloudformation/src/index.ts:18:30)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /home/migwell/.npm-global/lib/node_modules/@aws-amplify/cli/src/init-steps/s2-initProviders.ts:13:28
    at Array.forEach (<anonymous>)
    at initProviders (/home/migwell/.npm-global/lib/node_modules/@aws-amplify/cli/src/init-steps/s2-initProviders.ts:12:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.run (/home/migwell/.npm-global/lib/node_modules/@aws-amplify/cli/src/commands/init.ts:30:7)
    at Object.executeAmplifyCommand (/home/migwell/.npm-global/lib/node_modules/@aws-amplify/cli/src/index.ts:373:5)
    at executePluginModuleCommand (/home/migwell/.npm-global/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:178:3)
    at executeCommand (/home/migwell/.npm-global/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:30:5)
    at Object.run (/home/migwell/.npm-global/lib/node_modules/@aws-amplify/cli/src/index.ts:205:5)

```

**Comment by multimeric** [comment]
But then if I delete all the `/usr/lib` amplify libraries, I get this:
```bash
$ npm ls -g --all | grep amplify
$ NPM_CONFIG_PREFIX=~/.npm-global ~/.npm-global/bin/amplify init 
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the project tmpGLv8Nh9Vv0
The following configuration will be applied:

Project information
| Name: tmpGLv8Nh9Vv0
| Environment: dev
| Default editor: Visual Studio Code
| App type: javascript
| Javascript framework: none
| Source Directory Path: src
| Distribution Directory Path: dist
| Build Command: npm run-script build
| Start Command: npm run-script start

? Initialize the project with the above configuration? Yes
Using default provider  awscloudformation
Error: Cannot find module '/usr/lib/node_modules/amplify-provider-awscloudformation'
Require stack:
- /home/migwell/.npm-global/lib/node_modules/@aws-amplify/cli/lib/init-steps/s2-initProviders.js
- /home/migwell/.npm-global/lib/node_modules/@aws-amplify/cli/lib/commands/init.js
- /home/migwell/.npm-global/lib/node_modules/@aws-amplify/cli/lib/index.js
- /home/migwell/.npm-global/lib/node_modules/@aws-amplify/cli/bin/amplify
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /home/migwell/.npm-global/lib/node_modules/@aws-amplify/cli/lib/init-steps/s2-initProviders.js:36:32
    at Array.forEach (<anonymous>)
    at initProviders (/home/migwell/.npm-global/lib/node_modules/@aws-amplify/cli/lib/init-steps/s2-initProviders.js:35:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.run (/home/migwell/.npm-global/lib/node_modules/@aws-amplify/cli/lib/commands/init.js:30:13)
    at async Object.executeAmplifyCommand (/home/migwell/.npm-global/lib/node_modules/@aws-amplify/cli/lib/index.js:288:9)
    at async executePluginModuleCommand (/home/migwell/.npm-global/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:164:5)
    at async executeCommand (/home/migwell/.npm-global/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:35:9)
    at async Object.run (/home/migwell/.npm-global/lib/node_modules/@aws-amplify/cli/lib/index.js:162:9) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/migwell/.npm-global/lib/node_modules/@aws-amplify/cli/lib/init-steps/s2-initProviders.js',
    '/home/migwell/.npm-global/lib/node_modules/@aws-amplify/cli/lib/commands/init.js',
    '/home/migwell/.npm-global/lib/node_modules/@aws-amplify/cli/lib/index.js',
    '/home/migwell/.npm-global/lib/node_modules/@aws-amplify/cli/bin/amplify'
  ]
}
```

**Comment by josefaidt** [comment]
Ah thank you for providing those details @multimeric and I'm glad to hear you're back up and running 🙏
